VACMS-9714: add scripts to update crisis number to 988
department-of-veterans-affairs/va.gov-cms pull request #10044
Opened 2022-08-03 20:15 UTC by JayDarnell

## Description

Using the CMS Content Audits as a reference: https://airtable.com/shrngt7aaXoIwAenS/tblO7nwMBRn1jWpcJ/viwUPS9GYFKTkAK5j?blocks=hide

This PR provides scripts to update the crisis hotline to 988 for the following airtable (above) sections:
- VAMC Facility
- VAMC System Operating Status
- VAMC Detail Page

Post release note: once these scripts have been run the remaining items not explicitly skipped in the issue description need to be manually checked/fixed. Some of these may have already been fixed.
- Alerts
- Resources and Support
- VAMC System Banner
- Benefits Detail Page

Closes #9714 

## Testing done

Manual testing. 

## QA steps

With terminal access, run the following commands:
- [ ] `drush scr ./scripts/content/VACMS-9714-paragraphs-crisis-to-988.php`
- [ ] `drush scr ./scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php`
- [ ] `drush scr ./scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php`
- [ ] Using the airtable link above, check content to be sure instances of 800-273-8255 were replaced with 988

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [x] Automated tests have passed.
- [x] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [x] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

2022-08-09 22:12 UTC, swirtSJW reviewed
These will work,   I would have liked to see a bit more of this around building up our script library to handle phone number replacement a little bit more generically, but I understand this was a complex case.

2022-08-09 22:12 UTC, swirtSJW commented on scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php
> +          'format' => 'rich_text',
Assumes format.  Might not be a risk, but seems like it might be.

2022-08-09 22:12 UTC, swirtSJW commented on scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php
> +              'format' => 'rich_text',
assumes format?

2022-08-10 02:32 UTC, swirtSJW reviewed
drush scr ./scripts/content/VACMS-9714-paragraphs-crisis-to-988.php
![image](https://user-images.githubusercontent.com/5752113/183795639-6b5194bf-6c77-45eb-9e58-15fabaf8d686.png)


drush scr ./scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php
![image](https://user-images.githubusercontent.com/5752113/183795808-de6b416b-0505-4112-8aa1-ef1e58069da7.png)

drush scr ./scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php

![image](https://user-images.githubusercontent.com/5752113/183795972-c45f6886-53c3-4a94-b5fc-158e7a2d7ebf.png)


Run time for all three was just under a minute.

Logging was successful, but a bit misleading.  Most of the nodes listed were not touched.
![image](https://user-images.githubusercontent.com/5752113/183796628-e088e421-4897-4090-953b-b34cff8c4e1f.png)

revision logs is showing good 
![image](https://user-images.githubusercontent.com/5752113/183797322-9fb189fb-4da0-4690-919c-40899430b1a8.png)


This is looking good Jay.    I am going to change the audit logging to only record what was updated rather than everything examined.  Makes it easier to audit and validate.

2022-08-10 02:44 UTC, swirtSJW commented on scripts/content/VACMS-9714-paragraphs-crisis-to-988.php
> +    $pids[] = $paragraph->id();
```suggestion

```

2022-08-10 02:44 UTC, swirtSJW commented on scripts/content/VACMS-9714-paragraphs-crisis-to-988.php
> +    ->log(LogLevel::INFO, '%current paragraphs progress. Paragraphs processed: %pids', [
```suggestion
    ->log(LogLevel::INFO, '%current paragraphs progress. Paragraphs updated: %pids', [
```

2022-08-10 02:44 UTC, swirtSJW commented on scripts/content/VACMS-9714-paragraphs-crisis-to-988.php
> +      $sandbox['updated']++;
```suggestion
      $sandbox['updated']++;
      $pids[] = $paragraph->id();
```

2022-08-10 02:44 UTC, swirtSJW commented on scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php
> +    ->log(LogLevel::INFO, 'VAMC Detail Page nodes: %current nodes phone numbers updated. Nodes processed: %nids', [
```suggestion
    ->log(LogLevel::INFO, 'VAMC Detail Page nodes: %current nodes phone numbers updated. Nodes updated: %nids', [
```

2022-08-10 02:44 UTC, swirtSJW commented on scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php
> +    $nids[] = $nid;
```suggestion
      $sandbox['updated']++;
      $nids[] = $nid;
    }

    unset($sandbox['nids_to_update']["node_{$nid}"]);
```

2022-08-10 02:44 UTC, swirtSJW commented on scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php
> +    $nids[] = $nid;
```suggestion
      $sandbox['updated']++;
      $nids[] = $nid;
    }

    unset($sandbox['nids_to_update']["node_{$nid}"]);
```

2022-08-10 02:44 UTC, swirtSJW commented on scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php
> +    ->log(LogLevel::INFO, 'VAMC System Operating Status nodes: %current nodes phone numbers updated. Nodes processed: %nids', [
```suggestion
    ->log(LogLevel::INFO, 'VAMC System Operating Status nodes: %current nodes phone numbers updated. Nodes updated: %nids', [
```

2022-08-10 02:47 UTC, swirtSJW commented on scripts/content/script-library.php
> + * Returns a serialized form of the node as JSON.
```suggestion
 * Saves a node revision with log messaging.
```

2022-08-10 03:03 UTC, swirtSJW commented on scripts/content/VACMS-9714-paragraphs-crisis-to-988.php
> +      '%pids' => implode(', ', $pids),
```suggestion
      '%pids' => empty($pids) ? 'None' : implode(', ', $pids),
```

2022-08-10 03:03 UTC, swirtSJW commented on scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php
> +      '%nids' => implode(', ', $nids),
```suggestion
      '%nids' => empty($nids) ? 'None' : implode(', ', $nids),
```

2022-08-10 03:04 UTC, swirtSJW commented on scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php
> +      '%nids' => implode(', ', $nids),
```suggestion
      '%nids' => empty($nids) ? 'None' : implode(', ', $nids),
```

2022-08-10 03:37 UTC, swirtSJW requested changes
The paragraph fix seems to not be working correctly.  When I ran it the first time, the report showed 936 paragraphs were updated.    I expected a subsequent run of the same script to say none were updated, but now shows 827   and all subsequent runs show 827 updated. 
![image](https://user-images.githubusercontent.com/5752113/183803670-31bd7e72-0ab6-4127-8113-ce8b80812117.png)

subsequent
![image](https://user-images.githubusercontent.com/5752113/183803365-d543ad15-b361-4eeb-8595-f38c6de65be9.png)

drush scr ./scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php
![image](https://user-images.githubusercontent.com/5752113/183805727-fb3e2a61-0ba6-48ce-ae2f-fd543266fcdd.png)
subsequent run shows 25 remaining (unexpected)
![image](https://user-images.githubusercontent.com/5752113/183806124-2ac0a2ff-e4d3-418a-bb3e-ac7e8721bc8d.png)
 Third run shows zero .

drush scr ./scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php
![image](https://user-images.githubusercontent.com/5752113/183807133-fb278e6f-7011-413d-aac7-fe3ce23b6c33.png)
Subsequent run shows 0 items updated. - The expected result 
![image](https://user-images.githubusercontent.com/5752113/183807340-75e44f27-0776-4642-bb0c-e0e87e9cbc34.png)

Good messaging 
![image](https://user-images.githubusercontent.com/5752113/183807366-30426b7c-37d4-4f97-9949-da2eac516ff7.png)



SO it is a mystery why `drush scr ./scripts/content/VACMS-9714-paragraphs-crisis-to-988.php` is not able to reduce the number of updates to zero but did reduce the number initially.  Something seems off there

A bit less of a mystery is why `drush scr ./scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php` takes multiple runs to get the number to zero.

2022-08-10 12:45 UTC, swirtSJW commented on scripts/content/VACMS-9714-paragraphs-crisis-to-988.php
> +      $paragraph->save();
```suggestion
      $paragraph->setSyncing(TRUE);
      $paragraph->setValidationRequired(FALSE);
      $paragraph->save();
```

A bit of throwing spaghetti at the wall here but I think these are needed anyway, even if they do not resolve the issue of not processing all paragraphs.

2022-08-10 14:19 UTC, JayDarnell commented on scripts/content/script-library.php
> + * Saves a node revision with log messaging.
Thanks for catching this copy/paste error @swirtSJW

2022-08-10 16:34 UTC, swirtSJW submitted a review, later dismissed
This is looking great.   Tests out great too.   Nice work @JayDarnell  and @christianmburk

2022-08-10 17:13 UTC, swirtSJW approved these changes
Approved, will merge as soon as tests pass.

2022-08-10 17:15 UTC, merged

2022-08-10 17:32 UTC, swirtSJW commented
Post release steps here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10141