VACMS-9956: add new section field to lovell menu items
department-of-veterans-affairs/va.gov-cms pull request #10110
Opened 2022-08-09 13:49 UTC by JayDarnell

## Description

Relates to #_issueid_. (or closes?)

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-08-11 21:15 UTC, swirtSJW requested changes
This is looking really good Jay.  Nice work.   I think there is just one hole that I see in the logic.

2022-08-11 21:21 UTC, JayDarnell commented on docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
> +          $entity->set('field_menu_section', $section_map[$section_id]);
Good catch. Thanks @swirtSJW

2022-08-12 02:43 UTC, swirtSJW reviewed
Looks great.  Nice work

2022-08-12 02:52 UTC, swirtSJW approved these changes
Tests out good
![image](https://user-images.githubusercontent.com/5752113/184276153-81dceeb6-c721-4cf1-9073-69999df94871.png)

![image](https://user-images.githubusercontent.com/5752113/184276170-613883aa-c0db-4a90-aef4-c4af2df1f858.png)


![image](https://user-images.githubusercontent.com/5752113/184276179-7c7fdeee-68ac-457a-bb17-d0d900a3dd64.png)

2022-08-12 02:53 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/184276244-a93f4518-332b-403e-aab2-f22284dedd90.png)

2022-08-12 02:53 UTC, merged