VACMS-10046: updates for link colors to meet WCAG 2.0 AAA contrast requirements.
department-of-veterans-affairs/va.gov-cms pull request #10279
Opened 2022-08-15 21:15 UTC by edmund-dunn

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10046

2022-08-15 23:48 UTC, ndouglas commented
```
  Component accessibility test
┌─────────┬──────────────────┬───────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────┬───────┐
│ (index) │        id        │  impact   │                                                description                                                │      target      │ nodes │
├─────────┼──────────────────┼───────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────┼───────┤
│    0    │ 'color-contrast' │ 'serious' │ 'Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds' │ [ '#edit-link' ] │   1   │
└─────────┴──────────────────┴───────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┴───────┘
    1) Login page has no detectable accessibility violations on load.


  0 passing (2s)
  1 failing

  1) Component accessibility test
       Login page has no detectable accessibility violations on load.:
     AssertionError: 1 accessibility violation was detected: expected 1 to equal 0
      at Context.eval (https://pr10279-jphvf6vnpqbuaeyfr8pdufwlni8aumug.ci.cms.va.gov/__cypress/tests?p=tests/cypress/support/index.js:9682:20)

```

Ironic.

https://pr10279-jphvf6vnpqbuaeyfr8pdufwlni8aumug.ci.cms.va.gov/cypress/screenshots/actual/accessibility/homepageAccessibility.spec.js/Component%20accessibility%20test%20--%20Login%20page%20has%20no%20detectable%20accessibility%20violations%20on%20load%20(failed).png

2022-08-18 16:42 UTC, ndouglas commented
Did this affect any pages _other_ than the PIV login page?  It'd be awesome to get test coverage of any pages this touched.

2022-08-18 20:43 UTC, swirtSJW commented
It looks like we have lost some things from our PR template related to testing and qa steps.

2022-08-18 21:54 UTC, ndouglas commented
Likely my fault.  I've been really inconsistent about that lately.

2022-08-23 13:21 UTC, swirtSJW requested changes
I added the PR template output back the description.  (likely happened due to using gitkraken or something that bypasses githubs native pr ui)

Overall I am puzzled by some of these changes.  They seem unrelated to the original issue.   But maybe my confusion would clear up when the QA steps are populated.

2022-08-23 13:21 UTC, swirtSJW commented on .ddev/providers/platform.yaml
> +# Consider using `ddev get platformsh/ddev-platformsh` (https://github.com/platformsh/ddev-platformsh) for more
I am not clear on what these changes do or how they relate to #10046.
In general I'd like to avoid lumping in unrelated changes into a pr because it makes tracking the history and reason difficult.

2022-08-23 13:21 UTC, swirtSJW commented on docroot/sites/default/settings/settings.local.php
> +$config['simplesamlphp_auth.settings']['activate'] = FALSE;
I am confused about what the change has to do with link colors.   settings.local.php  covers tugboat.  Which does not support CAG.  I am probably missing something.

2022-08-23 13:21 UTC, swirtSJW commented on docroot/sites/default/settings/settings.local.php
> +$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/local.services.yml';
I am not clear on why this is being added.

2022-08-23 13:52 UTC, ndouglas commented on docroot/sites/default/settings/settings.local.php
> +$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/local.services.yml';
We should probably have the above in an if-file-exists block, add `local.services.yml` to `.gitignore`, etc.

2022-08-23 14:02 UTC, ndouglas commented on docroot/sites/default/settings/settings.local.php
> +$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/local.services.yml';
Opened a PR here for this topic. https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10397

2022-08-25 15:08 UTC, edmund-dunn commented on docroot/sites/default/settings/settings.local.php
> +$config['simplesamlphp_auth.settings']['activate'] = FALSE;
I am removing these changes for settings.local.php.

2022-08-25 15:10 UTC, ndouglas commented on docroot/sites/default/settings/settings.local.php
> +$config['simplesamlphp_auth.settings']['activate'] = FALSE;
Yes, `settings.tugboat.php` is for Tugboat.  Does that not match what you're seeing in practice?

2022-08-25 15:11 UTC, ndouglas commented on docroot/sites/default/settings/settings.local.php
> +$config['simplesamlphp_auth.settings']['activate'] = FALSE;
>Also, how do I get changes I would like into the code base that will speed up my development?

I'm trying to improve this somewhat in this PR: 

https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10397

Pls weigh in.

2022-08-25 19:29 UTC, edmund-dunn commented on docroot/sites/default/settings/settings.local.php
> +$config['simplesamlphp_auth.settings']['activate'] = FALSE;
Weighed in.

2022-08-26 15:59 UTC, ndouglas commented on docroot/themes/custom/vagovclaro/assets/scss/components/_links.scss
> +      background-color: #e4eff9;
Should colors like this be added to the variables file?

(I don't know; just asking 🙂 )

2022-08-26 16:00 UTC, ndouglas reviewed
Does this need to be rebuilt (i.e. CSS regenerated)?

(I don't know about this either 🙁 )

2022-08-26 16:17 UTC, edmund-dunn commented
> 

No, this theme builds in the deployment process now. Tanner set that up which is BRILLIANT because there can be a stupid number of merge conflicts with theme files when you build locally.

2022-08-26 16:17 UTC, ndouglas approved these changes
LGTM 🙂

2022-08-26 16:36 UTC, swirtSJW commented on docroot/themes/custom/vagovclaro/assets/scss/components/_links.scss
> +      background-color: #e4eff9;
Agreed should these not be tokens?

2022-08-26 16:42 UTC, swirtSJW reviewed
Nothing objectionable, but like Nate I wonder and don't really know how we determine what color should be a token and what is hardcoded.

I also have a request to tighten up our QA steps a little.
> Randomly check edit and view pages to ensure that all links now use the colors specified.
This could have a lot of randomness to it and a lot more effort on the QAer to do that.  I presume that when you were testing your work, you looked at some specific pages.  If you list those in the QA steps then two things happen:
1. As a QAer I don't have to go hunting for locations where I can see the items in question
2. I can see what you did, so I am better able to spot a gap in the QA.

2022-08-26 17:28 UTC, edmund-dunn commented
> 

In this case, I DON'T want you looking at the same pages. It is supposed to be a check. I can tighten it up by saying choose five pages randomly and check 2 - 3 links on each page.

2022-08-26 17:30 UTC, edmund-dunn commented
> Nothing objectionable, but like Nate I wonder and don't really know how we determine what color should be a token and what is hardcoded.
I chose to hardcode to make sure I wasn't breaking anything anywhere else.

2022-08-26 18:54 UTC, edmund-dunn commented on docroot/themes/custom/vagovclaro/assets/scss/components/_links.scss
> +      background-color: #e4eff9;
I hardcoded these to prevent color regressions elsewhere.

2022-08-30 13:00 UTC, swirtSJW commented
> > Nothing objectionable, but like Nate I wonder and don't really know how we determine what color should be a token and what is hardcoded.
> 
> I chose to hardcode to make sure I wasn't breaking anything anywhere else.

I respect your caution.  However I don't think accruing tech/maintenance debt to avoid risk is the model we want to be chasing.
The model I like to follow is the idea that **You** are the expert on the topic of **this** ticket.  There will never be anyone who understands this ticket as well as you do, so you are the most likely to resolve maintenance debt at this key point in time.  If not, then someone else who understands it less than you do, will have to do it later, and the risk of m breaking something is even higher.  Yes there is an assumption that you are the expert, and if you are not, then you would have consulted with someone who was.  

This does not have to be a blocker on this ticket.  I will let you determine whether it should be or not.

2022-08-30 13:03 UTC, swirtSJW reviewed
I am seeing some odd commits that don't belong in this PR   Looks like a bad rebase maybe
![image](https://user-images.githubusercontent.com/5752113/187443729-5ec0844b-57af-4a8b-9f0e-a79c9bfa2417.png)

2022-08-31 03:09 UTC, swirtSJW approved these changes
commit history looks good now.  Thanks for cleaning that up.

2022-08-31 10:49 UTC, ndouglas approved these changes
Looks great!

2022-09-01 15:42 UTC, merged