VACMS-9920: Update the main CMS toolbar to meet accessibility standards
department-of-veterans-affairs/va.gov-cms pull request #10365
Opened 2022-08-22 15:22 UTC by edmund-dunn

## Description

Relates to #_9920_. (or closes?)

## Testing done
Manual visual testing on local machine

## Screenshots
![CleanShot 2022-08-22 at 08 14 22](https://user-images.githubusercontent.com/109987005/185957091-30511cfe-ce9d-494c-b0e1-04a5047ebd29.png)
![CleanShot 2022-08-22 at 08 17 50](https://user-images.githubusercontent.com/109987005/185957212-fb279347-94e0-4b48-a74f-470be27fe5de.png)

## QA steps

This will need to be checked on all environments to make sure the colors are correct and that the environment lable is displayed correctly.  

As super admin
1. Log in
   - [ ] Validate that commit hash, branch, or build version appear and environment label is present.

As editor
1. Log in
   - [ ] Validate that commit hash, branch, or build version DO NOT appear and environment label is present.

### Definition of Done

- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [x] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-08-23 12:41 UTC, laflannery approved these changes

2022-08-23 13:59 UTC, swirtSJW reviewed
Overall this is coming along good.   I think there are some things we can do to tighten up the logic and make it rely on only the environment names instead of also sniffing url.

2022-08-23 13:59 UTC, swirtSJW commented on .ddev/mutagen/mutagen.yml
> +# https://ddev.readthedocs.io/en/latest/users/install/performance/
unexpected changes.  Seem unrelated to the issue.

2022-08-23 13:59 UTC, swirtSJW commented on .ddev/providers/platform.yaml
> +#ddev-generated
Also unexpected / unrelated.   If these are critical changes can we get these as their own issue an PR combination.

2022-08-23 13:59 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $env = 'local';
I think this default is going to be confusing as dev and test are also going to get labeled as "local".
![image](https://user-images.githubusercontent.com/5752113/186172756-4afc8c30-276b-4d82-b457-8abd6e32b91b.png)

2022-08-23 13:59 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $env = 'local';
For reusability, readability, and ease of testing, can we move all these checks to a method like va_gov_backend_get_environement_name()  

I suggest instead of a bunch of ifs, maybe structure it like
```
$environments = [
  'ci.cms' => 'PR Environment',
  'demo.cms' => 'Demo Environment',
  'staging.cms' => 'Staging Environment',
...
];
```

And then just loop though the array so the actual check logic is only written once. and the method just returns the match.

2022-08-23 13:59 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    ->get('environment_indicator.env') === 'prod' || \Drupal::state()
If we have all our environments named, do we even need all the url sniffing above?   Could we just match ->get('environment_indicator.env') to what the text should be... or even use that name directly?

2022-08-23 13:59 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $env = 'local';
Actually I think disregard my suggestion above and use the one farther down to just rely on the predefined environment names.  This would use a single source of truth instead of having the color determined by env name and message determined by url matching.

2022-08-23 13:59 UTC, swirtSJW commented on docroot/sites/default/services/services.local.yml
> +# Local development services additions defined by VA.gov-CMS.
This seems unrelated and if needed, should go in a separate issue/PR pair.

2022-08-23 15:20 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $env = 'local';
Dig [this](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/sites/default/settings.php):

```$env_type = getenv('CMS_ENVIRONMENT_TYPE') ?: 'ci';```

That should give you `'prod'|'staging'|'dev'|'tugboat'|'local'`.  On Tugboat, the environment variable `TUGBOAT_PREVIEW_TYPE` will be either `pullrequest`, `branch` (for a demo, or for a base preview).

I personally prefer this approach (relying on environment variables) to one that uses the request host because in some cases the host might be `localhost` (some tests and other operations) or `default` (some `drush` commands, etc).  Also, with the amount of proxying we have going on, I'm suspicious of trying to derive _anything_ from request headers.  That might just be unreasonable degrees of suspicion.  And this is a very user-facing subject, so 🤷🏻‍♂️ .

We also have an environment discovery system in `va_gov_build_trigger` that encapsulates some of this logic in an OOP fashion [here](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php).  If we're missing distinctions there (like demo vs. PR), it might be nice to add that in.  Or open an issue for later to add it in 🙂

2022-08-23 18:31 UTC, cjterdi submitted a review, later dismissed
Looks great!

2022-08-25 14:43 UTC, edmund-dunn commented on .ddev/mutagen/mutagen.yml
> +# https://ddev.readthedocs.io/en/latest/users/install/performance/
This was gerenated by ddev. If there is a better way.place to commit these changes please advise.

2022-08-25 14:44 UTC, edmund-dunn commented on .ddev/providers/platform.yaml
> +#ddev-generated
this was generated by ddev. If tehre is a beter way/place to commit this please advise.

2022-08-25 14:47 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    ->get('environment_indicator.env') === 'prod' || \Drupal::state()
They are not all named as needed. We need to differentiate the tugboat environments.

2022-08-25 14:50 UTC, edmund-dunn commented on docroot/sites/default/services/services.local.yml
> +# Local development services additions defined by VA.gov-CMS.
I do need this for local development. When you have a minute if you can walk me though the procedure on how to get these types of fiels into the code base it would be appreciated.

2022-08-25 14:58 UTC, ndouglas commented on .ddev/mutagen/mutagen.yml
> +# https://ddev.readthedocs.io/en/latest/users/install/performance/
Just open a different PR for it IMHO.

2022-08-25 14:59 UTC, ndouglas commented on .ddev/providers/platform.yaml
> +#ddev-generated
Tim Cosgrove merged a PR recently to add this file, so after you update this branch it should be fine 🙂

2022-08-25 15:47 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $env = 'local';
The comps I received did not have dev of test. Since I wasn't aware of those two environments (oops) I will work with @cjterdi to get comps for them and make sure they are included.

2022-08-29 17:26 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $env = 'local';
I ended up going with the variables Nate recommended here. 
`$environment_label = '';
  $env = getenv('CMS_ENVIRONMENT_TYPE') ?: 'ci';
  switch ($env) {
    case 'prod':
      $environment_label = 'Production Environment';
      break;

    case 'staging':
      $environment_label = 'Staging Environment';
      break;

    case 'dev':
      $environment_label = 'Dev Environment';
      break;

    case 'tugboat':
      $tugboat = getenv('TUGBOAT_PREVIEW_TYPE');
      if ($tugboat === 'pullrequest') {
        $environment_label = 'PR Environment';
      }
      elseif ($tugboat === 'branch') {
        $environment_label = 'Demo Environment';
      }
      break;

    case 'local':
      $environment_label = 'Local Environment';
      break;

  }

  \Drupal::state()->set("environment_indicator.environment_label", $environment_label);
  \Drupal::state()
    ->set('environment_indicator.env', $env);`

2022-08-29 17:46 UTC, ndouglas requested changes

2022-08-29 17:46 UTC, ndouglas commented on READMES/cms-login.md
> +
Great addition!

2022-08-29 17:46 UTC, ndouglas commented on READMES/facilities-lovell.md
> +
Is this related?  I'm a little confused.

2022-08-29 18:01 UTC, ndouglas requested changes

2022-08-29 18:01 UTC, ndouglas commented on docroot/sites/default/services/services.local.yml
> +    auto_reload: true
It's back!

2022-08-29 18:12 UTC, laflannery reviewed
I am seeing issues with link colors.  Is that something I need to be worried about on this PR?
![image](https://user-images.githubusercontent.com/106678594/187269678-9aeaf057-17b5-4c93-a4d9-25b51fab62a1.png)

2022-08-29 18:13 UTC, ndouglas commented
@laflannery They should match the current production behavior, since #10279 isn't merged yet.

2022-08-29 18:14 UTC, edmund-dunn commented on READMES/facilities-lovell.md
> +
I am leaving this since it came from merging main

2022-08-29 18:14 UTC, edmund-dunn commented on composer.lock
> +            "version": "3.6.0",
fixed

2022-08-29 18:14 UTC, edmund-dunn commented on docroot/sites/default/services/services.local.yml
> +    auto_reload: true
fixed!

2022-08-29 18:15 UTC, edmund-dunn commented on READMES/cms-login.md
> +
Wonder where I got the idea!

2022-08-29 18:25 UTC, cjterdi commented
The hover state for the selected nav item is also off:
![Screen Shot 2022-08-29 at 11 14 22 AM](https://user-images.githubusercontent.com/16213503/187271717-57ccbb7d-55fb-42a8-867b-f77399491a21.png)

2022-08-29 18:30 UTC, ndouglas requested changes

2022-08-29 18:30 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    '#weight'             => 102,
Still seeing this formatting issue.

2022-08-29 18:30 UTC, ndouglas commented on docroot/sites/default/settings/settings.local.php
> +
We shouldn't see this.

2022-08-29 18:30 UTC, ndouglas commented on .ddev/mutagen/mutagen.yml
> +# https://ddev.readthedocs.io/en/latest/users/install/performance/
Sorry, missed this earlier.  Please exclude this file.

2022-08-29 18:31 UTC, cjterdi commented
@ndouglas I'll open a new ticket for a narrow width design review for the Title and head branch. Also the Menu position is off

2022-08-29 18:32 UTC, ndouglas commented
That's weird, @cjterdi, I saw this: 

![Screen Shot 2022-08-29 at 2 31 23 PM](https://user-images.githubusercontent.com/1318579/187272900-1b932eac-e799-442e-8853-391b9ec3b8cf.png)

I wonder if perhaps all the styles weren't yet computed when you looked (or weren't when I looked? 😓 )...

2022-08-29 18:38 UTC, cjterdi commented
I refreshed and now it seems fine...

2022-08-29 18:41 UTC, edmund-dunn commented on docroot/sites/default/settings/settings.local.php
> +
removed

2022-08-29 18:44 UTC, edmund-dunn commented on .ddev/mutagen/mutagen.yml
> +# https://ddev.readthedocs.io/en/latest/users/install/performance/
removed

2022-08-29 18:44 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    '#weight'             => 102,
fixed, again

2022-08-29 18:47 UTC, ndouglas approved these changes

2022-08-29 18:48 UTC, ndouglas commented
I have no remaining complaints, but I'll defer to @swirtSJW and @cjterdi's re-reviews 🙂

2022-08-29 18:56 UTC, cjterdi approved these changes

2022-08-29 19:20 UTC, swirtSJW reviewed
Looks good.
![image](https://user-images.githubusercontent.com/5752113/187281229-3e6294f2-201f-4b33-9e17-2d5ee9e9f5d4.png)


![image](https://user-images.githubusercontent.com/5752113/187281256-ba2e49af-9753-48e7-b808-f987cf99a256.png)

2022-08-29 19:21 UTC, swirtSJW approved these changes

2022-08-29 19:25 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      $environment_label = 'Production Environment';
This seems like a lot of code that could have been avoided by just using the environment name and appending the word "environment"  
![image](https://user-images.githubusercontent.com/5752113/187282010-74325dfd-150f-4e41-b73c-4d2831ef93e0.png)

2022-08-29 20:12 UTC, merged