VACMS-10421 Adds config and behat test data for VBA fields
department-of-veterans-affairs/va.gov-cms pull request #10608
Opened 2022-09-01 21:40 UTC by omahane

## Description

Closes #10421

## Testing done
Manually

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-09-06 16:00 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/js/script.js
> +})(jQuery, window.Drupal);
I think we want this newline at the end added back in.   I am not sure if this is from your ide or the process that generates this file from the es6 version.

2022-09-06 16:14 UTC, swirtSJW requested changes
The fields that are to be populated by the api, should be locked from editing by normal hmans
![image](https://user-images.githubusercontent.com/5752113/188685041-26067da5-9d0e-4552-a00b-fe8a08cf803c.png)

2022-09-06 16:16 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/188685513-b783aedb-f1e8-4319-8486-5e85ab41a101.png)

2022-09-07 02:57 UTC, omahane commented
![Screen Shot 2022-09-06 at 7 30 35 PM](https://user-images.githubusercontent.com/766573/188778535-6f7d4a43-6631-4415-baad-075b3add6a6e.png)
@swirtSJW I'm not sure how to remove the first block here. Any advice?

2022-09-07 02:58 UTC, omahane commented
@swirtSJW 
<img width="1840" alt="Screen Shot 2022-09-06 at 7 30 13 PM" src="https://user-images.githubusercontent.com/766573/188778759-0b450ecb-2558-469e-804b-19e28837dd87.png">
I made a change to this module, but the linter doesn't like the old names of the "private" functions.

2022-09-07 16:18 UTC, swirtSJW requested changes

2022-09-07 16:18 UTC, swirtSJW commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    'node_vba_facility_edit_form',
Suggesting that we don't need this since we already have the function `_va_gov_consumers_disable_non_vha_facilities_api_form_fields  ` and we just need to add node_vba_facility_edit_form and node_vba_facility to that function.

2022-09-07 16:18 UTC, swirtSJW commented on config/sync/core.entity_view_display.node.vba_facility.default.yml
> -  field_administration:
disregard, i found it but forgot to remove the comment.

2022-09-07 16:38 UTC, omahane commented on config/sync/core.entity_view_display.node.vba_facility.default.yml
> -  field_administration:
I'm not seeing `field_administration` under the `config/sync/core.entity_view_display.node.health_care_local_facility.default.yml` either.
Not sure whether it should have been there or not.

2022-09-07 18:49 UTC, omahane commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    'node_vba_facility_edit_form',
![Screen Shot 2022-09-07 at 1 47 09 PM](https://user-images.githubusercontent.com/766573/188954820-55114110-1292-40d2-998d-11885dd0c9dd.png)
When I comment out the code for `_va_gov_consumers_modify_vba_facility_fields()`, the editor form view is no longer correctly showing the external content view mode.

2022-09-07 18:57 UTC, omahane commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    'node_vba_facility_edit_form',
`_va_gov_consumers_modify_vba_facility_fields()` calls `_va_gov_consumers_disable_external_content_editing()` and passes the form to it, which means lines 303 - 316 act on the form. Otherwise, just having vba in the array later on doesn't do the thing we need it to for non-admins. (That's how I read the code, but this is also corroborated by the result of not using that function I added.)

2022-09-07 20:57 UTC, omahane commented
@swirtSJW I'm not seeing any regressions, after looking at the facilities as an editor and as an admin.

2022-09-07 22:03 UTC, swirtSJW approved these changes
Nice work simplifying the logic and making the function speak the truth.

Tests out good 
![image](https://user-images.githubusercontent.com/5752113/188991711-08ecbaf9-2cb6-42d7-8a2c-9744cdf7d178.png)

2022-09-07 22:03 UTC, merged