VACMS-10422 add vba fields to migration
department-of-veterans-affairs/va.gov-cms pull request #10679
Opened 2022-09-09 19:07 UTC by omahane

## Description

Closes #10422 

## Testing done

Manually

## Screenshots

A VBA Facility after migration on local dev
![Screen Shot 2022-09-09 at 2 06 24 PM](https://user-images.githubusercontent.com/766573/189425593-e8f19920-4845-4d09-a104-37ab0cba47f9.png)

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-09-09 22:11 UTC, swirtSJW requested changes
A couple thoughts in comments below.

Also as far as testing steps, you have done a good job accounting for what is expected.  However we haven't accounted for checking for the unexpected.  You are making changes to a process plugin that is used by other migrations that we know are migrating different formats of the data.  We want to make sure we didn't break that.  (please add testing steps to vailidate we did not break existing.

2022-09-09 22:11 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +    "/^0/"   => "",
Is this one needed? 
Using the line from clean_time()  it seems like it handles it accordingly for pm
![image](https://user-images.githubusercontent.com/5752113/189450940-855641f3-fccb-4232-ad93-e6c2cb24c7d5.png)

and this code handles it for am
![image](https://user-images.githubusercontent.com/5752113/189451805-070bb854-d5d6-48d5-9593-ee8d34ffff25.png)

2022-09-09 22:11 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +    "/\:/"   => "",
I don't think this one is needed either.  I think it gets handled in cleantime()

![image](https://user-images.githubusercontent.com/5752113/189452210-a7452c45-8410-4180-9b9f-a411cc9b5f3a.png)

Unless you are certain it is needed, we should remove it.  It is kind of a broad net that could alter a comment.

2022-09-12 21:28 UTC, omahane commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +      // Remove extra characters and make letters uppercase.
This has been removed.

2022-09-12 21:29 UTC, omahane commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +    "/\./"   => "",
This has been replaced by only 2 items with optional periods.

2022-09-12 21:30 UTC, omahane commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +    "/\:/"   => "",
Much of this is removed.

2022-09-13 02:27 UTC, swirtSJW requested changes
Looking good.  Only a CS issue.

2022-09-13 02:27 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +    "/to/"   => "-",
```suggestion
    "/\–/" => "-",
    "/to/" => "-",
```
I'm not sure how this is not getting codesniffer errors when you try to commit.  phpcs should be catching this.

2022-09-13 02:27 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +    "/a\.?m\.?/i" => "AM",
NICE

2022-09-13 19:25 UTC, swirtSJW commented
Migrations are running right now on the pr environment. 
Will QA shortly

2022-09-14 01:31 UTC, swirtSJW commented
This is testing out great except for some non-usa outliers with less than truthful data 
![image](https://user-images.githubusercontent.com/5752113/190038459-c4cf7137-a1d7-4959-a350-e93552d2364e.png)

2022-09-14 10:51 UTC, swirtSJW commented
I think we should go ahead and merge this, and then I will raise this all in [#cms-lighthouse](https://dsva.slack.com/archives/C02BTJTDFTN) because there are 2 external tickets that would have to happen before we could properly implement a country fix on the CMS.

2022-09-14 10:53 UTC, swirtSJW approved these changes
All this checks out great.  other than the out of country issue with the data which is something that will need to be resolved elsewhere first.

Thank you for your fantastic QA steps.  Well done.

2022-09-14 11:12 UTC, merged