VACMS-11285: Changed unflag text on VA form flags
department-of-veterans-affairs/va.gov-cms pull request #11335
Opened 2022-10-24 22:41 UTC by chri5tia

## Description

Closes #11285 

## Testing done
In progress

## Screenshots
In progress

## QA steps

In progress

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-10-25 16:41 UTC, jilladams commented
@chri5tia reviewed at https://pr11335-igbdfmlyainn5d1e9jrvybetpvkeptt7.ci.cms.va.gov/admin/content/va-forms/new-deleted, looks good.  

@davidmpickett  FYI: flag labels are updated and can be reviewed if you like. (Dave signed off on content changes in ticket and in sprint planning, so I don't think we need add'l review unless he wants to take another look.)

Also: as this is just content change and no functional change, Accessibility review wasn't in ACs and I think we can skip it.

2022-10-25 16:42 UTC, jilladams approved these changes
Approving based on QA, not code review. Still need a code review approval before merging.

2022-10-25 17:00 UTC, davidmpickett commented
I don't see an Actions drop down when I go to the Tugboat environment, so I'm not able to confirm if changes were made, but I suspect that might be a permissions issue for my drupal account or something? Seems like Jill handled this, but FYI for future design review on PRs.
![Screen Shot 2022-10-25 at 11 58 14 AM](https://user-images.githubusercontent.com/51967950/197836306-2b8da951-b448-45a8-bd57-168046dff607.png)

2022-10-25 18:11 UTC, chri5tia commented
@davidmpickett Thank you for your question. These changes apply to the last three tabs: New/Deleted, Changed Title, and Changed Filename. :)

2022-10-25 18:22 UTC, davidmpickett commented
@chri5tia My bad for cropping my screenshot too closely. This is what what I see on those three tabs. No action drop-down. No checkboxes for forms.
![Screen Shot 2022-10-25 at 1 17 22 PM](https://user-images.githubusercontent.com/51967950/197851028-38f6d46a-13f0-42f1-95da-3473b4d0fb07.png)

I do see the action drop-down on the main Form view tab
![Screen Shot 2022-10-25 at 1 21 25 PM](https://user-images.githubusercontent.com/51967950/197851664-37cb4964-1b2c-4378-b073-4702c5e2e879.png)

2022-10-25 19:12 UTC, jilladams commented
Interesting - Is there a permission concern here, in order to use the bulk actions? it's worth verifying Dave's permission levels vs. mine. (I think I'm an admin.) I don't think that's necessarily a blocker if this PR is otherwise ready, but would like to understand it.

2022-10-25 20:04 UTC, chri5tia commented
@jilladams @davidmpickett Thank you! I will take a look at those permissions, good catch.

2022-10-25 23:48 UTC, jilladams commented
We just did a bunch of user / permission poking for Homepage stuff, and I did randomly see 2 things in Prod just now, noting since I saw it: 
1. [DaveP's user](https://prod.cms.va.gov/user/4222/roles) is a Content Admin / Content Publisher, not a Drupal Admin (unlike mine, THE POWER). 
2. Content Publishers and Content Admins are allowed to unflag content in site permissions. (Meaning, the view bulk action permissions should match the flag permissions. )

2022-10-27 09:20 UTC, chri5tia commented
@davidmpickett Permissions should be fixed

2022-10-27 15:14 UTC, chri5tia commented
Labels updated per Blake's comment: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11285#issuecomment-1291191880

2022-10-27 16:28 UTC, chri5tia commented
Looks like there is still a permissions issue. Not sure if it is functional, but will need to work on this:

```
There was 1 failure:

1) tests\phpunit\Security\RolesPermissionsTest::testSecurityRolesPermissions with data set #2 ('content_admin', array('access administration pages', 'access files overview', 'access media overview', 'access taxonomy overview', 'access user profiles', 'access vamc_operating_statuse... pages', 'administer menu', 'administer nodes', 'administer taxonomy', 'break content lock', 'bypass node access', 'bypass workbench access', 'cancel smart date recur instances', 'clone block entity', 'clone block_content entity', 'clone field_config entity', 'clone file entity', 'clone media entity', 'clone menu entity', 'clone node entity', 'clone paragraph entity', 'create alert block content', 'create document media', 'create document_external media', 'create image media', 'create media', 'create promo block content', 'create url aliases', 'create vamc_system_billing_in...ontent', 'create vamc_system_medical_re...ontent', 'create vamc_system_register_f...ontent', 'create video media', 'delete alert revisions', 'delete all block content revisions', 'delete all media revisions', 'delete document revisions', 'delete document_external revisions', 'delete image revisions', 'delete promo revisions', 'delete video revisions', 'edit any document media', 'edit any document_external media', 'edit any image media', 'edit any video media', 'execute entity:break_lock node', 'execute publish_latest_revisi...n node', 'execute views_bulk_edit all', 'export tablefield', 'import tablefield', 'link to any page', 'make smart dates recur', 'manipulate all entityqueues', 'manipulate entityqueues', 'notify of path changes', 'override all authored by option', 'rebuild tablefield', 'reschedule smart date recur instances', 'revert alert revisions', 'revert all block content revisions', 'revert all media revisions', 'revert all taxonomy term revisions', 'revert document_external revisions', 'revert image revisions', 'revert promo revisions', 'revert video revisions', 'unflag changed_filename', 'unflag changed_name', 'unflag changed_title', 'unflag deleted', 'unflag new', 'unflag new_form', 'unflag removed_from_source', 'update any alert block content', 'update any media', 'update any promo block content', 'update media', 'use editorial transition approve', 'use editorial transition archive', 'use editorial transition arch...lished', 'use editorial transition crea..._draft', 'use editorial transition publish', 'use editorial transition review', 'use text format rich_text', 'use text format rich_text_limited', 'use workbench access', 'va gov deploy content build', 'view alert revisions', 'view all block content revisions', 'view all media revisions', 'view all taxonomy term revisions', 'view any unpublished content', 'view document revisions', 'view document_external revisions', 'view image revisions', 'view latest version', 'view node link report', 'view promo revisions', 'view sections in toolbar', 'view the administration theme', 'view unpublished paragraphs', 'view video revisions', 'view workbench access information'))
The permissions for the content_admin do not match the expected permissions.  Make the expected look like this, to get the test passing: 
 'access administration pages',
 'access files overview',
 'access media overview',
 'access taxonomy overview',
 'access user profiles',
 'access vamc_operating_statuses entity browser pages',
 'administer menu',
 'administer nodes',
 'administer taxonomy',
 'break content lock',
 'bypass node access',
 'bypass workbench access',
 'cancel smart date recur instances',
 'clone block entity',
 'clone block_content entity',
 'clone field_config entity',
 'clone file entity',
 'clone media entity',
 'clone menu entity',
 'clone node entity',
 'clone paragraph entity',
 'create alert block content',
 'create document media',
 'create document_external media',
 'create image media',
 'create media',
 'create promo block content',
 'create url aliases',
 'create vamc_system_billing_insurance content',
 'create vamc_system_medical_records_offi content',
 'create vamc_system_register_for_care content',
 'create video media',
 'delete alert revisions',
 'delete all block content revisions',
 'delete all media revisions',
 'delete document revisions',
 'delete document_external revisions',
 'delete image revisions',
 'delete promo revisions',
 'delete video revisions',
 'edit any document media',
 'edit any document_external media',
 'edit any image media',
 'edit any video media',
 'execute entity:break_lock node',
 'execute flag_delete_flagging flagging',
 'execute publish_latest_revision_action node',
 'execute views_bulk_edit all',
 'export tablefield',
 'import tablefield',
 'link to any page',
 'make smart dates recur',
 'manipulate all entityqueues',
 'manipulate entityqueues',
 'notify of path changes',
 'override all authored by option',
 'rebuild tablefield',
 'reschedule smart date recur instances',
 'revert alert revisions',
 'revert all block content revisions',
 'revert all media revisions',
 'revert all taxonomy term revisions',
 'revert document_external revisions',
 'revert image revisions',
 'revert promo revisions',
 'revert video revisions',
 'unflag changed_filename',
 'unflag changed_name',
 'unflag changed_title',
 'unflag deleted',
 'unflag new',
 'unflag new_form',
 'unflag removed_from_source',
 'update any alert block content',
 'update any media',
 'update any promo block content',
 'update media',
 'use editorial transition approve',
 'use editorial transition archive',
 'use editorial transition archived_published',
 'use editorial transition create_new_draft',
 'use editorial transition publish',
 'use editorial transition review',
 'use text format rich_text',
 'use text format rich_text_limited',
 'use views bulk edit',
 'use workbench access',
 'va gov deploy content build',
 'view alert revisions',
 'view all block content revisions',
 'view all media revisions',
 'view all taxonomy term revisions',
 'view any unpublished content',
 'view document revisions',
 'view document_external revisions',
 'view image revisions',
 'view latest version',
 'view node link report',
 'view promo revisions',
 'view sections in toolbar',
 'view the administration theme',
 'view unpublished paragraphs',
 'view video revisions',
 'view workbench access information',

Failed asserting that false is true.

/var/lib/tugboat/docroot/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:120
/var/lib/tugboat/docroot/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:55
/var/lib/tugboat/tests/phpunit/Security/RolesPermissionsTest.php:37
/var/lib/tugboat/docroot/vendor/phpunit/phpunit/src/Framework/TestResult.php:703
/var/lib/tugboat/docroot/vendor/phpunit/phpunit/src/Framework/TestSuite.php:620
/var/lib/tugboat/docroot/vendor/phpunit/phpunit/src/Framework/TestSuite.php:620
/var/lib/tugboat/docroot/vendor/phpunit/phpunit/src/Framework/TestSuite.php:620
/var/lib/tugboat/docroot/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:659
/var/lib/tugboat/docroot/vendor/phpunit/phpunit/src/TextUI/Command.php:235
/var/lib/tugboat/docroot/vendor/phpunit/phpunit/src/TextUI/Command.php:194
phpvfscomposer:///var/lib/tugboat/docroot/vendor/phpunit/phpunit/phpunit:97

FAILURES!
Tests: 637, Assertions: 1320, Failures: 1, Skipped: 4.
```

This is the failed test.

2022-10-27 22:12 UTC, davidmpickett commented
I just got on tugboat and can confirm I still don't have permissions for the form flags

2022-10-30 01:08 UTC, swirtSJW requested changes
See comments below.

2022-10-30 01:08 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> +  - 'execute flag_delete_flagging flagging'
Please tread lightly on perm changes.  We do not change perms just to suit QA.  Perm changes should almost always be accompanied by their own issue so that we can be intentional about it and track the decisions.

This PR is about altering flag names.  Lets keep it focused on that and create a separate issue to ponder and create perm changes.

2022-10-30 01:08 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> +  - 'use views bulk edit'
This is changing perms everywhere for this role.  We have a lot of bulk ops that we have not discussed opening up to this role.

2022-10-30 01:08 UTC, swirtSJW commented on composer.lock
> +        "drupal/libraries": 15,
The changes to the lock are unrelated to this PR and should not be here.

2022-10-30 01:10 UTC, swirtSJW commented
The phpunit failure is because you altered perms without altering the phpunit test that covers perms
![image](https://user-images.githubusercontent.com/5752113/198858171-dce3de0c-6746-4a7a-b1d2-a14e2c43211f.png)

It will stop failing when you remove the perm changes.

2022-10-31 16:55 UTC, jilladams commented
@swirtSJW I understand your point. But also: the ACs in the flag language ticket include making sure you're able to unflag an issue as a Content Admin, which is why that all got pulled in here.

2022-10-31 20:16 UTC, chri5tia commented
@jilladams @davidmpickett I am pushing this revision soon. In the meantime, either of you can log in as me in the tug boat PR environments. Slack me for the ino.

2022-10-31 20:38 UTC, jilladams commented
Logged in as me (Drupal admin): I see form bulk actions, and can succesfully remove a flag.
Logged in as Dave Picket (Content Admin, also now on PTO for 2 weeks starting today): I cannot see form bulk actions or remove flags.

Since we do not actually know who will own the workflow of removing flags besides Drupal Admins (A6 staff), and that's flagged as an Ownership question in our [Forms/Flags mural](https://app.mural.co/t/vagov6717/m/vagov6717/1666820558104/5b87095d4d16ad7c8e7825567bd84ff53be71724?sender=u252e7152800e3981889d1910), I'm ok updating the ACs to remove that piece, so we can get this PR merged.

2022-10-31 21:09 UTC, jilladams commented
> Logged in as me (Drupal admin): I see form bulk actions, and can successfully remove a flag. Logged in as Dave Picket (Content Admin, also now on PTO for 2 weeks starting today): I cannot see form bulk actions or remove flags.
> 
> Since we do not actually know who will own the workflow of removing flags besides Drupal Admins (A6 staff), and that's flagged as an Ownership question in our [Forms/Flags mural](https://app.mural.co/t/vagov6717/m/vagov6717/1666820558104/5b87095d4d16ad7c8e7825567bd84ff53be71724?sender=u252e7152800e3981889d1910), I'm ok updating the ACs to remove that piece, so we can get this PR merged.

Same behavior after most recent tugboat update, on https://pr11335-igbdfmlyainn5d1e9jrvybetpvkeptt7.ci.cms.va.gov/. 

FWIW also, as Dave, I _do_ see bulk actions on the original audit tab (`/admin/content/va-forms`)

2022-10-31 21:14 UTC, chri5tia commented
@jilladams I removed the permissions, so Dave would have to log in as me if he wanted to review this, but now that he's out it's a moot point and you already did, so that's good. :)

I noticed that also, that the form audit view has bulk actions for that user. Do you want me to reconcile why that works without changing permissions even though my views do not? Or should we go ahead and put that as part of the permission conversation separately?

2022-10-31 21:18 UTC, jilladams commented
Yep - [per Steve's comment above](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11335#discussion_r1008776094), let's roll it all into the new issue. Please cut that new ticket before you merge here, just so we don't lose it as a to do.

2022-10-31 22:17 UTC, chri5tia commented
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11404

2022-11-01 16:11 UTC, jilladams approved these changes
Confirmed: as Drupal admin, flag language is correct and I'm able to complete bulk actions for all 4 views that have the option.

2022-11-02 21:45 UTC, swirtSJW commented
> Yep - [per Steve's comment above](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11335#discussion_r1008776094), let's roll it all into the new issue. Please cut that new ticket before you merge here, just so we don't lose it as a to do.
@jilladams  my concern was more about the broadening the permissions on who has access to bulk operations.  That has bigger implications than just flags.

2022-11-02 21:46 UTC, swirtSJW approved these changes
Looks good.  QA pased.

2022-11-02 21:46 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/199608713-6631eb85-9590-4018-a126-b253a59fcfa0.png)

2022-11-02 21:46 UTC, merged