VACMS-11069: lovell listing page parity enforcement
department-of-veterans-affairs/va.gov-cms pull request #11356
Opened 2022-10-27 15:59 UTC by JayDarnell

## Description

Closes #11069 

## Testing done

Manual testing

## Screenshots

<img width="1481" alt="Screen Shot 2022-10-26 at 5 50 04 PM" src="https://user-images.githubusercontent.com/21045418/198324125-7dc551ea-1ef3-4a98-a982-5d9b42230c3e.png">

## QA steps  

As an admin user:

**Change the listing page for a non-lovell event**

1. Navigate to /node/50575/edit (DEA Take Back Day for VA Augusta health care)
2. Change the value for **Where should the event be listed?** to **VA Atlanta health care: Events** and save the node
3. No error should be thrown

**Change the listing page for a lovell event**

1. Navigate to /node/49920/edit (Test Event 2 Both)
2. Change the value for **Where should the event be listed?** to **Lovell Federal TRICARE health care: Events** and save the node
3. An error should be thrown and the **Where should the event be listed?** field should be highlighted in red.

**Change the listing page for a lovell story**

1. Navigate to /node/49929/edit (Test story for Both Lovell)
2. Change the value for **Where should the story be listed?** to **Lovell Federal TRICARE health care: Stories** and save the node
3. An error should be thrown and the **Where should the story be listed?** field should be highlighted in red.

**Change the listing page for a lovell news release**

1. Navigate to /node/49925/edit (Test A press release for BOTH LOVELL)
2. Change the value for **News releases listing** to **Lovell Federal TRICARE health care: News releases** and save the node
3. An error should be thrown and the **News releases listing** field should be highlighted in red.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

2022-10-27 19:49 UTC, omahane approved these changes
![Screen Shot 2022-10-27 at 2 46 11 PM](https://user-images.githubusercontent.com/766573/198384391-c1732e27-ac6e-4bab-b317-6381c7ca0b61.png)

I tested stories, events and news releases for Lovell and non-Lovell and received the results I was expecting. 

I saw the PHP_CodeSniffer warning about the foreach. Could you have used `foreach (iterable_expression as $value)` instead of `foreach (iterable_expression as $key => $value)` if you don't need the $key?

2022-10-27 21:09 UTC, omahane submitted a review, later dismissed
Working as described. Nice!

2022-10-28 12:57 UTC, swirtSJW requested changes
Some thoughts for consideration.

2022-10-28 12:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParity.php
> +  public $notSectionListMatch = 'The selected list page is not within the %value section.';
I think we need to add wording to this to tell them how to fix it.

2022-10-28 12:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParityValidator.php
> +      '1040',
Can we make it so these centrally managed in /va_gov_lovell/src/LovellOps.php   ?

2022-10-28 12:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParityValidator.php
> +    // Only enforce this validator for Lovell sections.
Since we are using inheritdoc we will need a broad comment here that describes the purpose of this validator.  I know what it is for now.... but when I re-read this in 6 months I will not.  It could either go here, or up in the docblock on line 9

2022-10-28 12:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  $bundles = [
```suggestion
  $list_bundles = [
```

2022-10-28 12:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  && (in_array($bundle, $bundles))
```suggestion
  && (in_array($bundle, $list_bundles))
```

2022-10-28 12:59 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParity.php
> +  public $notSectionListMatch = 'The selected list page is not within the %value section.';
consult Blake, UX can help here

2022-10-28 14:27 UTC, JayDarnell commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParityValidator.php
> +      '1040',
Oh geez, I completely forgot about LovellOps. Good catch!

2022-10-28 14:37 UTC, JayDarnell commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParityValidator.php
> +    // Only enforce this validator for Lovell sections.
I've expanded this substantially.

2022-10-28 14:39 UTC, JayDarnell commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  $bundles = [
I was a little torn about this one. The bundles we are checking at this point aren't the listing content types but the content types contained within those list pages. But I can see how this makes sense.

2022-10-28 20:44 UTC, JayDarnell commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParity.php
> +  public $notSectionListMatch = 'The selected list page is not within the %value section.';
I have updated this message to be explicit: 
`public $notSectionListMatch = 'Please select "%validSelection" for the current section: "%section".';`

2022-10-28 21:00 UTC, JayDarnell commented
I've updated the error messages to be explicit in terms of what selection IS valid:

<img width="1691" alt="Screen Shot 2022-10-28 at 4 37 34 PM" src="https://user-images.githubusercontent.com/21045418/198731397-58e35b87-4a7c-43e4-a887-75f03a5d003d.png">

<img width="1467" alt="Screen Shot 2022-10-28 at 4 38 51 PM" src="https://user-images.githubusercontent.com/21045418/198731427-3ad97ed1-e518-410b-9e97-e499a9809c83.png">

<img width="1700" alt="Screen Shot 2022-10-28 at 4 39 13 PM" src="https://user-images.githubusercontent.com/21045418/198731499-c3f629b6-bacf-4fd1-a3bc-09df0fd5700b.png">

2022-10-29 23:27 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  $bundles = [
Good point.  'list_item_bundles' would be even better.

2022-10-29 23:39 UTC, swirtSJW requested changes
Looking pretty good.   I made a couple minor teaks that I will commit and test.

2022-10-29 23:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  $list_bundles = [
```suggestion
  $list_item_bundles = [
```

2022-10-29 23:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  && (in_array($bundle, $list_bundles))
```suggestion
  && (in_array($bundle, $list_item_bundles))
```

2022-10-29 23:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParity.php
> + * Checks that the submitted value is a valid number.
```suggestion
 * Validates that a Lovell Section choice matches the listing page choice.
```

2022-10-29 23:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParity.php
> +   * The message that will be shown if the value does not match the section.
```suggestion
   * The message shown if the listing page value does not match the Lovell section.
```

2022-10-29 23:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  && (isset($fields['field_administration']))) {
Do we want to only add this constraint if the section is one of the Lovells?  I know you check it within the validator, but this would prevent it from even being added at all and called for the 99% of the time it does not apply.

2022-10-29 23:53 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParity.php
> +  public $notSectionListMatch = 'The selected list page is not within the %value section.';
One minor concern on this is that it assumes the error is on the listing choice and not on the section choice.  The error could be in either direction but this only directs them to one fix.

Its a tough call.  If we make it opinionated, it is easier to understand, but sometimes wrong.  If we make it less opinionated it may be harder to follow.

Please discuss with @BlakeOrgan .

2022-10-31 15:11 UTC, JayDarnell commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  && (isset($fields['field_administration']))) {
The validate function itself checks the term value and doesn't run validations if its not Lovell but I see no reason I couldn't simply check that value before applying the validator to the field.

2022-10-31 16:23 UTC, JayDarnell commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  && (isset($fields['field_administration']))) {
Abandoning this idea as I couldn't find any examples where this sort of thing has been done.

2022-10-31 19:14 UTC, JayDarnell commented
Here are the updated screenshots with a close approximation of @davidmpickett 's suggestion:

Event Example
<img width="1472" alt="Screen Shot 2022-10-31 at 3 12 07 PM" src="https://user-images.githubusercontent.com/21045418/199090964-3a112697-4faf-4a01-9cfd-f8e87fdc56ba.png">

News Release Example
<img width="1475" alt="Screen Shot 2022-10-31 at 3 12 52 PM" src="https://user-images.githubusercontent.com/21045418/199091026-10700027-7101-44cf-9140-88343d28e0a6.png">

Story Example
<img width="1464" alt="Screen Shot 2022-10-31 at 3 13 20 PM" src="https://user-images.githubusercontent.com/21045418/199091046-a6861657-23ac-4437-8394-8de6db74a8e9.png">

2022-10-31 22:30 UTC, BlakeOrgan commented
From a UX perspective, we shouldn't be presenting editors with options that we know are going to throw an error. The error text could be completely avoided if the listing options dropdown only showed relevant options based on the selected section.

If we're going to keep it the way it is though, I would suggest a single error message that is the same across the different error types with direction on how to fix the error. For example:

"The selected option is not part of the {insert section name} section. Please choose a different option or change the section settings to match."

Happy to talk through this more if needed as well.

2022-11-01 14:01 UTC, JayDarnell commented
Thanks @BlakeOrgan, in most cases the available list page options for a given user are all considered valid. This is an edge case that makes up part of the Lovell platycorn where we really want to enforce the list page explicitly matching the section. I'm updating my PR to reflect your suggested text which is a little simpler than Dave's suggestion while being a more robust than my original take.

Story:
 
<img width="1476" alt="Screen Shot 2022-11-01 at 9 59 21 AM" src="https://user-images.githubusercontent.com/21045418/199251372-77803b8b-ffd3-466c-8bf4-e79f81f94b89.png">

News Release

<img width="1460" alt="Screen Shot 2022-11-01 at 10 00 07 AM" src="https://user-images.githubusercontent.com/21045418/199251418-592b0897-2ff9-465e-9ed6-3a85b77ef402.png">

Event

<img width="1475" alt="Screen Shot 2022-11-01 at 10 00 24 AM" src="https://user-images.githubusercontent.com/21045418/199251451-ff45c184-50a2-4da1-a426-988edbce85fb.png">

2022-11-01 19:09 UTC, JayDarnell commented on docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParity.php
> +  public $notSectionListMatch = 'The selected list page is not within the %value section.';
I've implemented Blakes suggestion which was a halfway point between my original error message text and Dave's initial suggestion.

2022-11-01 20:53 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  && (isset($fields['field_administration']))) {
Sorry.  I was bieng dumb and saw the $fields and completely forgot that at this stage they do not have values .  Forgive my misdirection.

2022-11-01 21:12 UTC, swirtSJW approved these changes
Nice work Jay.
![image](https://user-images.githubusercontent.com/5752113/199342538-0d6e2ea2-0161-45af-990b-67baa826f22d.png)

2022-11-01 21:12 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/199342668-8152a425-c8a2-41b2-acd2-af4f6cfc2f69.png)

2022-11-01 21:13 UTC, merged