VACMS-10793: new table audit
department-of-veterans-affairs/va.gov-cms pull request #11387
Opened 2022-10-28 19:43 UTC by edmund-dunn

## Description
Closes #10793.

## Testing done
Tested locally. 

## Screenshots

## QA steps

Navigate to Admin Content. Click on Content Audit tool. You should see a new tab called "Tables(New)". Click on it. You will see a report of all the tables in the CMS which contains the Table ID, Published state, The table body, VA.gov url, Node link, Content type and Section. You should also be able to click on and download a csv version of the report. 

### Definition of Done

- [ ] Report is visible and functioning.
- [ ] CSV report downloads.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-10-29 23:18 UTC, swirtSJW requested changes
I tried to QA but there was a tugboat failure 
![image](https://user-images.githubusercontent.com/5752113/198855926-ce19a16a-4caf-4a3c-92b8-33c8884f0ccf.png)

A couple questions and changes

2022-10-29 23:18 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +    }
With using the foreach as a reference, the reference must be unset as soon as the foreach is exited or calamity may ensue.

2022-10-29 23:18 UTC, swirtSJW commented on config/sync/core.extension.yml
> +  views_event_dispatcher: 0
Shouldn't paragraph_usage be enabled here too?

2022-10-29 23:18 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +   * Pre render event handler.
It would be helpful to make this description describe what the intent is.

2022-10-29 23:18 UTC, swirtSJW commented on composer.json
> +        "drupal/paragraphs_usage": "^1.0",
To what extent does this module duplicate what entitity_usage module does?

2022-10-31 11:26 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +    }
And add a comment explaining why for the benefit of maintainers 😁 

Code's safe as-is but could blow up if the next hapless adventurer reuses the variable name.

2022-10-31 19:01 UTC, edmund-dunn commented on config/sync/core.extension.yml
> +  views_event_dispatcher: 0
No, that is just good for local development.

2022-10-31 19:01 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +    }
Turns out I didn't need the reference. I also added a comment.

2022-10-31 19:02 UTC, edmund-dunn commented on composer.json
> +        "drupal/paragraphs_usage": "^1.0",
This module is extremely limited in its usage. It only shows you where the paragraphs are used and that is it.

2022-11-01 14:28 UTC, edmund-dunn commented on composer.json
> +        "drupal/paragraphs_usage": "^1.0",
I also couldn't get entity_usage to show me the same information. I am leaving it in place to use for local development.

2022-11-01 14:38 UTC, ndouglas commented
![Screen Shot 2022-11-01 at 10 36 58 AM](https://user-images.githubusercontent.com/1318579/199259530-ba46144c-ea88-4d30-9f9a-bd0c9775dcb4.png)

Looks great, but I get a 403 attempting to download the CSV.

Guessing there's a new permission I don't have?

2022-11-01 14:41 UTC, laflannery commented
The CSV works for me, but it gets funny at line 109 and no longer shows the proper values:
![image](https://user-images.githubusercontent.com/106678594/199260543-1c61f8a4-fcc4-45d1-b078-1a39f057626b.png)

2022-11-01 18:49 UTC, laflannery approved these changes
CSV and audit look good to me now

2022-11-01 18:51 UTC, ndouglas approved these changes
Seeing CSV now, everything looks great as before 🙂 👍🏻

2022-11-01 19:23 UTC, merged

2022-11-03 22:12 UTC, swirtSJW commented on .tugboat/config.yml
> +        - drush cim -y
I don't think this should be here.