VACMS-11421: add tricare description to service taxonomy
department-of-veterans-affairs/va.gov-cms pull request #11446
Opened 2022-11-03 18:15 UTC by JayDarnell

## Description

Closes #11421 

## Testing done

Manual testing

## Screenshots

![Screen Shot 2022-11-03 at 2 12 26 PM](https://user-images.githubusercontent.com/21045418/199801984-8977de58-e71b-4be2-ad30-1d3fc979202b.png)

![Screen Shot 2022-11-03 at 2 12 54 PM](https://user-images.githubusercontent.com/21045418/199802012-f9887d38-12a8-43a2-a5f7-7164798d4d82.png)

![Screen Shot 2022-11-03 at 2 11 09 PM](https://user-images.githubusercontent.com/21045418/199801690-f2412ab3-c10c-4c1e-8725-048061f59632.png)

## QA steps

As an admin user
- [x] Visit /admin/structure/taxonomy/manage/health_care_service_taxonomy/overview/fields
- [x] field_tricare_description exists as a field on health_care_service_taxonomy
   - [x] label : TRICARE service description
   - [x] type: text plain long
   - [x] form location 
![image](https://user-images.githubusercontent.com/5752113/199572697-0ac2abed-a986-4fc0-b9ea-368357741f90.png)
   - [x] Widget Text area multiple rows
   - [x] cardinality 1
   - [x] not required
   - [x]  display location 
![image](https://user-images.githubusercontent.com/5752113/199573031-45f9e9e9-39c7-4c9a-af25-8f5dcf6b4c9f.png)

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

2022-11-03 21:05 UTC, swirtSJW approved these changes
Minor but necessary.  VA is fanatical about sentence casing.

2022-11-03 21:05 UTC, swirtSJW commented on config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_description.yml
> +label: 'TRICARE Service Description'
```suggestion
label: 'TRICARE service description'
```

![image](https://user-images.githubusercontent.com/5752113/199833519-161b57d3-08fb-4016-aaa3-5c5e0e46e6dd.png)


![image](https://user-images.githubusercontent.com/5752113/199833640-1951e9be-75f9-4fa6-ba0d-700cda376b5a.png)

2022-11-03 21:05 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
> +| Vocabulary | VA Services | TRICARE Service Description | field_tricare_description | Text (plain, long) |  | 1 | Text area (multiple rows) |  |
```suggestion
| Vocabulary | VA Services | TRICARE service description | field_tricare_description | Text (plain, long) |  | 1 | Text area (multiple rows) |  |
```
You'll need to fix this in the spec tool.

2022-11-03 21:06 UTC, swirtSJW requested changes
I meant this one instead

2022-11-03 21:17 UTC, omahane submitted a review, later dismissed
@JayDarnell This appears correct.
I'm unclear, however, why all but the "Description" field renders tags.
![Screen Shot 2022-11-03 at 4 14 10 PM](https://user-images.githubusercontent.com/766573/199835922-1a3e5549-630a-47ee-afe4-52f09e0c2c14.png)

2022-11-04 00:31 UTC, swirtSJW approved these changes

2022-11-04 00:31 UTC, merged