VACMS-8671: Removes problematic behavioral test.
department-of-veterans-affairs/va.gov-cms pull request #11486
Opened 2022-11-07 18:12 UTC by ndouglas

## Description

Closes #8671.

I added a Cypress test for basic functionality and also a PHPUnit unit test to hit some of the combinations.

Unfortunately, this block is a complicated class as far as mocking is concerned; it has multiple responsibilities, uses calls that conceal heavy reliance upon the Drupal service container, and the critical function we want to test is 60+ lines long.

As this is a PR that replaces a test, the impact should be minimal.  However, I did some _slight_ rewriting to support dependency injection rather than concealed `Drupal::<service>` calls, so the EWA block _does_ need some manual testing.

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-11-07 18:25 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/modules/va_gov_backend_http_client/src/VaGovBackendHttpClient.php
> -<?php
This is the one, officer.

2022-11-07 18:25 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/modules/va_gov_backend_http_client/va_gov_backend_http_client.info.yml
> -name: VA.gov Backend Http Client
Zapping this whole module.

2022-11-07 18:25 UTC, ndouglas commented on docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
> +use Drupal\Core\Utility\LinkGeneratorInterface;
Inject this rather than allow it to be retrieved via `\Drupal::service('link_generator')` call from within `\Drupal\Core\Link`.

2022-11-07 18:25 UTC, ndouglas commented on docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
> +use Drupal\va_gov_workflow_assignments\Service\EditorialWorkflowContentRepositoryInterface;
Use interface, not implementation.

2022-11-07 18:25 UTC, ndouglas commented on docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
> +      ->label();
Use calls to the entity type manager rather than magic methods on `$node`.

2022-11-07 18:25 UTC, ndouglas commented on docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
> +    return $this->linkGenerator->generateFromLink($link);
`Link::toString()` conceals a `Drupal::service(...)` call.

2022-11-07 18:25 UTC, ndouglas commented on tests/behat/Drupal/ContextBase.php
> -
Installing/uninstalling this module caused a cache clear that likely caused occasional issues with concurrent tests.

2022-11-07 18:25 UTC, ndouglas commented on tests/behat/features/content_editing.feature
> -  Scenario: Confirm that the EWA block URL is shown correctly.
This test can (and should) be shifted to Cypress.  Now's a good time to do it.

2022-11-07 18:25 UTC, ndouglas commented on tests/cypress/integration/behavioral/ewa_block.feature
> +Feature: CMS Users see the EWA block.
A partial replacement for the removed Behat test.  This is a good target for an integration test, but we can't effectively test all of the different possibilities because of the concurrent testing apparatus.

2022-11-07 18:25 UTC, ndouglas commented on tests/phpunit/Content/EntityMetaDisplayTest.php
> +
Unit test for the EntityMetaDisplay block.

This does not offer full coverage of the possibility space.  I can expand it further, but I think this should work in concert with a refactoring of the block.  I began work on this in another branch but it grew very quickly beyond the scope of the original ticket, and that's not great.

So, chiefly, I'm trying to match the scope of the original functional tests.

2022-11-09 14:30 UTC, ndouglas commented on docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
> -
This has finally been merged and shouldn't happen anymore.

2022-11-09 14:30 UTC, ndouglas commented on docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
> +    $links = array_slice($links, 1, 3);
Split off into a separate module.

2022-11-09 14:30 UTC, ndouglas commented on docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
> -
This method's calls that conceal calls to `\Drupal::service(...)`, so I've split them out, along with the above function, into a separate module that can be DI'ed more cleanly for unit testing.

2022-11-17 17:17 UTC, swirtSJW requested changes
Nate this all looks amazing.  

Nice work.

I am seeing one regression  on the section breadcrumb output
https://cms-xxmehkfeohdgqiwhxpwbeginhkgdld2s.ci.cms.va.gov/outreach-and-events/events/51074
![image](https://user-images.githubusercontent.com/5752113/202513257-cfc57ee8-943c-4f3d-ad82-1abeeab7efc6.png)

2022-11-17 18:20 UTC, ndouglas commented
Thank you @swirtSJW!

The problem was that I switched the entity breadcrumb building part to not stop after a certain number of links, but kept the logic assuming a certain length in the block itself.

I added a new behavioral test case that shows this behavior:

![Screen Shot 2022-11-17 at 12 41 00 PM](https://user-images.githubusercontent.com/1318579/202518541-4c1923a4-f0be-4c89-bf14-961e9e2ab2de.png)

And extended the existing test case to make sure we get the expected link text.  (For some reason, I didn't add that before).

I also added some stuff to the unit tests to check the logic against varying numbers of parent terms.

I'm going to do manual testing too once this is deployed with nodes with varying numbers of parent terms just to make sure it's right.

2022-11-17 19:42 UTC, swirtSJW approved these changes
Nice adding the test in real time to catch the discovered regression.

2022-11-17 19:46 UTC, swirtSJW commented
Still waiting on cypress test to complete but it is a go for launch if it passes.  Really fantiastic work Nate

2022-11-17 19:47 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/202544366-7c0f7bb4-49f2-42c2-a151-3f429fd0ea6f.png)

2022-11-17 19:47 UTC, merged

2022-11-17 20:28 UTC, ElijahLynn commented on tests/behat/Drupal/ContextBase.php
> -
YAY to see this removed!