VACMS-11160: Homepage permission hardening
department-of-veterans-affairs/va.gov-cms pull request #11534
Opened 2022-11-09 20:31 UTC by dsasser

## Description

Closes #11160

## QA steps
TBD

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-11-09 22:34 UTC, jilladams commented
I plan to step through the QA steps as various users, but probably tomorrow: 
* pickett = content admin
* set up Michelle as Homepage content publisher on Tugboat = https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/user/1342
* Joshua Tuscher is an OPIA section user: https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/user/30

2022-11-10 18:48 UTC, jilladams commented
QA pass: 
🔴 🟢 

## As jill.adams1@va.gov, Drupal admin
* Created a Benefit promo block: https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/block/205?destination=/admin/structure/block/block-content
* Created a News promo block: https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/block/206?destination=/admin/structure/block/block-content

**Tasks:**
- [ ] Rename `News promo` block type to `V2 Home page news spotlight`
- [ ] Rename `Benefit promo` block type to  `V2 Home page benefit promo`

## **As suzanne.middaugh@va.gov, OCTO Section User / Homepage Content Publisher role:**
- 🔴  As a `OCTO Section` user, I can add/edit/remove links on the new menus: 'Other Search Tools' and 'Popular on VA.gov'
  -  `You are not authorized to access this page.` on Menu management pages: 
    * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/menu/manage/other-search-tools
    * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/menu/manage/popular-on-va-gov 
- 🔴 As a user with the new role of `homepage content publisher` I can create new 'Benefits Promo' and 'News Promo' blocks.
  -  `You are not authorized to access this page.` on Menu management pages: 
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/block/block-content
- [X] 🟢 As a user with the new role of `homepage content publisher`, I can populate the new 'V2 Home page hero' and 'V2 Home page news spotlight' entityqueues.
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/entityqueue
<details><summary>Entity Queues Screenshot</summary>
  
  ![Screen Shot 2022-11-10 at 10 29 20 AM](https://user-images.githubusercontent.com/85581471/201177468-9643ab2a-82b6-433d-8a70-83a8e8fc4c8d.png)
  </details>

**Tasks:**
- [ ] Seems like a role permission is needed for Homepage Content Publisher on menus?

## As Joshua.Tuscher@va.gov, Content Publisher role / OPIA section user:
- 🔴 As a `Office of Public and Intergovernmental Affairs section` user, I can maintain/edit 'Benefits Promo' and 'News Promo' blocks.
  - `You are not authorized to access this page.` 
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/block/block-content
- 🔴 As an OPIA user I can distinguish existing Homepage entityqueues from new entityqueues, e.g. rename new to 'V2 Home page hero' and 'V2 Home page news spotlight'
  - `You are not authorized to access this page.` 
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/entityqueue
- 🔴  As an OPIA user I can distinguish existing Homepage blocks from new blocks, e.g. rename new to 'V2 Home page Benefit Promo' and 'V2 Home page news spotlight'
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/entityqueue
- [X] 🟢 Only `OCTO Section` users can add/edit/remove links on the new menus: 'Other Search Tools' and 'Popular on VA.gov' 
  -  `You are not authorized to access this page.` on Menu management pages: 
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/menu/

## As David.Pickett@va.gov,  content publisher / content admin role, All sections user
- [X] 🟢 As a content admin, I can only manage the entityqueues to which I have been assigned (only `Home page hub list`) 
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/entityqueue
<details><summary>Entity Queues Screenshot</summary>
  
![Screen Shot 2022-11-10 at 10 43 19 AM](https://user-images.githubusercontent.com/85581471/201179883-4e92bf7f-5845-48c1-9baa-84ed9c4ab57d.png)
  </details>

2022-11-14 20:00 UTC, dsasser commented
@jilladams 

These should be resolved now:

 Rename News promo block type to V2 Home page news spotlight
 Rename Benefit promo block type to V2 Home page benefit promo

2022-11-14 21:00 UTC, dsasser commented
@jilladams 
> As an OPIA user I can distinguish existing Homepage entityqueues from new entityqueues, e.g. rename new to 'V2 Home page hero' and 'V2 Home page news spotlight'
You are not authorized to access this page.
https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/entityqueue

Entityqueue access (/admin/structure/entityqueue) is not 'Section' (workbench access) aware. Drupal roles/permissions control access to all things entityqueue related. So to accommodate this AC we would need to give this user the 'Homepage content admin' permission.

2022-11-15 22:37 UTC, swirtSJW commented
@jilladams @dsasser I see that many of the QA steps call out an OCTO sections user.
![image](https://user-images.githubusercontent.com/5752113/202039183-ded3c48a-1511-47b0-b5f3-c0885ad53f3b.png)


OCTO is an upper level section.  Do we want to be more surgical in this by setting up another sub-section within OCTO like
OCTO -> Home page  the way all the other OCTO sub-sections granular to their function.

2022-11-15 22:43 UTC, swirtSJW reviewed
A few questions and possible concerns.

2022-11-15 22:43 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> +    - smart_date_recur
unexpected

2022-11-15 22:43 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> -    - node.type.banner
Why are these being removed from content admin?

2022-11-15 22:43 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> -    - va_gov_menu_access
Note to myself to double check this perm

2022-11-15 22:43 UTC, swirtSJW commented on config/sync/user.role.homepage_content_publisher.yml
> +id: homepage_content_publisher
We seem to be breaking with our existing patterns of creator and publisher.  The use of the term publisher might give the wrong impression because it does not limit to publishing.  homepage_manager might be better since it sets nor defies an existing pattern.

2022-11-15 22:43 UTC, swirtSJW commented on config/sync/user.role.homepage_content_publisher.yml
> +  - 'administer menu'
This one grants a fair amount of power since we have  a lot of menus this person should not be accessing.

2022-11-15 22:43 UTC, swirtSJW commented on config/sync/views.view.va_blocks_admin.yml
> +  page_3:
Goes against our Views style guide of using meaningful names for views displays instead of the defaults.

2022-11-15 22:43 UTC, swirtSJW commented on config/sync/system.menu.other-search-tools.yml
> +      193: '193'
See my earlier comment about how setting this to an upper level taxonomy term (OCTO) seems like it might be too broad.  Do we want to be more surgical with a new term under OCTO.

2022-11-16 16:33 UTC, dsasser commented on config/sync/user.role.content_admin.yml
> +    - smart_date_recur
I agree, it is unexpected, and it I didn't catch this before committing. However, every time I export this role, this permission is added, so I have to look into why that is, or simply exclude it--but that will cause the active and staged configs to always differ perhaps.

2022-11-16 16:34 UTC, dsasser commented on config/sync/user.role.content_admin.yml
> -    - node.type.banner
I have no idea, this an export after a clean import. I'll investigate as per the other smart_date_recur permission.

2022-11-16 16:42 UTC, dsasser commented on config/sync/user.role.content_admin.yml
> -    - va_gov_menu_access
This may have occurred because I was toggling the va_gov_menu_access module off to test access, I'll clean this up.

And, so it's not completely forgotten by me: there is a "bug" with the va_gov_menu_access module (or maybe it is a feature?). Just by enabling the module, it restricts menu access to those that would otherwise have it. This occurs because Drupal is doing an `andIf` conditional with access between user permissions and custom permissions. In the access() method of Drupal\va_gov_menu_access\Access, we have:

```
  public function access(Route $route, RouteMatchInterface $route_match, AccountInterface $account) {
    // Restrict admin menu access.
    if ($this->permsService->hasAdminRole()
    || $account->hasPermission('administer cms custom menu access')) {
      return AccessResult::allowed();
    }

    return AccessResult::forbidden();
  }
```

So if the user is not an admin, nor has the custom `administer cms custom menu access` permission (despite having administer menu permissions), they are denied access to the admin/structure/menu page. Again, I'm not sure if this is by design, but wanted to flag it in case it isn't. If needed, I can open a ticket for further investigation here.

2022-11-16 16:42 UTC, dsasser commented on config/sync/user.role.homepage_content_publisher.yml
> +id: homepage_content_publisher
That makes sense to me.

2022-11-16 16:45 UTC, dsasser commented on config/sync/user.role.homepage_content_publisher.yml
> +  - 'administer menu'
Yeah this was me trying to figure out how to give the expected menu admin experience. Interestingly, the `administer menu` permission is nullified by the va_gov_menu_access module simply being enabled (see my other comment on the subject).

That said, we changed the requirements mid-stream and now we are not going to be giving users access to the main menu admin page, so I'll be pulling out these perms. Thanks for flagging these.

2022-11-16 16:46 UTC, dsasser commented on config/sync/views.view.va_blocks_admin.yml
> +  page_3:
Yeah it does, but I was following the pattern of the view I was modifying. Would you be open to creating a separate ticket to resolve all of the views (or at least all the displays on this view) to match the expected pattern?

2022-11-16 16:48 UTC, dsasser commented on config/sync/system.menu.other-search-tools.yml
> +      193: '193'
Noted, but I think that was intentional. I will be bringing this to the team today.

2022-11-16 17:01 UTC, dsasser commented
@wesrowe @jilladams 

Removed these ACs due to no longer needing menu admin permissions--it was decided the menus will be managed by Public Websites, who have admin access.

- [ ] As a `OCTO Section` user, I can add/edit/remove links on the new menus: 'Other Search Tools' and 'Popular on VA.gov'
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/menu/manage/other-search-tools
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/menu/manage/popular-on-va-gov 
- [ ] Only `OCTO Section` users can add/edit/remove links on the new menus: 'Other Search Tools' and 'Popular on VA.gov'

2022-11-16 18:36 UTC, dsasser commented on config/sync/user.role.content_admin.yml
> +    - smart_date_recur
Actually, this is expected after inspecting the current permissions of the content_admin, we see: `cancel smart date recur instances`

This change on line 35 is adding the smart_date_recur module as a dependency, because the permission comes from that module. I'm unsure why this was not originally here, but it is a valid dependency for the permission.

2022-11-16 18:40 UTC, dsasser commented on config/sync/user.role.content_admin.yml
> -    - node.type.banner
In commit f0edb3939517ad318ff319411c4a48e974f2494b, we see the removal of node permissions such as `create banner content`. I surmise that was either surgically done in the YAML, instead of in the UI (thus the dependency remaining until now), or somehow, Drupal failed to calculate the correct dependencies at that time. Either way, there are no banner permissions any longer for content admins, so I see this as a valid removal of a former dependency.

2022-11-16 18:45 UTC, dsasser commented on config/sync/user.role.content_admin.yml
> -    - va_gov_menu_access
This is another valid module dependency getting removed as I see it. The va_gov_menu_access provides a single permission, `administer cms custom menu access`, which content admins do not have, so there is no need for the va_gov_menu_access module to be a dependency on this role.

2022-11-16 18:53 UTC, dsasser commented on config/sync/system.menu.other-search-tools.yml
> +      193: '193'
No direct answer on this as of yet.

However, since we only want admins to control the menu, we can remove all section control from the menus, and rely on Drupal permissions alone for the time being. A fast-follow ticket could be created to circle back to this if the approach is not acceptable permanently.

I realize this is a departure from the pattern of every menu having some workbench access control. But I am not aware of how to accommodate admin only access by way of applying a Section (question posed in [Slack](https://dsva.slack.com/archives/C03NSH4SLQY/p1668623083545979?thread_ts=1668617632.226869&cid=C03NSH4SLQY)).

2022-11-16 18:59 UTC, dsasser commented on config/sync/views.view.va_blocks_admin.yml
> +  page_3:
Actually, it is a quick change to make on my end, so I'll update it for this display, but I don't feel comfortable updating all the machine names in this View to match the views styleguide. Perhaps we need (or already have) a ticket for auditing the state of views against the views styleguide?

2022-11-16 19:05 UTC, dsasser commented on config/sync/user.role.homepage_content_publisher.yml
> +id: homepage_content_publisher
Changed to homepage_manager.

2022-11-16 23:12 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> +    - smart_date_recur
Thanks for looking into it.

2022-11-16 23:17 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> -    - va_gov_menu_access
That was by design.  editors were not supposed to have access to menus, it was part of intentional menu hardening.

2022-11-16 23:20 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> -    - va_gov_menu_access
Note `permsService->hasAdminRole()`  includes  both admin and content_admin
while `permsService->hasAdminRole(TRUE)`  does not include content_admin.

2022-11-16 23:24 UTC, swirtSJW commented on config/sync/views.view.va_blocks_admin.yml
> +  page_3:
Yah good call... no need to fix the ones that already slipped through.

My main concern is if we ever target these views with custom code, the 'page_3' is not very meaningful.  And it seems like this view might have the potential for targeting with custom code.

2022-11-16 23:29 UTC, swirtSJW reviewed
Is this supposed to be here? 
![image](https://user-images.githubusercontent.com/5752113/202317116-7820ad1b-31a8-4559-999f-c62fe575926b.png)

2022-11-16 23:33 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> -    - node.type.banner
Interesting.  It might be one of those cases where it takes a second export to get everything in sync ... or bad practices.  ;)

2022-11-16 23:37 UTC, swirtSJW commented on config/sync/views.view.va_blocks_admin.yml
> +  page_3:
I don't think this got upddated.

2022-11-17 00:26 UTC, dsasser commented
> Is this supposed to be here? ![image](https://user-images.githubusercontent.com/5752113/202317116-7820ad1b-31a8-4559-999f-c62fe575926b.png)


> Is this supposed to be here? ![image](https://user-images.githubusercontent.com/5752113/202317116-7820ad1b-31a8-4559-999f-c62fe575926b.png)

Oof, how did that get there? Removed.

2022-11-17 00:27 UTC, dsasser commented on config/sync/views.view.va_blocks_admin.yml
> +  page_3:
You are correct, I failed to push my last commit. It's updated now, thanks for catching that.

2022-11-29 23:04 UTC, jilladams commented
Test pass: closer! 

## as suzanne.middaugh@va.gov (Homepage Manager role, Vet Center section permissions)
As a Octo section user / non, and Homepage Manager / non, and content admin verify positive / negatives:
- [X] 🟢 As a user with the new role of `Homepage Manager` I can create new 'V2 Home page hero' and 'V2 Home page news spotlight' blocks.
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/block/add?destination=/admin/content/v2-homepage
  * **Note:** Homepage Manager user will only be able to publish _to_ the Sections where they have Workbench permissions. So: for homepage, they'll need to be OPIA users. (Which I think they just will be, by the nature of who gets given the role.)

- [X] 🟢 As a user with the new role of `Homepage Manager`, I can populate the new 'V2 Home page hero' and 'V2 Home page news spotlight' entityqueues.
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/entityqueue
  * As this user, I can also only edit the content of blocks that match my Section permissions. 
  * **Note:I** can only select 1 block to appear in each entityqueue. To change blocks, I have to remove the one that's present and add the new one. 

- [X] 🟢 As a `Homepage Manager`  I can distinguish existing Homepage entityqueues from new entityqueues, e.g. rename new to 'V2 Home page hero' and 'V2 Home page news spotlight'
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/entityqueue

## As Joshua.Tuscher@va.gov (Content Publisher role, OPIA section)
- [ ]  🟡  As an OPIA user I can distinguish existing Homepage blocks from new blocks, e.g. rename new to 'V2 Home page Benefit Promo' and 'V2 Home page news spotlight'
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/content/v2-homepage
  * Renaming = 🟢 
  * From this page, you can't tell which type of block is which (benefit vs. promo), unless it's in the block description. We may want to add a column for Block type? (Can ticket separately, I don't think this is important right now). 
  * This user _can_ see those 2 types of blocks, and _cannot_ see any other types of blocks, e.g for the old Home page promos entityqueue. (In Staging: this actual user cannot see entity queues or block administration pages. So what we've done so far is an improvement.)
  * So: I'm not sure whether to call this done. If we fix the issue below, probably can call it done.
 
- [ ] 🔴  As a `Office of Public and Intergovernmental Affairs section` user, I can maintain/edit 'V2 Home page hero' and 'V2 Home page news spotlight' blocks.
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/content/v2-homepage
  * As Joshua.Tuscher@va.gov, with OPIA section and Content Publisher role, I can see this page. I can't modify the blocks: 
 
<img width="1403" alt="Screen Shot 2022-11-29 at 2 50 56 PM" src="https://user-images.githubusercontent.com/85581471/204665730-028aac72-c8f7-478b-8d16-4ff8392f3d9a.png">

## As David.Pickett@va.gov (Content Admin / Content Publisher role, all sections )

- [X] 🟢 As a content admin, I can only manage the entityqueues to which I have been assigned (only `Home page hub list`) 
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/structure/entityqueue

2022-11-29 23:29 UTC, dsasser commented
@jilladams 

> 🔴 As a Office of Public and Intergovernmental Affairs section user, I can maintain/edit 'V2 Home page hero' and 'V2 Home page news spotlight' blocks.

This is occurring because Drupal is combining (using and-if rules) Drupal Role based permissions, and custom permissions (workbench access ie Section). The Role based permissions (none granted for the content publisher currently, only for homepage admins) are not permitting editing the new blocks. As a test, I gave `content publisher` the below permissions, and edit access became available (using Joshua.Tuscher@va.gov). So the current implementation here in this PR results in: Drupal Role Access (for content publishers): Denied; Workbench Access: Allowed (depending on section)

<img width="1790" alt="Screen Shot 2022-11-29 at 3 18 49 PM" src="https://user-images.githubusercontent.com/221539/204670018-af06c6fc-3cbb-4396-a338-caa96ea04350.png">

So we need to think through what Drupal Roles should have the edit block permission for the new blocks (currently, just `homepage manager` has these block permissions). Note that content publishers currently have permission to create & edit Alert and Promo blocks, so if we decided to give content publishers additional block access, it would be aligned with current practice). I just need to know which Drupal role(s) we should be giving the block edit permissions.

2022-11-29 23:33 UTC, dsasser commented
@jilladams 

> This user can see those 2 types of blocks, and cannot see any other types of blocks, e.g for the old Home page promos entityqueue. (In Staging: this actual user cannot see entity queues or block administration pages. So what we've done so far is an improvement.)

Seeing only these 2 types of blocks is expected, even if the user has access to other blocks. This View is restricting display of only the two new block types.

2022-11-30 00:09 UTC, jilladams commented
Do I understand correctly that if we gave Joshua.Tuscher@va.gov the Homepage Manager role, this problem would be solved?

2022-11-30 00:36 UTC, dsasser commented
> Do I understand correctly that if we gave [Joshua.Tuscher@va.gov](mailto:Joshua.Tuscher@va.gov) the Homepage Manager role, this problem would be solved?

That is correct.

2022-11-30 16:38 UTC, dsasser commented
@jilladams 

> From this page, you can't tell which type of block is which (benefit vs. promo), unless it's in the block description. We may want to add a column for Block type? (Can ticket separately, I don't think this is important right now).

That is true. And this Views display doesn't currently meet views styleguide, which was mentioned in a previous comment by Steve. So with that, I'll update this View to both meet the views styleguide, and provide a meaningful "block type" column to accommodate ACs.

2022-11-30 17:51 UTC, jilladams commented
> > Do I understand correctly that if we gave [Joshua.Tuscher@va.gov](mailto:Joshua.Tuscher@va.gov) the Homepage Manager role, this problem would be solved?
> 
> That is correct. That is one approach, another would be utilizing existing Drupal roles such as the content publisher.

@mmiddaugh we need a decision point here, to get this over the finish line. In order to allow OPIA users to edit Homepage News & Benefit promo blocks, we have 2 options: 

1. Give Content Publishers or Content Admins the rights to modify blocks. This would allow OPIA users with Content Publisher / Content Admin roles to modify blocks. (Joshua Tuscher user has Content publisher role in prod.)
2. For any OPIA users who need to modify the homepage blocks, give them the Homepage Manager role. 

Dave has previously said he doesn't want to fuss with which OPIA users have permissions to do which tasks -- that we should give all OPIA section users the same access to do this work, and let them manage that internally as needed. That in mind: can you help us work out which way to go here?   (FYSA, @wesrowe )

2022-11-30 19:18 UTC, ndouglas commented
@laflannery @JayDarnell  These accessibility failures ^ might have crept into `main` recently.  Not sure how, since the test should've caught them.  Do you think it might be due to the PR merged earlier today?  Do these look legit/related?  Is this something that can be fixed quickly or do we need a revert?

2022-11-30 19:59 UTC, jilladams commented
Decisions were made in Slack re: the failing OPIA block management cases / how to mitigate: https://dsva.slack.com/archives/C03NSH4SLQY/p1669830717907119

2022-11-30 20:09 UTC, laflannery commented
@ndouglas Those axe issues are not issues - I don't really understand where they are coming from.
- If I run the page through my axe browser plugin I don't get those, so that's weird. The results should be the same
- If I manually inspect, the text/foreground color is `#212121` for all 3 elements not `#545454` which is what is being reported. And that color combined with the background does pass requirements
So I'm really not quite sure what's happening here, I will also say that a couple weeks ago my daily scan (which also uses axe-core) reported a error that apparently had been existing for months, then the next day, did not report it again even though I hadn't resolved it yet.

2022-11-30 22:57 UTC, dsasser commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      // phpcs:disable
These were PHPCS errors unrelated to my changes:

```
----------------------------------------------------------------------
FOUND 1 ERROR AND 7 WARNINGS AFFECTING 8 LINES
----------------------------------------------------------------------
  453 | ERROR   | unserialize() is insecure unless allowed classes
      |         | are limited. Use a safe format like JSON or use the
      |         | allowed_classes option.
  459 | WARNING | #options values usually have to run through t() for
      |         | translation
  460 | WARNING | #options values usually have to run through t() for
      |         | translation
  461 | WARNING | #options values usually have to run through t() for
      |         | translation
  462 | WARNING | #options values usually have to run through t() for
      |         | translation
  463 | WARNING | #options values usually have to run through t() for
      |         | translation
  594 | WARNING | Unused variable $bundle.
 1341 | WARNING | Unused variable $field_name.
```

I fixed all but the unserialize() one since that would require a lot of testing to ensure that all possible classes were in the allow list, so I toggled phpcs off for that line.

2022-11-30 23:18 UTC, dsasser commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function va_gov_backend_entity_type_build(array &$entity_types) {
Normally I'm not a fan of access control overrides unless there is a good reason. In this case, I think the reason is valid.

This solves: viewing the *label* of a block content type config entity without having to have 'administer blocks' permission (the label in this case is the 'block type' which is an additional column added to the new V2 Homepage View). This is because of a [change to fold the new 'view label' and 'view' operation together as 'view'](https://www.drupal.org/node/2661092). So a user needs 'view' permissions for the given entity type, just to see the label. In the case of custom block type entities (the config entity of a custom block, eg: the bundle), only the 'administer blocks' permission grants the 'view' access. 

Note that the change record implementing the 'view label' access change specifically says:

> If an entity type requires this distinction between 'view label' and 'view' entity access, a custom entity access handler needs to be provided for that entity type and the value of the viewLabelOperation needs to be overridden to TRUE.

I accomplished this per the example given in the change record. Note there are [examples in core performing ](https://git.drupalcode.org/project/drupal/-/blob/9.5.x/core/modules/user/src/UserAccessControlHandler.php#:~:text=21-,/**,%7D,-40)a custom access check for 'view label' and simply returning *allowed*. My point being, I think this is an established pattern in core and contrib.

2022-12-01 21:46 UTC, jilladams approved these changes
## As Joshua.Tuscher@va.gov (Content Publisher role, OPIA section)
- [X]  🟢   As an OPIA user I can distinguish existing Homepage blocks from new blocks, e.g. rename new to 'V2 Home page Benefit Promo' and 'V2 Home page news spotlight'
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/content/v2-homepage
  * Block type column is present, WOO
 
- [X] 🟢 As a `Office of Public and Intergovernmental Affairs section` user, I can maintain/edit 'V2 Home page hero' and 'V2 Home page news spotlight' blocks.
  * https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/admin/content/v2-homepage
  * As Joshua.Tuscher@va.gov, with OPIA section and Content Publisher role, I can see, edit, save blocks that appear the view. WOOO


Donezo!

2022-12-01 22:57 UTC, swirtSJW requested changes
This is looking good @dsasser   I have two minor changes and a bigger one.   If you want to talk about the bigger one, let me know.   It doesn't have to be a blocker but I'd like you to consider it.

2022-12-01 22:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +use Drupal\Core\Config\Entity\ConfigEntityType;
Minor:  Can we get these alpha sorted so they nest in with the other Drupal items?

2022-12-01 22:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  // entities.
Minor: I think this is a good solution @dsasser   
Can you summarize a wee bit of the "why"  that you explained in the git comment above and put in in a code comment for our future selves?

2022-12-01 22:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function va_gov_backend_entity_type_build(array &$entity_types) {
Can this be done in an event, as opposed to a hook?  We are trying to do our best to get off of hooks. It is not always possible, but I think this one should be.
docroot/modules/custom/va_gov_backend/src/EventSubscriber
\Drupal\core_event_dispatcher\EntityHookEvents::ENTITY_TYPE_BUILD


That lets us get this into a meaningfully named event subscriber and  keeps from further bloating the va_gov_backend.module which is already over 2000 lines.

2022-12-02 00:15 UTC, dsasser commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function va_gov_backend_entity_type_build(array &$entity_types) {
Makes sense. I have moved the logic to an event subscriber.

2022-12-02 00:20 UTC, dsasser commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +use Drupal\Core\Config\Entity\ConfigEntityType;
I moved these from va_gov_backend.module to the EntityEventSubscriber and alpha sorted in them there.

2022-12-02 02:44 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +use Drupal\Core\Config\Entity\ConfigEntityType;
If you are using VScode, I highly reccommend this plugin  to help keep these things tidy.
![image](https://user-images.githubusercontent.com/5752113/205203112-c368c162-74ea-432b-8b67-51d604bcc79d.png)

2022-12-02 03:04 UTC, swirtSJW reviewed
I am only through the first few QA items but I am seeing the following issue
I am logged in as kitty.walsh who I set to homepage manager and assigned section OCTO
![image](https://user-images.githubusercontent.com/5752113/205205678-f39a89dc-c5cd-4245-b4a7-12c0da83ca7c.png)


When i go to save a homepage benefit promo block, I am unable to because the moderation state field is not visible for me to set, but it is a required field
![image](https://user-images.githubusercontent.com/5752113/205205823-fb341ec9-39a1-423b-b7b2-5b4e793805bd.png)

As me (admin) I can see the field.
![image](https://user-images.githubusercontent.com/5752113/205206541-a9f66c95-72da-4287-829b-eaa2689ba7de.png)


[EDIT]   I just realized this is tester fail.  I missed the detail that user has to also be content_admin.  Sorry for the noise.
Making kitty.walsh a content_admin solved the issue with the moderation state not showing.
![image](https://user-images.githubusercontent.com/5752113/205210514-34429620-713e-4a9f-8310-72f5500c0dcf.png)

2022-12-02 03:07 UTC, swirtSJW commented
As kitty.walsh assigned to OCTO I am able to assign a block to any of the following subsections of OCTO
![image](https://user-images.githubusercontent.com/5752113/205206003-5b22913b-8945-4ecc-8931-d730c6fb795f.png)

That list seems a little mistargetted.  It is not a code problem as that is how section assignments work, but it still makes me think we should be using a subsection of OCTO   (header and footer) as the section for the assigned user.

2022-12-02 03:36 UTC, swirtSJW commented
I was a bit troubled by the look of the workflow section of the form it does not really follow the node pattern which is the probably the standard.  I know the various block types are all over the place in the design so you had not good model to follow.  I think alerts come the closest, but even they aren't right.  So I created this ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11779

2022-12-02 03:59 UTC, swirtSJW commented
Benefit and news promos, since they require content_admin as a role, they get the full section list availability
![image](https://user-images.githubusercontent.com/5752113/205211385-f66942a9-b74e-4b77-8ed3-41614f037788.png)

The section list gets winnowed to your own section UNLESS you are a content admin or an admin.

This seems like a risk. to consider since a low level facility could be assigned which would seem goofy.  Is there a case where we would want some low level section to be assigned?? or any section other than one within OCTO?  
If we don't envision this ever being assigned outside of OCTO, we might want to intentiaonlly overrid the section list options... OR make it so that content_admin is not a required role.

2022-12-02 04:11 UTC, swirtSJW commented
Is there a naming mismatch here?
![image](https://user-images.githubusercontent.com/5752113/205213205-ecb1a49a-6fcf-470c-a40f-6c23efb84e00.png)

2022-12-02 04:22 UTC, swirtSJW commented
As Kitty.walsh After I save the new block  The save happens but I get an access denied
![image](https://user-images.githubusercontent.com/5752113/205214119-348c7722-a361-45ae-8e76-52af20029ec0.png)
at path admin/structure/block/block-content
which is where I get taken if there is no ?destination set.

2022-12-02 04:43 UTC, swirtSJW commented
There is probably a way to intercept the route (admin/structure/block/block-content), and if the person has the perm, show it, but if not redirect to your VIew (admin/content/v2-homepage).  The problem is that would half to assume anyone looking for admin blocks that does not have perms would be looking for homepage blocks...which may not be the truth, and would actually let us only use this trick for one kind of block.   But I don't think there is time to get that in tonight.  :(

2022-12-02 19:14 UTC, dsasser commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +use Drupal\Core\Config\Entity\ConfigEntityType;
I don't use VScode for php, but you did inspire me to install a similar plugin for PHPStorm.

2022-12-02 20:53 UTC, dsasser commented
> Benefit and news promos, since they require content_admin as a role, they get the full section list availability ![image](https://user-images.githubusercontent.com/5752113/205211385-f66942a9-b74e-4b77-8ed3-41614f037788.png)
> 
> The section list gets winnowed to your own section UNLESS you are a content admin or an admin.
> 
> This seems like a risk. to consider since a low level facility could be assigned which would seem goofy. Is there a case where we would want some low level section to be assigned?? or any section other than one within OCTO? If we don't envision this ever being assigned outside of OCTO, we might want to intentiaonlly overrid the section list options.

This may be an artifact of the ACs changing quite a lot, but editing blocks doesn't require a content_admin permission, blocks can be edited by non-admins that:
- Are in the section the block is in (or a parent section) AND
- Are in the content_admin OR content_publisher OR homepage_admin roles.

So I don't see anything actionable here. Please let me know if this is not correct. cc @jilladams @wesrowe

2022-12-02 20:54 UTC, dsasser commented
> Is there a naming mismatch here? ![image](https://user-images.githubusercontent.com/5752113/205213205-ecb1a49a-6fcf-470c-a40f-6c23efb84e00.png)

The labels are as specified in the ACs. I'm not sure what action you would like taken here. cc @jilladams  @wesrowe

2022-12-02 21:38 UTC, jilladams commented
ugh you're right. Apologies. Not sure where hero came from. @wesrowe @mmiddaugh the goal is for names of blocks and names of entity queues to match. Any reason to strongly prefer 'homepage hero' vs 'homepage benefit promo' for the top spot on homepage?

2022-12-05 17:09 UTC, wesrowe commented
@jilladams @dsasser, it was called "homepage hero" at an earlier point. There's no search-and-replace in github so these references can be missed. "Benefit promo" is the correct label.

2022-12-05 19:57 UTC, dsasser commented
@wesrowe 

> "Benefit promo" is the correct label.

To be clear, you are suggesting to change the current entityqueue label from `V2 Home page hero` to `V2 Home page benefit promo`?

2022-12-05 20:01 UTC, dsasser commented
Per recent PR feedback prompted a recent discussion with @swirtSJW @jilladams and myself. The below isues, identified in various PR feedback and comments, will be solved with listed changes:


Remaining issues:
1. Moderation state not avialble for homepage manager: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11534#pullrequestreview-1201919269
2. Block workflow element not aligned with other uses--needs design work/change: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11534#issuecomment-1334721127
3. Section selection too broad, causing too many sections to be available to homepage managers: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11534#issuecomment-1334731800
4. Block types and entityqueue names are not aligned: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11534#issuecomment-1334741207
5. Getting "lost" from v2 homepage view, getting access denied, UX concerns around navigating/saving blocks: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11534#issuecomment-1334747866

Changes to be made:
1. Change moderation state permissions to allow homepage manager to edit/change moderation transition state on blocks. (permissions to match existing content_publisher permissions around workflow)
2. Update workflow element display on Block edit form (for both new homepage block types) to match "Alert Block" settings.
3. Create OPIA subsection: `OPIA Home Page`. Hompeage managers will be added to this section as needed.
4. [?] Update entityqueue labels to match respective block types. (pending results of the comment: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11534#issuecomment-1338086955)
5. Remove V2 Homepage View (added in this issue); Revise existing View permissions for the custom block listing page: admin/structure/block/block-content such that the page is accessible to authenticated users. Homepage managers will then be able to use the Core custom block listing View to view and edit homepage related blocks.

2022-12-05 20:46 UTC, jilladams commented
> @wesrowe
> 
> > "Benefit promo" is the correct label.
> 
> To be clear, you are suggesting to change the current entityqueue label from `V2 Home page hero` to `V2 Home page benefit promo`?

Yes, exactly, to match the  block name.

2022-12-06 22:52 UTC, jilladams commented
## As homepage manager

- [X] create blocks from /admin/structure/block/block-content
- [X] Modify blocks starting from /admin/structure/block/block-content
- [X] Edit entityqueue to remove, then add blocks
- [X] entityqueue labels match respective block types:  V2 Home page news spotlight,  V2 Home page benefit promo

🟡 
I'm still fuzzy on what the Workflow element display is re: "Update workflow element display on Block edit form (for both new homepage block types) to match "Alert Block" settings", so not sure how to check it.

🔴 
* I do not see the new OPIA subsection: OPIA Home Page: as admin I tried to add it to Tuscher: https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/user/30/workbench_access?destination=/admin/people

2022-12-07 17:17 UTC, dsasser commented
> I'm still fuzzy on what the Workflow element display is re: "Update workflow element display on Block edit form (for both new homepage block types) to match "Alert Block" settings", so not sure how to check it.

The idea here is that, despite adding the workflow element to the new V2 home page blocks, the display of that element, when editing the blocks, does not match other implementations, such as the Alert block. The Alert block was identified as a model for how to configure the new V2 Home page blocks display of the workflow element.

Upon revisiting this, I noticed a discrepancy that I'm resolving, where the revision log is not placed correctly in the new fieldset, so I'll be pushing up a fix for that soon. I'll also update test steps to indicate how to compare the displays.

> I do not see the new OPIA subsection: OPIA Home Page: as admin I tried to add it to Tuscher: https://pr11534-fjy928oobogzqvsgrrf2dfp2rletf7lk.ci.cms.va.gov/user/30/workbench_access?destination=/admin/people

This is because I added the section on Prod only yesterday. Apologies, I failed to mention this would take a day to propagate down to lower environments. I'll see if it is available now, and if so, I'll rebuild the Tugboat env so that it is available there.

2022-12-07 18:48 UTC, jilladams commented
Verified both!

2022-12-07 18:49 UTC, jilladams approved these changes

2022-12-08 19:10 UTC, swirtSJW reviewed
![image](https://user-images.githubusercontent.com/5752113/206521922-8af2e672-4a41-4171-a96f-2622bf41bab1.png)
Set up account as kitty.walsh

All tests pass.  This is great @dsasser    Just one question.

2022-12-08 19:14 UTC, dsasser commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +    if (!empty($entityTypes['block_content_type']) && $entityTypes['block_content_type'] instanceof ConfigEntityType) {
Yes. Without this, the block type label will not display, even if users can get to the View.

2022-12-08 19:18 UTC, swirtSJW approved these changes
Approved.   Please do not merge until after we get the "all clear" from platform about the resuming normal operations following the php 8 upgrade,

2022-12-08 19:19 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/206547503-693e83de-ebfc-48dc-8dd0-c7e44e9c5f7d.png)

2022-12-08 19:34 UTC, swirtSJW commented
Calling out here that we discussed on zoom that since this is a core view that we are altering, it is NOT expected that the View should meet our Views Style guide criteria.    It could always be a ticket for the future, but it is exempt from our current norms.

2022-12-08 23:06 UTC, merged