VACMS-11505: add Lasee Saved by an Editor field to all  content types
department-of-veterans-affairs/va.gov-cms pull request #11533
Opened 2022-11-09 20:04 UTC by edmund-dunn

## Description

Closes #11505.

## Testing done
Tested locally. 

## Screenshots

## QA steps

Select a piece of content, scroll to the bottom and change the moderation state to Published and click save. In the node view you will be able to see the field at the bottom with a date adn time. If you go back into the edit form and scroll to the bottom the field will now be populated but it will be disabled so that a user cannot interact with it. 

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-11-09 22:46 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
> -        - revision_log
This is AWOL.    Needs to be added back by hand.

2022-11-10 12:19 UTC, ndouglas requested changes
Looks great, just a couple quibbles from the checks.

2022-11-10 12:19 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/LastEditorSaveEventSubscriber.php
> +    $node = $form_state->getFormObject()->getEntity();
Just needs a type hint to get rid of the PHPStan gripe.
![Screen Shot 2022-11-10 at 7 16 39 AM](https://user-images.githubusercontent.com/1318579/201089349-e480b8c8-77c4-418c-b53c-581af3878695.png)

2022-11-10 12:19 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/LastEditorSaveEventSubscriber.php
> +    $form_state = $event->getFormState();
Do you need `$form_state` for anything?

2022-11-10 14:43 UTC, EWashb commented
All functionality looks/acts as expected in my QA

2022-11-10 14:43 UTC, EWashb submitted a review, later dismissed
all looks/functions as expected in the QA steps.

2022-11-11 15:56 UTC, swirtSJW requested changes
This is not working as expected.  When empty, it is displaying current time and date 

Other issues, summary from individual comments:

1. We have a bunch of unexprected changes coming through in the config, some of which were not there the on your first config exports.

   - lazy loading - I think that one is related to a dependabot bump of blazy, so it is unexpected but I thnk innocuouse.   - neds a QA step to double check one of the affected content types just to be sure.
   - field_administration going missing from hiddden.. that one seeems odd and should definitely be double checked for the impact.  
   - loss of meta title from groupping,  should be doublle checked 
    - There is a very wierd addition about time limit.   This one definetly needs checking out 
 2. looose check for string node is casting too wide a net.  See suggested code.
  3. Auto formatting of behat spec tests is making it look like every line changed.  Set your IDE to not format .feature files.  We want the raw output from spec to persist so that we can see only changes to the line that changed.
  4. QA steps are outdated please adjust them to the changes made
  5. Add a QA step to cover checking the dates on nodes that have not been editied sincee this change.

2022-11-11 15:56 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $last_saved_by_an_editor = $node->get('field_last_saved_by_an_editor')->value;
When the field is empty, it is just picking up the current date time.  This needs to be defensive about picking up a non value.
![image](https://user-images.githubusercontent.com/5752113/201374418-662294c8-2494-4d87-af5b-3de054598d59.png)

![image](https://user-images.githubusercontent.com/5752113/201374466-b3b8cffa-30d5-46fd-a16a-a6b971c0fac2.png)

2022-11-11 16:00 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
> -        - revision_log
This has to be put back  or the test will never pass.

2022-11-14 16:39 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $last_saved_by_an_editor = $node->get('field_last_saved_by_an_editor')->value;
@swirtSJW explain further

2022-11-15 16:15 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $variables['page']['last_saved_by_an_editor'] = $last_saved_by_an_editor ? \Drupal::service('date.formatter')->format($last_saved_by_an_editor, 'custom', 'F j Y g:ia') : 'This needs to be reviewe
@ndouglas no, it is the format used in the recent changes sidebar.

2022-11-15 16:17 UTC, edmund-dunn commented on composer.json
> +        "va-gov/content-build": "^0.0.3138",
I merged in main.

2022-11-15 16:18 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $variables['page']['last_saved_by_an_editor'] = $last_saved_by_an_editor ? \Drupal::service('date.formatter')->format($last_saved_by_an_editor, 'custom', 'F j Y g:ia') : 'This needs to be reviewe
Should we formalize it?  Feels weird having it in code like a magic constant.

2022-11-15 16:59 UTC, laflannery reviewed
The "Updated By:" field seems a bit misleading.  I believe this is actually the author, the original author, that's what it is in Prod currently.  However it seems like the label was updated here but not the functionality.  For example, I updated a piece of content and the new human field has the correct date and time but it still says updated by CMS Migrator:
![image](https://user-images.githubusercontent.com/106678594/201980523-ebe61d50-ed48-4f17-a0d5-9b21dab82bb8.png)

2022-11-17 13:08 UTC, swirtSJW submitted a review, later dismissed

2022-11-17 13:51 UTC, swirtSJW commented
This message seems a little misleading
![image](https://user-images.githubusercontent.com/5752113/202463251-1e734bad-a560-4c78-8c1e-b80bb33d03ae.png)

It was saved by an editor, just not since the field was added.  I realize some of this will go away when we bulk process the published and draft nodes to update that field, but until that happens, AND for the archived nodes that we are not going to touch, this message is not speaking the truth, which leads to confusion and cognition errors.   @BlakeOrgan @EWashb

2022-11-17 14:24 UTC, EWashb commented
> This message seems a little misleading ![image](https://user-images.githubusercontent.com/5752113/202463251-1e734bad-a560-4c78-8c1e-b80bb33d03ae.png)
> 
> It was saved by an editor, just not since the field was added. I realize some of this will go away when we bulk process the published and draft nodes to update that field, but until that happens, AND for the archived nodes that we are not going to touch, this message is not speaking the truth, which leads to confusion and cognition errors. @BlakeOrgan @EWashb
> 
> Suggestions:
> 
> * "Unknown"
> * "Uncertain"
> * "?"
> * "Not recorded"
> * (leave it empty)
> * (hide the display )

But the editor was a human editor in this example? I thought that user was a bot. Maybe we say something to signify that the last save was a bot.

2022-11-17 14:26 UTC, edmund-dunn commented
@EWashb in this case it because it hasn't been saved since we added the field.

2022-11-17 14:28 UTC, EWashb commented
That's exactly what I was thinking. Maybe we do a slight change in wording here, but possibly being pressed for time makes me wonder if we just hide it for the moment so that we can get an accurate report done before the sprint is over.

2022-11-17 14:31 UTC, edmund-dunn commented
I think just put "Unknown" since next sprint it will mostly go away with the script to update the field.

2022-11-17 15:38 UTC, BlakeOrgan commented
I think using "Unknown" is the best option. Once that's updated, I think that this would be good to approve from my end.

2022-11-17 16:03 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $last_saved_by_an_editor = $node->get('field_last_saved_by_an_editor')->value;
@swirtSJW ok, now I got it. This has been addressed. I added a ternary operator.

2022-11-17 16:31 UTC, edmund-dunn commented
> The "Updated By:" field seems a bit misleading. I believe this is actually the author, the original author, that's what it is in Prod currently. However it seems like the label was updated here but not the functionality. For example, I updated a piece of content and the new human field has the correct date and time but it still says updated by CMS Migrator: ![image](https://user-images.githubusercontent.com/106678594/201980523-ebe61d50-ed48-4f17-a0d5-9b21dab82bb8.png)

I changed this to be the latest revision author after conferring with @EWashb

2022-11-17 16:47 UTC, laflannery approved these changes
Looks good!

2022-11-17 16:59 UTC, merged

2022-11-17 19:23 UTC, swirtSJW commented
I am a bit concerned that this got merged without an passing approval from an engineer.
![image](https://user-images.githubusercontent.com/5752113/202539119-3cf7cd0c-b421-400c-abdc-f7e8987aeab0.png)

Especially when the last requested change were engineering related.