VACMS-11516 vba show services description facility view
department-of-veterans-affairs/va.gov-cms pull request #11696
Opened 2022-11-23 05:05 UTC by omahane

## Description

Relates to #11516.

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-11-28 23:08 UTC, swirtSJW requested changes
Some suggestions for making this less risky.

2022-11-28 23:08 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
> +          $entity = $this->entityTypeManager->getStorage('taxonomy_term')->load($referenced_term_id);
I think this risky grab of assuming that getValue() is returning an array that will have a target_id  and then jumping to loading that can be avoided like this.
```suggestion
          $entities = $service_node->get('field_service_name_and_descripti')->referencedEntities();
          $entity = reset($entities);
```
Of course $entity could be FALSE if that field is empty, so youll need to bail out if if it is FALSE.

2022-11-29 15:56 UTC, omahane commented on docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
> +            $view_builder = $this->entityTypeManager->getViewBuilder('taxonomy_term');
@swirtSJW Do I also need to check $entity before using it?

I see you did something like this here:
```
/**
 * Implements hook_simplesamlphp_auth_existing_user().
 *
 * @see hook_simplesamlphp_auth_existing_user()
 */
function va_gov_login_simplesamlphp_auth_existing_user($attributes) {
  $saml_mail = $attributes['adEmail'];
  $existing_users = \Drupal::service('entity_type.manager')->getStorage('user')->loadByProperties(['mail' => $saml_mail]);
  if ($existing_users) {
    $existing_user = is_array($existing_users) ? reset($existing_users) : FALSE;
    if ($existing_user) {
      return $existing_user;
    }
  }
  return FALSE;
}
```
docroot/modules/custom/va_gov_login/va_gov_login.module

2022-11-30 01:41 UTC, omahane commented on docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
> +            $view_builder = $this->entityTypeManager->getViewBuilder('taxonomy_term');
I've added that check.

2022-11-30 01:41 UTC, omahane commented on docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
> +          $entity = $this->entityTypeManager->getStorage('taxonomy_term')->load($referenced_term_id);
Changed and reworded.

2022-11-30 01:41 UTC, omahane commented on docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
> +        if (is_numeric($key) && !empty($service['#options'])) {
Changed.

2022-11-30 01:42 UTC, omahane commented
@swirtSJW This is ready for another going-over.

2022-11-30 04:11 UTC, omahane commented
@laflannery @BlakeOrgan I have this ready for review. Can you let me know what you think?
https://pr11696-tnnufvgx2phkyoicb0eltr92vbvmzhm3.ci.cms.va.gov/anchorage-va-regional-benefit-office-at-anchorage-va-medical-center/locations/pre-discharge-site-at-wasilla-ak

2022-11-30 13:55 UTC, laflannery commented
3 things:

1. On the view screen, could we remove the italics from the notice when there is not a national description? Italics is not recommended in the VA content style guide - it can be difficult to read in some cases.
   1. ![image](https://user-images.githubusercontent.com/106678594/204814137-0ec3e5e1-e6da-4fa1-b432-1622acdd2e62.png)
3. I am confused by VBA 3 on the edit screen - the dropdown says VBA 1, the description says VBA 3 and the title has nothing:
   1. ![image](https://user-images.githubusercontent.com/106678594/204812781-2342754f-9882-4025-8f26-6065b4f08a7f.png)
4. As someone who can edit the national service descriptions, there is an overlapping issue with the edit icon and the tooltips:
   1. I'm not sure how much of an issue this is, how many people this would impact, but I at least wanted to bring it up.  I also have a larger, future goal to overhaul the tooltips in general FYI. 
   2. ![image](https://user-images.githubusercontent.com/106678594/204813146-58488f47-58e6-4229-94f3-284f72734e4e.png)

2022-11-30 14:08 UTC, omahane commented
> 1. On the view screen, could we remove the italics from the notice when there is not a national description? Italics is not recommended in the VA content style guide - it can be difficult to read in some cases.

Yes, I'll change that to bold only.

>    1. ![image](https://user-images.githubusercontent.com/106678594/204814137-0ec3e5e1-e6da-4fa1-b432-1622acdd2e62.png)
> 2. I am confused by VBA 3 on the edit screen - the dropdown says VBA 1, the description says VBA 3 and the title has nothing:

This confusion has to do with the fact that I created the VBA Service with a term that existed (VBA 3). Then, I deleted the term, mostly to show what happens when we delete a term, showing the "Service not found" notice on node:view. This would have to be the cue to change the service choice on the edit screen.

Similarly, on the node:edit screen, the fact that the service has no service name after the facility name is an indication that something is amiss. 

The VBA 1 you're seeing is the form defaulting to the first item on the list for the purposes of selection. It hasn't actually been set to VBA 1 (yet) when you're seeing it in the form that way.

Does that make sense?

Granted, this is an edge case (deleted taxonomy term), but we wanted to account for it somehow.

2022-11-30 14:41 UTC, omahane commented
@laflannery @BlakeOrgan I edited this locally. I haven't pushed my changes, as that will reset the preview environment, including wiping out my content changes (like the terms and VBA services). 

Do these changes look sufficient?
![Screen Shot 2022-11-30 at 8 37 34 AM (2)](https://user-images.githubusercontent.com/766573/204825211-cc367e07-fcd6-4e9b-bf09-c6211498b690.png)

2022-11-30 14:43 UTC, laflannery submitted a review, later dismissed
Looks good, thanks!

2022-12-02 05:41 UTC, swirtSJW reviewed
This all looks good and was testing out.  However I am seeing some acccess denied errors on save.
![image](https://user-images.githubusercontent.com/5752113/205222764-9c659e9a-b007-4373-bc96-a0c45f19207e.png)



Path: /node/51488. Drupal\Core\Http\Exception\CacheableAccessDeniedHttpException: The 'view any unpublished content' permission is required. in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 118 of /var/lib/tugboat/docroot/core/lib/Drupal/Core/Routing/AccessAwareRouter.php).
--

```
Path: /node/51488. Drupal\Core\Http\Exception\CacheableAccessDeniedHttpException: The 'view any unpublished content' permission is required. in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 118 of /var/lib/tugboat/docroot/core/lib/Drupal/Core/Routing/AccessAwareRouter.php).
```  

I believe this is due to not exempting from an access check somewhere along the line.  I am looking into it right now.


Path: /node/51488. Drupal\Core\Http\Exception\CacheableAccessDeniedHttpException: The 'view any unpublished content' permission is required. in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 118 of /var/lib/tugboat/docroot/core/lib/Drupal/Core/Routing/AccessAwareRouter.php).
--


<br class="Apple-interchange-newline">

Path: /node/51488. Drupal\Core\Http\Exception\CacheableAccessDeniedHttpException: The 'view any unpublished content' permission is required. in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 118 of /var/lib/tugboat/docroot/core/lib/Drupal/Core/Routing/AccessAwareRouter.php).
--


<br class="Apple-interchange-newline">

2022-12-02 05:41 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
> +use Drupal\Core\Entity\EntityTypeManager;
```suggestion
use Drupal\Core\Entity\EntityTypeManagerInterface;
```
If there is an interface available, that is the better choicce to use.

2022-12-02 05:41 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
> +use Drupal\core_event_dispatcher\Event\Entity\EntityViewAlterEvent;
I'm going to push up an alpha sort of these use statements.
A useful VS code plugin if you don't have it
![image](https://user-images.githubusercontent.com/5752113/205219880-0fe99d0b-64e8-4e1f-9f27-d8e3426f93e0.png)

2022-12-02 05:41 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
> +   * @var \Drupal\Core\Entity\EntityTypeManager
reference the interface to match the use.

2022-12-02 05:41 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
> +          $referenced_term_array = $service_node->get('field_service_name_and_descripti')->referencedEntities();
Going a little hungarian notation here... which I used to love, but a more modern drupallly pattern is to name plurals if unknown quantity and singular when you have one.
```suggestion
          $referenced_terms = $service_node->get('field_service_name_and_descripti')->referencedEntities();
```

2022-12-02 08:10 UTC, swirtSJW commented
Turns out the access denied error is not coming from this PR.  I just saw it on staging as well
![image](https://user-images.githubusercontent.com/5752113/205246247-3518685c-fede-4f46-af7c-31b91513b04b.png)

it does not need to be fixed for this PR to pass.

2022-12-02 08:14 UTC, swirtSJW approved these changes
@omahane Nice work on this.  I made a couple minor commits mainly hoping to get this accross the line tonight, but then I remembered you has a style change related to the Tool tip location conflicting with the edit pencil icon.

push your changes in the morning and we can call this done.

2022-12-02 15:06 UTC, swirtSJW approved these changes
Approved and ready for merge, just waiting until after demo.

2022-12-02 17:21 UTC, merged