VACMS-11497: Set last-touched-by-a-human field on all published nodes.
department-of-veterans-affairs/va.gov-cms pull request #11719
Opened 2022-11-25 18:22 UTC by ndouglas

## Description

Closes #11497.

This needs more testing, and I'd prefer to close an unrelated issue first, because it's creating a lot of logspam:

![Screen Shot 2022-11-25 at 12 56 12 PM](https://user-images.githubusercontent.com/1318579/204036180-f7869df9-6bcb-4d69-8402-9ce5fc572ad9.png)

The script is split into the following files:

- `common.php` - library of shared code
- `delete_queue.php` - delete the queue and all of its items, mostly for cleanup between tests
- `load_queue.php` - load every published node in the DB into a queue for processing
- `print_full_history_of_node.php` - used to print a full revision history of the node, relevant fields, creation dates, etc.
- `print_node.php` - print a summary of the node with relevant fields, etc, _at the default revision_.
- `run_queue.php` - dequeue one chunk of nodes from the queue and update each one's default and latest revisions in place.
- `set_single.php` - print the full revision history of the node, update its revisions as appropriate, and then print the full revision history again for comparison.

## Testing done

Brute-force testing while developing.

## QA steps

So, generally, you wanna do the following:

### Pick a node and print its full history.

`drush scr ./scripts/content/vacms-11497/print_full_history_of_node.php 27263`

You should see some history like this:

```
$ ddev drush scr ./scripts/content/vacms-11497/print_full_history_of_node.php 27263
Acting as CMS Migrator [1317]
NID    | VID     | Publish | Default | UID   | Human | Created             | Touched (Set)       | Touched (Calc)      | Touched (Node)      | Touched (Will Set)  | Title                                    |
------ | ------- | ------- | ------- | ----- | ----- | ------------------- | ------------------- | ------------------- | ------------------- | ------------------- | ---------------------------------------- |
27263  | 469858  | Yes     | No      | 1203  | Yes   | 2021-07-08 17:44:56 | (not set)           | 2021-07-08 17:44:56 | 2021-07-08 17:44:56 | (not set)           | How do I change the name of a health ser |
27263  | 469861  | Yes     | No      | 1203  | Yes   | 2021-07-08 17:56:53 | (not set)           | 2021-07-08 17:56:53 | 2021-07-08 17:56:53 | (not set)           | How do I change the name of a health ser |
27263  | 469862  | Yes     | No      | 1203  | Yes   | 2021-07-08 18:00:20 | (not set)           | 2021-07-08 18:00:20 | 2021-07-08 18:00:20 | (not set)           | How do I change the name of a health ser |
27263  | 527768  | Yes     | No      | 197   | Yes   | 2021-09-01 16:00:21 | (not set)           | 2021-09-01 16:00:21 | 2021-09-01 16:00:21 | (not set)           | How do I change the name of a health ser |
27263  | 586334  | Yes     | No      | 1451  | Yes   | 2021-11-19 17:46:43 | (not set)           | 2021-11-19 17:46:43 | 2021-11-19 17:46:43 | (not set)           | How do I change the name of a health ser |
27263  | 626360  | Yes     | Yes     | 1451  | Yes   | 2022-03-22 10:24:25 | 2022-03-22 10:24:25 | 2022-03-22 10:24:25 | 2022-03-22 10:24:25 | 2022-03-22 10:24:25 | How do I change the name of a health ser |
27263  | 719974  | No      | No      | 3015  | Yes   | 2022-10-26 13:53:14 | 2022-10-26 13:53:14 | 2022-10-26 13:53:14 | 2022-10-26 13:53:14 | 2022-10-26 13:53:14 | How do I change the name of a health ser |
```

and a table like this:

NID    | VID     | Publish | Default | UID   | Human | Created             | Touched (Set)       | Touched (Calc)      | Touched (Node)      | Touched (Will Set)  | Title                                    |
------ | ------- | ------- | ------- | ----- | ----- | ------------------- | ------------------- | ------------------- | ------------------- | ------------------- | ---------------------------------------- |
27263  | 469858  | Yes     | No      | 1203  | Yes   | 2021-07-08 17:44:56 | (not set)           | 2021-07-08 17:44:56 | 2021-07-08 17:44:56 | (not set)           | How do I change the name of a health ser |
27263  | 469861  | Yes     | No      | 1203  | Yes   | 2021-07-08 17:56:53 | (not set)           | 2021-07-08 17:56:53 | 2021-07-08 17:56:53 | (not set)           | How do I change the name of a health ser |
27263  | 469862  | Yes     | No      | 1203  | Yes   | 2021-07-08 18:00:20 | (not set)           | 2021-07-08 18:00:20 | 2021-07-08 18:00:20 | (not set)           | How do I change the name of a health ser |
27263  | 527768  | Yes     | No      | 197   | Yes   | 2021-09-01 16:00:21 | (not set)           | 2021-09-01 16:00:21 | 2021-09-01 16:00:21 | (not set)           | How do I change the name of a health ser |
27263  | 586334  | Yes     | No      | 1451  | Yes   | 2021-11-19 17:46:43 | (not set)           | 2021-11-19 17:46:43 | 2021-11-19 17:46:43 | (not set)           | How do I change the name of a health ser |
27263  | 626360  | Yes     | Yes     | 1451  | Yes   | 2022-03-22 10:24:25 | 2022-03-22 10:24:25 | 2022-03-22 10:24:25 | 2022-03-22 10:24:25 | 2022-03-22 10:24:25 | How do I change the name of a health ser |
27263  | 719974  | No      | No      | 3015  | Yes   | 2022-10-26 13:53:14 | 2022-10-26 13:53:14 | 2022-10-26 13:53:14 | 2022-10-26 13:53:14 | 2022-10-26 13:53:14 | How do I change the name of a health ser |

or this:
![Screen Shot 2022-11-25 at 1 09 08 PM](https://user-images.githubusercontent.com/1318579/204037534-c73a77d8-0140-468d-b6b6-d2632454b550.png)

The columns are:
- **NID**: Node ID.
- **VID**: Revision ID.
- **Publish**: Whether this specific revision is published.
- **Default**: Whether this specific revision is the default revision.
- **UID**: The UID of the user who authored the revision.
- **Human**: Whether the authoring user was a human.
- **Touched (Set)**: The value of the last-touched-by-a-human field _actually set_ for the revision.  This is `(not set)` currently, because, uh, because it hasn't been set.
- **Touched (Calc)**: The value of the last-touched-by-a-human field _calculated_ for the revision based on the revision logic.  This will be **Created** if the revision is updated by a human, otherwise 0.
- **Touched (Node)**: The value of the last-touched-by-a-human field as should be reported for the revision based on the per-revision logic, but using the value from the previous revision(s) if set.
- **Touched (Will Set)**: The value of the last-touched-by-a-human field that will be actually set, on the revisions that will actually be altered by the script under development.
- **Title**: (truncated)

Verify that the logic seems appropriate.
- If **Touched (Set)** is No, then the last-touched-by-a-human field is not currently set.  
- **Touched (Will Set)** indicates what that field will be set to, if we attempt a write operation.  Does that reflect the logic we intend to use?

### Update a single node and observe the changes

`drush scr ./scripts/content/vacms-11497/set_single.php 27263`

You should see a table of the node's full revision history, then messages tracing through the basic logic of whether or not to set the last-updated field.  They may look like this:

```
Updating node 27263...
Inspecting default revision 626360 for node 27263
Value already set for revision 626360 to 1647959065 (2022-03-22 10:24:25); not overwriting.
Inspecting latest revision 719974 for node 27263
Value already set for revision 719974 to 1666806794 (2022-10-26 13:53:14); not overwriting.
```

or like this:

```
Updating node 27387...
Inspecting latest & default revision 619119 for node 27387
Value already set for revision 619119 to 1645563731 (2022-02-22 16:02:11); not overwriting.
```

or like this:

```
Updating node 50654...
Inspecting latest & default revision 723581 for node 50654
Setting revision last-human date for revision 723581 to 1666892832 (2022-10-27 13:47:12).
```

or like this:

```
Updating node 39262...
Inspecting latest & default revision 724832 for node 39262
Setting revision last-human date for revision 724832 to 1664389389 (2022-09-28 14:23:09).
The default revision is not publis [...]

2022-11-28 16:21 UTC, edmund-dunn submitted a review, later dismissed
This all looks good to me. The results look consistent. The code all makes sense and is clean!

2022-11-28 17:25 UTC, ndouglas commented
502 bad gateway to blame for the failing Cypress test 😩

2022-11-28 20:56 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +function get_latest_node_revision(int $nid): NodeInterface {
Some of these functions are super useful outside of this specific issue and some reproduce what is already here scripts/content/script-library.php    
Can we move the ones that have reusable value to script-library.php  ?

2022-11-28 21:24 UTC, ndouglas commented on scripts/content/vacms-11497/common.php
> +function get_latest_node_revision(int $nid): NodeInterface {
Yep, I'll do that tomorrow 🙂

2022-11-28 21:39 UTC, swirtSJW reviewed
The logging is so beautiful I think I want to cry. 

All looking great.  Just some suggestions for consolidating re-useable code.

2022-11-28 21:39 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +  1,
Nice

2022-11-28 21:39 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +function log_message(string $message): void {
A definite candidate for content/script-library.php  Though it might be good to name to indicate it is a terminal log message vs revisoon log or watchdog..

2022-11-28 21:39 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +function get_node_storage(): NodeStorageInterface {
candidate scripts/content/script-library.php

2022-11-28 21:39 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +function get_user_storage(): UserStorageInterface {
candidate scripts/content/script-library.php

2022-11-28 21:39 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +function switch_user(): void {
scripts/content/script-library.php   Though would be more honest to have it support a uid arg that defaults to cms migrator.

2022-11-28 21:39 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +function get_latest_node_revision(int $nid): NodeInterface {
This one is a duplicate of script-library.php::get_node_at_latest_revision.  Your logic is better because you compartmentalized the drupal calls.  Would be good to port it to there.

2022-11-28 21:39 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +function get_default_node_revision(int $nid): NodeInterface {
candidate  script-library.php

2022-11-28 21:39 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +function get_all_node_revisions(int $nid): array {
candidate script-library.php

2022-11-28 21:39 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +function delete_queue(): void {
I like the queue work.  I wonder if delete_queue and load_queue should go to script-library.php ? and then just 
run_queue would be what get's copied and altered in each script that needs it... or maybe run_queue accepst an argument that is the callback name like "set_node_last_human_date"

This is so powerful it would be great to have it be reusable.

2022-11-29 13:38 UTC, ndouglas commented on scripts/content/vacms-11497/common.php
> +function delete_queue(): void {
Yeah, I recall that the Queue API is not as ELI5 documented as it should be.  I end up having to do some reading every time I use it just because I don't remember e.g. whether a queue item is deleted if it's processed without throwing an exception or if `::deleteItem()` has to be called manually, etc.  (I feel like that might've changed from 7 -> 8, complicating the situation.)

2022-11-29 13:54 UTC, ndouglas commented on scripts/content/vacms-11497/common.php
> +function delete_queue(): void {
I didn't end up refactoring this part.  After playing with it a bit and factoring out a bit of boilerplate, all that's left is really the specific implementation details for the task at hand.  I think that's probably a sign that the Queue API's about as useful as it's gonna get, and that the real issue is just the lack of that ELI5 documentation.  I created #11733 to add some project-specific documentation on how we can use it and also to try to improve the d.o docs.

2022-11-30 12:18 UTC, ndouglas commented
Re-ran script after latest modifications:

```
real    79m42.698s
user    57m3.361s
sys     5m18.954s
```

I'm going to go in and click around on a good number of nodes and see if I see any monkey business. 🐵

2022-11-30 14:08 UTC, ndouglas commented
Some monkey business found, investigating.

2022-11-30 14:42 UTC, ndouglas commented
As far as I can tell, the actual dates on revisions are being set correctly.  However, I think there's a core bug that is preventing us from minimizing the actual impact to editors as much as I'd like.

See https://www.drupal.org/project/drupal/issues/2329253 , which I think might be the bug in question.

I'm trying to edit the node in-place, as much as possible, which includes setting `isSyncing` to `TRUE`.

![Screen Shot 2022-11-30 at 9 23 14 AM](https://user-images.githubusercontent.com/1318579/204820654-0a66b120-ebd6-4629-8849-cc2482bc55ef.png)

However, that still seems to change the `changed` date on nodes, which is visible in the Content Admin view and others.

So we might see this:

![Screen Shot 2022-11-30 at 9 24 55 AM](https://user-images.githubusercontent.com/1318579/204821167-fff27aa2-9be8-46c2-b90b-ad9a1be5df7b.png)

which makes it look as though we're running the Linky updater script again, which is a valid cause for concern.

(Admittedly, that's only when I shoot back many, many pages -- but it was alarming to me when I did so while testing, so I wanna bring it up.)

More recently, we'll see things like this:

![Screen Shot 2022-11-30 at 9 26 27 AM](https://user-images.githubusercontent.com/1318579/204821524-a4e51077-f2cb-4f6b-b5bf-3aa3fcb6467a.png)

It seems innocuous, and it more-or-less is (which is why I didn't notice it before).  But of course, that last-modified date is not to be trusted.

Viewing the node, we see:

![Screen Shot 2022-11-30 at 9 27 39 AM](https://user-images.githubusercontent.com/1318579/204821953-165446ca-340b-4936-a6ad-6afb992fb475.png)

which _appears_ inaccurate.  But viewing the revisions page:

![Screen Shot 2022-11-30 at 9 27 50 AM](https://user-images.githubusercontent.com/1318579/204821993-05ec7e8c-1c4a-4222-b8ec-1d2152949037.png)

So we see that the date-last-touched-by-a-human field is set correctly, but the block in node view is not accurately representing the node revision date.

Looking at the view, we see:

![Screen Shot 2022-11-30 at 9 37 23 AM](https://user-images.githubusercontent.com/1318579/204824275-e60c2ce4-d5ae-49b8-b2bb-89e20323fd38.png)

But the top date is coming in via an attachment:

![Screen Shot 2022-11-30 at 9 38 11 AM](https://user-images.githubusercontent.com/1318579/204824498-0092298a-3e5b-427e-bf73-a744aba4076d.png)

and that's actually using the Changed date, not the revision created date:

![Screen Shot 2022-11-30 at 9 38 48 AM](https://user-images.githubusercontent.com/1318579/204824674-08ad9cc4-9e5c-48ce-ba1a-cf6292c5000b.png)

Changing that to use the revision created date, we see a consistent sidebar block.

![Screen Shot 2022-11-30 at 9 41 12 AM](https://user-images.githubusercontent.com/1318579/204825183-fc23a6dc-b69d-4711-8073-442bba2bb26a.png)

So **TL;DR:** I think everything's right in the script itself but there are some confusing discrepancies that make this a little terrifying and not quite as low-disruption as we'd originally planned.

2022-11-30 22:04 UTC, swirtSJW commented
@ndouglas I think I have the solution to the changed date being update, but I want to test it before I send you down hole of small rabbit.

2022-11-30 23:04 UTC, swirtSJW reviewed
I think the first set of code suggestion I made solves it, but I am pulling a new db to try it fresh just to make sure.

2022-12-01 01:18 UTC, swirtSJW commented
Re-ran... that did not fix :(    Still poking at this.

2022-12-01 01:50 UTC, swirtSJW commented
It is this bit of code in docroot/core/lib/Drupal/Core/Field/Plugin/Field/FieldType/ChangedItem.php  Lines 49-51   

```
if ($this->value == $original_value && $entity->hasTranslationChanges()) {
          $this->value = REQUEST_TIME;
        }

```

2022-12-01 02:58 UTC, swirtSJW commented
Micorsecond tweak for the win
![image](https://user-images.githubusercontent.com/5752113/204955330-595a7500-2bfa-42f7-8a26-9b695ba073a0.png)


![image](https://user-images.githubusercontent.com/5752113/204955515-538ea93a-40d8-4460-b390-e21ae83e9550.png)


The changed time is NOT getting updated to the current time., which is great.

2022-12-01 03:02 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +  $node->setNewRevision(FALSE);
Disregard.  I already pushed a related change

2022-12-01 03:02 UTC, swirtSJW commented on scripts/content/vacms-11497/common.php
> +  $node->setSyncing(TRUE);
disregard, already pushed related

2022-12-01 03:05 UTC, swirtSJW requested changes
I think something is off here with looking for human updates that are farther down the revision stack.

This node is not picking up the human edit /node/2273/
![image](https://user-images.githubusercontent.com/5752113/204956301-eb10717c-a80e-4a52-ba62-7aa196e27650.png)

2022-12-01 04:40 UTC, swirtSJW commented
I see the problem.  Forcing in the date to get around the new save, is also forcing in the date and revision info of the last human saved... which is not alwasy the same as the revision being saved, since we are doing latests and default.
![image](https://user-images.githubusercontent.com/5752113/204959628-4af2c067-041d-445d-b6b2-a51f4a5bcc40.png)

I just pushed up a change to fix this.  But am awaiting another full round of testing.

2022-12-01 05:08 UTC, swirtSJW commented
Yep that last change seemed to fix it.
![image](https://user-images.githubusercontent.com/5752113/204970217-315a6584-a982-45cc-9e26-8e1cf8ff7279.png)


@ndouglas  can you run a full round of QA on this to double check me?  (never trust a cyclops past midnight)

2022-12-01 14:45 UTC, swirtSJW approved these changes
I have added some code (last three commits) that resolve the incorrect setting of the changed date.  I approve of this and it tests out, but someone else needs to review my code before this is considered mergeable..

2022-12-01 16:43 UTC, ndouglas commented
- Verified that no new log messages appeared
- looks like the changed dates aren't visibly updated, which is great!
![Screen Shot 2022-12-01 at 11 33 01 AM](https://user-images.githubusercontent.com/1318579/205107865-ce1440ee-6824-40be-b1b5-55414c855690.png)
- checking various permutations of human vs. CMS migrator, draft vs. published vs. archived, etc, looking correct.  I was going to share screenshots from each but seemed superfluous.  One new one was this:

![Screen Shot 2022-12-01 at 11 40 40 AM](https://user-images.githubusercontent.com/1318579/205109694-6db02af2-aef9-4bf4-b6f8-515cd728e84d.png)

- another interesting one is this one, which shows that the date is working correctly even when it's buried several revisions in the past.

![Screen Shot 2022-12-01 at 11 41 50 AM](https://user-images.githubusercontent.com/1318579/205109930-6eb4a7d1-e1ca-4fb6-95c7-b3146f41c2a2.png)

I'm not crazy about running this on Thursday night, for reasons, but I think everything is matching up.

2022-12-01 19:43 UTC, edmund-dunn approved these changes
This looks good to me. Solid work Nate!

2022-12-01 19:44 UTC, merged