VACMS-11519: Adds national vet center service descriptions to node:view
department-of-veterans-affairs/va.gov-cms pull request #11799
Opened 2022-12-05 19:12 UTC by omahane

## Description

Closes #11519.

## Testing done

Manually.

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-12-12 21:14 UTC, JayDarnell commented
Something strange is going on with the test Vet Center @omahane. The PTSD care service is listed without a service name when you edit the Vet Center. When you click edit on this item, the description tells you its PTSD but the service name shows Addiction and Substance abuse care (which is the other service for this particular Vet Center that doesn't have a national description)

2022-12-12 21:33 UTC, omahane commented
@JayDarnell I deleted the PTSD term, which is why it's not showing. The reason it appears to Addition and substance abuse care is that this is the first available term, to which it defaults.

2022-12-13 14:37 UTC, JayDarnell requested changes

2022-12-13 14:37 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +      // 15 chars or more means the copy should be legitimate.
What is the significance of 15 characters? How did you arrive at this number?

2022-12-13 14:37 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +    $view_builder = $this->entityTypeManager->getViewBuilder('taxonomy_term');
Referencing the PHPStan notice below, I think $description needs to be defined as an empty string to start with so we can safely say it is always defined. We don't want to get into a situation where we hit the return statement and $description doesn't exist.

2022-12-13 14:37 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +    return $description;
I ran a test where I deleted all the descriptions for a term: no VAMC description, no vet center description, just empty fields. Initially it was fine because it was cached but once the cache was cleared we ended up with this result:
![Screenshot 2022-12-13 at 9 37 07 AM](https://user-images.githubusercontent.com/21045418/207362178-1500ece8-10e7-4c56-a273-e3b3512840a6.png)

2022-12-13 14:44 UTC, omahane commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +      // 15 chars or more means the copy should be legitimate.
This was something Ethan did in the va_gov_backend code. There wasn't any comment that described its importance, but I trust Ethan had a reason for this, so I tried to comment something about that. I could be clearer that I don't know the significance but that given the code I'm replacing, I don't know all the ways he tested and got to that number.

2022-12-13 14:52 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +      // 15 chars or more means the copy should be legitimate.
I didn't catch that this was in the original code. In Ethan we trust :)

2022-12-13 15:53 UTC, omahane commented on docroot/modules/custom/va_gov_vet_center/css/vet_center_service.css
> +.centralized.tooltip-layout {
Thanks. Done.

2022-12-13 15:54 UTC, omahane commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +    $view_builder = $this->entityTypeManager->getViewBuilder('taxonomy_term');
I wasn't sure about making it a string so I made it an empty FormattableMarkup, which is what it is when returned if correct.

2022-12-13 20:30 UTC, JayDarnell commented
@omahane there are still a couple issues with the displays for the nationalized service descriptions. 

![Screenshot 2022-12-13 at 3 28 00 PM](https://user-images.githubusercontent.com/21045418/207437188-bd1842a9-df14-4545-8343-ec6a79655912.png)

![Screenshot 2022-12-13 at 3 28 12 PM](https://user-images.githubusercontent.com/21045418/207437240-8200a5ae-7b64-4eae-a1b7-a3115519ae82.png)

2022-12-14 16:03 UTC, JayDarnell approved these changes
I'm no longer seeing issues with blank term information and the styling looks great.

2022-12-14 17:04 UTC, merged