VACMS-11850: lovell federal health care system should not be editable…
department-of-veterans-affairs/va.gov-cms pull request #11888
Opened 2022-12-08 21:10 UTC by JayDarnell

… by non-admin

## Description

Closes #11850 

## Testing done

Manual/visual testing

## Screenshots

Admin on the left, non-admin editor on the right

![Screenshot 2022-12-08 at 3 42 38 PM](https://user-images.githubusercontent.com/21045418/206565920-52639092-5245-4bf3-880a-49b71b8800e5.png)

![Screenshot 2022-12-08 at 3 43 30 PM](https://user-images.githubusercontent.com/21045418/206566198-36db4a8a-3394-4dc5-81e5-a0fa974188ef.png)

![Screenshot 2022-12-08 at 3 44 03 PM](https://user-images.githubusercontent.com/21045418/206566245-d375497a-f058-46ed-bcc2-6517392cdad2.png)

## QA steps

As an admin user:

...

As a content editor for the Lovell system (example: Katie.Yearley@va.gov)

...

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

2022-12-09 15:51 UTC, omahane commented
When following the QA steps for the Lovell editor, the [bulk edit page](https://pr11888-ddcwflnwjtq964gdn1uauk08qar1qzru.ci.cms.va.gov/admin/content/bulk?title=&type=health_care_region_page&moderation_state=All&taxonomy_entity_index_tid_depth=347), is not accessible, so I went to the [section page](https://pr11888-ddcwflnwjtq964gdn1uauk08qar1qzru.ci.cms.va.gov/section/vha/vamc-facilities/lovell-federal-health-care) instead, after logging in.

2022-12-09 19:26 UTC, omahane requested changes
The QA steps worked (with that little change to the editor view of the facilities).

I think we should do this in the LovellEventSubscriber.php, though. I see that there's an ENTITY_ACCESS available.

2022-12-09 20:29 UTC, JayDarnell commented
Doh, good catch @omahane. Updating now.

2022-12-09 22:47 UTC, JayDarnell commented
@omahane I got it working with an event subscriber.

2022-12-12 14:11 UTC, omahane requested changes

2022-12-12 14:11 UTC, omahane commented on docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
> +   * @param Drupal\Core\Session\AccountInterface $account
` @param Drupal\Core\Session\AccountInterface $account`
should be
` @param \Drupal\Core\Session\AccountInterface $account`

2022-12-12 14:15 UTC, omahane commented on docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
> +   * @param Drupal\Core\Session\AccountInterface $account
Otherwise, it is working as designed. This is great, @JayDarnell .

2022-12-12 14:42 UTC, JayDarnell commented on docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
> +   * @param Drupal\Core\Session\AccountInterface $account
Thanks for catching my typo. Updated in my latest push.

2022-12-12 15:22 UTC, merged