VACMS-11425: orphaned paragraphs report
department-of-veterans-affairs/va.gov-cms pull request #11925
Opened 2022-12-13 18:44 UTC by edmund-dunn

## Description

Closes #11415.

## Testing done
Tested locally.

## Screenshots

## QA steps

1. Navigate to Report > Orphaned Paragraphs
   - [ ] Validate that the report shows total number of orphaned paragraphs.
   - [ ] Validate that the report is populated. 
- The report will take time to populate. 

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-12-14 15:00 UTC, swirtSJW requested changes
I tested as kitty walsh and confirmed that access was denied.
As admin on first load, I wait a long time and get a gateway timeout.  Subsequent page request works fine though.   Since this is an admin only thing AND will not be used daily, I am ok with that.

I did find a couple things that do need changing though.  See below.

2022-12-14 15:00 UTC, swirtSJW commented on config/sync/views.view.orphaned_paragraphs.yml
> +          caption: 'List of all tables used on the site'
This caption does not make sense for this View
![image](https://user-images.githubusercontent.com/5752113/207621489-74040ae5-7a29-4247-a93b-ccd50f6ab443.png)

2022-12-14 15:00 UTC, swirtSJW commented on config/sync/views.view.orphaned_paragraphs.yml
> +          label: Published
Due to workbench moderation, ALL paragraph revisions are published.  This column is misleading because it has nothing to do with the parent being published.   I think it should be removed to avoid confusion, and not surface data that is all the same.

![image](https://user-images.githubusercontent.com/5752113/207622887-00caa6c2-6f87-4c5e-850a-7a10ff8305ae.png)

2022-12-14 15:00 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/OrphansReportViewsEventSubscriber.php
> +          // $top_parent = va_gov_backend_get_top_parent_entity($paragraph);
If this doesn't belong here, can we remove it?

If it is important to keep it around for reference, can we add a comment to explain why it is valuable.

2022-12-14 15:00 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/OrphansReportViewsEventSubscriber.php
> +          $str = 'This paragraph is connected to ' . $top_parent->toLink()->toString() . '. Moderation state is: ' . $top_parent->get('moderation_state')->getValue()[0]['value'];;
This is an awesome touch.  Well done.
![image](https://user-images.githubusercontent.com/5752113/207623777-9473e55e-459b-4501-aabc-c6d6898a81b4.png)

A couple things on the code aspect of it: 
`get('moderation_state')->getValue()[0]['value']` is a risky grab because it assumes there is an element 0 and sub-element value.
this would have less risk
`get('moderation_state')->value`  It matches the pattern we are using elsewhere in our custom code.

Minor:
Multiple string concatenations are slower because it calls the string concatenation with every '.' it runs into.  Replacement is only called once, no matter how many replacements are present.  Personally I find it easier to read too.
```suggestion
          $str = "This paragraph is connected to {$top_parent->toLink()->toString()}. Moderation state is: {$top_parent->get('moderation_state')->value}.";
```

2022-12-14 15:00 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/OrphansReportViewsEventSubscriber.php
> +    ];
Minor: This function is the director of all the other functions  It should go at near the top of the class as it can go because  it tells the "story" of the code that comes after it.

2022-12-14 15:43 UTC, edmund-dunn commented on config/sync/views.view.orphaned_paragraphs.yml
> +          caption: 'List of all tables used on the site'
Good catch. Fixed.

2022-12-14 15:44 UTC, edmund-dunn commented on config/sync/views.view.orphaned_paragraphs.yml
> +          label: Published
Good point. Its removed.

2022-12-14 15:45 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/OrphansReportViewsEventSubscriber.php
> +          // $top_parent = va_gov_backend_get_top_parent_entity($paragraph);
I had kept it for testing purposes only. I went ahead and removed it.

2022-12-14 15:53 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/OrphansReportViewsEventSubscriber.php
> +    ];
That is a good point. I used `docroot/modules/contrib/hook_event_dispatcher/examples/ExampleViewsEventSubscribers.php` as my starting point and they put it at the bottom.

2022-12-15 02:30 UTC, swirtSJW requested changes
This tests out good.   There is only one change needed for a repeated semi-colon.  I will commit the change directly from here, then I thing we are good to go.

2022-12-15 02:32 UTC, swirtSJW approved these changes

2022-12-15 02:53 UTC, merged