VACMS-11526: Table audit displays tables that no longer exist on the current node
department-of-veterans-affairs/va.gov-cms pull request #11988
Opened 2022-12-16 15:36 UTC by edmund-dunn

## Description

Closes #11526.

## Testing done
Tested locally. 

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As an admin
1. Navigate to /admin/content/audit/tables?page=29
   - [ ] Validate that paragraphs with id 14232 - 14236 are not displayed. 
2. Then navigate to /admin/content/audit/tables?page=42
   - [ ] Validate that the paragraph with id 49883 is not displayed

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-12-16 17:41 UTC, laflannery commented
The items you pointed out in the QA steps I confirmed, however I saw this weird one on page 42:
![image](https://user-images.githubusercontent.com/106678594/208156739-a51cbe8c-85fc-478e-9f04-6debf2fe28c4.png)
It's on this page: https://web-fhcoo6tdjzfmfx2sfo8dppryjwu4cejv.ci.cms.va.gov/minneapolis-health-care/contact-us/
But there are no tables on this page, do you know where's it's coming from?

The other thing I noticed is that tables do not start to show up until page 3, which is a little confusing, page 1 and 2 have nothing:
https://pr11988-fhcoo6tdjzfmfx2sfo8dppryjwu4cejv.ci.cms.va.gov/admin/content/audit/tables?page=1
Is there anything we can do about that? If a user comes to this for the first time and sees nothing on  page load they may think it's broken

2022-12-16 21:23 UTC, laflannery approved these changes
Looks good!

2022-12-20 13:11 UTC, ndouglas commented
**praise**: Looks good, QA steps succeed. 👍🏻 

**thought**: I notice that PHP_CodeSniffer's throwing a fit because of some return signatures.  I'm not crazy about making those changes in an unrelated PR, but it'd be cool if you opened an issue and copypasta'ed the complaints in.  Actually nvm I'll see if I can open an issue for it.

2022-12-20 13:25 UTC, ndouglas requested changes
Code formatting is the only issue I see.

2022-12-21 18:07 UTC, ndouglas submitted a review, later dismissed

2022-12-21 18:07 UTC, ndouglas commented
Code formatting issues fixed, re-verified QA steps, everything looks good 😎

2022-12-21 18:29 UTC, swirtSJW requested changes
A few suggestions for changes.

2022-12-21 18:29 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +use Drupal\node\Entity\Node;
Do we want NodeInterface here?
```suggestion
use Drupal\node\NodeInterface;
```

2022-12-21 18:29 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +   * @param \Drupal\node\Entity\Node $node
Should this be the interface?

2022-12-21 18:29 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +   *   The tree of parent entities.
This is not just a flat array, it would be good to declare in the comment what elements are expected in the array (namely 'field_name' and 'revision_id' )

2022-12-21 18:29 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.install
> + * Remove table paragraph 50034.
```suggestion
 * Remove table paragraph 50034 because it was malformed and a remnant from clone cleanup.
```
Always good to let it tell the story of "why" since that can not be communicated by the code.

2022-12-21 18:29 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
>   *
Missing the param and explanation of $tree

2022-12-21 18:29 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +            if ($top_parent->getEntityTypeId() !== 'node') {
shouldn't this be an else?  The first if checks that it is a node.

```suggestion
            else {
```

2022-12-21 18:32 UTC, laflannery approved these changes

2022-12-21 18:42 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +            if ($top_parent->getEntityTypeId() !== 'node') {
This is a fallback for other entity types where the table para might be used in the future. Currently only used in nodes. I added a comment.

2022-12-21 18:43 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +            if ($top_parent->getEntityTypeId() === 'node') {
Fixed.

2022-12-21 18:43 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +   * @param \Drupal\node\Entity\Node $node
Probably.

2022-12-21 18:48 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.install
> + * Remove table paragraph 50034.
Fixed.

2022-12-21 18:48 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
>   *
Fixed.

2022-12-21 18:48 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +   *   The tree of parent entities.
Fixed.

2022-12-21 18:49 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +use Drupal\node\Entity\Node;
Yes. Fixed.

2022-12-21 18:50 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +  public function preRender(ViewsPreRenderEvent $event) {
No, this wasn't intentional. Adding it back in.

2022-12-22 14:26 UTC, EWashb approved these changes
Everything looks good to me

2022-12-22 22:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +            if ($top_parent->getEntityTypeId() !== 'node') {
Sorry, My point is that we have two blocks of code under separate if clauses,  One runs if it is a node, one runs if it is anything else.  That should be and if else, not two ifs.
![image](https://user-images.githubusercontent.com/5752113/209239138-193094ba-fec3-4dbf-86ae-7c6220cfb7a1.png)

If we aren't going to make it an else, then it should not be using string match and should be using a interface check.   Just making it an else would make it cleaner.

2022-12-22 23:02 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.install
> + * Remove table paragraph 50034.
I don't think this fix got committed.  As it still has the shorter version in the code.

2023-01-03 17:10 UTC, swirtSJW requested changes
@edmund-dunn  It looks like there are still two pieces of feedback that are unaddressed.

2023-01-03 17:10 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +            if ($top_parent->getEntityTypeId() !== 'node') {
This has not been addressed.

2023-01-03 17:10 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.install
> + * Remove table paragraph 50034.
This is still unresolved.

2023-01-03 19:09 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.install
> + * Remove table paragraph 50034.
Good catch! Fixed again! 👍

2023-01-03 19:26 UTC, edmund-dunn commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
> +            if ($top_parent->getEntityTypeId() !== 'node') {
I don't necessarily agree with this. However, it is done.

2023-01-03 21:27 UTC, swirtSJW approved these changes
Nice work on this @edmund-dunn

2023-01-03 21:27 UTC, merged