VACMS-11980: Winnows Lovell VA distinct from Lovell TRICARE
department-of-veterans-affairs/va.gov-cms pull request #11981
Opened 2022-12-16 01:23 UTC by omahane

## Description

Closes #11980.

## Testing done

Manually.

## Screenshots

### Non-clinical service

#### Lovell TRICARE

#### Lovell VA

#### Non-Lovell

### VAMC Facility Health Service

#### Lovell TRICARE

#### Lovell VA

#### Non-Lovell

## QA steps
### Non-clinical service
As an admin, create a non-clinical service for a non-Lovell facility.
- [ ] Validate that the facility has been appropriately winnowed.

As an admin, create a non-clinical service for Lovell VA.
- [ ] Validate that the facility has been appropriately winnowed.

As an admin, create a non-clinical service for Lovell TRICARE.
- [ ] Validate that the facility has been appropriately winnowed.

### VAMC Facility Health Service
As an admin, create a VAMC facility health service for a non-Lovell facility.
- [ ] Validate that the facility has been appropriately winnowed.
- [ ] Validate that the VAMC system health service has been appropriately winnowed.

As an admin, create a VAMC facility health service for Lovell VA.
- [ ] Validate that the facility has been appropriately winnowed.
- [ ] Validate that the VAMC system health service has been appropriately winnowed.

As an admin, create a VAMC facility health service for Lovell TRICARE.
- [ ] Validate that the facility has been appropriately winnowed.
- [ ] Validate that the VAMC system health service has been appropriately winnowed.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-12-16 02:38 UTC, ryguyk approved these changes
Approving **code**. 
**I have not followed the QA steps.**

A thought to consider, though:

I wonder if it 'd make more sense - and possibly be more concise - to set `adminMatcher` conditionally and then just have the one condition for removing the hidden tag:
```
let adminMathcher;
if (adminFieldText.search(lovellTricarePattern) > -1) {
  adminMatcher = 'Lovell Federal TRICARE health care';
} else if (adminFieldText.search(lovellVaPattern) > -1) {
  adminMatcher = 'Lovell Federal VA health care';
} else {
  adminMatcher = adminFieldText.replace(/(^-+)/g, "");
}
.
.
.
if (i.text.includes(adminMatcher)) {
  i.classList.remove("hidden-option");
}
```

This makes more sense in my brain, though that might just be me. Not blocking. Just my musings.

2022-12-16 02:49 UTC, swirtSJW reviewed
Code looks good.  Will test functionality in a bit.

2022-12-16 02:52 UTC, swirtSJW commented
> Approving **code**. **I have not followed the QA steps.**
> 
> A thought to consider, though:
> 
> I wonder if it 'd make more sense - and possibly be more concise - to set `adminMatcher` conditionally and then just have the one condition for removing the hidden tag:
> 
> ```
> let adminMathcher;
> if (adminFieldText.search(lovellTricarePattern) > -1) {
>   adminMatcher = 'Lovell Federal TRICARE health care';
> } else if (adminFieldText.search(lovellVaPattern) > -1) {
>   adminMatcher = 'Lovell Federal VA health care';
> } else {
>   adminMatcher = adminFieldText.replace(/(^-+)/g, "");
> }
> .
> .
> .
> if (i.text.includes(adminMatcher)) {
>   i.classList.remove("hidden-option");
> }
> ```
> 
> This makes more sense in my brain, though that might just be me. Not blocking. Just my musings.

I like the re-useability of this,  The repeated code was bugging me a bit.   This seems more DRY

2022-12-16 13:11 UTC, omahane commented
@ryguyk Inspired me to give it another look, so I refactored for DRY.

2022-12-16 15:14 UTC, ryguyk submitted a review, later dismissed

2022-12-16 15:14 UTC, ryguyk commented on docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.es6.js
> +    }
This function is a great abstraction! 

From a very theoretical perspective, I think it could be improved even further by defining the match text as a parameter and then passing that in when it's called, rather than relying on a variable defined outside the function (`adminMatcher`). That change would make the function pure. It would also make it more reusable.

From a practical perspective, the refactor described above is not critically necessary. If this function remains a nested function, there's not a lot to be gained. Still, in general, I think pure functions are a good thing to strive for.

2022-12-16 15:17 UTC, swirtSJW commented
Code looks good  (thank you for making it more DRY, and I love the QA steps. 

 I think the only concern I have is around our handling of umbrella services.    We probably need to discuss AC's around that.

2022-12-21 21:42 UTC, ryguyk commented on docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.es6.js
> +    }
😍

2022-12-21 22:15 UTC, omahane commented on docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.es6.js
> +    }
@ryguyk I'm digging into Cypress right now (not very TDD, I know), but if you see anything else you think might need to change, please let me know. I've gotten rid of all that Lovell-yness from va_gov_backend winnower and tested locally and in the PR env.

2022-12-22 12:58 UTC, omahane commented on tests/cypress/integration/behavioral/common/the_option_from_dropdown_should_be_selected.js
> +
@ryguyk This "breaks" the pattern of this common test, though it's very close. Should I just make a new one instead and  put my comment steps into it?

2022-12-23 21:38 UTC, swirtSJW requested changes
So far this is looking great.  A couple minor changes requested.

2022-12-23 21:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js
> +((Drupal) => {
Awesome work breaking this all out of vagov backend and working it into lovell.

2022-12-23 21:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +  // - vha_facility_nonclinical_service bundles.
```suggestion
  $bundles_to_remove_lovell_federal_from = [
    'health_care_local_health_service',
    'regional_health_care_service_des',
    'vha_facility_nonclinical_service',
  ];
```
This method removes the need for so much in the comments

2022-12-23 21:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
> +        $node->bundle() === 'vha_facility_nonclinical_service') {
```suggestion
    if (in_array($node->bundle(), bundles_to_remove_lovell_federal_from)) {
```

2022-12-23 21:38 UTC, swirtSJW commented on tests/cypress/integration/behavioral/content_editing_vamc_facility_service.feature
> +    When I am logged in as a user with the "content_admin" role
content_admin is a super user.  I think we want to narrow this to test with Content creator - VAMC (vamc_content_creator)
```suggestion
    When I am logged in as a user with the "vamc_content_creator" role
```

2022-12-27 16:56 UTC, omahane commented
@swirtSJW 
After changing the Cypress test to “vamc_content_creator”, the test in the PR environment was returning

```
https://pr11981-jtqcofqvxnlbtgmcwxm072cz96xppsti.ci.cms.va.gov/node/add/health_care_local_health_service

The response we received from your web server was:

  403: Forbidden
```
Plus, I am not sure how it will test whether all the sections work (Lovell - TRICARE, Lovell - VA and non-Lovell) if they are a vamc_content_creator. In fact, I tried to recreate the test manually by making a vamc_content_creator as Cypress does but because it does not add a section to the user, it can’t add the content, returning an “access denied”.

I reverted it back to "content_admin".

2022-12-29 14:08 UTC, swirtSJW commented
> @swirtSJW After changing the Cypress test to “vamc_content_creator”, the test in the PR environment was returning
> 
> ```
> https://pr11981-jtqcofqvxnlbtgmcwxm072cz96xppsti.ci.cms.va.gov/node/add/health_care_local_health_service
> 
> The response we received from your web server was:
> 
>   403: Forbidden
> ```
> 
> Plus, I am not sure how it will test whether all the sections work (Lovell - TRICARE, Lovell - VA and non-Lovell) if they are a vamc_content_creator. In fact, I tried to recreate the test manually by making a vamc_content_creator as Cypress does but because it does not add a section to the user, it can’t add the content, returning an “access denied”.
> 
> I reverted it back to "content_admin".

I think we should have a test condition that applies a section.  Meaning either we have one, or we need one.  If we are testing perms and capabilities of the winnower(s) this is often where they fail.  So we want to try to close that gap.

2022-12-30 23:14 UTC, omahane commented
@swirtSJW In testing, I discovered that we actually **do** have a problem with the way that Lovell permissions are being populated. 

This user (example1@example.com) has the "vamc_content_creator" role.

User example1@example.com is set to Lovell Federal section in Workbench Access:
<img width="1605" alt="Screen Shot 2022-12-30 at 4 44 54 PM" src="https://user-images.githubusercontent.com/766573/210116928-fdc895fb-2571-44b6-b623-d17be7c082e6.png">


User example1@example.com is set to Lovell TRICARE in Workbench Access:
<img width="1539" alt="Screen Shot 2022-12-30 at 4 52 07 PM" src="https://user-images.githubusercontent.com/766573/210116938-9c70c3d5-3bd4-4a67-975e-0d09d87b9661.png">


User example1@example.com is set to Lovell VA in Workbench Access:
<img width="1641" alt="Screen Shot 2022-12-30 at 4 57 45 PM" src="https://user-images.githubusercontent.com/766573/210116961-9d931b55-ea7b-405c-94eb-ccc05fd14f31.png">

The problem is that I'm not really sure how this works. 

I see that this *seems* to be set in
`_va_gov_backend_dropdown_field_access`
in `va_gov_backend/va_gov_backend.module`

2023-01-03 22:37 UTC, swirtSJW commented
Yah something seems weird.  When i login as example1 I can see the content, but I can't edit any of it.
![image](https://user-images.githubusercontent.com/5752113/210452855-44680924-742f-47bc-af95-37120b01b2ea.png)

2023-01-03 22:48 UTC, swirtSJW commented
Looking into this more, if I give the editor VAMC content creator AND Content Publisher, then I get edit buttons.    That doesn't seem like it should be the case, but I am looking deeper into the perms.

2023-01-03 22:57 UTC, swirtSJW commented
I am pretty sure the issue is this
![image](https://user-images.githubusercontent.com/5752113/210454862-b6ac502e-34ef-4d32-98e9-3f4620dfcd7f.png)

Someone with only the role of VAMC Content creator does not have the ability to view content.  So the list is not populates with anything.  There is nothing to choose because they can't see it.

I think that setting is a mistake.  Everyone ought to be able to see  content.  I need to dig a bit more.

2023-01-03 23:00 UTC, swirtSJW commented
It looks like everyone within VHA gets both roles.  Content creator and content publisher.
![image](https://user-images.githubusercontent.com/5752113/210455443-ba3e60b4-da55-4021-bd2e-bb9860d48612.png)

Our test likely needs both.

2023-01-04 14:21 UTC, JayDarnell commented
Thank you for documenting those details here @swirtSJW

2023-01-04 22:13 UTC, omahane commented on tests/cypress/support/commands.js
> -  roles.forEach(role => cy.drupalDrushUserRoleAdd(role, username, password));
But it is already being used in line 62 this way, right?
```
  return cy.drupalDrushUserRoleAdd(username, role);

```

2023-01-04 22:19 UTC, omahane commented on tests/cypress/support/commands.js
> -  roles.forEach(role => cy.drupalDrushUserRoleAdd(role, username, password));
Also, drupalAddUserWithRoles is using the username and password to create the user and then the username and role to add the roles with drupalDrushUserRoleAdd, which is defined on line 56 as only using the username and role.

2023-01-04 22:33 UTC, swirtSJW approved these changes

2023-01-04 22:33 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/210662715-0e227c78-7efe-40ae-9e50-2bd320e863ac.png)

2023-01-04 22:33 UTC, merged