VACMS-12217: Update wysiwyg from user behavior
department-of-veterans-affairs/va.gov-cms pull request #12403
Opened 2023-02-01 19:25 UTC by omahane

## Description

Relates to #12217 
Relates to #10708

This PR demonstrates through manual testing and through Cypress testing (`tests/cypress/integration/behavioral/content_editing_vamc_facility.feature`) that the WYSIWYG is updated from user interaction in another field.

It also shows that the field values persist on save, are shown in node:view and are loaded into the WYSIWYG on page load.

Not included is complete UI fidelity to the [FIGMA mockup](https://www.figma.com/file/IYpeP2ZAmBTT8jqhdtJklu/Covid-%2F-Facility-Status?node-id=128%3A32180&t=GcTmUSaSHKT2y5BN-0), though some of the work to approximate the mockup has been done.

## Testing done
Manually
Cypress

## Screenshots
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/766573/217236793-7c7e412c-9dd6-4e97-87fc-1cbcdce31869.gif)

## QA steps
### Create a facility
As an admin, create a VAMC Facility
- [x] Fill in any required fields
- [x] Validate that when choosing a COVID-19 Status that the WYSIWYG changes boilerplate copy, replacing the old copy
- [x] Validate that you can select all the copy and replace it with your own copy
- [x] Save the facility node
- [x] Validate that the node:view shows the data that was in the Details 
- [x] Click "Edit"
- [x] Validate that your own copy is showing in the COVID-19 Status Details WYSIWYG

### Edit a facility
As an editor, edit a VAMC Facility
- [x] Validate that on load, the COVID-19 Details field uses boilerplate copy, based on the default selection of the radio button
- [x] Validate that when choosing a different COVID-19 Status that the WYSIWYG changes boilerplate copy, replacing the old copy
- [x] Validate that you can select all the copy and replace it with your own copy
- [x] Save the facility node
- [x] Validate that the node:view shows the data that was in the Details 
- [x] Click "Edit"
- [x] Validate that your own copy is showing in the COVID-19 Status Details WYSIWYG

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-02-07 12:00 UTC, omahane commented
The Cypress tests show as failing due to `behavioral/content_release.feature`:
> 1) Content Release
       The content release page should show a pending default release initiated from the command line:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: 'Preparing' but never did.
      at Context.eval (https://pr12403-yjq5zexhavmhassuj4kctou3kauqjue2.ci.cms.va.gov/__cypress/tests?p=tests/cypress/integration/behavioral/content_release.feature:73222:28)
      at Context.resolveAndRunStepDefinition (https://pr12403-yjq5zexhavmhassuj4kctou3kauqjue2.ci.cms.va.gov/__cypress/tests?p=tests/cypress/integration/behavioral/content_release.feature:27189:29)
      at Context.eval (https://pr12403-yjq5zexhavmhassuj4kctou3kauqjue2.ci.cms.va.gov/__cypress/tests?p=tests/cypress/integration/behavioral/content_release.feature:26510:35)

The Cypress test I added (`behavioral/content_editing_vamc_facility.feature`) passed.

2023-02-07 13:19 UTC, ndouglas commented on tests/cypress/support/commands.js
> +Cypress.Commands.add("read_ckeditor", (element, content) => {
trying to figure out why I made `type_ckeditor` snake_cased instead of camelcased 🤔

2023-02-07 13:19 UTC, ndouglas commented on tests/cypress/integration/behavioral/content_editing_vamc_facility.feature
> +    And I wait "2" seconds
Are these lines still necessary with the 5 second delay in `read_ckeditor`?

2023-02-07 13:33 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +
Nice!

2023-02-07 13:33 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +      }
Could this be factored out into a separate method?  Or two?  Or three?

2023-02-07 13:33 UTC, ndouglas commented on tests/cypress/support/commands.js
> +Cypress.Commands.add("read_ckeditor", (element, content) => {
I'm confused about what this function is doing exactly.  

Above:

```
Then(`I should see {string} in ckeditor {string}`, (value, label) => {
  cy.read_ckeditor(label, value);
});
```

I feel like that's expecting that `cy.read_ckeditor()` will perform an assertion, since there's nothing explicitly making an assertion anywhere else.

But the only place `content` is used is in `win.CKEDITOR.instances[element].getData(content);` -- which doesn't look to me like it takes an argument:

![Screen Shot 2023-02-07 at 8 28 48 AM](https://user-images.githubusercontent.com/1318579/217257847-b5eca34d-8e73-48e8-9eb0-e54e636601d1.png)

and it doesn't seem to me to perform any assertions.

I feel like `read_ckeditor` should retrieve the data and nothing else -- maybe we want to log it, maybe we want to check if it _contains_ a string, or if it _exactly matches_ a string or a regex, etc.

Then the step definition for `I should see {string} in ckeditor {string}` should contain the assertion itself.

2023-02-07 13:56 UTC, omahane commented on tests/cypress/support/commands.js
> +Cypress.Commands.add("read_ckeditor", (element, content) => {
> I feel like read_ckeditor should retrieve the data and nothing else -- maybe we want to log it, maybe we want to check if it contains a string

@ndouglas Yes, that's definitely what I was going for, checking to see if the WYSIWYG has certain text in it. It looks like I missed the mark, though. I'm not sure how to get that assertion in there. Also, I was having no luck with debugging a Cypress test as I might other JS, no matter the number "debugger"s I put in.

2023-02-07 14:03 UTC, ndouglas commented on tests/cypress/support/commands.js
> +Cypress.Commands.add("read_ckeditor", (element, content) => {
I think you can just do `return cy.wrap(win.CKEDITOR.instances[element].getData()` in `read_ckeditor`.  

Then in the step definition, you can do `cy.read_ckeditor(label).should('contain', value)`.  I _think_ that'll work.

Cypress is definitely... an experience to debug.  And in general.  Its very unusual and doesn't resemble anything else in the space AFAICT.  `console.log` doesn't go where you expect.  I didn't have much luck with the debugger either -- maybe there's something we're both missing.

I typically end up doing very caveman-debugging stuff.

I assume that at some point another tool will come along that'll replace Cypress and do so in an elegant, more JS-like kind of way.  It'll probably come just as we finally understand Cypress 😩

2023-02-07 15:45 UTC, JayDarnell commented
QA passes. Waiting on a code refactor before I do a code review.

2023-02-08 14:20 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +      && empty($node->get("field_supplemental_status_more_i")['0']->getValue())) {
**question**: How did you develop this?  Because this sort of thing with the fielditemvaluelists and the fielditemvalues and entityreferencevalues and so forth is a nightmare to me.  I tend to write unit tests just so I can more-or-less know in real time just what the heck is going on.  But this is a private method so it's excruciating to test in PHPUnit.

2023-02-08 14:20 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    $statusIsEmpty = FALSE;
**suggestion**: This seems like a misleading variable name, since it's only TRUE if the 'status' field is set to something.

2023-02-08 14:20 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    $chosen_term_description = "";
**nitpick**: Setting a default value for this variable seems unnecessary.

2023-02-08 14:20 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +      $widget_description = $form['field_supplemental_status_more_i']['widget']['0']['#description']->__toString();
**thought**: I think this conceals a call to the Drupal string translation service, or some other service, IDK which.  i.e. somewhere in the called code there's a method that says `return \Drupal::stringTranslation->translate($this);` or something like that.  That makes adding unit tests a PITA.

That's not really an issue for right now, but another thing to think of for #10805.

2023-02-08 14:20 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    . $term_storage->load($status)->getDescription();
**nitpick**: I believe will die if there's no corresponding term for `$status`, i.e. if `load($status)` returns NULL.  Perhaps it should because it indicates a problem with the data integrity of the site, but I'd prefer it be an explicit exception.

2023-02-08 14:20 UTC, ndouglas commented on tests/cypress/integration/behavioral/content_editing_vamc_facility.feature
> +    When I am at "/alaska-health-care/locations/anchorage-va-medical-center"
**thought**: Because this uses an existing node, this can cause problems.  For instance, if the test fails, the node is left locked, which makes it aggravating to develop the test.

It's preferable to create a new, clean node for each test.

This likely has to wait until #12463.

2023-02-08 14:25 UTC, ndouglas commented
Cypress test failures appear legit:

https://user-images.githubusercontent.com/1318579/217557508-6fbd4816-2772-4b6c-ba1e-10b1a477fe65.mp4

2023-02-09 15:22 UTC, omahane commented on tests/cypress/integration/behavioral/content_editing_vamc_facility.feature
> +    When I am at "/alaska-health-care/locations/anchorage-va-medical-center"
I changed this to create a new one as an admin with only the required fields. As as soon as someone (perhaps me or another developer) takes on #12463, we can refactor the node creation part out.

2023-02-09 15:22 UTC, omahane commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    $chosen_term_description = "";
I agree. That's a holdover from when it was being set inside a condition.

2023-02-09 15:23 UTC, omahane commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    $statusIsEmpty = FALSE;
I agree. I changed it.

2023-02-09 15:25 UTC, omahane commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    && isset($node->get("field_supplemental_status")['0']->getValue()['target_id'])) {
I changed this.

2023-02-09 15:25 UTC, omahane commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    if (isset($node->get("field_supplemental_status")['0'])
OK, using only single quotes now.

2023-02-09 15:26 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    && isset($node->get("field_supplemental_status")['0']->getValue()['target_id'])) {
I guess it's cast transparently? 🤔

2023-02-09 15:28 UTC, omahane commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    return $statusIsEmpty;
Wow, _sounds_ like both useful and daunting for me, especially as blocker for this issue, which is one of our sprint goals. This is the first I'm hearing of bundle classes, so I'd need to do a little more research before I committed to this.

2023-02-09 15:30 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    return $statusIsEmpty;
Yeah, totally **not blocking** this PR.  Just a thought of how we can improve the codebase in the future.

2023-02-09 15:41 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +      && empty($node->get("field_supplemental_status_more_i")['0']->getValue())) {
They're not fun TBH.  I'm hoping to make it better.

2023-02-09 16:34 UTC, omahane commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    . $term_storage->load($status)->getDescription();
If it dies on that. It will do it here, first on line 239   
```
 $terms_text[$status]['name'] = $term_storage->load($status)->getName();
 $terms_text[$status]['description'] = $term_storage->load($status)->getDescription();

```
I am not sure exactly how to defend against that here. I'm seeing other places in the code where we go loading a term or terms without accounting for the null case, but that doesn't make it right, of course.

2023-02-09 16:50 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    . $term_storage->load($status)->getDescription();
You can't defend against it, realistically, but you can do something like this (not tested):

```php
$term = $term_storage->load($status);
if (!$term) {
  throw new \Exception('Term not found.');
}
```

Otherwise the error will be something like "Can't call getName() on null" or something like that.  It'd still give the line number, so we'd probably figure it out pretty quickly.  🤷🏻 

It will probably never matter, and like you said, we definitely don't check return values very often.

So... eh, nitpicky.

2023-02-09 16:53 UTC, ndouglas reviewed
Looks great to me 🙂   Thank you!

2023-02-10 16:58 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    if (isset($node->get('field_supplemental_status')[0])
I'm surprised by the [0] values in this section. The $node parameter passed into this function comes from `$node = $form_object->getEntity();` above. I don't understand the need for the [0] in each of these lines. `$node->get('field_supplemental_status')->value` seems like it should work to me instead of the `[0]->getValue()` but maybe this is some strange Drupal thing because we're in an EventSubscriber vs an old school .module form_alter. @swirtSJW any thoughts?

2023-02-10 17:42 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    if (isset($node->get('field_supplemental_status')[0])
I dunno.  It should work and should be the ideal.  DId you test that it didn't work?

2023-02-13 20:28 UTC, JayDarnell commented
@christianmburk QA steps pass. The only strange thing I noticed is that trying to use CMD+A on my mac to select all the text in the new field doesn't work. CMD+A will select all the text but when I release the keys the text is no longer selected. I've never seen this behaviour before. 

If I try to use CMD+A to select all the text in the VAMC system service description field on the VAMC System Health Service type it works as expected. Have you seen this behaviour?

2023-02-13 20:53 UTC, omahane commented
> 

It was the way the interpolated string was being transpiled from ES6 to JS. It was being prepended with an empty string. Who can say why? I put in a `<p>` to give CKEditor a bone to chew.
<img width="1840" alt="Screen Shot 2023-02-13 at 2 49 39 PM" src="https://user-images.githubusercontent.com/766573/218572006-fe361175-d3f6-429f-a8d1-f73278189e0e.png">

2023-02-14 16:40 UTC, swirtSJW approved these changes
Outstanding work @omahane   I left only a couple of minor suggestions.  Do not feel you have to act on any of them.

2023-02-14 16:40 UTC, swirtSJW commented on config/sync/field.field.node.health_care_local_facility.field_supplemental_status_more_i.yml
> +description: 'Add relevant details about how this status will impact Veterans and visitors. This section is pre-populated with suggested text based on the level you selected but is editable to in ord
**Could:**
```suggestion
description: 'Add relevant details about how this status will impact Veterans and visitors. This section is pre-populated with suggested text based on the level you selected, but is editable to in order to make changes that fit your unique situation.'
```

2023-02-14 16:40 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/css/set_covid_term_text.css
> +
Code style, should be only one trailing empty line.
```suggestion
```

2023-02-14 16:40 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/js/set_covid_term_text.js
>  })(Drupal);
Code style
```suggestion
})(Drupal);

```

2023-02-14 16:42 UTC, omahane commented on config/sync/field.field.node.health_care_local_facility.field_supplemental_status_more_i.yml
> +description: 'Add relevant details about how this status will impact Veterans and visitors. This section is pre-populated with suggested text based on the level you selected but is editable to in ord
You don't need that comma as the clause at the end is not an independent one. It has no subject.

2023-02-14 16:45 UTC, omahane commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> -const USER_CMS_HELP_DESK_NOTIFICATIONS = 4050;
Thank you for doing that.

2023-02-15 12:20 UTC, omahane commented
@ndouglas I successfully ran Cypress in a terminal in the PR environment:
<img width="1796" alt="Screen Shot 2023-02-15 at 6 19 00 AM" src="https://user-images.githubusercontent.com/766573/219025887-fb56c129-dd0f-4122-a100-6baf66777225.png">

2023-02-15 12:21 UTC, ndouglas commented
Great news!  If there are any issues with reliability, etc I'll take care of 'em 🙂

2023-02-24 18:06 UTC, ryguyk commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +
I'm curious about this change. Am I understanding correctly that it's simply a matter of not wanting the constant defined outside the class when it is only needed inside the class?

2023-02-24 18:34 UTC, ndouglas commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +
Also that the constant "comes along" with the class/interface if you refer to it from another namespace.  Simpler `use` statement.  And for encapsulation purposes you can alter the visibility of a class constant, but not (I believe) a constant defined outside a class.  And I just like it because then you're still defining one thing inside a file, rather than two things, one of which might easily be missed if you need to copypasta or whatever.

2023-02-26 23:45 UTC, ryguyk requested changes
I reviewed the JS work. I shared a few thoughts with some small requested changes.

2023-02-26 23:45 UTC, ryguyk commented on docroot/modules/custom/va_gov_vamc/js/set_covid_term_text.es6.js
>      });
**CONSIDER**
It feels like there is a cleaner way to handle getting this `statusId` value:
```
document.querySelector('input[name="field_supplemental_status"]:checked')?.value;
```

**Better yet**, this function `wysiwygSetter` feels like it should be getting the event passed in as a parameter, which would have the clicked option as an attribute:
```
const wysiwygSetter = e => {
   const statusId = e.target.value;
}
```

2023-02-26 23:45 UTC, ryguyk commented on docroot/modules/custom/va_gov_vamc/js/set_covid_term_text.es6.js
> +        iframeDocument.body.innerHTML = `<div>${drupalSettings.vamcCovidStatusTermText[statusId].description}</div>`;
**SHOULD**
It seems possible that `statusId` could be undefined. It also seems possible, though less likely, that `vamcCovidStatusTermText` and even `drupalSettings` might be undefined. This might not actually result in any apparent error to the editor, as it'll likely just result in keeping the `innerHTML` property empty, but it'd throw an error in the background and it'd probably be a good idea to account for it.

This can likely be achieved with some optional chaining:
```
iframeDocument.body.innerHTML = `<div>${drupalSettings?.vamcCovidStatusTermText?.[statusId]?.description || ''}
```

2023-02-26 23:52 UTC, ryguyk commented on docroot/modules/custom/va_gov_vamc/js/set_covid_term_text.es6.js
> +        iframeDocument.body.innerHTML = `<div>${drupalSettings.vamcCovidStatusTermText[statusId].description}</div>`;
Note: With my other suggestions, it seems `statusId` should never be undefined. Still, I think this is good to consider.

2023-02-27 19:26 UTC, omahane commented on docroot/modules/custom/va_gov_vamc/js/set_covid_term_text.es6.js
> +        iframeDocument.body.innerHTML = `<div>${drupalSettings.vamcCovidStatusTermText[statusId].description}</div>`;
Based on our conversation, as we don't have optional chaining and the mostly likely outcome is going to be some text the editors are going to replace, the checks don't seem worth it.

2023-03-01 15:26 UTC, omahane commented
<img width="977" alt="Screen Shot 2023-03-01 at 9 25 41 AM" src="https://user-images.githubusercontent.com/766573/222184561-f56933e6-325f-4bd7-a53a-356baa92edec.png">

Tests passing and worked approved.

2023-03-01 16:02 UTC, merged

2023-03-01 19:58 UTC, ElijahLynn commented
From [Slack](https://dsva.slack.com/archives/CJT90C0UT/p1677695837594769), this merge is causing tests to fail on STAGING with: 

> Expected to include "Visitors are welcome"

![image](https://user-images.githubusercontent.com/1504756/222252016-01ffa09b-6829-4387-959c-b42124311cf7.png)