VACMS-10735: Daily Form Migration CSV validation checks
department-of-veterans-affairs/va.gov-cms pull request #12421
Opened 2023-02-02 21:27 UTC by chri5tia

## Description

Relates to #10735

## Testing done
Not yet

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-02-08 19:33 UTC, jilladams commented
@dsasser not sure if you and Christia discussed this PR before she left? Added you as reviewer, holler if this is news / you have questions.

2023-02-08 22:02 UTC, dsasser commented
> @dsasser not sure if you and Christia discussed this PR before she left? Added you as reviewer, holler if this is news / you have questions.

I paired with Christia on this, so I don't think I should be the reviewer. I'll tag Swirt as he was involved with some conversations around the implementation.

2023-02-10 17:22 UTC, swirtSJW requested changes
A few questions and some suggestions.

One test that seems missing, which is one of the basis for the original ticket, is checking the date on the csv to make sure we are not continually downloading the same version (meaning they are not updating it nightly upstream).  It could be a followup ticket if you prefer, but seems to be a pretty likely point of failure.

2023-02-10 17:22 UTC, swirtSJW commented on scripts/tasks/VACMS-10735-Forms-CSV-migration-validation.php
> +  }
Do we need an explicit exit 0 ?

2023-02-10 17:28 UTC, swirtSJW commented on scripts/tasks/VACMS-10735-Forms-CSV-migration-validation.php
> +  }
Disregard.  these are all running serially, so can not exit 0 if success.

2023-02-10 17:28 UTC, swirtSJW commented on scripts/tasks/VACMS-10735-Forms-CSV-migration-validation.php
> +  }
Disregard, running serially.

2023-02-10 17:30 UTC, ndouglas commented on tasks-periodic.yml
> +            va/background/daily/migrate/csv_check
Yeah, how it works is the following:

```
          # Unless something goes wrong, return 0 (success).
          exit_code=0
          # an array of tasks
          tasks=(
            va/background/daily/migrate_copy/va_forms_csv_source
            va/background/daily/migrate/csv_check
            va/background/daily/migrate/va_forms
            va/background/daily/update/taxonomy_entity_index
          )
          # if an error occurs, add the exit code (nonzero) to the exit_code variable
          trap '{ (( exit_code |=\$? )); }' ERR
          # execute every dadblamed task, regardless of whether it succeeds or fails
          for i in "\${tasks[@]}"; do
            task --taskfile=./tasks-periodic.yml \$i
          done
          # change the error handler back to nothing
          trap - ERR
          # return an exit code that is the sum of all exit codes
          # if all succeeded, then this is zero and indicates success
          # otherwise, it is nonzero, indicates failure, a message gets posted to Slack, etc
          exit \$exit_code;
```

So this csv_check, if its success is a dependency for another task, should be mentioned in the `deps:` section of that task.  That will cascade success/failure correctly and run the job only if its dependencies succeed.

2023-02-10 17:37 UTC, swirtSJW commented on tasks-periodic.yml
> +            va/background/daily/migrate/csv_check
@ndouglas Probably the deps: is the more proper way to handle it, but just for my own knowledge, would moving the script call like this achieve the same kind blocking behavior?
![image](https://user-images.githubusercontent.com/5752113/218158648-7d1bdc8c-c8e3-4e94-bbb7-83d54cbf142c.png)

2023-02-10 17:39 UTC, ndouglas commented on tasks-periodic.yml
> +            va/background/daily/migrate/csv_check
Yeah, that'll work and is simpler; any failure by any of the `cmds` will cause the `va/background/daily/migrate/va_forms` task to stop right there and not execute any further commands.

2023-02-10 17:53 UTC, jilladams commented
@swirtSJW thanks much for the feedback. Are you willing to update comments to clarify Must, Should, Consider? Christia will come back to this after a couple weeks away so will be helpful to understand that for getting it all handled.

2023-02-11 02:37 UTC, swirtSJW commented on tasks-periodic.yml
> +            va/background/daily/migrate/csv_check
@chri5tia 
**Must:** Move the the drush command into the migrate/va_forms task so that it will prevent the migration from running if the tests fail.   
https://user-images.githubusercontent.com/5752113/218158648-7d1bdc8c-c8e3-4e94-bbb7-83d54cbf142c.png

The way it is currently written, the tests will run, but everything else will still run if they fail, and the failure should prevent the migration from running.

2023-02-13 23:10 UTC, swirtSJW approved these changes
I made the changes that were suggested in review.  I also added the drush alias so it will run when called on various environments.  I also changed the command from `drush src` to drush `scr`.  The former not being a command.

In testing: I ran the drush command locally
and it passed,
![image](https://user-images.githubusercontent.com/5752113/218595111-7be2be2d-e56a-4ec4-939b-0d3734e5820c.png)

Then I changed the filename it was looking for and it failed as expected
![image](https://user-images.githubusercontent.com/5752113/218595046-7f2604a9-7cd8-494f-98da-d04339f49726.png)

2023-02-14 00:04 UTC, dsasser approved these changes

2023-02-14 00:12 UTC, dsasser commented
Tested 3 scenarios:
1) valid file
2) Changed header values
3) Empty file

All produced the expected result:
<img width="776" alt="Screen Shot 2023-02-13 at 4 10 37 PM" src="https://user-images.githubusercontent.com/221539/218604491-5505380a-e210-463a-941f-647463483323.png">

2023-02-14 00:13 UTC, merged