VACMS-12303: add menu section for lovell menu items in parent list
department-of-veterans-affairs/va.gov-cms pull request #12550
Opened 2023-02-09 22:54 UTC by JayDarnell

## Description

Closes #12303 

## Testing done

Manual testing

## Screenshots

LOVELL - Parent select list before code change
<img width="1689" alt="Screenshot 2023-02-09 at 5 31 56 PM" src="https://user-images.githubusercontent.com/21045418/217955654-a0ed948f-8309-4a13-8423-49c8684aa893.png">

LOVELL - Parent select list after code change
<img width="1699" alt="Screenshot 2023-02-09 at 5 32 19 PM" src="https://user-images.githubusercontent.com/21045418/217955725-0be1b0ea-d4e2-472c-b0ea-2e5995ae4e8d.png">

OTHER - Parent select list before code change
<img width="1693" alt="Screenshot 2023-02-09 at 5 52 31 PM" src="https://user-images.githubusercontent.com/21045418/217957358-c40d789e-863b-4d63-a3ef-466099687c9a.png">

OTHER - Parent select list after code change
<img width="1690" alt="Screenshot 2023-02-09 at 5 52 45 PM" src="https://user-images.githubusercontent.com/21045418/217957369-bf6c3625-3ddb-473a-b2eb-ac2b446be41a.png">

## QA steps

**Lovell Items**

- [ ] Log into the site as an admin
- [ ] Visit /admin/structure/menu/manage/lovell-federal-health-care (you'll be clicking edit for the menu items below)
- [ ] In a separate browser window log in as Katie.Yearley@va.gov
- [ ] Visit /node/53388/edit
- [ ] Cross reference the list of menu options available in the **Parent link** field with the entire menu in your admin tab
- [ ] Verify that the suffix added to each menu option in the **Parent link** field matches the **Menu Section** field for each menu item in your admin tab

**Other Items**

- [ ] Log out as Katie.Yearley@va.gov
- [ ] Log in as Samuel.Hudson@va.gov
- [ ] Visit /node/23403/edit
- [ ] Verify that the options for the Parent link are unchanged compared to the screenshot above

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`

2023-02-10 15:30 UTC, swirtSJW reviewed
Looking good.  Only a couple questions/suggestions

2023-02-10 15:30 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +use Drupal\va_gov_lovell\LovellOps; // phpcs:ignore
why phpcs ignore?

2023-02-10 15:30 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      $type = $this->checkForLovellSubSystem($alias)
By setting this first, aren't we causing this to bypass any of the other handling that prevents detail pages from being put in certain parts of the menu?

2023-02-10 15:30 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      // By setting this value this item will be excluded.
This comment is a bit out scope.  It is describing  how code someplace else is going to behave.  That comment or something similar should be near where the code is that is calling this function.

2023-02-10 16:04 UTC, JayDarnell commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      // By setting this value this item will be excluded.
Good suggestion.

2023-02-10 16:09 UTC, JayDarnell commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      $type = $this->checkForLovellSubSystem($alias)
This function sets the type based on the first check that evaluates to true. That type is returned to the calling function and then passed as a parameter to addAllowedParent. Because this type doesn't match any of the checks in that function, these items are not added to the menu which is the goal. There are only two menu items that would satisfy this first check, these are the menu items for the two subsystems which we don't want users to see.

2023-02-10 17:16 UTC, omahane requested changes
QA passes. I only think the comments need to be clearer (see Steve's suggestion and my own).

2023-02-10 17:16 UTC, omahane commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +        // The Lovell menu contains section information for each menu item.
I think it would helpful to call out specifically that Lovell menu is the only one with this field `field_menu_section'`, which makes this only apply to Lovell.

2023-02-10 18:16 UTC, JayDarnell commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +        // The Lovell menu contains section information for each menu item.
Good suggestion.

2023-02-13 19:54 UTC, omahane approved these changes
QA passes. The comment changes are great.

2023-02-13 19:56 UTC, merged