VACMS-12586: support tricare service names & descriptions...
department-of-veterans-affairs/va.gov-cms pull request #12720
Opened 2023-02-22 23:01 UTC by JayDarnell

... on VAMC System Health Service nodes.

## Description

Closes #12586 

## Testing done

Manual testing

## Screenshots

## QA steps

-- coming soon --

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`

2023-02-23 22:59 UTC, omahane commented
@JayDarnell 
I did a search of the `select` element because I noticed one item we had **not** accounted for:
"My HealtheVet coordinator"

<img width="551" alt="Screen Shot 2023-02-23 at 4 55 00 PM" src="https://user-images.githubusercontent.com/766573/221049560-c83e96a6-ca5e-4632-bbe1-b87bbc0cf54b.png">

If you winnow "Vet", you should be able to get all of them, as I did a search for the string and these were returned:

```
<option value="39" class="hidden-option">Homeless Veteran care </option>
<option value="54" class="hidden-option">LGBTQ+ Veteran care </option>
<option value="152" class="hidden-option">Minority Veteran care </option>
<option value="56">My HealtheVet coordinator </option>
<option value="57" class="hidden-option">Women Veteran care </option>
```

2023-02-24 06:00 UTC, omahane requested changes

2023-02-24 06:00 UTC, omahane commented on docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
> +      const winnowTricareServices = (options) => {
I feel like there's a way to use `docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js` to winnow this (perhaps with a light refactor), but I am  just not sure how. Though, to be honest, I like the way you wrote this better than what I wrote in "limit_lovell".

2023-02-24 06:00 UTC, omahane commented on docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
> +              (tricareSystem && option.text.includes("Veteran"))
If you use "Vet", you can also remove "My HealtheVet coordinator", which maybe we should.

2023-02-24 06:01 UTC, omahane commented
@JayDarnell I went through all the QA steps without issue!

2023-02-24 15:22 UTC, JayDarnell commented on docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
> +      const winnowTricareServices = (options) => {
I could move this into va_gov_lovell. I'm not sure how to reference the isTricareSystem() function across drupal behaviors but I'll look into that today to see if it is possible.

2023-02-24 18:09 UTC, JayDarnell commented on docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
> +      const winnowTricareServices = (options) => {
I figured out how to do this. I'm pulling the winnower out into the va_gov_lovell module and the isTricareSystem function is part of that code. I have fixed it so that function is available to the va_gov_backend module.

2023-02-24 18:38 UTC, JayDarnell commented on docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
> +              (tricareSystem && option.text.includes("Veteran"))
I am still a little on the fence about this suggestion but I have implemented the necessary change. I dislike the fact that a service could be added with "vet" in the name in some capacity but couldn't think of many scenarios where this would apply. We can always revert this to Veteran with a very small code change so I decided to go for it.

2023-02-24 22:22 UTC, swirtSJW reviewed
Looking good overall Jay.  Just wondering if we had some changes escape the one View Display for VAMC.

2023-02-24 22:22 UTC, swirtSJW commented on config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml
> -    - field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name
Did this need to be added to the VBA View?  I am surprised to see this here.

2023-02-24 22:22 UTC, swirtSJW commented on config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
> -    - field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name
Should this be on the default View?  I was expecting to only see it on the VAMC display.

2023-02-24 22:22 UTC, swirtSJW commented on config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vet_center_service.yml
> -    - field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name
Also seems misplaced.  I think we wanted to only override the VAMC display.

2023-02-24 22:22 UTC, swirtSJW commented on config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_specific_service.yml
> +label: 'Show for TRICARE Facilities only'
```suggestion
label: 'Show for TRICARE Facilities only.'
```

2023-02-24 22:22 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
>              .getElementById(`${service.id}-services-general-description`)
Note to self, these should all be moved to va_gov_facilities in a different ticket.

2023-02-27 20:10 UTC, omahane commented on config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml
> -    - field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name
I don't see that field in the display, even though it shows here.
<img width="692" alt="Screen Shot 2023-02-27 at 2 09 26 PM" src="https://user-images.githubusercontent.com/766573/221672579-f7610c20-da96-4228-82d4-32ac2d45c392.png">
https://pr12720-exkvfvxerhxgbehwxuhnolqlpjvti0ob.ci.cms.va.gov/admin/structure/views/view/health_care_service_names_and_descriptions/edit/entity_reference_vba_services

2023-02-27 20:23 UTC, omahane commented on config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml
> -    - field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name
All of the term's fields are listed all displays. Here's from VBA:
YML on the left, the fields from the UI on the right
<img width="1732" alt="Screen Shot 2023-02-27 at 2 19 18 PM" src="https://user-images.githubusercontent.com/766573/221676961-2edcf702-7734-4057-a92e-f537d2b22db7.png">

2023-02-27 21:56 UTC, swirtSJW commented on config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
> -    - field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name
Mystery solved.

2023-02-27 23:06 UTC, omahane commented on config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml
> -    - field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name
@JayDarnell https://dsva.slack.com/archives/C0FQSS30V/p1677535034188749?thread_ts=1677527521.287719&cid=C0FQSS30V

2023-02-28 15:03 UTC, JayDarnell commented on config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml
> -    - field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name
Yeah, when I added the new field to the taxonomy it was added to all the displays for that taxonomy. It sounds like we are all in agreement that this is now okay.

2023-02-28 15:04 UTC, JayDarnell commented on config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vet_center_service.yml
> -    - field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name
See above comment.

2023-02-28 15:06 UTC, JayDarnell commented on config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_specific_service.yml
> +label: 'Show for TRICARE Facilities only'
For consistency I think we should leave punctuation off. We have other checkboxes like this one and none of them use punctuation for the labels:

Show for VAMC Facilities
Show for VBA Facilities
etc.

2023-02-28 15:06 UTC, JayDarnell commented on docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
>              .getElementById(`${service.id}-services-general-description`)
Do you want me to make a ticket for this @swirtSJW?

2023-02-28 15:16 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
>              .getElementById(`${service.id}-services-general-description`)
That would be great Jay.

2023-02-28 15:19 UTC, swirtSJW approved these changes

2023-02-28 16:01 UTC, merged

2023-02-28 18:37 UTC, JayDarnell commented
Merging as all requirements were previously met (QA pass, code review pass) I had to update the branch with the latest from main