VACMS-13070: New VA Benefits Taxonomy
department-of-veterans-affairs/va.gov-cms pull request #13154
Opened 2023-04-03 19:20 UTC by chri5tia

## Description

Relates to #13070
#13071 
#13206 
#13231 
#13141 
#13075 

## Testing done
Manual functional testing.
Automated testing.

## Screenshots
n/a

## QA steps
1. As a user with uid 4186 with user role administrator:
   - [ ] Go to Go to https://cms-i7n92wfzswpe358hivrspihf2ntzshzp.ci.cms.va.gov/admin/structure/taxonomy/manage/va_benefits_taxonomy/add

2. Under **Benefit name**:
   - [x] Enter a test **Official Benefit name** shorter than 255 characters, such as `VA Benefit test 1`; is a required field
   - [x] Enter a random test **VA Benefit API ID** value; is a required field
   - [x] Enter test **Alternate benefit name(s)** with comma separated values; not a required field

3. Under **Benefit Relationships**:
   - [x] Enter a test **Related legislation** external URL, such as `https://va.gov` and Link text; not a required field
   - [x] Click **Add another link**
   - [x] Enter a test **Related legislation** internal URL, such as `Post-9/11 GI Bill monthly housing allowance (47411)` and link text
   - [ ] Search in the **Pre-requisite benefits** field for `VA Benefit Test 2` and add it; not a required field
   - [ ] Search in the **Co-considered benefits** field for `VA Benefit Test 3` and add it; not a required field

4. Under **Benefit Description**:
   - [x] Enter test **Teaser summary** summary plain text. The counter should go down and into the negative after 300 characters; not a required field
   - [x] Enter test **Brief summary** summary rich text limited text. The counter should go down and into the negative after 500 characters; not a required field
   - [x] Enter test **Longer summary** summary rich text limited text, uncounted characters; not a required field
  
5. Under **Benefit Eligibility**:
   - [x] Select one or more checkboxes for **Beneficiaries**; this is a required field
   - [ ] Enter test rich text limited text in **Eligibility summary**, uncounted characters; not a required field

6. Under **How to apply**:
   - [x] Search for a form in **Related VA Form** field, such as `About VA Form 22-8873`; not a required field
   - [x] Enter test rich text limited text in **Preparing to apply**, uncounted; not a required field
   - [x] Enter test rich text limited text in **How to get help with your application**, uncounted; not a required field

7. Under **After you apply summary**:
   - [x] Enter test rich text limited text in **After you apply summary**, uncounted characters; not a required field

8. Under **Editorial workflow**:
   - [x] Select `Published` under **Save as**
   - [x] Enter a test revision log message
   - [x] Click **Save**

9. Logout  
10. As user with uid 4433 with user role content_admin

Go to https://cms-i7n92wfzswpe358hivrspihf2ntzshzp.ci.cms.va.gov/admin/structure/taxonomy/manage/va_benefits_taxonomy/add
   - [x] Validate that you can not edit text in the **Official Benefit name** field or the **VA Benefit API ID** field.

Note: field configs spec to match:
https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit#gid=0
Columns ABGHIJLMN

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [x] Tests have been added if necessary.
- [x] Automated tests have passed.
- [x] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [x] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-04-03 20:12 UTC, chri5tia commented
Not sure the PHP failure is: https://tugboat.vfs.va.gov/log/642b271a63b3e8775edf2bc3

2023-04-06 22:57 UTC, swirtSJW commented
Converted to draft so it does not get merged until complete.

2023-04-06 23:00 UTC, swirtSJW commented on config/sync/taxonomy.vocabulary.va_benefit_taxonomy.yml
> +description: 'Single source of truth for VA Benefits including official names, related legislation, related / pre-requisite benefits, applicat'
If the description is being truncated due to length, we should re-word so it is not cutoff.  If not we should fix wording.

2023-04-06 23:01 UTC, swirtSJW commented on config/sync/syslog.settings.yml
> +_core:
Is this related to this issue?

2023-04-06 23:02 UTC, swirtSJW commented on config/sync/password_policy.password_policy.va_gov_cms.yml
> -send_reset_email: false
The changes in this file seem unrelated and out of place.

2023-04-06 23:03 UTC, swirtSJW commented on config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
> +  field_facility_hours/value:
These changes are very unexpected and should not be here.  It is reverting changes that were made last week.  I think there may have been a misshap with a rebase.

2023-04-07 01:29 UTC, chri5tia commented on config/sync/core.extension.yml
> +  raven: 0
Trying to figure out why this is here. Should it be removed?

2023-04-07 02:38 UTC, chri5tia commented on config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
> +  field_facility_hours/value:
Hey there, I didn't even realize you made these comments. I already pushed revised commits, excluding several unexpected and unrelated files. This should likely address a lot of this.

2023-04-07 02:48 UTC, chri5tia commented on config/sync/password_policy.password_policy.va_gov_cms.yml
> -send_reset_email: false
Oops, some of these slipped by me. Should be fixed.

2023-04-07 03:13 UTC, chri5tia commented
Locked down fields can be seen in the tugboat instance now
![Screenshot 2023-04-06 at 8 12 07 PM](https://user-images.githubusercontent.com/22764938/230533631-aa9cd7b7-72f6-4268-b21a-33e627250f80.png)
 if you log in as a content admin or non admin.

2023-04-07 03:14 UTC, chri5tia commented on config/sync/taxonomy.vocabulary.va_benefit_taxonomy.yml
> +description: 'Single source of truth for VA Benefits including official names, related legislation, related / pre-requisite benefits, applicat'
For sure. We are working on this, thanks for taking a look.

2023-04-07 13:10 UTC, chri5tia commented
Noticing that content that is automatically generated doesn't use rich limited text, so when a non-admin editor goes in, the fields are locked down due. ~~Need to enforce the wywiwyg type and/or figure out how plain text is being used.~~ This seems to be a bug with devel generate. Manually entered fields do not provide another option.

<img width="355" alt="Screenshot 2023-04-07 at 5 54 57 AM" src="https://user-images.githubusercontent.com/22764938/230612652-70e7754c-4a6c-4e15-9b5e-857d7e80f29a.png">

<img width="415" alt="Screenshot 2023-04-07 at 6 06 18 AM" src="https://user-images.githubusercontent.com/22764938/230614161-7d50e2a4-11cd-425d-973e-337c1f3bbfd5.png">

There is also a mysterious failed cypress test relating to campaign pages: https://cms-i7n92wfzswpe358hivrspihf2ntzshzp.ci.cms.va.gov/cypress/screenshots/actual/content_type/campaign_landing_page.feature/Content%20Type%20Campaign%20Landing%20Page%20--%20Log%20in%20and%20create%20a%20campaign_landing_page%20(failed).png

2023-04-07 13:26 UTC, chri5tia commented
@swirtSJW @ndouglas Watch at 45 seconds in on this cypress test as it jumps to the taxonomy menu and goes to the new benefits taxonomy instead of running through the items on the campaign landing page. It's weird and kind of hilarious.
https://cms-i7n92wfzswpe358hivrspihf2ntzshzp.ci.cms.va.gov/cypress/videos/content_type/campaign_landing_page.feature.mp4

2023-04-07 13:28 UTC, ndouglas commented
Yeah, it looks like it finds a link in the admin toolbar and clicks that instead of whatever is expected.

2023-04-07 14:02 UTC, chri5tia commented
@ndouglas 

```
    // VA Benefits
    cy.contains("VA Benefits").scrollIntoView().click({ force: true });
    cy.contains("VA Benefits")
      .parent()
      .within(() => {
        cy.contains("Related benefits").scrollIntoView().click({ force: true });
        cy.contains("Select Benefit Hub(s)").click({ force: true });
      });
```

Maybe we need to remove that second line.

2023-04-07 21:12 UTC, dsasser commented on docroot/modules/custom/va_gov_benefits/va_gov_benefits.module
> +    $form['name']['widget'][0]['value']['#title'] = 'Official Benefit name';
Just a note that this should possible to do with base field overrides, which is config. It is a bit weird to expose the override config. Reading this may be useful https://www.previousnext.com.au/blog/overriding-base-field-labels-and-descriptions-of-drupal-entities-without-custom-code

2023-04-10 17:05 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/va_gov_benefits.module
> +    $form['name']['widget'][0]['value']['#title'] = 'Official Benefit name';
Thanks for this! I assume this can work for taxonomy and not just content type nodes. But will it be clear and obvious to the next developer who needs to change this? I don't like hard-coding content, but doing it this way feels more hidden. I am willing to hear your thoughts on which is the best case scenario for this project and/or best practice.

2023-04-24 20:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_benefits/va_gov_benefits.module
> +function va_gov_benefits_form_alter(&$form, FormStateInterface $form_state, $form_id) {
Is there a reason to have both  a form_alter in the event subscriber and a form_alter here?  If there is not a good reason, it would be helpful to keep them living together.

2023-04-24 21:03 UTC, swirtSJW commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +    $this->lockBenefitName($form, $form_state);
Consider: We are blindly calling these and then checking bundle in each method.   To avoid repeated code can we check the bundle or better yet, the form ID beforehand and then only call the function when needed?  form_alter is pretty generic and gets called a ton of times.

2023-04-24 21:17 UTC, swirtSJW commented on tests/cypress/integration/common/i_create_a_node.js
> +    cy.contains("Why this matters").click({ force: true });
I'm a little concerned about switching to blanket force: true.   It makes it harder to debug with screenshots and videos that cypress creates because it skips all these. 

> We will NOT perform these:
- Scroll the element into view
- Ensure it is visible
- Ensure it is not disabled
- Ensure it is not detached
- Ensure it is not readonly
- Ensure it is not animating
- Ensure it is not covered
- Fire the event at a descendent

Is there a specific issue we are trying to solve?

2023-04-24 21:42 UTC, chri5tia commented on tests/cypress/integration/common/i_create_a_node.js
> +    cy.contains("Why this matters").click({ force: true });
I included this to force local cypress test failures to pass, which seem to affect more than one developer. I can remove them. The error it gets in those places is that it can't find the center of the DOM in order to click it because a modal or some other element is in the way.

2023-04-24 21:43 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +    $this->userPermsService = $user_perms_service;
Thank you for taking a look at that. I assumed they weren't needed but broke things once they were removed. I will focus now on removing them properly instead of whether or not they should be removed.

2023-04-24 21:44 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +    $this->lockBenefitName($form, $form_state);
I may need a recommendation for this. That sounds wise.

2023-05-02 12:29 UTC, chri5tia commented on tests/cypress/integration/common/i_create_a_node.js
> +    cy.contains("Hero banner").click({ force: true });
Updated chained actions to satisfy new chaining standards, and the linter:
https://docs.cypress.io/guides/core-concepts/retry-ability#Actions-should-be-at-the-end-of-chains-not-the-middle

2023-05-02 12:31 UTC, chri5tia commented on tests/cypress/integration/common/i_create_a_node.js
> +    cy.get("#edit-group-va-benefits")
Identified element instead of the verbiage, because cypress testing was finding it in the menu (Taxonomy > VA Benefits) and leaving the campaign landing page.

2023-05-02 12:33 UTC, chri5tia commented on tests/cypress/integration/common/i_create_a_taxonomy_term.js
> +      { force: true }
This is a fake number for now. We can use different criteria once there is an AC for how to restrict the entry.

2023-05-02 20:39 UTC, swirtSJW requested changes
Overall this looks great.  A couple "musts" and a couple "coulds".

2023-05-02 20:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +    }
Could: Reduce lines of code and make the logic a little easier to follow.   If the first if-clause never gets acted on, there is no reason to entertain considering the second.  

```suggestion
    if ($form_object instanceof ContentEntityForm) {
      $bundle = $form_object->getEntity()->bundle();
      if (!$this->userPermsService->hasAdminRole(TRUE) && $bundle === 'va_benefits_taxonomy') {
        $form['field_va_benefit_api_id']['#disabled'] = TRUE;
      }
    }
```

2023-05-02 20:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +    }
Could:  reduce lines of code and unnecesary checks.
```suggestion
    if ($form_object instanceof ContentEntityForm) {
      $bundle = $form_object->getEntity()->bundle();
      if (!$this->userPermsService->hasAdminRole(TRUE) && $bundle === 'va_benefits_taxonomy') {
        $form['name']['#disabled'] = TRUE;
      }
    }
```

2023-05-02 20:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +    $form['relations']['#access'] = FALSE;
Minor concern about blanket hiding this for everyone.  It ties our hands as admins a bit.  However if we need to make it a structured taxonomy with depth and order we can do it by drag and drop through the term list page, so losing this functionality is not a deal breaker.

2023-05-02 20:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +   * Hides relations portion of the form.
Must: needs a param  defined.

2023-05-02 20:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +   */
Must: Needs a param defined.

2023-05-02 20:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_benefits/va_gov_benefits.libraries.yml
Do we need this file?

2023-05-02 20:39 UTC, swirtSJW commented on tests/cypress/integration/common/i_create_a_node.js
> +    cy.get("#edit-group-va-benefits")
Is this line needed?  It doesn't seem to be doing anything.

2023-05-02 20:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_benefits/va_gov_benefits.info.yml
> +core_version_requirement: ^8 || ^9
```suggestion
core_version_requirement:  ^9 || ^10
```

2023-05-02 20:47 UTC, swirtSJW commented
Did design sign off on this?
![image](https://user-images.githubusercontent.com/5752113/235782283-46e6c71f-c7f0-409c-8cb6-acb6b246d3e4.png)

2023-05-02 20:51 UTC, swirtSJW commented
Is this field type right?
![image](https://user-images.githubusercontent.com/5752113/235782853-b48c592a-5992-4dcc-b9da-ad95ad8ad616.png)

I am trying to figure out how we would use a string of free form text.  It seems like there should be shorter sting field with multiple cardinality so then we have a list we can work with.

2023-05-02 20:58 UTC, swirtSJW commented on config/sync/field.field.taxonomy_term.va_benefits_taxonomy.field_enforce_unique_id.yml
> +    limit_validation_to_published: 1
Must:  This should be 0.   We don't want editors creating a second one and then not being able to publish.
![image](https://user-images.githubusercontent.com/5752113/235784595-5b456730-5047-45c1-86f9-12c20c738de7.png)

2023-05-02 20:59 UTC, swirtSJW commented on config/sync/field.field.taxonomy_term.va_benefits_taxonomy.field_enforce_unique_value.yml
> +    limit_validation_to_published: 1
Must:  should be 0
![image](https://user-images.githubusercontent.com/5752113/235784708-9ca38038-2f27-4e1f-a2c0-621fe59db6bc.png)

2023-05-02 21:05 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +    $form['relations']['#access'] = FALSE;
I would defer to your opinion on this. We want to try to keep the taxonomy flat so it seemed like a good idea to hide unnecessary form components. At the same time, a different approach to making taxonomy flat for this taxonomy type would probably be a better move or hide it only for non-admins. 

Would you suggest that I fix this to hide from non-admins only?

2023-05-02 21:23 UTC, chri5tia commented
> Did design sign off on this? ![image](https://user-images.githubusercontent.com/5752113/235782283-46e6c71f-c7f0-409c-8cb6-acb6b246d3e4.png)

Verbiage, field types and content model is documented in the the [spec/content model](https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit#gid=0).

@davidmpickett 
Instead of this help text:

> The "VA Benefit API ID" is used to match the benefit with other external data sources. This value must be exact, or else the desired data will not appear. Once created, this can never be changed (enforced by Drupal).

Can we consider:

"The "VA Benefit API ID" will be used to match the benefit with external data sources. This value must fit specific criteria, [TBD]. Once the API ID is used, is should not be changed. Temporarily, any value will work."

I wonder why we don't disable this field until we have an external data source consuming it and get guidance from those teams for the criteria.

2023-05-02 21:27 UTC, chri5tia commented
> Is this field type right? ![image](https://user-images.githubusercontent.com/5752113/235782853-b48c592a-5992-4dcc-b9da-ad95ad8ad616.png)
> 
> I am trying to figure out how we would use a string of freeform text. It seems like there should be a shorter string field with multiple cardinality so then we have a list we can work with as data.
> 
> If this is the correct field, the help text could be more helpful. Should they separate by commas or new lines?

This field provides information to the end-user only. When someone is looking at the page, they might understand the benefit better under a different name. It will not be referenced in other places.

@davidmpickett 

Instead of the help text

> Add one or more nicknames for the benefit.

Can we consider 

"Add one or more Veteran-facing nicknames for the benefit, separated by commas."

2023-05-02 23:01 UTC, davidmpickett commented
## VA Benefit API ID

### Help text
The "VA Benefit API ID" will be used to match the benefit with external data sources. This value must fit specific criteria [TBD]. Once the API ID is published, it should not be changed.

### How to handle governance of this field (for now)
> I wonder why we don't disable this field until we have an external data source consuming it and get guidance from those teams for the criteria.

Yes. I think that it for the period of initial population of content with the Content Team that this should be set to not required and disabled and/or hidden. Right now doing anything with this is just going to cause unnecessary problems. Technically a call for @wesrowe to make though.

We could probably use some more detailed user permission stories for the the VA Benefit Taxonomy similar to [work I am currently doing](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13272) on Facilities this Sprint. Could be a place for us to collab next sprint?

## Alternate benefit names

### Help Text
> Can we consider
> 
> "Add one or more Veteran-facing nicknames for the benefit, separated by commas."

👍🏻

### Field type questions

@swirtSJW The parallel field on the Service Taxonomy is Common Conditions. A comma-separated list of alternate names for a benefit. 

We could potentially use a different field widget. The single-line text widget is what we use over there. It perhaps gets across the vibe of how much information should be here better.

![Screenshot 2023-05-02 175940](https://user-images.githubusercontent.com/51967950/235803380-00aa6703-2d25-46ff-b631-bbd977283ef9.png)

2023-05-02 23:29 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +    $form['relations']['#access'] = FALSE;
I went with hiding only for non-admins and added a test. Let me know what you think.

2023-05-02 23:34 UTC, chri5tia commented
@davidmpickett I can hide the API field from editors on the back end for now.

2023-05-02 23:43 UTC, chri5tia commented
> We could potentially use a different field widget. The single-line text widget is what we use over there. It perhaps gets across the vibe of how much information should be here better.

@davidmpickett I personally prefer the better visibility of a textarea field since there could be more than one nickname at whatever verbose length.

2023-05-02 23:54 UTC, chri5tia commented on tests/cypress/integration/common/i_create_a_taxonomy_term.js
> +
This test makes sure the form still works in general with respect to fields that have custom code vs. the other test, which is for editor experience. We can change the type of faker data when we further restrict the value rules.

2023-05-03 17:23 UTC, dsasser submitted a review, later dismissed

2023-05-03 17:25 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/va_gov_benefits.info.yml
> +core_version_requirement: ^8 || ^9
Oops, that should have been updated after Steve pointed it out.

2023-05-03 17:29 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/va_gov_benefits.module
Oops, good find.

2023-05-03 17:32 UTC, swirtSJW commented
> @swirtSJW The parallel field on the Service Taxonomy is Common Conditions. A comma-separated list of alternate names for a benefit.
> 
> We could potentially use a different field widget. The single-line text widget is what we use over there. It perhaps gets across the vibe of how much information should be here better.

I think we made a mistake on that one making it blobby, which is why I suggest making this not blobby.  We can't make connections or support chat bot or other consumers as well when this is blobby and they are expected to parse their own blobs.

2023-05-03 17:35 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +  public function lockBenefitName(array &$form, FormStateInterface $form_state) {
I want to hold on this because everything to do with the API is a bit up in the air. By having it separate, it'll be more straight forward to update later, at which point I should consolidate the code. That's my take on it, but I welcome thoughts.

2023-05-03 17:55 UTC, swirtSJW commented
> @swirtSJW It's worth noting that there are other fields that are blobby in this iteration, until we talk to the chatbot team. I like the idea of separating the nicknames for the next phase. We are going to be doing some work to separate components of the eligibility requirements, etc. as well.

Yes, those don't have the hair on the back of my neck standing up the way this one does.  We are taking something that we know is going to have multiple values and are forcing it into a single value field.   We are coming up with a data model that we are going to be feeding to several APIs.   Any one of them might want to have Veterans searching for things that are in common language and not the official term.  I can think of no reason to make that more complicated and have to do a string contains kind of query instead of string equals kind of query.

2023-05-03 18:02 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +  public function lockBenefitName(array &$form, FormStateInterface $form_state) {
Scratch that. Never know when "later" will be.

2023-05-03 18:02 UTC, swirtSJW commented
@davidmpickett and @chri5tia 
VBA benefit API id description seems problematic for me because is it trying to serve both admins (the only people who can set it) and Term editors who can not do anything with it.   We are also trying to explain all the rules and where it will be used.  These kind of things raise anxiety.  I suggest keeping it more generic.

Something like
The "VA Benefit API ID" is the unique identifier for this benefit.  Once it is established, it can not be changed.

2023-05-04 17:02 UTC, wesrowe commented
> > @swirtSJW It's worth noting that there are other fields that are blobby in this iteration, until we talk to the chatbot team. I like the idea of separating the nicknames for the next phase. We are going to be doing some work to separate components of the eligibility requirements, etc. as well.
> 
> Yes, those don't have the hair on the back of my neck standing up the way this one does. We are taking something that we know is going to have multiple values and are forcing it into a single value field. We are coming up with a data model that we are going to be feeding to several APIs. Any one of them might want to have Veterans searching for things that are in common language and not the official term. I can think of no reason to make that more complicated and have to do a string contains kind of query instead of string equals kind of query.

@swirtSJW, the decision to create a comma-separated field was discussed at some length in the MVP finalization meeting with Dave and Danielle. There were several drivers, including that no one knows how a field like this will be used by the Content team or consuming products. So the intent is to use this as a place to jot notes to drive post-MVP iteration. I don't think anyone intends for products to consume this field as-is. We should leave it as a single, comma-separated field as designed, as that's what stakeholders who are closest to the content are expecting and asked for.

2023-05-04 18:40 UTC, chri5tia commented on docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php
> +  ) {
Can't declare a return type for constructor. There is a php bug report for it, as others agree that it seems important to be able to declare `void` here; they marked it as "not a bug":
https://bugs.php.net/bug.php?id=75263

Trying to do so returns an error. 

```
  public function __construct(UserPermsService $user_perms_service): void {
    $this->userPermsService = $user_perms_service;
  }
```

```
Fatal error: Method Drupal\va_gov_benefits\EventSubscriber\BenefitsSubscriber::__construct() cannot declare a return type
```

Is there a way that you have dealt with this?

2023-05-04 18:59 UTC, dsasser submitted a review, later dismissed

2023-05-04 22:12 UTC, jilladams commented
Touched base with Christia in 1:1. I enabled automerge, since: Daniel approved before the last push. This way, when he re-approves, this will merge. @swirtSJW happy to talk through any concerns you have re: follow up tickets that we should create potentially.

2023-05-05 03:54 UTC, swirtSJW approved these changes
Works as intended.  Nice work Christia.

I included a QA check to make sure that unique applied to title.  It worked great.
![image](https://user-images.githubusercontent.com/5752113/236374470-dc3985af-9db3-4d2f-894e-addd26607bdd.png)

2023-05-05 17:05 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/236521520-f9f33735-3f56-40e6-ae51-fc5ad7b160bd.png)

2023-05-05 17:05 UTC, merged