VACMS-10845 Facilities runbook updates
department-of-veterans-affairs/va.gov-cms pull request #13311
Opened 2023-04-14 19:55 UTC by jilladams

## Description

Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10845

Today I updated 9 existing facility runbook tickets to use information from the latest runbooks, as a learning exercise for myself. In the process, I found a few things happening that I opted to standardize here. Feel free to modify this branch directly or propose changes: 
1. Redirect deploy notes were vague. More specific data is useful for building knowledge, so I updated the "Redirects are usually released" language to be specific re: timing / process.
2. Old templates asked for the Facility Locator URL for changes to existing facilities. New ones don't. I added it back in, as it seems useful and we might as well record it if it's available.
3. The markdown around the link to URL Change requests wasn't rendering correctly in Github. TO get the URL to act like a URL, had to update the markdown to display the full URL on its own line. 🤷‍♀️ 
4. Added team, product, and discipline labels where they were missing.

### Definition of Done

- [x] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-04-14 20:36 UTC, swirtSJW commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-closed.md
> +https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+n
Was removing this from a shorter link tag intentional?

2023-04-14 20:38 UTC, swirtSJW commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md
> +- [ ] 5. Create a [URL change request, changing the entry from the old facility URL to the new facility URL.
```suggestion
- [ ] 5. Create a URL change request, changing the entry from the old facility URL to the new facility URL.
```

2023-04-14 20:55 UTC, jilladams commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-closed.md
> +https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+n
Yep. When input that way, in GH front-end, these were rendering as markdown, rather than rendering as a link. After playing with it, it only renders this link as a link if it's only its own line with an empty line above it. (I think it may be due to query parameters.)

2023-04-15 12:55 UTC, omahane approved these changes
I think these are a great improvement. Thanks for looking at this. I had one minor edit, which I must have overlooked when I worked on these last time.

2023-04-17 22:37 UTC, ryguyk commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-closed.md
> +https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+n
This seems to work, at least in this comment.
- [ ] 5. Create a [redirect request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+name%3E) from the URL of the facility to be closed to the URL of its parent system.

2023-04-17 22:48 UTC, jilladams commented
Reverted the commit for markdown changes to the redirect ticket link based on convo w Ryan here, and added a one-line change to fix the new VAMC template where the issue did repro / is fixed by a blank line after `</details>`: https://dsva.slack.com/archives/C0FQSS30V/p1681771043842529?thread_ts=1681502414.393989&cid=C0FQSS30V.

2023-04-17 23:02 UTC, ryguyk commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md
> +Facility locator link: <insert_facility_locator_link>
I see this change in a number of places. I'm not in love with it, personally. Here's why:
1. The wording makes it sound like the facility-locator link is somehow a component of the other link ("including").
2. I'm actually not sure what I'm supposed to put here.  Is the "Link to facility in production" a va.gov link or a CMS link?
3. It's not immediately clear what "Facility locator link" means. There's a placeholder page that is created for facilities that are in VAST and/or Lighthouse but not yet published in Drupal, and that page is the one linked by the facility locator _initially_. But after the CMS page is published, a URL Change Request would have changed this so that the facility locator now links to the CMS-generated page. So, in many cases (including, specifically, this case, a facility name change) the page linked by the facility locator _is_ the va.gov production link. Technically, the original placeholder page still exists, but a redirect would prevent anybody from actually getting there. So I doubt that URL would be useful in this context. So, what exactly are we asking for here and why?

2023-04-17 23:20 UTC, jilladams commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md
> +Facility locator link: <insert_facility_locator_link>
Fair. I did that from a place of ignorance mostly because it used to exist in some templates, and get populated. I, again, am ignorant. Happy to remove it again if it doesn't actually make sense.

2023-04-18 20:07 UTC, jilladams commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md
> +Facility locator link: <insert_facility_locator_link>
@ryguyk is this a blocker for approval from your perspective?

2023-04-19 21:53 UTC, jilladams commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md
> +Facility locator link: <insert_facility_locator_link>
I talked to Christian and understand better now that this is really standing in for Facility API ID. I'll either remove this or change it to be explicit on that.

2023-04-20 21:12 UTC, jilladams commented on .ddev/mutagen/mutagen.yml
> +# https://ddev.readthedocs.io/en/latest/users/performance/#using-mutagen
not sure if I should manually edit this value back to what it was.

2023-04-20 21:14 UTC, jilladams commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-closed.md
> +- [ ] 7. When redirect has been deployed, make these changes. Practice first on staging or a demo environment.
Because we added step 6 to execute the redirect steps, the old 6, 6a, 6b etc became 7, 7a, 7b

2023-04-20 21:15 UTC, jilladams commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-closed.md
> +- [ ] 6. Execute the steps of the URL change request ticket from step 5 above.
New addition to this runbook. Previously we went straight from "request redirect" to "when redirect has been deployed" without a step to implement

2023-04-20 21:17 UTC, jilladams commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md
> +(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change t
Relocated deploy info below the task which will cause deploy.

2023-04-20 21:20 UTC, jilladams commented on .github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md
> +(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change t
deliberately did _not_ relocate these notes here below step 2 where change request gets implemented, because this runbook is more complex with more Engineer steps following.

2023-04-20 21:24 UTC, jilladams commented on .github/ISSUE_TEMPLATE/runbook-vet-center-closed.md
> +(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change t
Added this and step 3 to align with how we're doing this on other runbooks.

2023-04-20 21:58 UTC, jilladams commented
@omahane @swirtSJW @ryguyk : PR updated with notes from today in scrum / refinement, and updated PR description with what's done here in the end post-churn.

2023-04-21 15:41 UTC, omahane requested changes
After that mutagen change is made, I will approve.

2023-04-21 15:41 UTC, omahane commented on .ddev/mutagen/mutagen.yml
> +# https://ddev.readthedocs.io/en/latest/users/performance/#using-mutagen
Well this link returns a 404, so probably not a good change.
```suggestion
# https://ddev.readthedocs.io/en/latest/users/install/performance/
```

2023-04-21 16:27 UTC, jilladams commented
@omahane done!

2023-04-21 17:38 UTC, omahane approved these changes
These are great changes and makes the various processes much clearer.

2023-04-21 18:46 UTC, swirtSJW approved these changes

2023-04-21 19:45 UTC, merged