VACMS-13479: Applies D10-compliant minor changes to custom modules
department-of-veterans-affairs/va.gov-cms pull request #13634
Opened 2023-05-08 17:24 UTC by tonytaylor

## Description

Applies minor changes for D10 compliance to the following custom modules:

- va_gov_api
- va_gov_backend
- va_gov_db
- va_gov_events
- va_gov_facilities
- va_gov_migrate
- va_gov_notifications
- va_gov_post_api
- va_gov_resources_and_support
- va_gov_vamc
- va_gov_vet_center

Relates to #13479 

## Testing done

- Verified no WSOD
- Verified most forms properly render post-refactoring

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-05-08 20:20 UTC, ndouglas reviewed
Mostly solid, but I feel like some merges might've gone the wrong way.

2023-05-08 20:20 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinksValidator.php
Why is this refactor (factoring out common code into TextValidatorTrait) being reversed?

2023-05-08 20:20 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/src/Service/VaGovUrl.php
> +    catch (\Exception $e) {
👍🏻

2023-05-08 20:20 UTC, ndouglas commented on docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContent.php
> +          $this->queueNotification($editor, 'vamc_outdated_content');
Doesn't this undo some of @edmund-dunn's work?

2023-05-08 20:40 UTC, tonytaylor commented
Thanks @ndouglas.  I guess there's some confusion surrounding this.

2023-05-08 23:50 UTC, tonytaylor commented on docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContent.php
> +          $this->queueNotification($editor, 'vamc_outdated_content');
That is @edmund-dunn's work.
I diffed this against the D10 branch to verify.

2023-05-08 23:53 UTC, tonytaylor commented on docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinksValidator.php
These are from the D10 branch.

2023-05-10 16:49 UTC, swirtSJW commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
> -
This is relatively new code that should not be going away.

2023-05-10 16:49 UTC, swirtSJW commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
> +    $this->additionalInfoToPush = $this->facilityNode->get('field_operating_status_more_info')->value;
This change should not be happening.

2023-05-11 17:12 UTC, tonytaylor commented
Thanks guys.  I appreciate the feedback.

I think I've cleaned this up.

2023-05-11 19:13 UTC, ndouglas commented on docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContent.php
> +          $this->queueNotification($editor, 'vamc_outdated_content');
That might be your issue -- I don't know if that work is present in the D10 branch.

2023-05-11 19:18 UTC, ndouglas requested changes
Everything looks wonderful _except_:

Changes to these files appear revert some work that I think was done after the D10 branch was split from `main`:

- `docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinksValidator.php`
- `docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteUrlsAsPathsInLinksValidator.php`
- `docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventDomainsAsPathsInLinksValidator.php`
- `docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventProtocolRelativeLinksValidator.php`
- `docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventVaGovDomainsAsPathsInLinksValidator.php`
- `docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContent.php`
- `docroot/modules/custom/va_gov_notifications/templates/message--va-outdated-content--mail-body.html.twig`
- `docroot/modules/custom/va_gov_notifications/va_gov_notifications.module`
- `docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php`

2023-05-18 13:15 UTC, tonytaylor commented
This was a rather unproductive rabbit hole. Closing.

2023-05-18 13:15 UTC, closed without merging