VACMS-13362: Adds migration yml. Migration tested and passed.
department-of-veterans-affairs/va.gov-cms pull request #13858
Opened 2023-05-26 16:18 UTC by omahane

## Description

Closes #13362 

## Testing done
Manually

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-05-31 03:01 UTC, swirtSJW requested changes
The migration looks great.  I added some suggested changes on the archival part.

2023-05-31 03:01 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
> +    $facility->save();
I am not sure if this creates a new revision or just alters the current.  I am not able to test this right now to know for sure, but please check the revision log display shows this as a new revision attributed to the CMS Migrator.

I think we want to include some other things
```suggestion
    $facility->setNewRevision(TRUE);
    $facility->setUnpublished();
    Assign to CMS Migrator user.
    $facility->setRevisionUserId(1317);
    // Prevents some other actions.
    $facility->setSyncing(TRUE);
    $facility->setChangedTime(time());
    $facility->isDefaultRevision(TRUE);
    $facility->setRevisionCreationTime(time());
    $facility->save();
```

2023-05-31 11:13 UTC, omahane commented on docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
> +    $facilities_to_archive = ['nca_facility'];
Good idea.

2023-05-31 12:30 UTC, omahane commented
@swirtSJW Thank you for the review while on vacation, no less. I have pulled those suggestions in and added QA steps. I'll get someone else to give it a thorough going over.

2023-05-31 13:22 UTC, swirtSJW reviewed
Two thoughts.  On about facility ops, the other about setting facility status to closed and clearing out status morinfo.

2023-06-01 14:15 UTC, omahane commented on docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
> +    $facility_bundles_to_archive = ['nca_facility'];
These thoughts led me to some spelunking, and I saw this in `va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php`, which could be refactored to use `isFacilityWithStatus`:
```
 protected function clearNormalStatusDetails(EntityInterface $entity): void {
    if ($entity instanceof NodeInterface) {
      $facilitiesWithStatus = [
        'health_care_local_facility',
        'nca_facility',
        'vba_facility',
        'vet_center',
        'vet_center_outstation',
      ];
```
Beyond this scope of this work, but thought I'd let you know, @swirtSJW

2023-06-01 15:54 UTC, omahane commented
> To avoid confusion from conflicting data, this should set status to closed, and clear out the status morinfo.

I am unclear what the conflicting data to which you are referring might be. I can see that there may be information in the more info field even if we set it to "closed". Is the idea that we wouldn't want any data in the more info field that would be at odds with the "closed" status. Just trying to confirm. I am going to bring it up in refinement today to get Dave C/Michelle's feedback.

2023-06-01 22:29 UTC, omahane commented
As a follow up, we talked about this change to the ACs in refinement (changing the status and removing the status more info content) and decided to keep those changes in another ticket (if it's decided to do it at all).

2023-06-02 16:19 UTC, dsasser approved these changes

2023-06-02 17:19 UTC, merged

2023-06-07 13:32 UTC, swirtSJW commented
> > To avoid confusion from conflicting data, this should set status to closed, and clear out the status morinfo.
> 
> I am unclear what the conflicting data to which you are referring might be. I can see that there may be information in the more info field even if we set it to "closed". Is the idea that we wouldn't want any data in the more info field that would be at odds with the "closed" status. Just trying to confirm. I am going to bring it up in refinement today to get Dave C/Michelle's feedback.

Answered here  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13362#issuecomment-1580816072

2023-06-09 15:04 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
> +    $facility_bundles_to_archive = ['nca_facility'];
I created a ticket based on this finding https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14045