VACMS-13664: d10-ready custom module updates
department-of-veterans-affairs/va.gov-cms pull request #13999
Opened 2023-06-05 14:28 UTC by tonytaylor

## Description

Applies minor changes for D10 compliance to the following custom modules:

- va_gov_api
- va_gov_backend
- va_gov_db
- va_gov_events
- va_gov_facilities
- va_gov_migrate
- va_gov_notifications
- va_gov_post_api
- va_gov_resources_and_support
- va_gov_vamc
- va_gov_vet_center

Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13664

## Testing done

- Verified no WSOD
- Verified most forms properly render post-refactoring

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-06-05 17:49 UTC, timcosgrove reviewed
Some changes needed, but mostly just more information.

2023-06-05 17:49 UTC, timcosgrove commented on .github/workflows/continuous_integration.yml
> +          category: "/language:${{matrix.language}}"
These and following shouldn't be removed. All text files should end in a newline character. 

https://www.drupal.org/docs/develop/standards/php/php-coding-standards#:~:text=PEAR%20Coding%20standards.-,Indenting%20and%20Whitespace,n%20(Windows%20line%20endings).

2023-06-05 17:49 UTC, timcosgrove commented on docroot/modules/custom/va_gov_api/va_gov_api.info.yml
> +core_version_requirement: ^9 || ^10
On the other hand these are straight forward, no need to comment.

2023-06-05 17:49 UTC, timcosgrove commented on docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_status.yml
> +# Migration meta data.
What is this file for?

2023-06-05 17:49 UTC, timcosgrove commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
> -
Did this update never run? If it has run in the past, we should minimally keep an empty update so that people know in the future to start from 8011.

2023-06-05 17:56 UTC, tonytaylor commented on docroot/modules/custom/va_gov_api/va_gov_api.info.yml
> +core_version_requirement: ^9 || ^10
Got it.

2023-06-05 17:59 UTC, tonytaylor commented on .github/workflows/continuous_integration.yml
> +          category: "/language:${{matrix.language}}"
Duly noted. Apologies for the confusion.

2023-06-05 18:01 UTC, tonytaylor commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
> -
No idea.  Just the new guy making quasi-cosmetic changes to satisfy an upgrade gatekeeper.

2023-06-05 18:05 UTC, tonytaylor commented on docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_status.yml
> +# Migration meta data.
This config came from the `VACMS-12252-drupal-10` branch.  Should this be removed?

2023-06-07 15:44 UTC, edmund-dunn submitted a review, later dismissed
This all looks good to me! Clean and makes sense.

2023-06-07 16:14 UTC, timcosgrove reviewed
There are still some files and weird insertions which need explaining.

2023-06-07 16:14 UTC, timcosgrove commented on docroot/modules/custom/va_gov_backend/js/script.js
> +        var targetTypes = ["health_care_local_facility", "vba_facility"];
Is this correct? it removes a targetType.

2023-06-07 16:14 UTC, timcosgrove commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php
> +  const LOVELL_TRICARE = 1039;
Why is this PR adding this in?

2023-06-07 16:14 UTC, timcosgrove commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php
> +
Same

2023-06-07 16:14 UTC, timcosgrove commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
> +  /**
Why is this PR adding this in?

2023-06-07 16:14 UTC, timcosgrove commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
> +  /**
Why is this PR adding this in?

2023-06-07 16:17 UTC, timcosgrove requested changes
There are some additions/deletions that need explaining before this can go out.

2023-06-07 16:17 UTC, timcosgrove submitted a review, later dismissed
There are some additions/deletions that need explaining before this can go out.

2023-06-07 18:20 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/data/vet-center-facility-status.csv
> +"id","name","station_id","facility_type","physical_city","physical_state","Vet Center Status
This file is also trying to sneak back in.

2023-06-07 18:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
> +      "Failed to move data source file: @file", ['@file' => $file_source]
These two lines are not equivalent.  [UpdateException extends \Exception](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Utility%21UpdateException.php/class/UpdateException/10) which is a php exception that does not support tokens.  As near as I can tell, it only supports strings.  

Probably better just avoid tokens and translation in installs
 
```suggestion
      "Failed to move data source file: $file_source"
```

2023-06-07 18:41 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
> -
This should have run and was added a couple weeks back.  I would not expect this update to remove it.

2023-06-07 18:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
> +      '#description' => $this->t('Select a content type to queue.'),
I don't see this class using the string translation trait.  (maybe some higher extended class is bringing it in?)  
If this was not tested, it would be a breaking change.   Also this form is only for us admins, so it is a bit silly to translate this.
```suggestion
      '#description' => 'Select a content type to queue.',
```

2023-06-07 18:48 UTC, swirtSJW commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php
> +  const LOVELL_TRICARE = 1039;
This is more git rebase problem   This code was added last week. and this PR is mistakenly reverting it.

2023-06-15 14:29 UTC, tonytaylor commented on docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
> +# Migration meta data.
It appears the D10 branch held on to some stale files. Removed.

2023-06-15 14:31 UTC, tonytaylor commented on docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_status.yml
> +# Migration meta data.
Removed this stale file.

2023-06-15 14:32 UTC, tonytaylor commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
> -
This file was outdated. Updated.

2023-06-15 14:33 UTC, tonytaylor commented on docroot/modules/custom/va_gov_backend/js/script.js
> +        var targetTypes = ["health_care_local_facility", "vba_facility"];
Thanks for the heads up here.  Restored the earlier state.

2023-06-15 14:34 UTC, tonytaylor commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php
> +  const LOVELL_TRICARE = 1039;
This had artifacts that apparently have been removed since.  Updated to latest from trunk.

2023-06-15 14:36 UTC, tonytaylor commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
> +      "Failed to move data source file: @file", ['@file' => $file_source]
This has been refactored in the most recent push.

2023-06-15 14:54 UTC, tonytaylor commented on docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
> +      '#description' => $this->t('Select a content type to queue.'),
Removing `$this->t()` triggers a warning and returns non-zero status from phpcs during pre-commit.

2023-06-15 19:33 UTC, swirtSJW requested changes
Hi @tonytaylor this is looking pretty good.  There are only two Facilities related issues that I see.

2023-06-15 19:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/js/script.es6.js
> +        const targetTypes = ["health_care_local_facility", "vba_facility"];
This change seems unrelated to d10 readiness and is unexpected.  This is changing functionality  and preventing it from operating on nca facilities.

2023-06-15 19:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/js/script.js
> +})(jQuery, window.Drupal);
Should not be losing newline at end of file.

2023-06-15 20:08 UTC, tonytaylor commented on docroot/modules/custom/va_gov_backend/js/script.es6.js
> +        const targetTypes = ["health_care_local_facility", "vba_facility"];
Agreed. Restored to earlier state.

2023-06-15 20:08 UTC, tonytaylor commented on docroot/modules/custom/va_gov_backend/js/script.js
> +})(jQuery, window.Drupal);
Done.

2023-07-06 15:02 UTC, edmund-dunn approved these changes
This looks good! Nicely done sir!

2023-07-06 15:37 UTC, merged