VACMS-14442: Enable other CLP sections and test them
department-of-veterans-affairs/va.gov-cms pull request #14763
Opened 2023-08-11 16:00 UTC by chri5tia

## Description

Relates to #_issueid_. (or closes?)

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-08-22 17:08 UTC, ndouglas commented on tests/cypress/integration/features/content_type/campaign_landing_page.feature
I recommend breaking it up into multiple tests, each beginning with the "I am logged in as a user... I am at /node/add/campaign_landing_page..." bit.

It does add a little bit of overhead to create a user and log in. 

But it also adds better traceability/debugging/maintainability:

- A user is added for each test, so you can see relevant watchdog log messages for a specific user.
- It gives more specificity about where exactly the error occurred -- the test name has more meaning.
- A single Given-When-Then sequence is easier to think about, easier to write about, and easier to map to acceptance criteria (and vice-versa).
- Shorter tests are easier to develop and test independently, since you don't have to wait for _n - 1_ steps to complete before you can see the results of your current area of focus 🙂 

If you have a substantial number of tests, then they can be split into e.g. `campaign_landing_page/hero_banner.feature`, `campaign_landing_page/why_this_matters.feature`, etc. Each of those tests will incur some overhead, but since our tests are parallelized (and ideally will be more parallelized in the future), the length of the entire test run may not increase very much because the tests can be scheduled more efficiently.

2023-08-24 07:54 UTC, chri5tia commented on tests/cypress/integration/features/content_type/campaign_landing_page.feature
> -    Then I create a "campaign_landing_page" node
This gets moved to `/campaign_landing_page/basic_requirements.feature`

2023-08-24 16:31 UTC, ndouglas requested changes
This looks fantastic overall.

My main suggestion is to wait for elements to appear or disappear, etc, rather than using wait times. The wait times will make the tests flaky.

2023-08-24 16:31 UTC, ndouglas commented on tests/cypress/integration/step_definitions/common/i_enable_the_segment.js
**Praise**: Nice!

2023-08-24 16:31 UTC, ndouglas commented on tests/cypress/integration/features/content_type/campaign_landing_page/why_this_matters.feature
> +    And I wait "3" seconds
**Suggestion**: This would be a great place for an 'I wait for "{selector}" to [dis]appear' step definition.

2023-08-24 16:31 UTC, ndouglas commented on tests/cypress/integration/features/content_type/campaign_landing_page/why_this_matters.feature
> +    And I wait "3" seconds
**Suggestion**: These fixed waits will make the tests flaky. We should wait on <something> to happen.

2023-08-24 17:58 UTC, dsasser commented on tests/cypress/integration/features/content_type/campaign_landing_page/basic_requirements.feature
Question:
Do we plan to remove the redundant bits from i_create_a_node.js that are now covered by the new tests?

2023-08-24 18:05 UTC, chri5tia commented on tests/cypress/integration/features/content_type/campaign_landing_page/basic_requirements.feature
The new tests do not submit the form, they just check for the presence and function of expected elements. I'm still figuring out if there is anything in the the old test that can be removed with that in mind. Maybe in a future ticket.

2023-08-24 18:06 UTC, chri5tia commented on tests/cypress/integration/features/content_type/campaign_landing_page/basic_requirements.feature
But in short, yes!

2023-08-24 19:58 UTC, chri5tia commented on tests/cypress/integration/step_definitions/common/i_check_the_checkbox.js
> +  cy.get('input[type="checkbox"]').eq(2).check({ force: true });
The idea behind this is to just select a "random" option. It's great for lists generated by taxonomy that is liable to change without needing to affect the test. It should be selecting the second option, which also ensures there are actual options.

2023-08-24 23:42 UTC, chri5tia commented on tests/cypress/integration/features/content_type/campaign_landing_page/why_this_matters.feature
> +    And I wait "3" seconds
I love this. I attempted to use `cy.waitUntil` but apparently it's not installed? Unless I used it incorrectly, it's saying that waitUntil isn't a function:
https://www.npmjs.com/package/cypress-wait-until

Here is an example:

```
Given(
  "I wait until the element with the selector {string} is visible",
  (selector) => {
  cy.waitUntil(selector).should("be.visible");
});
```

2023-08-26 00:33 UTC, chri5tia commented on tests/cypress/integration/features/content_type/campaign_landing_page/why_this_matters.feature
> +    And I wait "3" seconds
Done. However, I am realizing that there were some problems with how I was testing the modal e.g. false positives. I have removed all the modals from the test for now until I can do more work to see how to get cypress and iframes to play nice.

2023-08-26 00:33 UTC, chri5tia commented on tests/cypress/integration/features/content_type/campaign_landing_page/why_this_matters.feature
> +    And I wait "3" seconds
These are removed in lieu of removing modal tests.

2023-08-26 00:33 UTC, chri5tia commented on tests/cypress/integration/features/content_type/campaign_landing_page/faq.feature
> +#    And I fill in "Link text" field with fake text
I was having trouble getting cypress to find these fields.

2023-08-26 00:34 UTC, chri5tia commented on tests/cypress/integration/step_definitions/common/i_check_the_checkbox.js
> +  cy.get('input[type="checkbox"]').eq(2).check({ force: true });
Turns out it doesn't work. I don't know if it's because I switched to Electron instead of Chrome but I suspect it needed to be tested more so I removed it.

2023-08-26 00:39 UTC, chri5tia commented
@ndouglas Can you take a fresh look? There are two features that need more work for accurate testing: CTA buttons and Add media button/iframe modals. I have put TODO items in place so that we can keep track of what is missing. Let me know if I should remove those before merging and if anything else is needed. I think this is a logical stopping point for this ticket. Let me know your thoughts.

2023-08-29 05:38 UTC, chri5tia commented
Creating new tickets for testing the modal and testing the CTA links

2023-08-29 14:49 UTC, ndouglas submitted a review, later dismissed
This looks really good, but it's much better if you follow a Given-When-Then format rather than Given-Then or Given-Then-Then. Please change those where possible.

In some cases, I ask you to write step definitions to verify that text has been written successfully to a field (rather than just disappearing into the DOM or the void or something). That's not necessary right now, but would be a great place to follow up, just so there's some actual verification in a Then step happening.

So, bottom line is I'd like you to make some changes with how you use Given-When-Then, but that should mostly just be some light editing and shouldn't involve making any substantial changes, adding additional tests or step definitions, etc. Feel free to open up followup issues for those, or don't.

Thank you!

2023-08-29 14:49 UTC, ndouglas commented on tests/cypress/integration/features/content_type/campaign_landing_page/connect_with_us.feature
**Suggestion**: Behavioral tests normally follow a Given-When-Then format, and this follows a sort of Given-Then format.

Given should describe preconditions, initial setup, etc.

When should describe the actions that you take.

Then should describe the expectations of the effects of those actions.

So in this case, I'd say "Given I am logged in... and I am at... and I click to expand..."

The "When" is fuzzier. Here, it just seems like you're demonstrating that a dropdown works. I'd suggest formatting it like this:

- Given... as you have it.
- When I click to expand "Connect with us"
- Then the dropdown with selector "#edit-field-related-office" has the option "NCA"
- And the dropdown with selector "#edit-field-related-office" has the option "VAC0"
- etc.

That's then a little clearer about what you're wanting to see here.

2023-08-29 14:49 UTC, ndouglas commented on tests/cypress/integration/features/content_type/campaign_landing_page/spotlight.feature
**Suggestion**: This is a Given-Then-Then test. 

If you have a Then section, you can add another Then section... but you should add another When section before it to specify what exactly you're doing.

e.g.

- Given I am standing in my yard
- When I look up
- Then I should see the sky
- When I look down
- Then I should see the ground
- When I look in a mirror
- Then I should see an idiot
- etc

I think it should look like:

- Given I am logged in...
- When I fill in field...
- Then field with selector "#whatever" contains some text
- When I click the "Add Link teaser" button...
- And I ...
- Then "Link summary" should contain some text

Something like that.

2023-08-30 01:43 UTC, chri5tia commented
@ndouglas Thanks for explaining the Given, When, Then flow. I fixed them for each of the tests and it will hopefully be more apparent that I am just testing if I can fill out a field or if a field is there. At this point, nothing is being submitted because I haven't figured out how to resolve all the redundancy for filling out the required fields and also I think the modal and CTA tests would need to be in place first. But right now in some places seeing if it can fill out or interact with a field is like seeing if it's there, its the kind of field that was expected and permissions are correct, etc. Can you take a fresh look with these changes?

2023-08-30 11:55 UTC, ndouglas approved these changes
These look great! Thank you!

2023-08-30 11:55 UTC, ndouglas commented on tests/cypress/integration/features/content_type/campaign_landing_page/connect_with_us.feature
**Praise**: Yep, that's great!

2023-08-30 11:55 UTC, ndouglas commented on tests/cypress/integration/features/content_type/campaign_landing_page/downloadable_resources.feature
> +    Then I click the "Add existing Downloadable resource" button
**Nitpick**: Missed one.

2023-08-30 12:02 UTC, ndouglas commented
Looks like there's an issue with the video test:

https://cms-bk1bdtbdtzgaipprqu6gzyeortznilju.ci.cms.va.gov/cypress/videos/content_type/campaign_landing_page/video.feature.mp4
https://cms-bk1bdtbdtzgaipprqu6gzyeortznilju.ci.cms.va.gov/cypress/screenshots/actual/content_type/campaign_landing_page/video.feature/Content%20Type%20Campaign%20Landing%20Page%20--%20Enable%20Video%20page%20segment%20and%20ensure%20expected%20fields%20are%20present%20(failed).png

2023-08-30 16:12 UTC, merged

2023-08-30 17:30 UTC, chri5tia commented
See this PR to fix video etc: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15028