VACMS-14793: Hide Link Description Field in Footers
department-of-veterans-affairs/va.gov-cms pull request #15069
Opened 2023-09-01 15:25 UTC by chri5tia

## Description

Closes #14793 

## Testing done
Local functional testing

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-09-11 15:41 UTC, dsasser reviewed
Reminder: we don't want PRs to close issues automatically when they are merged. This gives us a chance to prod verify the solution before closing the issue:

<img width="442" alt="Screenshot 2023-09-11 at 8 38 03 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/3f2bf49c-85b0-4876-b73d-c2bad4565e62">

2023-09-15 10:21 UTC, chri5tia commented
@dsasser The PR is failing because the new trait  `MenuFormAlter` lives in the new module `va_gov_header_footer`, which cannot be installed due to drush failing on this error, where the already-installed `va_gov_home` module depends on an expected trait that it can't find, throwing a drush error.

Here is what I was seeing in my browser locally:

```
Fatal error: Trait "Drupal\va_gov_header_footer\Traits\MenuFormAlter" not found in /var/www/html/docroot/modules/custom/va_gov_home/src/EventSubscriber/FormEventSubscriber.php on line 14
```

I propose that I move the new `MenuFormAlter` trait to the `va_gov_home` module instead, or move everything related to menus that is in `va_gov_home` and `va_gov_header_footer` to a module called `va_gov_menus`. 

It would be nice if we could ensure that `va_gov_home` isn't dependent on something other than like the backend module. Thoughts?

2023-09-15 17:56 UTC, dsasser requested changes

2023-09-15 17:56 UTC, dsasser commented on config/sync/core.extension.yml
> +  va_gov_menus: 0
SHOULD

[As stated in my comment on your other PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15273/files#r1327576458), we should avoid using generically named modules for product business logic.

For this issue, I would recommend the following changes:

- Revert your changes to va_gov_home
- Add a new va_gov_header_footer module
- Add an event subscriber to va_gov_header_footer module
- Leverage the MenuFormAlter trait in va_gov_header_footer

2023-09-15 18:24 UTC, chri5tia commented on config/sync/core.extension.yml
> +  va_gov_menus: 0
Please see my previous comment. 
As far as modules, I favor creating modules about site features not based on teams or "products". "Menus" makes more sense to me than having two modules about menus. But if we do do it the other way (the way you had it with header_footer and home modules), how do we get around pushing a dependency to a module that isn't installed yet? (home was calling for a trait in header_footer that it couldn't find and couldn't install header_footer.) Tugboat was failing to build and it would be an issue if deployed to prod.

2023-09-15 18:42 UTC, dsasser commented on config/sync/core.extension.yml
> +  va_gov_menus: 0
> I favor creating modules about site features not based on teams or "products". "Menus" makes more sense to me than having two modules about menus

I would say, just by looking at the modules we already have in place, we have already gone down both paths:

Products:
va_gov_events
va_gov_banner
va_gov_benefits
// etc.

Genericly named modules:
va_gov_backend
va_gov_content_types
//etc.

Which of these module are easier to maintain over the long run? To test?

> But if we do do it the other way (the way you had it with header_footer and home modules), how do we get around pushing a dependency to a module that isn't installed yet? (home was calling for a trait in header_footer that it couldn't find and couldn't install header_footer.)

This could be solved with some conditional blocks, which is preferred over having to move a bunch of code to get around the issue.

2023-09-15 21:36 UTC, chri5tia commented on config/sync/core.extension.yml
> +  va_gov_menus: 0
Here is a much more straight-forward revision. 
I will create a new ticket to restructure `va_gov_home` to use the MenuFormAlter trait and put the diff in it.

2023-09-15 22:05 UTC, chri5tia commented
Ticket created for follow up:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15279

2023-09-18 16:14 UTC, dsasser requested changes

2023-09-18 16:49 UTC, chri5tia commented on docroot/modules/custom/va_gov_header_footer/src/Traits/MenuFormAlterTrait.php
> +trait MenuFormAlterTrait {
That was my argument last week for putting it in va_gov_home. We are on the same page. Where do you suggest that we put it?

2023-09-18 17:06 UTC, chri5tia commented on docroot/modules/custom/va_gov_header_footer/src/Traits/MenuFormAlterTrait.php
> +trait MenuFormAlterTrait {
To recap, this is a PR from last sprint that was ready for review after you contributed code to it, but I saw that I needed to remove the dependency for the trait that was in the module that wasn't installed yet, so the change was to address that. I hesitate to keep rewriting it. I still lean toward having a custom module for menus instead of dividing it up for different types of menus but as you pointed out earlier, this would essentially gut the va_gov_home module. 

Let me know how you want me to proceed.

2023-09-18 17:39 UTC, dsasser commented on docroot/modules/custom/va_gov_header_footer/src/Traits/MenuFormAlterTrait.php
> +trait MenuFormAlterTrait {
> To recap, this is a PR from last sprint that was ready for review after you contributed code to it, but I saw that I needed to remove the dependency for the trait that was in the module that wasn't installed yet, so the change was to address that. I hesitate to keep rewriting it. I still lean toward having a custom module for menus instead of dividing it up for different types of menus but as you pointed out earlier, this would essentially gut the va_gov_home module.
> 
> Let me know how you want me to proceed.

I'm asking that we not place re-usable code inside a module which is named for a particular feature/product. My suggestion is to either use va_gov_backend, or create a new module va_gov_menus.

2023-09-19 01:35 UTC, chri5tia commented on docroot/modules/custom/va_gov_header_footer/src/Traits/MenuFormAlterTrait.php
> +trait MenuFormAlterTrait {
Thanks for the suggestion. I moved the new trait to a new module called va_gov_menus so that it's more centralized. Thank you for working through my questions. This is ready for re-review!

2023-09-21 02:22 UTC, dsasser commented on docroot/modules/custom/va_gov_header_footer/src/EventSubscriber/FormEventSubscriber.php
> +      $form['description']['#access'] = FALSE;
Note for future us: this line should use the new trait added in va_gov_menus, but we can't roll out a new trait in a new module while also using it elsewhere in the codebase at the same time, as we get a php error:

```
PHP Fatal error:  Trait "Drupal\va_gov_menus\Traits\MenuFormAlterTrait" not found in /var/www/html/docroot/modules/custom/va_gov_header_footer/src/EventSubscriber/FormEventSubscriber.php on line 14
```

We will want to go back and leverage the trait here, as well as in va_gov_home (after moving va_gov_home's menu alter methods to the trait as well).

2023-09-21 02:31 UTC, dsasser approved these changes
Looks good!

As admin:
<img width="790" alt="Screenshot 2023-09-20 at 7 30 26 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/4a70dc4c-a400-4115-99d5-0190cd7a5c1d">


As non-admin:
<img width="1028" alt="Screenshot 2023-09-20 at 7 29 08 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/9f3202ee-f111-4b1d-9650-eb3635a0cbc6">

2023-09-21 03:32 UTC, merged