VACMS-14701 Update vba facility fields
department-of-veterans-affairs/va.gov-cms pull request #15143
Opened 2023-09-07 18:47 UTC by swirtSJW

## Description

Relates to #14701

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-09-07 21:20 UTC, swirtSJW commented
The DB data is not locking down correctly.

2023-09-08 13:36 UTC, swirtSJW commented on config/sync/paragraphs.paragraphs_type.health_care_local_facility_servi.yml
> -label: 'VAMC facility service (non-healthcare service)'
This is used across vet centers, VBA and VAMC so I altered the name to be less specific.

2023-09-11 13:54 UTC, omahane requested changes
It appears that the order of the fields in the node:view is not as expected from the QA:
![Screenshot 2023-09-11 at 8 47 38 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/d3636e36-677e-4f32-bca6-e5dd9caeca3f)

It also appears that the order of the fields in node:edit is not as expected from QA:
![Screenshot 2023-09-11 at 8 52 52 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/1d518ee4-5d63-4284-bc1c-15c23ee9892d)

2023-09-11 18:18 UTC, omahane approved these changes
Everything looks good to me.

2023-09-11 21:32 UTC, swirtSJW commented
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/33e523e1-123f-4eef-930c-4c0b017bac15)

2023-09-11 21:32 UTC, merged