VACMS-15242: Make Revision log message requirement more inclusive
department-of-veterans-affairs/va.gov-cms pull request #15355
Opened 2023-09-22 10:15 UTC by chri5tia

## Description

Relates to #15242 
#15187 

This PR revises workflow module code to hide the checkbox that asks editor if they want to create a revision log message because it is required. Formerly the code hid the revision log message field and not just the checkbox on promo block types. This code resolves this while putting in some extra checks. The code disables the functionality of the checkbox so that it isn't hidden in a state where it is not checked and it also reinforces that the log message is exposed. 

## Testing done
local functional

## Screenshots
<img width="408" alt="Screenshot 2023-09-22 at 3 13 28 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/6c458172-62ff-4760-aa2c-f19b2bad4070">

## QA steps

Check both promo and NON promo blocks that a) revision log message works, is required and the checkbox is hidden.
This should apply to any user.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-09-22 10:35 UTC, chri5tia commented
@swirtSJW We'll have to rebuild this when the tugboat issues are resolved (I see that nothing is being deployed/environment isn't being built) but wondering if you can pull down the branch and test it and/or take a look at the code revision and give me any feedback or preferences. Thanks!

2023-09-22 13:29 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +    unset($form['revision_log']['#states']);
This seems potentially overreaching to obliterate all states.  Is there way to be more targeted about which state is getting removed?  


Also this seems like it might be an upstream bug.  If this checkbox is set, 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/5776207e-96b0-49b8-b0c6-967241639efc)  
Users should  not be presented with the option to opt out of creating a new revision.

If it is not an upstream issue, it makes sense (to me anyway) that the logic we employ ought to rely on that setting across all block bundles.

2023-09-22 17:04 UTC, chri5tia commented
Cypress failure is the media function, which is unrelated. Still trying to figure out what to do about that.

https://cms-7blfsvkcnwkjikm4zu3iee5ko5eheqhn.ci.cms.va.gov/cypress/screenshots/actual/platform/media.feature/

<img width="1174" alt="Screenshot 2023-09-22 at 10 04 32 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/7af012ef-2988-4e0a-b0cf-db5ea0cff2eb">

2023-09-26 12:36 UTC, chri5tia commented on .tugboat/config.yml
> +        - git rm --cached -r . && git reset --hard
I'll remove this before merging.

2023-09-26 12:37 UTC, chri5tia commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +    unset($form['revision_log']['#states']);
Thank you.

2023-09-26 19:54 UTC, chri5tia commented
I noticed that the `cms_announcemet` block type was also affected by the defect reported in #15187 

Engineering notes to incorporate the fix:

`dpm($form)` shows the revision log structure for this bundle as:

```
  "revision_log" => array:9 [▼
    "#type" => "container"
    "#parents" => array:1 [▶]
    "#attributes" => array:1 [▼
      "class" => array:3 [▼
        0 => "field--type-string-long"
        1 => "field--name-revision-log"
        2 => "field--widget-string-textarea"
      ]
    ]
    "widget" => array:13 [▶]
    "#access" => true
    "#weight" => 25
    "#cache" => array:3 [▶]
    "#group" => "revision_information"
    "#states" => array:1 [▼
      "visible" => array:1 [▼
        ":input[name="revision"]" => array:1 [▼
          "checked" => true
        ]
      ]
    ]
  ]
```

`alert`, `cta_with_link` block, `benefit_promo`, `news_promo` work with the following previously-implemented alter:

```
$form["revision_information"]["#attributes"]['class'][] = 'visually-hidden';
```

2023-09-26 22:59 UTC, chri5tia commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +    unset($form['revision_log']['#states']);
I seem to only be able to get this to work on promo and cms_announcement if I unset the revision_log state (checkbox), because changing access to false makes the log disappear, even if I tell it access true. But I have moved unsetting the state to just these two blocks.

I think this is because of how we add the revision block on the config sync as part of the Editorial workflow group when it isn't actually. I'm not sure though.

2023-09-27 02:46 UTC, swirtSJW requested changes
I think this has one major breaking change that has to be remedied.

2023-09-27 02:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +    // Promo blocks have a different form structure.
Minor:  Your comment and your code are in disagreement.  Your comment says promo blocks are different, while your code says promo and cms_announcement are different.

I suggest altering your comment to say some blocks are different.... or better yet, explain what about them is different.

2023-09-27 02:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +    // Promo blocks have a different form structure.
Also cms announcement block is probably not worth addressing since it is a dead block
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15419

2023-09-27 02:46 UTC, swirtSJW commented on tests/cypress/support/main_content_blocks.js
> +  // cy.get("form.node-form").find("input#edit-submit").click();
If we are commenting this out, can we comment on why it is being commented out and what it might take to comment it back in?

2023-09-27 02:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +      return;
Critical:  This method 'requireRevisionMessage()' Is being called on to operate on both blocks and nodes.  It is called in alterBlockContentForm() and alterNodeForm()   but with this one check we are bailing out of the function if it is something other than a block.  So it is no longer operating on nodes.   I am pretty sure this is a breaking change.

2023-09-27 05:33 UTC, chri5tia commented on tests/cypress/support/main_content_blocks.js
> +  // cy.get("form.node-form").find("input#edit-submit").click();
My understanding was that saving the form during this test is not desirable. @ndouglas, can you confirm? Test fails because it is looking for form elements after it saves, which is odd, but I don't want to remove critical functionality of the test if I misunderstood feedback from earlier.

2023-09-27 05:34 UTC, chri5tia commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +      return;
Removing this all together.

2023-09-27 12:17 UTC, swirtSJW commented on tests/cypress/support/main_content_blocks.js
> +  // cy.get("form.node-form").find("input#edit-submit").click();
If we should not be saving during the test, why leave the code commented out?  The commented out code just becomes cruft.  Usually we only comment out code if we are leaving breadcrumbs to come back to later.

2023-09-27 12:49 UTC, swirtSJW reviewed
This looks much better, functionally.  It is no longer a breaking change.   A couple of minor suggestions.

2023-09-27 12:49 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +        // Hide revision checkbox on Promo blocks.
It would still be good to have some breadcrumb left here in a comment that describes why promos are different from all other blocks.  I've been on this PR for a while now and it is still not clear to me why promos are fundamentally different than our other blocks.  If present-me can't connect the dots, there is no way future-me is going to .   We need to be kind to our future selves.   ;)

2023-09-27 12:49 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +        // Hide revision checkbox on Promo blocks.
Rather than create exceptions, would it be better for promo blocks to be made to be just like other blocks?

2023-09-27 12:49 UTC, swirtSJW commented on tests/cypress/support/main_content_blocks.js
> -  cy.get("form.node-form").find("input#edit-submit").click();
Nice.  This makes good sense.  The block test should not be responsible for saving the node.

2023-09-27 12:49 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +      if ($entity->bundle() === 'promo') {
Minor:  You had good instincts before to make this check specific to blocks named promo.   We don't have a node named promo or a menu named promo but it is a simple machine name that could easily appear so it makes sense to keep your original check.
```suggestion
      if (($entity instanceof BlockContentInterface) && ($entity->bundle() === 'promo')) {
```

2023-09-27 12:49 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
>  use Drupal\Core\Entity\ContentEntityForm;
```suggestion
use Drupal\block_content\BlockContentInterface;
use Drupal\Core\Entity\ContentEntityForm;
```

See the change I suggested below that will require this to be added.

2023-09-27 12:51 UTC, swirtSJW commented on tests/cypress/support/main_content_blocks.js
> +  // cy.get("form.node-form").find("input#edit-submit").click();
Your new commit resolves this.

2023-09-27 12:54 UTC, swirtSJW commented
> I noticed that the `cms_announcement` block type was also affected by the defect reported in #15187
> 

CMS announcement is a dead block type that should be removed by CMS Team https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15419

2023-09-27 13:26 UTC, chri5tia commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +        // Hide revision checkbox on Promo blocks.
I am checking to see if there is just a field group in all but the promo block that could easily be put in.

2023-09-27 14:16 UTC, chri5tia commented
@swirtSJW Creating a fieldset and moving the revision_log in config to match the other blocks fixed the issue without the need to change what you had in the event subscriber originally. *epic facepalm*

Thanks for working through this ticket with me; I learned a lot!

2023-09-27 18:46 UTC, swirtSJW requested changes
Code wise this looks good.
I am seeing a difference in the order of the fields on promo VS other blocks.   The order on the promo seems a little scrambled.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/df92ded7-d352-4884-845b-8a47df128150)

I think we want those to be consistent, and the alert seems to make more sense the order of 

- section
- moderation state
- revision log message

2023-09-27 18:55 UTC, swirtSJW commented
The QA steps were a little loose, so tightening them up a bit makes it easier on reviewers

1. As  an admin [edit a promo block](https://pr15355-7blfsvkcnwkjikm4zu3iee5ko5eheqhn.ci.cms.va.gov/block/263?destination=/admin/structure/block/block-content) 
   - [ ] Validate that there is no checkbox option to not create a revision.
   - [ ] Validate that revision log message is required.
   - [ ] Validate the field order is
      - section
      - workflow
      - revision log message
2. Visit another block type ([alert block](https://pr15355-7blfsvkcnwkjikm4zu3iee5ko5eheqhn.ci.cms.va.gov/block/256?destination=/admin/structure/block/block-content)) to make sure it is unaffected 
   - [ ] Validate that there is no checkbox option to not create a revision.
   - [ ] Validate that revision log message is required.
   - [ ] Validate the field order is
      - section
      - workflow
      - revision log message

2023-09-27 20:19 UTC, swirtSJW approved these changes
This tests out.  Thank you.

2023-09-27 20:21 UTC, merged