Stubbing out next server config
department-of-veterans-affairs/va.gov-cms pull request #15429
Opened 2023-09-27 15:35 UTC by KitLykos

## Description

Relates to #_issueid_. (or closes?)

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-09-27 16:18 UTC, ndouglas commented
Please keep your PR in draft rather than relying on the "Do Not Merge" label 🙂

2023-10-13 14:54 UTC, tjheffner requested changes

2023-10-13 14:54 UTC, tjheffner commented on composer.json
> +		"va:next-preview": "Prepare the next preview server"
this spacing is off

2023-10-13 14:54 UTC, tjheffner commented on composer.json
> +		"va:next:install": [
spacing is off for all 3 of these, the indents should match the other commands

2023-10-13 14:54 UTC, tjheffner commented on composer.json
> +			"! ./scripts/should-run-directly.sh || yarn start",
`"! ./scripts/should-run-directly.sh || ./scripts/next-start.sh",`

2023-10-13 14:54 UTC, tjheffner commented on scripts/next-build.sh
> +yarn next:start
i'd like this moved to a new script file, `next-start.sh`

```
#!/usr/bin/env bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
source ~/.bashrc

cd next

APP_ENV=tugboat yarn start
```

2023-10-13 14:54 UTC, tjheffner commented on .tugboat/config.yml
one more line needs added here afterwards to start the server

`- bash -lc 'composer va:next:start'`

2023-10-13 16:01 UTC, tjheffner requested changes

2023-10-13 16:01 UTC, tjheffner commented on .github/ISSUE_TEMPLATE/ap-defect.md
> -<!-- What is the user prevented from doing? About how many users are affected? -->
i don't think we want any changes to this file in this PR

2023-10-24 21:53 UTC, tjheffner approved these changes

2023-10-25 00:24 UTC, merged