VACMS-14342: Set up `CODEOWNERS`
department-of-veterans-affairs/va.gov-cms pull request #15581
Opened 2023-10-06 13:04 UTC by ndouglas

Closes #14342.

This includes a `CODEOWNERS` file (I hope it works) and some light documentation about the concept.

I am posting this and requesting a review from basically everyone on this project in the interests of transparency (and, most likely, catching stupid mistakes arising directly from my ignorance and various moral failings).

This is a total work in progress. I ask – I beg – for y'all to review this and give input and feedback. Obv fixing it after this point is just a matter of opening a pull request, but I want to ensure that everyone feels that this file matches the current state and goals of the project as a whole and our respective teams and is not something I'm yeeting into the codebase by fiat.

## FAQ

### Why do you have so many lines with `# @department-of-veterans-affairs/platform-cms-drupal-engineers`?

The `#` makes it a comment. That line's intended to indicate that `platform-cms-drupal-engineers` is the default code owner, but still mention that directory/file so that we can discuss it.

In some cases, I may have suggested that `platform-cms-drupal-engineers` would own something they shouldn't. This is purely a result of ignorance on my part. So I'm adding these lines in an effort to be as transparent as possible, and because I'm seeking feedback.

### What are these new groups? Whoever heard of `platform-cms-qa`, anyway?

The `platform-cms` teams are newly added, as of yesterday. I'm adding `platform-cms-ux`, `platform-cms-accessibility`, etc teams to ensure that we have a _formal_ way of requesting review from our UX and Accessibility experts.

The full list of new teams can be found here:
- https://github.com/orgs/department-of-veterans-affairs/teams/platform-cms
- https://github.com/orgs/department-of-veterans-affairs/teams/platform-cms/teams

These teams are my best approximations of the different disciplinary areas within the Platform Team. It's possible I left something or someone out. I'm sorry, folks, I'm doing the best I can.

### Hey, you did a dumb over here!

Sorry, I'll fix it 😓 

### Have you heard about `$coolTool` or `$coolProcess` we can use with CODEOWNERS?

Nope. Pls tell me about it.

2023-10-06 13:49 UTC, EWashb commented
The only thing I have to add to this amazing work is that it might be helpful to add @joagnitti to the UX team. She may not always have a review to give, though.

Thank you for doing this, Nate!

2023-10-06 14:16 UTC, davidmpickett commented on .github/CODEOWNERS
Parsing out config is definitely gonna be a huge pain in the butt, BUT, if I'm reading the syntax rules correctly, we should be able to start breaking it down a bit by taking advantage of asterisks and existing naming conventions.

For example, I'm pretty sure this would catch a bunch of Facilities specific config files that everyone else would be happy not to be notified about

```
/config/sync/*vamc @department-of-veterans-affairs/facilities-cms
/config/sync/*vba @department-of-veterans-affairs/facilities-cms
/config/sync/*vet_center @department-of-veterans-affairs/facilities-cms
```

2023-10-06 14:27 UTC, davidmpickett commented on .github/CODEOWNERS
Not sure if trailing asterisks are needed to complete the pattern aka
`config/sync/*vamc*`

2023-10-06 14:49 UTC, ndouglas commented on .github/CODEOWNERS
I _think_ it does. The CODEOWNERS format is supposed to support _most_ of the syntax from [`.gitignore`](https://git-scm.com/docs/gitignore#_pattern_format) files.

At least in the case of `.gitignore`, you'd need to specify `*vamc*` to match anything including but not ending with `vamc`. So `*vamc` would match `my_cat_is_a_vamc`, but not `my_cat_is_a_vamc_and_so_can_you`.

e.g. 
![Screenshot 2023-10-06 at 10 48 25 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/a8fb8c52-1d5d-4c87-98c5-ddc0555baab0)

Of course that's just for `.gitignore`, and it's possible that CODEOWNERS is different, but I can't any documentation saying it's different in this specific regard.

2023-10-06 14:50 UTC, tjheffner commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_api                                  @department-of-veterans-affairs/facilities-cms
and if an AP team is needed, it may also be worth adding a rule `/config/sync/jsonapi*

2023-10-06 14:51 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_api                                  @department-of-veterans-affairs/facilities-cms
ah, my bad -- I thought that was Facilities' 😑 

I think `accelerated-publishing` is the team, so I can change that rn. If y'all have permission to write to CMS anyway.

2023-10-06 15:51 UTC, jilladams commented on .github/CODEOWNERS
>  # @department-of-veterans-affairs/vfs-cms-team
Noting: this team is primarily administrative, and used to govern access to the va.gov-cms repo, mainly so ppl can access the sprint board and make tickets in here, but it includes all kinds of random people (PMs, DMs, Researchers, etc). I know this is a code comment is that worth adding, so no one tries to make this group a codeowner of anything? I could go either way. 🤷‍♀️

2023-10-06 15:51 UTC, jilladams commented on .github/CODEOWNERS
> +/config/                                                            @department-of-veterans-affairs/vfs-cms-team
Related to my comment above. 😬  Do we need a "platform-cms-contributors" team or something that is only engineers?  That is annoying and probably wrong, if I'm thinking about how new Drupal contributor teams will get onboarded (would mean adding them to both `vfs-cms-team` for access, as well as the code contrib team, for PR review purposes.).

2023-10-06 15:51 UTC, jilladams commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_entity_browser                       @department-of-veterans-affairs/public-websites-cms
Fascinating. We own the CMS customization of entity browser?

2023-10-06 15:51 UTC, jilladams commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_migrate                              @department-of-veterans-affairs/facilities-cms
Would like to confirm the Forms migration lives elsewhere. If it's in here, we should add PW as a second owner.

2023-10-06 15:54 UTC, ndouglas commented on .github/CODEOWNERS
>  # @department-of-veterans-affairs/vfs-cms-team
Good question. I thought it might be a good fallback, but perhaps it's not. I could also just use all of the existing teams if there's no good reason for a specific one to get requests.

2023-10-06 15:55 UTC, ndouglas commented on .github/CODEOWNERS
> +/config/                                                            @department-of-veterans-affairs/vfs-cms-team
Whatever's easiest. If everyone gets `vfs-cms-team`, then that's fine IMHO and probably for most everyone. I'm not worried about people maliciously editing anything, and the lower the friction, the better.

2023-10-06 15:56 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_entity_browser                       @department-of-veterans-affairs/public-websites-cms
I don't know 🙂 I could be wrong. Places where I saw heavy contributions from a single team, I tried to assign it to that team. Not a very scientific process, and I could be completely off-base.

2023-10-06 15:57 UTC, davidmpickett commented on .github/CODEOWNERS
> +/config/sync/*jsonapi*                                              @department-of-veterans-affairs/accelerated-publishing
`/config/sync/*health_care* @department-of-veterans-affairs/facilities-cms # To catch VAMC stuff with older naming convention`

2023-10-06 16:03 UTC, davidmpickett commented on .github/CODEOWNERS
> +/config/sync/*jsonapi*                                              @department-of-veterans-affairs/accelerated-publishing
```
/config/sync/*full_width_banner_alert* @department-of-veterans-affairs/facilities-cms # aka VAMC System Banner Alert with Situation Updates
/config/sync/*locations_listing* @department-of-veterans-affairs/facilities-cms # aka VAMC System Locations List
/config/sync/*nca* @department-of-veterans-affairs/facilities-cms
```

2023-10-06 22:50 UTC, jilladams commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_entity_browser                       @department-of-veterans-affairs/public-websites-cms
More likely you're right (I didn't check commits to those files) and I just wasn't aware. Sitewide devs shall opine and let us know.

2023-10-11 16:38 UTC, dsasser commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_migrate                              @department-of-veterans-affairs/facilities-cms
> Would like to confirm the Forms migration lives elsewhere. If it's in here, we should add PW as a second owner.

The forms migration does in fact live in va_gov_migrate.

2023-10-11 16:40 UTC, dsasser commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_entity_browser                       @department-of-veterans-affairs/public-websites-cms
PW built this va_gov_entity_browser module, and the code within, so ownership should be on PW.

2023-10-11 16:41 UTC, dsasser requested changes
PW is the codeowner of the Forms migration, so should be a 2nd owner of va_gov_migrate

2023-10-11 17:53 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_migrate                              @department-of-veterans-affairs/facilities-cms
```suggestion
/docroot/modules/custom/va_gov_migrate                              @department-of-veterans-affairs/facilities-cms @department-of-veterans-affairs/public-websites-cms
```

2023-10-18 22:39 UTC, swirtSJW reviewed
This is a great compilation @ndouglas.  Very thorough.   

There are a couple places where I think co-ownership  might be warranted.  see comments.

2023-10-18 22:39 UTC, swirtSJW commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_consumers                            @department-of-veterans-affairs/facilities-cms
I think this one likely needs to be both facilities and public websites.  It impacts forms and facility data.

2023-10-18 22:39 UTC, swirtSJW commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_content_types                        # @department-of-veterans-affairs/platform-cms-drupal-engineers
With the flexibility and potential this holds, I think it should be platform, facilities and PW.

2023-10-18 22:39 UTC, swirtSJW commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_dashboards                           # @department-of-veterans-affairs/platform-cms-drupal-engineers
The only user of this right now is VetCenters so maybe facilities should co-own. It was built for facilities, but also with an eye toward other teams.

2023-10-18 22:39 UTC, swirtSJW commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_flags                                # @department-of-veterans-affairs/platform-cms-drupal-engineers
This is primarily used by facilities and PW forms.  This seems like a case for co-ownership by all three teams.

2023-10-18 22:39 UTC, swirtSJW commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_notifications                        # @department-of-veterans-affairs/platform-cms-drupal-engineers
Facilities is the primary user of this right now.  Should probably be co-owned so they are aware of changes.

2023-10-18 22:39 UTC, swirtSJW commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_user                                 # @department-of-veterans-affairs/platform-cms-drupal-engineers
Facilities is a heavy user and PW is becoming more so.  This should be owned three ways.

2023-10-18 22:39 UTC, swirtSJW commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_workflow                             # @department-of-veterans-affairs/platform-cms-drupal-engineers
All eyes should probably be on changes here.  A good candidate for ownership by all teams

2023-10-24 15:30 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_consumers                            @department-of-veterans-affairs/facilities-cms
```suggestion
/docroot/modules/custom/va_gov_consumers                            @department-of-veterans-affairs/facilities-cms @department-of-veterans-affairs/public-websites-cms
```

2023-10-24 15:30 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_content_types                        # @department-of-veterans-affairs/platform-cms-drupal-engineers
```suggestion
/docroot/modules/custom/va_gov_content_types                        @department-of-veterans-affairs/platform-cms-drupal-engineers @department-of-veterans-affairs/public-websites-cms @department-of-veterans-affairs/facilities-cms 
```

2023-10-24 15:30 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_dashboards                           # @department-of-veterans-affairs/platform-cms-drupal-engineers
```suggestion
/docroot/modules/custom/va_gov_dashboards                           @department-of-veterans-affairs/platform-cms-drupal-engineers @department-of-veterans-affairs/facilities-cms 
```

2023-10-24 15:30 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_flags                                # @department-of-veterans-affairs/platform-cms-drupal-engineers
```suggestion
/docroot/modules/custom/va_gov_flags                                @department-of-veterans-affairs/platform-cms-drupal-engineers @department-of-veterans-affairs/public-websites-cms @department-of-veterans-affairs/facilities-cms 
```

2023-10-24 15:30 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_notifications                        # @department-of-veterans-affairs/platform-cms-drupal-engineers
```suggestion
/docroot/modules/custom/va_gov_notifications                        @department-of-veterans-affairs/platform-cms-drupal-engineers @department-of-veterans-affairs/facilities-cms 
```

2023-10-24 15:30 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_user                                 # @department-of-veterans-affairs/platform-cms-drupal-engineers
```suggestion
/docroot/modules/custom/va_gov_user                                 @department-of-veterans-affairs/platform-cms-drupal-engineers @department-of-veterans-affairs/facilities-cms @department-of-veterans-affairs/public-websites-cms 
```

2023-10-24 15:30 UTC, ndouglas commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_workflow                             # @department-of-veterans-affairs/platform-cms-drupal-engineers
```suggestion
/docroot/modules/custom/va_gov_workflow                             @department-of-veterans-affairs/platform-cms-drupal-engineers @department-of-veterans-affairs/facilities-cms @department-of-veterans-affairs/public-websites-cms 
```

2023-10-31 13:17 UTC, acrollet commented
> Have you heard about `$coolTool` or `$coolProcess` we can use with CODEOWNERS?

well, since you asked... https://github.com/andrewring/github-distributed-owners

2023-11-01 12:27 UTC, merged