DO NOT MERGE: VACMS-14683: Updating service locations paragraph
department-of-veterans-affairs/va.gov-cms pull request #15622
Opened 2023-10-10 14:16 UTC by swirtSJW

# Merge / launch planned for Monday 5/13. DO NOT MERGE PRIOR.

## Description

Relates to #14683

This is a PR that is tracking the integration-service-location branch which contains work that can not go out until FE and CM have been done.

Note:  To run the migration, but this in terminal:  `drush scr ./scripts/content/VACMS-15559-migrate-service-location-from-node-to-paragraph.php`

To build the front end:
**Which version of content-build would you like to use?**
BRANCH VACMS-16144-VAMC-ServiceLocationParagraphs
**Which version of vets-website would you like to use?**
BRANCH main

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2024-01-18 19:37 UTC, swirtSJW commented
I am rebasing the integration branch.
You will need to use 
```
git fetch --all 
git reset --hard upstream/integration-service-location 
```

2024-02-03 03:01 UTC, swirtSJW commented
I just touched off the migration on the Tugboat.

2024-02-03 13:34 UTC, swirtSJW commented
migration completed 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/6336b567-e994-44d2-8f74-b55e22dbf519)

2024-02-13 15:15 UTC, swirtSJW commented
This is likely going to have a conflict from the cherry-picked script-library that went out with the menu rearranging.   I am not going to clear the conflict until after demo so we don't destroy any data in use by FE.

2024-02-14 15:19 UTC, swirtSJW reviewed
@omahane and @Becapa  I left a couple notes on adjustements that will be needed based on changes in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17236

2024-02-14 15:19 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/ServiceLocationMigration.php
> +    $facility_services = (empty($nids)) ? [] : $node_storage->loadMultiple(array_values($nids));
@omahane and @Becapa Because of the new state keeping logic in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17236  this will likely fall apart a bit because the state is tracking per item, not per batch.
The state does not know how to reference which batch of 25 was just finished and would not really be able to pick up where it left off.   Also the output would likely be jibberish.

I suggest this be changed to remove the batch size and just grab the top item in the array.  Something like this.  (not tested)

```suggestion
    $node_storage = get_node_storage();
    $nid_to_load = reset($sandbox['items_to_process']);
    $facility_services = (empty($nid_to_load)) ? [] : $node_storage->loadMultiple(array_values($nid_to_load));
```

2024-02-14 15:19 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/ServiceLocationMigration.php
> +    foreach ($facility_services as $nid => $facility_service_node) {
This foreach is no longer needed since there is only one node in $facility_services, but it would require a lot more shifting of logic to unwrap it than is probably necessary to get this working with the state keeping logic and way more than I can do in a PR suggestion.

2024-03-13 18:40 UTC, omahane commented
The migration into the service locations has been run once more.

2024-05-06 18:16 UTC, jilladams commented
As of today: 
* Branch is updated from main
* PR is up that will merge into this branch, to fix some code conflicts that got committed: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18042/files
* Apart from those code conflict fixes: This branch is ready to review. Updating PR. 

FYI @dsasser @omahane

2024-05-07 16:11 UTC, dsasser requested changes

2024-05-07 16:11 UTC, dsasser commented on docroot/modules/custom/va_gov_vamc/src/ServiceLocationMigration.php
> + * This is not a service, it is only needed one time so DI can not be used.
TIP:
You actually can use DI in custom classes using the [Class Resolver](https://api.drupal.org/api/drupal/core%21lib%21Drupal.php/function/Drupal%3A%3AclassResolver/8.9.x) service. [Example](https://git.drupalcode.org/project/expirable_content/-/blob/1.0.x/expirable_content.module?ref_type=heads#L25).

2024-05-07 17:47 UTC, dsasser approved these changes
Changes look great, nice work @omahane!

2024-05-07 18:00 UTC, jilladams commented
@department-of-veterans-affairs/platform-cms-devops-engineers FYI that this PR is ready for review if anyone would like to take a look. **We will merge next Monday 5/13 for Monday daily deploy.**  

After deploy, that'll be the trigger to run the related production script we've been talking to Grace / Tyler about.  (cc @gracekretschmer-metrostar)

2024-05-09 17:06 UTC, maxx1128 approved these changes
This is a lot of unfamiliar files and languages for me, but I looked through everything and didn't see any red flags or worrying signs. Glad that the merge conflicts get removed 👍

2024-05-10 20:38 UTC, omahane commented on docroot/modules/custom/va_gov_vamc/src/ServiceLocationMigration.php
> + * This is not a service, it is only needed one time so DI can not be used.
Thanks for the heads-up on this, @dsasser.

2024-05-10 20:49 UTC, 7hunderbird approved these changes
Looks good to me.  Thanks!

2024-05-13 16:04 UTC, merged

2024-05-13 16:43 UTC, omahane commented
Last minute ministrations around merging [on Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1715608045674369).