VACMS-15503 add multi workflow filters to all Views that have exposed content moderation filter
department-of-veterans-affairs/va.gov-cms pull request #15769
Opened 2023-10-21 03:44 UTC by swirtSJW

## Description

Relates to #15503

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-10-21 03:46 UTC, swirtSJW commented
Not to self:
Come back to all facilities views.
Left off at moderated_content

2023-10-23 13:42 UTC, swirtSJW commented on composer.lock
> +                    "version": "8.x-2.0-beta2+1-dev",
Unrelated metadata changes.

2023-10-23 13:45 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 13:47 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            operator: moderation_state_multiple_workflow_filter_op
```suggestion
            operator: moderation_state_op
```

2023-10-23 13:47 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            multiple: false
```suggestion
            multiple: true

2023-10-23 13:48 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +          operator: or
```suggestion
          operator: in
```

2023-10-23 13:49 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +          operator: or
in

2023-10-23 13:51 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            multiple: false
```suggestion
            multiple: true
```

2023-10-23 13:52 UTC, swirtSJW commented on config/sync/views.view.content.yml
> -            editorial-archived: editorial-archived
This should have never been limited.  It was just outdated.

2023-10-23 13:52 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 13:53 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            operator: moderation_state_multiple_workflow_filter_op
```suggestion
            operator: moderation_state_op
```

2023-10-23 13:53 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +              admnistrator_users: '0'
We have more users than we had when this was last updated.  These are expected.

2023-10-23 14:29 UTC, swirtSJW commented on config/sync/views.view.content.yml
> -            editorial-archived: editorial-archived
Incorrectly limited in the old.

2023-10-23 14:29 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:29 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            operator: moderation_state_multiple_workflow_filter_op
```suggestion
            operator: moderation_state_op
```

2023-10-23 14:31 UTC, swirtSJW commented on config/sync/views.view.content.yml
> -            editorial-archived: editorial-archived
Incorrectly limited which was inadvertently hiding "pending appoval" status.

2023-10-23 14:31 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:31 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +            operator: moderation_state_multiple_workflow_filter_op
```suggestion
            operator: moderation_state_op
```

2023-10-23 14:32 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:32 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator: moderation_state_multiple_workflow_filter_op
```suggestion
            operator: moderation_state_op
```

2023-10-23 14:33 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:34 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:35 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator: moderation_state_multiple_workflow_filter_op
```suggestion
            operator: moderation_state_op
```

2023-10-23 14:40 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:41 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:43 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:44 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:44 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:45 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:45 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:46 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:46 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:47 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:47 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator: moderation_state_multiple_workflow_filter_op
```suggestion
            operator: moderation_state_op
```

2023-10-23 14:48 UTC, swirtSJW commented on config/sync/views.view.facility_services.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:48 UTC, swirtSJW commented on config/sync/views.view.knowledge_base_article_administration.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:48 UTC, swirtSJW commented on config/sync/views.view.metatag_audit.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:49 UTC, swirtSJW commented on config/sync/views.view.rich_text_field_audit.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:49 UTC, swirtSJW commented on config/sync/views.view.va_forms.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:50 UTC, swirtSJW commented on config/sync/views.view.va_forms.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:50 UTC, swirtSJW commented on config/sync/views.view.va_forms.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 14:50 UTC, swirtSJW commented on config/sync/views.view.vamc_alerts_and_operating_statuses.yml
> +            operator_id: moderation_state_multiple_workflow_filter_op
```suggestion
            operator_id: moderation_state_op
```

2023-10-23 20:17 UTC, laflannery commented
@swirtSJW I have no issues however I definitely thought that someone said "Editorial Workflow" would be gone from here so I just want to make sure that this is what I should be seeing
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/0025d985-cc56-48d0-b33c-027ba7a465b8)

If so, I shall go ahead and approve

2023-10-23 20:35 UTC, swirtSJW commented
> @swirtSJW I have no issues however I definitely thought that someone said "Editorial Workflow" would be gone from here

It definitely should be gone from there.  Which View is that?

2023-10-23 20:36 UTC, laflannery commented
@swirtSJW this one: https://pr15769-4wq0cjp3zdblysiz1xjp3l1xc9kegtfq.ci.cms.va.gov/admin/content/audit/phone-numbers

I just clicked on another (Meta tags) and saw it was gone so I'll look at that one

2023-10-23 20:37 UTC, swirtSJW commented
They all should look like this
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/d230e83b-64d2-4362-9855-eedd16051894)

2023-10-23 20:39 UTC, swirtSJW commented
@laflannery  I see it, it looks like just the phone audit has had a regression for some reason.
Fixing that now.

2023-10-23 20:48 UTC, laflannery approved these changes

2023-10-24 01:22 UTC, swirtSJW commented
I just fixed the phone audit to add the right filter back in.

2023-10-24 11:40 UTC, omahane requested changes
For the most part, this looks great.

I see a couple issues, one functional and the other related to user interface.

## Functional
The [Metatag audit](https://pr15769-4wq0cjp3zdblysiz1xjp3l1xc9kegtfq.ci.cms.va.gov/admin/content/audit/metatag?type=health_care_local_facility&moderation_state=published&section=All) doesn't seem to return content correctly. For instance, "Moderation state" = "Draft", returns no results, even though we have plenty of content in Draft state.
![Screenshot 2023-10-24 at 6 16 05 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/4545c411-fd7f-419b-9285-be89b0897ee7)

## User interface
The "[Content audit - Buttons](https://pr15769-4wq0cjp3zdblysiz1xjp3l1xc9kegtfq.ci.cms.va.gov/admin/content/audit/buttons)" has the incorrect title above the results table.
![Screenshot 2023-10-24 at 5 50 37 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/51dedf5a-c539-436d-a879-88bcc17ed4e2)

2023-10-24 12:43 UTC, swirtSJW commented
Good catches.  Checking the metatag and button audit.

2023-10-24 14:04 UTC, swirtSJW commented
I found why the metatag view is broken.  Not  a new change.  An existing defect
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/9f781238-3910-4118-9e1c-76b666fdf4da)

2023-10-24 14:15 UTC, ndouglas commented
Think the GitHub workflows complaint is because I just merged a couple PR updating actions and it's confused.

2023-10-24 15:07 UTC, omahane approved these changes
This looks great. It's working on all pages.

2023-10-25 19:02 UTC, ndouglas approved these changes
This looks good to me. Thank you for asking for a review, and sorry about the delay. I need some kind of automated queue to keep track of what I should be doing 🥵

2023-10-25 19:08 UTC, swirtSJW commented
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/21ea4740-252e-439e-8acf-23db7ddc99ef)

2023-10-25 19:08 UTC, merged