VACMS-15891: Update Q&A Content Report View to use Multiple Workflow Filter
department-of-veterans-affairs/va.gov-cms pull request #15896
Opened 2023-10-27 22:20 UTC by chri5tia

## Description

Relates to #15891 

## Testing done
Locally

## QA steps
Pasted from style guide:
https://prod.cms.va.gov/admin/structure/cm_document/note/124/views-style-guide

As a developer logged in as administrator, go to https://va-gov-cms.ddev.site/admin/structure/views/view/content/edit/page_qa

- [ ] Display machinename, not `default`, is page_qa
- [ ] URL is [`/admin/content/qa`] (And note if there is a more appropriate parent view than content)
- [ ] Menu item setting: Should be a menu tab "Page-specific Q&A"
- [ ] Limit to 100 per page, paginated
- [ ] Show result count in header below any exposed filters. (`<p>Displaying @start - @end of @total</p>`)
- [ ] Has table caption describing the table
- [ ] Columns
   - [ ] Title (sortable)
   - [ ] Edit button (not operations, no heading)
   - [ ] Content type (sortable) (if applicable)
   - [ ] Moderation State
   - [ ] Section (field_administration) (sortable)
   - [ ] Is Locked (optional)
   - [ ] Last updated (date time and by user) (sortable, default sort, DESC)
   - [ ] [Other content fields as needed] (sortable)
- [ ] Filters
   - [ ] Exposed
      - [ ] "Title contains" (text search of title field)
      - [ ] "Content type" (single value drop down or multivalue? should options be limited) (if applicable)
      - [ ] "Moderation state"  - Must use the one for multiple workflows (single value drop down or multivalue?)
      - [ ] "Section" (workbench access section; single select, show children)
      - [ ] Order of filters matches order of columns
       - [ ] Reset button exists
       - [ ] Apply button says 'Filter'
- [ ] Tab navigation is alpha sorted or intentionally grouped

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-10-27 22:23 UTC, jilladams commented on config/sync/views.view.content.yml
> -    - field.storage.node.field_clp_faq_paragraphs
Contents of the report shouldn't be changing, just workflow, so checking: Was this removal intentional?

2023-10-27 22:23 UTC, jilladams commented on config/sync/views.view.content.yml
> -    - field.storage.paragraph.field_questions
Same here - was this removal intentional?

2023-10-27 22:58 UTC, chri5tia commented on config/sync/views.view.content.yml
> -    - field.storage.node.field_clp_faq_paragraphs
These were added in the last PR but I don't think they're needed. My system is suggesting their removal.

2023-10-28 02:47 UTC, swirtSJW commented on config/sync/views.view.content.yml
> -    - field.storage.node.field_clp_faq_paragraphs
I agree with Jill.  There are some changes in this PR that seem unexpected.

2023-10-28 02:50 UTC, swirtSJW commented
> As a developer logged in as administrator, go to https://va-gov-cms.ddev.site/admin/structure/views/view/content/edit/page_qa

Sending me to my own ddev site is a sure fire way to confuse me :)

2023-10-28 02:56 UTC, swirtSJW requested changes
Must:  This caption change got applied to all displays in the View, so we now have things like this
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/722c61d5-538b-48ef-a2c9-52557a95b2da)


I think there are some other issues.. but this one is a definite show stopper.

2023-10-28 03:02 UTC, swirtSJW commented
Must:
Tab has gone AWOL
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/614965cc-21a2-455d-97bd-410e3286d299)

I see that you changed the path to be under audit, but it has no tab in that section.

2023-10-28 03:07 UTC, swirtSJW commented
I think either the wrong filter is being used for section or it is misconfigured.  It should show the children of a section.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/8c0dc3fd-a0f4-4a21-bdbc-092f67f8c6ea)

2023-10-28 03:17 UTC, swirtSJW commented
Style guide-wise  there are some anti-patterns that are being used here.
Admin content is kind of our North star
Admin content is on top, QA audit on the bottom
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/672aa25e-344e-4dcd-b941-8b28878497af)

1. We are not supposed to be using the operations field.   Should be a plain edit button.
2. "Updated" should contain the latest revision editor, not have them be in a separate column. 
3. Column order is not in agreement with what the style guide calls out.

2023-10-28 03:36 UTC, swirtSJW commented
So it looks like 25  is the new 100.   It looks like when the Outdated content View was created, its pagination got mistakenly or intentionally applied to all the displays in that View.  The good news is, that is not your problem to solve.  :)

2023-10-31 05:15 UTC, chri5tia commented
## Caption

<img width="500" alt="Screenshot 2023-10-30 at 3 55 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/07933b6f-e03f-41a6-8b8b-c48ed4e2611f">

The other versions of the content audit view in a [recent, unrelated PR](https://pr15888-uizu61rw6eecymxkelmuvp5ajgfrv6rm.ci.cms.va.gov/admin/structure/views) environment do not have Captions.
<img width="1261" alt="Screenshot 2023-10-30 at 3 59 48 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/381071b5-e185-4e74-a3df-39d84cb27daa">
So it seems that adding one for Q&A also filled in the one for the template "content". Leaving this empty since we can't cleanly add unique table captions and since the others in this view are empty.

## Menu tab
Right now, the content audit is under administration/content and there doesn't seem to be a better place for it available so I am putting this one back under the content menu parent.

## Everything else
For everything else I copied "All content" and re-created the Q&A view.

2023-10-31 05:56 UTC, chri5tia commented on config/sync/views.view.content.yml
> -    - field.storage.node.field_clp_faq_paragraphs
This is evolutionary residue from my earlier work on this and is not needed in the code.

2023-10-31 05:56 UTC, chri5tia commented on config/sync/views.view.content.yml
> -    - field.storage.paragraph.field_questions
Not needed.

2023-10-31 22:07 UTC, omahane requested changes
###  Menu item setting: Is it where it belongs?
Regarding where this view should live, it should really be in Content Audit tools, making the url
`/admin/content/audit/q&a` and the 
**Local task parent**: "content(content_audit_page)"

### Result count
The QA step says that the result count should be "below any exposed filters", but it is above the filters. This "above the filters" placement also seems consistent with other views. I'm going to read "above" as a typo.

### Columns
- "Content type" is not sortable
- "Updated" comes before "Moderation State"

### Tab navigation
I'm unclear on what this means. If it refers to where the view link shows under Content, it should be moved, as stated above under "Menu item setting"
![Screenshot 2023-10-31 at 5 04 49 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/340acde8-82a7-4356-b468-83efe393fc6b)

2023-10-31 22:41 UTC, jilladams commented
@swirtSJW @omahane for awareness: I've asked Christia to triage feedback here and identify: 
MUST - what do we need todo now to get this view / PR out of the way of multiple workflows work, and get Christia on to other higher priority sprint goals / sprint work
SHOULD - work we can do as a fast follow

So: not all requested changes may be implemented in this PR, in favor of unblocking sprint priorities. We'll keep track of it. In that spirit: if your feedback isn't critical, please go ahead and approve, and we'll log the notes to take care of in a later PR.

2023-10-31 22:41 UTC, jilladams commented
Also for awareness: this view is for CAIA, we won't deliver it to them til the feedback is addressed, so it's low impact to be in a not ideal for a minute while we take care of sprint goals.

2023-11-01 13:41 UTC, omahane approved these changes
I've updated my QA response (https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15896#pullrequestreview-1707306236). Nothing is critical, though I'd say where this views shows in the menu is a SHOULD+. Given that this wasn't an option, I didn't make it such.

2023-11-01 18:15 UTC, merged