VACMS16061: updated graphql to v3.4
department-of-veterans-affairs/va.gov-cms pull request #16070
Opened 2023-11-08 22:08 UTC by edmund-dunn

## Description

Relates to #16061

## Testing done
Tested locally by running content build, build completed successfully. 
```
Finished 918 queries in 2032s with 27284 pages
https://va-gov-cms.ddev.site response time: : 33:53.878 (m:ss.mmm)
Total time to load content from GraphQL: 34:10.405 (m:ss.mmm)
Drupal successfully loaded!
Successfully piped Drupal content into Metalsmith!
```

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

1. Navigate to /admin/content/deploy and click Release Content
   - [ ] Validate that
2. Then view the web front end tugboat preview
   - [ ] Validate that it is built

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [x] `CMS Team`
- [x] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-11-08 22:45 UTC, eselkin approved these changes
lgtm

2023-11-08 23:03 UTC, swirtSJW commented on composer.json
> -            },
@edmund-dunn there are two patches being removed.  Is it confirmed that those two patches are now part of v3.4?

2023-11-09 14:57 UTC, swirtSJW commented
Release notes
- [3.4](https://www.drupal.org/project/graphql/releases/8.x-3.4)
   - [GraphQL - Moderately critical - Access bypass - SA-CONTRIB-2023-050](https://www.drupal.org/sa-contrib-2023-050)
   - [GraphQL - Moderately critical - Cross Site Request Forgery - SA-CONTRIB-2023-051](https://www.drupal.org/sa-contrib-2023-051)
- [3.3](https://www.drupal.org/project/graphql/releases/8.x-3.3)
   - MAJOR UPDATE - Drupal 10 compatibility for 3.x
   - The "graphql-php" library has been updated to one of the latest versions, making it compatible with PHP8. This can cause compatibility breaks with custom code within existing projects.
   - This version is no longer compatible with Drupal 8.
   - The code has been updated to stop using deprecated functions in Drupal 10 and also to make it compatible with PHP8.
   - The graphql explorer and voyager libraries have also been updated with the same changes as in the 4.x branch. This way, the core library "core/once" is used, and "jquery.once" is no longer used.
   - We recommend upgrading from 3.x to 4.x to take advantage of the improvements made in the GraphQL module and the underlying GraphQL library. If you still require automatic generation of the schema then take a look at the GraphQL Compose or GraphQL Core Schema projects which have implemented automatic schema generation on top of the 4.x GraphQL module.
-  3.2
   - MAJOR UPDATE - Drupal 10 compatibility for 3.x
   - The "graphql-php" library has been updated to one of the latest versions, making it compatible with PHP8. This can cause compatibility breaks with custom code within existing projects.
   - This version is no longer compatible with Drupal 8.
   - The code has been updated to stop using deprecated functions in Drupal 10 and also to make it compatible with PHP8.
   - The graphql explorer and voyager libraries have also been updated with the same changes as in the 4.x branch. This way, the core library "core/once" is used, and "jquery.once" is no longer used.
   - We recommend upgrading from 3.x to 4.x to take advantage of the improvements made in the GraphQL module and the underlying GraphQL library. If you still require automatic generation of the schema then take a look at the GraphQL Compose or GraphQL Core Schema projects which have implemented automatic schema generation on top of the 4.x GraphQL module.

2023-11-09 15:05 UTC, swirtSJW commented on composer.json
> -            },
Looks like the first one is 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/51078db8-ea33-47ce-b6c5-8b9a7aafdc3d)

2023-11-09 15:06 UTC, swirtSJW commented on composer.json
> -            },
And the second one is good too.

2023-11-09 15:21 UTC, edmund-dunn commented on composer.json
> -            },
@swirtSJW yes, I don't remove patches without doing that.

2023-11-09 15:25 UTC, swirtSJW commented
- [x] Checked revisions logs for breaking changes
- [x] Checked removed patches to make sure they made it into this version
- [x] https://pr16070-39f99ty0oncifd1xdnvs9v8m8hyaeerm.ci.cms.va.gov/graphql/explorer  Checked explorer to be operational
- [ ] Check Voyager https://pr16070-39f99ty0oncifd1xdnvs9v8m8hyaeerm.ci.cms.va.gov/graphql/voyager

2023-11-09 15:25 UTC, swirtSJW commented
Voyager seems to be non operational when compared to prod where it is working 
PR on left, prod on right.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/de9ed6c6-98cb-4ac2-92e7-0b6bf6d38f48)

2023-11-09 15:27 UTC, swirtSJW commented
Also seeing an error coming out of a test
https://pr16070-39f99ty0oncifd1xdnvs9v8m8hyaeerm.ci.cms.va.gov/admin/reports/dblog?type%5B%5D=graphql
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/272d6563-f6b1-4d17-a7aa-953492e95d17)

2023-11-09 15:29 UTC, swirtSJW requested changes
I am seeing two defects that need to be checked out
- [ ] Voyager not working
- [ ] Error coming from test (need to check other pr environments to see if they also include that error to determine if it is coming from this update or not
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/d7eb2cbd-8dec-4986-8423-635230969677)

2023-11-09 15:44 UTC, edmund-dunn commented
> Also seeing an error coming out of a test https://pr16070-39f99ty0oncifd1xdnvs9v8m8hyaeerm.ci.cms.va.gov/admin/reports/dblog?type%5B%5D=graphql ![image](https://user-images.githubusercontent.com/5752113/281782491-272d6563-f6b1-4d17-a7aa-953492e95d17.png)

This is an existing error. I see it on staging.
![CleanShot2023-11-09at07 43 59](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/109987005/c699fdbf-c4c2-435a-82dc-a51cd0864d37)

2023-11-09 16:13 UTC, edmund-dunn commented
> Voyager seems to be non operational when compared to prod where it is working PR on left, prod on right. ![image](https://user-images.githubusercontent.com/5752113/281781986-de9ed6c6-98cb-4ac2-92e7-0b6bf6d38f48.png)

Voyager is not functioning correctly on prod either. If Voyager is needed then an issue can be entered and we will get it working. Since this has never been brought up before I think we can safely assume that its notbeing used by anyone at this time. @ndouglas thoughts?
![CleanShot2023-11-09at08 08 50](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/109987005/d01f6751-75dd-4bfc-ba6d-9a18322ab4e2)

2023-11-09 16:42 UTC, ndouglas commented
Voyager's never worked. 

We're not going to delay a security update because someone we don't really use and has never worked correctly seems to be broken in a different way than previously.

If someone wants Voyager to work, then they can open an issue for it.

2023-11-09 17:12 UTC, ndouglas commented
According to [this ticket](https://github.com/drupal-graphql/graphql/issues/1238), Voyager might not have worked for a long time on 3.x

2023-11-09 19:04 UTC, swirtSJW commented
Voyager is throwing an error on prod and is not drawing the graph, but it still allows a FE developer to explore the available fields on a content type 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/b0cb2078-6470-405d-855b-cec8b458fd1b)


That can not be done at all after this upgrade.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/835a12f4-be6d-4fa1-a9d4-643df1046641)

It does not need to hold up the security update (which zero trust or not is a non-issue because it is only preventing someone from reading our data, which is all publicly available anyway. Passwords would be the only thing at risk... if graphQL could surface them, which it can not.)   But I do not want to bury this as, it has always been broken when it is now more broken than it has been.

Also there is some history of other teams asking for it in the past
- https://dsva.slack.com/archives/C0FQSS30V/p1604585083323700?thread_ts=1604584812.323400&cid=C0FQSS30V  Michael Pelz Sherman in a conversation with Dave Conlon
- https://dsva.slack.com/archives/CDHBKAL9W/p1641741179016900 Napoleon Kerzant in a conversation with Ryan and I.

I swear Neil got it working after Napoleon requested it, but I can find no record of it now.

2023-11-09 19:25 UTC, swirtSJW approved these changes
My concerns were addressed by feedback from @ndouglas and @edmund-dunn so I am approving this.

2023-11-14 17:17 UTC, dsasser submitted a review, later dismissed
LGTM

2023-11-15 13:21 UTC, ndouglas commented
All I did was resolve a merge conflict, so I'll merge once tests pass.

2023-11-15 14:31 UTC, merged