Documentation updates
department-of-veterans-affairs/va.gov-cms pull request #16253
Opened 2023-11-30 18:24 UTC by JunTaoLuo

## Description

Resolves https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16228. 

## Acceptance Criteria

### Broken or missing links
These are links in our documentation that are missing documentation or pointing to outdated links. The action items here are to create new documentation, link to updated content or remove the original link.

Top level [Readme](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/efc87a8b61a98e5e5b9824a8da0c4743ef795a3d/README.md)
- [x] 3.vi - should this be pointing to comparing-graphql-output.md?
- [ ] 4.iii - new documentation need to be added
- [x] 5.i - missing architecture overview
- [ ] 5.ii - missing drupal overview, otherwise we should consolidate it and its subsection to Drupal - Memcache
- [ ] 5.iv - missing MetalSmith documentation
- [x] 5.ix - broken link to downstream dependencies

QA [Readme](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/1bcc9937a697280a9669ee1ff84a41ede0abde80/READMES/qa.md)
- [x] Broken Conflence from outdated va-gov domain

Security [Readme](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/efc87a8b61a98e5e5b9824a8da0c4743ef795a3d/READMES/security.md) 
- [x] Fortify Security Scans was removed in https://github.com/department-of-veterans-affairs/va.gov-cms/commit/e9aca3cfa3824481311f7bcd3dc64abca04b590f
- [x] Security policy has been moved to https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/SECURITY.md

### Unlinked or orphaned content
The action items are to decide if these content should be linked in the top level Readme's TOC. Some content may be outdated and should be moved to READMES/historical.

- [x] analytics.md
- [x] blackfire.md
- [x] codeowners.md
- [x] comparing-graphql-output.md
- [x] dependabot-alerts.md
- [ ] distribution-group-mgmt.md
- [x] jsonapi.md
- [ ] multilingual.md
- [x] remove-deprecated-fields.md
- [x] scalability-testing.md
- [x] sentry.md
- [ ] translation.md
- [ ] user_management.md

### Documentation update
The action items here are to update our documentation to reflect our current workflow and recommendations.

- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/https.md Update OSX instructions for new macOS UI
- [x] Use branches instead of forks in our getting started recommendations
- [x] Update getting started steps to include:
  - create .env from .env.example
  - ddev pull va --skip-files requirement for running locally
- [x] How to find link to cypress logs from CI Tugboat images
- [x] Insert link to the docs at https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms

## Testing done

None since these are doc updates

## Screenshots

None

## QA steps

None

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] ~~Tests have been added if necessary.~~
- [ ] ~~Automated tests have passed.~~
- [ ] ~~Code Quality Tests have passed.~~
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] ~~If there are field changes, front end output has been thoroughly checked.~~

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

2023-12-15 16:31 UTC, ndouglas requested changes
Mostly looks fantastic! Just a couple of moves and a couple of deletions I disagree with. No other major complaints.

2023-12-15 16:31 UTC, ndouglas commented on README.md
> +      - Cypress test logs and artifacts, see [Testing](READMES/testing.md) for details.
Note to self: I'm moving this file to `automated-tests.md` in a separate PR.

2023-12-15 16:31 UTC, ndouglas commented on READMES/translation.md
This needs to remain.

2023-12-15 16:31 UTC, ndouglas commented on READMES/multilingual.md
This needs to remain.

2023-12-15 16:31 UTC, ndouglas commented on READMES/devops/distribution-group-mgmt.md
I don't think this should be moved.

2023-12-15 16:31 UTC, ndouglas commented on READMES/devops/user_management.md
I don't think this should be moved either. This is mostly helpdesk-facing.

2023-12-15 16:35 UTC, JunTaoLuo commented on READMES/translation.md
Hmm let's also check with @EWashb who recommended moving it to [Product Outlines](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines). Same with multilingual.md

2023-12-15 16:35 UTC, JunTaoLuo commented on README.md
> +      - Cypress test logs and artifacts, see [Testing](READMES/testing.md) for details.
I was planning on fixing up these links after you merge your PR.

2023-12-15 16:38 UTC, JunTaoLuo commented on READMES/devops/distribution-group-mgmt.md
Ok I moved it back. Just for my understanding how are this and user_management related to dev work in CMS?

2023-12-15 16:41 UTC, JunTaoLuo commented on READMES/devops/user_management.md
I wonder if this is a better home for it then? https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/helpdesk

2023-12-19 17:36 UTC, JunTaoLuo commented on READMES/translation.md
Reverted, will follow up in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16498

2023-12-19 17:36 UTC, JunTaoLuo commented on READMES/multilingual.md
Reverted, will follow up in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16498

2023-12-19 17:36 UTC, JunTaoLuo commented on READMES/devops/distribution-group-mgmt.md
Reverted, will follow up in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16498

2023-12-19 17:36 UTC, JunTaoLuo commented on READMES/devops/user_management.md
Reverted, will follow up in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16498

2023-12-19 17:55 UTC, olivereri approved these changes

2023-12-19 18:25 UTC, JunTaoLuo commented
Since Nate and Edmund are both out and Nate's comments have been addressed (all moved files were reverted), I'm merging this now.

2023-12-19 18:25 UTC, merged