16457 Update/patch entity_browser module
department-of-veterans-affairs/va.gov-cms pull request #16542
Opened 2023-12-21 16:29 UTC by edmund-dunn

## Description

Closes #16457.

This updates the `entity_browser` module and patches it and the `entity_browser_tables` module. There were breaking changes in `entity_browser` see https://www.drupal.org/project/entity_browser/issues/3407702 for reference.

## Testing done
Tested locally. Cypress tests that failed in the dependabot PR passed locally. 

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

Mostly this would be considered good to go if autoated tests pass. However in light of the information on breaking changes we need each product team to review to make sure that none of their custom code is effected by those breaking changes.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [x] `CMS Team`
- [x] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2023-12-21 16:59 UTC, dsasser commented
@edmund-dunn changes look good but there appears to be a cypress test failure.

2023-12-21 20:16 UTC, edmund-dunn commented
> @edmund-dunn changes look good but there appears to be a cypress test failure.

@dsasser that test is no longer needed. Per https://www.drupal.org/project/entity_browser/issues/3074457 that is now part of entity_browser.

2024-01-02 20:43 UTC, BerniXiongA6 commented
@edmund-dunn would you be able to size this one since i'ts already in progress? Thank you very much cc: @maortiz-27-80

2024-01-04 12:55 UTC, ndouglas approved these changes
This is fine to merge from my perspective once merge conflicts are resolved 🙂

2024-01-04 21:45 UTC, dsasser reviewed
The patch for entity_browser is a bit weird in that it is loading entities that ostensibly should already be there. Swirt had a similar sentiment [on the d.o issue](https://www.drupal.org/project/entity_browser/issues/3408216#comment-15379911).

2024-01-05 16:17 UTC, edmund-dunn commented
@dsasser that was a good call. I was able to remove that patch. The patch on entity_borwser_tabloe to bring it in line with the changes to entity_browser seemed to have fixed our issues.

2024-01-05 16:26 UTC, dsasser requested changes

2024-01-05 16:26 UTC, dsasser commented on patches/3408216-error-call-to-member-function-getstorage-on-null.patch
SHOULD:

Do we need this patch if we are no longer including it in Composer?

2024-01-05 16:42 UTC, edmund-dunn commented on patches/3408216-error-call-to-member-function-getstorage-on-null.patch
It is removed. Good cal!

2024-01-05 16:43 UTC, dsasser approved these changes

2024-01-05 20:12 UTC, swirtSJW approved these changes
I am happy that original patch has been removed.

### QA Steps
Review instances of entity browser:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/b42e7381-4555-45dd-a2ab-a931988aa14a)
There are only 2 instances of entity_browser_table being used on Facilities products do my QA is limited to those.   In the absence of actual QA steps on the PR, I am assuming that CMS team and PW team have reviewed the other instances. 

- [x] Validate that vet_center_locations_list is working as it should be
prod on right
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/37e4e2a3-58f0-425c-8b49-cfce1c6fb5e4)

added entities successfully
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/c304166e-edff-4531-a1ec-4a8f570d0556)

Removed entities successfully
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/a151cc00-b79d-4d91-b322-48280eccb999)


- [x] Validate that paragraph.contact_information  is working as it should be
Prod on right
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/be21a179-ade3-4ecd-b6f2-687dfcf2b116)

Added and removed phone numbers fine.  Allowed number of entries still work
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/a5982b78-753a-4de5-88ee-5d772e9de4cd)

2024-01-05 20:27 UTC, merged