Vacms 16853 next build branches ftw
department-of-veterans-affairs/va.gov-cms pull request #17154
Opened 2024-02-06 18:09 UTC by alexfinnarn

## Description

closes #16853

## Testing done

- Updated some tests for git information/API/frontend. 
- Manually tested locally by running script.
- Need to test on Tugboat with this PR.

## Screenshots

Content release form when you can trigger a build.
<img width="964" alt="Screenshot 2024-02-06 at 1 06 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/3640707/268bf177-46b9-47fd-b8fb-752973072986">

Content release form when build is running with a link to the build log.
<img width="885" alt="Screenshot 2024-02-06 at 1 08 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/3640707/ff233355-681f-482b-a3e2-ac8a85bae43c">

## QA steps

1. Log in and go to "/admin/content/deploy/next_git"
   - [ ] Validate that
2. Then choose a next branch and submit the form.
   - [ ] Validate that
3. Wait X seconds and reload the form...
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

2024-02-09 17:49 UTC, tjheffner requested changes

2024-02-09 17:49 UTC, tjheffner commented on docroot/sites/default/settings/settings.local.php
> +// Match next frontend variables with Tugboat.
This comment feels misleading to me. Also I think we'll want to target port `3999` locally, based on the [.env.example in next-build](https://github.com/department-of-veterans-affairs/next-build/blob/main/envs/.env.example#L29)

2024-02-09 17:49 UTC, tjheffner commented on docroot/sites/default/settings/settings.local.php
> +// Match next frontend variables with Tugboat.
Actually I'm not sure that these `$settings` are needed at all. The default values in config may need to be updated, though.

`settings.tugboat.php` updates these:
```php
// Update next-build site endpoint to the appropriate tugboat alias
$config['next.next_site.next_build_preview_server']['base_url'] = 'https://next-' . getenv('TUGBOAT_SERVICE_TOKEN') . '.' . getenv('TUGBOAT_SERVICE_CONFIG_DOMAIN');
$config['next.next_site.next_build_preview_server']['preview_url'] = 'https://next-' . getenv('TUGBOAT_SERVICE_TOKEN') . '.' . getenv('TUGBOAT_SERVICE_CONFIG_DOMAIN') . '/api/preview';
```

You are changing `$settings` here instead of `$config`. And the config from `next.next_site.next_build_preview_server.yml` defaults to 
```
base_url: 'http://localhost:3000'
preview_url: 'http://localhost:3000/api/preview'
```

2024-02-09 17:49 UTC, tjheffner commented on scripts/next-install.sh
>  echo "Yarn $(yarn -v)"
what yarn version gets used here if the corepack stuff is commented out?

2024-02-09 17:49 UTC, tjheffner commented on docroot/sites/default/settings.php
> +$settings['va_gov_next_build_root'] = '../next';
is there a reason this is relative vs the rest of the roots above? `/var/www/cms/next` ?

2024-02-09 17:49 UTC, tjheffner commented on docroot/modules/custom/va_gov_content_release/va_gov_content_release.module
> -<?php
was this mistakenly deleted?

2024-02-09 17:49 UTC, tjheffner commented on docroot/modules/custom/va_gov_content_release/src/Form/NextGitForm.php
> +    $frontend_base_url = $this->settings->get('next.next_site.next_build_preview_server')['base_url'] ?? 'https://www.va.gov';
can this load from `$config` instead of `$settings`? The tugboat links to va.gov because these settings aren't set on tugboat, the url gets loaded from config.

2024-02-09 17:49 UTC, tjheffner commented on docroot/modules/custom/va_gov_content_release/README.md
> +# VA.gov Content Release
READMEs are generally included in the root `READMES` directory instead of at the module level. `cms-content-release.md` is probably worth updating with a `## next-build release` section.

2024-02-09 17:49 UTC, tjheffner commented on scripts/next-build-frontend.sh
> +# The currently selected version of content-build (may be "__default", a PR#, or a git ref)
```suggestion
# The currently selected version of next-build (may be "__default", a PR#, or a git ref)
```

2024-02-09 17:49 UTC, tjheffner commented on scripts/next-build-frontend.sh
> +# Get the requested content-build version
```suggestion
# Get the requested next-build version
```

2024-02-09 17:49 UTC, tjheffner commented on scripts/next-build-frontend.sh
> +  echo "==> Using default content-build version" >> ${logfile}
```suggestion
  echo "==> Using default next-build version" >> ${logfile}
```

2024-02-09 18:24 UTC, alexfinnarn commented on docroot/sites/default/settings/settings.local.php
> +// Match next frontend variables with Tugboat.
At one point I was under the impression that Drupal merged `$config` and `$settings` into the same array before applying them, but that does not seem to be the case...I swear that used to be the case, but I'm probably wrong. D7 did use `$conf` though for `$setitngs` so maybe that's where I got it...

But regardless, I was following the pattern here https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/modules/custom/va_gov_content_release/src/FrontendUrl/FrontendUrl.php#L38 and looking for some kind of settings variable. 

I see `next.next_site.next_build_preview_server.base_url` config, and I will try to pull that value in.

2024-02-09 18:30 UTC, alexfinnarn commented on scripts/next-install.sh
>  echo "Yarn $(yarn -v)"
I have no idea, but I can find out...actually, it should still say in the build logs...here's what my Tugboat QA spit out.

```
==> Installing yarn dependencies
> # Prepare the next build project
> ! ./scripts/should-run-directly.sh || ./scripts/next-install.sh
Repo next-build already cloned.
v18.17.0 is already installed.
Now using node v18.17.0 (npm v9.6.7)
Now using node v18.17.0 (npm v9.6.7)
Node v18.17.0
NPM 9.6.7
Yarn 3.6.1
```

2024-02-09 18:37 UTC, alexfinnarn commented on docroot/sites/default/settings.php
> +$settings['va_gov_next_build_root'] = '../next';
No reason, just I knew that next was one directory above the docroot. I thought the right location for next was `/var/www/html/next` in ddev, but I could have gotten the wrong place if the repo is included other places. I don't see `/var/www/cms` locally, just `/var/www/html/web` which is a symlink to `docroot/vendor/va-gov/content-build`. But since this is a default settings file, I'm not sure these values carry through other overrides. They do get overriden in other settings files.

2024-02-09 18:40 UTC, alexfinnarn commented on docroot/modules/custom/va_gov_content_release/va_gov_content_release.module
> -<?php
No, I just didn't think the blank module file was needed. I added a `hook_cron` for debugging on Tugboat, but after that wasn't needed, I deleted it. Drupal no longer requires a module file like in the past, but I can put it back if there are coding standards requiring one. 

Reference: https://www.drupal.org/node/2217931

2024-02-09 18:40 UTC, alexfinnarn commented on docroot/modules/custom/va_gov_content_release/src/Form/NextGitForm.php
> +    $frontend_base_url = $this->settings->get('next.next_site.next_build_preview_server')['base_url'] ?? 'https://www.va.gov';
yeah I screwed this up and will change it.

2024-02-09 18:47 UTC, alexfinnarn commented on docroot/modules/custom/va_gov_content_release/README.md
> +# VA.gov Content Release
Hmm, I wonder how many times people forget to read those then, like me. I probably should have found that readme before now, but didn't look since some modules like `va_gov_build_trigger` have readmes with the module, albeit they are blank.

I can move the next-build section to that file and delete what I wrote for content-build since that part is covered.

2024-02-09 19:12 UTC, alexfinnarn commented on docroot/modules/custom/va_gov_content_release/README.md
> +# VA.gov Content Release
Well, I'm adding to the `ms-content-release.md` doc, but that links to `environments.md` for some details...oh well, probably good enough for now as I assume more tickets will touch this work and alter what the docs currently say, especially for how this will work on production and whatnot.

2024-02-09 19:39 UTC, alexfinnarn commented on docroot/sites/default/settings/settings.local.php
> +// Match next frontend variables with Tugboat.
I updated the config file to use port 3999 and deleted those settings. Seems to work on Tugboat. 

<img width="784" alt="Screenshot 2024-02-09 at 2 38 55 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/3640707/bd6ea023-96fd-4aa3-9091-0a942b894890">

2024-02-09 21:19 UTC, tjheffner commented on docroot/sites/default/settings.php
> +$settings['va_gov_next_build_root'] = '../next';
if they get overridden elsewhere i'm not too worried about it. `/var/www/cms/` may even be leftover from when the project used lando before ddev. it just stuck out to me because it was noticeably different format than the lines above.

2024-02-09 21:45 UTC, tjheffner approved these changes

2024-02-15 20:19 UTC, edmund-dunn approved these changes
This looks good, nice and clean!!

2024-02-15 20:26 UTC, merged