VACMS-17426: Requires VA facility location when the event is using a VA facility location type
department-of-veterans-affairs/va.gov-cms pull request #17859
Opened 2024-04-16 03:11 UTC by dsasser

## Description

Relates to #17426

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2024-04-16 15:17 UTC, omahane requested changes
The fields seem to be required, having all the trappings of requirement, but I can save the page without filling in either VA location (when "At a VA facility" is chosen) or an address (when "At a non-VA location" is chosen).

I did this here: https://pr17859-vpvmby9elrebdlxtkz0lfeyzfggxlf4j.ci.cms.va.gov/node/67710/edit

Here's a video of me doing so.

https://www.loom.com/share/05c581e632e94fbf8786bb528fa6f9cf?sid=34adf16d-4c51-4c74-ae11-d071e7fdd5d4

2024-04-16 18:41 UTC, dsasser commented
> The fields seem to be required, having all the trappings of requirement, but I can save the page without filling in either VA location (when "At a VA facility" is chosen) or an address (when "At a non-VA location" is chosen).
> 
> I did this here: https://pr17859-vpvmby9elrebdlxtkz0lfeyzfggxlf4j.ci.cms.va.gov/node/67710/edit
> 
> Here's a video of me doing so.
> 
> https://www.loom.com/share/05c581e632e94fbf8786bb528fa6f9cf?sid=34adf16d-4c51-4c74-ae11-d071e7fdd5d4

That's....not good at all. And I was able to replicate this prior to this change as well, so something very peculiar is going on that I'll need to look into.

2024-04-17 19:31 UTC, dsasser commented
@edmund-dunn @omahane I verified that this is an existing bug, not introduced in this PR, and I think I have located the culprit: clientside validation (or so it seems).

![Screenshot 2024-04-17 at 12 23 28 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/16642257-7268-4882-948b-fe914f9709a4)

If I disable clientside validation for all forms, then Events are validated client-side as expected. But re-enabling that setting, and I'm able to bypass client-side validation. To recreate on staging:

1. Visit node/67744/edit
2. Make no changes, and attempt to save (it shouldn't let you since a revision log is required).
3. Notice how it let you submit the form unexpectedly (no browser/client-side error), but thankfully Drupal's backend field validation prevented saving.
4. Visit /admin/config/user-interface/clientside-validation
5. Uncheck the box to disable clientside validation for all forms, and save the form.
6. Revisit node/67744/edit (make sure you load the page again if you have it open in a separate tab)
7. Try to save.
8. Notice you get the expected browser validation error

2024-04-17 23:14 UTC, jilladams commented
Noting: next steps for what we do about that bug are in discussion on the ticket; https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17426#issuecomment-2062420134

2024-04-18 15:44 UTC, dsasser commented
@omahane given we know that the [issue you found](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17859#pullrequestreview-2003952724) is pre-existing, how would you feel about reviewing this with Clientside Validation turned off?

2024-04-18 16:51 UTC, omahane commented on docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js
> +  const toggleFacilityLocationRequiredFields = (enableDisable, addRemove) => {
I am unsure why `enableDisable`. I see that it's used elsewhere:
`fieldAddressAdminArea.required = enableDisable;`

Is there a functional reason for the difference?

2024-04-26 21:20 UTC, omahane approved these changes
Code looks good. And the UI/UX is working. Let's hope that the subsequent work to get clientside_validation out of the way will make the browser validation work correctly.

2024-04-27 15:04 UTC, merged