DO NOT MERGE VACMS-17860: Updates staff phone field to paragraph field
department-of-veterans-affairs/va.gov-cms pull request #19038
Opened 2024-08-25 16:40 UTC by dsasser

## Description

Relates to #17860 

## Testing done
Unit tests for the phone number extraction, and manual testing and QA for the phone data migration.

## Screenshots
N/A

## QA steps
TBD

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [x] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

2024-09-04 20:19 UTC, jv-agile6 commented on .ddev/nginx_full/nginx-site.conf
default nginx config added for batch process.

2024-09-04 20:20 UTC, jv-agile6 commented on .github/CODEOWNERS
Custom module va_gov_batch

2024-09-04 20:20 UTC, jv-agile6 commented on .github/CODEOWNERS
> +/docroot/modules/custom/va_gov_batch                                @department-of-veterans-affairs/public-websites-cms
Custom module va_gov_batch

2024-09-04 20:21 UTC, jv-agile6 commented on composer.json
added codit_batch_operation and giggsey/libphonenumber-for-php libraries

2024-09-04 20:23 UTC, jv-agile6 commented on config/sync/core.entity_form_display.node.person_profile.default.yml
Config changes on field.field.node.person_profile.field_telephone. telephone paragraph added telephone field removed

2024-09-04 20:29 UTC, jv-agile6 commented on config/sync/codit_batch_operations.settings.yml
Using codit batch operations, enabled va_gov_batch script set user to 1317 and enabled cron zero.

2024-09-04 20:35 UTC, jv-agile6 commented on config/sync/field.field.node.person_profile.field_telephone.yml
👀

2024-09-04 20:37 UTC, jv-agile6 commented on config/sync/views.view.rich_text_field_audit.yml
added fields for phone number and another for extension

2024-09-04 20:41 UTC, jv-agile6 commented on docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigratePhoneFieldToParagraph.php
va_gov_batch module for cbo_script to use phone field to paragraph migration

2024-09-04 20:44 UTC, jv-agile6 commented on docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigratePhoneFieldToParagraph.php
> +use JetBrains\PhpStorm\ArrayShape;
👀

2024-09-04 20:44 UTC, jv-agile6 commented on docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigratePhoneFieldToParagraph.php
> +use JetBrains\PhpStorm\ArrayShape;
👀

2024-09-04 20:48 UTC, jv-agile6 commented on docroot/modules/custom/va_gov_profile/va_gov_profile.deploy.php
add MigratePhoneFieldToParagraph to deploy

2024-09-04 20:50 UTC, jv-agile6 approved these changes
Reviewed code additions and subtraction for VACMS-17860: Updates staff phone field to paragraph field #19038. Followed both form and logic with no identifiable defects.

2024-09-10 15:41 UTC, dsasser commented on .ddev/nginx_full/nginx-site.conf
> but I believe that it is intended for this to be generated

That is the case initially, but our setup requires the buffers to be bumped up beyond the default in order to accept large POST requests (graphql). This ddev config change has been [vetted with the CMS team](https://dsva.slack.com/archives/CT4GZBM8F/p1724701371261819?thread_ts=1724692145.752969&cid=CT4GZBM8F).

2024-09-10 16:23 UTC, omahane approved these changes
I've been using this code as the base for my own changes, and it's been working well without issue.

2024-09-16 16:37 UTC, timcosgrove requested changes
Just a small request to bring the nginx-site.conf in the PR in line with the current generated ddev one; only substantive change is on the list of handled files.

2024-09-16 16:59 UTC, dsasser commented on .ddev/nginx_full/nginx-site.conf
> +# ddev drupal9 config
Good catch. [Updated](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19038/commits/97817bfb55a6f1b936afe3ef3c3c89a49e8650b0).

2024-09-16 17:10 UTC, timcosgrove approved these changes

2024-09-16 17:22 UTC, merged