VACMS-19227: Adds Philippines as a US state for facility purposes
department-of-veterans-affairs/va.gov-cms pull request #20068
Opened 2024-12-09 22:16 UTC by omahane

## Description

Relates to #19227 

## Testing done
Manually

## Screenshots

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2024-12-10 15:13 UTC, omahane commented
@edmund-dunn @dsasser I have a change in this PR that replaces the default states in the US with a list that includes the Philippines, as we have facilities in the Philippines that are mapped to US addresses by way of the Lighthouse API: 
<img width="705" alt="Screenshot 2024-12-10 at 9 02 00 AM" src="https://github.com/user-attachments/assets/b0284357-b967-4ff4-97f2-59fd7a4a5116">

Do you think it makes more sense to keep it in the `va_gov_manila` module because it's only necessary because of the Manila facilities? Or do you think that the scope of the change makes it necessary to add to a module that encompasses more features, such as `va_gov_facilities` or `va_gov_backend`?

2024-12-10 18:10 UTC, omahane commented
Based on the conversation on Slack, I chose to create a new module and add the code to that: https://dsva.slack.com/archives/CT4GZBM8F/p1733844761259909

2024-12-16 20:29 UTC, dsasser commented on docroot/modules/custom/va_gov_address/src/EventSubscriber/AddPhilippinesAsStateSubscriber.php
> +    if ($event->getParents() != ['US']) {
SHOULD:
I would suggest using strict comparison here, if possible. eg: `!==`

2024-12-16 20:29 UTC, dsasser commented on docroot/modules/custom/va_gov_address/src/EventSubscriber/AddPhilippinesAsStateSubscriber.php
> +  public function onSubdivisions(SubdivisionsEvent $event) {
SHOULD:
This should probably have unit test coverage.

2024-12-17 18:49 UTC, omahane commented on docroot/modules/custom/va_gov_address/src/EventSubscriber/AddPhilippinesAsStateSubscriber.php
> +        'AL' => [
How would I get the Philippines in there, then?

2024-12-17 21:58 UTC, dsasser commented on docroot/modules/custom/va_gov_address/src/EventSubscriber/AddPhilippinesAsStateSubscriber.php
> +        'AL' => [
You pull in the provided json and then add in the Philippines. Something like...

```php
// psuedo code
$definitions = // get definitions from .json
$definitions['subdivisions']['PH'] = [
  'code' => 'PH',
  'name' => 'Philippines',
  'country_code' => 'US',
  'id' => 'PH',
];
```

2024-12-18 23:39 UTC, dsasser commented on composer.lock
> +    "content-hash": "aa992d810ef45398cacf8ee73a2a1bd9",
Usually we don't see content-build changes showing up in PRs. Is this expected?

2024-12-18 23:40 UTC, dsasser commented on config/sync/core.extension.yml
> -  danse: 0
Looks like some unexpected changes leaked into your PR.

2024-12-18 23:40 UTC, dsasser commented on config/sync/metatag.metatag_defaults.node__event.yml
> +  title: '[node:title] | [node:field_listing:entity:field_office]  | Veterans Affairs'
More unexpected changes.

2024-12-18 23:41 UTC, dsasser commented on docroot/modules/custom/va_gov_db/va_gov_db.install
> +
More unexpected changes.

2024-12-18 23:42 UTC, dsasser commented on docroot/themes/custom/vagovclaro/assets/js/anchor_links.js
> +      //removed XOR operator because it was causing an issue where anchor lins were undefined VACMS-19375
More unexpected changes.

2024-12-18 23:44 UTC, dsasser requested changes
Looks like possibly a rebase may have caused some things to get added to this PR that are not expected. See other comments.

2024-12-19 01:46 UTC, dsasser approved these changes
Great work. Code changes are awesome and the QA steps passed. Philippines is now available for all addresses across the CMS!

<img width="637" alt="Screenshot 2024-12-18 at 5 38 11 PM" src="https://github.com/user-attachments/assets/24091d7a-7419-4dae-8f41-f6d13e3cabe0" />
<img width="1496" alt="Screenshot 2024-12-18 at 5 29 05 PM" src="https://github.com/user-attachments/assets/95bb786f-1d70-4003-8b2d-e854d6d3f6dc" />

2024-12-19 04:52 UTC, merged