WIP: VACMS-2489: Created Related Benefits entity reference field on QA con…
department-of-veterans-affairs/va.gov-cms pull request #2835
Opened 2020-09-02 15:46 UTC by kaise-lafrai

…tent type, added related links teaser on QA content type, created new related benefits entity browser.

## Description

See _issueid_. 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-09-04 21:49 UTC, swirtSJW reviewed
One suggestion and then a couple questions  (will be coming in separate comments).

2020-09-04 21:49 UTC, swirtSJW commented on config/sync/views.view.benefits_hub_categories.yml
> +    id: entity_browser_1
moderate:  I prefer to not use the default machine name on views because when we ever need to reference them in code  it is easier to understand `benefits_hub_categories` than it is to understand `entity_browser_1`  Same idea on view  pages "page_1" and view blocks "block_1"

2020-09-04 21:50 UTC, swirtSJW commented
This default seems odd.   Is it intentional that a new faq_multiple_q_a pointes to a an archived benefit hub?

2020-09-04 21:58 UTC, swirtSJW commented
@oksana-c @kaise-lafrai  We should probably discuss this default  reference to an archived node.   It seems like what we are trying to achieve here is more like back-fill behaviour that may be better as just  front end template default rather than an actual Drupal connection.

2020-09-08 15:05 UTC, kaise-lafrai commented
> @oksana-c @kaise-lafrai We should probably discuss this default reference to an archived node. It seems like what we are trying to achieve here is more like back-fill behaviour that may be better as just front end template default rather than an actual Drupal connection.
> 
> If we had to go with archived, If someone ever removed it, how would they ever put it back, since it can't be added through the UI?

The default reference was not archived on my local. Even after a db sync. @oksana-c should we continue to use the archived reference?

2020-09-08 15:18 UTC, oksana-c commented on config/sync/entity_browser.browser.lc_benefit_hubs.yml
> +  link_text: 'Select entities'
```suggestion
  link_text: 'Select Benefit Hub(s)'
```

2020-09-08 16:42 UTC, oksana-c reviewed
@kaise-lafrai , please see comments below. Everything else looks good. Per scrum convo - default value "VA health care" should remain since it is published on Prod and it is very unlikely that it will be unpublished because this is a primary benefits hubs

2020-09-08 17:22 UTC, kaise-lafrai commented on config/sync/entity_browser.browser.lc_benefit_hubs.yml
> +widget_selector: drop_down
@oksana-c I originally used single widget but realized that drop_down provides better error handling. Single widget will say something like this "1 error has been found: Select this item" drop-down will provide more detail and say something like "only 3 entities are allowed".

2020-09-08 17:31 UTC, kaise-lafrai commented on config/sync/views.view.benefits_hub_categories.yml
> +    id: entity_browser_1
I resolved this on the benefits_hub_categories view.

2020-09-08 18:35 UTC, kaise-lafrai commented
@oksana-c @swirtSJW Ready for review once checks are complete.

2020-09-09 19:17 UTC, oksana-c requested changes

2020-09-09 19:17 UTC, oksana-c commented on config/sync/field.field.node.media_list_videos.field_related_links.yml
> +description: ''
```suggestion
description: ''
```
```suggestion
description: 'Add up to 5 link teasers.'
```

2020-09-09 19:17 UTC, oksana-c commented on config/sync/field.field.node.q_a.field_related_links.yml
> +description: ''
```suggestion
description: ''
```
```suggestion
description: 'Add up to 5 link teasers.'
```

2020-09-09 19:17 UTC, oksana-c commented on config/sync/field.field.node.step_by_step.field_related_links.yml
> +description: ''
```suggestion
description: ''
```
```suggestion
description: 'Add up to 5 link teasers.'
```

2020-09-09 19:55 UTC, oksana-c approved these changes

2020-09-09 20:40 UTC, merged