VACMS-2872
department-of-veterans-affairs/va.gov-cms pull request #2879
Opened 2020-09-09 23:37 UTC by ethanteague

## Description
See #2872 

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/92665149-d263d280-f2d3-11ea-9ba9-04b13a236c35.png)

## QA steps
@oksana-c to qa manually (please).

2020-09-10 14:30 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/views.feature
> +| Recent content | Master | default | Master |
sort seems off

2020-09-10 14:33 UTC, swirtSJW reviewed
Just a couple Q related to behat.

2020-09-10 14:57 UTC, ethanteague commented on tests/behat/features/save_and_continue.feature
> +#  Scenario: Log in, edit, and save nodes with save and continue button and confirm revision saves changes.
Note above, @swirtSJW

2020-09-11 13:20 UTC, ethanteague commented on tests/behat/drupal-spec-tool/views.feature
> +| Recent content | Master | default | Master |
Just a quick note to confirm that the weird sort isn't coming from a weird rebase - just pulled in from the sheet prior to beginning any mod's, and the order matches what we are seeing above, @swirtSJW

2020-09-11 13:48 UTC, ethanteague commented
Updated, and ready for code review, @swirtSJW @oksana-c

2020-09-11 13:55 UTC, swirtSJW approved these changes

2020-09-11 13:58 UTC, swirtSJW commented
Code looks fine, but this UI seems confusing
![image](https://user-images.githubusercontent.com/5752113/92934234-3e9a1f80-f415-11ea-87bf-552165cf7cc3.png)

Are they dealing with categories or topic?   There ought to be alignment between these two.

2020-09-16 16:49 UTC, oksana-c reviewed
@ethanteague , please check updated spec in #2872 . Also, agreed w/ @swirtSJW "Add topics" should read "Add categories"

2020-09-16 16:51 UTC, ethanteague commented
> @ethanteague , please check updated spec in #2872 . Also, agreed w/ @swirtSJW "Add topics" should read "Add categories"

Thanks, @oksana-c & @swirtSJW  :+1: - will update

2020-09-17 14:47 UTC, ethanteague commented
@oksana-c @swirtSJW hoping we can break out the no repeats allowed in Entity browser requirement into a separate task. I tried a bunch of patches, and none fit the bill. I tried some manual tinkering to determine LOE, and didn't get very far. All of this is to say that the duplicate prevention thing is gonna take a while, and hoping we can get this task over the finish line without having to address.

2020-09-21 11:52 UTC, oksana-c requested changes

2020-09-21 11:52 UTC, oksana-c commented on config/sync/entity_browser.browser.topics.yml
> +name: topics
`name: topics`  > `name: categories`

also, the name of this config file contains "topics" and should be updated to match new term

2020-09-21 11:52 UTC, oksana-c commented on config/sync/core.entity_form_display.node.checklist.default.yml
> +    - entity_browser.browser.topics
`browser.topics`  will change for each field dependency once the browser is renamed

2020-09-21 11:52 UTC, oksana-c commented on config/sync/core.entity_form_display.node.checklist.default.yml
> +    - field.field.node.checklist.field_lc_primary_category
I'll be a bearer of dreary news this morning... unfortunately.
Last Friday we learned that the Learning Center may in fact not be called Learning Center anymore. One potential name is "Support & Resources". That being said, it's fine for us to keep field Labels as is for now containing "Learning Center", but it's best to keep any machine names without specific `lc` prefix. 
Let's change all these fields to `field_primary_category` and `field_other_categories`. 
Sorry for all these change requests @ethanteague

2020-09-21 11:52 UTC, oksana-c commented on config/sync/core.entity_form_display.node.checklist.default.yml
> +    group_learning_center_categories:
per comment above `group_learning_center_categories` > `group_categories`

2020-09-21 11:54 UTC, oksana-c commented
in regards to preventing duplicates in "Other categories" field - I'll open a follow up story. @kaise-lafrai is adding a contrib for duplicate validation in #2941 . Once that one is merged, we'll be able to add duplicate constraint to "other categories" field separately. Thanks @ethanteague

2020-09-21 13:52 UTC, ethanteague commented on config/sync/core.entity_form_display.node.checklist.default.yml
> +    - field.field.node.checklist.field_lc_primary_category
Np a'tall, @oksana-c - easy to change.

2020-09-21 21:40 UTC, oksana-c commented
@ethanteague , thanks for refactoring the fields. I reviewed and made some tweaks to field widgets. Also, added new fields to a new content type that was merged today "Learning Center Detail Page".
Updated all tests as well.

This branch is not building in Devshop .. when you see this, please pull the updates locally and open a new PR w/ all this work so we can verify tests pass in the morning and deploy tomorrow afternoon. Thanks so much!

2020-09-22 12:12 UTC, ethanteague commented
> @ethanteague , thanks for refactoring the fields. I reviewed and made some tweaks to field widgets. Also, added new fields to a new content type that was merged today "Learning Center Detail Page".
> Updated all tests as well.
> 
> This branch is not building in Devshop .. when you see this, please pull the updates locally and open a new PR w/ all this work so we can verify tests pass in the morning and deploy tomorrow afternoon. Thanks so much!

Pulled this down, and trying to rebase off of master with your commits is creating a bunch of conflicts that are going to be difficult to resolve, @oksana-c . Wondering if this is the reason for the build failure?

2020-09-22 14:49 UTC, oksana-c commented
closing in favor of #2963

2020-09-22 14:49 UTC, closed without merging