WIP: VACMS 2794 need more help
department-of-veterans-affairs/va.gov-cms pull request #2935
Opened 2020-09-16 21:12 UTC by kaise-lafrai

## Description

See _issueid_. 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-09-16 21:17 UTC, kaise-lafrai commented on docroot/themes/custom/vagovadmin/templates/node--landing-page--support-services-listing.html.twig
> +</article>
Add new line

2020-09-16 21:17 UTC, kaise-lafrai commented on docroot/themes/custom/vagovadmin/templates/node--support-service--support-services-listing.html.twig
> +</article>
Add new line

2020-09-22 19:08 UTC, kaise-lafrai commented
@oksana-c This is ready for review.

2020-09-22 19:45 UTC, swirtSJW requested changes
Some assorted questions and suggestions.

2020-09-22 19:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $benefit_hub = $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'];
Moderate: There is a bit of risk here since getValue can return NULL.  I suggest being defensive and make sure getValue gives us an array before digging blindly into an array  structure that may not exist.

2020-09-22 19:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  ];
Are there content types that might contain  `field_contact_information`  but we don't want the validation to run?  If so, then disregard.

Otherwise, 
Moderate:  I'd like to see this be a bit more dynamic and just look to see if `field_contact_information` rather than use a hard coded list.

2020-09-22 19:45 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_bundles.feature
> +| Contact information | contact_information | Paragraph type |  |
Bad alpha sort?

2020-09-22 19:45 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_content_type_fields.feature
> +| Content type | Checklist | Need more help? | field_contact_information | Entity reference revisions |  | 1 | Paragraphs Classic | Translatable |
Bad alpha sort?

2020-09-22 19:45 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_content_type_fields.feature
> +| Content type | FAQ - multiple Q&As | Need more help? | field_contact_information | Entity reference revisions |  | 1 | Paragraphs Classic | Translatable |
Bad alpha sort?

2020-09-22 19:45 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_content_type_fields.feature
> +| Content type | Media list - Images | Need more help? | field_contact_information | Entity reference revisions |  | 1 | Paragraphs Classic | Translatable |
bad alpha

2020-09-22 19:45 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_content_type_fields.feature
> +| Content type | Media list - Videos | Need more help? | field_contact_information | Entity reference revisions |  | 1 | Paragraphs Classic | Translatable |
Bad alpha

2020-09-22 20:07 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  ];
@swirtSJW I believe this is only being used on Learn Center content types. @oksana-c Could you confirm this?

2020-09-22 20:08 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  ];
@swirtSJW Otherwise it does make sense to make it more dynamic if we plan on using this elsewhere.

2020-09-23 19:24 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $benefit_hub = $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'];
@swirtSJW Would something like this be okay:

```
  if ($form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'] && $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts']) {
    $contact_type = $form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'];
    $benefit_hub = $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'];
    $benefit_hub_contact = array_shift($benefit_hub);
  }
```

2020-09-23 20:02 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  ];
Going to resolve this by doing this instead:

if (isset($form['field_contact_information'])) {
  $form['#validate'][] = '_va_gov_backend_contact_information_validation';
}

2020-09-24 01:25 UTC, closed without merging

2020-09-24 01:25 UTC, kaise-lafrai commented
@swirtSJW @oksana-c This merge request is being closed and picked back up here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2986