VACMS-2756 metatag entity paths B
department-of-veterans-affairs/va.gov-cms pull request #2971
Opened 2020-09-22 19:57 UTC by swirtSJW

## Description

See _issueid_. 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-09-22 19:59 UTC, swirtSJW commented
This is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2826 which broke devshop

2020-09-23 15:08 UTC, ElijahLynn commented
This has been deployed to https://test.dev.cms.va.gov/ (INTERNAL) for testing.

2020-09-23 16:26 UTC, ElijahLynn commented on docroot/sites/default/settings.php
> +if (PHP_SAPI === 'cli') {
I think this block needs a "why" comment.

2020-09-23 16:27 UTC, ElijahLynn commented on docroot/sites/default/settings.php
> +  $webhost = "{$_SERVER['REQUEST_SCHEME']}://{$_SERVER['HTTP_HOST']}";
The Jenkins host requests e.g. `internal-dsva-vagov-dev-cms-test-1790117836.us-gov-west-1.elb.amazonaws.com` so this will be that right?

2020-09-23 16:46 UTC, ElijahLynn commented on docroot/sites/default/settings.php
> + $settings['file_public_base_url'] = "{$webhost}/sites/default/files";
Remove leading space.
```suggestion
$settings['file_public_base_url'] = "{$webhost}/sites/default/files";
```

2020-09-23 16:50 UTC, ElijahLynn commented on docroot/sites/default/settings.php
> +if (PHP_SAPI === 'cli') {
```suggestion
// Because Jenkins can't resolve e.g. prod.cms.va.gov DNS, and only the internal*elb addresses.
// And some times the host would return data with "http://default/..." hostnames for files
// so we set the host here and pass it to the `file_public_base_url` setting to fix that. 
if (PHP_SAPI === 'cli') {
```

2020-09-23 17:10 UTC, swirtSJW commented on docroot/sites/default/settings.php
> +  $webhost = "{$_SERVER['REQUEST_SCHEME']}://{$_SERVER['HTTP_HOST']}";
That's right.   And this was just tested to work correctly thank you.

2020-09-23 17:16 UTC, swirtSJW commented on docroot/sites/default/settings.php
> +if (PHP_SAPI === 'cli') {
Added

2020-09-23 17:16 UTC, swirtSJW commented on docroot/sites/default/settings.php
> +if (PHP_SAPI === 'cli') {
This was added

2020-09-23 17:21 UTC, ElijahLynn requested changes

2020-09-23 17:21 UTC, ElijahLynn commented on docroot/sites/default/settings/settings.lando.php
> +$webhost_on_cliq = 'http://va-gov-cms.lndo.site';
```suggestion
$webhost_on_cli = 'http://va-gov-cms.lndo.site';
```

2020-09-23 17:21 UTC, ElijahLynn commented on docroot/sites/default/settings.php
> +  //This is running from a web request.
```suggestion
  // This is running from a web request.
```

2020-09-23 17:35 UTC, ElijahLynn approved these changes

2020-09-23 18:14 UTC, merged