Vacms 2794 need more help component
department-of-veterans-affairs/va.gov-cms pull request #2986
Opened 2020-09-24 01:25 UTC by kaise-lafrai

## Description

See _issueid_. 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-09-24 15:20 UTC, swirtSJW requested changes
Just one issue.

2020-09-24 15:20 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'] && $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'])
Moderate: I think this will still throw a php notice if it is not there.  The only safe way to check if something is there, is to wrap it in either !empty  or isset

Throws notice: `if ($form_state->getValue('field_contact_information')[0]['subform']['something_not here']){ `
Throws nothing: `if (!empty($form_state->getValue('field_contact_information')[0]['subform']['something_not here']){ `

However I think it is even more than that.   Because `$form_state->getValue('field_contact_information')` is a function that can return NULL  So then we don't have a missing element in an array, we have a non thing.

NULL:[0]['subform']['field_contact_info_switch']   which throws different kind of notice.  So I think you want an inital check for `if (!empty($form_state->getValue('field_contact_information')) && <the rest of your !empty checks for the things you are reaching for.>)

2020-09-24 16:29 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'] && $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'])
Thank you @swirtSJW. I will remedy this.

2020-09-24 18:19 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'] && $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'])
@swirtSJW 

How about this:

`  if ((!empty($form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'])) && (!empty($form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts']))) {
    $contact_type = $form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'];
    $benefit_hub = $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'];
    $benefit_hub_contact = array_shift($benefit_hub);
  }`

2020-09-24 18:26 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'] && $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'])
Or would it be better to do this:

  if ((!empty($form_state->getValue('field_contact_information'))) && (!empty($form_state->getValue('field_contact_information')))) {
Do Something...
  }

2020-09-24 18:47 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'] && $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'])
The first doesn't account for the NULl.  The second, only accounts for the NULL.  I think you want something like this
```
if (
  !empty($form_state->getValue('field_contact_information'))  &&
 !empty($form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch']) && !empty($form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'])) {
Do Something...
  }
```
That way you are checking before you dig, and then checking the exact target.

2020-09-24 20:55 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($form_state->getValue('field_contact_information')[0]['subform']['field_contact_info_switch'] && $form_state->getValue('field_contact_information')[0]['subform']['field_benefit_hub_contacts'])
Thank you. New push has latest changes.

2020-09-25 13:43 UTC, swirtSJW approved these changes
Nice work Kaise.

2020-09-25 13:43 UTC, merged