VACMS-2975: Improve url aliases and node titles for health services
department-of-veterans-affairs/va.gov-cms pull request #2994
Opened 2020-09-24 21:22 UTC by acrollet

## Description

See #2975.

## Testing done

Added phpunit test and ran locally.

## Screenshots

## QA steps

Verify that Facility/System Health Service node paths are correct after the database update has been completed.

- [ ] Facility Health Service node paths
- [ ] System Health Service node paths

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-09-25 15:13 UTC, swirtSJW requested changes
Nice work @acrollet.   Just one request. see in comments.

2020-09-25 15:13 UTC, swirtSJW commented on tests/phpunit/AliasesTest.php
> +
This looks great @acrollet.  Thank you for being thoughtful enough to add the test.   Just one request, can you delete these created nodes at the end of the test?   Right now all the front end dev and staging builds point to prod for their data, but we may go back to pointing them to staging, and if we did that, having test content remain published.  Behat tests remove what they create, but phpUnit tests don't.

2020-09-25 15:16 UTC, acrollet commented on tests/phpunit/AliasesTest.php
> +
@swirtSJW thanks for the review - when I was running the test locally the nodes were deleted, but I'll go ahead and explicitly delete them :-)

2020-09-25 15:27 UTC, acrollet commented on tests/phpunit/AliasesTest.php
> +
@swirtSJW as I look more, the documentation for ExistingSiteBase and the traits it's using is explicit that users, terms and nodes should be deleted at the end of the method. The one fly in the ointment is that if the test run fails mid-stream, any created entities would not be cleaned up. (This would also be true for manual deletion) I don't usually like relying on DB state for tests, but would it actually be better to test against existing content?

2020-09-25 16:15 UTC, swirtSJW commented on tests/phpunit/AliasesTest.php
> +
Interesting find.  If they were actually deleted, I am not worried about them persisting if the tests fail.   That is not as critical.   Does make me wonder why some of our others are not being deleted.   I'll have to look into it.

2020-09-25 16:52 UTC, acrollet commented on tests/phpunit/AliasesTest.php
> +
@swirtSJW good deal, just let me know if any changes are still needed?

2020-09-25 17:29 UTC, swirtSJW commented
Pausing on this as I am not sure this is the pattern we want
`va-eastern-colorado-health-care/system-health-services/recreation-and-creative-arts-therapy-at-va`

https://dsva.slack.com/archives/CT4GZBM8F/p1601053222076700

2020-09-25 17:47 UTC, swirtSJW commented
@acrollet when you have a chance can you updated these two QA steps to  be more specific?  What path should I go to, what should I expect to see?
```
- [ ] Facility Health Service node paths

 - [ ]  System Health Service node paths
```

2020-09-25 18:31 UTC, acrollet commented
@swirtSJW I've updated the QA steps.

2020-09-28 12:18 UTC, kevwalsh commented
> Pausing on this as I am not sure this is the pattern we want
> `va-eastern-colorado-health-care/system-health-services/recreation-and-creative-arts-therapy-at-va`
> 
> https://dsva.slack.com/archives/CT4GZBM8F/p1601053222076700

This looks like the old pattern that we are trying to move away from. perhaps the update hook was not successful? 

OLD pattern: '[node:field_administration:entity:name]/system-health-services/[node:title]'

NEW pattern: '[node:field_region_page:entity:url:path]/health-services/[node:title]'

`eastern-colorado-health-care/health-services/recreation-and-creative-arts-therapy-at-va-eastern-colorado-health-care` (if truncated a bit). 

There is a bit of repetition in there, but i think that's OK for now. These are not front end URLs, and there is some  minor concern about duplication without the duplicative `-at-va-eastern-colorado-health-care` at the end.

2020-09-28 14:45 UTC, acrollet commented
This is the URL I have for that node locally: ```/eastern-colorado-health-care/health-services/recreation-and-creative-arts-therapy-at-va-eastern```

@swirtSJW It appears that perhaps the update did not run successfully on your environment? It would be a bit chatty but I could perhaps add a log entry per node giving the alias before and after the node save?

2020-09-28 15:17 UTC, swirtSJW commented
> This is the URL I have for that node locally: `/eastern-colorado-health-care/health-services/recreation-and-creative-arts-therapy-at-va-eastern`
> 
> @swirtSJW It appears that perhaps the update did not run successfully on your environment? It would be a bit chatty but I could perhaps add a log entry per node giving the alias before and after the node save?

It did run them... that's where the screen capture in the QA steps came from.   It is possible we got a weird stay where devshop ran another build after I checked the hook_update ran., so that when I checked titles, they had not been updated yet.   I will check again on this recent build.

2020-09-28 17:00 UTC, swirtSJW commented
@acrollet It looks like either the pattern is not sticking... or the existing nodes are being saved but the path is not getting updated.
![image](https://user-images.githubusercontent.com/5752113/94463096-7251a500-018a-11eb-9de6-fe2ecf430791.png)
and I confirmed that node 7580 was updated in the hook_update
http://pr2994.ci.cms.va.gov/admin/reports/dblog/event/76

2020-09-28 17:01 UTC, acrollet commented
@swirtSJW ok, I'll pull an updated DB and try to repro locally.

2020-09-28 17:29 UTC, acrollet commented
I've updated this PR to remove the DB update so that another PR can operate with the updated config. (As discussed [on Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1601053222076700))

2020-09-28 18:06 UTC, swirtSJW approved these changes

2020-09-28 18:06 UTC, merged