VACMS-2504-2825-2967-2978 ET & KEV services work
department-of-veterans-affairs/va.gov-cms pull request #2998
Opened 2020-09-25 13:20 UTC by ethanteague

## Description
See #2504  #2825 #2967 #2978 

## Testing done
Visual / Behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/94271853-390e0080-ff10-11ea-8485-a0e57f4b8469.png)
![image](https://user-images.githubusercontent.com/2404547/94271860-3d3a1e00-ff10-11ea-968f-ef0deeb74737.png)
![image](https://user-images.githubusercontent.com/2404547/94271870-41663b80-ff10-11ea-8746-3c76f77bf1f8.png)

## QA steps
@kevwalsh to give this work the nod of approval (plz).

2020-09-28 02:41 UTC, swirtSJW requested changes
One question and some data issues.

2020-09-28 02:41 UTC, swirtSJW commented on config/sync/field.field.node.health_care_local_health_service.field_body.yml
> +  allowed_formats:
Confimring... we are taking away these options....what is going to happen to existing data?

2020-09-28 02:41 UTC, swirtSJW commented on config/sync/field.storage.node.field_online_scheduling_availabl.yml
> +      value: '2'
I don't think we whe should be using a numerical key here that will be meaningless when it hits the frontend. 0 and 1 are good keys for booleans, but 2 is a bad key for 'Not applicable'

2020-09-28 02:41 UTC, swirtSJW commented on config/sync/field.storage.node.field_referral_required.yml
> +      value: '2'
non-translatable key

2020-09-28 02:41 UTC, swirtSJW commented on config/sync/field.storage.node.field_walk_ins_accepted.yml
> +      value: '2'
non-translatable key

2020-09-28 02:41 UTC, swirtSJW commented on config/sync/field.storage.paragraph.field_hours.yml
> +      label: 'Use the general facility hours'
Should be a bool value 1, not 0, this is misleading  or non-translatable data.

2020-09-28 02:41 UTC, swirtSJW commented on config/sync/field.storage.paragraph.field_hours.yml
> +      value: '1'
SHould be a bool value 0

2020-09-28 11:11 UTC, ethanteague commented
> One question and some data issues.

Apologies, @swirtSJW ....... I don't know the answer. Looping in @kevwalsh to weigh in.

2020-09-28 12:01 UTC, kevwalsh commented on config/sync/field.storage.node.field_online_scheduling_availabl.yml
> +      value: '2'
not sure what we should do here. 
ideally, we would nuke the field and recreate with semantic keys for all values. 
we have some existing data in these fields for Pittsburgh, but not a lot, and it could be reentered manually.

2020-09-28 13:34 UTC, swirtSJW commented on config/sync/field.storage.node.field_online_scheduling_availabl.yml
> +      value: '2'
The fields were correct... this change is what flipped them.  0 was no.   1 was yes.   Except for on the hours field where the nature of the question reversed.

2020-09-28 16:56 UTC, kevwalsh approved these changes

2020-09-28 17:01 UTC, swirtSJW commented on config/sync/field.field.node.health_care_local_health_service.field_body.yml
> +  allowed_formats:
Good example of confusing bools ;)

2020-09-28 18:36 UTC, kevwalsh commented
Ooops... i'll fix this conflict ^

2020-09-29 13:40 UTC, swirtSJW requested changes
Just need to re-key the `2` to `not_applicable`

2020-09-29 13:40 UTC, swirtSJW commented on config/sync/field.storage.node.field_online_scheduling_availabl.yml
> +      value: '2'
@ethanteague  this should not be value 2 anymore right?  should be value `not_applcable`?

2020-09-29 13:40 UTC, swirtSJW commented on config/sync/field.storage.node.field_referral_required.yml
> +      value: '2'
Should be `not_applicable`

2020-09-29 13:40 UTC, swirtSJW commented on config/sync/field.storage.node.field_walk_ins_accepted.yml
> +      value: '2'
`not_applicable`

2020-09-29 13:40 UTC, swirtSJW commented on config/sync/field.storage.paragraph.field_hours.yml
> +      label: 'Use the general facility hours'
Leave this as is. Kev created a followup ticket.

2020-09-29 13:40 UTC, swirtSJW commented on config/sync/field.storage.paragraph.field_hours.yml
> +      value: '1'
Leave this as is for catching later in follow-up ticket.

2020-09-29 17:14 UTC, swirtSJW commented on config/sync/field.storage.paragraph.field_hours.yml
> +      value: '1'
This leaves two items with the same label for two different values.

2020-09-29 17:15 UTC, swirtSJW commented on config/sync/field.field.paragraph.service_location.field_hours.yml
> +label: 'Do not specify hours'
This label change does not seem right for the field.

2020-09-29 17:48 UTC, ethanteague commented on config/sync/field.field.paragraph.service_location.field_hours.yml
> +label: 'Do not specify hours'
Changing back to `Use the facility''s hours`

2020-09-29 17:49 UTC, ethanteague commented on config/sync/field.storage.paragraph.field_hours.yml
> +      value: '1'
Changing value 1 to `Do not specify hours`

2020-09-29 18:06 UTC, swirtSJW commented on config/sync/field.field.paragraph.service_location.field_hours.yml
> -label: Hours
Is this right?

2020-09-29 18:09 UTC, ethanteague commented on config/sync/field.field.paragraph.service_location.field_hours.yml
> -label: Hours
Apologies, I don't know. Deferring to @kevwalsh

2020-09-29 18:09 UTC, kevwalsh commented on config/sync/field.field.paragraph.service_location.field_hours.yml
> -label: Hours
Yes, it has been changed to  'Use the facility''s hours'

2020-09-29 18:09 UTC, swirtSJW commented on config/sync/field.field.paragraph.service_location.field_hours.yml
> -label: Hours
This seems odd that the label matches one of the possible settings.

2020-09-29 18:13 UTC, kevwalsh commented on config/sync/field.field.paragraph.service_location.field_hours.yml
> -label: Hours
I hear that, this was the design that Rachel and i collaborated on. It may not be perfect... but it's better than just "Hours", which duplicates the fieldset. 
![Create_VAMC_Facility_Health_Service___VA_gov_CMS](https://user-images.githubusercontent.com/643678/94599064-e5781b80-025d-11eb-9349-710304588bca.jpg)

2020-09-29 18:24 UTC, swirtSJW commented on config/sync/field.field.paragraph.service_location.field_hours.yml
> -label: Hours
Ok cool.

2020-09-29 18:24 UTC, swirtSJW approved these changes

2020-09-29 18:34 UTC, merged