VACMS-2975 (2): Re-save health services nodes to update titles/DB aliases
department-of-veterans-affairs/va.gov-cms pull request #3012
Opened 2020-09-28 17:31 UTC by acrollet

## Description

NB: This should not be merged until https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2994 has been merged and is live.

See #2975.

## Testing done

Tested DB update locally.

## Screenshots

## QA steps

Verify that Facility/System Health Service node paths are correct after the database update has been completed.

- Go to the content listing, filter by Content Type: VAMC Facility Health Service, visit a few representative pages:
  - [ ] Validate that paths match the pattern "{Parent Facility node URL}/{Regional health service name & description}"
- Go to the content listing, filter by Content Type: VAMC System Health Service, visit a few representative pages:
  - [ ] Validate that paths match the pattern "{Parent Region node URL}/health-services/{node title}"
- [ ] validate that the hook_update_n completed 
![image](https://user-images.githubusercontent.com/5752113/94292422-f0b00c00-ff2a-11ea-8fab-c164723ed0cd.png)
- [ ] validate that  ~1400 nodes were updated via the hook_update_n
- [ ] Validate that updated nodes have proper revision message 
![image](https://user-images.githubusercontent.com/5752113/94292955-a5e2c400-ff2b-11ea-860c-468804143e4b.png)

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-09-28 18:07 UTC, swirtSJW commented
Holding on this one until after todays merge of part 1 lands on prod.

2020-09-28 20:15 UTC, indytechcook commented on docroot/modules/custom/va_gov_db/va_gov_db.install
> +function va_gov_db_update_8019(&$sandbox) {
Can we switch to `hook_post_update_NAME` https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_post_update_NAME/8.8.x

2020-09-28 20:17 UTC, indytechcook commented on docroot/modules/custom/va_gov_db/va_gov_db.install
> +    $node = Node::load($nid);
The performance will be much better the nodes are bulk loaded

2020-09-28 20:18 UTC, indytechcook commented on docroot/modules/custom/va_gov_db/va_gov_db.install
> +    $node = Node::load($nid);
Using `array_splice` or something to the the nids to load load.

2020-09-28 23:23 UTC, acrollet commented
@indytechcook ready for re-review.

2020-09-29 12:25 UTC, indytechcook submitted a review, later dismissed

2020-09-29 12:25 UTC, indytechcook commented
Looks Great!!

2020-09-29 13:33 UTC, swirtSJW commented
This is still on hold as yesterday's merge of part 1  did not go out due not passing tests on staging. (not part 1's fault)

2020-09-29 13:35 UTC, swirtSJW approved these changes

2020-09-30 15:37 UTC, swirtSJW commented
This is cleared for merge as soon as tests pass.

2020-09-30 17:06 UTC, swirtSJW commented
@acrollet Looks like we may have an issue with this.  
![image](https://user-images.githubusercontent.com/5752113/94716908-9396ca80-031d-11eb-9110-e4c4fd40acfa.png)

2020-09-30 17:06 UTC, swirtSJW requested changes
Titles seem to be failing.

2020-09-30 17:08 UTC, swirtSJW commented
Editing and saving one of the nodes with an empty title causes the title to be set correctly, so it is related to the atomated save.

2020-09-30 17:13 UTC, acrollet commented
pulling a new db and attempting to repro...

2020-09-30 19:22 UTC, acrollet commented
@swirtSJW After investigating, I at least have a workaround - changing the automatic label pattern from '[node:field_regional_health_service] - [node:field_facility_location]' to '[node:field_regional_health_service:entity:title] - [node:field_facility_location:entity:title]' lets the tokens be correctly replaced. We have a couple of options for dealing with this:

1. Update the auto-label patterns to explicitly specify the information we're pulling from the entity reference fields as above. This has the advantage of being clear about what data from the referenced entity is desired.  Unfortunately, I think this would take yet another deploy since the DB updates run before config import.
2. Attempt to repro this behavior in a d8 sandbox and raise an issue with a patch in the token module queue. (This is somewhat risky time-wise as it's not unknown whether this behavior can easily be reproduced with a base case or is due to interactions with contrib modules on the VA site) I did try adding a specific display mode for tokens, but that did not resolve the issue with pre-save.

2020-10-01 15:56 UTC, swirtSJW commented
@acrollet  We should do it right and update the pattern to make it more specific.  We deploy every day, so not a big deal to lose another day.

2020-10-01 15:57 UTC, acrollet commented
@swirtSJW sounds good, should we create a follow-on to look for and address this pattern elsewhere?

2020-10-01 20:53 UTC, acrollet commented
This will probably need to be re-rolled after #3087 goes live, assigning myself.

2020-10-06 21:24 UTC, swirtSJW commented
@kevwalsh The paths look right now, but the titles seem cumbersome.
Can you confirm that the titles are as they should be?
![image](https://user-images.githubusercontent.com/5752113/95261576-a0715d80-07f8-11eb-8a30-ecf1f1795250.png)

Is a facility service title supposed to have have a title that redundantly includes the system name?
![image](https://user-images.githubusercontent.com/5752113/95261590-a9fac580-07f8-11eb-8fcd-2329939240c1.png)

2020-10-06 21:35 UTC, swirtSJW commented
It is like our concatenation of titles is cascading
![image](https://user-images.githubusercontent.com/5752113/95262526-4b364b80-07fa-11eb-86c7-69765f631f3b.png)

2020-10-07 12:10 UTC, kevwalsh commented
We don't need the system name at the facility level. The green box in the last screenshot looks good (could be a "-" or an "at", i don't think it matters.)

eg 
Mental health care at Abie Abraham VA Clinic
or 
Mental health care - Abie Abraham VA Clinic

2020-10-07 14:04 UTC, swirtSJW commented
> We don't need the system name at the facility level. The green box in the last screenshot looks good (could be a "-" or an "at", i don't think it matters.)
> 
> eg
> Mental health care at Abie Abraham VA Clinic
> or
> Mental health care - Abie Abraham VA Clinic

The problem is, the system name is now part of the service name.  The service name does not exist by itself anymore.

2020-10-07 14:05 UTC, kevwalsh commented
We can still get to it, via a token, going through the VAMC system health service entity reference, then to the taxonomy term.

2020-10-09 14:47 UTC, acrollet commented
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3154

2020-10-09 14:57 UTC, swirtSJW approved these changes
Looked at the results on devshop and the titles and paths look good.

2020-10-09 14:58 UTC, merged