VACMS-2547,2972: [LC] update metatag config
department-of-veterans-affairs/va.gov-cms pull request #3085
Opened 2020-10-01 20:17 UTC by acrollet

## Description

See #2547, #2972

## Testing done

Added & ran behat tests, manually verified updated config on new db after db update.

## Screenshots

## QA steps

As an admin user,
- [ ] Verify that metatag fieldgroup, title and description are no longer present on the LC content types.
- [ ] Verify that the metatag title is correctly generated for LC content type pages

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-10-05 14:50 UTC, swirtSJW requested changes
Nice work @acrollet Just a couple small changes.

2020-10-05 14:50 UTC, swirtSJW commented on tests/behat/features/lc_metatags.feature
> +    | Test Detail Page          |       1 |
These are great tests. Thanks for adding them.
Can we make them 100% unique to this test though?  The examples are remarkably close to what editors come up with as their own test content on prod
 
![image](https://user-images.githubusercontent.com/5752113/95094498-f90d0180-06f7-11eb-8d3a-ec882add6aa4.png)


I want to make sure our tests don't fail because they collide with a human.

Lets add "- BeHaT"  to the end of them, so we know where they came from and to differentiate them from any editors making test content.

2020-10-06 14:37 UTC, acrollet commented on docroot/modules/custom/va_gov_backend/va_gov_backend.install
> +  }
got it, thanks for the background 👍

2020-10-06 14:38 UTC, acrollet commented
@swirtSJW feedback addressed, fixing the conflicts is pending 16th minute discussion today.

2020-10-07 15:25 UTC, acrollet commented
The spec tool tests also need to be updated, working on that now.

2020-10-07 16:04 UTC, acrollet commented
@swirtSJW ready for re-review pending tests

2020-10-08 17:40 UTC, swirtSJW commented
@acrollet Can you resolve the composer lock conflict?

2020-10-09 19:53 UTC, swirtSJW commented
Test on this one should start passing when I merge https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3160

2020-10-13 14:53 UTC, acrollet commented
@swirtSJW I just touched base with @kaise-lafrai and will be updating the spec tool test shortly.

2020-10-13 22:39 UTC, acrollet commented
@swirtSJW tests are now passing with va-gov/web updated.

2020-10-14 15:59 UTC, oksana-c approved these changes

2020-10-14 16:00 UTC, oksana-c commented on composer.lock
> +            "version": "v0.1.1093",
👍

2020-10-14 16:01 UTC, oksana-c commented
@acrollet - green light to merge once tests pass 👍

2020-10-14 16:41 UTC, merged