VACMS 2704 QA Standalone Page Field
department-of-veterans-affairs/va.gov-cms pull request #3170
Opened 2020-10-13 20:31 UTC by kaise-lafrai

## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2704

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-10-14 19:11 UTC, oksana-c requested changes
@kaise-lafrai , the ACs are implemented in a bit of a reversed fashion here.

The logic should be: 
If the checkbox is checked, then the fieldset with standalone page fields is displayed.
If it's not checked, then the fieldset with standalone page fields is not displayed.

I know @acrollet offered to get this through the finish line, so tagging him here for visibility.

2020-10-14 19:27 UTC, acrollet commented
Looking at this now...

2020-10-14 22:51 UTC, acrollet commented
@oksana-c tests are passing and I've addressed the requirements and completed all QA steps.

2020-10-15 11:24 UTC, oksana-c commented
@acrollet, one more update needs to happen before this goes out - CTA buttons field is required, but doesn't throw an error on validation if button paragraph fields are empty.

The requirement for buttons in all R&S nodes is - at least one CTA button should be added per node, max - two buttons.

2020-10-15 14:15 UTC, acrollet commented
@oksana-c I assume this change should be made for all content types where field_buttons appears?

2020-10-15 14:21 UTC, oksana-c commented
@acrollet good point 👍 . Paragraph "Button" should have both fields Label and Link marked required. Then we'd need to add logic to prevent form errors for CTA buttons on Q&A content type if the "Enable standalone page" checkbox is not checked.

2020-10-15 14:22 UTC, acrollet commented
@oksana-c sounds good, thanks!

2020-10-15 16:29 UTC, acrollet commented
Pushed, I'll re-validate on the CI environment after the tests run.

2020-10-15 17:22 UTC, oksana-c requested changes

2020-10-15 17:22 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    }
if we remove this part, then we get the behavior, we're looking for.

2020-10-15 17:27 UTC, oksana-c commented
glitch in the last action taken. nm

2020-10-15 17:29 UTC, acrollet commented
@oksana-c I think you were right... Re-validating locally.

2020-10-15 17:36 UTC, acrollet commented
Local validation complete, will re-check on CI when ready.

2020-10-15 17:40 UTC, acrollet commented
Re-validated on http://pr3170.ci.cms.va.gov/

2020-10-15 17:55 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $form['field_buttons']['widget'][0]['subform']['field_button_link']['widget'][0]['uri']['#states']['required']['input[id="edit-field-standalone-page-value"]'] = ['checked' => TRUE];
`['widget'][0]` works only on the first instance of the paragraph. 
In the scenario where user removes the paragraph via "Remove" button and then adds another instance of the Button paragraph, the button fields are no longer required.

also, when the user removes the CTA paragraph and leaves the CTA field empty - a couple of notices are thrown on node save. see screenshot below

<img width="979" alt="Screen Shot 2020-10-15 at 11 54 12 AM" src="https://user-images.githubusercontent.com/16477724/96167902-44d05f80-0edd-11eb-87e4-c0eb2c452b84.png">

2020-10-15 17:57 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      $form['field_buttons']['widget'][0]['subform']['field_button_link']['widget'][0]['uri']['#required'] = TRUE;
same here - `['widget'][0]`  - index 0 only covers the first instance of a paragraph

2020-10-15 19:30 UTC, acrollet commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $form['field_buttons']['widget'][0]['subform']['field_button_link']['widget'][0]['uri']['#states']['required']['input[id="edit-field-standalone-page-value"]'] = ['checked' => TRUE];
@oksana-c after much hassling with #states + paragraphs + AJAX I've added a core patch which resolves these issues for me locally. (Along with improving the original logic)

2020-10-15 19:30 UTC, acrollet commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $form['field_buttons']['widget'][0]['subform']['field_button_link']['widget'][0]['uri']['#states']['required']['input[id="edit-field-standalone-page-value"]'] = ['checked' => TRUE];
I will re-validate on the CI environment after it's been rebuilt.

2020-10-15 20:22 UTC, acrollet commented
The CI environment behavior is not matching my local, investigating...

2020-10-15 20:23 UTC, acrollet commented
Belay that, drupal + browser cache clears fixed it.

2020-10-15 20:27 UTC, acrollet commented
@oksana-c I've successfully re-validated all QA steps on the CI environment. Please ensure you clear browser cache before testing removing/adding CTA buttons :-)

Also, here's a link to the issue for the new core patch: https://www.drupal.org/node/1091852

2020-10-15 20:59 UTC, oksana-c approved these changes
looks great 👍 thank you @acrollet !

2020-10-15 21:07 UTC, merged