VACMS 2912: Force editors to save first as draft or in review, then publish on the proofing pages.
department-of-veterans-affairs/va.gov-cms pull request #3207
Opened 2020-10-19 20:11 UTC by ndouglas

## Description

See #2912.

I'm fairly new to this process, so any omissions/failures/errors/etc are unintentional.

## Testing done
Created and ran a Behat test.

## Screenshots

Edit Form:
<img width="269" alt="Screen Shot 2020-10-19 at 3 00 23 PM" src="https://user-images.githubusercontent.com/1318579/96505590-f643fd80-121b-11eb-9133-d5a67419ada9.png">

Proofing (Such As Is):
<img width="514" alt="Screen Shot 2020-10-19 at 3 00 48 PM" src="https://user-images.githubusercontent.com/1318579/96505593-f6dc9400-121b-11eb-824f-983a5d4b5980.png">

## QA steps
As user with permission to create a node of a type with moderation enabled, e.g. `press_release`.
1. Open a form to create a new node of that type.
2. Confirm that "Published" is not an option for the Moderation State widget.
3. Save the node as a draft or for review.
4. Confirm that "Published" is now an option for the Moderation State widget.

## Definition of Done
- [ ] Release notes are forthcoming.

2020-10-19 21:00 UTC, acrollet commented on tests/behat/features/content_editing.feature
> +    And I should not see "Published" in the "#edit-moderation-state-0-state" element
@ndouglas nice work, thanks for adding the test! It would make sense to me for this test to run in a less privileged role, probably content admin. (I think I need to up my own game in that regard on a few existing tests...) It would also be nice to verify that we still see the "Published" option on the proofing page if there's not an existing test.

2020-10-19 21:06 UTC, ndouglas commented on tests/behat/features/content_editing.feature
> +    And I should not see "Published" in the "#edit-moderation-state-0-state" element
Sounds good.  I'll do both of those tomorrow.

2020-10-21 03:12 UTC, ndouglas commented
The tests in question pass locally but the command fails with an error akin to that in #2570, which @acrollet suggested was causing this issue.  I suspect that this might be the reason this test is failing in CI, since I'm not seeing an explicit error message associated with the test in the [Details](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/be68f5f2d0fcdf8ca0d91c75de2ef85c3745a3eb#commitcomment-43424888).  I'm not sure of the best course of action here or if I'm diagnosing the issue correctly.

2020-10-21 16:11 UTC, ndouglas commented
This change thoroughly breaks [this test](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/298818aae49ebe5a9060e7ceced37bae1356b77c/tests/behat/features/perms.feature#L66).  I'll restructure that slightly to incorporate this change.

2020-10-23 16:42 UTC, acrollet requested changes
Nice work! Just a couple of very minor comments :-)

2020-10-23 16:42 UTC, acrollet commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  // Remove "Published" from available moderation states.
trying to learn from @indytechcook here, should this be a "why" comment rather than a "what"?

2020-10-23 16:42 UTC, acrollet commented on tests/behat/Drupal/FeatureContext.php
>     * @Then the :element element should exist
nice semantic improvement here! Not sure if there's great wording available but should we also change to something like the following?

"@Then the :element-selector element should exist"

(I don't know off-hand if behat will choke on the hyphen or not)

2020-10-23 16:43 UTC, ndouglas commented on tests/behat/Drupal/FeatureContext.php
>     * @Then the :element element should exist
I can find out pretty easily 😎

2020-10-23 16:54 UTC, ndouglas commented on tests/behat/Drupal/FeatureContext.php
>     * @Then the :element element should exist
Yeah, it chokes, but `:selector` should work.

2020-10-23 17:03 UTC, acrollet approved these changes
![EGc8sVIXoAIvcf-](https://user-images.githubusercontent.com/101649/97032678-71105f80-151f-11eb-948a-3599c2af15ee.jpg)

2020-11-04 15:08 UTC, ndouglas commented on tests/behat/features/content_editing.feature
> +    # (Re-)Publish the node.
Hey @acrollet, I modified this test slightly to conform to the new behavior (not being able to publish directly from the node edit form).  Test passes and I think it makes sense, but I wanted to specifically call your attention to it in case I'm not thinking clearly this morning.  Which is a definite possibility.

2020-11-04 15:09 UTC, ndouglas commented on tests/behat/features/perms.feature
> +    And I select "Published" from "Change to"
I think you mentioned at some point that this test needed followthrough, i.e. I should confirm that the node can indeed be published from the proofing page.  That's the purpose of this addition.

2020-11-04 15:15 UTC, acrollet commented on tests/behat/features/content_editing.feature
> +    # (Re-)Publish the node.
I'm not sure I'm thinking any more clearly but it looks god!

2020-11-04 15:40 UTC, acrollet approved these changes
<img src="https://media0.giphy.com/media/Hw8vYF4DNRCKY/200.gif" />

2020-11-04 16:03 UTC, merged