VACMS-3132: Resources Support Role
department-of-veterans-affairs/va.gov-cms pull request #3216
Opened 2020-10-20 14:56 UTC by kaise-lafrai

## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3132

## Testing done

## Screenshots

## QA steps

Coming soon...

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-10-20 15:47 UTC, swirtSJW requested changes
Looks good so far Kaise.  I think we need to add a set of testing to tests/phpunit/SecurityRolesPermissionsTest.php to cover this new role.

2020-10-20 20:57 UTC, oksana-c commented
added one important item to definition of done to this PR. 
@kaise-lafrai you have sufficient access to follow-up w/ updating user roles on prod, so wanted to put that on your radar.

2020-10-22 15:07 UTC, kaise-lafrai commented
> added one important item to definition of done to this PR.
> @kaise-lafrai you have sufficient access to follow-up w/ updating user roles on prod, so wanted to put that on your radar.

Sounds good @oksana-c, I will be sure to give them those roles once this deploys.

2020-10-22 19:19 UTC, swirtSJW commented on tests/phpunit/SecurityRolesPermissionsTest.php
> -          'create support_resources_detail_page content',
@kaise-lafrai  When I requested a test be added for the new role.  What I meant was that we were removing these from the "content_editor" array.
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/c3ff0053944297a6e9f79a324df008cf7d39bafc/tests/phpunit/SecurityRolesPermissionsTest.php#L197-L334
  But we have not added an array to cover the perms of `content_creator_resources_and_support`

on trick to creating this is just add 

```
[
        'content_creator_resources_and_support',
        [
          'access administration pages',
 ],
      ],

```
Then run the test and it will tell you what should actually be in the array.

2020-10-22 19:42 UTC, kaise-lafrai commented on tests/phpunit/SecurityRolesPermissionsTest.php
> -          'create support_resources_detail_page content',
@swirtSJW I didn't create a new test for content_creator_resources_and_support because I didn't see one for (content creator - benefit hubs, content creator - VAMC) and thought we left it out for a reason. I will create a test for content_creator_resources_and_support now so this can move along since it's blocking 2706. Thank you.

2020-10-22 20:20 UTC, kaise-lafrai commented
@swirtSJW The latest commit adds securitpermissionsroles testing for the following roles: `'vamc_content_creator', 'content_creator_benefits_hubs', 'content_creator_resources_and_support'`

2020-10-22 20:34 UTC, kaise-lafrai commented
Testing steps updated.

2020-10-22 20:41 UTC, kaise-lafrai commented
@oksana-c Can you let me know exact usernames for the users who need role updates for Resources and Support. See below for the ACs to verify agains.

`Assign "content creator - Resources and support" role to the following users on production: Jen, Randi, Selina, Beth`

`Content Creator - Resources and support role is added to the following user accounts immediately after this PR is deployed: Laura.Walsh1@va.gov. Other users that should be creating R&S content: beth.potts@va.gov, selina.cooper@va.gov,, but they don't need the role, since "Content admin" permissions allow them to create content of any type. tagging @kevwalsh for awareness.`

2020-10-23 00:37 UTC, oksana-c commented
@kaise-lafrai , list of users to assign new role: Laura.Walsh1@va.gov, beth.potts@va.gov, selina.cooper@va.gov, Randi.Hecht@va.gov, Jennifer.Lee27@va.gov

some of these account have content admin roles, which gives them access without having a new roles assigned. In the future though, we may be reconsider the role of content admin, so let's go ahead and assign this new role to all listed above.

2020-10-23 14:13 UTC, swirtSJW approved these changes
Nice work Kaise.

2020-10-23 14:13 UTC, merged