[DO NOT MERGE PRIOR TO PR 3204 PROD RELEASE] VACMS-3197 aliases part b
department-of-veterans-affairs/va.gov-cms pull request #3259
Opened 2020-10-22 10:00 UTC by ethanteague

## Description
See #3197 
This pr:
1. Forces LC content types to use the patterns created in pr 3204.
2. Makes the alias widget unavailable to non-admins after lc node is published.

## Testing done
Behat / visual

## QA steps
1. As an `administrator`,  visit `/node/8296/edit` and visually verify that Url alias widget field reads `/resources-and-support-for-your-va-benefits-and-services`
2. Publish node, then visit `/node/8296/edit` as a `content_editor` and visually verify that Url alias widget is not visible

2020-10-23 17:44 UTC, swirtSJW requested changes
A couple changes please.

2020-10-23 17:44 UTC, swirtSJW commented on scripts/content/VACMS-3197-bulk_update_lc_path_aliases-2020-10.php
> +    $updated = $updated + 1;
Minor:
```suggestion
    $updated++;
```

2020-10-23 17:44 UTC, swirtSJW commented on scripts/content/VACMS-3197-bulk_update_lc_path_aliases-2020-10.php
> +    $failed = $failed + 1;
Minor:
```suggestion
    $failed++;
```

2020-10-23 18:13 UTC, ethanteague commented on scripts/content/VACMS-3197-bulk_update_lc_path_aliases-2020-10.php
> +    $failed = $failed + 1;
Yeah, agreed - was copying stuff and not thinking much. Will update, @swirtSJW

2020-10-23 18:14 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
Yep - I got lazy. Will update, @swirtSJW :+1:

2020-10-26 14:04 UTC, swirtSJW reviewed
I understand this takes care of hiding the field if it is published.  Is there are part C that contains:

 1. the entity_update hook that  unticks the checkbox when it is changed from draft to published.  
2. script to change tick the box on all currently published nodes.

2020-10-26 17:51 UTC, ethanteague commented
> I understand this takes care of hiding the field if it is published. Is there are part C that contains:
> 
> 1. the entity_update hook that  unticks the checkbox when it is changed from draft to published.
> 2. script to change tick the box on all currently published nodes.

@swirtSJW @oksana-c I had a tough time digging into the widget to alter that checkbox. I was able to pretty easily just remove the whole widget after publish, so that's what I'm doing in this pr. So, the tick box logic isn't needed, because the box is unavailable after publish to non-admins (it returns if the node is set back to draft / review). Hoping you all are okay with this approach - I couldn't seem to dig into that checkbox :cry:

2020-10-26 17:59 UTC, swirtSJW commented
> So, the tick box logic isn't needed, because the box is unavailable after publish to non-admins (it returns if the node is set back to draft / review). Hoping you all are okay with this approach - I couldn't seem to dig into that checkbox

I think it is still needed.  I don't think hiding the tick box  preventz the node from still following the url pattern as a title changes.   We need it to actually remain with the current url indefinitely.

2020-10-26 22:02 UTC, ethanteague commented
> > So, the tick box logic isn't needed, because the box is unavailable after publish to non-admins (it returns if the node is set back to draft / review). Hoping you all are okay with this approach - I couldn't seem to dig into that checkbox
> 
> I think it is still needed. I don't think hiding the tick box prevents the node from still following the url pattern as a title changes. We need it to actually remain with the current url indefinitely.

Yeah, you are right. Updated, @swirtSJW :+1:

2020-10-27 18:20 UTC, swirtSJW commented
On testing this out @ethanteague  I see an issue.

If as an admin I publish a checklist, then edit the checklists title and save the node, I get this error

![image](https://user-images.githubusercontent.com/5752113/97344771-9bd02000-185f-11eb-8d41-f6bce78e3601.png)

2020-10-27 18:22 UTC, swirtSJW requested changes
Solve issue reported in comment related to node save error.

2020-10-28 12:05 UTC, ethanteague commented
> On testing this out @ethanteague I see an issue.
> 
> If as an admin I publish a checklist, then edit the checklists title and save the node, I get this error
> 
> ![image](https://user-images.githubusercontent.com/5752113/97344771-9bd02000-185f-11eb-8d41-f6bce78e3601.png)
> 
> The save never happens.

> On testing this out @ethanteague I see an issue.
> 
> If as an admin I publish a checklist, then edit the checklists title and save the node, I get this error
> 
> ![image](https://user-images.githubusercontent.com/5752113/97344771-9bd02000-185f-11eb-8d41-f6bce78e3601.png)
> 
> The save never happens.

Ugh....my bad! I just pushed a fix, @swirtSJW

2020-10-28 16:31 UTC, swirtSJW commented
@ethanteague  This is mainly working correctly, but has an issue.
If a node gets published the checkmark goes away as it should.   But then if an editor who can only edit and submit drafts for review, makes a title change and then submits for review, and then I as an admin looks at the draft to change it to published, the checkmark is again set.
![image](https://user-images.githubusercontent.com/5752113/97466159-2cb70200-1919-11eb-8c01-f59c3ebebed3.png)

When I publish the revision, the node gets and updated alias that should not have happened.
![image](https://user-images.githubusercontent.com/5752113/97466409-73a4f780-1919-11eb-81d2-22284588b4ab.png)

2020-10-28 16:35 UTC, swirtSJW requested changes
This is largely working, but has one flaw.   See error described in previous comment.

2020-10-28 16:35 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      if ($status === 'published') {
I think only having this look at published means the it does not untick the box when you are looking at  node that has been published but the current revision that you are looking at is in review or draft.   It has to look at node itself, not the revision.

2020-10-28 18:11 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      if ($status === 'published') {
Yep, that's the ticket, @swirtSJW - updated :+1:

2020-10-29 13:52 UTC, ethanteague commented
@swirtSJW - reworked this a bit. I've gotten rid of the js checkbox toggle approach, and replaced with an after_build function. I've also added a check in entity presave hook to turn off pathauto if the default revision is published. Hopefully this will cover us! Appreciate your eyes on this.

2020-10-29 14:39 UTC, swirtSJW requested changes
I added some suggestion.

2020-10-29 14:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    'step_by_step',
```suggestion
    'step_by_step',
    'va_form',
```

This feature was originally requested for VA Forms nodes.

2020-10-29 14:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> + * Return an array of R&S node types.
```suggestion
 * @return array 
 *   Node types that should have their alias locked upon publishing.
```

@return?     I think your codesniffer be stuffed up.

2020-10-29 14:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function _va_gov_backend_r_and_s_types() {
```suggestion
function _va_gov_backend_get_locked_alias_bundles() {
```

Functions should be verbs, and variables should be nouns. Also I think the name of this should be less product specific and more about what it represents. Something like "_va_gov_backend_get_locked_alias_bundles"

2020-10-29 14:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $bundles_with_hidden_alias_widget = _va_gov_backend_r_and_s_types();
```suggestion

```

2020-10-29 14:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    if (in_array($bundle, $bundles_with_hidden_alias_widget)) {
```suggestion
    if (in_array($bundle, _va_gov_backend_get_locked_alias_bundles())) {
```

2020-10-29 14:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($entity->getEntityTypeId() === 'node' && in_array($entity->bundle(), $r_and_s_types)) {
```suggestion
  if ($entity->getEntityTypeId() === 'node' && in_array($entity->bundle(), _va_gov_backend_get_locked_alias_bundles())) {
```

2020-10-29 14:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +
```suggestion
```

2020-10-29 14:50 UTC, ethanteague commented
> I added some suggestion.

Thanks @swirtSJW - added them.

2020-10-29 14:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> + *   return array $form.
```suggestion
 *   @return array 
  *   The $form.
```

code sniffer

2020-10-29 20:13 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +}
I don't think this is actually doing anything.   When I am content-editor I can never see the widget.   And when I am content-admin I can always see it, even though we are not hiding it based on role at all.

I am digging into this.

2020-10-31 01:31 UTC, swirtSJW approved these changes

2020-11-02 14:26 UTC, swirtSJW submitted a review, later dismissed

2020-11-02 14:31 UTC, swirtSJW commented
Testing conversation here just for history.
https://dsva.slack.com/archives/CT4GZBM8F/p1604065580014100

2020-11-02 15:03 UTC, swirtSJW approved these changes

2020-11-02 15:04 UTC, merged

2020-11-02 20:48 UTC, olivereri commented
```
bash-4.2$ source /etc/sysconfig/httpd; /usr/local/bin/drush scr ../scripts/content/VACMS-3197-bulk_update_lc_path_aliases-2020-10.php 
Skipped or failed updating alias for nid 9275 VACMS-3197-bulk_update_lc_path_aliases-2020-10.                                                                                                       [warning]
Skipped or failed updating alias for nid 9480 VACMS-3197-bulk_update_lc_path_aliases-2020-10.                                                                                                       [warning]
Skipped or failed updating alias for nid 9276 VACMS-3197-bulk_update_lc_path_aliases-2020-10.                                                                                                       [warning]
Skipped or failed updating alias for nid 8684 VACMS-3197-bulk_update_lc_path_aliases-2020-10.                                                                                                       [warning]
Path aliases updated 84 out of 88 entities.  Skipped or failed to update: 4.
bash-4.2$
```