VACMS-2706: Updated Resources and Support Dashboard
department-of-veterans-affairs/va.gov-cms pull request #3282
Opened 2020-10-23 13:24 UTC by kaise-lafrai

…ding page block, updated resources and support page to include the new block in the header and updated url alias

## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2706

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

2020-10-23 13:26 UTC, kaise-lafrai commented
@oksana-c I'm creating this draft PR for you to review the Resources and Support dashboard. Keep in mind that the roles for the view access are still not updated because 3132 is still in review and not merged yet. Thank you.

2020-10-26 14:51 UTC, swirtSJW requested changes
Looks great Kaise.   Just one minor request as long as we are burning the original view and starting over.

2020-10-26 14:51 UTC, swirtSJW commented on config/sync/views.view.content.yml
>    page_3:
As long as we are essentially recreating this view.  Can we get rid of this default name and name it more meaningfully.    It would also need a change to the behat test too?  Sorry I let that slip in originally.
![image](https://user-images.githubusercontent.com/5752113/97187512-e0cd5700-1778-11eb-8385-33ad6e3f6487.png)

It would help if the machine name was similar to the human name and namespaced to  dashboard 
 ex: dashboard_resources_support

2020-10-26 14:54 UTC, kaise-lafrai commented on config/sync/views.view.content.yml
>    page_3:
I agree with you. I made sure I created a human readable name for the new view block. I'll also make sure to update this view page to something meaningful. 👍

2020-10-26 16:08 UTC, kaise-lafrai commented on config/sync/views.view.content.yml
>    page_3:
Done!

2020-10-26 17:21 UTC, swirtSJW approved these changes

2020-10-26 17:22 UTC, merged