VACMS_3265: Format situation update time field widget.
department-of-veterans-affairs/va.gov-cms pull request #3291
Opened 2020-10-24 11:49 UTC by ethanteague

## Description
See #3265 

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/97080954-22210380-15cd-11eb-92d4-491bfb45708d.png)

## QA steps
Kev to do this one (please)

2020-10-26 15:04 UTC, swirtSJW requested changes
Looks good Ethan.   One minor and one moderate request.

2020-10-26 16:21 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($paragraph_entity_reference_field_name === 'field_content_block' || $paragraph_entity_reference_field_name === 'field_service_location' || $paragraph_entity_reference_field_name === 'field_situ
I think the line limit thing is maybe set to not trigger a phpcs violation in our container settings? I'll refactor this, @swirtSJW :+1:

2020-10-26 17:27 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($paragraph_entity_reference_field_name === 'field_content_block' || $paragraph_entity_reference_field_name === 'field_service_location' || $paragraph_entity_reference_field_name === 'field_situ
Nice.  Thanks.

2020-10-26 17:28 UTC, swirtSJW approved these changes

2020-10-27 18:28 UTC, swirtSJW approved these changes

2020-10-27 18:30 UTC, swirtSJW commented
QA steps  I am not sure what to do with this one.  @kevwalsh can I merge?

2020-10-27 19:22 UTC, ethanteague commented
@kevwalsh can you qa this one?

2020-10-28 13:21 UTC, kevwalsh commented
Sorry for delay on the QA!
![Edit_VAMC_System_Banner_Alert_with_Situation_Updates_Help_Limit_the_Spread_of_COVID-19_and_other_Illnesses___VA_gov_CMS](https://user-images.githubusercontent.com/643678/97441195-d210ac80-18fe-11eb-8087-e3a0536565d0.jpg)

2020-10-28 13:26 UTC, ethanteague commented
@swirtSJW - looks like we are good to merge this one in.

2020-10-29 03:03 UTC, merged