VACMS 3223:  User Role dimension for the CMS Google Analytics data
department-of-veterans-affairs/va.gov-cms pull request #3302
Opened 2020-10-26 17:55 UTC by ndouglas

## Description

See #3223.

I do not currently have access to Google Tag Manager, so I can't add the necessary mapping.  

I'm setting `currentUserRoles` to a comma-delimited list of user role machine names, e.g.
```
    | role                | roles                             |
    | "authenticated"     | "authenticated"                   |
    | "content_admin"     | "authenticated,content_admin"     | 
    | "content_publisher" | "authenticated,content_publisher" |
```

I also added a Behat test and some code to `\CustomDrupal\FeatureContext` to support the test and any other tests we want to perform on the JS Drupal Settings or on the GTM dataLayer.  Please let me know if this is inappropriate or should've been done in a different place.

## Testing done
I added a Behat test and some supporting code and ran it for the roles listed above.

## Screenshots
<img width="554" alt="Screen Shot 2020-10-26 at 12 51 51 PM" src="https://user-images.githubusercontent.com/1318579/97209220-0f076280-178a-11eb-86a3-d3fd439b8c7b.png">

## QA steps
As any user
1. Log in and view any page in Chrome or some other browser with a developer console.
2. Open developer console and type `dataLayer[1].currentUserRoles`.
3. Verify that the console responds with a comma-separated list of user roles.

## Definition of Done
- [ ] Mapping needs to be added in GTM to set the appropriate GA custom dimension.  I have access to GA but not GTM yet.

2020-11-02 14:01 UTC, ndouglas commented
@ethanteague This change is two lines of code or so, but I thought you might have some thoughts about the way I did the tests, whether they're worth doing that way, whether I should expand them/change them/rip them out completely, etc.  Probably (?) can't be merged until the GTM/GA work is done elsewhere, but thought it might be worth reviewing anyway.

2020-11-02 14:36 UTC, ethanteague commented on tests/behat/features/google_tag_manager.feature
> +    Then google tag manager id is "GTM-WQ3DLLB"
@ndouglas I don't think this step / function is necessary - googleTagManagerIdIs step logic should be enough.

2020-11-02 14:36 UTC, ndouglas commented on tests/behat/features/google_tag_manager.feature
> +    Then google tag manager id is "GTM-WQ3DLLB"
Fair enough 👍

2020-11-02 14:45 UTC, indytechcook submitted a review, later dismissed

2020-11-12 23:28 UTC, oksana-c requested changes

2020-11-12 23:28 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.js
> +        'currentUserRoles': settings.gtm_data.currentUserRoles ? settings.gtm_data.currentUserRoles : null,
```suggestion
        'userRoles': settings.gtm_data.userRoles ? settings.gtm_data.userRoles : null,
```

2020-11-12 23:28 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $sections['currentUserRoles'] = json_encode($user_roles);
```suggestion
  $sections['userRoles'] = json_encode($user_roles);
```

2020-11-12 23:28 UTC, oksana-c commented on tests/behat/features/google_tag_manager.feature
> +    Then google tag manager data layer value for "currentUserRoles" should be '["anonymous"]'
```suggestion
    Then google tag manager data layer value for "userRoles" should be '["anonymous"]'
```

2020-11-12 23:28 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.js
> +        'currentUserRoles': settings.gtm_data.currentUserRoles ? settings.gtm_data.currentUserRoles : null,
changing `currentUserRoles` to `userRoles` to match GA/GTM naming. Having `current` in the var name is not necessary for GA context.

2020-11-18 15:04 UTC, oksana-c approved these changes
code/tests look great.
disregard my request to filter out `authenticated` role. After all,  it has its use. When new users are registered in the CMS they go without having a role for some time, so we could track their info separately.

2020-11-18 15:09 UTC, oksana-c commented
prepped GA and GTM, and will coordinate updated container release once this baby goes out to prod ⚡

2020-11-19 13:26 UTC, merged