VACMS-3254: Update R&S term page views.
department-of-veterans-affairs/va.gov-cms pull request #3321
Opened 2020-10-27 21:26 UTC by ethanteague

## Description
See #3254

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/97363492-0e99c500-1879-11eb-8479-99c048778e30.png)
![image](https://user-images.githubusercontent.com/2404547/97363519-15c0d300-1879-11eb-9b1a-2b64ac810afc.png)
![image](https://user-images.githubusercontent.com/2404547/97363571-2a9d6680-1879-11eb-8b17-ffeb738b6968.png)

## QA steps
- As an administrator, go to `admin/config/system/taxonomy-entity-index/reindex`, check both entity types, and rebuild index.
- When indexing is complete, go to R&S page `/taxonomy/term/292`
- Visually verify that the title reads `All articles in: Sign in`
- Visually verify that rss link is not in footer
- Visually verify that page title sort order is a-z

2020-10-28 15:18 UTC, oksana-c requested changes
when I visit http://pr3321.ci.cms.va.gov/node/8222 I see "Sign in" - topics tag and "All Veterans" - Audience tag. 
Term content listing views are empty though:
* http://pr3321.ci.cms.va.gov/taxonomy/term/292
* http://pr3321.ci.cms.va.gov/taxonomy/term/268

please take a look, something may be missing in views config

2020-10-28 15:33 UTC, ethanteague commented
Looks like you missed this QA step, @oksana-c : `As an administrator, go to admin/config/system/taxonomy-entity-index/reindex, check both entity types, and rebuild index.`
I just ran, and those pages are now populated
![image](https://user-images.githubusercontent.com/2404547/97458637-43f1f180-1911-11eb-897c-2de373ecdba7.png)
![image](https://user-images.githubusercontent.com/2404547/97458660-49e7d280-1911-11eb-8939-d51a9de46021.png)

2020-10-28 15:47 UTC, oksana-c approved these changes
I sure did. Thanks @ethanteague - I can see it now ✅

2020-10-28 16:46 UTC, oksana-c requested changes
one of the new path patterns is deleted, let's bring it back. see comment

2020-10-28 16:46 UTC, oksana-c commented on config/sync/pathauto.pattern.taxonomy_terms.yml
> -uuid: 47be66c7-ece7-45e1-a63c-5c92ee31d9b3
something tells me this should be deleted

2020-10-28 16:46 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      . ' ' . $variables['title']['#markup'];
```suggestion
      $variables['title']['#markup'] = t('All articles in:') . ' ' . $variables['title']['#markup'];
```

2020-10-28 16:55 UTC, oksana-c approved these changes
⚡

2020-10-29 02:02 UTC, swirtSJW approved these changes

2020-10-29 02:41 UTC, merged