VACMS-2934: Add html formatting constraint checks to table cells.
department-of-veterans-affairs/va.gov-cms pull request #3369
Opened 2020-11-03 15:11 UTC by ethanteague

## Description
See #2934 
@kevwalsh @oksana-c have a look at the screenshot / form when qa'ing. 

**BAD NEWS**: You'll notice that every cell is highlighted when a violation is detected - I haven't been able to figure out a way (at least not with constraints) to target individual cells.

**GOOD NEWS**: Html entries are all being caught, and this approach will solve the challenges that editors are having with missed / mismatched tags breaking pages.

Just lemme know if this approach will suffice.

## Testing done
Visual 

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/98000425-7b054e80-1dba-11eb-9a60-265c5eda329e.png)

## QA steps
- As an administrator, go to `/node/471/edit`
- In Main content section, add a table paragraph
- Enter content with broken html tags in multiple cells
- Save form, and confirm error notifications occur and specify each improperly formatted html instance

2020-11-03 17:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> -
Looks like you are clobbering some previous work here.

2020-11-03 17:40 UTC, swirtSJW requested changes
Bad rebase?   Clobbered a bunch of prior work.

2020-11-03 18:05 UTC, ethanteague commented
> Bad rebase? Clobbered a bunch of prior work.

Yeah - lemme sort this out. Gonna put this in draft state for now.

2020-11-03 20:37 UTC, swirtSJW commented
I'm trying a bit to refine this... make it less scary

2020-11-05 16:02 UTC, swirtSJW commented
@ethanteague  I just pushed up some changes to make the feedback more informative about which cells are bad... but this still does not seem like the right approach.   I commented as such on the issue.   We should re-group on this.

2020-11-06 14:10 UTC, swirtSJW commented
@ethanteague I am going to close this in favor of the processing approach rather than the validation approach.   It was a valiant effort on both our parts.. but this just aint the right dragon to slay,

2020-11-06 14:12 UTC, closed without merging