VACMS-2934: Add html cleanup to table field.
department-of-veterans-affairs/va.gov-cms pull request #3415
Opened 2020-11-07 15:11 UTC by ethanteague

## Description
See #2934 

## Testing done
Visual / behat

## QA steps
- As an administrator, go to /node/471/edit
- In Main content section, add a table paragraph
- Enter content with broken html tags in multiple cells
- Save form, and confirm table displays properly on node save
- Return to edit form, and confirm broken html has been cured in table cells

2020-11-12 21:33 UTC, swirtSJW requested changes
I think you are on the right track here.  Just a few suggestions.

2020-11-12 21:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function _va_gov_backend_tidy_html(EntityInterface $entity) {
Naming here is a bit vague.  Could benefit from being named about what it actually does.  
```suggestion
function _va_gov_backend_apply_filter_to_tablefield_cells(EntityInterface $entity) {
```

2020-11-12 21:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> + * Clean up html tags in table fields.
```suggestion
 * Apply html filter to tablefield on save so it is properly formatted on the way in.
 *
 * This is needed because the field data of table fields does not have a 'processed' 
 * property in graphQL or CMS Export. 
```

You'll need to add this one by hand since formatting of comments by the inline github suggestion always ends messed up.

2020-11-12 21:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +        foreach ($row_item as $cell_key => $cell_item) {
I think we need to be defensive here and check that is an array before dumping it into a foreach.   I can envision some goofy situation where an editor removes a row or something and we get unexpected results here which would create a whitescreen during node save which would be bad.

2020-11-12 22:05 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($entity->getEntityTypeId() === 'paragraph' && $entity->bundle() === 'table') {
That's a great point, @swirtSJW - didn't think of that :+1:

2020-11-13 16:38 UTC, swirtSJW requested changes

2020-11-13 16:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $raw_table = $entity->get('field_table')->value;
This is still making the assumption it is in field_table... which bypasses other occurrences even if they were found in the earlier loop.

2020-11-13 16:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    if ($field->getType() === 'tablefield') {
This logic is finding the presence of tablefield, but then not getting the field name, so it does not know what to alter.  
I suggest not doing the detection here.  Just call the function `_va_gov_backend_apply_filter_to_tablefield_cells` for all entities and have this detection in the function.  As it loops through detecting the `tablefield` it should be collecting the field names so then when it goes to clean those, it knows which fields to process.

2020-11-13 16:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +        foreach ($row_item as $cell_key => $cell_item) {
Still need to be defensive here.

2020-11-13 22:03 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $raw_table = $entity->get('field_table')->value;
oops - will fix :+1:

2020-11-16 13:51 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $field_definitions = Drupal::service('entity_field.manager')->getFieldDefinitions($entity->getEntityTypeId(), $entity->bundle());
Why was it necessary to load the service and call this for the bundle when you had direct access to the field definitions on the entity via `$entity->getFieldDefinitions()`?

That was working before. We just need to detect if the method is available first since not all entities support it.

2020-11-16 15:00 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $field_definitions = Drupal::service('entity_field.manager')->getFieldDefinitions($entity->getEntityTypeId(), $entity->bundle());
Marking this as resolved, per slack convo summary: 
**Ethan Teague** Today at 9:38 AM
Howdy, @Steve Wirt - here's the problem I was running into / reason for calling the service to get field info.

![image](https://user-images.githubusercontent.com/2404547/99267794-65e4e280-27f2-11eb-98ab-2457d2864381.png)

**2 replies**

**Steve Wirt**  5 minutes ago
OK...   That is because our php is too out of date.  On our old php  method_exists returns a TRUE even if the method is private.  On current php  it returns FALSE if the method is private.
var_dump(method_exists(Bar::class, 'privateMethodTest'));
// PHP 7.4: bool(false)
// PHP 7.3: bool(true)
 (edited) 

**Steve Wirt**  5 minutes ago
Good solution then.

2020-11-18 14:41 UTC, ethanteague commented
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3511

2020-11-18 14:41 UTC, closed without merging