[docs] VACMS-3157 Update code review document
department-of-veterans-affairs/va.gov-cms pull request #3437
Opened 2020-11-09 22:18 UTC by indytechcook

## Description

See #3157 

This document assumes that tugboat has been implemented for PR tests.

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-11-10 14:12 UTC, swirtSJW commented on READMES/code-review.md
> +* PHPCS
If these are part of our test suite, do they need to be called out separately?

2020-11-10 14:12 UTC, swirtSJW approved these changes

2020-11-10 14:16 UTC, ndouglas submitted a review, later dismissed

2020-11-10 14:18 UTC, ndouglas commented
One question: why is it important for the PR to be assigned to the author?  I'm guessing that serves some function, I'm just not sure what.  And maybe that should be in the document? 🤔

2020-11-10 17:59 UTC, oksana-c requested changes

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +* PR Review must Approve Pull Request
```suggestion
* PR Reviewer must Approve Pull Request
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +Let's start the discussion by talking about different personas. I will try to avoid process descriptions in the personas and focus on responsibilities.
```suggestion
Let's start the discussion by talking about different personas and focus on their responsibilities.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +* Merging the Pull Request on Approval and test passing.
```suggestion
* Merging the Pull Request when it's approved, tests are passing and the PR meets a Definition of Done.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +
```suggestion
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +* Validating the changes in the Pull Request fulfill the needs of the Product Owner and related issue
```suggestion
* Validating the changes in the Pull Request fulfill the needs of the Product Owner and ACs in related issue
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +A PR Review is one or more people responsible for reviewing all the changes a Pull Request introduces. There can be multiple PR Reviewers per PR. A PR Reviewer can be anyone that is part of the depar
```suggestion
A PR Review is one or more people responsible for reviewing all the changes a Pull Request introduces. There can be multiple PR Reviewers per PR. A PR Reviewer can be anyone that is part of the department-of-veterans-affairs/va.gov-cms group. If a change introduced by a Pull Request introduces an architectural change or a significant new feature, a Tech Lead and a Product Manager (as needed) should be the PR Reviewer.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +
```suggestion
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +* Review code for quality passed upon Insert Spec Here?
```suggestion
* Review code for quality passed upon [Insert Spec Here]
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +* Request a review from a Tech Lead if necessary.
```suggestion
* Request a review from a Tech Lead if necessary.
* Request a review from a Product Manager if necessary.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +* Request a review from a Product Owner on CI if necessary.
```suggestion
* Request a review from a Product Owner on CI if necessary. Note: issues that require PO review will be tagged using `Needs PO review` label. PRs addressing issues that need PO review should also be labelled.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +The Product Manager is a person on the CMS team who works with the Product Owner on defining feature requests and priorities. The Product Manager can participate in the Code Review process and be bro
```suggestion
### Product Owner

The Product Owner is a person who makes and prioritizes feature requests. This person is normally a part of VA/DEPO organization. The Product Owner is not directly involved in the PR Review process. The Product Manager makes a decision of whether the Product Owner should be brought in to review changes on the CI environment.

### Product Manager

The Product Manager is a person on the CMS team who works with the Product Owner on defining feature requests and priorities. The Product Manager can participate in the PR Review process and be brought in to review changes on the CI environment as specified in User Story Acceptance Criteria. The Code Owner will keep the Product Manager up to date on status.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +1. Add Code/Product team label.
```suggestion
1. Add `Core Application Team` or `Product Team Support` label.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +1. A Pull Request is created in Github as a `draft`.
```suggestion
1. A Pull Request is created in Github as a `Draft`.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +1. If appropriate, the PR Owner will add one or multiple PR Reviews as reviewers on the Pull Request.
```suggestion
1. PR Owner will request one or multiple PR Reviewers for the Pull Request as needed.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +1. If a change introduced by a Pull Request introduces an architectural change or a significant new feature, the Tech Lead will take the role as the PR Reviewer and a reviewers on the Pull Request.
```suggestion
1. If a change introduced by a Pull Request introduces an architectural change or a significant new feature, the Tech Lead will take the role of the PR Reviewer on the Pull Request.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +1. PR Reviewer will provide feedback on the Pull Request using the Review Changes feature. The feedback should be in a single review and not several individual comments on the Pull Request.
```suggestion
1. PR Reviewer will provide feedback on the Pull Request using the Review Changes feature. Good feedback practice is to leave a single review and not several individual comments on the Pull Request.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +1. When PR Reviewer is satisfied the changes introduced by the Pull Request are of high quality, address the related issue and will not introduce new regressions, the Pull Request is approved.
```suggestion
1. When PR Reviewer has identified that the changes introduced by the Pull Request are of high quality, address the related issue and will not introduce new regressions, the Pull Request is approved.
```

2020-11-10 17:59 UTC, oksana-c commented on READMES/code-review.md
> +* Manual Code Review Approved
```suggestion
* Manual Code Review Approved
* Acceptance Criteria in related issue are met
```

2020-11-10 20:06 UTC, indytechcook commented
> One question: why is it important for the PR to be assigned to the author? I'm guessing that serves some function, I'm just not sure what. And maybe that should be in the document?

@ndouglas it's important to know who the code owner is both as a reviewer and as an owner.  Like if I have 5 PR's I'm owning I can filter the list down quickly.

2020-11-10 20:12 UTC, indytechcook commented on READMES/code-review.md
> +* PHPCS
I'd like to separate out tests from code quality.  Eventually moving to something like https://codeclimate.com/ or https://www.exakat.io/en/.  Tugboat also provides the ability to fail the build before tests even start on code quality fails.

2020-11-10 20:18 UTC, indytechcook commented on READMES/code-review.md
> +* Review code for quality passed upon Insert Spec Here?
I meant to delete this line.  We don't need a spec as automated tests, code quality and manual review is already listed on this doc

2020-11-10 20:19 UTC, indytechcook commented on READMES/code-review.md
> +* Request a review from a Product Owner on CI if necessary.
Reminder for me to update the PR template in github

2020-11-10 21:38 UTC, acrollet commented on READMES/code-review.md
> +* Follow up with questions/feedback PR Code Owner in a timely manner
```suggestion
* Follow up with questions/feedback for the PR Code Owner in a timely manner
```

2020-11-10 21:39 UTC, acrollet commented on READMES/code-review.md
> +A PR Review is one or more people responsible for reviewing all the changes a Pull Request introduces. There can be multiple PR Reviewers per PR. A PR Reviewer can be anyone that is part of the depar
```suggestion
A PR Reviewer is one or more person(s) responsible for reviewing all the changes a Pull Request introduces. There can be multiple PR Reviewers per PR. A PR Reviewer can be anyone that is part of the department-of-veterans-affairs/va.gov-cms group. If a change introduced by a Pull Request introduces an architectural change or a significant new feature, a Tech Lead and a Product Manager (as needed) should be the PR Reviewer.
```

2020-11-10 21:41 UTC, acrollet commented on READMES/code-review.md
> +The Product Owner is a person who makes and prioritizes feature requests. This person is normally a part of VA/DEPO organization. The Product Owner is not directly involved in the PR Review process.
```suggestion
The Product Owner is a person who makes and prioritizes feature requests. This person is normally a part of VA/DEPO organization. The Product Owner is not directly involved in the PR Review process. The Product Manager decides whether the Product Owner should be brought in to review changes on the CI environment.
```

2020-11-13 14:39 UTC, ethanteague submitted a review, later dismissed

2020-11-13 14:49 UTC, indytechcook commented
I listed a few possible follow ups after a discussion in slack: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3157#issuecomment-726805558.

2020-11-16 14:58 UTC, merged