VACMS-3470: fix publish latest revision action
department-of-veterans-affairs/va.gov-cms pull request #3478
Opened 2020-11-13 19:17 UTC by acrollet

## Description

See #3470.

## Testing done

Manual testing, added unit test for new service.

## QA steps

As an admin user:
1. Open the Bulk Edit Content page (/admin/content/bulk?title=Psychology+Internships+and+Fellowships&type=health_care_region_detail_page&moderation_state=All&taxonomy_entity_index_tid_depth=All)
1. Open the "Psychology Internships and Fellowships" node in a new tab and save a draft with a new title
1. On the Bulk Edit Content page, select the "Psychology Internships and Fellowships" and apply the "Publish Latest Revision" action
1. Validate that:
- [ ] The published revision has the new title

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

2020-11-13 20:34 UTC, indytechcook commented
It looks good code wise.  I nice refactor.  I'm waiting until test pass to do the review in devshop.

2020-11-13 20:36 UTC, ndouglas submitted a review, later dismissed
I tested locally @indytechcook and it worked as expected.  Code LGTM too.

2020-11-13 23:06 UTC, acrollet commented
@oksana-c pinging in case you'd like to validate this.

2020-11-16 13:47 UTC, oksana-c requested changes
attaching annotated screenshots. We may need a 16th min on this one today

### testing VBO on existing content
<img width="1508" alt="1" src="https://user-images.githubusercontent.com/16477724/99259559-6cb22c00-27d7-11eb-9347-b809a7a542d9.png">

let's rename these two custom actions while we're at it

<img width="1493" alt="rename actions" src="https://user-images.githubusercontent.com/16477724/99259572-720f7680-27d7-11eb-8e0e-d30c6d0d0f4b.png">

----

### Observations while creating new content then running it thru Unpublish bulk action

Revisions in content region seems to align, although no revision messages are added and expect that author and timestamp are also taken from the last revision before the VBO was ran. 
In the right sidebar, the view shows an extra Draft revision, which is expected, because current logic in this PR saves Archived and then Draft revision. I can guess the rationale why Draft was added as a last revision, although I think we should not add Draft after Archived for Unpublish action, since users need to get accustomed to the concept of "Archived" and make a conscious decision on whether or not content gets resurrected as Draft after been Archived.
<img width="1493" alt="Screen Shot 2020-11-16 at 7 02 02 AM" src="https://user-images.githubusercontent.com/16477724/99261370-dfbca200-27d9-11eb-8ed2-4fec7d9daa3a.png">

strangely, Draft is displayed as last status in the bulk content view
<img width="1473" alt="Screen Shot 2020-11-16 at 7 02 42 AM" src="https://user-images.githubusercontent.com/16477724/99261381-e4815600-27d9-11eb-8a6d-d4e9ec8d8d6e.png">

2020-11-16 13:47 UTC, oksana-c commented on docroot/modules/custom/va_gov_bulk/src/Service/ModerationActions.php
> +    $node->set('moderation_state', 'draft');
is there a reason why we would want to create a `draft` after creating `archived` version?

2020-11-16 13:47 UTC, oksana-c commented on docroot/modules/custom/va_gov_bulk/src/Service/ModerationActions.php
> +    }
revision info is not applied on save. 

`$node instanceof RevisionLogInterface` - did you mean `NodeInterface`? do we need `if` statement here?

2020-11-16 15:01 UTC, acrollet commented on docroot/modules/custom/va_gov_bulk/src/Service/ModerationActions.php
> +    $node->set('moderation_state', 'draft');
good question, I assumed that this was an original requirement.

2020-11-16 15:04 UTC, acrollet commented on docroot/modules/custom/va_gov_bulk/src/Service/ModerationActions.php
> +    }
Good point, I think this action was originally meant to be available for all entities so I believe that was the reasoning behind `RevisionLogInterface`. However there were other dependencies on the object being a node, so I made the logic explicit and I think we can remove the `if` statement.

2020-11-16 15:06 UTC, acrollet commented
@oksana-c let's definitely 16th minute this and get on the same page since we're talking about changing the spec. :-)

2020-11-16 16:16 UTC, acrollet commented
I'm also seeing that the content creation time is shown in the 'Recent changes' view, which means that when a revision is published via bulk action, the date shown is when the draft was created rather than when it was published. Let's discuss whether to change that behavior as well.

2020-11-16 17:13 UTC, acrollet commented
Capturing action items discussed in 16th minute:

- [ ] change "Unpublish current revision" to "Archive selected content (Unpublish) "
- [ ] Archive action should not also create a new draft revision
- [ ] change "Publish Latest Revision" to "Publish latest revision"
- [ ] update "Recent changes" view to display revision update timestamp instead of revision created timestamp

2020-11-17 18:37 UTC, oksana-c approved these changes
both actions work well. I'm opening a follow up issue to use Revision Created time instead of Changed for sorting the right sidebar "Recent changes" view, since it's definitely out of scope here.
✅ good to merge from me

2020-11-17 18:54 UTC, acrollet commented
@indytechcook @ndouglas if I could get a re-pass on the CR from one of you that would be awesome, thanks :-)

2020-11-17 18:55 UTC, ndouglas commented
@acrollet What's the timetable?  I should be able to get to this today if it's not _too_ rushed, but it might be a couple hours.

2020-11-17 18:57 UTC, acrollet commented
I think we're past today's window to test and deploy, so any time today should be fine. cc @oksana-c

2020-11-17 21:48 UTC, ndouglas approved these changes
I confirmed that this worked as expected and reflected the update to the action name, etc.

2020-11-17 22:56 UTC, acrollet commented
many thanks @ndouglas !

2020-11-17 22:56 UTC, merged