VACMS-3507: implement alternative publishing workflow (copy)
department-of-veterans-affairs/va.gov-cms pull request #3541
Opened 2020-11-20 03:04 UTC by acrollet

This is a copy of #3515 to get a new test environment created.

2020-11-20 12:56 UTC, oksana-c requested changes
@acrollet, functionally - the ACs are met 👍 . Please see comments re: config files / code

2020-11-20 12:56 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    if ($element['current']['#markup'] === 'Published') {
String comparison for state/transition labels is dangerous. they may change overtime. Not that the "Published" one will change any time soon, but it's best if we pull current state machine name from node object instead of relying on the FE label in the markup element.

2020-11-20 12:56 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      $element['state']['#default_value'] = 'Draft';
this works in PR env, but is it `Draft` or `draft` ? 

<img width="593" alt="Screen Shot 2020-11-20 at 5 52 45 AM" src="https://user-images.githubusercontent.com/16477724/99802266-a3988280-2af4-11eb-8639-83336cb77046.png">

2020-11-20 13:08 UTC, ethanteague commented on config/sync/core.entity_view_display.node.health_care_region_page.default.yml
> -        - field_leadership
@acrollet @oksana-c 
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3457/files
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3524/files

2020-11-20 15:12 UTC, acrollet commented
@oksana-c tests have passed in this copy :-)

2020-11-20 15:27 UTC, acrollet commented on config/sync/core.entity_view_display.node.health_care_region_page.default.yml
> -        - field_leadership
@ethanteague @oksana-c can we hang on for a few minutes after the demo and touch base on this?

2020-11-20 15:51 UTC, oksana-c commented on config/sync/core.entity_view_display.node.health_care_region_page.default.yml
> -        - field_leadership
dropped 15mins on our calendars

2020-11-20 15:51 UTC, acrollet commented on config/sync/core.entity_view_display.node.health_care_region_page.default.yml
> -        - field_leadership
ty!

2020-11-20 15:54 UTC, acrollet commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      $element['state']['#default_value'] = 'Draft';
It turns out the comparison is very greedy, even 'Draft123' works(!) I had used the value b/c that's what the default #default_value does, but it makes sense to me to use the key, changed.

2020-11-20 15:57 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      $element['state']['#default_value'] = 'Draft';
key is safer because it represents a machine name of the state, which is unlikely to change overtime 👍

2020-11-20 16:31 UTC, ElijahLynn commented
This got borked somehow in CI. Fixing now.

2020-11-20 17:08 UTC, acrollet commented
field changes were validated with @ethanteague @oksana-c on a call just now.

2020-11-24 00:33 UTC, oksana-c approved these changes
DevShop is borked, but I QA'ed this thoroughly on local env. Tests are passing locally. Merging this. thank you @acrollet 

@rachel-kauff , let's queue up the announcement for tomorrow's deploy

2020-11-24 00:33 UTC, merged