VACMS-3465: Add spotlight panel.
department-of-veterans-affairs/va.gov-cms pull request #3565
Opened 2020-11-23 21:31 UTC by ethanteague

## Description
See #3465 

## Testing done
Visual / Behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/100017279-a7542f80-2da8-11eb-8528-5183a9980fe2.png)
![image](https://user-images.githubusercontent.com/2404547/100017291-aae7b680-2da8-11eb-9092-fb708ab9abc3.png)

## QA steps
- As an administrator, go to `/node/add/campaign_landing_page` and click on the Spotlight panel
- Visually verify that only a `Spotlight opt-in` toggle appears
- Visually verify that clicking it reveals all section fields, and text fields are required
- Add list of link teasers, and visually verify that after third is added, button to add more no longer appears

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-11-24 16:07 UTC, kevwalsh commented
Nice, i have a few suggestions for some changes, minor field labels and help text. 

![Create_Campaign_Landing_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/100118563-f8653180-2e43-11eb-9c59-2132a151ab49.jpg)

![Create_Campaign_Landing_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/100119391-cdc7a880-2e44-11eb-9bb3-be50e9cd0114.jpg)

Also, i think we should replace `field_spotlight_cta` with `field_clp_spotlight_cta` (sorry), to bring it in line with the other fields that won't be reused outside this product.

2020-11-24 16:07 UTC, kevwalsh requested changes
I reviewed the content model and editorial experience. Not the boolean behavior code. Requested changes above.

2020-11-24 22:20 UTC, oksana-c approved these changes
Code looks good ⭐ . Didn't retest functionality since devshop is still building. @kevwalsh , leaving it up to you to re-test UI after updates.

2020-11-24 22:20 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +            'required' => TRUE,
❤️ this new structure. thanks for giving it a shot!

2020-11-24 22:20 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  // this pattern.
👍

2020-11-30 15:20 UTC, kevwalsh approved these changes
QA'd the form and looks good!

2020-11-30 18:21 UTC, swirtSJW reviewed
Waiting to test this until I get devshop sorted out 
![image](https://user-images.githubusercontent.com/5752113/100648440-ee917180-330e-11eb-84e8-c3dc7ffa76fa.png)

2020-11-30 18:21 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/js/script.js
> +        if ($('#field-clp-spotlight-link-teasers-add-more-wrapper .paragraphs-dropbutton-wrapper').length > 3) {
Doesn't this only remove the button if there are 4?  Shouldn't it be >=?

2020-11-30 18:26 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/js/script.js
> +        if ($('#field-clp-spotlight-link-teasers-add-more-wrapper .paragraphs-dropbutton-wrapper').length > 3) {
Good q, but nope. For some reason there is an extra instance of this element being counted via behaviors. I looked up and down in the dom, and couldn't figure out why, but the count was consistently off by one in both brave and chromium, @swirtSJW

2020-11-30 18:27 UTC, ethanteague commented on config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
> +    - field.field.node.campaign_landing_page.field_clp_spotlight_opt_in
Straight out of @kevwalsh 's mind / old pr.

2020-11-30 20:49 UTC, swirtSJW commented
This tests out on the other PR tests 
![image](https://user-images.githubusercontent.com/5752113/100662954-944edb80-3323-11eb-9237-ab1d4d95b8f8.png)

2020-11-30 21:56 UTC, swirtSJW commented
Proofing issues raised  here https://dsva.slack.com/archives/CT4GZBM8F/p1606772498165900 are already in another ticket.

2020-11-30 22:02 UTC, merged