VACMS-3467: CLP Video Panel
department-of-veterans-affairs/va.gov-cms pull request #3581
Opened 2020-11-24 20:25 UTC by kaise-lafrai

## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3467

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
Coming soon

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-11-24 20:26 UTC, kaise-lafrai commented
@kevwalsh I'm still writing up the QA steps. Please feel free to check the work out.

2020-12-03 17:11 UTC, swirtSJW requested changes
A couple possible issues.

2020-12-03 17:12 UTC, acrollet commented on config/sync/core.entity_form_display.media.video.media_library.yml
> -  revision_log_message: true
hmm, I guess our revision log test doesn't catch these cases?

2020-12-03 22:02 UTC, swirtSJW reviewed
Code looks good.   Testing locally now.

2020-12-03 22:44 UTC, swirtSJW commented
Needs to be connected to Ethan's hidey logic but can be in followup ticket 
![image](https://user-images.githubusercontent.com/5752113/101097436-24dd2400-358f-11eb-8e02-e62b8514acd2.png)

2020-12-04 01:29 UTC, kevwalsh approved these changes
Screenshot of the video panel form looks good to me! 

@swirtSJW i tested the video bundle form previously, so assuming it hasn't changed this is good to go. i can't test locally right now. 

Boolean form hiding logic will take place in #3575, next sprint

2020-12-04 06:35 UTC, swirtSJW commented
Proof of working 
![image](https://user-images.githubusercontent.com/5752113/101130110-e0727800-35d0-11eb-8bf1-bfeca2682428.png)


I completed #3575  too.

2020-12-04 06:45 UTC, swirtSJW approved these changes

2020-12-04 06:51 UTC, swirtSJW commented
Devshop completely fell down on building this 
![image](https://user-images.githubusercontent.com/5752113/101131113-c33ea900-35d2-11eb-92eb-7aaf7e4c4291.png)

Merging based on tests passing on sandbox.

Nice work @kaise-lafrai

2020-12-04 06:52 UTC, merged