VACMS-000: Add resources panel to clp.
department-of-veterans-affairs/va.gov-cms pull request #3601
Opened 2020-12-01 14:38 UTC by ethanteague

## Description

See _issueid_. 

## Testing done

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/100746701-0f110880-33af-11eb-80db-bdce00056946.png)
![image](https://user-images.githubusercontent.com/2404547/100746712-13d5bc80-33af-11eb-9df3-6b8acfac0f3a.png)

## QA steps
As an administrator, go to `node/add/campaign_landing_page#edit-group-downloadable-resources`
Visually verify that the resources panel appears as indicated by the screenshots.
Verify enabling panel and not entering data in fields does not save and displays form error.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-12-02 17:43 UTC, kevwalsh commented
@ethanteague I updated some ACs based on our conversation with PW POs this morning, plus a couple of minor details. 

i unchecked the ACs that i modified.

2020-12-02 21:27 UTC, ethanteague commented
> @ethanteague I updated some ACs based on our conversation with PW POs this morning, plus a couple of minor details.
> 
> i unchecked the ACs that i modified.

Updated, @kevwalsh

2020-12-03 17:24 UTC, swirtSJW requested changes

2020-12-03 17:24 UTC, swirtSJW commented on config/sync/field.field.media.document_external.field_media_in_library.yml
> +description: 'By default, documents you upload to the CMS can be reused by other VA.gov CMS editors. Uncheck this box if to prevent reuse by other CMS editors.'
```suggestion
description: 'By default, documents you upload to the CMS can be reused by other VA.gov CMS editors. Uncheck this box to prevent reuse by other CMS editors.'
```

2020-12-03 17:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PdfCheck.php
> + *   label = @Translation("UPDF Check", context = "Validation"),
UPDF?

2020-12-03 17:24 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_media_fields.feature
> +      | Type       | Bundle              | Field label                 | Machine name                     | Field type         | Required | Cardinality | Form widget                           | Trans
Are the indening changes directly from spectool?

2020-12-03 17:24 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/views.feature
> +| File browsers | Block | block_1 | Block |
Would like to get non-generic names on these views.  block_1 and default are not very intuitive when accessing through code.

2020-12-03 20:18 UTC, ethanteague commented on config/sync/field.field.media.document_external.field_media_in_library.yml
> +description: 'By default, documents you upload to the CMS can be reused by other VA.gov CMS editors. Uncheck this box if to prevent reuse by other CMS editors.'
:+1:

2020-12-03 20:18 UTC, ethanteague commented on tests/behat/drupal-spec-tool/content_model_media_fields.feature
> +      | Type       | Bundle              | Field label                 | Machine name                     | Field type         | Required | Cardinality | Form widget                           | Trans
Nope - my bad

2020-12-04 07:17 UTC, swirtSJW commented
Pulling this local to resolve conflict and test

2020-12-04 08:30 UTC, swirtSJW commented
Mime type gts picked up automtically.
![image](https://user-images.githubusercontent.com/5752113/101140497-0e5fb880-35e1-11eb-8658-61223910f403.png)

2020-12-04 08:31 UTC, swirtSJW commented
Am running into this where the widget does not get set on config... we have run into this before.  will have to set it by hand.

2020-12-04 10:19 UTC, swirtSJW commented
@ethanteague  I resolved the conflicts on this but then I needed to force push to your branch and didn't have perms for that so I opened up https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3631

There are a couple issues with it though.   
 1. I can not get the widget for choosing the file to work despite changing  the widget
![image](https://user-images.githubusercontent.com/5752113/101149423-ebd39c80-35ec-11eb-9db1-37bd2c943f41.png)

 2   There are js issues related to hiding fields that prevent node saving. 
![image](https://user-images.githubusercontent.com/5752113/101149404-e5ddbb80-35ec-11eb-8c8f-9696668b8e1b.png)

3. The toggling logic is not surviving node save.  I narrowed it down to it is working on prod, but not on staging.  So it was either something I introduced with the tinkering I did on Kaises PR that merged.

I need sleep.

2020-12-04 10:53 UTC, swirtSJW commented
It is something about these two fields... in the toggle logic.   
![image](https://user-images.githubusercontent.com/5752113/101155284-e417f600-35f4-11eb-91fd-eed1cd324a9a.png)

If I toggle them on and put some text in them,   things save fine and the toggle logic persists too.

2020-12-04 13:50 UTC, closed without merging