VACMS_3616: Add html table field html removal script.
department-of-veterans-affairs/va.gov-cms pull request #3627
Opened 2020-12-03 20:10 UTC by ethanteague

## Description
See #3616 

## Testing done
`lando drush php-script VACMS-3616-remove-tablefield-tags-2020-12.php --script-path=/app/scripts/content`

## QA steps
Run the above script, and spot check the hours fields on the following pages:
- node/603/edit
- node/605/edit
- node/1023/edit
- node/478/edit

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-12-04 18:52 UTC, swirtSJW requested changes
One suggestion.  The rest looks great.

2020-12-04 18:52 UTC, swirtSJW commented on scripts/content/VACMS-3616-remove-tablefield-tags-2020-12.php
> +      $revisions['processed'] = $revisions['processed'] + 1;
In the spirit of assume nothing:  Right here you are assuming something was processed when it may not have been.  update()->execute() returns a count of the number of rows affected.   So it would be good to use that to report what the actual results were.
```suggestion      
       $updated_count = $query->execute();
      if (!empty($updated_count)){
        $revisions['processed'] = $revisions['processed'] + $updated_count;
      }
```

2020-12-04 18:56 UTC, swirtSJW commented on scripts/content/VACMS-3616-remove-tablefield-tags-2020-12.php
> +      $revisions['processed'] = $revisions['processed'] + 1;
Testing this locally we get the expected results... but now we can trust them 
![image](https://user-images.githubusercontent.com/5752113/101203307-768db900-3638-11eb-9ec5-6144fa993a1a.png)

2020-12-04 19:14 UTC, ethanteague commented
Great suggestion, @swirtSJW - committed.

2020-12-04 19:37 UTC, swirtSJW commented
Test passing locally   Cleared for launch

2020-12-04 19:38 UTC, swirtSJW approved these changes

2020-12-04 19:39 UTC, merged

2020-12-07 20:49 UTC, olivereri commented
modified command for env:
`source /etc/sysconfig/httpd; /usr/local/bin/drush php-script ../scripts/content/VACMS-3616-remove-tablefield-tags-2020-12.php`

Output:
```
SUCCESSFULLY connected to drupal database. Beginning process...

There are 247 paragraph__field_facility_service_hours to be processed.
>>> Successfully processed 247 of 247 paragraph__field_facility_service_hours updates.
There are 489 paragraph_revision__field_facility_service_hours to be processed.
>>> Successfully processed 489 of 489 paragraph_revision__field_facility_service_hours updates.
There are 1315 node__field_facility_hours to be processed.
>>> Successfully processed 1315 of 1315 node__field_facility_hours updates.
There are 267982 node_revision__field_facility_hours to be processed.

>>> Successfully processed 267982 of 267982 node_revision__field_facility_hours updates.

```