VACMS-3436: Improves link experience on help center pages.
department-of-veterans-affairs/va.gov-cms pull request #3637
Opened 2020-12-04 19:07 UTC by ndouglas

## Description

See #3436.

I have a `preg_replace()` in the hook that will remove leading occurrences of `Download ` from the link title.  I know that shouldn't be there longterm, but I haven't yet looked to see how many links are affected by this or discussed when this will be manually removed from existing items.

I also haven't really poked around in the other ways in which the `downloadable_file` paragraph can be used, so I haven't found any potentially problematic scenarios that might be present elsewhere.  I might need to make the string processing for the title more robust.

## Testing done
Forthcoming.  I'll add a Behat test or two on Monday.

## Screenshots
<img width="667" alt="Screen Shot 2020-12-04 at 1 26 42 PM" src="https://user-images.githubusercontent.com/1318579/101200489-5d830900-3634-11eb-91cd-8673ec91da1a.png">

## QA steps

As a user with permission to view help center pages:
1. View a node with a `downloadable_file` paragraph referencing a file.
1. Then validate Acceptance Criteria from issue #3436:
- [ ] remove the option to add "Video" from "Link to file or video" paragraph and rename it to "Link to file".
- [ ] introduce a template for "Link to file" paragraph that renders a link to file w/ an icon and using "Link text" as link text and file url as `href` attribute in a link while preserving a file type icon as shown on the image above.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

2020-12-08 12:22 UTC, oksana-c commented on config/sync/field.field.paragraph.downloadable_file.field_media.yml
> +label: 'Link to a file'
per ACs - paragraph config should not be changing in this PR

2020-12-08 12:23 UTC, oksana-c commented on config/sync/paragraphs.paragraphs_type.downloadable_file.yml
> +label: 'Link to file'
same - not changing paragraph config

2020-12-08 13:18 UTC, oksana-c requested changes
I know this is in Draft still, but figured I'll note a few things:

1. The download link is empty for Media:File (see screenshot in comments)
2. The file extension is missing for Media:File and Media:Image. e.g. `(PDF)`
3. Video remains as an option for "Link to file or video" paragraph. Let's revert paragraph config that unsets video and changes paragraph's name
4. NEW: We'll need distinct template logic for `documentation_page` content type and other content types when it comes to rendering Media:Video (see comment on the template file)

Let's zoom if it's easier to run thru all these IRL...  just called zoom IRL 🤔

2020-12-08 13:18 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +        if (!empty($fid)) {
wondering if we could skip some of these calls/preprocessing by setting the rendered entity format to "Download link"

<img width="1407" alt="Screen Shot 2020-12-08 at 6 02 22 AM" src="https://user-images.githubusercontent.com/16477724/101487488-7aad2580-391b-11eb-9d31-18d0b9669234.png">

We also need to have a file mime type displayed in caps for files and images only, not for videos

---

We're also missing File links for Media:File
<img width="1593" alt="Screen Shot 2020-12-08 at 6 09 21 AM" src="https://user-images.githubusercontent.com/16477724/101488071-57cf4100-391c-11eb-8bf4-a1c5856e3438.png">

2020-12-08 13:18 UTC, oksana-c commented on docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--downloadable-file--documentation-page.html.twig
> +    <span {{ media_object.attributes }}>
looks to me that we could omit this extra span and move `{{ media_object.attributes }}` to the link markup. The icon then would be set in `&::before` selector

2020-12-08 13:28 UTC, ndouglas commented on config/sync/field.field.paragraph.downloadable_file.field_media.yml
> +label: 'Link to a file'
Yeah, I thought I changed that back but must've not exported config 🤦

2020-12-08 20:56 UTC, ndouglas commented
The fourth Behat test will fail ATM because there're no `downloadable_file` paragraphs with videos that aren't attached to `documentation_page` nodes.  The modal dialog seems to break BeHat's ability to gracefully test this sort of operation, so I'm going to have to fiddle with possible solutions tomorrow.

2020-12-09 13:57 UTC, ndouglas commented
@oksana-c @acrollet 

Do you have any thoughts about testing this fourth situation (non-`documentation_page` node with `downloadable_file` video)?  

I see ~three~ ~four~ five options:

1) use [this](https://github.com/dennisinteractive/behat-drupal-paragraphs) to create nodes with paragraphs with specific structure and content.  However, it hasn't been updated in a couple years and it's currently not installable with Composer (haven't dug into why, but seems like a bad sign).  This would probably be very useful in other tests.

2) create dummy content on prod so the DB has something to test against.  I dislike this and I don't think it's scalable, but it's fast.

3) Try to get the test working by creating a node via pushing buttons and such in BeHat.  This was the approach I used yesterday and it's not great -- the modal dialog inserts a paragraph (of the wrong type) as soon as the "Add Content block" button is pushed, which I think is because of the Goutte driver and the way modal dialogs are done in Drupal.  This is a lousy and fragile way to do things, overall, and it's a major PITA to write tests this way.

4) Fork or rewrite `dennisinteractive/behat-drupal-paragraphs` for our own use, since it looks abandoned.

5) Write the test(s) in something other than BeHat.

2020-12-09 14:08 UTC, acrollet commented
My vote is to look into whether we could use cypress for our e2e testing now that we're close to having tugboat up. It's a much nicer framework to use and the tests run on a full browser, so it's much closer to the actual environment. I have a working branch with cypress-axe that I'll dig up when I'm online.

2020-12-09 14:59 UTC, acrollet commented
Here's the branch: https://github.com/acrollet/va.gov-cms/tree/VACMS-3289-implement-cypress-axe

2020-12-09 15:19 UTC, acrollet commented
ha @ndouglas I was about to make a separate PR for the stylelint issues - I'm guessing it was something that got merged around the same time as the stylelint PR.

2020-12-09 15:20 UTC, ndouglas commented
nah, it was my crap (s)css

2020-12-09 15:21 UTC, acrollet commented
haha meh it's a matter of opinion... 😄

2020-12-09 19:36 UTC, ndouglas commented
@acrollet I dig Cypress, and would way rather write JS than Gherkin or whatever, but I guess it's a bit much to roll into this PR.  

I'd love to make it a top priority, though, because it's pretty aggravating to not have a clean way (AFAICT) of writing tests for this stuff.

2020-12-09 20:06 UTC, acrollet commented
@ndouglas we'd certainly have to do it over time, but I'd like to have us consider writing new e2e tests in cypress. [this](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor) could potentially help with migration...

I think we have an open issue about e2e testing tools somewhere.

2020-12-09 20:21 UTC, ndouglas commented
a'ight, I'ma do it -- I'm not thinking up any faster solutions tbh, and I'm on the clock 🕞

2020-12-09 21:14 UTC, acrollet commented
Sorry, I should have been more clear that we probably need a team-level decision on this.￼ I know that Elijah didn't want to introduce Cypress until after tugboat is up and running. The solution for this issue might be to test manually and add a follow on to automate the test. cc oksana-c

2020-12-09 21:17 UTC, ndouglas commented
too late now rollett, I'm a rootin'-tootin' [ranagazoo](https://www.youtube.com/watch?v=qLrnkK2YEcE)

2020-12-10 00:58 UTC, oksana-c reviewed
there ain't no stoppin' ya Nate! 

I agree w/ @acrollet, we need to hold off on Cypress. Glad you both got to experiment w/ it ahead of time though 👍  
Let's remove video tests, I validated the ACs manually in DevShop, so once vid tests are removed and build is passing - let's get this one merged.
Added a few inline suggestions, some of which you can commit right in github UI.
Links look great 💪

2020-12-10 00:58 UTC, oksana-c commented on docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--downloadable-file--documentation-page.html.twig
> + * Default theme implementation to display a paragraph.
```suggestion
 * VAGOVADMIN theme implementation to display a `downloadable_file` paragraph 
 on `documentation_page` nodes.
```

2020-12-10 00:58 UTC, oksana-c commented on docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--downloadable-file.html.twig
> + * Default theme implementation to display a paragraph.
```suggestion
 * VAGOVADMIN theme implementation to display a `downloadable_file` paragraph.
```

2020-12-10 00:58 UTC, oksana-c commented on docroot/themes/custom/vagovadmin/assets/scss/styles.scss
> +}
```suggestion
.downloadable-file-link {
  padding-left: 20px;
  position: relative;

  &::before {
    background-repeat: no-repeat;
    background-size: 16px 16px;
    content: '';
    display: inline-block;
    height: 16px;
    padding-right: 4px;
    width: 16px;
  }
}
```

couldn't help to make it pixel perfect..

2020-12-10 00:58 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $parent_bundle = $paragraph->getParentEntity()->bundle();
```suggestion
```

unused variable

2020-12-10 00:58 UTC, oksana-c commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +use Drupal\Core\Template\Attribute;
A-Z sort on use statements would be nice

2020-12-10 00:58 UTC, oksana-c commented on config/sync/paragraphs.paragraphs_type.downloadable_file.yml
> -    description: "Allowed file types: \r\nFor images: png, gif, jpg, jpeg \r\nFor files: pdf, doc, docx, ppt, xlsx (pdf is preferable)\r\nVideo support coming soon!"
let's bring this one back 

`description: "Allowed file types: \r\nFor images: png, gif, jpg, jpeg \r\nFor files: pdf, doc, docx, ppt, xlsx (pdf is preferable)\r\nVideos can be selected from the library."`

2020-12-10 18:25 UTC, oksana-c commented on docroot/themes/custom/vagovadmin/assets/scss/styles.scss
> +    width: 16px;
```suggestion
    background-repeat: no-repeat;
    background-size: contain;
    content: '';
    display: block;
    height: 16px;
    position: absolute;
    top: 2px;
    width: 16px;
```

2020-12-11 01:20 UTC, oksana-c approved these changes

2020-12-11 01:24 UTC, oksana-c commented
✅ ready to merge once tests pass.

@rachel-kauff , this PR once deployed will add file extensions to link automatically, so you'll need to update some link titles in CMS Help Center that have file ext intentionally added. example on /help/session-1-cms-orientation page 
<img width="465" alt="Screen Shot 2020-12-10 at 6 23 04 PM" src="https://user-images.githubusercontent.com/16477724/101849375-cd056680-3b14-11eb-9f02-367148e4faf1.png">

2020-12-14 14:51 UTC, oksana-c approved these changes

2020-12-14 14:51 UTC, merged