VACMS-3633 Refactor Front end web build
department-of-veterans-affairs/va.gov-cms pull request #3677
Opened 2020-12-09 18:05 UTC by indytechcook

## Description

See #3633. This contains a refactor of how the environment (local/tugboat/brd/devshop) difference are handled.  It also contains calling a composer command for lando and tugboat builds.

## Testing done

* Go to `admin/content/deploy` and see if the messages match the environment.  
* Press the `release content` button.  
  * On lando/tugboat this will take a long time as it builds synchronously.
  * On devshop this will trigger a new devshop tasks.
  * on dev/stage/prod it will trigger a jenkins job:  this can't be tested until merge.
* Go to a node page and make sure the deploy status still work.
* Go to a node page and verify preview link works.  This will work on local also.

![PTSD Treatment | Veterans Affairs 2020-12-09 12-56-26](https://user-images.githubusercontent.com/121603/101668087-1de66380-3a1e-11eb-8b21-99d62adf495b.png)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-12-09 19:20 UTC, acrollet requested changes
None of these comments are critical, we can address in a follow-on if timing is an issue for tugboat.

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +   * Is this on Tugboat?
```suggestion
   * Is this on Local?
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +   *   Is this on Tugboat?
```suggestion
   *   Is this on Local?
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +   * Get the environment type.
Is this getting the environment type, name or id? The constant suggests that type would be the correct terminology?

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +   * Should the front end be triggered?
```suggestion
   * Should the front end build be triggered?
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +   *   Should the front end be triggered?
```suggestion
   *   Whether the front end build should be triggered.
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +   *   Is this CLI.
```suggestion
   *   Current process is CLI.
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
> +   * The URL the the front end.
```suggestion
   * The URL for the front end.
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
> +   * Should this environment trigger an front content deploy?
```suggestion
   * Should this environment trigger a frontend content deploy?
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
> +   * This controls if content updates shoudl trigger the
```suggestion
   * This controls whether content updates should trigger the
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
> +   * front end deploy?
```suggestion
   * front end deploy.
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
> +   * @reutrn bool
```suggestion
   * @return bool
```

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +        $this->logger->warning('Retry site build - attempt #' . $retry);
nitpicky but should this use a placeholder?

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +        $this->logger->warning('Retry site build - attempt #' . $retry);
Thinking about it more, is this logging useful? Not sure if we care if there's one retry and the request then succeeds?

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +        $message = t('Site rebuild failed with status code {:status_code} {:reason_phrase} and URL {:url}.', $vars);
Should we inject the translation service rather than doing this procedurally?

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +    $time_raw = \Drupal::service('date.formatter')
use DI?

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/DevShop.php
> +    return \Drupal::request()->getBasePath() . '/static';
use DI?

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/DevShop.php
> +    return \Drupal::request()->getBasePath() . '/static';
Withdrawing this comment since devshop is going away.

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
> +    return \Drupal::request()->getBasePath() . '/static';
Use DI?

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
> +    return \Drupal::request()->getBasePath() . '/static';
Use DI?

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
> +      $this->environmentDiscovery->triggerFrontendBuild();
<img src="https://media0.giphy.com/media/Joybb4YVIpf4NE9x8k/giphy.gif"></img>

2020-12-09 19:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
>        $message = t('You cannot trigger a build in this environment. Only the DEV, STAGING and PROD environments support triggering builds.');
Is this true? Looks like tugboat is supported.

2020-12-09 19:22 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
> +    return \Drupal::request()->getBasePath() . '/static';
I was having issues getting DI to work with a plugin.  I need to follow up.

2020-12-09 21:59 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +        $this->logger->warning('Retry site build - attempt #' . $retry);
Yeah, this was 100% copy/past code from `tome`

2020-12-09 22:13 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +   * Get the environment type.
This is deprecated.  The `CMS_ENVIRONMENT_TYPE` isn't really used anymore.

2020-12-10 14:11 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
> +    return \Drupal::request()->getBasePath() . '/static';
I figured this out.  it was super easy, I'm working on it now.

2020-12-10 17:40 UTC, merged