VACMS-000: Consolidate multiple clp panel prs.
department-of-veterans-affairs/va.gov-cms pull request #3714
Opened 2020-12-11 15:42 UTC by ethanteague

## Description
Consolidates multiple clp panel pr's / logic:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3636
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3666
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3676

## Testing done
Visual / behat

## QA steps
Lot going on here - manual qa by @kevwalsh will be required.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-12-11 16:27 UTC, swirtSJW reviewed
Overall looks good..  One super minor suggestion and looks like some cleanup is needed for linting failure tests.

2020-12-11 16:27 UTC, swirtSJW commented on config/sync/field.field.node.campaign_landing_page.field_clp_connect_with_us.yml
> +description: 'Choose an administration from this list to display a set of social media and links to email lists'
```suggestion
description: 'Choose an administration from this list to display a set of social media and links to email lists.'
```

2020-12-11 20:50 UTC, kevwalsh requested changes
Form validation feedback looks pretty good, although it's weird that it gives a numerical value for one fail, but not others. Not a deal-breaker
![Create_Campaign_Landing_Page___VA_gov_CMS_and_Slack___cms-team___Digital_Service___VA___2_new_items_and_CivicActions_-_Calendar_-_Week_of_December_7__2020_and_Create_VAMC_System___VA_gov_CMS](https://user-images.githubusercontent.com/643678/101951502-190fe400-3bc5-11eb-89c1-1262f5a249f3.jpg)

Defect: If i add a node title and click Save without filling out a single field, nothing happens. i assume form validation is somehow choking. No feedback from the UI. 

Video panel defect:  this should have a red asterisk. Form validation doesn't seem to be checking, either. 

![Create_Campaign_Landing_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/101953386-414d1200-3bc8-11eb-8b82-039fcd119784.jpg)


Stories panel defect: this should have a red asterisk. Form validation doesn't seem to be checking, either. 

![Create_Campaign_Landing_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/101950815-e31e3000-3bc3-11eb-893d-7330d27a85ff.jpg)

Defect: Downloadable resources should have a red asterisk. Form validation doesn't seem to be checking, either. 

![Create_Campaign_Landing_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/101951010-414b1300-3bc4-11eb-91f4-06d7e895971f.jpg)

@swirtSJW At some point we may need to decide that form validation issues should be considered as follow-ups. The content model is looking great we want this in Monday's deploy for content entry starting Tuesday.

2020-12-11 21:44 UTC, ethanteague commented
@kevwalsh this doesn't match what is building for me locally. I'll inspect.

2020-12-11 22:44 UTC, ethanteague commented
@swirtSJW @kevwalsh fixed all items with one exception:  ```Defect: If i add a node title and click Save without filling out a single field, nothing happens. i assume form validation is somehow choking. No feedback from the UI.```
Like you suspected, this is happening b/c html form elements in various panels that have js / behavior validation are empty. The only way I can think of to remedy this is to undo the behaviors logic, and create new constraint handlers for these fields, like I'm doing on paragraphs. Essentially, server side validation to replace browser validation.

2020-12-14 14:52 UTC, kevwalsh approved these changes
QA pass!

2020-12-14 15:28 UTC, swirtSJW approved these changes

2020-12-14 15:28 UTC, merged