VACMS-3682 push facility covid service status
department-of-veterans-affairs/va.gov-cms pull request #3794
Opened 2020-12-16 23:04 UTC by swirtSJW

## Description
This is not ready for  merge.  Just a work in progress.
## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-12-21 19:26 UTC, kaise-lafrai requested changes
Small update to the code comment block that you mentioned during our call.

2020-12-21 19:26 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
>   */
Code comment block should say `_update` and not `_insert`

2020-12-22 20:08 UTC, kaise-lafrai approved these changes
All testing steps passed. All changes requested on code looks great. 

Needs rebase and a look into why behat tests are failing.

2020-12-22 23:01 UTC, acrollet submitted a review, later dismissed
The code all makes sense to me, these are pretty much just suggestions around readability :-)

2020-12-23 14:53 UTC, swirtSJW commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
> +    $defaultRevisionIsPublished = (isset($this->facilityService->original) && ($this->facilityService->original instanceof EntityInterface)) ? (bool) $this->facilityService->original->status->value :
Good point, instanceof does not throw an error, but php throws a notice if you try to reference something that doesn't exist.  $this->facilityService->original  is not always present.

2020-12-23 15:12 UTC, swirtSJW commented on docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
> +  if ($entity->bundle() === 'health_care_local_health_service') {
hook_entity_presave would allow it to be done in one spot, however it would have to make an assumption about the save happening.  If something jiggers with the data on presave, we send data that may or may not match based on when it occurred in the hook stack. Also if something aborts during presave then the save doesn't happen but we would have just pushed data to lighthouse that was never saved.  Also the first batch of these will be coming in via migration,

The check prior to the call is just to keep this from firing up the service for every single save or update.  I assume there is a load to calling a service even if the service does nothing in response... though I have never tested that assumption.  There is no need to throw an exception if the wrong bundle ends up being passed in.  Failing silently is enough and faster than logging an exception.

2020-12-23 15:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
> +    if (empty($this->errors) && $this->shouldPush()) {
Good call.  The errors were already checked.... and the shouldPush check could come before getPayload is called.  I mentally grapple... and ultimately waffle between making the methods self-defensive and making the calls to to methods defensive.  I am sure there is a name to one pattern or the other....and I need to pick one and stay consistent.

I like making the methods self defensive because then somebody could move the call to the method and still get desired results.. but it does extend the concern of the method too far.  I'll rework this.

2020-12-23 15:27 UTC, swirtSJW commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
> +      $this->setFacility();
Yah largely these were for initial testing but I think the errors are good to know in their entirety.  Those items  are in required fields right now so they should be there.  However the initial round of these are coming in via migration and if one or more of them are failing it helps to know them all at once.

2020-12-23 15:42 UTC, swirtSJW commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
> +    if (($entity->getEntityTypeId() === 'node') && ($entity->bundle() === 'health_care_local_health_service')) {
Ideally yes, but we can't execute isPushable until we have the this->serviceTerm->id() which can't be obtained until we have  $this->systemService.  We could dig for it earlier, but I am not sure what that would gain.  All the calls to setFacility, setSystemService, setServiceTerm... don't really do anything.  They just assign object references to make things easier to read and validate that they exist.   In order to make isPushable callable higher up, we'd have to move all the calls to `set___`  into isPushable.

2020-12-24 16:11 UTC, acrollet commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
> +    $defaultRevisionIsPublished = (isset($this->facilityService->original) && ($this->facilityService->original instanceof EntityInterface)) ? (bool) $this->facilityService->original->status->value :
ah, good call, forget I spoke!

2020-12-24 16:36 UTC, acrollet commented on docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
> +  if ($entity->bundle() === 'health_care_local_health_service') {
Makes sense, thanks for the explanation!

Long-term it could be cool to look at something like https://www.drupal.org/project/bundle_override when we're extending the behavior of single bundles - it would be neat to implement [EntityBase::postSave](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityBase.php/function/EntityBase%3A%3ApostSave/8.9.x) in a healthCareLocalHealthService class for this use case.

2020-12-24 16:40 UTC, acrollet commented on docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
> +    if (($entity->getEntityTypeId() === 'node') && ($entity->bundle() === 'health_care_local_health_service')) {
makes sense!

2021-01-08 23:06 UTC, swirtSJW commented
Investigating odd error from behat
 ┃ | "content_editor" | "health_care_local_health_service" |                    
 ┃         Fatal error: Call to a member function get() on null

2021-01-09 02:03 UTC, swirtSJW commented
Behat test failure was due to behat perms test not filling in required entity references.   I added a couple defensive checks to keep from failing catastrophicaly.

2021-01-09 02:43 UTC, merged