VACMS-3840: Add new leadin field to services.
department-of-veterans-affairs/va.gov-cms pull request #3843
Opened 2020-12-21 19:54 UTC by ethanteague

## Description
See #3840 

## Testing done
Visual/Behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/102816537-2f275c80-439c-11eb-8f9d-62a38eb2f7dd.png)

## QA steps
As an administrator, go to `admin/structure/types/manage/support_service/form-display` and visually verify that `Appointment lead-in text` appears identical to screenshot (when cog is clicked)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-12-21 20:45 UTC, swirtSJW requested changes

2020-12-21 20:45 UTC, swirtSJW commented on config/sync/field.field.node.support_service.field_health_service_appt_leadin.yml
> +    value: 'Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first.'
This default is not supposed to be in here.  The default is going to live on the front end and not live as a value in each node.

2020-12-21 21:04 UTC, ethanteague commented on config/sync/field.field.node.support_service.field_health_service_appt_leadin.yml
> +    value: 'Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first.'
D'oh - my bad, @swirtSJW. Updated.

2020-12-22 17:50 UTC, swirtSJW approved these changes

2020-12-22 17:50 UTC, merged

2020-12-28 16:10 UTC, swirtSJW commented
Kev points out this is on the wrong content type.  Rolling this back.

2020-12-28 16:14 UTC, swirtSJW commented
Reverting with https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3863