VACMS 3509: Video embeds for CMS Help Center pages
department-of-veterans-affairs/va.gov-cms pull request #3845
Opened 2020-12-21 21:18 UTC by ndouglas

## Description

See #3509 .

## Testing done
Manual tests so far.  I'll add some Behat tests.

## Screenshots
<img width="821" alt="Screen Shot 2020-12-21 at 4 15 31 PM" src="https://user-images.githubusercontent.com/1318579/102822832-c8a83b80-43a7-11eb-9eb2-2da59f1606df.png">
<img width="884" alt="Screen Shot 2020-12-21 at 4 15 23 PM" src="https://user-images.githubusercontent.com/1318579/102822828-c7770e80-43a7-11eb-8d9a-dcc2e7f62d3a.png">

## QA steps
As a user with the ability to view and/or create CMS Help Page nodes:
1. Create or edit a node so that it has video media in the Main Content 
1. Then validate Acceptance Criteria from issue #3509:
    - [ ] Media:Video has a new view mode enabled "User Guides"
    - [ ] Media:Video "User Guides" view mode  is configured as follows:
        * displayed fields:
           * Video URL | Label - hidden | format - Video - embed video responsive
           * Name | Label - hidden | format - plain text
           * Duration | Label - inline | format - Natural human languages + remove the `and` separator
           * Description | Label hidden | Plain text
    - [ ] Paragraph "Media list- videos" has a new view mode enabled "User guides" w/ following settings:
        * Section Header: Label - hidden; format - plain text
        * Videos: Label hidden; format - Rendered Entity w/ view mode - User Guides
    - [ ] new template is added for `paragraph--media-list-videos--user-guides.html.twig` that renders field_section_header as an `h2` heading
  - [ ] CMS Help Page content type - field_content_block `/admin/structure/types/manage/documentation_page/fields/node.documentation_page.field_content_block` allows `Media list - Videos` paragraph type as an option

### Definition of Done
- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

2020-12-22 16:49 UTC, ndouglas commented
@oksana-c @rachel-kauff [Here](https://pr3845-bjte00jbyxkzt6e6z8ghrmbwpfynf3vs.ci.cms.va.gov/node/6884/latest) is a preview that hopefully contains enough information to review.  I added the duration and description fields for the two media items.

2020-12-22 17:20 UTC, oksana-c requested changes
video list layout looks great! I left a comment re: downloadable file paragraph changes

duration field label could use some styling. I pasted some scss below (warning: untested code). The result should look as shown on the screenshot.
Let's make sure that we're only targeting the duration field label on a media list paragraph in user guides view mode.

file to add scss - docroot/themes/custom/vagovadmin/assets/scss/user_guides.scss

#block-vagovadmin-content {
  .paragraph--type--media-list-videos {
    &.paragraph--view-mode--user-guides {
      .field--name-field-duration {
        .field__label {
          font-size: 16px;
          text-transform: capitalize;
        }
      }
    }
  }
}

<img width="457" alt="Screen Shot 2020-12-22 at 10 19 21 AM" src="https://user-images.githubusercontent.com/16477724/102915510-2cca0e80-443f-11eb-8d29-8b4d01ee5eda.png">

2020-12-22 17:20 UTC, oksana-c commented on docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--downloadable-file--user-guides.html.twig
> +      {{ content.field_media }}
we are not changing downloadable file paragraph config in this PR. The only paragraph type affected by ACs is "Media list - Videos" in User Guides view mode. apologies if that wasn't clear.

2020-12-22 17:22 UTC, ndouglas commented on docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--downloadable-file--user-guides.html.twig
> +      {{ content.field_media }}
Ah, okay.  Not a problem 😄

2020-12-23 01:03 UTC, oksana-c commented
added minor styling tweaks. here's the result.
✅ good to merge once we get thumbs up from @rachel-kauff and the build is green


<img width="646" alt="Screen Shot 2020-12-22 at 6 01 02 PM" src="https://user-images.githubusercontent.com/16477724/102947133-d29d6d80-447f-11eb-948a-8614a65cdfbf.png">

2020-12-23 01:03 UTC, oksana-c approved these changes

2020-12-23 16:28 UTC, ndouglas commented
Tugboat hasn't been building the previews for this PR automatically, for some reason, but it should be current as of now.

2020-12-29 23:22 UTC, rachel-kauff commented
@ndouglas cc: @oksana-c Just reviewed, looks great. Thank you so much for your work on this!

2020-12-30 16:36 UTC, merged