VACMS 3124: Have CMS notify Slack if content release fails.
department-of-veterans-affairs/va.gov-cms pull request #3862
Opened 2020-12-28 15:03 UTC by ndouglas

## Description

See #3124.

I'm pretty tentative about this, because I haven't touched BRD before.

I have some questions about this:

1. #3124 mentions "notify cms-team", but AFAICT we don't have a specific webhook URL for posting to the #cms-team channel.  I'm just reusing the #cms-notifications channel webhook URL, but wanted to mention that this differs from the issue's ACs in case there's something we need to discuss there.
2. I looked and didn't find a better way of determining whether we're on prod, so I copied and modified some of the logic in docroot/modules/custom/va_gov_build_trigger/src/Form/PreviewForm.php .  I feel like this should be centralized somewhere, maybe in docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php, and I actually started doing that, but wanted to get some feedback on that idea first.

## Testing done
None, lol.  Mostly just wanted to get eyes on this to see if this approach is sound and if everyone is okay with this approach.

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

2020-12-28 16:58 UTC, ndouglas commented
@acrollet @swirtSJW If you guys have some free time, I'd appreciate some feedback on this approach.  I'd like to add some tests to this (which I think will involve some slight refactoring), but I wanted to get a little buy-in on whether it's heading in the right direction or if we need to have a wider discussion about how and to whom the notification is sent, how we determine prod, etc, or if I'm just flat-out ignorant about something.

2020-12-28 17:52 UTC, acrollet commented
As far as determining whether we're on prod goes, I'm seeing at least three approaches in use:

- Inspecting `$config['environment_indicator.indicator']['name']`
- hostname inspection
- The `CMS_ENVIRONMENT_TYPE` environment variable

For my $.02, I'd be in favor of standardizing on one approach and having something like a `isProduction()` method in `EnvironmentDiscovery`...

CC @indytechcook

2020-12-28 17:53 UTC, ndouglas commented
_Definitely_ think we should standardize on something.  And I'm happy to roll that job into this PR, of course.

2020-12-28 19:17 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +  public const VAGOV_PRODUCTION_HOSTS = [
If we are in the plugin then we are in BRD.  No need to add any more checks.

2020-12-28 19:21 UTC, ndouglas commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +  public const VAGOV_PRODUCTION_HOSTS = [
I don't understand.  This isn't to check whether we're in BRD, but to distinguish between BRD environments.  Am I lost?

2020-12-28 19:21 UTC, indytechcook commented
We should do another plugin for `Production`

2020-12-28 19:25 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +  public const VAGOV_PRODUCTION_HOSTS = [
Add a plugin for `Production`

2020-12-28 19:37 UTC, indytechcook commented
> Inspecting $config['environment_indicator.indicator']['name']

This is just a label and not used anywhere else right?

> The CMS_ENVIRONMENT_TYPE environment variable

This is only used in `post_api` code now.  This should be deprecated in favor of the `EnvironmentDiscovery` code.

In the current design, the `EnvironmentDiscovery` plugins are more for the frontend web build.  I do like the idea of expanding the usage but we need to be careful about the plugin classes doing to much.  As the `Environment` plugin grows, it should start to become a collection of classes where it would have a `getWebBuilder` method and `getWebBuildForm` method.

2020-12-28 19:44 UTC, ndouglas commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +  public const VAGOV_PRODUCTION_HOSTS = [
Gotcha.  I'll do it that way.

2020-12-28 20:45 UTC, ndouglas commented
Warning: code is untested.  LMK if this is more-or-less what you had in mind.  I read through the BRD code, contemplated a couple different ways of refactoring it, and, uh, did this.  If you wanna pick this apart on Twitch or whatever, that's fine with me -- there are some places with which I'm not entirely happy, but I didn't want to go _too_ wild.

2020-12-28 21:28 UTC, indytechcook requested changes
While this code refactor/changes if fine and dandy, this not the correct place to handle this change.  The Jenkins job itself is where the content job runs.  This will only notify slack if Jenkins is down, not if the job fails.

2020-12-28 21:28 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +    if ($build_type === 'brd' && $this->isProd()) {
the build type is set in the corresponding settings file, in this case `settings.prod.php`.   Let's not override it anywhere.

2020-12-28 21:28 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +    return !empty($this->request) && in_array($this->request->getHost(), static::VAGOV_PRODUCTION_HOSTS);
Let the plugin define this. Add a `isProd() : bool` to the interface and default it to false in `EnvironmentPluginBase`

2020-12-28 21:28 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
> +    $handler_stack = HandlerStack::create();
Ideally, you would inject this also but we are looking a larger refactor of this logic later so this is fine for now.

2021-01-04 17:23 UTC, swirtSJW commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +    'prod.cms.va.gov',
Most of our other logic around the site uses the environment name.   This would be a switch to using host detection.  Can this be made to use environment names for consistency of approach?

2021-01-05 14:42 UTC, swirtSJW commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +    'prod.cms.va.gov',
Ignore this... somehow I missed all the other discussion on this topic on this PR.

2021-01-06 15:35 UTC, closed without merging