VACMS-3791: built front-end PRs
department-of-veterans-affairs/va.gov-cms pull request #3864
Opened 2020-12-28 17:33 UTC by acrollet

## Description

See #3791 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-12-28 23:03 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
> +    return $this->getEnvironment()->getBuildTriggerFormClass();
@indytechcook let me know what you think of this approach for overriding the Build Trigger form. I like that it lets us dump the case statement and use inheritance on the form class...

2020-12-29 15:07 UTC, indytechcook requested changes

2020-12-29 15:07 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Routing/RouteSubscriber.php
> +      if ($buildTriggerFormClass = $this->environmentDiscovery->getBuildTriggerFormClass()) {
Interesting, i like this approach.

2020-12-29 15:07 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
> +    return '\Drupal\va_gov_build_trigger\Form\TugboatBuildTriggerForm';
Use `TugboatBuildTriggerForm::class` for class names in these plugins

2020-12-29 15:07 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
> +  public function triggerFrontendBuild($web_pr) : void;
Update this variable name since it's not just a PR right,  type hint it and add the doc block comment.

2020-12-29 15:07 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
> +      $request = $this->httpClient->get(
Can we use https://github.com/KnpLabs/php-github-api or will that guzzle version interfere with ours?

2020-12-29 15:11 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
> +      $request = $this->httpClient->get(
good question, I'll give it a shot!

2020-12-29 16:20 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
> +      $string = Unicode::strtolower($input);
The whitespace is automatically trimmed by some piece of the drupal autocomplete infrastructure. Glad you mentioned because I found out that this method is deprecated when I looked it up...

2020-12-29 19:36 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
> +      $request = $this->httpClient->get(
done - we should make sure to update version 3 once we're on PHP 7.2.

2020-12-29 19:47 UTC, acrollet commented
@indytechcook @ndouglas this is ready for another CR pass, however the preview environment won't work (at least without some manual jiggery-pokery) until #3875 is merged and we have a new base environment built on tugboat.

2020-12-30 14:37 UTC, indytechcook commented on composer.json
> -                "Possibly unnecessary logging in SchemaFactory::create(). https://www.drupal.org/project/schemata/issues/3190131": "https://www.drupal.org/files/issues/2020-12-28/schemata-remove-logg
Was this last one meant to be removed?

2020-12-30 14:38 UTC, ndouglas commented on composer.json
> -                "Possibly unnecessary logging in SchemaFactory::create(). https://www.drupal.org/project/schemata/issues/3190131": "https://www.drupal.org/files/issues/2020-12-28/schemata-remove-logg
yeah, don't remove that

2020-12-30 14:51 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
> +        $this->githubClient->authenticate($gh_token, NULL, Client::AUTH_HTTP_TOKEN);
Much nicer :). If you were going a more pure OOP route you would create an [adapter](https://designpatternsphp.readthedocs.io/en/latest/Structural/Adapter/README.html) or [factory](https://designpatternsphp.readthedocs.io/en/latest/Creational/SimpleFactory/README.html) class around the Github code so we don't have a hard dependency on another library.

2020-12-30 14:56 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
> +    $branches = explode(PHP_EOL, shell_exec("cd {$repo_root}/web && git ls-remote --heads origin | cut -f2 | sed 's#refs/heads/##'"));
I like the simplicity of this!  To make this method easier to test let's pull this logic out into a `GIT` or `Repo` class that knows how to work with git.  

Remember, this class is just a controller that knows how to format data for us in a web request.

2020-12-30 14:57 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentPluginBase.php
> +    if (is_numeric($front_end_git_ref)) {
Move this logic into the `Git` class also

2020-12-30 14:58 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
> +      preg_match("/.+\\s\\(([^\\)]+)\\)/", $front_end_branch, $matches)
Could you add a comment for those of us who are regex illiterate :)

2020-12-30 15:15 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
> +      preg_match("/.+\\s\\(([^\\)]+)\\)/", $front_end_branch, $matches)
will do :-) It's actually taken from [EntityAutocomplete::extractEntityIdFromAutocompleteInput](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21Element%21EntityAutocomplete.php/function/EntityAutocomplete%3A%3AextractEntityIdFromAutocompleteInput/8.9.x) - I decided against directly using the method in case its behavior changes in the future...

2020-12-30 15:39 UTC, acrollet commented on composer.json
> -                "Possibly unnecessary logging in SchemaFactory::create(). https://www.drupal.org/project/schemata/issues/3190131": "https://www.drupal.org/files/issues/2020-12-28/schemata-remove-logg
Yeah, I ran into some composer issues with that - the schemata module is not explicitly required in `composer.json` and composer was trying to pull in a newer version when I was adding the github api client. fixed :-)

2020-12-30 16:01 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
> +        $this->githubClient->authenticate($gh_token, NULL, Client::AUTH_HTTP_TOKEN);
@indytechcook The other thing I had thought about was creating a wrapper module that exposes the client as a service. I held off because we need to use an older version of the client until we're on PHP 7.2. What do you think would be best?

2020-12-30 16:09 UTC, indytechcook commented on docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
> +        $this->githubClient->authenticate($gh_token, NULL, Client::AUTH_HTTP_TOKEN);
Adding an adapter/wrapper would abstract the `GitHub` library implementation from our code.  The idea is that you would need to just update the adapter layer with the new version of the library and the rest of your code doesn't require any changes.  So the new service would have it's own interface which other code used and the service calls the `GitHub` library code directly.  This is a great example of why using an adapter would save us work in the long run.

2020-12-30 18:08 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
> +      if ($gh_token = getenv('GITHUB_TOKEN')) {
wrap in drupal settings variable?

2020-12-30 21:48 UTC, acrollet commented on tests/phpunit/FrontendBuild/BuildTriggerFormTest.php
> +<?php
@indytechcook ok, it's not at all obvious how to override Drupal site settings for a functional test, but I found a working approach - pushing this up for you to have a look and see if the approach makes sense to you before going further. The BRD test currently fails because the BRD class's call to `parent::__construct()` is not compatible with `EnvironmentPluginBase::__construct()`.

2020-12-31 14:14 UTC, indytechcook commented on tests/phpunit/FrontendBuild/BuildTriggerFormTest.php
> +<?php
This is great!

2021-01-04 14:58 UTC, indytechcook commented
### Testing without branch change on:

Release content button pressed:

![Jobs | VA gov CMS 2021-01-04 09-30-09](https://user-images.githubusercontent.com/121603/103545813-188b0600-4e70-11eb-8bcf-da57819b7374.png)


Queue in-process:
![image](https://user-images.githubusercontent.com/121603/103545766-0741f980-4e70-11eb-9fde-447a1336ec44.png)


Build Complete with no errors in logs.

![image](https://user-images.githubusercontent.com/121603/103546145-8a634f80-4e70-11eb-93e7-fab3d6baa0f9.png)


### Testing change in content:

Content Change:

![image](https://user-images.githubusercontent.com/121603/103546460-065d9780-4e71-11eb-896f-7926fd74b0aa.png)

Front end Before Build:

![image](https://user-images.githubusercontent.com/121603/103546519-1b3a2b00-4e71-11eb-94e1-420c90b6aac0.png)

Front end build after build:

![image](https://user-images.githubusercontent.com/121603/103547471-6d2f8080-4e72-11eb-9ba9-fb8946deb698.png)


### Testing branch change:

Testing changes from https://github.com/department-of-veterans-affairs/vets-website/pull/15500

Queued Job:

![image](https://user-images.githubusercontent.com/121603/103547957-11192c00-4e73-11eb-8651-533d60b666cb.png)


Before branch change:
![image](https://user-images.githubusercontent.com/121603/103547750-d0b9ae00-4e72-11eb-8844-4e87dd715fc2.png)

After Branch Change

There was an error in processing which I am fixing now: 

``` 
Notice: Undefined variable: token in Drupal\va_gov_consumers\Git\GithubAdapter->__construct() (line 49 of /var/lib/tugboat/docroot/modules/custom/va_gov_consumers/src/Git/GithubAdapter.php)
#0 /var/lib/tugboat/docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'Undefined varia...', '/var/lib/tugboa...', 49, Array)
#1 /var/lib/tugboat/docroot/modules/custom/va_gov_consumers/src/Git/GithubAdapter.php(49): _drupal_error_handler(8, 'Undefined varia...', '/var/lib/tugboa...', 49, Array)
#2 /var/lib/tugboat/docroot/modules/custom/va_gov_consumers/src/Git/GithubFactory.php(43): Drupal\va_gov_consumers\Git\GithubAdapter->__construct(Object(Github\Client), Object(Drupal\Core\Logger\LoggerChannelFactory))
#3 /var/lib/tugboat/docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php(58): Drupal\va_gov_consumers\Git\GithubFactory->get('department-of-v...', 'va_cms_bot_gith...')
#4 /var/lib/tugboat/docroot/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php(28): Drupal\va_gov_build_trigger\Controller\FrontEndBranchAutocompleteController::create(Object(Drupal\Core\DependencyInjection\Container))
#5 /var/lib/tugboat/docroot/core/lib/Drupal/Core/Controller/ControllerResolver.php(120): Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition('\\Drupal\\va_gov_...')
#6 /var/lib/tugboat/docroot/core/lib/Drupal/Core/Controller/ControllerResolver.php(72): Drupal\Core\Controller\ControllerResolver->createController('\\Drupal\\va_gov_...')
#7 /var/lib/tugboat/docroot/core/lib/Drupal/Core/Controller/ControllerResolver.php(88): Drupal\Core\Controller\ControllerResolver->getControllerFromDefinition('\\Drupal\\va_gov_...', '/admin/content/...')
#8 /var/lib/tugboat/docroot/vendor/symfony/http-kernel/HttpKernel.php(134): Drupal\Core\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#9 /var/lib/tugboat/docroot/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/lib/tugboat/docroot/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/lib/tugboat/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/lib/tugboat/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /var/lib/tugboat/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /var/lib/tugboat/docroot/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /var/lib/tugboat/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#20 {main}
```

2021-01-04 15:19 UTC, indytechcook commented on docroot/modules/custom/va_gov_consumers/src/Git/GithubAdapter.php
> +use Github\Exception\InvalidArgumentException;
```suggestion
```

2021-01-04 16:32 UTC, indytechcook commented
There is an outstanding issue here where the build assets do not exist for the commit.  The front end build assets exist when the code is merged to master.  I'm looking for a workaround.

2021-01-04 22:23 UTC, indytechcook commented
After fixing permission issues with tugboat the following test ran:

I changed the branch to https://github.com/department-of-veterans-affairs/vets-website/pull/15518

Testing the URL: https://web-uiomfdsc7ztwpyj25ndi5ulfbttrhmju.ci.cms.va.gov/resources/get-a-premium-my-healthevet-account/

Before:

![image](https://user-images.githubusercontent.com/121603/103583753-4f800c80-4eae-11eb-92ed-d3bd7e0f119d.png)


After:

![image](https://user-images.githubusercontent.com/121603/103583726-442ce100-4eae-11eb-92e0-edf2379e8cfc.png)

2021-01-04 22:24 UTC, indytechcook commented
There is a failing test that isn't related to this code.  Hopefully pulling in the latest code will fix it.

2021-01-04 23:12 UTC, indytechcook approved these changes

2021-01-05 21:24 UTC, indytechcook commented
I removed the DO NOT MERGE tag now that `advancedqueue` is enabled on prod.

2021-01-06 18:00 UTC, merged