[DRAFT] VACMS-3840: Appt-Intro-Text
department-of-veterans-affairs/va.gov-cms pull request #3912
Opened 2020-12-31 00:52 UTC by kaise-lafrai

## Description

See _issueid_. 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2020-12-31 14:17 UTC, kevwalsh commented
@kaise-lafrai this is looking great. 

A couple things i noticed: 

Appointments h2 should not have the red required asterisk. Do you mind removing that? Not part of your PR, but let's fix that. 

![Edit_VAMC_Facility_Health_Service_Adaptive_sports_-_Abie_Abraham_VA_Clinic___VA_gov_CMS](https://user-images.githubusercontent.com/643678/103413619-650cd380-4b48-11eb-847a-b8ca0658b781.jpg)

You're probably aware of this, but after specifying "Customize appointments intro text", adding some content, then changing to "No appointments intro text", it saves the customized content. 

![Adaptive_sports_-_Abie_Abraham_VA_Clinic___Veterans_Affairs](https://user-images.githubusercontent.com/643678/103413687-98e7f900-4b48-11eb-8a42-94a0bcc0e1cd.jpg)

Finally, i think we should handle some basic proofing work as part of this. Essentially, just displaying the fields on the node view in the appropriate spot. We should also remove the markup field from node display.  

![Adaptive_sports_-_Abie_Abraham_VA_Clinic___Veterans_Affairs](https://user-images.githubusercontent.com/643678/103413778-e8c6c000-4b48-11eb-9cab-b405046e9b9b.jpg)

2021-01-05 03:10 UTC, kevwalsh commented
QA pass. Great work @kaise-lafrai ! I tested on an existing node and on a new one. 

I'd like to get @rachel-kauff's  eyes on this before we merge. Now that it's implemented, i think we could use a small tweak to the positioning of the "default intro text" when the first item is selected. 

Also, i think we need to let the VAMC upgrade team, at the very least, know about this change. We may want to check with training team about this too.

2021-01-05 03:16 UTC, kevwalsh submitted a review, later dismissed
Pass, but i want to get @rachel-kauff's review too, at https://pr3912-txpmojlwj4ivzctkkctjyqrxdpz4t0tz.ci.cms.va.gov/node/9165/edit

2021-01-05 15:35 UTC, swirtSJW requested changes
Looks good overall Kaise.  Only one requested change (see below)

2021-01-05 15:35 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    }
There is a lot of logic here.  I'd prefer to put this into an aptly named function that gets called.  It will help keep the _hook_alter from getting overrun with unrelated logic.

2021-01-05 16:07 UTC, rachel-kauff commented
👀 Looking now...

2021-01-05 16:43 UTC, rachel-kauff commented
![Screen Shot 2021-01-05 at 8 30 18 AM](https://user-images.githubusercontent.com/41017988/103673174-22753d80-4f32-11eb-93bc-9205b2a1e970.png)

2021-01-05 17:19 UTC, rachel-kauff commented
> Widening the embedded (italicized) content should be straightforward, right @kaise-lafrai? Actually i just noticed these are hard returns. @rachel-kauff on large screens this will make it appear on just one line
Ah, interesting, so is there no max width for that kind of text element? That seems like it would be worth having, but one line is preferable to the stanzas that we have currently (though I do love the deadpan poetry.)

2021-01-05 21:20 UTC, kaise-lafrai commented
> Responding to Rachel's four comments
> 
> 1. Brevity looks good. @kaise-lafrai Let's make this change to the radio labels
> 2. I don't see a problem with adding the default value in order to prepopulate the Custom field. @swirtSJW or @kaise-lafrai may have a different take on that though. The plan is to make this default value editable elsewhere in the CMS in the future.
> 3. Widening the embedded (italicized) content should be straightforward, right @kaise-lafrai? Actually i just noticed these are hard returns. @rachel-kauff on large screens this will make it appear on just one line.
> 4. @kaise-lafrai can you change the height of the `Appointment lead-in text` text field in the form display to 3 lines instead of 5?

@kevwalsh @rachel-kauff 1, 3 and 4 implemented. For number 2, Adding a default, should we keep this empty so users understand that it needs a value if they save without entering anything? I thought the intention of custom text was to prevent a user from entering the default value. If they save with the default value then it might be more work to update that later.

2021-01-05 22:13 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    }
@swirtSJW Please review changes. Thanks!

2021-01-05 22:14 UTC, kaise-lafrai commented
@kevwalsh @rachel-kauff @swirtSJW Ready for another round of review. Thanks!

2021-01-06 14:17 UTC, kevwalsh approved these changes
Looks good to me. 

I think default text when choosing "Customize" is OK, because the editor may simply want to tweak it a bit. 

But i also see the additional cost of refactoring this once we make this default text editable to an editor. 

@rachel-kauff do you feel ok about shipping this with an empty  box for the "customize" option? When we iterate on this to make the default text editable to a national editor, we can revisit this.  

![Edit_VAMC_Facility_Health_Service_Physical_therapy__occupational_therapy_and_kinesiotherapy_-_Lawton_VA_Clinic___VA_gov_CMS](https://user-images.githubusercontent.com/643678/103778294-08a22c00-5000-11eb-8977-bda94399ec7f.jpg)

2021-01-07 16:31 UTC, rachel-kauff commented
@kevwalsh Yes, that makes sense. We can backlog the prefilled customized field.

2021-01-08 18:39 UTC, swirtSJW approved these changes
I like the refactored approach.  Nice work.

2021-01-08 18:41 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/104052094-2e256600-51b7-11eb-8d39-de9ca23e8456.png)

2021-01-08 18:41 UTC, merged