VACMS-3342: Extend Disable Auto Alias
department-of-veterans-affairs/va.gov-cms pull request #4012
Opened 2021-01-14 22:25 UTC by kaise-lafrai

## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3342

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
Coming soon..

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-01-14 22:57 UTC, swirtSJW requested changes
See two comments below.

2021-01-14 22:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +        $term_entity = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($entity_id);
Shouldn't we determine which kind of entity we are dealing with and just load the right one?  SInce we could easily have a match on both we would end up loading the right entity AND the wrong entity.

2021-01-14 22:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +        if (!empty($node_entity)) {
Node ids and term ids can easily overlap.   This would mean that the loads()  abpve returned a terma and node, only the node would get published.   See comment above about determining which we have before we load it, then  only process one.

2021-01-14 22:58 UTC, acrollet commented on tests/behat/Drupal/FeatureContext.php
> +   *   Either the view or form page.
```suggestion
   *   Either the view or edit page.
```

2021-01-14 22:58 UTC, acrollet commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
>  function _va_gov_backend_get_locked_alias_bundles() {
Do we need to keep this function to return an empty array? Do we anticipate needing locked aliases again soon?

2021-01-14 23:05 UTC, acrollet commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +        $term_entity = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($entity_id);
I'm wondering if we need the load at all or can just say something like:

```
if ($entity = $form_state->getformObject()->getEntity() && $entity->isPublished()) {
  $form['#after_build'][] = '_va_gov_backend_node_after_build_uncheck_auto_alias';
}
```

2021-01-14 23:29 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +        $term_entity = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($entity_id);
@acrollet Provided a review of the code with some suggestions.

2021-01-15 00:23 UTC, kaise-lafrai commented on tests/behat/Drupal/FeatureContext.php
> +   *   Either the view or form page.
Updated

2021-01-15 00:23 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +        if (!empty($node_entity)) {
Updated code

2021-01-15 00:25 UTC, kaise-lafrai commented
Pushed out updates for another round of review. @swirtSJW @acrollet

2021-01-15 00:26 UTC, kaise-lafrai commented
@acrollet Thanks for the detailed review. I Learned some new stuff!

2021-01-15 00:26 UTC, acrollet reviewed
lgtm! @swirtSJW the ball's in your court :-)

2021-01-15 00:27 UTC, acrollet commented
> @acrollet Thanks for the detailed review. I learned some new stuff!

any time! Thanks for taking time with me.

2021-01-15 00:28 UTC, acrollet commented
I kicked tugboat so hopefully the test results will come through...

2021-01-15 05:01 UTC, swirtSJW requested changes
Very thorough wok Kaise.  I like all the streamlining you and @acrollet worked out.

I only have a couple of small semantic changes to make it so the code speaks the truth and that the behat test runs a little faster.

2021-01-15 14:20 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
>  function _va_gov_backend_get_locked_alias_bundles() {
Thanks for catching this!

2021-01-15 14:20 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($entity->getEntityTypeId() === 'node' && !in_array($entity->bundle(), _va_gov_backend_get_locked_alias_bundles())) {
Thanks for catching this!

2021-01-15 14:20 UTC, kaise-lafrai commented on tests/behat/features/content_editing.feature
> +    Then I press "Edit"
Thanks for catching this! Testing it out now locally.

2021-01-15 14:21 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if (!in_array($entity->bundle(), _va_gov_backend_get_locked_alias_bundles()) &&
Thanks for catching this!

2021-01-15 17:37 UTC, kaise-lafrai commented
@swirtSJW @acrollet Ready for review once again!

2021-01-15 17:39 UTC, acrollet commented on tests/behat/features/content_editing.feature
> +    And I fill in "URL alias" with "/test-office-behat-404"
👍

2021-01-19 16:14 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if (!($form_state->getFormObject() instanceof EntityFormInterface)) {
This code is so much cleaner!  I can skim down it and understand what's happening right away!    Nice job!!

2021-01-19 17:40 UTC, swirtSJW approved these changes
Nice refactor @kaise-lafrai

2021-01-19 17:40 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/105072160-867c2380-5a53-11eb-801d-c9802c04fd37.png)

2021-01-19 17:40 UTC, merged