VACMS-4017: CC-Policies-Proofing
department-of-veterans-affairs/va.gov-cms pull request #4124
Opened 2021-01-28 20:51 UTC by kaise-lafrai

## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4017

## Testing done

## Screenshots

## QA steps

Coming soon...

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-01-28 21:25 UTC, kevwalsh requested changes
@kaise-lafrai small change to markup field: `<h1>Policies</h1>` instead `<h2>POLICIES</h2>` 

So it should look more like this


![Screenshot_2021-01-28__4_25_PM](https://user-images.githubusercontent.com/643678/106200762-7962e100-6185-11eb-8635-e2479f69eb80.png)

2021-01-29 00:02 UTC, kaise-lafrai commented
> @kaise-lafrai small change to markup field: `<h1>Policies</h1>` instead `<h2>POLICIES</h2>`
> 
> So it should look more like this
> 
> ![Screenshot_2021-01-28__4_25_PM](https://user-images.githubusercontent.com/643678/106200762-7962e100-6185-11eb-8635-e2479f69eb80.png)

H1 is not an allowable option at the moment.

2021-01-29 02:49 UTC, swirtSJW commented on config/sync/field.field.node.vamc_system_policies_page.field_fieldset_markup.yml
> +    value: "<h2>Policies</h2>\r\n"
@kevwalsh I really don't like that we are hard coding an h2 in here.  We can fix later though.  Not in this PR though.  Poor Kaise has been through enough on this ;)

2021-01-29 02:53 UTC, swirtSJW approved these changes
Excellent work @kaise-lafrai

2021-01-29 03:04 UTC, swirtSJW commented on config/sync/field.field.node.vamc_system_policies_page.field_fieldset_markup.yml
> +    value: "<h2>Policies</h2>\r\n"
The other problem is that now we have fieldsets with empty legends which is going to be a 508 issue. Fieldsets may be an inappropriate use in this case because they do not contain fields.   They are a fieldset full of content.  :(

2021-01-29 03:15 UTC, merged