VACMS-4090: Fix required related info field bug.
department-of-veterans-affairs/va.gov-cms pull request #4189
Opened 2021-02-03 20:23 UTC by ethanteague

## Description
See #4090 

## Testing done
Visual / Behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/106804599-9db23800-6633-11eb-8c07-68d9e356324b.png)
![image](https://user-images.githubusercontent.com/2404547/106804619-a145bf00-6633-11eb-99c5-dc47bf7f1a88.png)

## QA steps
- As an administrator, go to `node/add/q_a`, and complete all fields required _outside_ of `Enable standalone Resources and support page for this Q&A.` (don't toggle it on).
- Save the form, and confirm no errors are thrown.
- Edit the form, toggle on the `Enable standalone Resources and support page for this Q&A.`, visually verify that a link widget appears for related info, click save, and confirm that error is thrown indicating the related info link field is required.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-02-04 13:44 UTC, kevwalsh commented
![Edit_Q_A_hello___VA_gov_CMS](https://user-images.githubusercontent.com/643678/106900850-05fd2a00-66c5-11eb-80a9-24f802815f2c.png)

@ethanteague i may be missing something, but i don't see any difference here. 

1. Related info is still not required
2. No empty link teaser form is displayed upon load. 

https://pr4189-0bmtpopyxrr6z4bnuj5o3v6wf7zempym.ci.cms.va.gov/node/15848/edit

2021-02-05 22:48 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $form_state->unsetValue('field_related_information');
Could benefit from a comment here describing the why.

2021-02-05 23:25 UTC, ethanteague commented
> ![Edit_Q_A_hello___VA_gov_CMS](https://user-images.githubusercontent.com/643678/106900850-05fd2a00-66c5-11eb-80a9-24f802815f2c.png)
> 
> @ethanteague i may be missing something, but i don't see any difference here.
> 
> 1. Related info is still not required
> 2. No empty link teaser form is displayed upon load.
> 
> https://pr4189-0bmtpopyxrr6z4bnuj5o3v6wf7zempym.ci.cms.va.gov/node/15848/edit

Ready for another pass when you have a sec, @kevwalsh

2021-02-09 15:59 UTC, swirtSJW commented
QA did not pass
![image](https://user-images.githubusercontent.com/5752113/107390601-d9cb1a00-6ac5-11eb-8996-a0bb6f949f3f.png)


![image](https://user-images.githubusercontent.com/5752113/107390696-f0717100-6ac5-11eb-9332-17e5ecd062b7.png)

2021-02-09 17:27 UTC, ethanteague commented
> QA did not pass
> ![image](https://user-images.githubusercontent.com/5752113/107390601-d9cb1a00-6ac5-11eb-8996-a0bb6f949f3f.png)
> 
> ![image](https://user-images.githubusercontent.com/5752113/107390696-f0717100-6ac5-11eb-9332-17e5ecd062b7.png)

Should be fixed now, @swirtSJW

2021-02-09 19:48 UTC, swirtSJW commented
@ethanteague I am still getting that same error on the pr environment.  Even cleared my caches.
![image](https://user-images.githubusercontent.com/5752113/107419455-d3e53100-6ae5-11eb-9437-0a1cdbb6015f.png)

2021-02-09 19:48 UTC, swirtSJW requested changes
QA not passing  see previous comment.

2021-02-09 19:56 UTC, ethanteague commented
> QA not passing see previous comment.

Dangit.......sorry about this, @swirtSJW ! Lemme take a look.

2021-02-09 21:00 UTC, swirtSJW approved these changes
Tests out fine.   Nice work.

2021-02-09 21:02 UTC, swirtSJW commented
This is good to go.  Just waiting on tests to pass.  
When they pass it can be merged.

2021-02-10 17:04 UTC, merged