VACMS-4049: Policy-Tooltips-Accessible
department-of-veterans-affairs/va.gov-cms pull request #4247
Opened 2021-02-10 17:15 UTC by kaise-lafrai

## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4049

## Testing done

## Screenshots

## QA steps

Coming soon...

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-02-10 22:44 UTC, swirtSJW requested changes
Overall looks good Kaise.  Just a couple of minor changes.

2021-02-10 22:44 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/Tooltip.php
> +    ];
curious:  what are these for?  I'm not familiar with these.

2021-02-10 22:44 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/Tooltip.php
> +    if ($context == 'form') {
Suggestion:   Whenever you aren't sure of the values that may come through the variable, you want to be defensive by using the strict comparison (===) It is a subtle difference, but always safer to default to strict or your risk unintended results.  (see the comparison of the truth tables.
![image](https://user-images.githubusercontent.com/5752113/107582146-17fc3280-6bc7-11eb-915a-aec56e1c9851.png)

![image](https://user-images.githubusercontent.com/5752113/107582297-4e39b200-6bc7-11eb-9b1b-bfd40073c9e9.png)

2021-02-11 23:37 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/Tooltip.php
> +    ];
These hide some of the unnecessary fields that come with Html element.

2021-02-11 23:39 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/Tooltip.php
> +    if ($context == 'form') {
Fixed in new commit.

2021-02-11 23:40 UTC, kaise-lafrai commented on config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
> +      format_type: Tooltip
Resolved in new commit

2021-02-11 23:40 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/Tooltip.php
> + *   id = "Tooltip",
resolved in new commit

2021-02-11 23:53 UTC, kaise-lafrai commented on config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
> +      format_type: Tooltip
Take that back: I couldn't figure out why my format type starts with a capital T. I tried changing it and it breaks the fieldgroup selection on the content type configration.

2021-02-11 23:58 UTC, kaise-lafrai commented
@swirtSJW @kevwalsh Ready for review.

2021-02-12 03:23 UTC, swirtSJW commented
Looks like the partial switch of the tooltip manchine name to lower case and the config in uppercase led to a mismatch on import.
![image](https://user-images.githubusercontent.com/5752113/107726691-a4861e00-6cb7-11eb-9b43-7a16d957ad55.png)

I pushed up a fix to sync the two.

My guess is it did not work locally for you due to caching.  This needed a cache clear before config import.

2021-02-12 03:47 UTC, swirtSJW approved these changes
This looks great Kaise.  Outstanding work.   I added the role attribute.

Just waiting on tests to pass to merge this.

2021-02-12 04:50 UTC, merged