VACMS-000: Add default details class to required fieldsets on clp.
department-of-veterans-affairs/va.gov-cms pull request #4346
Opened 2021-02-17 13:36 UTC by ethanteague

## Description
New details with image formatter doesn't add the asterisk to fieldsets with required fields.
This pr adds the missing asterisk hook class to the fieldsets that are required.

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/108211737-1668c800-70fb-11eb-8d15-f005eb12f6b5.png)

## QA steps
As an administrator, go to `/node/add/campaign_landing_page` and visually verify that the first three and the last fieldsets show a required red asterisk.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-02-17 13:42 UTC, kevwalsh requested changes
I see the asterisk but the first image is missing.

2021-02-17 13:42 UTC, kevwalsh commented on config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
> -        visual_guide_alt_text: 'Basic visual layout of the hero banner page segment.'
i don't think you meant to do this.

2021-02-17 14:39 UTC, ethanteague commented on config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
> -        visual_guide_alt_text: 'Basic visual layout of the hero banner page segment.'
Thanks for catching that, @kevwalsh :heart:

2021-02-17 16:04 UTC, swirtSJW approved these changes

2021-02-17 16:07 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/108231871-348cf300-7110-11eb-9183-81dbe721faaa.png)
  Tests out good for me.  Can merge when tests pass.

2021-02-19 14:05 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/108514207-96c13180-7291-11eb-889e-9ebd59c1bb64.png)

2021-02-19 14:05 UTC, merged