VACMS-2743: Fix image cropping issues.
department-of-veterans-affairs/va.gov-cms pull request #4348
Opened 2021-02-17 14:12 UTC by ndouglas

## Description

See #2743. 

The only way I can think of to effectively determine whether the platform is generating cropped images correctly is with visual regression testing.  So after some research and playing briefly with a couple of different options, and thinking about the options available in deployment (for instance, `imagick` doesn't seem to be installed on Tugboat, and it might not be present on BRD), I figured [cypress-visual-regression](https://www.npmjs.com/package/cypress-visual-regression) was likely to be the best path forward.

I'm going to write the tests first and then try to find the simplest change possible that will get the tests to pass.

There are several cases I'm concerned about:
1. when a new node is saved and the image is freshly uploaded and cropped
2. when the derivative is subsequently deleted
3. when a node is edited and the image is freshly uploaded and cropped
4. when a node is edited and the existing image is recropped

(I might think of more as I dig deeper)

Of these cases, I think the only one that does not currently work is # 1, but it's also the most important 😛  This will be confirmed or disproven with tests.

## Testing done
Forthcoming.

## Screenshots
Forthcoming.  Boy, are these forthcoming.

## QA steps
As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done
- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review
- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?
- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner
- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

2021-02-19 00:23 UTC, ndouglas commented
@acrollet I'd love to get your thoughts on this nightmare tomorrow.  I think there's some insight I'm missing into the DOM or event listening or something else and think you might be just the guy to inflict my neuroses on for a while.

2021-02-19 01:13 UTC, acrollet commented
@ndouglas 
[](https://media1.tenor.com/images/baaeeb9bc7c8215943fd04e8b1b50df4/tenor.gif?itemid=14186847)

2021-02-19 14:30 UTC, ndouglas commented
@acrollet I ended up figuring it out.  Thank you 😁

2021-02-19 15:01 UTC, acrollet commented
@ndouglas nice! Sleeping on it usually helps...

2021-02-19 18:44 UTC, ndouglas commented
So the first part of this ("tell cropper.js we're resizing the crop!") did not go as smoothly as I'd anticipated.

![giphy (1)](https://user-images.githubusercontent.com/1318579/108546586-55dc1380-72b7-11eb-81db-fc6164203f94.gif)

I found a few issues with Cucumber, most importantly that regular expressions in step matching expressions don't seem to be working right now, hence one of the earlier commits reverting all of my triumphant regexes...

And I realized as I went further that I should use slightly different tools -- `cypress-visual-regression` is not appropriate in a case where I'm comparing two raw images, but we have `pixelmatch`...

And this really needs to be refactored and reworded, and I need to improve the way the ideas of these step definitions are expressed.

but given a test like this:

<img width="908" alt="Screen Shot 2021-02-19 at 1 38 01 PM" src="https://user-images.githubusercontent.com/1318579/108546869-b9664100-72b7-11eb-8e9f-65ccca666268.png">

https://user-images.githubusercontent.com/1318579/108546893-c420d600-72b7-11eb-9567-d9b8ae869587.mp4

We can get a diff image (should we care) and a raw number of pixels that differ.  (In this case, ~67K)
 
![Manually cropping an image should lead to correctly cropped derivatives](https://user-images.githubusercontent.com/1318579/108547039-f7fbfb80-72b7-11eb-99d8-5b1ecb8dd5bb.png)

So I'll write a few tests that branch off this for the other cases I'm worried about and then I can finally work on the solution.

2021-02-22 20:49 UTC, ndouglas commented
To succinctly give some background, we have two modules involved: `image_widget_crop`, which creates a crop configuration based on the user interface invoked when an image is uploaded, and `image_style_warmer`, which generates image derivatives when the entity is saved.

The issue is that `image_style_warmer`'s warming is invoked from `hook_ENTITY_TYPE_(insert|update)()`, for `file` entities, whereas `image_widget_crop`'s crop configurations are generated from `hook_entity_(insert|update)()` hooks.  This means that the image derivative is generated before and does not reflect the crop configuration.

`hook_ENTITY_TYPE_*()` hooks are invoked prior to `hook_entity_*()` hooks, unavoidably; changing the weights of these two modules should not ameliorate the bug (and, in testing, does not).

So we have a few possible solutions:
1.  An approach that appeals to me is to rewrite the `image_style_warmer` module to act on events rather than hooks.  If a list of styles and an affected entity are stored, then this list and entity can be retrieved later by a subscriber to the `TERMINATE` kernel event.  This would allow all hooks to modify the entity prior to the image derivative generation.  I haven't tested this approach, though, because ain't nobody got time for that.
2. As above, but enqueue all image derivative generation and run that in response to the `TERMINATE` event.
3. Add or modify an early-running module to hijack `image_widget_crop`'s crop configuration generation service and run it in `hook_ENTITY_TYPE_*()` implementations.  This was my idea from the other day, is the easiest to try, and, fortunately, we already have such an early-running module: `va_gov_content_export`.  And at least to me it seems an acceptable thing to shove into that module.  Unfortunately, this doesn't (and can't) work, as the crop settings don't really exist at the time that the file entity is created.

So we move on:

4.  Hack some extra settings into the `image_style_warmer` module's config form and use those settings for our own nefarious purposes 😈   Form looks like :peach:, but I think we can whip something up with some CSS to make it look more coherent:
 
<img width="849" alt="Screen Shot 2021-02-22 at 3 43 26 PM" src="https://user-images.githubusercontent.com/1318579/108767714-c471d900-7524-11eb-92a0-d0eda2b070d5.png">

And it looks like the code has the desired effect:

<img width="543" alt="Screen Shot 2021-02-22 at 3 44 44 PM" src="https://user-images.githubusercontent.com/1318579/108767851-f3884a80-7524-11eb-9315-eb5f81510c05.png">
<img width="702" alt="Screen Shot 2021-02-22 at 3 44 49 PM" src="https://user-images.githubusercontent.com/1318579/108767853-f420e100-7524-11eb-8e00-638551ede1c1.png">

:tada:

I wanted to get some feedback on this approach (now that I'm confident it works) and whether I should 1) turn it into a separate module, like `va_gov_image` or something, or 2) leave it where it is, or 3) open a PR with the `image_style_warmer` guy, either as an alternative to or replacement for the current behavior.  Or, 4) this approach flat-out sucks and I should fall on my sword.

Thoughts?

2021-02-23 13:46 UTC, ndouglas commented
Hey @oksana-c if you have a moment, what's the yuck factor of my approach here?  I was also thinking about editing the `image_style_warmer` form to just hide the "initial image styles" and replace that list with the one I'm using for this late generation.  So it would be a transparent change to the form.

2021-02-23 21:01 UTC, oksana-c commented
notes from our 🦆 session:
* let's move all form alters + helper function into `va_gov_media` (remember to mark it as D9 compatible)
* let's open an follow-up story to refactor the altered form + attached functionality once we have a queue runner

2021-02-23 21:04 UTC, ndouglas commented
Things to Do:
- disable queue image styles
- disable initial image styles
- move hooks to separate module
- write followup issue -- these hooks should be removed when we have a realtime queue runner; at that point we'll use the queue image styles and not need the initial image styles
- add comment in code referring to followup issue

2021-02-23 22:49 UTC, mchelen-gov commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
```suggestion
  if (
    !empty($image_styles)
    && isset($entity)
    && $entity instanceof FieldableEntityInterface
  ) {
    foreach ($entity->getFields() as $entity_fields) {
      if ($entity_fields instanceof FileFieldItemList) {
        foreach ($entity_fields->getValue() as $entity_file_field_value) {
          \Drupal::service('image_style_warmer.warmer')
            ->doWarmUp($entity_file_field_value->entity, array_keys($image_styles));
        }
      }
    }
  }
```

2021-02-24 13:52 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
Sure!

2021-02-24 15:21 UTC, ndouglas commented
New form.  Other changes implemented as discussed in call 😃 

<img width="494" alt="Screen Shot 2021-02-24 at 10 19 53 AM" src="https://user-images.githubusercontent.com/1318579/109022592-f5b7e980-7689-11eb-931f-4179699924d6.png">

2021-02-24 20:04 UTC, acrollet requested changes

2021-02-24 20:04 UTC, acrollet commented on tests/behavioral/cypress/integration/common/i_select_option_from_dropdown.js
> +Given(`I select option {string} from dropdown {string}`, (option, label) => {
❤️

2021-02-24 20:04 UTC, acrollet commented on tests/behavioral/cypress/integration/common/the_derivative_of_the_media_image_should_match_the_fixture.js
> +      console.log('Derivative URL', derivativeUrl);
testing code or useful for CI?

2021-02-24 20:04 UTC, acrollet commented on tests/behavioral/cypress/integration/common/the_derivative_of_the_media_image_should_match_the_fixture.js
> +        console.log(derivativeImage);
```suggestion
```

2021-02-24 20:04 UTC, acrollet commented on tests/behavioral/cypress/integration/common/the_derivative_of_the_media_image_should_match_the_fixture.js
> +          const path = `cypress/screenshots/pixelmatch_diffs/${cy.state('ctx').test.title}.png`;
```suggestion
          const path =
            `cypress/screenshots/pixelmatch_diffs/${cy.state('ctx').test.title}.png`;
```

2021-02-24 20:04 UTC, acrollet commented on tests/behavioral/cypress/integration/image_crop.feature
> +  Scenario: Manually cropping an image should lead to correctly cropped derivatives
awesome test 

![](https://i.pinimg.com/originals/84/d4/40/84d440d70af47873b7aa80204ed0543e.gif)

2021-02-24 20:04 UTC, acrollet commented on tests/behavioral/cypress/support/commands.js
> +    cmd = 'lando drush %command';
yay

2021-02-24 20:08 UTC, ndouglas commented on docroot/modules/custom/va_gov_media/va_gov_media.module
> + * Contains va_gov_migrate.module.
Kinda funny that it griped at me when I did't have the @file comment but didn't when I ineptly copypasta'ed it.

2021-02-24 20:10 UTC, acrollet commented on docroot/modules/custom/va_gov_media/va_gov_media.module
> + * Contains va_gov_migrate.module.
![](http://i.imgur.com/Ieo6ddj.gif)

2021-02-24 20:10 UTC, ndouglas commented on tests/behavioral/cypress/integration/common/i_delete_the_derivative_of_the_media_image.js
> +      cy.exec('npm run build', { timeout: 20000 })
none at all, accidentally left behind reference code

2021-02-24 20:11 UTC, ndouglas commented on tests/behavioral/cypress/integration/common/the_derivative_of_the_media_image_should_match_the_fixture.js
> +      console.log('Derivative URL', derivativeUrl);
Not allowing commits with `console.log()` calls would be a nice hook

2021-02-24 20:12 UTC, acrollet commented on tests/behavioral/cypress/integration/common/the_derivative_of_the_media_image_should_match_the_fixture.js
> +      console.log('Derivative URL', derivativeUrl);
I think eslint will catch that if we add the behavioral dir to it.

2021-02-24 20:12 UTC, acrollet commented on tests/behavioral/cypress/integration/common/the_derivative_of_the_media_image_should_match_the_fixture.js
> +      console.log('Derivative URL', derivativeUrl);
let's not delay this PR on that though.

2021-02-24 20:13 UTC, ndouglas commented on tests/behavioral/cypress/integration/image_crop.feature
> +  Scenario: Manually cropping an image should lead to correctly cropped derivatives
Thanks... hope we can find a way to improve some of that phrasing.

2021-02-24 20:14 UTC, acrollet commented on tests/behavioral/cypress/integration/image_crop.feature
> +  Scenario: Manually cropping an image should lead to correctly cropped derivatives
meh, it does what it says on the tin :-)

2021-02-24 20:20 UTC, acrollet commented
Crop UI:

<img width="863" alt="Screen Shot 2021-02-24 at 1 19 59 PM" src="https://user-images.githubusercontent.com/101649/109060744-01fc7080-76a3-11eb-8418-aebaa8c1d134.png">

Generated Image:
![Image from iOS-2](https://user-images.githubusercontent.com/101649/109060776-0e80c900-76a3-11eb-958a-f3fb0d1a313c.jpg)

2021-02-24 20:25 UTC, acrollet approved these changes
Manual test passed, great new tests coming in.

2021-02-24 21:04 UTC, merged