VACMS-4203: remove computed field
department-of-veterans-affairs/va.gov-cms pull request #4364
Opened 2021-02-18 19:38 UTC by acrollet

## Description

See _issueid_. 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-02-22 20:42 UTC, acrollet commented
@swirtSJW is there a way to manually test alert sending without spamming real people?

2021-02-23 15:55 UTC, swirtSJW reviewed
> @swirtSJW is there a way to manually test alert sending without spamming real people?

Two ways.

1.  Use one environment that does not have your code.   Edit a facility banner alert.   Look in the queue to get the data.   Repeat the same steps on an environment with your changes.  Compare the queued data.  There should be no diff.
2. Look in phpinfo on tugboat to see if it has govedelivery dev endpoint set.  If it does you could test on tugboat then have Elijah or I log into govedeliver dev and see if it sent.   If tugboat can't do it, we may have to have Elijah or Neil pull your PR to dev so that it can do a test send.

2021-02-23 15:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_govdelivery/src/EventSubscriber/EntityEventSubscriber.php
> +      $entity->getType() === 'full_width_banner_alert';
```suggestion
    return ($entity instanceof NodeInterface) &&
      ($entity->getType() === 'full_width_banner_alert');
```
Not necessary but more explicit?

2021-02-23 15:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_govdelivery/src/EventSubscriber/EntityEventSubscriber.php
> +<?php
I REALLY like this architecture.   Thank you for implementing it.

One concern: with other facility types coming that will also be leveraging govdeliver  in different ways, should this 'EntityEventSubscriber' be namespaced more specifically to the content type?  Like 'EntityEventSubscriberStatusBulletins' or are you envisioning that we just add additional cases to 'processStatusBulletins()'?  If the latter then the naming of 'processStatusBulletins()' should probably become less specific like 'processStatusBulletins()'.
Seems like either the class needs to be more specific or the method needs to be less specific (heisenburg naming uncertainty principle :)  )

2021-02-23 15:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php
> -      $template_variables['situation_update'] = FALSE;
Intentionally removed?

2021-02-23 19:17 UTC, swirtSJW reviewed
Very awesome and thorough work.  I only had a few questions or concerns.

2021-02-23 19:17 UTC, swirtSJW commented on docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module
> +    return;
I am troubled by the use of this bail out early pattern on things like hook_form_alter because it does not encapsulate the code that is supposed to run if that is not the case.   It makes it risky for other developers' additions to the alter hook that might be unrelated to full width banners.  Ideally this could just be moved to another function  that gets called from within the alter.  Then it does its own defensive bail early check.

2021-02-23 21:07 UTC, acrollet commented on composer.lock
> +            "name": "drupal/computed_field",
brain fart, thank you!

2021-02-23 21:11 UTC, acrollet commented on docroot/modules/custom/va_gov_govdelivery/src/EventSubscriber/EntityEventSubscriber.php
> +<?php
makes sense, updated

2021-02-23 21:21 UTC, acrollet commented on docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php
> -      $template_variables['situation_update'] = FALSE;
good eye - I had set it to default to `FALSE` in the declaration of `$template` but that line went missing somehow. I put it back here since it doesn't really save anything to move it up.

2021-02-23 22:37 UTC, acrollet commented on docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php
> +        return;
You were right, this wanted a big re-factor ;-)

2021-02-23 22:48 UTC, acrollet commented on docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module
> +    return;
good call, I switched to `hook_form_FORMID_alter` instead.

2021-02-23 22:50 UTC, acrollet commented
@swirtSJW the code is ready for another pass when you are!

2021-02-23 23:01 UTC, acrollet commented
The preview is failing, I'm seeing this: 
```
Next Drupal\Component\Plugin\Exception\PluginNotFoundException: Unable to determine class for field type 'computed_string_long' found in the 'field.storage.node.field_banner_alert_computdvalues' configuration in /var/lib/tugboat/docroot/core/modules/field/src/FieldStorageConfigStorage.php:174
```

Looks like we'll need a first PR to remove the config, and a follow-on to remove the module.

2021-02-24 14:58 UTC, indytechcook requested changes

2021-02-24 14:58 UTC, indytechcook commented on docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module
> +    $node->isPublished() || ($node->moderation_state->value === 'published')
Let's verify if checking the moderation state is necessary.

2021-02-24 14:58 UTC, indytechcook commented on docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php
> +    if ($send_type === 'status alert') {
Let's use CONST for these

2021-02-24 16:57 UTC, acrollet commented on docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module
> +    $node->isPublished() || ($node->moderation_state->value === 'published')
good call, the banner alert node type is not moderated. Removed and also added logic to ensure the field is disabled if the node has ever been published.

2021-02-24 18:34 UTC, acrollet commented
Manual test 1: I created a new published bulletin node with sending enabled on a clone of master and this branch. I diffed the created queue items and found differences only in timestamps and IDs:

[branch_initial_publish.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6038122/branch_initial_publish.txt)
[master_initial_publish.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6038123/master_initial_publish.txt)

(Queue items retrieved with `drush sqlq "SELECT * FROM queue WHERE name = 'govdelivery_bulletins' ORDER BY item_id DESC LIMIT 1\G"`)

2021-02-24 18:38 UTC, acrollet commented
Manual test 2: I updated the previous bulletin node to add a situation update with sending enabled on a clone of master and this branch. I diffed the created queue items and again found differences only in timestamps and IDs:

[branch_situation_update.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6038145/branch_situation_update.txt)
[master_situation_update.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6038146/master_situation_update.txt)

2021-02-24 18:43 UTC, acrollet commented
@swirtSJW calling your attention to my previous comments, please take a look when you're able. Thanks! :-)

2021-02-24 19:45 UTC, indytechcook approved these changes

2021-02-24 23:08 UTC, merged