VACMS-4322_4323_4340 Vet center config
department-of-veterans-affairs/va.gov-cms pull request #4366
Opened 2021-02-18 23:30 UTC by ethanteague

## Description
See: #4322 #4323 #4340 

## Testing done
Visual / Behat

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-02-19 13:26 UTC, kevwalsh commented on config/sync/node.type.vet_center_locations_list.yml
> +      - main
We don't need any menus available. Can you disable this? And while you're at it, the Alias and Authoring options. 

![Create_Vet_Center_Locations_List___VA_gov_CMS](https://user-images.githubusercontent.com/643678/108510150-28c63b80-728c-11eb-8543-7ea198ecfc35.png)

2021-02-19 13:28 UTC, kevwalsh commented on config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
> +    - field.field.node.vet_center_locations_list.body
Remove `body` field. I always forget that it's there by default.

2021-02-19 13:31 UTC, kevwalsh commented on config/sync/core.entity_view_display.node.vet_center_locations_list.default.yml
> +content:
![Boston_Vet_Center___Veterans_Affairs](https://user-images.githubusercontent.com/643678/108510708-d76a7c00-728c-11eb-916b-08cfbe230e9f.png)

Let's hide these three fields (and body too, but it's going away anyway).

2021-02-19 14:58 UTC, ethanteague commented on config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
> +    - field.field.node.vet_center_locations_list.body
Me too! I should know to remove this automatically, by now - apologies for missing, @kevwalsh

2021-02-19 15:09 UTC, kevwalsh commented on config/sync/core.entity_view_display.node.vet_center_locations_list.teaser.yml
> +    - core.entity_view_mode.node.teaser
@ethanteague no teaser view mode needed.

2021-02-19 15:24 UTC, kevwalsh requested changes
![kevin_walsh___VA_gov_CMS](https://user-images.githubusercontent.com/643678/108524085-a85c0680-729c-11eb-91d3-916f004d2ffa.png)

Oops, this got lost in my last review.

2021-02-19 17:48 UTC, kevwalsh approved these changes
LGTM!

2021-02-23 14:51 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> +    type: tablefield
Did we look into using "Office hours module?"

2021-02-23 15:01 UTC, ethanteague commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> +    type: tablefield
Good q, and I don't recall. Not sure if we want to explore this, as it would introduce a pattern unlike other places where we have hours treatments, @swirtSJW . What say you, @kevwalsh ?

2021-02-23 16:12 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> +    type: tablefield
Right this would be the first of the new pattern to move the others to.  The tablefield is problematic for any potential for hardening and data sending to lighthouse.   We we hoping that "Office hours" module might give us more structure.

2021-02-23 16:16 UTC, swirtSJW commented on config/sync/node.type.locations_listing.yml
> +name: 'VAMC System Locations List'
@kevwalsh  is this "VAMC System" accurate since vet centers will be using them too?

2021-02-23 16:19 UTC, swirtSJW commented on config/sync/pathauto.pattern.vet_center.yml
> +pattern: '[node:title]'
These are just all going at the root level?  That doesn't seem right.

2021-02-23 16:24 UTC, ethanteague commented on config/sync/pathauto.pattern.vet_center.yml
> +pattern: '[node:title]'
That's my understanding, @swirtSJW - @kevwalsh , is this correct?

2021-02-23 16:25 UTC, kevwalsh commented on config/sync/node.type.locations_listing.yml
> +name: 'VAMC System Locations List'
@swirtSJW  Vet Centers will not be using it in the end.

2021-02-23 16:26 UTC, swirtSJW commented on config/sync/pathauto.pattern.vet_center.yml
> +pattern: '[node:title]'
@kevwalsh Shouldn't these be namespaced to something like /vet-centers/[node:title]

2021-02-23 16:26 UTC, kevwalsh commented on config/sync/pathauto.pattern.vet_center.yml
> +pattern: '[node:title]'
yeah there's a slack thread about it. it may change, but unlikely.

2021-02-23 18:16 UTC, swirtSJW commented on config/sync/pathauto.pattern.vet_center.yml
> +pattern: '[node:title]'
400 vetcenters all littering up the root level path seems problematic especially when one goes away.  People know how to go up a level when something is a 404, but if there is no level to go up to they are stuck.

2021-02-23 18:38 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/108891203-71f3f380-75dc-11eb-8c77-87ea28da1e6c.png)

2021-02-23 18:39 UTC, merged