VACMS-4355 VC facility health service
department-of-veterans-affairs/va.gov-cms pull request #4377
Opened 2021-02-19 20:27 UTC by ethanteague

## Description
See #4355 

## Testing done
Visual, behat, phpunti

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/108557311-634cca00-72c6-11eb-9b69-ebdfb75b23a9.png)

## QA steps
- As an administrator, go to `node/add/vet_center_facility_health_servi`
- Select Boston Vet Center, and choose the Complementary and alternative medicine options.
- Save the form, and visually verify the page and path match the screenshot, above.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE` prior to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4366 being merged

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-02-19 21:16 UTC, kevwalsh requested changes
![Create_Vet_Center_Facility_Health_Service___VA_gov_CMS](https://user-images.githubusercontent.com/643678/108562442-d73ea080-72cd-11eb-9f0d-31d5947d489d.png)

2021-02-19 21:16 UTC, kevwalsh commented on config/sync/field.field.node.vet_center_facility_health_servi.field_vet_center.yml
> +required: false
should be required (i just updated AC, sorry)

2021-02-19 21:16 UTC, kevwalsh commented on config/sync/field.field.node.vet_center_facility_health_servi.field_service_name_and_descripti.yml
> +required: false
Should also be required

2021-02-19 21:55 UTC, ethanteague commented on config/sync/field.field.node.vet_center_facility_health_servi.field_vet_center.yml
> +required: false
My bad, @kevwalsh - I should have done that.

2021-02-23 19:48 UTC, swirtSJW commented
@ethanteague Conflicted.  Needs counseling  ;)

2021-02-24 17:06 UTC, swirtSJW submitted a review, later dismissed
Looks good.  Just waiting on tests to complete.

2021-02-24 22:04 UTC, swirtSJW approved these changes

2021-02-25 01:41 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/109090210-9e913380-76e0-11eb-9656-e94ad49979c2.png)

2021-02-25 01:41 UTC, merged