VACMS-4520 4523 Disable title and display intro
department-of-veterans-affairs/va.gov-cms pull request #4532
Opened 2021-03-03 13:28 UTC by ethanteague

## Description
See #4520 #4523

## Testing done
Visual / Behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/109812403-045a4f80-7bfa-11eb-9ad5-2ceb9060b039.png)
![image](https://user-images.githubusercontent.com/2404547/109812417-08866d00-7bfa-11eb-825a-42cab381e92d.png)

## QA steps
- As an administrator, go to `node/2360/edit` and visually verify that you can alter the title.
- Logout, login back in as a user without administrator role, and visually verify that the title field is no longer editable.
- As an administrator, go to `/health-care/covid-19-vaccine-tag` and visually verify that the page introduction is visible.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-03-03 13:43 UTC, kevwalsh submitted a review, later dismissed

2021-03-03 13:43 UTC, kevwalsh commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  // Prevent system title from being edited on the edit form by non admins.
oh nice, i like this approach, it takes care of #4522 as well. Can you extend this to content_admin, not just admin?

2021-03-03 15:56 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  // Prevent system title from being edited on the edit form by non admins.
Nice thinking, @kevwalsh ! Updated :+1:

2021-03-03 22:23 UTC, swirtSJW requested changes

2021-03-03 22:23 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
Can we chunk this into a meaningfully named local function and call it just to keep all the logic bloat out of the hook_form_alter()?

2021-03-03 23:16 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
Yep, @swirtSJW :+1: 

We should probably clean this big 'ol nasty alter up one of these days. It's grown to where it's no longer readable.

2021-03-04 20:51 UTC, swirtSJW requested changes

2021-03-04 20:51 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $current_user_roles = User::load(\Drupal::currentUser()->id())->getRoles();
Sorry, Missed this earlier.  This seems redundant.   User::load   and \Drupal::currentUser()   both give you the same [account user interface](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Session%21AccountProxyInterface.php/interface/AccountProxyInterface/8.7.x)  
which provides you with  the getRoles() method 
I think you could get away with 
`$current_user_roles = \Drupal::currentUser()->getRoles();`
and avoid the redundant load of a user you already have.

2021-03-04 20:51 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $admin_roles = count(array_intersect($allowed_roles, $current_user_roles));
Bonus points for use of array intersect.  `$admin_roles` is kind of a misrepresentation though... it does not contain roles, it is a count  so `$allowed_role_count` would be more accurate.

2021-03-04 23:34 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $current_user_roles = User::load(\Drupal::currentUser()->id())->getRoles();
Argh - I knew that, but still didn't catch it. Apologies, @swirtSJW - ty for the keen eyes :+1:

2021-03-04 23:35 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $admin_roles = count(array_intersect($allowed_roles, $current_user_roles));
Agreed, @swirtSJW :+1: - updated

2021-03-05 23:01 UTC, swirtSJW approved these changes
Nice work Ethan.

2021-03-05 23:04 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/110183586-3081f600-7ddd-11eb-83f0-684c664c998d.png)

2021-03-05 23:04 UTC, merged