VACMS-4537: Replace vet center ef field.
department-of-veterans-affairs/va.gov-cms pull request #4540
Opened 2021-03-03 18:20 UTC by ethanteague

## Description
See #4537
## Testing done
Visual / behat

## QA steps
@kevwalsh to manually review (please)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-03-03 22:17 UTC, swirtSJW requested changes

2021-03-03 22:17 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +            $blah = '';
We don't speak that way around here  ;)

2021-03-03 22:17 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +          $blah = '';
Or here

2021-03-03 22:17 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +            $blah = '';
Or here

2021-03-03 22:17 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> -          foreach ($option_header as $option_key => $option_item) {
This seems like an odd change.  What was an item has become a key?
The values are not equivalent
![image](https://user-images.githubusercontent.com/5752113/109879814-1a8cfd80-7c44-11eb-9e45-ea8d9426b202.png)
This would change from bing a number to being a string.

2021-03-03 23:01 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +          $blah = '';
Ugh - sorry 'bout that. Was rushing to get this pushed and got sloppy, @swirtSJW

2021-03-03 23:04 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> -          foreach ($option_header as $option_key => $option_item) {
Yeah, you are right, @swirtSJW . Glad you caught that.

2021-03-03 23:07 UTC, ethanteague commented
Thanks for saving my bacon on this one, @swirtSJW :+1:

2021-03-04 05:08 UTC, kevwalsh commented
Why no tugboat environment on this? I'd like to manually qa this one. i realize it's a blocker for #4325.

2021-03-04 12:47 UTC, ethanteague commented
@swirtSJW @kevwalsh - closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4549 - devshop instance didn't build for this one, so figured would just be easier to create an identical instance in hopes of devshop  working on the new one.

2021-03-04 12:47 UTC, closed without merging