VACMS-4281: upgrade migrate plus + drush and add migration tests
department-of-veterans-affairs/va.gov-cms pull request #4590
Opened 2021-03-05 21:28 UTC by acrollet

## Description

See #4281 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-03-05 22:11 UTC, swirtSJW requested changes
@acrollet Amazing work here.   I love what you did with the tests.   That is a huge improvement.

No real changes requested but can't approve until changes are made so our deploy doesn't break due to site alert.   Also the one module version regression in .lock.

2021-03-05 22:11 UTC, swirtSJW commented on tests/phpunit/Migration/VaFormMigrationTest.php
> +    ];
Nice!  I like this test model a lot.

2021-03-05 22:12 UTC, acrollet commented on composer.json
> +        "drupal/site_alert": "1.2",
PR for that is here: https://github.com/department-of-veterans-affairs/devops/pull/8627

2021-03-05 22:13 UTC, acrollet commented on composer.json
> +                "3118800 - Add drush commands to add and remove alerts by label": "https://www.drupal.org/files/issues/2020-10-26/3118800-45.patch"
the updated command can remove by label, I tested locally.

2021-03-05 22:36 UTC, acrollet commented on composer.lock
> +            "version": "1.1.0",
nice catch, thanks!

2021-03-05 22:57 UTC, swirtSJW approved these changes
Approved.  Awesome work.   
I leave it up to bigger brains than mine to work out the timing of this one and https://github.com/department-of-veterans-affairs/devops/pull/8627

2021-03-09 23:12 UTC, ElijahLynn commented on .tugboat/config.yml
> +        - docker-php-ext-install zip
We are on PHP 7.3 now as of a few hours ago. 
```suggestion
```

2021-03-09 23:15 UTC, ElijahLynn commented on tests.yml
> +  command: "drush $DRUSH_ALIAS core-requirements --format=list --severity=2 | grep . && exit 1 || echo 'Success: No Drupal status requirement errors were found.'"
Hrm, didn't realize a list format was an option. Gonna use that in another test to check for PHP errors.

2021-03-10 02:14 UTC, ElijahLynn commented
> time() expects exactly 0 parameters, 1 given

This should be resolved by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4611 which I just merged in from master branch.

2021-03-10 17:45 UTC, ElijahLynn commented
Tested this on cms-test DEV and PROD and IT WORKS!!!! LGTM!

2021-03-10 17:45 UTC, ElijahLynn approved these changes
Tested this on cms-test DEV and PROD and IT WORKS!!!! LGTM!

2021-03-10 17:52 UTC, merged