VACMS 4110: Improve content release integration with AdvancedQueue Part Deux
department-of-veterans-affairs/va.gov-cms pull request #4620
Opened 2021-03-10 22:21 UTC by ndouglas

## Description

See #4110.  My previous PR, #4543, is too broad and touches too many things, and some changes were obsoleted by the upgrade to Drush 10, so this is a more tightly-focused PR.  

## Testing done
Adding behavioral, unit, and kernel tests as needed.  Current tests aren't reliable or even correct, just a starting point.

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue #4110:
    - [ ] users can see the status of all builds on the Content Release page (Tugboat/local) regardless of how it was initiated
    - ~every environment uses the queue for FE build~ (will be done as part of #4617).
    - [ ] advancedqueue runner checks for in-process web builds and requeues the task if any are encountered or if the build has errored
    - [ ] builds complete successfully regardless of how they were initiated
    - [ ] check if the state is removed when job errors
    - [ ] split composer commands into (1) runner (2) queuer

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

2021-03-11 19:11 UTC, ndouglas commented
Weirdly, my image-crop tests are passing locally (whether I run the .feature individually or run all of them together).

2021-03-11 19:34 UTC, ndouglas commented
D'oh.  Realized I missed the `tests/scripts/build-web.sh` call 🤔

2021-03-11 20:54 UTC, ndouglas commented
I've been blasting away at this PR for so long, even my momma thinks that my mind is gone
![maxresdefault](https://user-images.githubusercontent.com/1318579/110853091-31090980-8281-11eb-8fd7-05b9ee4788b7.jpg)

@indytechcook @acrollet I know you guys are like holy crap busy right now, but I'd appreciate any thoughts you have on this PR.  I don't think the existing automated tests are sufficient, but I feel like there's a substantial amount of effort left to implement them.  

I'm thinking that I should "mock" jobs with command payloads like `[ 'exit 0' ]`, `[ 'exit -43' ]`, `[ 'sleep 10; exit 0' ]`, and so forth, but wanted to see if you guys had any further suggestions, requests, etc.

This obviously ain't getting merged and deployed today, so my goal right now is to just get it done in a quasi-reasonable time frame and incurring as little tech debt as possible.  ❤️

2021-03-11 22:06 UTC, acrollet reviewed
the code looks great to me! I added a minor suggestion that's not at all essential.

2021-03-11 22:06 UTC, acrollet commented on docroot/modules/custom/va_gov_build_trigger/src/WebBuildStatus.php
> +  protected const STATE = 'va.web_build_status';
![](https://media.tenor.com/images/106eb75797d89cb5d82c33455160d11c/tenor.gif)

2021-03-11 22:11 UTC, ndouglas commented on composer.json
> +            "find ./docroot/vendor/va-gov/web/build/vagovdev/generated -type f -print0 | xargs -0 sed -i \"s/https:\\/\\/dev-va-gov-assets\\.s3-us-gov-west-1\\.amazonaws\\.com//g\" "
Yeah, that's absolutely worth doing.  I'll check it interactively tomorrow just to make sure.  I never have a good grasp on what's PCRE and what's sed-friendly 😩

2021-03-11 22:13 UTC, acrollet commented on composer.json
> +            "find ./docroot/vendor/va-gov/web/build/vagovdev/generated -type f -print0 | xargs -0 sed -i \"s/https:\\/\\/dev-va-gov-assets\\.s3-us-gov-west-1\\.amazonaws\\.com//g\" "
yeah me neither 😳

2021-03-12 14:02 UTC, indytechcook requested changes
I did a code revie with Nate on zoom and the only change is to remove the extra composer commands since they are just calling drush commands and to update documentation with the new drush commands.

Otherwise this is awesome.

2021-03-15 14:50 UTC, acrollet commented on composer.json
> +            "find /app/docroot/vendor/va-gov/web/build/vagovdev/generated -type f -exec sed -i \"s#https://dev-va-gov-assets\\.s3-us-gov-west-1\\.amazonaws\\.com##g\" {} \\+"
I don't think using `/app` will work on tugboat...

2021-03-15 14:51 UTC, ndouglas commented on composer.json
> +            "find /app/docroot/vendor/va-gov/web/build/vagovdev/generated -type f -exec sed -i \"s#https://dev-va-gov-assets\\.s3-us-gov-west-1\\.amazonaws\\.com##g\" {} \\+"
good catch -- actually inserted that to test locally 😩

2021-03-15 14:53 UTC, indytechcook commented on composer.json
> +            "find /app/docroot/vendor/va-gov/web/build/vagovdev/generated -type f -exec sed -i \"s#https://dev-va-gov-assets\\.s3-us-gov-west-1\\.amazonaws\\.com##g\" {} \\+"
This is also run on BRD fyi

2021-03-15 15:05 UTC, acrollet approved these changes
All feedback addressed, lgtm

2021-03-15 15:10 UTC, ndouglas commented
https://www.youtube.com/watch?v=u_8nAvU0T5Y

2021-03-15 15:22 UTC, indytechcook approved these changes

2021-03-15 15:23 UTC, merged