[WIP] VACMS-4325: New Migrations for updates to Vet Center, MVC and OS, new…
department-of-veterans-affairs/va.gov-cms pull request #4652
Opened 2021-03-11 23:28 UTC by kaise-lafrai

… plugs to accomplish office hours field and skipping rows based on substring

## Description

See _issueid_. 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-03-12 23:39 UTC, swirtSJW reviewed
THanks for getting this across the line @kaise-lafrai   I will test it when down the road.

This is blocked until we get the status push code in place.


I would also like to get  a process plugin `entity_delete` created that could pass the name, lookup the entity then delete it.  It would be avaluable addition.

2021-03-12 23:39 UTC, swirtSJW commented on config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
> +    visnprefix: 'VISN '
I don't think this should be here .

2021-03-23 17:46 UTC, swirtSJW commented
Testing:  This is the base before any of these are run 
![image](https://user-images.githubusercontent.com/5752113/112193349-2e41d900-8bde-11eb-9d2a-9fb7815154c5.png)

2021-03-23 18:25 UTC, swirtSJW commented
MVC migration testing
![image](https://user-images.githubusercontent.com/5752113/112197136-1ec48f00-8be2-11eb-9546-a8a6f3d9489f.png)

![image](https://user-images.githubusercontent.com/5752113/112197520-90044200-8be2-11eb-8bc2-a94d82f88b3d.png)

The number 81  is right.  The other vet_center migration is due to a dependency which is expected.  The 1 failure is not expected.  .  There are no migration messages noted.
The failure was due to a deadlock I believe cause by automated tests running while the migration was running.
![image](https://user-images.githubusercontent.com/5752113/112198531-921ad080-8be3-11eb-8531-3994d46cfa9b.png)
I believe it is unrelated but will watch for it on a second run.

2021-03-23 21:49 UTC, swirtSJW commented
Testing outstationgs worked as expected
![image](https://user-images.githubusercontent.com/5752113/112223010-ae2c6b00-8bff-11eb-8133-09baf5a7cb55.png)


I did see some php notices that I need to investigate
![image](https://user-images.githubusercontent.com/5752113/112223264-0d8a7b00-8c00-11eb-83db-ed5a54d43d9a.png)

```
Notice: Undefined index: endhours in Drupal\va_gov_migrate\Plugin\migrate\process\VAFieldOfficeHours->transform() (line 156 of /var/lib/tugboat/docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php)
#0 /var/lib/tugboat/docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'Undefined index...', '/var/lib/tugboa...', 156, Array)
#1 /var/lib/tugboat/docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php(156): _drupal_error_handler(8, 'Undefined index...', '/var/lib/tugboa...', 156, Array)
#2 /var/lib/tugboat/docroot/core/modules/migrate/src/MigrateExecutable.php(401): Drupal\va_gov_migrate\Plugin\migrate\process\VAFieldOfficeHours->transform(Array, Object(Drupal\migrate_tools\MigrateBatchExecutable), Object(Drupal\migrate\Row), 'field_office_ho...')
#3 /var/lib/tugboat/docroot/core/modules/migrate/src/MigrateExecutable.php(207): Drupal\migrate\MigrateExecutable->processRow(Object(Drupal\migrate\Row))
#4 /var/lib/tugboat/docroot/modules/contrib/migrate_tools/src/MigrateBatchExecutable.php(225): Drupal\migrate\MigrateExecutable->import()
#5 /var/lib/tugboat/docroot/core/includes/batch.inc(295): Drupal\migrate_tools\MigrateBatchExecutable::batchProcessImport('va_node_facilit...', Array, Array)
#6 /var/lib/tugboat/docroot/core/includes/batch.inc(137): _batch_process()
#7 /var/lib/tugboat/docroot/core/includes/batch.inc(93): _batch_do()
#8 /var/lib/tugboat/docroot/core/modules/system/src/Controller/BatchController.php(55): _batch_page(Object(Symfony\Component\HttpFoundation\Request))
#9 [internal function]: Drupal\system\Controller\BatchController->batchPage(Object(Symfony\Component\HttpFoundation\Request))
#10 /var/lib/tugboat/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#11 /var/lib/tugboat/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#12 /var/lib/tugboat/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#13 /var/lib/tugboat/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#14 /var/lib/tugboat/docroot/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#15 /var/lib/tugboat/docroot/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#16 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /var/lib/tugboat/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /var/lib/tugboat/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /var/lib/tugboat/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /var/lib/tugboat/docroot/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /var/lib/tugboat/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#25 {main}
```

2021-03-24 01:43 UTC, swirtSJW commented
Validating the numbers on this one.  I expected the numbers to go down.... but it might just be an accounting error in how migrate tracks.
![image](https://user-images.githubusercontent.com/5752113/112241505-bc3eb380-8c20-11eb-904a-c79137db9198.png)

2021-03-24 01:58 UTC, swirtSJW commented
I validated the number on the vetcenter's.  It works out.
There are 403 currently on prod all lumped in as vet centers.
403 lumped together in CMS > 300 CS  + 81 MVC  + 18 OS  
399 total in VAST  =  399  total in CMS
![image](https://user-images.githubusercontent.com/5752113/112242720-ce215600-8c22-11eb-8b69-4c4b8d29b820.png)

The difference of 4 are attributed to vetcenters that not longer appear in VAST but have never been removed from the CMS.

2021-03-24 14:27 UTC, swirtSJW requested changes
Overall looks good.
Some relatively minor things (see comments) and also we need to add the two new migrations to the periodic tasks yml so they run nightly along with the other facility migrations.
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/tasks-periodic.yml#L28

2021-03-24 14:27 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_os.yml
> +    - va_node_facility_vet_centers
This one is not dependent since it does not lookup the vet center.

2021-03-24 14:27 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +          'endhours' => $hours_clean[$daylong]['endhours'],
These are not always set, so we are getting notices like 
```
Notice: Undefined index: starthours in Drupal\va_gov_migrate\Plugin\migrate\process\VAFieldOfficeHours->transform() (line 155 of /var/lib/tugboat/docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php)
```
and 
```
Notice: Undefined index: endhours in Drupal\va_gov_migrate\Plugin\migrate\process\VAFieldOfficeHours->transform() (line 156 of /var/lib/tugboat/docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php)

```
Needs a ternary to check to see if it exists, or force it to exist higher up.

2021-03-24 14:27 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +
Each of these cases use a lot of repeated code.   I suggest replacing the entire switch  with  something like this:
```
//Bring this definition up from where you define it farther down.
$daymap = [
   'monday' => '1',
   'tuesday' => '2',
  'wednesday' => '3',
   'thursday' => '4',
   'friday' => '5',
   'saturday' => '6',
   'sunday' => '0',
 ];
$low_day = strtolower($day)
if (preg_match('(AM|PM)', $hour) === 0) {
    $hours_clean[$low_day']['comment'] = $hour;
 }
  else {
      $hours_clean[$low_day]['starthours'] = $arr_starthours[$daymap[$low_day']];
      $hours_clean[$low_day]['endhours'] = $arr_endhours[$daymap[$low_day']];
  }

```

2021-03-24 14:29 UTC, swirtSJW commented on config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
> +        - address3
I'm still examing the data on this one to see what it appropriate.

2021-03-24 14:39 UTC, acrollet commented
> Some relatively minor things (see comments) and also we need to add the two new migrations to the periodic tasks yml so they run nightly along with the other facility migrations.
> https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/tasks-periodic.yml#L28

If these new migrations will be running nightly is it worth adding [tests for them](https://github.com/kaise-lafrai/va.gov-cms/tree/VACMS-4325-Vet-Center-VAST-Migration/tests/phpunit/Migration)?

2021-03-24 14:41 UTC, swirtSJW commented on config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
> +        - address3
I would like to do this
![image](https://user-images.githubusercontent.com/5752113/112328889-1b3a1200-8c8d-11eb-845d-015319169c4c.png)
Essentially putting `address_1` into `address_line1` and then concatenating `address_2` and `address_3` and putting it into address_line2

2021-03-24 16:59 UTC, swirtSJW commented on config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
> +        - address3
I've updated this.

2021-03-24 19:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +
I resolved this.

2021-03-24 19:59 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
> +          'endhours' => $hours_clean[$daylong]['endhours'],
I resolved these.  No notices appear after running the migrations now.

2021-03-24 20:07 UTC, swirtSJW approved these changes

2021-03-24 20:15 UTC, swirtSJW commented
I did a little refactoring of the hours process plugin and validated that even the extremes work 
![image](https://user-images.githubusercontent.com/5752113/112377456-26586680-8cbc-11eb-94ce-ca6a6929d785.png)

2021-03-24 20:20 UTC, swirtSJW approved these changes

2021-03-24 21:15 UTC, swirtSJW commented
Hmmm just ran MVC and nothing was created  
![image](https://user-images.githubusercontent.com/5752113/112384226-87843800-8cc4-11eb-8db2-c45a7d5e5c40.png)
investigating.

2021-03-24 21:40 UTC, swirtSJW commented
I think that failure ^^ was a data endpoint fluke.  There should have been 2496 items processed.  The fact that there were only 375 I get the impression that the dataset from the endpoint got cut off.   Running the migration again behaved as expected 
![image](https://user-images.githubusercontent.com/5752113/112387343-05960e00-8cc8-11eb-8057-a1b2979cb97b.png)

2021-03-24 21:49 UTC, swirtSJW commented
There are 8 mobile vet centers  that did not end up with a proper assignment to the parent vet center.  This is due to the new names from VAST using the state if there are multiples.
![image](https://user-images.githubusercontent.com/5752113/112388231-3b87c200-8cc9-11eb-98db-62013f13fcc8.png)


That is acceptable.  They will need to be assigned by hand.

2021-03-24 21:51 UTC, swirtSJW commented
Nice work Kaise.

2021-03-24 21:52 UTC, merged

2021-03-25 19:54 UTC, swirtSJW commented
Deployment record
1. vetcenter facility migration 
![image](https://user-images.githubusercontent.com/5752113/112535162-55d1a680-8d82-11eb-84d1-81a2b3b5b94c.png)

2021-03-25 20:23 UTC, swirtSJW commented
We are holding on running the outstation migration until the facility status view is updated to allow editors to use it.