VACMS-4731: Add vc caps view.
department-of-veterans-affairs/va.gov-cms pull request #4740
Opened 2021-03-19 13:28 UTC by ethanteague

## Description
See #4731

## Testing done
VIsual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/111787172-04627c80-8895-11eb-9363-217562003de8.png)
![image](https://user-images.githubusercontent.com/2404547/111787186-075d6d00-8895-11eb-964f-82fdd953fe6e.png)

## QA steps
@kevwalsh - I added a block just below main content, and disabled (you'll need to enable it for qa). I tested as Vanessa, both with the Escanaba section added, and without, to ensure the edit buttons appear only when user has appropriate perms. You should be able to see the block on Escanaba VC, but nowhere else.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-03-19 15:48 UTC, kevwalsh requested changes
i think

2021-03-19 15:48 UTC, kevwalsh commented on config/sync/views.view.vet_center_facility_listing.yml
> +      arguments:
i think this is more complex than it needs to be. We shouldn't need relationships. Just a TID argument, because this will alwys only appear on the taxonomy/term/TID page

2021-03-19 17:24 UTC, ethanteague commented on config/sync/views.view.vet_center_facility_listing.yml
> +      arguments:
@kevwalsh  I don't know how to get that tid arg without a token, and I can only get the token with a relationship. Is there another way to do this?

2021-03-19 17:26 UTC, ethanteague commented on config/sync/block.block.views_block__vet_center_facility_listing_vc_caps_block.yml
> +id: views_block__vet_center_facility_listing_vc_caps_block
Will have to shorten this a bit - gets us over 64 chars. I'll make it vc_facility_listing

2021-03-19 19:24 UTC, ethanteague commented
Updated, @kevwalsh :+1:

2021-03-22 12:50 UTC, kevwalsh requested changes
Looking good. One small change here: 

![Escanaba_Vet_Center___VA_gov_CMS](https://user-images.githubusercontent.com/643678/111992164-7cc27b00-8aeb-11eb-857b-ceb75be8ca8a.png)

2021-03-22 15:36 UTC, swirtSJW commented on config/sync/migrate_plus.migration.facility_health_care_service_2.yml
> +    - id
All these migration structure changes seem to be the result of an update to migrate plus module.   No issues with them.

2021-03-22 20:31 UTC, swirtSJW approved these changes

2021-03-22 20:32 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/112054632-304b5f80-8b2c-11eb-816d-a263d7f1ad52.png)

2021-03-22 20:33 UTC, merged