VACMS-4628: Add revision log message validation to vcs.
department-of-veterans-affairs/va.gov-cms pull request #4853
Opened 2021-03-29 14:02 UTC by ethanteague

## Description
See #4628

## Testing done
Visual

## QA steps
As an administrator, edit any existing vc node type without adding a revision log message. 
Visually verify that a form error is thrown, indication you need to add a revision log message.
Add a message, and confirm that form saves without error being thrown.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-04-01 15:36 UTC, kevwalsh commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
Not pushing back on this going to va_gov_vet_center, but i think it's likely this becomes more widely adopted by other content types (possibly all!).

2021-04-01 15:50 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
@ethanteague to Kevs point  ^^ ok to leave it in va_gov_backend, lets just move it into a call to
_va_gov_backend_require_revision_message($form, $form_id)

2021-04-01 17:30 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
Updated, @swirtSJW @kevwalsh

2021-04-01 17:37 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if (empty($form_state->getValue('revision_log')[0]['value'])) {
I don't think we can avoid it, here, @swirtSJW. Those methods return the inverse of what is expected.
![image](https://user-images.githubusercontent.com/2404547/113332569-540e6280-92ef-11eb-8533-da77d05c9a86.png)

2021-04-07 15:25 UTC, swirtSJW requested changes

2021-04-07 15:25 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> + * Adds Validation to check for an empty Appointment lead-in field.
This seems to be copy pasta.

2021-04-07 15:26 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if (empty($form_state->getValue('revision_log')[0]['value'])) {
`$form_state->isValueEmpty('revision_log')`  returns TRUE  of there is something in it?

2021-04-08 12:42 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if (empty($form_state->getValue('revision_log')[0]['value'])) {
Yep!

2021-04-09 04:15 UTC, kevwalsh requested changes
Forms seem to be invalidating properly, but i don't see a red asterisk to indicate required state. I feel like i remember them being there last time i QAd this.

2021-04-09 12:40 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if (empty($form_state->getValue('revision_log')[0]['value'])) {
I just update to this  `if ($form_state->isValueEmpty(['revision_log', '0', 'value'])) {`  It is still digging, but using the api to do it.


I also adjusted the error level so the link to the form element would work.

$form_state->setErrorByName('revision_log][0][value'

2021-04-09 12:49 UTC, swirtSJW approved these changes
Tested with single and bulk operations.  Works as intented.

2021-04-09 12:50 UTC, swirtSJW commented
> Forms seem to be invalidating properly, but i don't see a red asterisk to indicate required state. I feel like i remember them being there last time i QAd this.

The link was pointing to an id that does not exist.  I resolved it.

2021-04-09 14:07 UTC, swirtSJW commented
I misread Kev's comment   I fixed the validation error of the link not taking you to the form field, but yes the field is missing its required indicator.   Since it is not really a configurable field it is not just a quick config setting.  
this approach could work  but I hate scattering this logic all over the place..... though maybe just setting it required in teh base field would remove all the other custom validation... it would just work
https://www.drupal.org/project/drupal/issues/308352#comment-13371248

2021-04-12 11:17 UTC, ethanteague commented
> Forms seem to be invalidating properly, but i don't see a red asterisk to indicate required state. I feel like i remember them being there last time i QAd this.

They weren't there, but I'll look for a way to implement this, @kevwalsh

2021-04-12 11:56 UTC, ethanteague commented
Revision log required indicator added, @kevwalsh

2021-04-12 12:45 UTC, kevwalsh commented
Hmm, no tugboat environment yet.

2021-04-13 13:53 UTC, swirtSJW approved these changes

2021-04-13 17:16 UTC, swirtSJW commented
This tests out good 
![image](https://user-images.githubusercontent.com/5752113/114593719-675bef00-9c5a-11eb-938a-527895f0202e.png)

2021-04-13 17:17 UTC, swirtSJW commented
Looks like we have a failing test.

2021-04-13 17:46 UTC, ethanteague commented
> Looks like we have a failing test.

Passes for me locally, @swirtSJW - just looped in @ElijahLynn in slack.

2021-04-13 18:48 UTC, ethanteague commented
Tests passing, @swirtSJW

2021-04-13 19:10 UTC, ElijahLynn commented
```
 root@php:/var/lib/tugboat# curl https://pr4911-iqbvykov5ruybyetpszrgwwzmm17z2ay.ci.cms.va.gov
The website encountered an unexpected error. Please try again later.<br /><em class="placeholder">Error</em>: Call to undefined method Drupal\user\Form\UserLoginForm::getEntity() in <em class="placeholder">va_gov_backend_form_alter()</em> (line <em class="placeholder">440</em> of <em class="placeholder">modules/custom/va_gov_backend/va_gov_backend.module</em>).
```

2021-04-15 20:51 UTC, swirtSJW approved these changes

2021-04-15 20:53 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/114936927-19d2b400-9e0b-11eb-8e39-1cff34477622.png)

2021-04-15 20:53 UTC, merged