VAGOV-4311: Add custom menu perm module.
department-of-veterans-affairs/va.gov-cms pull request #4894
Opened 2021-04-01 16:12 UTC by ethanteague

## Description
See #4311

## Testing done
Visual / behat / phpunit

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/110260962-542f7280-7f7c-11eb-96be-d56825c4e1d7.png)
![image](https://user-images.githubusercontent.com/2404547/110260974-58f42680-7f7c-11eb-8947-690904c647da.png)
![image](https://user-images.githubusercontent.com/2404547/110260983-5db8da80-7f7c-11eb-8649-32d99c9b65b6.png)
![image](https://user-images.githubusercontent.com/2404547/110260989-627d8e80-7f7c-11eb-98a9-cfa74111cae7.png)
![image](https://user-images.githubusercontent.com/2404547/110260993-66a9ac00-7f7c-11eb-99ef-911fb4f465bd.png)
![image](https://user-images.githubusercontent.com/2404547/110261002-6c06f680-7f7c-11eb-82d2-44a457676a32.png)
![image](https://user-images.githubusercontent.com/2404547/110262154-c0ac7080-7f80-11eb-84f2-3cc9845f249c.png)
![image](https://user-images.githubusercontent.com/2404547/110262160-c4d88e00-7f80-11eb-9351-8d4ee688dad4.png)

## QA steps
- As an administrator, go to `admin/config/content/va_gov_menu_access`
- Check the following roles: `Content creator - VAMC` & `Content editor`
- Check the following menus: `VA Butler health care` & `VA Bay Pines health care`
- Enter the following paths (one per line): `/butler-health-care/pharmacy` & `*/work-with-us`
- Go to `/user/1730/roles` and check the following roles: `Content creator - VAMC` , `Content editor` , `Content reviewer` , `Content publisher`
- Go to `user/1730/workbench_access` and check `VA Altoona health care` & `VA Butler health care`
- Sign out, and login as vanessa.luxen@va.gov
- Go to `/node/2551/edit` click save, and visually verify that you cannot save, and see `The path alias you have created has already been reserved.` message
- Go to `/node/2560/edit` click save, and visually verify that you cannot save, and see `The path alias you have created has already been reserved.` message
- Go to `/node/1332/edit` and visually verify that you see an access denied message
- Go to `node/add/health_care_region_detail_page` open up the menu settings, and visually verify that only VA Butler vamc items are available, and all other vamc items are greyed out and unclickable
- Go to `/admin/structure/menu/` and visually verify access is denied.
- Go to `/admin/content?title=&type=All&moderation_state=All&owner=185` and visually verify you can only edit Detail pages.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-04-05 14:40 UTC, kevwalsh requested changes
This looks like it's on the right track but there are a couple bugs and need some additional details. Possibly some UX writing attention. 

One more comment: i don't see anything about making specific rules for the `health_care_region_detail_page` ... one of the ACs is 

> i shouldn't be able to add or edit menu items for content types other than Detail Pages

As noted, as vanessa.luxen@va.gov, i was able to (sort of?) create a menu item for an event.

2021-04-05 14:40 UTC, kevwalsh commented on docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.es6.js
> +          if (opt && opt.text.includes(" | Disabled")) {
Looks like this can be customized, which we may want to do.

2021-04-05 14:40 UTC, kevwalsh commented on docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.es6.js
> +          if (opt && opt.text.includes(" | Disabled")) {
Nice! 

<img width="1207" alt="Create_Detail_Page___VA_gov_CMS_and_iMac" src="https://user-images.githubusercontent.com/643678/113584949-8f63a680-95f9-11eb-9395-10d88e4ed267.png">

2021-04-05 14:40 UTC, kevwalsh commented on docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.es6.js
> +          if (opt && opt.text.includes(" | Disabled")) {
Actually, looks like the menu hierarchy is totally scattered there ^^^ . Items have retained the correct depth, but not the correct parents or weight.

2021-04-05 14:40 UTC, kevwalsh commented on docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.es6.js
> +          if (opt && opt.text.includes(" | Disabled")) {
Related possibly to the order:

As vanessa.luxen@va.gov, i went to create an event. I checked "Provide a menu link"

The default menu item is `------ Health services | Disabled`, which should not be eligible at all (but appears enabled in my browser, see screenshot).  

<img width="1166" alt="Create_Event___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/113585873-cd14ff00-95fa-11eb-8c42-1b12411abf52.png">

When I saved the event, no menu item was apparently created (form validated fine), and i went back to edit, and saw this, which seems unusual.  

<img width="476" alt="Edit_Event_asdf___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/113585972-ef0e8180-95fa-11eb-923e-6bf4537107d5.png">

2021-04-05 18:55 UTC, swirtSJW reviewed
Some thoughts

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Form/VaGovMenuAccessConfigForm.php
> +    $menus = !empty($form_state->getValue('menus')) ? $form_state->getValue('menus') : '';
```suggestion
    $menus = !empty($form_state->getValue('menus')) ? $form_state->getValue('menus') : [];
```

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Form/VaGovMenuAccessConfigForm.php
> +    if ($menus) {
```suggestion

```

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Form/VaGovMenuAccessConfigForm.php
> +      foreach ($form_state->getValue('menus') as $menu_key => $menu_val) {
```suggestion
      foreach ($menus as $menu_key => $menu_val) {
```

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Form/VaGovMenuAccessConfigForm.php
> +          $selected_menus[$menu_key] = $menu_val;
Could use a comment here to describe why we want to collect menus that are not numeric.

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Routing/AdminRouteSubscriber.php
> + * Limits access to admin paths by Extending RouteSubscriberbase.
This seems to generic to be helpful.

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  // Sort parents into universal and single allowance arrays.
Could use examples here of what makes something universal or single

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +
```suggestion
```

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +    if (!empty($form['menu']['link']['menu_parent']['#options'])) {
Could use a comment to explain what this is looking for or what it indicates to you if there are #options present.

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +          $uuids_with_vals[$menu_id] = [
IN line 137 you are giving the option for $menu_id to be an empty string.  Here you are creating an array with a key of an empty string.   You are going to get odd results since you are putting in numeric keys and I think empty strings are also going to generate numeric keys. and there is no allowance for when those numeric keys collide or get re-keyed.

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +          $uuids_only[] = $menu_id;
Here you could also end up with an empty value.

2021-04-05 18:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +        $uri_parts = explode('node/', $menu_item->get('link')->uri);
I am a little uneasy about this as there are 41 other words that end in node.  https://lotsofwords.com/*node that would give you unintended results if exploded like this.  It would be good to check that node/  appears as the first  5 chars first.

2021-04-05 19:12 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Routing/AdminRouteSubscriber.php
> + * Limits access to admin paths by Extending RouteSubscriberbase.
Lol - yeah.....I got pretty lazy on that one, @swirtSJW. I'll make this more meaningful.

2021-04-05 19:13 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +        $uri_parts = explode('node/', $menu_item->get('link')->uri);
Great catch / great tool, @swirtSJW ! Point taken - will tighten this up :+1:

2021-04-05 19:14 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +          $uuids_only[] = $menu_id;
ugh. Yep, @swirtSJW - :+1:

2021-04-05 19:14 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +          $uuids_with_vals[$menu_id] = [
Yep, @swirtSJW - I'll fix this up :+1:

2021-04-05 19:15 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Form/VaGovMenuAccessConfigForm.php
> +      foreach ($form_state->getValue('menus') as $menu_key => $menu_val) {
Ugh - my bad, @swirtSJW. Will fix :+1:

2021-04-06 12:55 UTC, kevwalsh commented
@ethanteague i'm making this a draft because we don't want to merge this until we go through some design review.

2021-04-07 12:08 UTC, kevwalsh commented on docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.es6.js
> +          if (opt && opt.text.includes(" | Disabled")) {
> Looks like this can be customized, which we may want to do.

I had a look at this with @rachel-kauff. Decision was to just 

- [ ] remove the ` | Disabled` string altogether. 

Separately, we talked about removing the _other_ ` (disabled)` string that is appended to menu items that have menu items that don't appear in the left nav.  Can you look at the lift in removing this to? From an editor perspective, this isn't useful information because they can't control these things anyway. 

- [ ] Remove  ` (disabled)` string appended on menu items.

2021-04-07 12:18 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.es6.js
> +          if (opt && opt.text.includes(" | Disabled")) {
I'll just target the `Disabled` for removal in the js script that adds the disabled attribute, @kevwalsh - easy to do.

2021-04-09 04:40 UTC, kevwalsh commented
Moving this to #4988, for next sprint.

2021-04-12 20:43 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.es6.js
> +          if (opt && opt.text.includes(" | Disabled")) {
> Related possibly to the order:
> 
> As [vanessa.luxen@va.gov](mailto:vanessa.luxen@va.gov), i went to create an event. I checked "Provide a menu link"
> 
> The default menu item is `------ Health services | Disabled`, which should not be eligible at all (but appears enabled in my browser, see screenshot).
> 

This will be resolved in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4911

2021-04-13 03:05 UTC, kevwalsh requested changes
A few things. 

### 1. New spec for config

I've added new config spec on #4988, which should be added to our config

i also added some new ACs. 

### 2. Defect for parents

![VAMC_Menu_Custom_Access___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114490048-27592580-9be2-11eb-8356-27f682ecd116.png)


As admin, I entered the above config at `/admin/config/content/va_gov_menu_access` and cleared Cache, Then logged in as Vanessa, and the entire menu is disabled. 

- [x] I should be allowed to add the Locations as parents (eg for Facility maps).


![Create_Detail_Page___VA_gov_CMS_and__1__AP__Solution_Brainstorm__OPEN__·_Issue__4809_·_department-of-veterans-affairs_va_gov-cms](https://user-images.githubusercontent.com/643678/114489757-b0239180-9be1-11eb-809b-a99badc1f02f.png)


### 3. Defect with default menu item parent value

1. As vanessa.luxen@va.gov, i created a detail page

2. Checked off "Provide a menu link" 

3. Default value for me is just the VA Butler health care homepage (which doesn't look disabled _until_ you click the dropdown, and i leave as is. (screenshot 1)

4. If i save as is, it saves properly, form validates, but without creating a menu item (node 18371). This is confusing UX. Not sure how to best handle the default value. 

Maybe a "- Select a value -" that doesn't validate. Ideas? 


![Create_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114489926-f4af2d00-9be1-11eb-8e36-a671ab1edc49.png)


### 4. Content admin followup to the above

5. If i go back to the same node 18371 above , the default value has _changed_ to `<Pittsburgh health care>`, which must be the default menu item spec'd in config for this content type (see #4847, which should be taking care of that). But regardless of 4847, there's some significnat risk that this could happen accidentally later. 

![Edit_Detail_Page_Test_invalid_menu_item_at_root_VAMC_level___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114489224-c54bf080-9be0-11eb-811b-e9b55a9e73a4.png)

- [x] I think this situation can be avoided if we just don't let editors create "empty" menu items (see 4 above)

### 5. Content types with disabled menu items

- [x] Instead of disabling menu items for certain content types, we should hire this entire fieldset if possible. 

If there are issues, let's explore a different UX. 

![Create_News_Release___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114489266-dc8ade00-9be0-11eb-8b9e-4429620ad48a.png)

### 6. Config menu item label

![VAMC_Menu_Custom_Access___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114490222-72733880-9be2-11eb-810d-c40651404f62.png)

- [x] Menu item label should match h1 for the config page


### 7. Config field labels and help text

- [x] Use `URL` in both field labels
- [x] replace the ` | use` with `. Use`

![VAMC_Menu_Custom_Access___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114490364-b7976a80-9be2-11eb-870a-b16b729364fd.png)

### 8. Some new ACs that came up on Friday Apr 9 and added to #4988 

In the UI parent item selector, when creating a `health_care_region_detail_page`, i should be able to see:
- [x]  any menu item that is eligible to have children (and its children, which should also be eligible to have children)
- [x]  the ancestors of any menu item that is eligible to have children (_except the top level_, which is always the Health Care System, and is redundant)

I realize this last one complicates things and we should discuss feasibility / LOE.

2021-04-15 21:15 UTC, ethanteague commented
Back to you, @kevwalsh - more than happy to go over this with you via zoom.

2021-04-16 13:11 UTC, kevwalsh commented
@ethanteague as vanessa.luxen@va.gov i see no menu options at https://pr4894-h9posaleh9umnvsbhxxfydmjbe3wrkcj.ci.cms.va.gov/node/add/health_care_region_detail_page 

![Create_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/115029069-97420700-9e93-11eb-8fef-62a9652dc7df.png)

2021-04-16 13:15 UTC, kevwalsh requested changes
Also some minor label changes to the config page 

`Prevent menu editing of "Detail Page" nodes for non-admin users at these URL paths`

![VAMC_Menu_Custom_Access___VA_gov_CMS](https://user-images.githubusercontent.com/643678/115029689-3cf57600-9e94-11eb-95f8-83aed59a57e1.png)

2021-04-16 15:20 UTC, ethanteague commented
```
5. Content types with disabled menu items
 Instead of disabling menu items for certain content types, we should hire this entire fieldset if possible.
If there are issues, let's explore a different UX.
```
Can we do this in a different issue, @kevwalsh? It's a little more complicated to handle this than I anticipated, and hoping we can consider it as slightly beyond the original scope.

Updated to address other items in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4894#issuecomment-821163312 & https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4894#pullrequestreview-637685000

2021-04-19 01:47 UTC, kevwalsh commented
Yeah we can handle that in a separate issue i suppose. 

I'm having a really hard time QAing this. As admin, i'm making sure that two pages with menu items exist that match the URL at Butler:

https://pr4894-h9posaleh9umnvsbhxxfydmjbe3wrkcj.ci.cms.va.gov//butler-health-care/programs
https://pr4894-h9posaleh9umnvsbhxxfydmjbe3wrkcj.ci.cms.va.gov//butler-health-care/internships-fellowships

I cleared cache. 

But as vanessa.luxen@va.gov i still don't see any menu options when i go to https://pr4894-h9posaleh9umnvsbhxxfydmjbe3wrkcj.ci.cms.va.gov/node/add/health_care_region_detail_page

The field briefly appears then disappears.

2021-04-19 01:50 UTC, kevwalsh commented
> 5. Content types with disabled menu items
> Instead of disabling menu items for certain content types, we should hire this entire fieldset if possible.
> If there are issues, let's explore a different UX.

FWIW, this fieldset is gone completely now from all node creation pages as vanessa.luxen@va.gov

2021-04-19 12:20 UTC, ethanteague commented
> > 1. Content types with disabled menu items
> >    Instead of disabling menu items for certain content types, we should hire this entire fieldset if possible.
> >    If there are issues, let's explore a different UX.
> 
> FWIW, this fieldset is gone completely now from all node creation pages as [vanessa.luxen@va.gov](mailto:vanessa.luxen@va.gov)

Apologies for the headache, @kevwalsh - looks like the build stalled, and didn't pick up my latest changes. I'm gonna rebuild the instance.

2021-04-19 12:37 UTC, ethanteague commented
Okay, @kevwalsh - should be working now.
![image](https://user-images.githubusercontent.com/2404547/115237312-6dcee880-a0ea-11eb-8dc7-8c51c44c8cf3.png)

2021-04-19 13:47 UTC, kevwalsh commented
@ethanteague Can we avoid this scenario somehow? Where if no eligible parents exist, like at Butler currently, no ancestors show up? 

![Screen_Shot_2021-04-19_at_9_45_35_AM](https://user-images.githubusercontent.com/643678/115246742-29484a80-a0f4-11eb-954f-6e44d056d145.png)

2021-04-19 13:52 UTC, kevwalsh commented
Defect:

- [ ] As a Publisher at Pittsburgh, Research (/pittsburgh-health-care/research) is missing

![Screen_Shot_2021-04-19_at_9_48_00_AM](https://user-images.githubusercontent.com/643678/115247371-bc818000-a0f4-11eb-8245-5bc103823c72.png)

2021-04-21 21:00 UTC, kevwalsh requested changes
Defect

- [ ] as user 34 i'm going to https://pr4894-h9posaleh9umnvsbhxxfydmjbe3wrkcj.ci.cms.va.gov/node/add/health_care_region_detail_page and i can't successfully create a menu item for my detail page

Here's the node i was working with: https://pr4894-h9posaleh9umnvsbhxxfydmjbe3wrkcj.ci.cms.va.gov/node/18598

Node validates but breadcrumb is wrong and if i go back to edit the node, the menu item option is no longer checked. 


![Create_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/115622075-67489880-a2c5-11eb-9567-8b436b419191.png)

2021-04-21 21:38 UTC, swirtSJW reviewed
Just added a couple of thoughts before I lose them.  It is an incomplete review as I need to get on the dashboard review.

2021-04-21 21:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/AccessChecks/RouteAccessChecks.php
> +    $admin_role_count = count(array_intersect($admin_roles, $current_user_roles));
This pattern we are using all over the place.   I would like to move this into the perms service as a public method  `->hasAdminRole()` that does this same logic and returns a bool.   That way we are defining in one spot what an admin role is.

2021-04-21 21:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Form/VaGovMenuAccessConfigForm.php
> +
This would be where you would load your user perms service and pass it in.

2021-04-21 22:40 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +    if (strpos($form_id, 'health_care_region_detail_page') === FALSE) {
@kevwalsh this was something I missed that I did when I was testing. This missed check was allowing the menu settings fields to be disabled on new Detail pages (node add). There is logic further down that adds this disabling to detail page _edit_ forms, which I thought was necessary (but I am happy to remove).

Anyway, fixing my conditional resolves the faulty page / breadcrumb creation issue:
![image](https://user-images.githubusercontent.com/2404547/115629765-fad39680-a2d0-11eb-961b-1da29642e26b.png)
![image](https://user-images.githubusercontent.com/2404547/115629783-0030e100-a2d1-11eb-8a4b-a9f41bf9322d.png)

2021-04-21 23:34 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/AccessChecks/RouteAccessChecks.php
> +    $admin_role_count = count(array_intersect($admin_roles, $current_user_roles));
I'm having a challenge with this, @swirtSJW. I want to create a static method, so that I can call this new method without having to use DI (nervous about adding complexity without much time to resolve issues). Adding the static method is no problem, the issue I'm having is with accessing another method in the same class inside of my new static method. I want to get `currentUser` in my new `hasAdminRole`, but having trouble figuring this out.

2021-04-21 23:40 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Form/VaGovMenuAccessConfigForm.php
> +
Apologies, @swirtSJW - I don't understand why I'm adding the user perms service, here.

2021-04-22 12:42 UTC, kevwalsh requested changes
Defect

As an admin, i create a Detail page without a menu item, and i see this. 

![Create_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/115715903-9a7f3c00-a346-11eb-85af-9d3b329c3e78.png)

2021-04-22 12:45 UTC, kevwalsh requested changes
Related to the last issue

As admin, if i _add_ a menu item (with an eligible or non-eligible menu item, doesn't seem to matter), the Parent item value it doesn't "stick" and i basically get the same error as above, albeit with the menu item checkbox checked.

2021-04-22 12:47 UTC, kevwalsh requested changes
Same issues as above for user 34, a content publisher with access to only one section. Can't save a detail page right now, with or without a menu item.

2021-04-22 21:34 UTC, swirtSJW commented
After looking at this with @kevwalsh there are two outstanding concepts we need to account for.
1) the addition of the default has to be done for all nodes where the menu setttings exist.
2) the reduction of the menu choices to only a set of items, has to be constrained to health_care_region_detail_page nodes.

2021-04-22 21:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  _va_gov_backend_set_default_option_on_new_nodes($form, $form_state);
Comment needs to go away and this needs to be renamed to reflect what it is doing.
```suggestion
  _va_gov_backend_set_menu_parent_to empty_default($form, $form_state);
```

2021-04-22 21:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function _va_gov_backend_set_default_option_on_new_nodes(array &$form, FormStateInterface $form_state) {
```suggestion
function _va_gov_backend_set_menu_parent_to empty_default(array &$form, FormStateInterface $form_state) {
```

2021-04-22 21:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> + * Sets the owner field to a select option prompt.
Description is not right.

2021-04-22 21:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  // Don't set parent menu item on new nodes.
Comment no longer accurate

2021-04-22 21:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $form['#after_build'][] = '_va_gov_backend_alter_parent_menus';
This method is not specific enough.  'alter ' is not meaningful.
```suggestion
    $form['#after_build'][] = '_va_gov_backend_set_menu_parent_requirement';
```

2021-04-22 21:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function _va_gov_backend_alter_parent_menus(array $form, FormStateInterface $form_state) {
```suggestion
function _va_gov_backend_set_menu_parent_requirement(array $form, FormStateInterface $form_state) {
```

2021-04-22 21:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> + * Returns form with empty option set for parent menu item.
No longer accurate.

2021-04-22 23:28 UTC, ethanteague commented
> After looking at this with @kevwalsh there are two outstanding concepts we need to account for.
> 
> 1. the addition of the default has to be done for all nodes where the menu setttings exist.
> 2. the reduction of the menu choices to only a set of items, has to be constrained to health_care_region_detail_page nodes.

Addressed both in lates push, @swirtSJW

2021-04-23 03:08 UTC, swirtSJW requested changes

2021-04-23 03:08 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +      // Loop through them, and decide whether it should be allowed in options.
From this point and below there is a whole lot of grinding going on that I am not sure is necessary.  I am so lost in all the loops and ifs leading up to this that I am a bit lost.   I am not sure if all the alias loading and juggling below is needed.  It certainly is not performant.   I think we need to look closer at this.

2021-04-23 11:12 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +    $form_type_flag = $form_type_flag;
Sorry, should be 'vet-center'. Changed.

2021-04-23 11:14 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  if (strpos($form_id, 'vet_center') === TRUE) {
I wanted to make sure that the menu disabling logic only targets VAMC's and can't spill over into vet center content types.

2021-04-23 13:13 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  if (strpos($form_id, 'vet_center') === TRUE) {
My understanding is this is only supposed to be fore detail pages so there should be no other spill over.

2021-05-05 17:20 UTC, swirtSJW commented
I am working on this now.

2021-05-17 16:35 UTC, swirtSJW commented
Seems to be an issue with both the original and this one not grandfathering in existing patterns that may have been done by a content_admin.
![image](https://user-images.githubusercontent.com/5752113/118524567-492b5800-b70c-11eb-95fc-44199a4a696a.png)


An existing page with a path that does not match an allowed pattern, should bypass menu reduction.

2021-05-20 19:49 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    // End of @todo removal.  Nothing below this point will run.
Everything beyond this point can not get executed yet as stakeholders aren't ready for it, and some requirements may be changing as a result of other work that is being done in the full epic.

2021-05-20 20:05 UTC, indytechcook commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    return (!empty($this->formState->getValue(['menu', 'menu_parent']))) ? TRUE : FALSE;
```suggestion
    return !empty($this->formState->getValue(['menu', 'menu_parent']));
```

This _should_ work...

2021-05-20 20:18 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    return ($this->formState->getValue(['menu', 'enabled']) === 1) ? TRUE : FALSE;
```suggestion
    return $this->formState->getValue(['menu', 'enabled']);
```
Riffing on @indytechcook 's suggestion above, this should return a bool, so I don't _think_ you need the ternary.

2021-05-20 20:21 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    $allowed_separators = ['About'];
Wondering if this should live in config, @swirtSJW ? Seems like this is gonna be something we need to mess with on a regular basis.

2021-05-20 20:27 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      $form['menu']['#attributes'] = ['style' => 'display:none'];
@swirtSJW I'm curious why you are adding an inline style, in lieu of something like 
```suggestion
      $form['menu']['#attributes']['class'][] = 'element-invisible';
```

2021-05-20 20:31 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  $form['#after_build'][] = '_va_gov_menu_access_set_menu_parent_requirement';
This is the kind of thing that I would have bungled, @swirtSJW - I wouldn't think to separate these concerns into two different functions. Nice.

2021-05-20 20:33 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +    $form_state->setErrorByName('menu][menu_parent', t('Menu parent item cannot be empty.'));
Just for confirmation: this is setting an error on the appropriate thing in the parent menu widget, and not going nuclear and adding a bunch of red to every field in the widget, correct, @swirtSJW ?

2021-05-20 20:34 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.services.yml
> +    arguments: ['@config.factory', '@entity_type.manager', '@path_alias.manager', '@va_gov_user.user_perms']
Gonna ask you to school me on arguments in services when you have some time, @swirtSJW

2021-05-20 20:34 UTC, ethanteague reviewed
Ty +1000 for taking this on, @swirtSJW

2021-05-20 21:14 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    return (!empty($this->formState->getValue(['menu', 'menu_parent']))) ? TRUE : FALSE;
getValue returns NULL if it finds nothing.  Which then breaks the contract of returning a bool.  Or are you saying it is no longer needed because the return-type declaration of bool will actually cast it to a bool?

2021-05-20 21:21 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    $allowed_separators = ['About'];
Yah it is only here because that is where you had it and there is only 1.   Also I think as we roll menu goverance to other content types and other products, we will have too many variations to handle in config so some of this may move back into code. 
I think when we get all the aliases locked down to using the menu, then we can change much of the logic to not rely on aliases, but to go with more of an allowed menu pattern structure.

2021-05-20 21:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      $form['menu']['#attributes'] = ['style' => 'display:none'];
Yah I hemmed and hawed on that one for a bit.  I mainly chose the inline style because I did not want a css snafu surfacing it.  I could be talked either way on it.  It felt dirty, but also felt right ;)

2021-05-20 21:25 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      ?? $this->checkForSimpleMatch($alias);
Yep  Null coalescing operator is one of the cool new php items that makes this kind of thing so slick.

2021-05-20 21:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +    $form_state->setErrorByName('menu][menu_parent', t('Menu parent item cannot be empty.'));
Good question.  Just the appropriate amount of red.
![image](https://user-images.githubusercontent.com/5752113/119051397-1b0a7a00-b991-11eb-8948-0f7dfc04a9f0.png)

You did it well.

2021-05-20 21:34 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.services.yml
> +    arguments: ['@config.factory', '@entity_type.manager', '@path_alias.manager', '@va_gov_user.user_perms']
Those get passed into the service constructor as though you were obtaining them through using the dependency injection create() method.

2021-05-20 23:16 UTC, ethanteague commented
QA pass with latest steps for Lisa T and Ryan S, @swirtSJW :+1:

2021-05-21 01:44 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    return (!empty($this->formState->getValue(['menu', 'menu_parent']))) ? TRUE : FALSE;
I had to prove it to myself.  Turns out the return type declaration works for everything but NULL
![image](https://user-images.githubusercontent.com/5752113/119069689-96c9ee00-b9b4-11eb-8d7f-0e92d6f046f1.png)

2021-05-21 01:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    return ($this->formState->getValue(['menu', 'enabled']) === 1) ? TRUE : FALSE;
Keeping as is because it does not cover the NULL option 
![image](https://user-images.githubusercontent.com/5752113/119069779-bf51e800-b9b4-11eb-94b6-dc991668f645.png)

2021-05-21 03:12 UTC, swirtSJW commented
Updated the tests

2021-05-21 03:52 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/119079587-61c69700-b9c6-11eb-8375-ae6faef49eed.png)

2021-05-21 03:52 UTC, merged

2021-05-21 10:20 UTC, indytechcook commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    return (!empty($this->formState->getValue(['menu', 'menu_parent']))) ? TRUE : FALSE;
No, but `empty` returns a boolean.

2021-05-21 10:21 UTC, indytechcook commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    return (!empty($this->formState->getValue(['menu', 'menu_parent']))) ? TRUE : FALSE;
if you wanted to cast it `(bool)` is way faster also.

2021-05-21 10:29 UTC, indytechcook commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +    return ($this->formState->getValue(['menu', 'enabled']) === 1) ? TRUE : FALSE;
You don't need the `TRUE : FALSE` part.  `($this->formState->getValue(['menu', 'enabled']) === 1)` returns a `bool`