VACMS-4541: Prevent non admin user from editing administration.
department-of-veterans-affairs/va.gov-cms pull request #4907
Opened 2021-04-01 22:37 UTC by ethanteague

## Description
See #4541

## Testing done
Visual / Behat

## QA steps
- As an administrator, add Content publisher and Content creator - Vet Center roles to `vanessa.luxen@va.gov` account
- Add Create perms on main perms page for Vet Center Locations List, Vet Center Outstation and Vet Center Mobile Vet Center content types for Content creator - Vet Center role
- Assign `vanessa.luxen@va.gov` account all Vet Center sections.
- Add a VC Cap, and visually verify that all vc's are available in Owner dropdown
- Edit an existing Vet Center Outstation, and visually verify that the Owner dropdown is disabled.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-04-02 21:07 UTC, swirtSJW requested changes

2021-04-02 21:07 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
> +      if (in_array($form_id, $vc_target_bundles)) {
Moderate:  Let's move this check up in the stack so we aren't creating all the other vars and checks for every single form being loaded.

2021-04-02 21:41 UTC, ethanteague commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
> +      if (in_array($form_id, $vc_target_bundles)) {
Not sure I'm following you, @swirtSJW . To do this check safely requires that I confirm `$form_object instanceof ContentEntityForm` which requires me to `$form_object = $form_state->getFormObject();` . I'm not sure how I would safely move those vars out of that nested logic. I was thinking that this piece: `  $user_roles = \Drupal::currentUser()->getRoles();
  $admin_roles = ['content_admin', 'administrator'];
  // User isn't an admin, so logic is applied.
  if (empty(array_intersect($user_roles, $admin_roles))) {` would serve as my sanity check to prevent the logic from running _all_ the time

2021-04-05 14:02 UTC, kevwalsh commented
I'm not sure if these QA steps are complete or accurate. There are others on #4541 that are missing from this. 

> As an administrator, add Content publisher and Content creator - Vet Center roles to vanessa.luxen@va.gov account
> Add Create perms on main perms page for Vet Center Locations List, Vet Center Outstation and Vet Center Mobile Vet Center content types for Content creator - Vet Center role **Not sure why we need to do this in QA. "Normal" (non content admin) editors wouldn't be creating these, ever).**
> Assign vanessa.luxen@va.gov account all Vet Center sections.
> Add a VC Cap, and visually verify that all vc's are available in Owner dropdown
> Edit an existing Vet Center Outstation, and visually verify that the Owner dropdown is disabled.

2021-04-05 15:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
> +      if (in_array($form_id, $vc_target_bundles)) {
$form_id and $vc_target_bundles are directly accessible at the very beginning.    Move that check up to be the first check, then do all you other digging if it makes it past that.

2021-04-05 17:59 UTC, ethanteague commented
> I'm not sure if these QA steps are complete or accurate. There are others on #4541 that are missing from this.
> 
> > As an administrator, add Content publisher and Content creator - Vet Center roles to [vanessa.luxen@va.gov](mailto:vanessa.luxen@va.gov) account
> > Add Create perms on main perms page for Vet Center Locations List, Vet Center Outstation and Vet Center Mobile Vet Center content types for Content creator - Vet Center role **Not sure why we need to do this in QA. "Normal" (non content admin) editors wouldn't be creating these, ever).**
> > Assign [vanessa.luxen@va.gov](mailto:vanessa.luxen@va.gov) account all Vet Center sections.
> > Add a VC Cap, and visually verify that all vc's are available in Owner dropdown
> > Edit an existing Vet Center Outstation, and visually verify that the Owner dropdown is disabled.

Can you have another look at this when you get a minute, @kevwalsh ? I updated field_office to suck in the logic defined by user_perms service.

2021-04-09 02:49 UTC, swirtSJW approved these changes

2021-04-09 02:49 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/114121649-b998bb00-98bc-11eb-9902-7e28ca78dea9.png)

2021-04-09 02:50 UTC, merged

2021-04-09 04:10 UTC, kevwalsh commented
Sorry, i never got back to QA this again, and i don't think it's done. 

1. I made suzanne.middaugh@va.gov a Vet Center content creator, assigned her to Escanaba Vet Center section, and removed her content admin role. 
2. Went to /node/add/vet_center_cap and /node/add/vet_center_facility_health_servi
3. field_adminstration was properly restricted to Escanaba, but field_office was not. 

i think we need to write some automated tests for this too.


Here's a screenshot from the issue of the ACs. 

![Extend_field_office_entity_reference_permissions_to_Vet_Center_content_types_·_Issue__4541_·_department-of-veterans-affairs_va_gov-cms](https://user-images.githubusercontent.com/643678/114127156-d5558e80-98c7-11eb-98f4-e6d4de9d24b0.png)