VACMS-4604: Change default office to VHA.
department-of-veterans-affairs/va.gov-cms pull request #4909
Opened 2021-04-02 12:11 UTC by ethanteague

## Description
See #4604 

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/113414176-5d98d880-938a-11eb-8603-c98e14026e61.png)

## QA steps
@kevwalsh - we don't have a `Please Make a Selection` type of option for this field. To add this would be pretty involved, b/c this field is used in several places. Seems like the best course of action is to set the default to VHA (see screenshot) - just lemme know if this approach is flawed.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-04-02 21:18 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> + * Sets empty option for owner field.
```suggestion
 * Sets empty default option for owner field.
```

2021-04-02 21:45 UTC, swirtSJW requested changes
Sorry a bunch of picky renaming stuff junk.

2021-04-02 21:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function _va_gov_backend_unset_default_owner(array &$form, $form_id) {
```suggestion
function _va_gov_backend_set_default_administration(array &$form, $form_id) {
```
Name of function is the opposite of what it does.  Also we want to address the field name rather than the label since the label may change.

2021-04-02 21:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  _va_gov_backend_unset_default_owner($form, $form_id);
```suggestion
  _va_gov_backend_add_default_administration($form, $form_id);
```

2021-04-02 21:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/OwnerUndefined.php
> +  public $notDefined = 'Owner must be defined';
```suggestion
  public $notDefined = 'Owner must be defined.';
```

2021-04-02 21:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/OwnerUndefined.php
> + *   id = "OwnerUndefined",
```suggestion
 *   id = "FieldAdministrationUndefined",
```
field name is a more enduring source of truth.

2021-04-02 21:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/OwnerUndefined.php
> +class OwnerUndefined extends Constraint {
```suggestion
class FieldAdministrationUndefined extends Constraint {
```

The filename needs to be renamed to match.

2021-04-02 21:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/OwnerUndefinedValidator.php
> +class OwnerUndefinedValidator extends ConstraintValidator {
```suggestion
class FieldAdministationUndefinedValidator extends ConstraintValidator {
```
File needs to be renamed accordingly.

2021-04-02 21:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    $fields['field_administration']->addConstraint('OwnerUndefined');
```suggestion
    $fields['field_administration']->addConstraint('FieldAdministrationUndefined');
```

2021-04-02 21:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/OwnerUndefinedValidator.php
> +    if ($item->getValue()[0]['target_id'] === '0') {
I don't think we have to dig into the array here.  I am not clear what interface we have in $item but is it an object with a getValue method.   I would be surprised if it didn't have a isEmpty()   or a get('target_id`)  or something like that.  xdebug will tell you what the interface is or the class and you can see if there is a better method available.

2021-04-05 11:50 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/OwnerUndefinedValidator.php
> +    if ($item->getValue()[0]['target_id'] === '0') {
The problem with ->isEmpty() is that it returns false b/c there _is_ a target id on that empty string (gets set to 0 when ---none--- is added to the options array). I've not been able to find a method that gets me any closer to the target id than the get() for the field, @swirtSJW

2021-04-05 12:52 UTC, kevwalsh commented
Couple things: 

1. this is not really about field_office, more field_administration. (PR name is misleading for others coming back to this later). 
2. I was thinking that this was just config, there is a default value for field_administration set on a couple of content types. Could this just be done by setting config and some automated tests?

2021-04-05 16:45 UTC, ethanteague commented
> Couple things:
> 
> 1. this is not really about field_office, more field_administration. (PR name is misleading for others coming back to this later).
> 2. I was thinking that this was just config, there is a default value for field_administration set on a couple of content types. Could this just be done by setting config and some automated tests?

I updated this to use the existing _none field, @kevwalsh - sorry about the confusion.

2021-04-07 21:28 UTC, swirtSJW commented
conflicted

2021-04-09 04:29 UTC, kevwalsh requested changes
There's some inconsistent behavior still.  As content admin, i would expect the default value to be "Select a value" any content type that i create, forcing me to choose. Instead, i'm now seeing "Veterans Affairs" as the default value on about half the content types, including, for example 

https://pr4909-6vtcmxuwrv3sd1pfglbk5bgq1hqvvbaz.ci.cms.va.gov/node/add/vet_center_outstation
and https://pr4909-6vtcmxuwrv3sd1pfglbk5bgq1hqvvbaz.ci.cms.va.gov/node/add/full_width_banner_alert

I think i need to be writing better ACs.

I still think this is a config problem, not one that needs to be solved in custom code. We have default values set in config in a few places, like this.  Instead of custom code that overrides this config setting, why not just fix the configuration? 


![Owner_settings_for_VAMC_System_Banner_Alert_with_Situation_Updates___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114128530-8bba7300-98ca-11eb-8787-92fb375f69dd.png)

2021-04-09 17:06 UTC, ethanteague commented
> There's some inconsistent behavior still. As content admin, i would expect the default value to be "Select a value" any content type that i create, forcing me to choose. Instead, i'm now seeing "Veterans Affairs" as the default value on about half the content types, including, for example
> 
> https://pr4909-6vtcmxuwrv3sd1pfglbk5bgq1hqvvbaz.ci.cms.va.gov/node/add/vet_center_outstation
> and https://pr4909-6vtcmxuwrv3sd1pfglbk5bgq1hqvvbaz.ci.cms.va.gov/node/add/full_width_banner_alert
> 
> I think i need to be writing better ACs.
> 
> I still think this is a config problem, not one that needs to be solved in custom code. We have default values set in config in a few places, like this. Instead of custom code that overrides this config setting, why not just fix the configuration?
> 
> ![Owner_settings_for_VAMC_System_Banner_Alert_with_Situation_Updates___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114128530-8bba7300-98ca-11eb-8787-92fb375f69dd.png)

Apologies, @kevwalsh - I thought you and @swirtSJW  and I were in agreement on our Monday zoom call that this isn't possible to do via config (an empty owner option isn't available to content types that have available menus set on the content type form - setting it to empty in yaml breaks stuff). I'm glad to implement the same behavior on the admin form for the default value as I did on the node form, but I'm not sure if you are still okay with this approach (and that I'm not missing something). Just lemme know how you want me to proceed.

2021-04-12 14:03 UTC, ethanteague commented
My bad, @kevwalsh - you are right that this can be done in config. Looks like some of our content types already have this set, so I grepped on `config/sync` for `config/sync/field.field.node.*.field_administration.yml`, and added / changed the default to `default_value: {  }` on the items that were not set this way.

2021-04-13 03:10 UTC, kevwalsh commented on config/sync/field.field.node.full_width_banner_alert.field_administration.yml
> +third_party_settings:
I assume this is intentional.

2021-04-13 03:12 UTC, kevwalsh reviewed
@ethanteague cool, thanks! Just left one comment.

2021-04-13 10:55 UTC, ethanteague commented on config/sync/field.field.node.full_width_banner_alert.field_administration.yml
> +third_party_settings:
I didn't change anything manually in config to add this, nor did I change anything in the ui - it was just picked up on export. Do you want me to remove, @kevwalsh ?

2021-04-13 17:38 UTC, swirtSJW commented on tests/behat/features/content_editing.feature
> +@content_editing @et
Phone home?

2021-04-13 17:39 UTC, swirtSJW commented on tests/behat/features/content_editing.feature
> +@content_editing @et
```suggestion
@content_editing
```

2021-04-13 17:40 UTC, swirtSJW approved these changes

2021-04-15 21:17 UTC, swirtSJW submitted a review, later dismissed

2021-04-15 21:24 UTC, swirtSJW commented
@kevwalsh I am wondering if this is scoped right?  
![image](https://user-images.githubusercontent.com/5752113/114939920-16412c00-9e0f-11eb-9916-d8cacb570064.png)
The issue makes it sound like it should only apply for content admin and admin.   But the AC makes it seem more broad.

If it is intended to be more broad, isn't that counter to our goal of having that field prepopulated based on what section an editor is a part of?

2021-04-20 13:15 UTC, kevwalsh commented
> @kevwalsh I am wondering if this is scoped right?
> ![image](https://user-images.githubusercontent.com/5752113/114939920-16412c00-9e0f-11eb-9916-d8cacb570064.png)
> The issue makes it sound like it should only apply for content admin and admin. But the AC makes it seem more broad.
> 
> If it is intended to be more broad, isn't that counter to our goal of having that field prepopulated based on what section an editor is a part of?

I missed this comment the other day. 

This is one of those config things where we have defaults set, when we shouldn't. It's mainly a problem for content admins or editors who have access to more than one section. 

Here's another way of putting it: 
- [ ] Editors with only one workbench access section should see their section pre-populated 
- [ ] Editors with more than one workbench access section should be forced to choose. 

In the future, i think we'd like to find ways to pre-populate this field based on various contexts, for editors who have more than one section, but we're not there yet.

2021-04-20 13:17 UTC, kevwalsh commented
I've updated the ACs in the issue accordingly.

2021-04-20 19:03 UTC, ethanteague commented
@kevwalsh @swirtSJW I've updated this pr:
Now, when a user who has either the content admin or administrator role, but only one section selected they will see that section as the default owner. 
E.g.: 

- I assigned user 1730 the content admin role, here: `user/1730/roles` and then made sure only `VA Butler health care` section was assigned, here: `/user/1730/workbench_access` and then visited `node/add/full_width_banner_alert` and visually verified that the default `Owner` value was set to `VA Butler health care`.
- I then assigned an additional section to `/user/1730/workbench_access`, revisited `node/add/full_width_banner_alert` and visually verified that the `Owner` values was set to `Select a value`.

2021-04-21 16:01 UTC, swirtSJW requested changes

2021-04-21 16:13 UTC, ethanteague commented on docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php
> +      if (($key = array_search('administration', $results)) !== FALSE || $user->hasPermission('bypass workbench access')) {
Yeah, I hear you. I had something like you were suggesting initially, but I felt like it was a little bit harder to read than the extra nest I added. I'll change this, @swirtSJW

2021-04-21 16:21 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      if (count($user_sections) === 1) {
Good point - will add, @swirtSJW :+1:

2021-04-21 16:31 UTC, ethanteague commented on docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php
> +   *   Determines whether we get all sections or just ones selected on form.
That's right, @swirtSJW - I'll update this comment.

2021-04-21 20:55 UTC, swirtSJW requested changes

2021-04-21 20:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      if ($default = $perms_service->getDefault($user)) {
This approach seems a bit odd.  Your perms service already has the current user using proper dependency injection..  There is no need to pass it in.  You do have to pass in the admin bypas bool though.
![image](https://user-images.githubusercontent.com/5752113/115618472-b9d38600-a2c0-11eb-974a-08a37e85194d.png)
 There is no need to load it `\Drupal::currentUser();`.   Lines 1204 - 1208 are not needed.

2021-04-21 20:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php
> +    $user_sections = $this->getSections($user, TRUE);
```suggestion
  public function getDefault(bool $admin_bypass = FALSE) {
    $user_sections = $this->getSections($this->currentUser, $admin_bypass);
```

2021-04-21 20:55 UTC, swirtSJW commented on tests/behat/features/content_editing.feature
> +@content_editing @et
No et.

2021-04-30 20:12 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    if ($default = $perms_service->getDefault(TRUE)) {
In looking at this closer, I think we are blindly overwriting if a value was already set.   We aren't restricting this just a node add.  I need to test this out to make sure.

2021-04-30 20:17 UTC, swirtSJW requested changes
confirmed, We are not checking at all to see if the value was already set, we are just overwritting it with what the perms service says is the default.
![image](https://user-images.githubusercontent.com/5752113/116749866-9353d000-a9cf-11eb-9e41-7c3a836cc37f.png)

2021-05-05 17:39 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    if ($default = $perms_service->getDefault(TRUE)) {
:+1: updated, @swirtSJW

2021-05-05 19:06 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      // If only 1, make default, otherwise defaults to Select prompt.
This seems a little odd to dig into the entity that may not exist yet.  Also seems like a bit to much value juggling.
I didn't test this, but something like this "should" work 
```suggestion
   
    // There isn't a target id, so set a default using perms service.
    if ($form_state->isValueEmpty('field_administration') {
      $perms_service = \Drupal::service('va_gov_user.user_perms');
      // If only 1, make default, otherwise defaults to Select prompt.
```

2021-05-05 21:01 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      // If only 1, make default, otherwise defaults to Select prompt.
Stumped on this one. $form_object values are all empty when I set breakpoints in this function.
![image](https://user-images.githubusercontent.com/2404547/117208755-7c442200-adc3-11eb-9aa9-f16cf3f9b71a.png)

2021-05-06 14:28 UTC, swirtSJW approved these changes
Code looks good.   Functional QA works for me too, but I also want @kevwalsh  to poke at it. and do functional QA

2021-05-06 14:46 UTC, kevwalsh requested changes
[removed false alarm about a defect that was not a defect but an artifact of behat test that hadn't finished running]

2021-05-13 14:02 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/118136602-4958ea00-b3d2-11eb-9ada-c30cacf17441.png)

2021-05-13 14:02 UTC, merged