VACMS-4847: Set empty option on new events.
department-of-veterans-affairs/va.gov-cms pull request #4911
Opened 2021-04-02 15:19 UTC by ethanteague

## Description
See #4847

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/113428537-f63c5200-93a4-11eb-880c-53696f6fd931.png)

## QA steps
- As an administrator, go to `node/add/event` and visually verify that parent menu item is set to `---none---`
- Set parent to something else, and confirm form saves as expected.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-04-02 21:55 UTC, swirtSJW commented
@ethanteague are we missing the config approach ?
![image](https://user-images.githubusercontent.com/5752113/113456918-7d58ec80-93dc-11eb-893d-78001c25f04a.png)
Can we handle it in config without the code?

2021-04-05 12:15 UTC, ethanteague commented
> @ethanteague are we missing the config approach ?
> ![image](https://user-images.githubusercontent.com/5752113/113456918-7d58ec80-93dc-11eb-893d-78001c25f04a.png)
> Can we handle it in config without the code?

Sadly, doesn't appear so, @swirtSJW . cc: @kevwalsh 
![image](https://user-images.githubusercontent.com/2404547/113572878-0a6f9180-95e7-11eb-9c62-1a3603cfe9d4.png)

2021-04-05 12:54 UTC, kevwalsh commented
Yeah i'm confused about this. I thought that this was just config too. 16th minute?

2021-04-05 16:48 UTC, ethanteague commented
> Yeah i'm confused about this. I thought that this was just config too. 16th minute?

Per zoom convo, current pr implementation is correct.

2021-04-05 19:09 UTC, kevwalsh requested changes
I'm getting this error when testing as user 197. 

```

Drupal\Core\Database\IntegrityConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'menu_name' cannot be null: INSERT INTO {menu_tree} (id, menu_name) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1); Array ( [:db_insert_placeholder_0] => menu_link_content:5b55d726-1463-4dc6-b847-480b88ce1bcb [:db_insert_placeholder_1] => ) in Drupal\Core\Database\Connection->handleQueryException() (line 698 of /var/lib/tugboat/docroot/core/lib/Drupal/Core/Database/Connection.php).
--


```

![https___pr4911-iqbvykov5ruybyetpszrgwwzmm17z2ay_ci_cms_va_gov_node_add_event](https://user-images.githubusercontent.com/643678/113614511-9a7dfd00-9620-11eb-939c-11b1189c7cbe.png)

i also see some php notices 

```
Notice: Undefined index: menu_name in token_node_menu_link_submit() (line 757 of modules/contrib/token/token.module).
Notice: Undefined index: parent in token_node_menu_link_submit() (line 758 of modules/contrib/token/token.module).
```

2021-04-05 21:58 UTC, ethanteague commented
Apologies for that error, @kevwalsh - updated with a fix.

2021-04-06 12:36 UTC, kevwalsh requested changes
@ethanteague I forgot to suggest this one other change yesterday.

2021-04-06 12:36 UTC, kevwalsh commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  array_unshift($form['menu']['link']['menu_parent']['#options'], '---none---');
To match the Owner field
<img width="627" alt="Create_Event___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/113711523-09a43180-96b3-11eb-921f-7c97b8fe1e5b.png">

```suggestion
  array_unshift($form['menu']['link']['menu_parent']['#options'], '- Select a value -');
```

2021-04-06 12:36 UTC, kevwalsh commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $form['menu']['link']['menu_parent']['#default_value'] = '---none---';
```
suggestion
  $form['menu']['link']['menu_parent']['#default_value'] = '- Select a value -';
```

2021-04-07 21:20 UTC, swirtSJW commented
conflicted

2021-04-08 20:31 UTC, kevwalsh commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  array_unshift($form['menu']['link']['menu_parent']['#options'], '---none---');
I see this is resolved here in the github convo but i don't see the change in the UI.

![Uploading Create_Event___VA_gov_CMS.png…]()

2021-04-08 21:59 UTC, ethanteague commented
Apologies, @kevwalsh- I forgot that we changed this task to not just target events, so I've expanded the logic to operate on all node add forms. Setting parent menu items to null in yml throws errors = for select lists that don't have a null option available, we have to override it in an alter.

2021-04-09 04:34 UTC, kevwalsh commented
> Apologies, @kevwalsh- I forgot that we changed this task to not just target events, so I've expanded the logic to operate on all node add forms. Setting parent menu items to null in yml throws errors = for select lists that don't have a null option available, we have to override it in an alter.

Sorry but it was never about just events, that was just the example. The issue title for #4847 is "Menu item should not have a default parent for any node type.", and the only AC is " Menu items for all content types should always be specified manually."

2021-04-09 16:46 UTC, ethanteague commented
> > Apologies, @kevwalsh- I forgot that we changed this task to not just target events, so I've expanded the logic to operate on all node add forms. Setting parent menu items to null in yml throws errors = for select lists that don't have a null option available, we have to override it in an alter.
> 
> Sorry but it was never about just events, that was just the example. The issue title for #4847 is "Menu item should not have a default parent for any node type.", and the only AC is " Menu items for all content types should always be specified manually."

Sorry about that, @kevwalsh. My reply conflated a conversation (I thought) we had about fixing the events parent to be set to none on new node forms with the broader scope of this task (fwiw, I did read the title and the ac). I'm also getting confused by conversations we had about the other set to _none task we had this sprint: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4909 as well as the zoom conversation you and Steve and I had on Monday.

2021-04-13 03:13 UTC, kevwalsh commented
This didn't build right it seems. PR enviro is erroring with 
```
The website encountered an unexpected error. Please try again later.
Error: Call to undefined method Drupal\user\Form\UserLoginForm::getEntity() in va_gov_backend_form_alter() (line 440 of modules/custom/va_gov_backend/va_gov_backend.module).
```

2021-04-13 19:11 UTC, ElijahLynn commented
>  root@php:/var/lib/tugboat# curl https://pr4911-iqbvykov5ruybyetpszrgwwzmm17z2ay.ci.cms.va.gov
The website encountered an unexpected error. Please try again later.<br /><em class="placeholder">Error</em>: Call to undefined method Drupal\user\Form\UserLoginForm::getEntity() in <em class="placeholder">va_gov_backend_form_alter()</em> (line <em class="placeholder">440</em> of <em class="placeholder">modules/custom/va_gov_backend/va_gov_backend.module</em>).

2021-04-13 19:13 UTC, ElijahLynn commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +
>  root@php:/var/lib/tugboat# curl https://pr4911-iqbvykov5ruybyetpszrgwwzmm17z2ay.ci.cms.va.gov
The website encountered an unexpected error. Please try again later.<br /><em class="placeholder">Error</em>: Call to undefined method Drupal\user\Form\UserLoginForm::getEntity() in <em class="placeholder">va_gov_backend_form_alter()</em> (line <em class="placeholder">440</em> of <em class="placeholder">modules/custom/va_gov_backend/va_gov_backend.module</em>).

2021-04-19 14:39 UTC, swirtSJW requested changes

2021-04-19 14:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +
Can you move this all to its own well named function?

2021-04-19 14:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if ($form_state->getFormObject() instanceof EntityFormInterface && $form_object->getEntity()->getEntityType()->id() === 'node' && $form_object->getOperation() === 'default') {
```suggestion
  $form_operation = ($form_state->getFormObject() instanceof EntityFormInterface) ? $form_state->getFormObject()->getOperation : NULL;
  if ($form_operation === 'default' && $form_object->getEntity()->getEntityType()->id() === 'node') {
```

2021-04-21 16:25 UTC, swirtSJW requested changes
The code looks good, but on testing it does not seem to be working.

> As an administrator, go to node/add/event and visually verify that parent menu item is set to ---none---

![image](https://user-images.githubusercontent.com/5752113/115588307-98f93980-a29c-11eb-9eec-4c327ab30a15.png)

2021-04-21 17:24 UTC, ethanteague commented
> The code looks good, but on testing it does not seem to be working.
> 
> > As an administrator, go to node/add/event and visually verify that parent menu item is set to ---none---
> 
> ![image](https://user-images.githubusercontent.com/5752113/115588307-98f93980-a29c-11eb-9eec-4c327ab30a15.png)

Dangit - sorry about that. Was trying to use a magic method that had no magic. Fixed, @swirtSJW

2021-04-21 20:52 UTC, kevwalsh requested changes
I like that this forces a deliberate selection. Two issues that i see: 

- [ ] Red asterisk should appear beside Parent item to indicate that it's required.
- [ ] `---none---` Should instead be `- Select a value-`. Not because "Select a value" is ideal, but because that's what we have everywhere else, and consistency is ideal.  

Also, I guess i'm confused why this PR leaves all this stuff in config: `menu_ui: parent: 'va-altoona-health-care:'`. Seems like cruft that will bite us later. Can we not also:

- [ ] remove all `menu_ui: parent:` values

2021-04-22 10:56 UTC, ethanteague commented
> I like that this forces a deliberate selection. Two issues that i see:
> 
> * [ ]  Red asterisk should appear beside Parent item to indicate that it's required.
> * [ ]  `---none---` Should instead be `- Select a value-`. Not because "Select a value" is ideal, but because that's what we have everywhere else, and consistency is ideal.
> 
> Also, I guess i'm confused why this PR leaves all this stuff in config: `menu_ui: parent: 'va-altoona-health-care:'`. Seems like cruft that will bite us later. Can we not also:
> 
> * [ ]  remove all `menu_ui: parent:` values

@kevwalsh , here's what happens when we replace the '`parent: some-menu-here` setting on a node.type.*.yml (that has a menu set) with `parent: ''` 
![image](https://user-images.githubusercontent.com/2404547/115703156-c5ae5f00-a337-11eb-9731-150493c3022e.png)

2021-04-22 14:06 UTC, swirtSJW requested changes

2021-04-23 13:18 UTC, swirtSJW commented
Closing this as it has been consumed by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4894

2021-04-23 13:18 UTC, closed without merging