VACMS-4850 Vet Center dashboard mvp/poc
department-of-veterans-affairs/va.gov-cms pull request #4994
Opened 2021-04-09 16:31 UTC by ethanteague

## Description
See #4850

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/114211793-12a13700-992f-11eb-8687-dbe648c9bcff.png)
![image](https://user-images.githubusercontent.com/2404547/114211807-1634be00-992f-11eb-9657-cea3fae6150a.png)
![image](https://user-images.githubusercontent.com/2404547/114211817-19c84500-992f-11eb-93d2-d6d6b403f13b.png)

## QA steps
- As an administrator, go to `/taxonomy/term/392/edit` and choose the Vet center product.
- Clear cache, and go to `/section/veterans-health-administration/vet-centers/escanaba-vet-center`
- Visually verify that you see the new dashboard format (cards up top, listing down below)
- Visit another administration term page, and visually verify that the default view listing is displayed, e.g.: `section/veterans-affairs`

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-04-12 22:24 UTC, swirtSJW reviewed
Just some thoughts.

2021-04-12 22:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
> +          $dash_panels['locations'] = [
It would be great to consider how we could increase the re-useabiltiy  of this.
It could be as simple as moving the things like the specific term id and the content type to reference in vars at the top in one spot and then use the var and making  the vars uses less "vet center" specific.  Or it could be a little more broad by creating a trait that provides some helpers so we don't have to have so much duplicate code in each of these dashboards.

2021-04-12 22:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.module
> +        echo 'va_gov_homepage';
?

2021-04-12 22:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.module
> +      foreach ($parents as $parent) {
This assumes parents are returned in order of hierarchy.  Is that how they are returned?

2021-04-12 22:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.module
> +      $parents = \Drupal::service('entity_type.manager')->getStorage("taxonomy_term")->loadAllParents($entity->id());
I have some concerns about the performance of this on deep terms and how often people will be hitting the this dashboard.   This could be pretty costly.   We may want to kick around some ideas on how to cache this or create a lookup table.

2021-04-12 23:08 UTC, ethanteague commented on docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.module
> +      $parents = \Drupal::service('entity_type.manager')->getStorage("taxonomy_term")->loadAllParents($entity->id());
Yeah, I was kinda feeling that as well, @swirtSJW . I like the idea of a some kind of a flat file / lookup table, but not sure how extensible this would be.

2021-04-13 03:25 UTC, kevwalsh commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
> +      $tid = $this->routeMatch->getRawParameter('taxonomy_term') ? $this->routeMatch->getRawParameter('taxonomy_term') : '392';
392 is Escanaba Vet Center, one of 300 Vet Centers. Is that here as an example?  I didn't think TIDs would be in the code, since the trigger is in the content layer.

2021-04-13 10:56 UTC, ethanteague commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
> +      $tid = $this->routeMatch->getRawParameter('taxonomy_term') ? $this->routeMatch->getRawParameter('taxonomy_term') : '392';
That's right, @kevwalsh.

2021-04-16 19:51 UTC, ethanteague commented on docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.module
> +        echo 'va_gov_homepage';
D'oh! Thanks for catching that (typo), @swirtSJW !

2021-04-16 21:19 UTC, ethanteague commented on docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.module
> +      foreach ($parents as $parent) {
Yep. I just tested by throwing a breakpoint in that foreach (after removing the break statement in the loop for testing), and checking the id returned at each iteration. Went like this: `392 (Escanaba) -> 699 (Vet Centers MVP) -> 190 (Vet Centers) -> 3 (Veterans Health Administration)`

2021-04-16 21:35 UTC, ethanteague commented on docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.module
> +      $parents = \Drupal::service('entity_type.manager')->getStorage("taxonomy_term")->loadAllParents($entity->id());
Wondering if the lookup will happen every time the page is hit, @swirtSJW ? Won't the block cache that I have setup (using the term tag) serve this as static content?

2021-04-16 21:43 UTC, ethanteague commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
> +          $dash_panels['locations'] = [
@swirtSJW | @kevwalsh 
Agreed - I would like to get a feel for what future dashboards are gonna look like. My thinking is, I would like to make a trait that is generic enough to allow for different panel implementations (fields, etc.). Do either of you all know what kind of stuff we are going to have in other dashboards? If this is still kinda fluid, I'm wondering if I can punt on this until we get other dash implementations a bit more nailed down?

2021-04-21 22:07 UTC, swirtSJW requested changes
I am interrupted on my review so it is not complete, but wanted to get this in.

2021-04-21 22:07 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
> +      'field_administration' => $tid,
On line 129 you create the possiblilty that $tid might be empty,   Here would be where you want to be defensive about what should or should not happen if it is empty.

2021-04-21 22:07 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
> +          $dash_panels['locations'] = [
Fair enough, lets make dashboard number 2 require  more abstraction of this.

2021-04-23 13:26 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.module
> +      $parents = \Drupal::service('entity_type.manager')->getStorage("taxonomy_term")->loadAllParents($entity->id());
It should, but we need to validate that hypothisis reloading the page with the debugger running and a breakpoint set in what should not be running repeatedly

2021-04-23 15:00 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
> +      return;
This has to come after where you set $node = null and then it has to return $node.

2021-04-23 20:46 UTC, swirtSJW requested changes
Super minor stuff that needs resolving.

2021-04-23 20:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
> +   * {@inheritdoc}
Because of what you did in the create, you are overriding the parameters from the base class, so you can't just inherit the doc.  So the docblock has to be explicit.

2021-04-23 20:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Block/VcDashboardsBlock.php
> +   * {@inheritDoc}
You are altering what gets passed in via the create, so you have to explicitly declare the docblock for the constructor. It can't be inherited.

2021-04-23 20:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
> +      'type' => 'vet_center',
```suggestion
      'type' => $content_type,
```

2021-04-24 18:08 UTC, ethanteague commented
@swirtSJW - derivatives are creating caching issues. If I move Nashville under Escanaba for the former to inherit the dashboard product treatment of the latter, the blocks created in the derivative get stuck on the term page first viewed after cache clear, so if you load Escanaba after viewing Nashville, you will see links to Nashville vc on Escanaba. 

From what I'm reading, there are a couple/few issues 
(e.g.: https://www.drupal.org/project/drupal/issues/2880682, https://www.drupal.org/project/drupal/issues/3001284)
with derivatives and how caching is handled by said api. To confirm that this behavior is associated with derivative controlled blocks, I created a new, singular block (not under purview of our derivative class), and added logic to output the vc nid associated with the current page term = correct nid is always returned.

So, I'm not sure about the best path forward. I realize that derivatives are the de facto solution for creating block multiples of similar content, but I'm not sure it's capable of handling our use case. I could pretty easily break each of these derivatives into their own block classes and place them in layout builder (probably an hour of work), but wanted to get your thoughts, first.

I updated this pr with Kaise's stuff, as well as the things you and I worked on, yesterday, and a couple of other issues I found when testing.

cc: @kevwalsh

2021-04-28 02:40 UTC, swirtSJW commented
@ethanteague  Interesting.  I just noticed we lost the dual view  and edit links.
spec
![image](https://user-images.githubusercontent.com/5752113/116338183-5b6b4380-a7a9-11eb-8d21-93082be48217.png)


current
![image](https://user-images.githubusercontent.com/5752113/116338273-7d64c600-a7a9-11eb-8232-219e6fc58316.png)


I don't think that was anything I touched, but I'll have to look into it.

2021-04-28 03:12 UTC, swirtSJW commented
I found the issue with the missing links.  They are restored now.

2021-04-28 04:07 UTC, kevwalsh commented
I did some clicking around from https://pr4994-ktrcnvwibjve1xd1v2cabeky6va0snm5.ci.cms.va.gov/section/veterans-health-administration/vet-centers-mvp and it looks good. 

It would be great to merge #5089 after this because it's dashboard related. 

We also spun out #5110 into its own issue. Not critical, but it's the next up that's related.

2021-04-28 04:08 UTC, kevwalsh approved these changes
QA pass!

2021-04-28 13:09 UTC, acrollet commented
minor note: I clicked to https://pr4994-ktrcnvwibjve1xd1v2cabeky6va0snm5.ci.cms.va.gov/section/veterans-health-administration/vet-centers-mvp and it's accessible to anonymous users - not sure if that's desired or not?

2021-04-28 13:29 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/116411891-250ee200-a804-11eb-8eea-c4d17dd948bf.png)

2021-04-28 13:33 UTC, swirtSJW commented
@acrollet Good spotting that issue.  It is not related to this PR as the sections taxonomy is available to anon users now.   I believe that is intentional, but I don't have the history on the rationale.    Here is an example from staging.
![image](https://user-images.githubusercontent.com/5752113/116412422-ac5c5580-a804-11eb-8f92-20ca3568924b.png)

2021-04-28 13:34 UTC, acrollet commented
@swirtSJW good deal!

2021-04-28 13:46 UTC, swirtSJW commented
Will merge as soon as tests finish.

2021-04-28 14:25 UTC, merged