VACMS-4972: Vet-Center-Office-Hours-Opt-In
department-of-veterans-affairs/va.gov-cms pull request #5016
Opened 2021-04-12 21:03 UTC by kaise-lafrai

…n another field, added logic to unset the build of the office hours field on proofing page if the choice was to hide the office hours field

## Description

See _issueid_. 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-04-13 02:28 UTC, kevwalsh submitted a review, later dismissed
Nice! 

On https://pr5016-xsryvj9ndosceqa7imiftq8njzyoijql.ci.cms.va.gov/node/16624/edit i've indicated "Veterans should call main Vet Center for hours". if i go back and change it to TRUE, the old `field_office_hours` data i had added on a previous revision is still there. 

I think that's fine, but just want to flag that behaviour in case @swirtSJW has a thought about it for API consumers etc.

2021-04-14 14:30 UTC, swirtSJW requested changes
Overall looks good.  I have a few requests through.  :)  Please and thank you.

2021-04-14 14:30 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  // We want to trigger the office hours field on/off.
Since these are all vetcenter specific.  I would prefer they live here
docroot/modules/custom/va_gov_vet_center

2021-04-14 14:30 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if (($form_id === 'node_vet_center_cap_edit_form') || ($form_id === 'node_vet_center_cap_form')) {
This form id checking could be done in the function since we never want that function to be called on anything else.  And it would make reading the logic in the alter clearer.

2021-04-14 14:30 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  $node = \Drupal::routeMatch()->getParameter('node');
I suggest passing in the $formstate to this function, then you can get the node with
`$node = $form_state->getformObject()->getEntity();`
The entity is already loaded in the formstate which is more performant than loading it through routeMatch and without the need for calling \Drupal::.

2021-04-14 14:30 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  };
Would be good to put all this in a function too, then just call the function.

2021-04-21 16:51 UTC, swirtSJW requested changes
We are close here.  Some minor suggestions and one must have.

2021-04-21 16:51 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
> + *   The node form array.
Minor: A bit misleading as this will get called on any form, so it may not always be the node form array.

2021-04-21 16:51 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
> +  _va_gov_vet_center_cap_hours_opt_in($form, $form_state, $form_id);
Minor:  Related to clean coding: If we've done a good job naming the function, then no comment is needed.  Ideally a function's name should say it all, and when it can't, the function description should.    (more about that in a similar comment farther down)

2021-04-21 16:51 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
> +      $form['field_office_hours']['#states'] = [
Minor: We could benefit from a comment here as it is not clear to me why having both fields (regardless of value) is enough to set the visible state.

2021-04-21 16:51 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
> + * Unset field_office_hours on proofing page based on trigger field.
Major: Need to specify @params here.

2021-04-21 16:51 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
> +  _va_gov_vet_center_unset_cap_hours($build, $entity);
Minor:  if the function is named well, the comment is unnecessary,   This one concerns me because the comment and the function name are not in alignment  `toggle` vs `unset`.  Seems like toggle may the more accurate description.  If extra declaration is needed, then it should be in the description of the function, not where the function is called.

2021-04-22 15:47 UTC, kaise-lafrai commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
> + * Unset field_office_hours on proofing page based on trigger field.
Weird because I did have params here but codesniffer kept failing.

2021-04-22 17:50 UTC, swirtSJW approved these changes
Outstanding work on QA steps.   I really appreciate the extra regression tests.

2021-04-22 18:06 UTC, swirtSJW commented
tubboat seems to be stalled out on tests.    Updating the branch to re-trigger.

2021-04-22 20:47 UTC, swirtSJW commented
tugboat is not running tests.   Kicking off a rebuild in tugboat.

2021-04-23 00:29 UTC, swirtSJW commented
I am not quite tracking what is going on with these tests.  Initially the github actions tests passed and the tugboat tests never ran.
Then I triggered a rebuild in tugboat ant the tugboat tests ran but not the others
```
134 scenarios (133 passed, 1 undefined)
982 steps (966 passed, 1 undefined, 15 skipped)
9m9.62s (370.18Mb)

--- CustomDrupal\ContentModelContext has missing steps. Define them with these snippets:

    /**
     * @When I run :arg1
     */
    public function iRun($arg1)
    {
        throw new PendingException();
    }

github-status-updater: Updated status 12868278084
task: [va/tests/behavioral] cat <<EOF | bash
  : "${SKIP_REPORTING:=0}"
  exit_code=\$?
  mkfifo output
  result="\$(composer va:test:behavioral 2>&1 | tee \$output)"
  (cat output&)
  if [ "$SKIP_REPORTING" -ne 1 ]; then
    if [ "\$exit_code" -eq 0 ]; then
      github-status-updater -action=update_state -state=success -context='va/tests/behavioral' -description='Success'
    else
      github-status-updater -action=update_state -state=failure -context='va/tests/behavioral' -description='Failed'
    fi
  fi
EOF

github-status-updater: Updated status 12868317649
task: [va/tests/check-cer] cat <<EOF | bash
  : "${SKIP_REPORTING:=0}"
  output="\$(mktemp -d)/output"
  mkfifo \$output
  (cat \$output&)
  result="va/tests/check-cer:<br/><br/>\$(./tests/scripts/check-cer.sh 2>&1 | tee \$output)"
  exit_code=\$?
  if [ "$SKIP_REPORTING" -ne 1 ]; then
    if [ "\$exit_code" -eq 0 ]; then
      github-status-updater -action=update_state -state=success -context='va/tests/check-cer' -description='Success'
    else
      github-status-updater -action=update_state -state=failure -context='va/tests/check-cer' -description='Failed'
      [ -z "\${GITHUB_COMMENT_TYPE}" ] && github-commenter -delete-comment-regex="va/tests/check-cer" -comment="\${result}"
    fi
  fi
EOF

github-status-updater: Updated status 12868317805
task: [va/tests/phplint] cat <<EOF | bash
  : "${SKIP_REPORTING:=0}"
  output="\$(mktemp -d)/output"
  mkfifo \$output
  (cat \$output&)
  exit_code=0
  result="va/tests/phplint<br/><br/>"
  trap '{ (( exit_code |=\$? )); result+="\$output_text<br/>"; }' ERR
  output_text=\$(find docroot/modules/custom docroot/themes -name '*.inc' -print0 | xargs -0 -n1 php -l 2>&1 | tee \$output)
  output_text=\$(find docroot/modules/custom docroot/themes -name '*.php' -print0 | xargs -0 -n1 php -l 2>&1 | tee \$output)
  output_text=\$(find docroot/modules/custom docroot/themes -name '*.module' -print0 | xargs -0 -n1 php -l 2>&1 | tee \$output)
  output_text=\$(find docroot/modules/custom docroot/themes -name '*.install' -print0 | xargs -0 -n1 php -l 2>&1 | tee \$output)
  trap - ERR
  if [ "$SKIP_REPORTING" -ne 1 ]; then
    if [ "\$exit_code" -eq 0 ]; then
      github-status-updater -action=update_state -state=success -context='va/tests/phplint' -description='Success'
    else
      github-status-updater -action=update_state -state=failure -context='va/tests/phplint' -description='Failed'
      [ -z "\${GITHUB_COMMENT_TYPE}" ] && github-commenter -delete-comment-regex="va/tests/phplint" -comment="\${result}"
    fi
  fi
EOF

No syntax errors detected in Standard input code

```


![image](https://user-images.githubusercontent.com/5752113/115800828-5f622480-a3a9-11eb-8dfc-9baba4ace75f.png)

2021-04-23 13:04 UTC, merged