VACMS-4927: Configure Memcache support in Tugboat.
department-of-veterans-affairs/va.gov-cms pull request #5023
Opened 2021-04-13 12:56 UTC by ndouglas

## Description

See #4927.   Gotta:
- [ ] create method or docs to disable memcache on demand
- [ ] set up locks
- [ ] set up session support

## Testing done
none yet

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

2021-04-14 12:48 UTC, indytechcook commented on config/sync/memcache_admin.settings.yml
> +show_memcache_statistics: true
Should we default this to false and only have it enabled on non-prod?

2021-04-14 12:51 UTC, ndouglas commented on config/sync/memcache_admin.settings.yml
> +show_memcache_statistics: true
Without a doubt, but I'm keeping it `true` right now because it's the easiest way to tell whether Memcache is working at any given time.

2021-04-22 16:10 UTC, indytechcook approved these changes

2021-04-22 16:11 UTC, indytechcook requested changes
This is not currently working on tugboat: https://cms-ig2ltlrtrshwqhsex4qqnld8e0tpkaou.ci.cms.va.gov/admin/reports/memcache

2021-04-22 16:12 UTC, ndouglas commented
I think this is because of something I was messing with earlier -- lemme check.

2021-04-22 16:13 UTC, ndouglas commented
(messing around with within Tugboat, not in the PR)

2021-04-22 16:15 UTC, ndouglas commented
@indytechcook I think you're looking at the wrong preview environment -- that one won't work because the `memcache` PECL module is installed in the `init` phase, so you gotta look at the base preview which is `607dc25ceac8ec760aa4b2d0`.

2021-04-22 16:17 UTC, indytechcook commented
I just clicked in link in the comment.  I'll go directly to tugboat and test.

2021-04-22 16:25 UTC, indytechcook commented
I tested this on the base preview that branch uses: https://vacms-4927-configure-memcache--xw0ifux3kpohwslblqfitpiiisdhtpbe.ci.cms.va.gov/admin/reports/memcache

![image](https://user-images.githubusercontent.com/121603/115750113-cfe75200-a365-11eb-93bb-982b17948579.png)


The PR preview would not have the new init phase items yet.

2021-04-22 16:25 UTC, indytechcook approved these changes

2021-04-22 16:52 UTC, ndouglas commented
https://vacms-4927-configure-memcache--xw0ifux3kpohwslblqfitpiiisdhtpbe.ci.cms.va.gov/admin/reports/memcache working FWIW

2021-04-22 16:52 UTC, ndouglas commented
D'oh, missed that you'd posted that very thing 😩

2021-04-22 16:52 UTC, merged