VACMS-4054: Centralized Content Last Updated Date
department-of-veterans-affairs/va.gov-cms pull request #5074
Opened 2021-04-20 20:35 UTC by kaise-lafrai

## Description

See _issueid_. #4054 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-04-20 21:03 UTC, swirtSJW requested changes
Overall looks great Kaise.  There are just a couple of losses of those pesky revision_log and one thing I want to double check with @kevwalsh

2021-04-20 21:03 UTC, swirtSJW commented on config/sync/core.date_format.short.yml
> +pattern: 'M d Y g:i a'
Did @kevwalsh sign off on this change?  Not sure where else short date is used or if it matters.

2021-04-20 21:03 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> -        - revision_log
Don't want to lose this.

2021-04-20 21:07 UTC, swirtSJW commented
@kevwalsh  and @rachel-kauff   
One question on this
![image](https://user-images.githubusercontent.com/5752113/115464351-f046cd80-a1fa-11eb-9126-4ffa1d3e417d.png)

2021-04-20 21:15 UTC, swirtSJW commented on config/sync/core.date_format.short.yml
> +pattern: 'M d Y g:i a'
Looks like @rachel-kauff had some concerns about this new format that she left in the issue.

2021-04-20 23:02 UTC, rachel-kauff commented
@swirtSJW Great question. I assume there are two dates because those are two discrete pieces of data, but if they're always  going to be the same then yes, let's just show one updated link.

2021-04-21 13:42 UTC, swirtSJW commented on config/sync/core.date_format.short.yml
> +pattern: 'M d Y g:i a'
Looks like the old is preferable to the new format  From Kauffe's comment in the issue

> That is to say I'm in favor of using mm/dd/yyyy - H:m

2021-04-21 14:22 UTC, kaise-lafrai commented
@rachel-kauff @swirtSJW Thanks for the input. Let me get started!

2021-04-21 16:39 UTC, kaise-lafrai commented
@rachel-kauff @swirtSJW Ready for another look. Thanks :)

2021-04-21 17:10 UTC, swirtSJW approved these changes
Looks good to me.  Nice work Kaise.
![image](https://user-images.githubusercontent.com/5752113/115593729-dfea2d80-a2a2-11eb-86f0-d169baa85cf1.png)

Just waiting on tests to complete.

2021-04-21 18:56 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/115606464-b97fbe80-a2b1-11eb-96ca-1b114d99a1d0.png)

2021-04-21 18:56 UTC, merged