VACMS-4075 Unique validation for content types
department-of-veterans-affairs/va.gov-cms pull request #5459
Opened 2021-05-27 14:12 UTC by ethanteague

## Description
See #4075

## Testing done
Behat

## QA steps
It's probably overkill, but we could create two of each of the content types to which we've added the `field_enforce_unique_combo` field, and duplicate the values in the unique value combo fields, then verify that a notice is created when trying to save the second one. 
We could probably just spot check a few: E.g.: 
- Create two Facility Health Services with the same field_service_name_and_descripti value, and visually verify that a notice is thrown when saving the second. 
- Create two Story Listing nodes with the same field_office value, and visually verify that a notice is thrown when saving the second. 
- Create two Operating Status nodes with the same field_office value, and visually verify that a notice is thrown when saving the second. 
- Create two Locations Listing nodes with the same field_office value, and visually verify that a notice is thrown when saving the second. 

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-05-27 19:58 UTC, swirtSJW requested changes

2021-05-27 19:58 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
> -Feature: Content model: VAMC Content Type fields
@ethanteague  this looks like a mis-past from spectool

2021-05-27 19:58 UTC, swirtSJW commented on composer.json
> +        "drupal/allow_only_one": "1.0.x-dev",
Now that this is released lets get this on the alpha release so it doesn't float.

2021-05-27 21:06 UTC, ethanteague commented on tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
> -Feature: Content model: VAMC Content Type fields
Dangit. I'm a repeat mis-paste offender. Thanks for catching this, @swirtSJW

2021-05-28 02:21 UTC, swirtSJW reviewed
PR looks awesome, but seems behat is still grumpy

2021-05-28 02:24 UTC, swirtSJW requested changes
Caught a couple `revision_log entries trying to sneak over the fence.

2021-05-28 02:24 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
> -        - revision_log
gone AWOL.

2021-05-28 02:24 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.health_services_listing.default.yml
> -        - revision_log
AWOL

2021-05-28 13:08 UTC, swirtSJW approved these changes
Looks good.   
waiting on tests to finish.

2021-05-28 13:13 UTC, swirtSJW commented
@ethanteague It looks like the content build test is probably trying to create a duplicate and gettng blocked  :)
```
@content_editing
  Scenario: Log in and confirm that System-wide alerts can be created and edited # features/content_editing.feature:160
    When I am logged in as a user with the "content_admin" role                  # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
    Then I am at "node/add/vamc_operating_status_and_alerts"                     # Drupal\DrupalExtension\Context\MinkContext::assertAtPath()
    And I press "Add new banner alert"                                           # Drupal\DrupalExtension\Context\MinkContext::pressButton()
    And I select "Information" from "Alert type"                                 # Drupal\DrupalExtension\Context\MinkContext::selectOption()
    And I select "Veterans Affairs" from "edit-field-administration"             # Drupal\DrupalExtension\Context\MinkContext::selectOption()
    And I fill in "Title" with "BeHat Alert title"                               # Drupal\DrupalExtension\Context\MinkContext::fillField()
    And I fill in "Alert body" with "BeHat Alert body"                           # Drupal\DrupalExtension\Context\MinkContext::fillField()
    And I press "Save draft and continue editing"                                # Drupal\DrupalExtension\Context\MinkContext::pressButton()
    Then I should see "Pages for the following VAMC systems"                     # Drupal\DrupalExtension\Context\MinkContext::assertPageContainsText()
      The text "Pages for the following VAMC systems" was not found anywhere in the text of the current page. (Behat\Mink\Exception\ResponseTextException)
    │
    And I should not see "BeHat Alert Body"                                      # Drupal\DrupalExtension\Context\MinkContext::assertPageNotContainsText()```

```

2021-05-28 13:15 UTC, swirtSJW commented
Actually that ^^ does not seem like it should be affected by this.... but still needs to be checked out.

2021-06-02 13:30 UTC, swirtSJW commented on tests/behat/features/content_editing.feature
> +@content_editing @et
ET phone home?

2021-06-02 13:31 UTC, swirtSJW commented on tests/behat/features/content_editing.feature
> +    Then I am at "node/1010/edit"
This seems like an odd change making it nid specifc.

2021-06-02 13:34 UTC, ethanteague commented on tests/behat/features/content_editing.feature
> +    Then I am at "node/1010/edit"
Need to target an existing id - node add forms run the risk of getting shouted down by our Highlander validation, @swirtSJW.

2021-06-02 13:36 UTC, swirtSJW commented on tests/behat/features/content_editing.feature
> +    Then I am at "node/1010/edit"
I see why it is needed.   Lets just prefface it with a comment so it is clear what node/1010 is.

2021-06-02 13:36 UTC, swirtSJW requested changes
Remove ET and add comment for test   See comments ^^

2021-06-02 13:39 UTC, ethanteague commented on tests/behat/features/content_editing.feature
> +    Then I am at "node/1010/edit"
Makes sense to me, @swirtSJW :+1:

2021-06-02 13:43 UTC, ethanteague commented
> Remove ET and add comment for test See comments ^^

Updated, @swirtSJW

2021-06-02 14:00 UTC, swirtSJW approved these changes

2021-06-02 15:03 UTC, swirtSJW commented
Just triggered a tugboat rebuild to try to get past FE build without failure.

2021-06-02 18:28 UTC, swirtSJW commented
That failure is  Notice: MemcachePool::set(): Server memcache (tcp 11211, udp 0) failed with: SERVER_ERROR out of memory storing object
       (130) in /var/lib/tugboat/docroot/modules/contrib/memcache/src/Driver/MemcacheDriver.php line 17

Passes locally.  I am merging.

2021-06-02 18:28 UTC, merged