VACMS-4932: Add contextual menu block.
department-of-veterans-affairs/va.gov-cms pull request #5468
Opened 2021-05-27 23:17 UTC by ethanteague

## Description
See #4932

## Testing done
Visual / behat

## QA steps
This will require a bunch of clicking around / spot checking, e.g: Visit multiple VAMC's and subordinate pages in said VAMC's, confirming that the contextually appropriate menu appears (just once) on each page. We will also need to confirm that VAMC menus do not appear in places where they shouldn't, i.e.: admin pages, user pages, node edit pages, etc.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-05-28 02:16 UTC, kevwalsh commented
@ethanteague 

QA fail for now, per the QA instructions i added above

```
Check that the correct VAMC menu is there

- [ ] 1. On VAMC facility nodes 
  - [ ] Go to /admin/content and filter VAMC facility
  - [ ] Open a variety of recently updated facilities to see if the menu is there, and that it's the right menu
- [ ] 2. On events
  - [ ] Go to /admin/content and filter by Event nodes
  - [ ] Open a variety of recently updated events with a section set to VAMC, to see if the menu is there, and that it's the right menu
- [ ] 3On Policies pages
  - [ ] Go to /admin/content and filter by nodes with "Policies" in the title
  - [ ] Open a variety of recently updated nodes with a section set to VAMC, to see if the menu is there, and that it's the right menu
```

QA passed on VAMC facility nodes after i checked this value on the PR environment. But we shouldn't need content types to be specified for this to work. 

![Configure_block___VA_gov_CMS](https://user-images.githubusercontent.com/643678/119919655-deaebf00-bf38-11eb-803f-55577abe45e8.png)

2021-05-28 14:46 UTC, ethanteague commented
> @ethanteague
> 
> QA fail for now, per the QA instructions i added above
> 
> ```
> Check that the correct VAMC menu is there
> 
> - [ ] 1. On VAMC facility nodes 
>   - [ ] Go to /admin/content and filter VAMC facility
>   - [ ] Open a variety of recently updated facilities to see if the menu is there, and that it's the right menu
> - [ ] 2. On events
>   - [ ] Go to /admin/content and filter by Event nodes
>   - [ ] Open a variety of recently updated events with a section set to VAMC, to see if the menu is there, and that it's the right menu
> - [ ] 3On Policies pages
>   - [ ] Go to /admin/content and filter by nodes with "Policies" in the title
>   - [ ] Open a variety of recently updated nodes with a section set to VAMC, to see if the menu is there, and that it's the right menu
> ```
> 
> QA passed on VAMC facility nodes after i checked this value on the PR environment. But we shouldn't need content types to be specified for this to work.
> 
> ![Configure_block___VA_gov_CMS](https://user-images.githubusercontent.com/643678/119919655-deaebf00-bf38-11eb-803f-55577abe45e8.png)

@kevwalsh wondering if maybe you caught the environment in a funky state? I unchecked the VAMC facility type in the block, cleared cache, and visited the Dwight D. Eisenhower facility, and the menu is there.
![image](https://user-images.githubusercontent.com/2404547/120001564-eb1b3200-bfa1-11eb-97e2-33161dd456c8.png)

2021-05-28 15:27 UTC, kevwalsh commented
@ethanteague yeah maybe it just needed a cache clear. We probably still need to bang on the QA a bit more, especially on pages that _shouldn't_ have anything.

2021-06-01 13:10 UTC, kevwalsh commented
@ethanteague  Went back to PR environment, menus were missing again. Cleared cache and they started appearing. However, the VA Dublin health care menu is showing up on every page that doesn't have a VAMC menu item, including both VAMC Policies pages like https://pr5468-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/central-alabama-health-care/policies and Benefits Detail Pages https://pr5468-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/careers-employment/vocational-rehabilitation/programs/self-employment

2021-06-01 18:12 UTC, ethanteague commented
> @ethanteague Went back to PR environment, menus were missing again. Cleared cache and they started appearing. However, the VA Dublin health care menu is showing up on every page that doesn't have a VAMC menu item, including both VAMC Policies pages like https://pr5468-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/central-alabama-health-care/policies and Benefits Detail Pages https://pr5468-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/careers-employment/vocational-rehabilitation/programs/self-employment

Just updated, @kevwalsh - have a looksee when you get a minute.

2021-06-02 14:14 UTC, kevwalsh commented
Same sorts of issues

1. i was on a pittsburgh-health-care URL, missing the menu. i cleared the cache, which made the menu appear
2. then most URLs would work, but in various cases Pittsburgh menu would show on nodes that have it, like 

* https://pr5468-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/st-cloud-health-care/make-an-appointment
* https://pr5468-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/new-jersey-health-care/doing-business-with-us
* https://pr5468-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/resources/how-do-i-show-my-intent-to-file

2021-06-02 21:49 UTC, swirtSJW requested changes
I'm still looking at your caching logic.... but here are a couple that I spotted trying to sneak over the fence.

2021-06-02 21:49 UTC, swirtSJW commented on config/sync/core.entity_form_display.media.document.default.yml
> -  revision_log_message: true
AWOL

2021-06-02 21:49 UTC, swirtSJW commented on config/sync/core.entity_form_display.media.document.media_library.yml
> -  revision_log_message: true
AWOL
![image](https://user-images.githubusercontent.com/5752113/120556390-70e81480-c3ca-11eb-9ea8-4b68593552ad.png)

2021-06-02 22:28 UTC, ethanteague commented on config/sync/core.entity_form_display.media.document.media_library.yml
> -  revision_log_message: true
KILNGER!!!!

2021-06-03 01:30 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +      }
Ideally this should all be encapsulated in a method like "getMenuName()"

2021-06-03 02:06 UTC, swirtSJW requested changes

2021-06-03 02:06 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +        $build = $menu_tree_service->build($tree);
Ideally this should all be in a method "getMenuBuild($menu_links).

It would return [] if $menu_llinks is empty or $build if it was not. 
`$build = $this->getMenuBuild($menu_links);`
 That way it would be more testable, readable and you could get rid of the empty array being set on line 116

2021-06-03 02:20 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> + *   id = "va_gov_backend",
This seems like a very generic id for such a specific block.   I would think something like `sidebar_menu_block` would give it more meaning and tie it to the actual class name.  Will need to alter this in all the config in this pr.

2021-06-03 02:21 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> + *   admin_label = @Translation("Sidebar Menus block")
```suggestion
 *   admin_label = @Translation("Sidebar Menus block")
 *   category = @Translation("Menus")
```

2021-06-03 12:00 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +      $menu_link_service = $this->menuLinkManager;
Well, when you say it like that........
This was me copying an example online, and not thinking critically enough about it.
:+1:

2021-06-03 12:02 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +      }
Yeah, I was hoping I could justify squeaking this in my build method b/c it's small, but you are right :+1:

2021-06-03 12:21 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +          'config:system.menu.' . $menu_name,
@kevwalsh has been experiencing weirdness with testing on the tugboat instance, e.g.: seeing sidebar nav menus from the previous vamc when visiting a new vamc (or a benefit detail page). So, I guess the thing I'm trying to solve for is how to prevent the wrong menu from appearing when first switching context, @swirtSJW ?

2021-06-03 12:35 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> + *   id = "va_gov_backend",
> This seems like a very generic id for such a specific block. I would think something like `sidebar_menu_block` would give it more meaning and tie it to the actual class name. Will need to alter this in all the config in this pr.

Ugh.....I don't know why I gave this block such a weak name.

2021-06-03 15:06 UTC, swirtSJW requested changes
Looks like the awol issues came back plus some other stuff.

2021-06-03 16:08 UTC, ethanteague commented on config/sync/core.entity_form_display.node.regional_health_care_service_des.inline_entity_form.yml
> -  revision_log: true
ARGHHHHHHHHH

2021-06-03 20:21 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +    $menu_tree_service = $this->menuLinkTree;
That name juggling for no good reason thing.

2021-06-21 18:06 UTC, ethanteague commented
Assuming performance tests check out, this can be merged, @kevwalsh 

cc: @indytechcook

2021-07-06 20:40 UTC, indytechcook submitted a review, later dismissed
After doing the performance review in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5734, I found that this new code is more performant than the current code.  See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5734#issuecomment-874966507 for the links to the blackfire diffs.

2021-07-06 20:40 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +    if ($args[1] === 'pittsburgh-health-care') {
This snowflake already exists in `Drupal\va_gov_graphql\Plugin\GraphQL\Fields\SideNavMenus` line 33.  Due to my dislike of snow, Is it possible to create a `VAMenuSevice` with an `isSideBarMenu` method?

2021-07-07 11:22 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +    if (!empty($node)) {
Do you want to check if this is a `NodeInterface`?

2021-07-07 11:52 UTC, indytechcook commented on config/sync/block.block.sidebarmenusblock.yml
> +visibility:
I've read there are some bugs with block visibility described here: https://www.drupal.org/project/drupal/issues/923934.  If you continue to have issues, a custom Conditional plugin might be the way to go (or that patch)  

Conditional Plugin info:
* https://spinningcode.org/2017/06/controlling-block-visibility-with-a-custom-field-in-drupal-8/
* https://drupal.stackexchange.com/a/224163

2021-07-09 14:13 UTC, ethanteague commented on config/sync/block.block.sidebarmenusblock.yml
> +visibility:
I see the problem - we aren't forcing the menu add option on events, and as such, events aren't being assigned to a menu, so there is no context for the sidenav to work with. This isn't a bug with the sidebar menu block. If you go to /va-tennessee-valley-health-care/events/va-tennessee-valley-placeholder-event, and on the edit form, add it to TVA -> Events, on save, the TVA menu appears in the sidebav.

2021-07-09 14:17 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +    if (!empty($node)) {
You mean....like.....do it the right way? :+1:

2021-07-09 14:22 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
> +    if ($args[1] === 'pittsburgh-health-care') {
Good thinking / eye, @indytechcook - will put it together.

2021-07-09 15:41 UTC, ndouglas commented
Not sure if doing it right -- I should see the menu on these, right?

<img width="1751" alt="Screen Shot 2021-07-09 at 11 39 17 AM" src="https://user-images.githubusercontent.com/1318579/125103406-503a6b00-e0aa-11eb-81f0-20615923a4d2.png">

https://cms-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/wilkes-barre-health-care/events/deadline-for-entry-into-the-2021-local-veterans-creative-arts-competition-is-july-30

I'm seeing the menu here:

https://cms-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/wilkes-barre-health-care/policies

and on the VAMC facility nodes, but not in the events I looked at.

2021-07-09 16:04 UTC, ethanteague commented
> Not sure if doing it right -- I should see the menu on these, right?
> 
> <img alt="Screen Shot 2021-07-09 at 11 39 17 AM" width="1751" src="https://user-images.githubusercontent.com/1318579/125103406-503a6b00-e0aa-11eb-81f0-20615923a4d2.png">
> 
> https://cms-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/wilkes-barre-health-care/events/deadline-for-entry-into-the-2021-local-veterans-creative-arts-competition-is-july-30
> 
> I'm seeing the menu here:
> 
> https://cms-sbfhan6rl6jarzcwkrvrpqghxnub9jsh.ci.cms.va.gov/wilkes-barre-health-care/policies
> 
> and on the VAMC facility nodes, but not in the events I looked at.

Needs to be added to the menu on the node form, @ndouglas , then published.
No:
![image](https://user-images.githubusercontent.com/2404547/125106528-be346180-e0ad-11eb-8d14-d6634d68851b.png)
Yes:
![image](https://user-images.githubusercontent.com/2404547/125106543-c1c7e880-e0ad-11eb-9e1e-cb90b7e47ea3.png)
Published:
![image](https://user-images.githubusercontent.com/2404547/125106564-c5f40600-e0ad-11eb-82d1-0acc73006fa9.png)

2021-07-09 16:06 UTC, ndouglas commented
And I was enlightened 😃

2021-07-09 16:06 UTC, ndouglas approved these changes

2021-07-16 04:06 UTC, swirtSJW approved these changes
The code looks good and Neil has signed off on my performance concern, so we just need to have this pass hand QA.     I will reQA after the rebase.

2021-07-16 16:34 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/125980152-d60fe064-3026-4774-8e8a-a9dc8bf42021.png)

2021-07-16 16:34 UTC, merged