VACMS-5180: Update email links and location info display.
department-of-veterans-affairs/va.gov-cms pull request #5621
Opened 2021-06-16 00:37 UTC by ethanteague

## Description
See #5180

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/122140255-cf74b000-ce18-11eb-978e-3396c58ae5d6.png)

## QA steps
- As an administrator, go to `/node/1322/edit` and visually verify that the location info now appears in a tooltip'd fieldset, and hovering over the tooltip icon reveals fieldset info.
- Click the `contact an administrator` link, and visually verify it follows the template guidelines defined by Rachel in ticket.
- Go to view page for node 1322, click the `contact an administrator` link, and visually verify it follows the template guidelines defined by Rachel in ticket.
- Go to view page for `node/3774/edit`, click the `contact an administrator` link, and visually verify it follows the template guidelines defined by Rachel in ticket.
- Go to view page for node 3774, click the `contact an administrator` link, and visually verify it follows the template guidelines defined by Rachel in ticket.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-06-16 17:04 UTC, kevwalsh requested changes
From zoom call

- [ ] Use view mode instead of disabled fields, like in the Vet Center facility node experience
  - [ ] grey background with `.not-editable`
- [ ] Switch from inline field labels on node view mode to "above"
- [ ] UX Writing changes, coming from @rachel-kauff 
  - [ ] Tooltip text 
  - [ ] Fieldgroup description 
  - [ ] Fieldgroup label "Facility data from VAST"
  - [ ] Email text updates

2021-06-16 22:46 UTC, ethanteague commented
> From zoom call
> 
> * [x]  Use view mode instead of disabled fields, like in the Vet Center facility node experience
>   
>   * [x]  grey background with `.not-editable`
> * [x]  Switch from inline field labels on node view mode to "above"
> * [ ]  UX Writing changes, coming from @rachel-kauff
>   
>   * [ ]  Tooltip text
>   * [ ]  Fieldgroup description
>   * [ ]  Fieldgroup label "Facility data from VAST"
>   * [ ]  Email text updates

While @rachel-kauff is hammering on the ux writing changes, I updated the display stuff, @kevwalsh:
![image](https://user-images.githubusercontent.com/2404547/122304434-3787cc80-ced3-11eb-908c-2507acc9aa86.png)

2021-06-16 23:28 UTC, rachel-kauff commented
> > From zoom call
> > 
> > * [x]   Use view mode instead of disabled fields, like in the Vet Center facility node experience
> >   
> >   * [x]   grey background with `.not-editable`
> > * [x]   Switch from inline field labels on node view mode to "above"
> > * [ ]   UX Writing changes, coming from @rachel-kauff
> >   
> >   * [ ]   Tooltip text
> >   * [ ]   Fieldgroup description
> >   * [ ]   Fieldgroup label "Facility data from VAST"
> >   * [ ]   Email text updates
> 
> While @rachel-kauff is hammering on the ux writing changes, I updated the display stuff, @kevwalsh:
> ![image](https://user-images.githubusercontent.com/2404547/122304434-3787cc80-ced3-11eb-908c-2507acc9aa86.png)

UX writing recommendations in this mural: https://app.mural.co/t/vagov6717/m/vagov6717/1623884203877/dca75b9a5e81c0f3ab856f704004cfb43cc9d473

@kevwalsh can you review first?

2021-06-17 02:45 UTC, kevwalsh commented
@rachel-kauff 

1. i don't think that "auto-generated" is appropriate in the fieldgroup label, because that makes it sound like it is AI or bot-created. Bots help move it around via api, but the data itself is managed by humans "elsewhere".  
2. This can get philosophical and maybe i'm overly sensitive to this topic, but mixing the words "data" and "content" in the fieldgroup label and fieldgroup description is confusing. Either it's data or it's content. In this case i think it's _data_, because "content" is what happens when the data has been assembled/designed in a way that adds meaning. Found [this resource that explains it well](https://www.cmswire.com/cms/web-engagement/content-strategy-understanding-the-difference-between-data-information-and-content-009088.php). 
3. I agree that the description should go in the child fieldgroup.

![UX_writing_scratchpad_•_Agile_Six](https://user-images.githubusercontent.com/643678/122323048-77ab7700-cef4-11eb-92a7-c9e54be59256.png)
 
@ethanteague i think there's enough for you to go on for config but we'll still need to get some final wording from Rachel which you can probably just copy/paste into the config yml later.

2021-06-17 03:10 UTC, kevwalsh requested changes
Combining Rachel's design updates and some QA... this screenshot shows PAO view on the left (using vanessa.luxen@va.gov on https://pr5621-b8zcua99smjgisilu0jx6nvzsdwhyotp.ci.cms.va.gov/node/1327/edit), and admin view on the right

![Edit_VAMC_Facility_Butler_VA_Medical_Center___VA_gov_CMS_and_Edit_VAMC_Facility_Butler_VA_Medical_Center___VA_gov_CMS_and_Android_Messages](https://user-images.githubusercontent.com/643678/122324985-c4448180-cef7-11eb-96b1-9fecdd803486.png)


- [ ] Field group changes
  - [ ] Add provisional fieldgroup label "Facility data" to the tooltip fieldgroup
  - [ ] Add provisional fieldgroup description "To request a correction or update to this data, email an administrator." to the tooltip fieldgroup and remove description from its parent field group.
- [x] For content admins
  - [x] Get rid of all the code that disables the fields 
- [ ] "Name of facility" field 
  - [ ] should appear within the tooltip fieldgroup as non-editable text for non-content-admins, and as editable for content admins
  - [ ] should not appear below the tooltip fieldgroup as it is right now. 
- [x] Remove all redundant help text on fields that appear within the tooltip fieldgroup

Stretch: 
- [x] get rid of crazy padding on hours table 
- [x] Change Mobile field display from TRUE/FALSE to Yes/No. @rachel-kauff any thoughts on this?  I'm sure we could do better than "Mobile: Yes/No" but not sure if we want to dig too deep here, and moving away from the TRUE/FALSE is a very quick change.

2021-06-17 16:08 UTC, rachel-kauff commented
@ethanteague Wiggled the words a bit more, ready for 🚀 . cc: @kevwalsh

2021-06-18 00:50 UTC, kevwalsh requested changes
Another round of review, found 4 issues but only the first one (red in screenshot) is a dealbreaker

<img width="1400" alt="Edit_VAMC_Facility_Butler_VA_Medical_Center___VA_gov_CMS_and_Edit_VAMC_Facility_Butler_VA_Medical_Center___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/122489150-fc59cc00-cfac-11eb-8a13-66bf44ef1430.png">

- [ ] Name of facility should appear first for non-content admins (blocker)

Minor issues, not necessarily blockers
- [ ] phone numbers should not be displayed as links in the application because it triggers useless node link reports
- [x] field group labels for tooltip fieldgroups should match the standard fieldgroup label (existing issue,  not a regression here)
- [x] first fieldgroup's description is misplaced for content admin

2021-06-18 20:23 UTC, ethanteague commented
@ndouglas @swirtSJW @kevwalsh have an accesibility failure here that I can't figure out - the output doesn't give me anything more than a content type, and when I run axe locally in a browser, the one "severe" violation that Nate helped me suss out before is no longer present (I fixed). Gonna need someone to help me buy a clue.

2021-06-21 01:19 UTC, kevwalsh requested changes
Two things, then i thikn we can call this done!

- [ ] "Page title" field label should appear below the fieldgrop description, not above, on Vet Centers
- [ ] drop "API " from the 15 places  where it appears in the phrase "centrally-managed API data".

2021-06-21 18:05 UTC, ethanteague commented
If all looks good, feel free to merge, @kevwalsh

2021-06-24 14:46 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/js/script.es6.js
> +              // than using the global flag.
Because it uses regex syntax?  Just try'n'a understand.

2021-06-24 14:46 UTC, ndouglas commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    $get_help = '<div id="top-get-help-email">To request a correction or update to this centrally-managed data, <a class="admin-help-email-tpl" href="mailto:api@va.gov?bcc=vadrupalcms@va.gov&subject=
Can we do this another way?  In the past I've used templates for this sort of thing, and that's probably overkill, but it'd be nice to have an efficient, editable way of managing these mailto links.

2021-06-24 14:46 UTC, ndouglas commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    if ($node->gettype() !== 'health_care_local_facility') {
should this be `$node->getType()`?

2021-06-24 14:47 UTC, ndouglas commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    if ($node->gettype() !== 'health_care_local_facility') {
TIL PHP is not case-sensitive.  Been using it almost twenty years and didn't know that.

2021-06-24 14:58 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/js/script.es6.js
> +              // than using the global flag.
@ndouglas : Yeah. It's heavier to run with the `g` and I get unpredictable results (e.g.: sometimes it scoops up all instances, sometimes it doesn't, and I don't know why).

2021-06-24 15:00 UTC, ethanteague commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    if ($node->gettype() !== 'health_care_local_facility') {
Lol.....it is a typo, but I didn't know that, either, @ndouglas ! No wonder it worked.

2021-06-24 15:01 UTC, ndouglas submitted a review, later dismissed

2021-06-24 15:23 UTC, ethanteague commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    $get_help = '<div id="top-get-help-email">To request a correction or update to this centrally-managed data, <a class="admin-help-email-tpl" href="mailto:api@va.gov?bcc=vadrupalcms@va.gov&subject=
Per slack convo, I'm gonna break this off into a separate task.

2021-06-24 17:51 UTC, merged