VACMS-4988 Prevent notice when Menu form is not present.
department-of-veterans-affairs/va.gov-cms pull request #5648
Opened 2021-06-18 16:16 UTC by swirtSJW

## Description

See #4988. 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-07-14 15:00 UTC, swirtSJW commented
Something is amiss.  I am getting what looks like proper options for 
Pittsburgh as RS
![image](https://user-images.githubusercontent.com/5752113/125644627-1467b6c9-1adf-4492-9b24-41b85d82a189.png)
But not for Albany as Peter.potter
![image](https://user-images.githubusercontent.com/5752113/125644746-d1910c47-b539-4003-9154-ae6d4054d225.png)

2021-07-15 00:39 UTC, kevwalsh requested changes
As a publisher in Albany, i was able to create a VAMC detail page without touching the menu settings (i should have been forced to set it to Programs, or Research, etc)

<img width="809" alt="asdfasdf_asdf___VA_Albany_health_care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/125709997-cbf5cb61-05c8-4f22-9b8b-283cf9c1ade4.png">

Then when i went to edit it (https://pr5648-cebnmfzeip2qe1sje8ewy9pjmt4dboqf.ci.cms.va.gov/node/27562/edit), i saw that a menu item had been created that i could no longer edit. 
<img width="521" alt="Edit_VAMC_Detail_Page_asdfasdf_asdf___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/125710040-c4de63a3-d8fb-454e-8f93-613c961e9ff4.png">

As i suspected, it was created under Pittsburgh, which is the default parent. i could see this by logging in as admin 

<img width="517" alt="Edit_VAMC_Detail_Page_asdfasdf_asdf___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/125710135-de81babf-1933-4e72-b816-fc4c2d241edf.png">

2021-07-15 01:49 UTC, swirtSJW commented
Good catch.  I can fix that.   I just need to move the non-default default addition to AFTER we reduce the menu.

2021-07-15 02:54 UTC, swirtSJW commented
I fixed the issue of the empty setting being wiped out by the menu reduction.  
![image](https://user-images.githubusercontent.com/5752113/125720532-31f9f587-b356-4508-b357-81bf1630f513.png)

2021-07-15 03:00 UTC, swirtSJW commented
I discovered another problem.
https://pr5648-cebnmfzeip2qe1sje8ewy9pjmt4dboqf.ci.cms.va.gov/node/8635/edit
![image](https://user-images.githubusercontent.com/5752113/125720957-988cc309-be55-4524-8aa0-556a807c25a4.png)

For any menu item assigned to `About us` the selector should be locked.   It allows something to be moved  out of "About us" but there is no way to put it back in.

2021-07-15 12:51 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      $alias = $this->getAliasFromUri($menu_item->get('link')->uri);
Is there a method we can use here instead of grabbing naked `uri`? Don't we run the risk of getting a grumpy message from Drupal if (for some reason) uri isn't present?

2021-07-15 12:51 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +        $subject_uuid = $parent_options_menu_ids[$menu_item->get('uuid')->value];
Same q as above.

2021-07-15 13:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      $alias = $this->getAliasFromUri($menu_item->get('link')->uri);
That is a great question.   Good eyes.     Usually accessing a property directly should be avoided and a method should be used.  However in this case `$menu_item->get('link')`  returns a [Drupal\Core\Field\FieldItemList](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Field%21FieldItemList.php/class/FieldItemList/9.0.x)

There is no specific method for uri.

**But** there is a magic __get which returns any property that is public and NULL if you request something that does not exist (see the request for the fictitious 'boog' below, it results in no grumpiness).

![image](https://user-images.githubusercontent.com/5752113/125796043-8e24a5c2-6d84-46df-af55-098ee80c6168.png)

So the only risk in this is that get(link) does not return a FieldItemList   which would only happen if someone hacked menu module to not use a select list for parents.

2021-07-15 13:37 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +        $subject_uuid = $parent_options_menu_ids[$menu_item->get('uuid')->value];
Similar answer.   Great raising this as a legit concern though.
![image](https://user-images.githubusercontent.com/5752113/125797233-6a4181e8-d336-46d4-be41-74e77062da67.png)

2021-07-15 13:40 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +      $alias = $this->getAliasFromUri($menu_item->get('link')->uri);
Ah - appreciate you chasing that down, @swirtSJW !

2021-07-15 13:40 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
> +        $subject_uuid = $parent_options_menu_ids[$menu_item->get('uuid')->value];
Awesome, @swirtSJW

2021-07-15 13:42 UTC, ethanteague approved these changes
:+1:

2021-07-15 13:46 UTC, swirtSJW commented
Looks like some legit test failures related to menu items   :(

![image](https://user-images.githubusercontent.com/5752113/125798685-af455c13-aa7e-4cce-a01e-fa76561543f7.png)

2021-07-15 14:14 UTC, swirtSJW commented
The web build test failure is due to the Daisy award node.  It has already been fixed in prod so will need to rebuild this with a fresh copy.

2021-07-15 20:37 UTC, swirtSJW commented
I just pushed up a fix to prevent the error on the behat test.  (due to behat not having access to any parents.)
@ethanteague can you take a looky-see at the latest commit?

2021-07-15 20:41 UTC, ethanteague submitted a review, later dismissed
LGTM, @swirtSJW

2021-07-16 02:25 UTC, swirtSJW commented
This is ready for merge and is just on hold to coordinate release communication.

2021-07-16 15:13 UTC, swirtSJW commented
I updated the patterns to include the two that were missing.

2021-07-16 16:13 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/125977704-d8eb6c54-6d6f-414f-b322-9b84fc3a9d99.png)

2021-07-16 16:14 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/125977831-13f8fd47-1cb1-44b0-a043-4b9c72ee0169.png)

2021-07-16 16:15 UTC, merged