VACMS-5669 update url patterns
department-of-veterans-affairs/va.gov-cms pull request #5690
Opened 2021-06-24 20:04 UTC by ethanteague

## Description
See #5669

## Testing done
Visual, cypress, bulk update

## QA steps
- As an administrator, run bulk alias update on all content.
- Visit any location listing, and visually verify that the path is inherited from the parent item in the breadcrumb.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-06-24 21:49 UTC, kevwalsh requested changes
Requesting one change for now (removing menu_force from `page`), we probably need to discuss the other things.

2021-06-24 21:49 UTC, kevwalsh commented on config/sync/node.type.page.yml
> +    menu_force: 1
I think we need to pull out this content type for now, [based on this slack convo](https://dsva.slack.com/archives/C01K37HRUAH/p1624570534096400). Sorry!

2021-06-24 21:49 UTC, kevwalsh commented on docroot/modules/custom/va_gov_db/va_gov_db.install
> + * Enable pathauto for vamc leadership_listing node types.
We may need to put this in its own PR, or think about where this fits into the #5500 runbook. Let's chat about it.

2021-06-24 22:24 UTC, ethanteague commented on config/sync/node.type.page.yml
> +    menu_force: 1
Np, a'tall.

2021-06-25 03:37 UTC, kevwalsh commented on config/sync/node.type.page.yml
> +    menu_force: 1
Crap, i just realized that i should have put this in #5689, the branch on which this branch is built. My bad. Let's fix it there, merge and rebase, and we can the rest of this merged next week.

2021-06-25 03:39 UTC, kevwalsh commented on config/sync/node.type.landing_page.yml
> +    - menu_force
Sorry let's remove this content type too, since we're also removing `page`, which is closely connected.

2021-06-28 12:50 UTC, kevwalsh commented
i just put “do not merge” on it. because it resets the URL aliases to use “generate automatically”, this needs to be merged right before update all the Leadership Listing aliases. it’ll probably sit here for a week or so

2021-07-06 17:10 UTC, kevwalsh commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    'leadership_listing',
Not sure if we actually want this.Per slack

> we want to reset Leadership nodes to generate URLs from h1s, but then after we regenerate those h1s, we want it to go back to being locked again

2021-07-07 02:06 UTC, kevwalsh commented
@ethanteague can you have a look at this confict?

2021-07-07 13:46 UTC, ethanteague commented
> @ethanteague can you have a look at this confict?

Fixed, @kevwalsh

2021-07-08 01:12 UTC, kevwalsh commented
Would be good to merge this Tuesday July 13 so that we can finish out #5500 that afternoon or the following morning.

2021-07-13 11:45 UTC, kevwalsh approved these changes
I thought i had approved this earlier.

2021-07-13 11:46 UTC, merged