VACMS-4056: Add logic to restrict elements to certain roles on centralized content.
department-of-veterans-affairs/va.gov-cms pull request #5735
Opened 2021-06-28 17:11 UTC by ethanteague

## Description
See #4056

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/123676390-e3091900-d811-11eb-8638-d052f982ea5e.png)

## QA steps
As an administrator, visit `/node/16142/edit` and visually verify that deletes, actions (the three vertical dots elements), row drags, and `Show row weights` action link appear.
Log in as a user who is not a content admin / admin, visit `/node/16142/edit` and visually verify that deletes, actions (the three vertical dots elements), row drags, and `Show row weights` action link do not appear.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-06-28 17:47 UTC, ndouglas commented
unrelated but nevertheless poetic 

<img width="151" alt="Screen Shot 2021-06-28 at 1 46 52 PM" src="https://user-images.githubusercontent.com/1318579/123681094-5feac180-d817-11eb-8801-8ba823c12ace.png">

2021-06-28 17:53 UTC, ndouglas commented
Still seeing row weights with a [normal user](https://cms-hh5yokv1sc3susjvaaawvlgutl47bs36.ci.cms.va.gov/user/2386/edit):

<img width="231" alt="Screen Shot 2021-06-28 at 1 51 10 PM" src="https://user-images.githubusercontent.com/1318579/123681507-eacbbc00-d817-11eb-84fb-9b383f2c6b45.png">

I explicitly gave this user access to the Vet Centers section.

Prior to logging in with this account, I clicked "Show row weights" with my personal account.  When logging in I noticed that row weights were shown.  Perhaps that's a confounding factor, or perhaps I misread something.  Happy to assist further if needed but I'll be in backlog refinement for a couple hours now.

2021-06-28 17:58 UTC, ethanteague commented
> Still seeing row weights with a [normal user](https://cms-hh5yokv1sc3susjvaaawvlgutl47bs36.ci.cms.va.gov/user/2386/edit):
> 
> <img alt="Screen Shot 2021-06-28 at 1 51 10 PM" width="231" src="https://user-images.githubusercontent.com/1318579/123681507-eacbbc00-d817-11eb-84fb-9b383f2c6b45.png">
> 
> I explicitly gave this user access to the Vet Centers section.
> 
> Prior to logging in with this account, I clicked "Show row weights" with my personal account. When logging in I noticed that row weights were shown. Perhaps that's a confounding factor, or perhaps I misread something. Happy to assist further if needed but I'll be in backlog refinement for a couple hours now.

Thanks, @ndouglas ! I'll see what's up and ping you when I get it figured out.

2021-06-29 05:20 UTC, kevwalsh requested changes
Tested as user/1523 who has access to /node/16142/edit as a content publisher, and this works well! 

But we also have to remove access for content admins, such as user/1342

2021-06-29 05:20 UTC, kevwalsh commented on docroot/modules/custom/va_gov_backend/js/script.es6.js
> +      const adminRoles = ["content_admin", "administrator"];
This should only be administrator.

2021-06-29 05:21 UTC, kevwalsh commented
Ah, i missed the part about QAing the row weights, but i'm glad Nate caught that!

2021-06-29 12:05 UTC, ethanteague commented
@kevwalsh & @ndouglas pr updated - have a look when you all get a sec, and I'll merge if it looks good.

2021-06-29 12:52 UTC, ndouglas commented
<img width="1430" alt="Screen Shot 2021-06-29 at 8 51 41 AM" src="https://user-images.githubusercontent.com/1318579/123800375-3d0fea00-d8b7-11eb-93ae-694176b2c5fa.png">

Looking into this test failure...

<img width="1362" alt="Screen Shot 2021-06-29 at 8 52 09 AM" src="https://user-images.githubusercontent.com/1318579/123800445-4ef18d00-d8b7-11eb-9c4b-c6a51c0e28a6.png">

Yup.

I'm not sure why this is happening, but lemme look into it and figure out what's up so your tests will pass.

2021-06-29 13:13 UTC, ndouglas approved these changes
LGTM, verified the elements are restricted appropriately.

2021-06-29 13:42 UTC, merged