VACMS-5774: Add vc facility listing block to node view and form.
department-of-veterans-affairs/va.gov-cms pull request #5786
Opened 2021-07-06 21:26 UTC by ethanteague

## Description
See #5774

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/124668707-3c5ef100-de7f-11eb-97bd-b69ce2460e49.png)
![image](https://user-images.githubusercontent.com/2404547/124668717-3ff27800-de7f-11eb-9eb7-2b20223dee03.png)

## QA steps
 - As an admin, go to `/admin/structure/types/manage/vet_center_locations_list/fields` and `/nashville-vet-center/locations` and compare to screenshots.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-07-07 02:43 UTC, kevwalsh requested changes

2021-07-07 02:43 UTC, kevwalsh commented on config/sync/field.field.node.vet_center_locations_list.field_nearby_vet_centers.yml
> -label: 'Nearby Vet Centers and Outstations'
Wrong field! This field label change and addition of description should go on Nearby Mobile Vet Centers, not Nearby Vet Centers.

2021-07-07 02:43 UTC, kevwalsh commented on config/sync/field.field.node.vet_center_locations_list.field_nearby_vet_centers.yml
> +description: 'Add any additional Mobile Vet Centers that are not already associated with your Vet Center.'
There's not enough padding between the description and the button. 

![Edit_Vet_Center_-_Locations_List_Locations___VA_gov_CMS](https://user-images.githubusercontent.com/643678/124691309-a2f90480-dea9-11eb-8ca1-13ad4a41b4d9.png)

2021-07-07 02:43 UTC, kevwalsh commented on config/sync/views.view.vet_center_facility_listing.yml
> +            image_style: 3_2_medium_thumbnail
Now that i see this in my place, i think we should make it look more like the entity browser fields below

- [ ] remove images from here. 
- [ ] remove facility status
- [ ] add Moderation state field, but change the label to "Status" to match the entity browser fields below. 
- [ ] Change label to "Main and satellite locatoins"
- [ ] Change fieldgroup to Details, not collapsed to match the ones below

Sorry for the change in tact!


![Edit_Vet_Center_-_Locations_List_Locations___VA_gov_CMS](https://user-images.githubusercontent.com/643678/124692385-852c9f00-deab-11eb-8124-ef260b29e6de.png)

2021-07-07 11:29 UTC, ethanteague commented on config/sync/field.field.node.vet_center_locations_list.field_nearby_vet_centers.yml
> -label: 'Nearby Vet Centers and Outstations'
Argh - sorry about that. They looked too similar to me in config, and I got my eyes crossed, @kevwalsh.

2021-07-07 11:32 UTC, ethanteague commented on config/sync/field.field.node.vet_center_locations_list.field_nearby_vet_centers.yml
> +description: 'Add any additional Mobile Vet Centers that are not already associated with your Vet Center.'
Yeah, agreed, @kevwalsh - you were trying to tell me to do that in the ticket when you wrapped the description in a `p` !

2021-07-07 11:33 UTC, ethanteague commented on config/sync/views.view.vet_center_facility_listing.yml
> +            image_style: 3_2_medium_thumbnail
I was wondering the same - no problem, @kevwalsh :+1:

2021-07-07 19:30 UTC, kevwalsh approved these changes
Looks great Ethan

![Edit_Vet_Center_-_Locations_List_Locations___VA_gov_CMS](https://user-images.githubusercontent.com/643678/124817682-1b0e0b80-df38-11eb-976d-5675795a7b51.png)

2021-07-07 19:33 UTC, kevwalsh commented on config/sync/field.field.node.vet_center_locations_list.field_nearby_vet_centers.yml
> -label: 'Nearby Vet Centers and Outstations'
no worries, it's the same problem that editors were facing too. Confusion.

2021-07-14 00:22 UTC, kevwalsh approved these changes
QA Pass, i checked as 5 different MVP users listed from https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/product-brief.md and edited Locations List page, all behaved as expected.

2021-07-14 14:38 UTC, kevwalsh commented
It says there was a Behat failure but [i don't see any](https://tugboat.vfs.va.gov/log/60e4ca9e4fa3233927d8f332)

2021-07-14 14:55 UTC, ethanteague commented
> It says there was a Behat failure but [i don't see any](https://tugboat.vfs.va.gov/log/60e4ca9e4fa3233927d8f332)

Looks like a connection issue - rebuilding.

2021-07-14 18:39 UTC, merged