VACMS-5784: Remove weight set on VISN titles items.
department-of-veterans-affairs/va.gov-cms pull request #5787
Opened 2021-07-07 16:08 UTC by ethanteague

## Description
See #5784

## Testing done
Visual

## Implementation notes
 - This removes the weight set on save for taxonomy items that begin with `VISN`
 - Will require setting the weight for these items (I assigned each VISN a weight to match it's VISN #) on prod after deploy, here: `/admin/structure/taxonomy/manage/administration/overview`

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-07-08 01:07 UTC, kevwalsh commented
@ethanteague i wasn't sure how to QA this. On https://pr5787-peybkcjlspzye8lreyamufhbe40m2fe1.ci.cms.va.gov/admin/structure/taxonomy/manage/administration/overview, i set VISN 19 to weight 10, hit save, and it reset itself to 0, which was unexpected. 

also, i saw this long set of errors for the first time, not sure if it's related. 

There are ~240 of these. 
![Sections___VA_gov_CMS](https://user-images.githubusercontent.com/643678/124846644-465c1f00-df67-11eb-83bf-1391aaeaaf09.png)

2021-07-08 11:33 UTC, ethanteague commented
Sorry about that, @kevwalsh ! The method I was using to grab administration vocab was working for me yesterday (on my local)......but obviously isn't now. Not sure if related to the upgrade, or something else. Anyways, swapped out `getVocabularyId` for `bundle` and it seems to be working. Give it a retest when you get a minute (please).

2021-07-08 12:53 UTC, indytechcook commented
> Anyways, swapped out getVocabularyId for bundle and it seems to be working.

`getVocabularyId` was deprecated

2021-07-12 14:16 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
>      if (array_key_exists(8, $parents) || array_key_exists(190, $parents)) {
Can we add a comment to clarify what is special about '8' and '190'  or assign them to meaningful variables so we know what they represent?

2021-07-12 14:22 UTC, swirtSJW requested changes
I don't think this is the way we want to force a sort exemption.   All we are trying to do it get a "natural" sort rather than pure alpha sort.    Just set the flag on where we are sorting
https://www.php.net/manual/en/function.sort.php
https://www.php.net/manual/en/function.natsort.php

2021-07-12 17:38 UTC, ethanteague commented
> I don't think this is the way we want to force a sort exemption. All we are trying to do it get a "natural" sort rather than pure alpha sort. Just set the flag on where we are sorting
> https://www.php.net/manual/en/function.sort.php
> https://www.php.net/manual/en/function.natsort.php

@kevwalsh , whaddya think about @swirtSJW 's approach?

2021-07-13 11:11 UTC, kevwalsh commented
> > I don't think this is the way we want to force a sort exemption. All we are trying to do it get a "natural" sort rather than pure alpha sort. Just set the flag on where we are sorting
> > https://www.php.net/manual/en/function.sort.php
> > https://www.php.net/manual/en/function.natsort.php
> 
> @kevwalsh , whaddya think about @swirtSJW 's approach?

Makes sense!

2021-07-13 15:34 UTC, ethanteague commented
PER SCRUM CONVO: Remove weight set on save logic, and manually set weights for VISN's in ui.
cc: @kevwalsh @swirtSJW

2021-07-16 03:19 UTC, swirtSJW approved these changes

2021-07-16 03:22 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/125886809-7cf48f32-66ad-497a-8e05-0f33b671525f.png)

2021-07-16 03:23 UTC, merged