VACMS-5775: Update meta titles.
department-of-veterans-affairs/va.gov-cms pull request #5828
Opened 2021-07-12 13:47 UTC by ethanteague

## Description
See #5775

## Testing done
Behat

## QA steps
TBD

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-07-14 14:57 UTC, kevwalsh requested changes
it's good that our default will no longer include `node:field_office` but we need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required. Sorry if ACs were unclear in #5775, i just updated them a bit.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node.yml
> -  og_title: '[node:title] | [node:field_office] | Veterans Affairs'
We may need to remove the og_image spec altogether, pending convo with PW. Ideally they would check for a value before printing it.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__event.yml
> -  twitter_cards_title: '[node:title] | [node:field_office] | Veterans Affairs'
We need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__event_listing.yml
> -  twitter_cards_title: '[node:title] | [node:field_office] | Veterans Affairs'
We need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__health_care_local_facility.yml
> -  twitter_cards_title: '[node:title] | [node:field_office] | Veterans Affairs'
We need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__vamc_operating_status_and_alerts.yml
> -  twitter_cards_title: '[node:title] | [node:field_office] | Veterans Affairs'
We need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__press_release.yml
> -  twitter_cards_title: '[node:title] | [node:field_office] | Veterans Affairs'
We need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__person_profile.yml
> -  twitter_cards_title: '[node:title] | [node:field_office] | Veterans Affairs'
We need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__news_story.yml
> -  og_title: '[node:title] | [node:field_office] | Veterans Affairs'
We need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__health_care_region_page.yml
> -  title: '[node:title] | [node:field_office] | Veterans Affairs'
We need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__health_care_region_page.yml
>  label: 'Content: Health Care System'
This one should have og:image specified.

2021-07-14 14:57 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__health_care_region_detail_page.yml
> -  twitter_cards_title: '[node:title] | [node:field_office] | Veterans Affairs'
We need to keep `[node:title] | [node:field_office] | Veterans Affairs` wherever field_office is required.

2021-07-14 18:36 UTC, ethanteague commented
Thanks for taking the time to go through all those files, @kevwalsh :heart: - back to you.

2021-07-15 01:20 UTC, kevwalsh requested changes
I'm really sorry, i feel like i'm fumbling through the specs on this. we probably needed a spreadsheet approach to this one. 

Stories, Events, News releases do not have a field_office, so they'll need to pick that up by going through their respective List pages. See for example https://pr5828-wrb1q983pfwgqw6ixqwofsjszpwdosrp.ci.cms.va.gov/wilmington-health-care/stories/veteran-suicide-prevention-in-new-jersey

Leadership pages have a field_office that will; need to be inserted, see for example 
https://pr5828-wrb1q983pfwgqw6ixqwofsjszpwdosrp.ci.cms.va.gov/butler-health-care/about-us/leadership

Finally, Operating Status we should probalby treat specially, as follows: 
`Operating Status | [node:field_office] | Veterans Affairs` since their [node:title] is weird.

2021-07-15 01:20 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__campaign_landing_page.yml
> +  og_image: '[node:field_hero_image:entity:image:entity:3_2_medium_thumbnail:url]'
NOICE

2021-07-15 13:50 UTC, ethanteague commented
> I'm really sorry, i feel like i'm fumbling through the specs on this. we probably needed a spreadsheet approach to this one.
> 
> Stories, Events, News releases do not have a field_office, so they'll need to pick that up by going through their respective List pages. See for example https://pr5828-wrb1q983pfwgqw6ixqwofsjszpwdosrp.ci.cms.va.gov/wilmington-health-care/stories/veteran-suicide-prevention-in-new-jersey
> 
> Leadership pages have a field_office that will; need to be inserted, see for example
> https://pr5828-wrb1q983pfwgqw6ixqwofsjszpwdosrp.ci.cms.va.gov/butler-health-care/about-us/leadership
> 
> Finally, Operating Status we should probalby treat specially, as follows:
> `Operating Status | [node:field_office] | Veterans Affairs` since their [node:title] is weird.

Np a'tall, @kevwalsh - I should have thought of that.

2021-07-16 03:16 UTC, swirtSJW approved these changes
Approved by me.  Ready for merge if Kev approves.

2021-07-16 16:10 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/125977210-1c31aff9-bae4-4037-83cb-72de54c111ef.png)

2021-07-16 16:10 UTC, merged