VACMS-5781: Remove 4 visn endpoints.
department-of-veterans-affairs/va.gov-cms pull request #5832
Opened 2021-07-12 14:39 UTC by ethanteague

## Description
See #5781 
Removes 4 visn endpoints from migrations.

## Testing done
N/A

## Screenshots
N/A

## QA steps
N/A

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-07-19 15:22 UTC, kevwalsh requested changes

2021-07-19 15:22 UTC, kevwalsh commented on docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
> -    - https://www.butler.va.gov/locations/facilities.asp
re-add Butler (pending comment from @SgardnerPMP)

2021-07-23 14:28 UTC, kevwalsh commented
@ethanteague can you once again remove Butler endpoint and also remove Oklahoma City endpoint

2021-07-23 15:53 UTC, kevwalsh approved these changes

2021-07-26 14:31 UTC, indytechcook approved these changes

2021-07-26 21:53 UTC, swirtSJW approved these changes

2021-07-26 21:54 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/127064225-f48f43cb-dba6-46ce-a440-5aac5be6aec0.png)

2021-07-26 21:55 UTC, merged