VACMS-5887: Adding workaround for core issue related to block lazy loading
department-of-veterans-affairs/va.gov-cms pull request #5906
Opened 2021-07-20 13:37 UTC by ethanteague

## Description
See #5887

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/126333482-8be85ee6-a5ec-48dc-9bd6-d187a1d82b5e.png)
![image](https://user-images.githubusercontent.com/2404547/126333496-68cd5577-2dfa-4857-af8e-235a79372943.png)

## QA steps
 - Go to /escanaba-vet-center and visually verify left sidebar is not visible.
 - Go to /pittsburgh-health-care and visually verify left sidebar is visible.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-07-20 14:15 UTC, swirtSJW approved these changes
I don't really like that we are hiding it by default and then only enabling with JS, but I can't think of a way that work in a more failsafe fashion that would not create other strange occurrences if JS failed.

2021-07-20 14:36 UTC, ethanteague commented
> I don't really like that we are hiding it by default and then only enabling with JS, but I can't think of a way that work in a more failsafe fashion that would not create other strange occurrences if JS failed.

Agreed - this approach is weak. I figure out another way, @swirtSJW . Can you take a look when you have a minute?

2021-07-20 16:54 UTC, swirtSJW requested changes
I like this approach a lot better.  Nice work.    Just a few suggestions to make the code more self descriptive.

2021-07-20 16:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  _va_gov_menu_access_exclude_block_from_lazybuilder($build, $block);
```suggestion
  _va_gov_menu_access_exclude_sidebar_menu_block_from_lazybuilder($build, $block);
```
Truthful code is clean code.

2021-07-20 16:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +function _va_gov_menu_access_exclude_block_from_lazybuilder(array &$build, BlockPluginInterface $block) {
```suggestion
function _va_gov_menu_access_exclude_sidebar_menu_block_from_lazybuilder(array &$build, BlockPluginInterface $block) {
```

2021-07-20 16:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> + * Prevents lazybuilder placeholders from being set on blocks.
```suggestion
 * Prevents lazybuilder placeholders from being set on sidebar menu blocks.
```

2021-07-20 16:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  if ($block->getPluginId() == 'sidebar_menu_block') {
```suggestion
  if ($block->getPluginId() === 'sidebar_menu_block') {
```

2021-07-20 17:00 UTC, swirtSJW approved these changes
Just waiting on tests to run.

2021-07-20 17:11 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  _va_gov_menu_access_exclude_block_from_lazybuilder($build, $block);
I dunno if we wanna limit this function namespace to `sidebar_menu_block`. Since the lazyBuild thing is an issue for any block that lives by it's lonesome in any region, I can see us wanting to add additional blocks to this function, @swirtSJW

2021-07-20 17:12 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  if ($block->getPluginId() == 'sidebar_menu_block') {
D'oh! Thanks for catching that, @swirtSJW :+1:

2021-07-20 17:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  _va_gov_menu_access_exclude_block_from_lazybuilder($build, $block);
But the conditional that is being acted upon is that sidebar_menu_block.

2021-07-20 17:36 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  _va_gov_menu_access_exclude_block_from_lazybuilder($build, $block);
Yes, but I can see us adding in other id's to the conditional, e.g.:  ` if (in_array($block->getPluginId(), $array_of_blocks_to_not_lazy_build) ...`

2021-07-20 17:52 UTC, ethanteague commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  _va_gov_menu_access_exclude_block_from_lazybuilder($build, $block);
Not that big of a deal, and I'm fine with merging, just wanted to let you know my thought process when I named it.

2021-07-20 21:22 UTC, swirtSJW commented on docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
> +  _va_gov_menu_access_exclude_block_from_lazybuilder($build, $block);
When we expand its scope, we can rename so that it stays truthful.

2021-07-22 14:23 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/126655493-8969a4a9-4a96-4ddd-9eac-ee68272b1bb0.png)

2021-07-22 14:23 UTC, merged