VACMS-5912 Vamc limiter
department-of-veterans-affairs/va.gov-cms pull request #5954
Opened 2021-07-23 17:43 UTC by ethanteague

## Description

Closes #5912

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/126820827-ec0da41a-e17b-437e-ad91-d12b18027bfe.png)

## QA steps
 - As `jacob.dillon@va.gov`, go to `node/add/full_width_banner_alert` and visually verify only WIlmington checkbox appears.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-07-27 17:25 UTC, kevwalsh submitted a review, later dismissed
QA pass!

2021-07-28 14:32 UTC, swirtSJW requested changes
I think this too heavy handed.  It should only limit it for some editors, It should not limit it for content_admin or admin
![image](https://user-images.githubusercontent.com/5752113/127340769-ac7be05e-86b3-4736-8529-d49cc862e11f.png)

2021-07-28 14:37 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/127341396-b2aa9cb0-95d9-403c-b3cf-22b751f6aa88.png)

The testing steps for this are not taking into account enough variation of users.    We need to test content admins as well as single section editors.
We also need to test editing of existing and creation of new.  We need to make sure multiple selections made by content admins do not get wiped out when edited by a single section editor.

2021-07-28 15:26 UTC, ethanteague commented
> 
> The testing steps for this are not taking into account enough variation of users. We need to test content admins as well as single section editors.
> We also need to test editing of existing and creation of new. We need to make sure multiple selections made by content admins do not get wiped out when edited by a single section editor.

Good call, @swirtSJW :+1:

2021-07-28 15:46 UTC, swirtSJW requested changes
See comment above

2021-07-28 15:58 UTC, ethanteague commented
> Disregard... this comment was on the wrong pr.

Lol - I still agreed to it.

2021-07-29 20:26 UTC, swirtSJW requested changes
I can't get past the first QA step.  An admin / content_admin should be able to select multiple systems.
![image](https://user-images.githubusercontent.com/5752113/127561044-d1304bf8-149a-49b0-9a39-42ea07b6abff.png)

2021-07-29 22:05 UTC, swirtSJW reviewed
As Jacob I can not see the other systems the banner appears on 
![image](https://user-images.githubusercontent.com/5752113/127571212-b678eef4-28ca-4b7f-adb9-18a0d6208640.png)
I can see them on node view.... so maybe that is good enough.  Just can't see them on node edit... which removes some valuable UX context.

2021-07-29 22:30 UTC, ethanteague commented
> As Jacob I can not see the other systems the banner appears on
> ![image](https://user-images.githubusercontent.com/5752113/127571212-b678eef4-28ca-4b7f-adb9-18a0d6208640.png)
> I can see them on node view.... so maybe that is good enough. Just can't see them on node edit... which removes some valuable UX context.

Yeah…..I see what you mean. Not sure if maybe we should show them, but make them disabled, or some other treatment. Punting to @kevwalsh to weigh in.

2021-07-30 11:42 UTC, swirtSJW commented
Yah so there are two issues with this that are both minor so @kevwalsh may call them good enough:
1. The issue raised in my QA that items already selected that I  (as an editor) don't have access to, should be visible but not deselectable.
2. The AC is `As a VAMC banner alert creator on /node/add/full_width_banner_alert, i should only see VAMCs that i have access to via workbench access.`    Is not quite implemented.  What is limiting this list is what is selected as the section,  If I were an editor in multiple sections I would not see all I have access to, I would still only see  the section the node is assigned to.

2021-07-30 14:05 UTC, kevwalsh commented
#1 is an extreme edge case. not sure if it's worth additional work right now. we could icebox an issue around it. 

#2 is probably more of an issue. As a VISN editor with access to all the VAMCs in my section, if i set the Section to my VISN, will i still see all the VAMCs listed?

2021-07-30 15:37 UTC, swirtSJW commented
@kevwalsh With the way this PR stands if the section is set to VISN, no choices display.  So we will need to rework this.

2021-07-30 15:56 UTC, ethanteague commented
@kevwalsh @swirtSJW y'all just tell me how to proceed on this - it's an easy one to update / modify.

2021-07-31 01:02 UTC, ethanteague commented
Updated approach to show all items, but set to disabled if UserPermsService returns false for checkbox nid. This will allow for users with different perms to select/deslect items without overriding options for which they do not have access.

2021-08-12 21:06 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +      $perms = $this->userPermsService->userAccess($key, 'node', $this->currentUser, 'field_office');
**Minor:** When reading code, a variable like $key if almost impossible to know what it is.  It is best only used if the key is just a ordinary array key from a flat array (automatically assigned numeric keys).  In all other cases we should try to be meaningful in the naming.   In this case it is especially confusing because  the first argument that `->userAccess() ` takes is an entity id.... which makes me think this should be passing $nid and not $key.   Because this makes me get hung up on the question "Are $key and $nid both containing the same values?  If so why did we bring $key into existence?"

2021-08-12 21:15 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +      $perms = $this->userPermsService->userAccess($key, 'node', $this->currentUser, 'field_office');
Ahh here the confusion gets revealed.   $key is a nid, but $nid is definitely not a nid.
![image](https://user-images.githubusercontent.com/5752113/129270957-a5454aa4-9405-49f8-ac30-6b83c6d05d6d.png)

2021-08-12 21:15 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +      $perms = $this->userPermsService->userAccess($key, 'node', $this->currentUser, 'field_office');
I've got it pulled locally and will fix.

2021-08-12 21:36 UTC, swirtSJW requested changes
QA is not checking out.
On initial edit of Pittsburgh as RyanS it all looks good:
![image](https://user-images.githubusercontent.com/5752113/129273131-3b13eff9-24cb-444c-a997-0cfdb254539f.png)
As Ryan I can alter my system but no-one elses.
Unfortunately, on save, there is data loss as Altoona is no longer selected.
![image](https://user-images.githubusercontent.com/5752113/129273292-92a1f6ea-fd66-4641-a14b-1ffc23d24721.png)

2021-08-12 23:12 UTC, ethanteague commented
> QA is not checking out.
> On initial edit of Pittsburgh as RyanS it all looks good:
> As Ryan I can alter my system but no-one elses.
> Unfortunately, on save, there is data loss as Altoona is no longer selected.

Glad you caught that, @swirtSJW ! So, setting a checkbox to disabled (even if it is already checked), causes it to be submitted as unchecked (TIL).

Updated :+1:

2021-08-13 01:53 UTC, swirtSJW approved these changes
QA pass.   Nice work.

2021-08-13 01:54 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/129293894-ec17f7e7-d1db-4bf5-a7ac-8b073f8afa8a.png)

2021-08-13 01:54 UTC, merged