VACMS-6007: Add banner content type.
department-of-veterans-affairs/va.gov-cms pull request #6013
Opened 2021-08-02 18:16 UTC by ethanteague

## Description
Closes #6007 

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/127905712-682b8730-6e09-4eff-9c59-04ed9676d3a1.png)

## QA steps

As user _uid_ with _user_role_
As a content_admin, go to `admin/structure/types/manage/banner/form-display` an visually verify banner type exists.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-08-02 20:15 UTC, swirtSJW commented
Can we disable all menus? 
![image](https://user-images.githubusercontent.com/5752113/127918366-1f8ec779-4cea-45c8-9855-f0a2bf6f94ac.png)

2021-08-02 20:26 UTC, ethanteague commented
> Can we disable all menus?

Done, @swirtSJW

2021-08-02 20:34 UTC, swirtSJW approved these changes
This looks good to me.  (assuming we are holding on help text until later in the development.  This is just to get the fields out the door so Kelson can play.

2021-08-02 20:49 UTC, swirtSJW commented
@kevwalsh Don't we need a type selector so that a banner can be either informational or a warning?

2021-08-03 02:49 UTC, kevwalsh requested changes
- [ ] Good catch by @swirtSJW ... definitely need field_alert_type, just like block/add/alert 

![Add_Alert_custom_block___VA_gov_CMS](https://user-images.githubusercontent.com/643678/127949728-9e057e5a-494a-41b5-bba1-75a02ab68be8.png)


- [ ] "Rich text limited" only -- can't remember if this is straightforward or not
- [ ]  Hide URL alias (if possible?) and Authoring information fieldsets
- [ ]  Body is required

![Create_Banner___VA_gov_CMS](https://user-images.githubusercontent.com/643678/127949496-cefd0127-84f2-4750-8547-6f7ff88d65aa.png)

2021-08-03 11:41 UTC, ethanteague commented
Updated, @kevwalsh @swirtSJW

2021-08-05 21:23 UTC, swirtSJW requested changes
Just one change

2021-08-05 21:23 UTC, swirtSJW commented on config/sync/field.field.node.banner.field_alert_type.yml
> +    value: warning
Having this field be required and setting a default of 'warning'  seems counter productive.  
![image](https://user-images.githubusercontent.com/5752113/128422788-fee0bdb6-dc98-42ba-8466-282b4fd228c5.png)
It will never not be selected (impossible to unselect).
I think we want people to consciously choose which they want.
An empty prompt ' - Select a value -'should be the default, like it is on VAMC Full width banner alert.

![image](https://user-images.githubusercontent.com/5752113/128422979-29931c3b-ec7f-43d0-8a6a-06106d7881fc.png)

2021-08-06 13:25 UTC, swirtSJW approved these changes

2021-08-06 13:27 UTC, merged