VACMS-5985 alert block governance
department-of-veterans-affairs/va.gov-cms pull request #6045
Opened 2021-08-05 21:26 UTC by ethanteague

## Description
Closes #5985

## Testing done
Visual

## QA steps
 - On paths `block/95` and `block/add/alert`, as a content admin and a content publisher, test the following scenarios:
   - Only content admins can create new alert blocks
   - As non-content-admin, I cannot edit or access the Scope field on any alert block
   - Banner or in-page alert? is a required field and defaults to in-page Alert
   - The Scope field is only visible if "Banner alert" has been selected in field_is_this_a_header_alert_

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-08-09 15:42 UTC, swirtSJW requested changes
A couple odd things  (see comments below)

2021-08-09 15:42 UTC, swirtSJW commented on composer.lock
>  }
I think this should not be included.

2021-08-09 15:42 UTC, swirtSJW commented on phpstan-baseline.neon
> +			path: docroot/modules/custom/disable_node_menu_item/disable_node_menu_item.module
This module is no longer in  our codebase.  Do we really need this ignore?

2021-08-13 11:57 UTC, ethanteague commented
Apologies for sleeping on this one, @swirtSJW - you reviewed this several days ago, and I forgot to circle back.

2021-08-13 14:53 UTC, swirtSJW requested changes
I'm getting a fail on the first step As Lisa (content admin) I do not have access to the 
https://pr6045-hgzahimmyyzt89bvkbxbdftigxnho3vr.ci.cms.va.gov/block/add/alert
![image](https://user-images.githubusercontent.com/5752113/129375750-22ab85ff-9680-4346-8dc9-8b80ff87f892.png)

Can you make the QA steps a little more specific, so I know what you tested already and make it a bit faster for me to test.

2021-08-13 16:30 UTC, ethanteague commented
Updated, @swirtSJW :+1:

2021-08-20 22:06 UTC, swirtSJW requested changes
I got a fail on the scenerio 1. Scope is visible on node add by default.


I am also not really following why `field-is-this-a-header-alert` is required when there are only two options and one is set by default.  It is impossible to unset this field.

2021-08-21 13:16 UTC, ethanteague commented
> I got a fail on the scenerio 1. Scope is visible on node add by default.

Sorry about that, @swirtSJW  - fixed.

> I am also not really following why `field-is-this-a-header-alert` is required when there are only two options and one is set by default. It is impossible to unset this field.

@kevwalsh set this as a requirement in the task: ```Banner or in-page alert? is a required field and defaults to in-page Alert (admin/structure/block/block-content/manage/alert/fields/block_content.alert.field_is_this_a_header_alert_)```

2021-08-30 20:30 UTC, swirtSJW approved these changes
This all passes QA.  Thanks @ethanteague 

This part of the UI should probably also be hidden it is not a banner alert
![image](https://user-images.githubusercontent.com/5752113/131401246-ce664e11-2c14-4ee5-bd41-06d4fb8f6b70.png)

But lets leave it as is for now, since the next iteration will just be to remove all those fields anyway.

2021-08-30 20:30 UTC, swirtSJW commented
THis is ready to go, just waiting on tests to complete.

2021-08-30 21:10 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/131406037-84d61e1e-ba10-4281-b4ed-162207af9082.png)

2021-08-30 21:10 UTC, merged