VACMS-6113: Automatically fix broken links to email addresses.
department-of-veterans-affairs/va.gov-cms pull request #6140
Opened 2021-08-16 20:08 UTC by ndouglas

## Description

Relates to #6113. 

Super simple approach based around `filter_var($string, FILTER_VALIDATE_EMAIL)` and a pretty selective XPath query.

TL;DR: If it looks like a bare email address, stick a `mailto:` in front of it.

```php
$urls = [
    'test@example.org',
    'test%40example.org',
    '/test@example.org',
    '/test%40example.org',
    'mailto:test@example.org',
    'mailto://test@example.org',
    'https://absolute.url/test@example.org',
    'https://absolute.url/test%40example.org',
];

foreach ($urls as $in) {
    $out = filter_var($in, FILTER_VALIDATE_EMAIL);
    $out = $out === FALSE ? 'Not Matched' : $out;
    echo "$in: $out\n"; 
}
```

```
test@example.org: test@example.org
test%40example.org: Not Matched
/test@example.org: /test@example.org
/test%40example.org: Not Matched
mailto:test@example.org: Not Matched
mailto://test@example.org: Not Matched
https://absolute.url/test@example.org: Not Matched
https://absolute.url/test%40example.org: Not Matched
```

I went back in time to check a node from a few days ago that caused issues along these lines, and the emails had been entered correctly (just minus the `mailto:`), so I don't see any need for the `%40` or other extra case capturing at this time.  These are handled fine provided the filter is early enough in the order.  I contemplated using a fancier approach but it doesn't seem necessary (or necessarily a good idea) at this time.

Gonna create a test node here in a minute, when the PR env is live.

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

2021-08-16 21:10 UTC, acrollet commented
> Note that this does check strings that begin with forward slashes. That's valid per the RFC. Does anyone actually have an email address like that? I hope not, but a standard's a standard.

TIL

2021-08-16 21:18 UTC, acrollet commented on docroot/modules/custom/va_gov_backend/src/Plugin/Filter/EmailLinkRepairFilter.php
> +        $element->setAttribute('href', "mailto:$email");
This probably comes from too much time with the airbnb style guide but I kind of like using the curly syntax for variables in strings to highlight when substitution is happening, e.g. `"mailto:{$email}"`

Total preference thing, what do you think?

2021-08-16 21:20 UTC, acrollet requested changes
The code looks great to me, per our shiny new [best practices](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/development-best-practices.md#code-strucutre) doc I'd love to see a test for the `process` method.

2021-08-16 21:28 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/src/Plugin/Filter/EmailLinkRepairFilter.php
> +        $element->setAttribute('href', "mailto:$email");
I don't really care either way.  I think it'd be good to formally institute the rule somewhere if it's not already.

2021-08-16 21:30 UTC, acrollet commented on docroot/modules/custom/va_gov_backend/src/Plugin/Filter/EmailLinkRepairFilter.php
> +        $element->setAttribute('href', "mailto:$email");
yeah, I think it's my pickiness, I don't think there's a real standard in the PHP community. Maybe I'll take a straw poll...

2021-08-16 21:33 UTC, ndouglas commented on docroot/modules/custom/va_gov_backend/src/Plugin/Filter/EmailLinkRepairFilter.php
> +        $element->setAttribute('href', "mailto:$email");
The curly braces haven't really made a big impact on me because they're not as useful (or necessary) as JS' template literals.  I used to mostly just do concatenation with single-quoted strings, but at some point when building URLs I lost patience and started using the double-quoted strings.

2021-08-17 13:15 UTC, indytechcook approved these changes
Awesome work.  I like using the built-in PHP solution.  Fast and secure.  And the test looks great.

I wonder about contributing some of these filters back.  Thoughts for the future?

2021-08-17 14:00 UTC, acrollet approved these changes
Awesome test!

2021-08-17 14:26 UTC, merged

2021-08-17 20:25 UTC, swirtSJW commented
I am late to the praise on this one Nate, but Nice Work!