VACMS-6071 create three new content types
department-of-veterans-affairs/va.gov-cms pull request #6142
Opened 2021-08-17 00:05 UTC by ethanteague

## Description

Relates to #6071
## Testing done
Visual, phpunit, Behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/129643332-2f04e0aa-927e-4a4a-8055-9f568690625c.png)
![image](https://user-images.githubusercontent.com/2404547/129643354-012cf210-5785-40a4-8d08-d68bd310244c.png)
![image](https://user-images.githubusercontent.com/2404547/129643369-189af2e1-7e78-48a7-814c-ce20413eedb1.png)

## QA steps
- As an administrator (or content_admin), create 1 node here: `/node/add/vamc_system_medical_records_offi` & here `/node/add/vamc_system_register_for_care` & here: `/node/add/vamc_system_billing_insurance`
- Prior to save, visually verify the pages match the screenshots above
- After save, visually verify that title is `Register for care` or `Medical records office` or `Billing and insurance`
- Login as ryan.thurlwell@va.gov and confirm that you cannot view any of the three new node add forms
- Visit all three of the new nodes created by admin, and confirm that you can edit and save each of the new nodes.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-08-20 13:46 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__vamc_system_billing_insurance.yml
> +label: 'Content: VAMC System Billing Insurance'
should be "VAMC System Billing and Insurance"

2021-08-20 13:46 UTC, kevwalsh commented on config/sync/node.type.vamc_system_billing_insurance.yml
> +name: 'VAMC System Billing Insurance'
should be "VAMC System Billing and Insurance"

2021-08-20 13:46 UTC, kevwalsh commented on tests/behat/drupal-spec-tool/content_model_bundles.feature
> +| VAMC System Billing Insurance | vamc_system_billing_insurance | Content type |  |
should be "VAMC System Billing and Insurance"

2021-08-20 13:46 UTC, kevwalsh commented on config/sync/metatag.metatag_defaults.node__vamc_system_billing_insurance.yml
> +label: 'Content: VAMC System Billing Insurance'
should be "VAMC System Billing and Insurance"

2021-08-20 13:48 UTC, kevwalsh requested changes
- [ ] "Billing and insurance" should have the "and" everywhere except the machine name, where it doesn't fit.  
- [ ] Section should always appear first, and in these cases above Menu settings. i think the only way to do this is to set the section fieldset's weight manually. 

![Create_VAMC_System_Billing_Insurance___VA_gov_CMS_and_VACMS-6071_create_three_new_content_types_by_ethanteague_·_Pull_Request__6142_·_department-of-veterans-affairs_va_gov-cms](https://user-images.githubusercontent.com/643678/130243127-05e5655b-f773-41c9-961c-55d3ad5711b3.png)

2021-08-20 15:09 UTC, ethanteague commented
Updated, @kevwalsh :+1:

2021-08-20 17:03 UTC, swirtSJW commented
Can we get the system to be sorted by name?
![2021-08-20_12-59](https://user-images.githubusercontent.com/5752113/130268640-a4e7761b-b2f8-4500-8f40-9e08b77c4861.png)

2021-08-20 17:28 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/130271253-f293058d-e84f-4248-897b-cf9ca6c00f7a.png)
I don't think this is what we want.   This would treat unique on the combination of the two.  I think we want two allow only ones,  one on section, one on system.

2021-08-20 17:55 UTC, ethanteague commented
> ![image](https://user-images.githubusercontent.com/5752113/130271253-f293058d-e84f-4248-897b-cf9ca6c00f7a.png)
> I don't think this is what we want. This would treat unique on the combination of the two. I think we want two allow only ones, one on section, one on system.



> Can we get the system to be sorted by name?
> ![2021-08-20_12-59](https://user-images.githubusercontent.com/5752113/130268640-a4e7761b-b2f8-4500-8f40-9e08b77c4861.png)

I think this would require creating a new view entity reference view display (the field / form settings don't have any sorting options / magic available). Happy to do it, but will mean adding config, and will result in having other instances of this field having different config until we update to use the new view reference.

Just tell me how you all want me to proceed @kevwalsh @swirtSJW

2021-08-20 18:05 UTC, kevwalsh commented
You can sort the select list with a setting in the field (not on the form widget). It's confusing because it doesn't say "Title". you can see how this is done in some of the other field_office select list settings. 

and yes, only one of each content type per section. and only one of each content type per field_office

2021-08-20 19:21 UTC, ethanteague commented
Updated, @swirtSJW

2021-08-23 18:55 UTC, swirtSJW commented on config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
> -    - 'https://www.erie.va.gov/locations/facilities.asp'
I don't think this belongs here.

2021-08-23 18:56 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
> -    - https://www.erie.va.gov/locations/facilities.asp
Does not belong here.

2021-08-23 19:16 UTC, ethanteague commented
updated, @swirtSJW :+1:

2021-08-23 20:26 UTC, swirtSJW approved these changes
There is an issue where the node title is automatically set, but it is not auto setting the menu title but I will create a separate issue for this to move this one along.

2021-08-24 15:03 UTC, merged