VACMS-6148: Prevent non admins from altering path fields.
department-of-veterans-affairs/va.gov-cms pull request #6166
Opened 2021-08-18 17:21 UTC by ethanteague

## Description

Relates to #6148

## Testing done
Visual / behat

## QA steps

**Scenario 1**
- [ ] As an administrator, go to `node/33317/edit` and visually verify that `Paths` are editable - make a change, confirm save preserves change.

**Scenario 2**
- [ ] As an administrator, go to `node/add/banner` and visually verify that `Paths` are editable - complete the form, confirm save preserves additions to paths field.

**Scenario 3**
- [ ] As an administrator, go to `block/add/alert` and visually verify that `Scope` is editable - complete the form, confirm save preserves addition to scope field.

**Scenario 4**
- [ ] As an administrator, go to `block/101` and visually verify that `Scope` is editable - complete the form, confirm save preserves addition to scope field.

**Scenario 5**
- [ ] As a non content_admin/administrator, go to `node/33317/edit` and visually verify that `Paths` is not editable - make a change to the node, confirm save does not lose `Paths` data.

**Scenario 6**
- [ ] As a non content_admin/administrator, go to `node/add/banner` and visually verify that `Paths` is not editable - complete the form, confirm save works.

**Scenario 7**
- [ ] As a non content_admin/administrator, go to `block/add/alert` and visually verify that `Scope` is not editable - complete the form, confirm save works.

**Scenario 8**
- [ ] As a non content_admin/administrator, go to `block/101` and visually verify that `Scope` is not editable - complete the form, confirm save does not lose scope field data.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-08-19 03:01 UTC, swirtSJW requested changes
see comments.

2021-08-19 03:01 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> -   * Add js script and disallowed nids to Banner node form.
I don't think this is in the right spot.   The banner content type is not a vamc product.  It is a global product.  Banner content type is not a replacement for the full width banner alert.  It is a replacement for the block alert that is using the full width option.

2021-08-19 11:53 UTC, ethanteague commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    if (!in_array('content_admin', $roles) && !in_array('administrator', $roles)) {
Dangit - that's what threw me off. I was thinking we had a `isAdmin` method in our User perms service, but didn't see it. Forgot that we called it `hasAdminRole` - will swap.

2021-08-20 12:43 UTC, swirtSJW commented on docroot/modules/custom/va_gov_global/va_gov_vamc.module
> +<?php
This file is in the wrong spot.  I think it was copy-pasta.

In general though I am concerned with the creation of va_gov_global because there is nothing to differentiate it from va_gov_backend.   They are both destined to be junk drawers due to their generic naming and having two junk drawers to look through is worse than one.  

We are going to have some additional custom code around banners so it makes sense to create a va_gov_banner rather than another generic module.

2021-08-20 12:44 UTC, swirtSJW requested changes
See comment about new module name.

2021-08-20 17:55 UTC, swirtSJW requested changes
Some suggestions and questions.  See below.

2021-08-20 17:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php
> +  }
Are we making these two methods that do the exact same thing right now because we're expecting to make them differ in the future?

2021-08-20 17:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_banner/va_gov_banner.module
> +      $output .= '<p>' . t('Custom code used for multiple product types') . '</p>';
Seems inaccurate.

2021-08-20 17:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_banner/va_gov_banner.info.yml
> +description: 'Custom code used for banners'
```suggestion
description: 'Custom code used for banner node bundle.'
```

2021-08-20 17:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow_assignments/src/EventSubscriber/EntityEventSubscriber.php
> +    if (!in_array('content_admin', $roles) && !in_array('administrator', $roles)) {
Why aren't we using the userPerms service here?

2021-08-20 17:55 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow_assignments/src/EventSubscriber/EntityEventSubscriber.php
> +    if (!in_array('content_admin', $roles) && !in_array('administrator', $roles)) {
Good spot for the userPerms service?

2021-08-20 19:28 UTC, ethanteague commented on docroot/modules/custom/va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php
> +  }
Yeah, but now that I'm looking back at it, this seems silly - we can add another method if edit form differs from the add form, in the future (it may never happen).

2021-08-20 19:33 UTC, ethanteague commented
Updated, @swirtSJW

2021-08-30 18:34 UTC, swirtSJW commented
Conflicted :(

2021-08-30 20:14 UTC, ethanteague commented
> Conflicted :(

We all are, @swirtSJW . We all are.
Conflict fixed :+1:

2021-08-30 21:17 UTC, swirtSJW commented
Sorry, even more conflicted now.

2021-08-30 21:29 UTC, ethanteague commented
> Sorry, even more conflicted now.

:+1: updated, @swirtSJW

2021-08-30 21:47 UTC, swirtSJW commented
@ethanteague  I think your conflict resolution broke you previous work on alert blocks.
![image](https://user-images.githubusercontent.com/5752113/131410065-2e9f6478-eef4-4fe9-b168-9883e990e28a.png)

If `in-page alert` is selected, the scope fields aren't supposed to show.

2021-08-30 22:48 UTC, ethanteague commented
> @ethanteague I think your conflict resolution broke your previous work on alert blocks.
> ![image](https://user-images.githubusercontent.com/5752113/131410065-2e9f6478-eef4-4fe9-b168-9883e990e28a.png)
> 
> If `in-page alert` is selected, the scope fields aren't supposed to show.

D'oh!
Thank you for catching that, @swirtSJW !
Added it back in.

2021-08-31 18:58 UTC, swirtSJW approved these changes

2021-08-31 18:59 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/131560495-fb2e2507-9434-4ae1-8c8b-f5fb8a8dc477.png)

2021-08-31 18:59 UTC, merged