VACMS-6213: Add logic to handle top task pages.
department-of-veterans-affairs/va.gov-cms pull request #6308
Opened 2021-08-31 22:33 UTC by ethanteague

## Description
Relates to #6213

## Testing done
Visual / behat

## QA steps
 - [ ] As an administrator, go to `/node/add/vamc_system_billing_insurance` and visually verify the title field is visible, but disabled, and the Menu title is prepopulated with the form title value
 - [ ] As an administrator, go to `/node/add/vamc_system_medical_records_offi` and visually verify the title field is visible, but disabled, and the Menu title is prepopulated with the form title value
- [ ] As an administrator, go to `/node/add/vamc_system_register_for_care` and visually verify the title field is visible, but disabled, and the Menu title is prepopulated with the form title value

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-09-02 14:28 UTC, swirtSJW requested changes
I  think we missed AC #2010 
![image](https://user-images.githubusercontent.com/5752113/131861705-cd5757be-75ca-4c6a-9179-60cfc7bff7a7.png)
I can see the confusion though as I mis-described the menu title field as the title field.  I am sorry about that.   Both the title field AND the menu title field should not be editable by editors.

2021-09-02 14:28 UTC, swirtSJW commented on docroot/modules/custom/va_gov_root_pages/src/EventSubscriber/EntityEventSubscriber.php
> +      'hook_event_dispatcher.form_node_vamc_system_billing_insurance_edit_form.alter' => 'alterTopTaskNodeForm',
This same logic needs to be performed on the vamc_system_policies_page which is also a top task page.  I thought we were already doing it on that page but when I just checked, we are not... unless we had a regression.

2021-09-02 14:28 UTC, swirtSJW commented on config/sync/core.extension.yml
> +  va_gov_root_pages: 0
I'm not a fan of spinning this into a new module with a name that does not have any reference to any product name.  I could have been sold on top_task_pages, but these are pretty specific to VAMCs so I would rather all this live inside va_gov_vamc.

2021-09-02 20:47 UTC, ethanteague commented
> I think we missed AC #2010
> I can see the confusion though as I mis-described the menu title field as the title field. I am sorry about that. Both the title field AND the menu title field should not be editable by editors.

Updated, @swirtSJW :+1:

2021-09-09 21:58 UTC, swirtSJW approved these changes
Approved.   This is working for the three new page types but is not quite working for vamc_system_policies_page  .

2021-09-09 21:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +      'hook_event_dispatcher.form_node_vamc_system_policies_page_form.alter' => 'alterTopTaskNodeForm',
This is adding it for vamc_system_policies_page but it is not functioning there because the title is not showing.   I'll create another ticket for that.

2021-09-09 21:59 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/132768236-1ecb2a4b-d714-42ce-b5e1-602a253bc56e.png)

2021-09-09 21:59 UTC, merged