VACMS-6015: Add path validation constraint.
department-of-veterans-affairs/va.gov-cms pull request #6316
Opened 2021-09-01 16:41 UTC by ethanteague

## Description
Relates to #6015

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/131710046-096e712d-4c24-44d7-97fc-c94e45553f98.png)

## QA steps
 - [ ] As an administrator, go to `node/33217/edit` remove the `/` from the first path field, and save as draft.
 - [ ] Edit this page again, setting status to published, and save.
 - [ ] Visually verify form error identical to screenshot.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-09-09 22:17 UTC, swirtSJW requested changes
This works pretty well.   We have two issues
If there is an error.  The jump lik does not work
![image](https://user-images.githubusercontent.com/5752113/132769814-54a74bea-c044-466d-8591-cb85e5f77bff.png)

If I remove a path after published and try to publish.  I get a proper validation, but a bunch of warnings and notices too.
![image](https://user-images.githubusercontent.com/5752113/132769761-a2ebead2-8cb0-43f6-84b4-b0580d77bf67.png)

2021-09-10 11:04 UTC, swirtSJW commented
I have a feeling this validation is going to play badly with the code that hides the path fields for non-content admins.

2021-09-10 11:56 UTC, ethanteague commented
> I have a feeling this validation is going to play badly with the code that hides the path fields for non-content admins.

Good thinking, @swirtSJW - I'll add some of kind of role checking to the constraint.

2021-09-14 17:22 UTC, ethanteague commented
I'm stumped on this one, @swirtSJW - not finding anything about working with deltas in constraints. Closest thing I stumbled upon is this: https://philfrilling.com/blog/2018-09/custom-validation-multiple-dependent-entity-fields-drupal-8 , specifically, using the `atPath` method, but it doesn't seem to have any effect on the delta (or field for that matter).

2021-09-15 17:21 UTC, ndouglas approved these changes
<img width="395" alt="Screen Shot 2021-09-15 at 1 20 46 PM" src="https://user-images.githubusercontent.com/1318579/133479990-098457de-681f-4d7d-9564-ebb67859a2cb.png">
Yup, think it does what you want and doesn't do what you don't want.

2021-09-16 21:09 UTC, swirtSJW requested changes
I don't think we can use JS validation because for the editors we are trying to prevent from publishing these, the path fields are hidden, so there is nothing to check.   

Example:  AS an admin I created a banner with no path and assigned it to Josh T,   then logged in as Josh T and was not prevented from publishing.   HTML5 validation does not apply to fields that are not present.

![image](https://user-images.githubusercontent.com/5752113/133685970-70461749-49e6-4890-b37e-b13d78901ddb.png)

2021-09-16 21:19 UTC, swirtSJW commented
I just update the QA steps to more completely test our use case where one person will be creating the banner and the other will be setting the content and publishing when ready / as needed.

2021-09-16 21:21 UTC, swirtSJW commented
I also noticed that if there is at least one space in the path field, it allows save.  I think we want to prevent that, since it would give the front end a banner that could not be placed with any certainty.

2021-09-17 17:08 UTC, ethanteague commented
@swirtSJW @kevwalsh pr updated:
   - Adds custom constraint.
   - Adds core patch to address missing parent messages.
   - Adds custom js to fix form error jump link.
   - Adds logic to require revision log message on form edit

2021-09-17 20:56 UTC, swirtSJW requested changes

2021-09-17 20:56 UTC, swirtSJW commented on docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScope.php
> +  public $noPaths = 'Please add at least one path before you publish this banner.';
I think we want two messages here.  Crude examples:.  
$nopaths_admin =  'Please add at least one path before you publish this banner.';
$nopaths_non_admin =  'No paths have been set for this banner, please contact an administrator to define where this banner should appear.';

2021-09-17 20:56 UTC, swirtSJW commented on docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScopeValidator.php
> +    if (empty($item->getEntity()->get('field_target_paths')->getString())) {
I think (unless this is what you an Nate already tried) you need to loop through the values and then  set the delta on the ->path( like in the examples here  https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21Plugin%21Validation%21Constraint%21ValidReferenceConstraintValidator.php/function/ValidReferenceConstraintValidator%3A%3Avalidate/8.2.x

I am pretty sure (again unless this didn't solve it) that this will make the javascipt link fix unnecesary.  And maybe make that patch unnecessary too.

2021-09-17 20:56 UTC, swirtSJW commented on docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScopeValidator.php
> +      $this->context->addViolation($constraint->noPaths);
Use dependency injection to load your perms service and then check hasAdmin() to decide which error text to throw.

example of DI on validator 
https://git.drupalcode.org/project/drupal/-/commit/5f7ec33

2021-09-17 20:56 UTC, swirtSJW commented on docroot/modules/custom/va_gov_banner/va_gov_banner.libraries.yml
> +fix_constraint_jump_link:
Might not be needed if the setting the validator path works

2021-09-17 21:35 UTC, ethanteague commented on docroot/modules/custom/va_gov_banner/js/fixConstraintJumpLink.es6.js
> +              ".region-highlighted .messages--error ul.item-list__comma-list li a"
I can tighten this up

2021-09-17 21:36 UTC, ethanteague commented on docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScope.php
> +  public $noPaths = 'Please add at least one path before you publish this banner.';
Sorry....confused with all the swirl around this task. The way I have it at present, non admins don't see this field, and they can't publish banners. So, if we are continuing on this path, only one message should be necessary.

2021-09-17 21:37 UTC, ethanteague commented on docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScopeValidator.php
> +    if (empty($item->getEntity()->get('field_target_paths')->getString())) {
We tried this, but it didn't work.

2021-09-17 21:37 UTC, ethanteague commented on docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScopeValidator.php
> +      $this->context->addViolation($constraint->noPaths);
I don't think we need to worry about non-admins.

2021-09-17 21:38 UTC, ethanteague commented on docroot/modules/custom/va_gov_banner/va_gov_banner.libraries.yml
> +fix_constraint_jump_link:
Think we are going to need it.

2021-09-20 14:35 UTC, ethanteague commented on docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScope.php
> +  public $noPaths = 'Please add at least one path before you publish this banner.';
Passing the user perms service via an argument in services file to the __construct in my validator just wasn't working (kept getting the 0 arguments passed error). Had to pass it in with __create.

2021-09-22 15:32 UTC, swirtSJW commented
Dave C agreed on call today that disabling the field was good enough for now, to avoid lots of technical debt in overriding how field validation works.

2021-09-23 02:34 UTC, swirtSJW requested changes
I think this is very close.  Just one suggestion to close up that one QA step.

2021-09-23 02:34 UTC, swirtSJW commented on docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScopeValidator.php
> +    if (empty($item->getEntity()->get('field_target_paths')->getString())) {
This QA step is failing.
>> add a single space in the path field
save the node as published
 Validate that the node does NOT save and you are told why.


```suggestion
    $path = trim($item->getEntity()->get('field_target_paths')->getString());
    if (empty($path)) {
```

2021-09-23 11:32 UTC, ethanteague commented
> I think this is very close. Just one suggestion to close up that one QA step.

Sorry I missed that, @swirtSJW - I just merged your suggestion :+1:

2021-09-23 14:30 UTC, swirtSJW approved these changes
QA pass.   Nice work Ethan.

2021-09-23 14:31 UTC, merged