VACMS-6448: Add new name field to vc.
department-of-veterans-affairs/va.gov-cms pull request #6459
Opened 2021-09-16 19:34 UTC by ethanteague

## Description
Relates to #6448

## Testing done
Behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/133674339-11f2bf27-02ba-462d-80bd-6d3777d3006b.png)
![image](https://user-images.githubusercontent.com/2404547/133674395-94f6c31c-0bd2-4427-b483-0230d7e1e16b.png)

## QA steps
- [ ] As an administrator, go to `/admin/structure/types/manage/vet_center/display` & `/admin/structure/types/manage/vet_center/form-display` and visually verify placement of Official name field matches the screenshots above.

2021-09-16 21:39 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> -        - revision_log
The test caught Klinger making a run for it.

2021-09-16 21:43 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> +      allow_system_delete: false
Any idea what this is?  I don't see how it relates not is it anywhere in any of our other config files.

2021-09-16 21:45 UTC, swirtSJW requested changes
One Awol, one stowaway  ;)

2021-09-16 22:30 UTC, ethanteague commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> -        - revision_log
Great reference!

2021-09-17 11:55 UTC, ethanteague commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> +      allow_system_delete: false
This prevents inline entities from being deleted from the system, as opposed to just being removed from the form. I didn't intentionally add, but I think it would be good to leave it in, @swirtSJW

2021-09-17 11:57 UTC, ethanteague commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> -        - revision_log
Fixed

2021-09-17 11:59 UTC, ethanteague commented
> One Awol, one stowaway ;)

Plugged that revision_log back in (thanks for catching it!), but I think it wouldn't be a bad idea to leave in the allow_system_delete setting to prevent ief entities from being deleted from the system, @swirtSJW

2021-09-17 14:28 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vet_center.default.yml
> +      allow_system_delete: false
Thanks.  Makes sense.

2021-09-17 14:55 UTC, swirtSJW approved these changes
Added a couple of QA steps and they all check out.   Nice work.

2021-09-17 14:55 UTC, merged