VACMS-5248: Add logic to prevent non admin archive from node form.
department-of-veterans-affairs/va.gov-cms pull request #6483
Opened 2021-09-20 23:17 UTC by ethanteague

## Description
Relates to #5248

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

2021-09-21 19:05 UTC, swirtSJW requested changes
This is looking good.
Some suggestions (see below)

2021-09-21 19:05 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php
> +   *   Returns true is present false if not.
More descriptive.  This should tell what true represents in relation to the method... not to the inner workings of the method.  
When you do this, you will realize that this method currently does the opposite of what it says it does.  (the opposite of what it is supposed to do.)

2021-09-21 19:12 UTC, ethanteague commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +      $is_archiveable = !in_array($bundle, $this->workflowContentControl->getTargetBundleTypes());
D'oh! I meant to use it, @swirtSJW - walked away from my machine and forgot I made this method.

2021-09-21 20:02 UTC, ethanteague commented on docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php
> +  public function getTargetBundleTypes() {
Makes sense, @swirtSJW :+1:

2021-09-21 20:13 UTC, ethanteague commented on docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php
> +   *   Returns true is present false if not.
![image](https://user-images.githubusercontent.com/2404547/134240879-05754d72-0c9b-45e2-94ab-f3a5d8ce2a52.png)

2021-09-21 21:39 UTC, swirtSJW reviewed
Double checking on the discussion we had earlier about already archived state and how there should be nothing to do.  Maybe I misunderstood?

2021-09-21 21:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php
> +      'full_width_banner_alert',
```suggestion
```
This content type does not use moderation state so can not be archived or otherwise.

2021-09-21 21:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +      $is_archived = $node->get('moderation_state')->getString() === 'archived' ? TRUE : FALSE;
```suggestion
```

Double checking: This you said was not necessary, right?  Because workbench moderation itself does not present it as an option if the status is archived.

2021-09-21 21:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +      if (!$is_admin && !$is_archiveable && !$is_archived) {
```suggestion
      if (!$is_admin && !$is_archiveable) {
```

2021-09-22 16:45 UTC, swirtSJW approved these changes
Tests out great @ethanteague.   Thanks for seeing this through the craziness.

2021-09-22 16:46 UTC, merged