VACMS-6363: Add bio fields toggle.
department-of-veterans-affairs/va.gov-cms pull request #6503
Opened 2021-09-22 14:42 UTC by ethanteague

## Description
Relates to #6363 

## Testing done
Visual / Behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/134365302-cd6047e7-52c0-4f1b-8899-4bbb1e47cace.png)

## QA steps
 - [ ] As an administrator, go to `/node/35031/edit` and visually verify that the `Create profile page with biography` boolean appears in the bio fieldset, and checking it on/off toggles the bio fieldset fields.

2021-09-22 15:38 UTC, kevwalsh requested changes
The unhidden fields should be required  (AC buried in a comment, sorry)

2021-09-23 20:29 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +  /**
I don't think we want this in va_gov_vamc because person_profiles are not just a VAMC thing.  Any product can use them.

2021-09-23 20:41 UTC, ethanteague commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +  /**
Makes sense. Where do you think it should live, @swirtSJW ?

2021-09-24 01:47 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +  /**
va_gov_backend is our more generic / multi product module.

2021-09-24 02:06 UTC, ethanteague commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +  /**
Agreed, but I was thinking we were wanting to avoid putting much more into it. I guess it's alright since most of the bloat is in the .module file, and we are moving away from the old hook system and using event dispatcher hooks.

2021-09-24 04:28 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +  /**
It where it belongs.... so it is not like we are just walling that module off and not using it anymore.  We just want to be careful to check to see if there is a more appropriate spot.... which in this case there is not.

I dealy over time we will want to look at what is in that module that is specific to other products and move it out of there.

2021-09-24 10:49 UTC, ethanteague commented
Updated, @kevwalsh @swirtSJW

2021-09-24 15:39 UTC, kevwalsh requested changes
@ethanteague @swirtSJW didn't think about this earlier, and this may blow the estimate out, but i think we need to do some database updates before this gets merged. Thinking about this as a new AC

- [ ] Existing staff profiles that have content in both  `field_body ` and `field_intro_text` have their  `field_complete_biography_create` populated as TRUE

2021-09-24 15:56 UTC, ethanteague commented
> @ethanteague @swirtSJW didn't think about this earlier, and this may blow the estimate out, but i think we need to do some database updates before this gets merged. Thinking about this as a new AC
> 
> * [ ]  Existing staff profiles that have content in both  `field_body ` and `field_intro_text` have their  `field_complete_biography_create` populated as TRUE

Good thinking, @kevwalsh - I'll work on this.

2021-09-24 21:22 UTC, swirtSJW commented
@kevwalsh  and @ethanteague  Hmmm I was thinking the update script was not needed, because this is a UI thing only.    BUT to make this truthful with the front end, we need the front end to actually use the value of this checkbox to decide not just the presence of the fields values the way it is now.

Otherwise, someone can fill out the fields but then uncheck the box and be confused that the bio page is still created.

2021-09-24 21:35 UTC, ethanteague commented
> @kevwalsh and @ethanteague Hmmm I was thinking the update script was not needed, because this is a UI thing only. BUT to make this truthful with the front end, we need the front end to actually use the value of this checkbox to decide not just the presence of the fields values the way it is now.
> 
> Otherwise, someone can fill out the fields but then uncheck the box and be confused that the bio page is still created.

Oh......I was thinking @kevwalsh 's concern was about the content entry experience on the node form, @swirtSJW . If an editor goes to update a staff profile, and there is content in the bio fields, they won't be aware of it.....granted, there aren't any other fields where they could enter bio type text (just some name / contact type fields).

Y'all just lemme know how you want me to proceed.

2021-09-28 17:28 UTC, ethanteague commented
Update script added to this pr.

2021-09-29 15:23 UTC, swirtSJW requested changes
One minor change

2021-09-29 15:23 UTC, swirtSJW commented on scripts/content/VACMS-6363-set-bio-booleans-that-have-content.php
> +Drupal::logger('va_gov_db')->log(LogLevel::INFO, 'Turned bio display boolean on for %count nodes in va_gov_db_update_8033.', [
Logger not speaking truth.
```suggestion
Drupal::logger('va_gov_db')->log(LogLevel::INFO, 'Turned bio display boolean on for %count nodes via set-bio-booleans script.', [
```

2021-09-29 21:43 UTC, swirtSJW commented on scripts/content/VACMS-6363-set-bio-booleans-that-have-content.php
> +    $node->setOwnerId(1317);
I know you got this from a previously used pattern but I think we are making a mistake setting the owner.
It makes it looks like cms migrator was the original author.

![image](https://user-images.githubusercontent.com/5752113/135352777-ac1068f9-f558-40d4-b011-61147bb25aa8.png)

2021-09-29 21:57 UTC, swirtSJW commented on scripts/content/VACMS-6363-set-bio-booleans-that-have-content.php
> +    $node->setOwnerId(1317);
I validated that  the display in that screen cap is indeed showing the owner (original author) not just the last person to save the revision.

2021-09-29 22:04 UTC, swirtSJW commented on scripts/content/VACMS-6363-set-bio-booleans-that-have-content.php
> +    $node->setOwnerId(1317);
I updated the testing steps for checking the script run. and the bit about the author.

2021-09-30 14:42 UTC, ethanteague commented on scripts/content/VACMS-6363-set-bio-booleans-that-have-content.php
> +    $node->setOwnerId(1317);
Thanks @swirtSJW :+1: - updated.

2021-10-01 14:19 UTC, swirtSJW approved these changes

2021-10-01 14:20 UTC, merged

2021-10-01 14:25 UTC, swirtSJW commented
We'll need these deploy steps run after it deploys today
- [ ] on prod, run `drush scr ./scripts/content/VACMS-6363-set-bio-booleans-that-have-content.php`
- [ ] Copy and paste terminal output in a comment on this PR.

2021-10-01 20:34 UTC, ndouglas commented
```bash
[cms@ip-10-247-33-17 cms]$ drush scr ./scripts/content/VACMS-6363-set-bio-booleans-that-have-content.php
Turned bio display boolean on in '714' nodes.[cms@ip-10-247-33-17 cms]$ 
```

2021-10-01 20:54 UTC, ethanteague commented
> ```bash
> 
> [cms@ip-10-247-33-17 cms]$ drush scr ./scripts/content/VACMS-6363-set-bio-booleans-that-have-content.php
> 
> Turned bio display boolean on in '714' nodes.[cms@ip-10-247-33-17 cms]$ 
> 
> ```

Thanks buddy!