VACMS-6602: Set login time from last to time.
department-of-veterans-affairs/va.gov-cms pull request #6610
Opened 2021-10-02 00:40 UTC by ethanteague

## Description
Relates to #6602

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/135698048-ae867b42-87f8-40ff-a5f7-1e25df18b8a0.png)

## QA steps
 - [ ] As an administrator, go to `admin/people` and visually verify last column reads `LAST ACCESS (USA NYC TIME)`
 - [ ] Visually verify last column login times are in `30-Sep-21 7:37pm` format
 - [ ] Download csv from link at bottom of page, and visually verify time format for last login is `30-Sep-21 7:37pm`

2021-10-04 22:29 UTC, swirtSJW requested changes
We should take out the reference to the time zone on the header.

2021-10-04 22:29 UTC, swirtSJW commented on config/sync/views.view.user_admin_people.yml
> +          label: 'Last access (USA NYC time)'
Are we sure of it being for NY?  Doesn't it use the users local time?

2021-10-04 22:29 UTC, swirtSJW commented on config/sync/views.view.user_admin_people.yml
> +          label: 'Last access (USA NYC time)'
Confirmed.  It does NOT use NY.   It uses time relative to logged in user viewing the View
![image](https://user-images.githubusercontent.com/5752113/135933192-e521709d-a207-47c2-be42-56d57b34f106.png)

Pacific time on the left, NY time on the right.

2021-10-05 12:23 UTC, kevwalsh requested changes
This is great and has unblocked some of the user audit work. 

A few changes i'd like to request

- [x]  Revert to "time ago" dates for Last Access on the /admin/people page 
- [x]  In the CSV output
  - [x] switch to non-relative dates for both the Member Since AND the Last Access fields
  - [ ] Use the date format "October 5, 2021, 5:21pm ET" on the CSV
- [ ] What Steve said (revert to the old column field labels, in both the CSV and the view screen)
- [ ] Stretch: on the CSV output: add a new column with an "Edit link" column label, and output a raw link, eg, https://prod.cms.va.gov/user/UID/edit

2021-10-05 17:30 UTC, ethanteague commented
Updated @swirtSJW @kevwalsh :+1:

2021-10-05 20:34 UTC, kevwalsh approved these changes
Looks good to me. Sent to Chris and Stef and Jane for review.

2021-10-05 21:17 UTC, swirtSJW approved these changes
Looks great.  Thanks Ethan.
![image](https://user-images.githubusercontent.com/5752113/136103867-577c4198-7ef2-4a11-89bb-89e486d548aa.png)


![image](https://user-images.githubusercontent.com/5752113/136103892-e20c3368-945b-4e24-a16a-87e4c159b560.png)

2021-10-05 21:23 UTC, merged