VACMS-6454: remove title from vet center migration - copy from field_official_name
department-of-veterans-affairs/va.gov-cms pull request #6706
Opened 2021-10-15 18:54 UTC by JayDarnell

## Description

closes #6454 

## Testing done

Visual testing

## Screenshots

Checked the content page `/admin/content` and filtered by Content type = Vet Center to see how many items there are:

<img width="1606" alt="Screen Shot 2021-10-15 at 1 50 00 PM" src="https://user-images.githubusercontent.com/21045418/137531184-2ab77115-5221-42be-b15c-459c45af0248.png">

From the terminal I then ran `lando drush mr va_node_facility_vet_centers` to wipe the migration map table

Next I ran the migration fresh with `lando drush migrate:import va_node_facility_vet_centers --update`

I then checked the content page `/admin/content` and filtered by Content type = Vet Center again to see the item count. Because the migration map table was wiped out we now have duplicates to test. I then searched for a specific Vet Center to be sure there were two copies and that the new one has a title:

<img width="1626" alt="Screen Shot 2021-10-15 at 1 58 34 PM" src="https://user-images.githubusercontent.com/21045418/137532161-352c6b01-073f-4cd9-9fdd-e090cb29201e.png">

I then edited the new item's title and ran the migration again. To edit the title you need to make the field visible (It is labeled: Name of Facility) here: `/admin/structure/types/manage/vet_center/form-display`. You will also need to comment out the va_gov_consumers_form_alter function on line 14 of `docroot/modules/custom/va_gov_consumers/va_gov_consumers.module`. Once the migration finishes running I checked the edited Vet Center to make sure the page title change I just made wasn't reverted.

<img width="1611" alt="Screen Shot 2021-10-15 at 2 41 59 PM" src="https://user-images.githubusercontent.com/21045418/137537477-ef604f9c-eb61-41fa-b141-2578761ecba4.png">

## QA steps

As an admin user
1. [x] Check the content page `/admin/content` and filter by Content type = Vet Center to see how many items there are
2. [x] From the terminal run `lando drush mr va_node_facility_vet_centers` to wipe the migration map table
3. [x] From the terminal run `lando drush migrate:import va_node_facility_vet_centers --update`
4. [x] Visit `/admin/structure/types/manage/vet_center/form-display` and set the **Name of Facility** field to visible
5. [x] In your IDE comment out the va_gov_consumers_form_alter() function in va_gov_consumers.module
6. [x] Check the content page `/admin/content` and search for a specific Vet Center (you should see two entries)
7. [x] Edit the most recently migrated copy and change the **Name of Facility** (note the new name)
8. [x] From the terminal run `lando drush migrate:import va_node_facility_vet_centers --update` again
9. [x] Refresh the `/admin/content` page and filter by the new name you created in step 7

If the new name you created was not overwritten by the migration running again then you're good to go.

2021-10-15 21:58 UTC, swirtSJW requested changes
Thanks Jay.  I left some suggestions.  Let me know if you have any questions.

2021-10-15 21:58 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
> +  field_nearby_vet_centers: true
These were carryovers from a config change yesterday.  They are out of place, but fine and expected.

2021-10-15 21:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
> +    _va_gov_migrate_process_va_form($entity);
_va_gov_migrate_process_va_form() is self checking (it has the bundle check in the function)  so there is no need for this to be wrapped in the bundle check.

2021-10-15 21:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
> -  if ($entity->bundle() !== 'va_form') {
Lets keep this here so the function remains self checking.  It is the only thing that has to know what it is operating on.   That way no external safety checks are needed before anyone calls it.

2021-10-15 21:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
> +  elseif ($entity->bundle() == 'vet_center') {
Lets move this check to inside (_va_gov_migrate_process_vet_center)   so it is self checking.

The self checking pattern has a couple benefits:
1. It keeps our hooks easy to read because there is not a lot of gatekeeper logic to read through.
2. It reduces the risk of someone calling the function to act on something it was not intended to act on.  If someone calls it inappropriately, no harm done.

2021-10-15 21:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
> +  else {
Even with the gatekeeper logic, I don't think we need this else.  hook_entity_presave does not have a return

2021-10-15 21:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
> +function _va_gov_migrate_process_vet_center(EntityInterface &$entity) {
On the va_form example you were copying, the word "process" was generic enough to cover all that was going on.  In this case this function is only doing one thing so it is better to make it speak its own truth. Something like `_va_gov_migrate_set_default_vet_center_title` speaks the truth and as a result is a lot more readable and understandable (clean)

In general your spidey sense should tingle whenever you are using generic verbs or nouns in your code.   Sometimes it is unavoidable but usually when it is used, it is a sure sign the "generic function" has too broad a "concern" and  should be split into smaller functions.

2021-10-15 21:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
> +    $entity->setTitle($entity->get('field_official_name')->value);
```suggestion
    $default_title = $entity->get('field_official_name')->value ?: '- none -';
    $entity->setTitle($default_title);
```

Just in case for some reason the migration brings in nothing for the official name.  It should not happen.... but I have learned to not trust the facility API... it sometimes goes wonky.  This at least protects against ending up with a titleless node.

2021-10-20 16:58 UTC, swirtSJW commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
> -  if ($entity->bundle() !== 'va_form') {
Looks like this check still needs to be put back Jay.

2021-10-20 17:26 UTC, JayDarnell commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
> -  if ($entity->bundle() !== 'va_form') {
Strange, I thought for sure I had updated this. I'll check again.

2021-10-20 17:31 UTC, JayDarnell commented on docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
> -  if ($entity->bundle() !== 'va_form') {
This is what my local shows...
![Screen Shot 2021-10-20 at 1 31 23 PM](https://user-images.githubusercontent.com/21045418/138142481-b0167488-89a0-4226-a555-fec7f2970d69.png)

2021-10-22 06:11 UTC, merged