VACMS-6455: add audit tool for VAMC system service headings
department-of-veterans-affairs/va.gov-cms pull request #6733
Opened 2021-10-20 15:29 UTC by JayDarnell

## Description

Closes #6455 

## Testing done

Visual Testing

## Screenshots

<img width="1775" alt="Screen Shot 2021-10-20 at 11 24 00 AM" src="https://user-images.githubusercontent.com/21045418/138123051-a8e03178-e814-4369-a9b1-aabd82e62ed3.png">

Filters applied

<img width="1742" alt="Screen Shot 2021-10-20 at 11 24 17 AM" src="https://user-images.githubusercontent.com/21045418/138123097-53218752-124b-4dba-ad1e-7f5d9b173779.png">

CSV button is present

![Screen Shot 2021-10-20 at 11 24 57 AM](https://user-images.githubusercontent.com/21045418/138123157-07e5a405-e19c-4df1-98f9-37696a0ddebe.png)

Exported CSV file contains rows matching the applied filters

## QA steps

As user with either the administrator role or the content admin role

1. [x] Visit /admin/content/audit/vamc-system-service-audit and verify the page loads
2. [x] Filter the view by VAMC System Description of Service **contains** `<h3>Care we provide at</h3>`
3. [x] Verify the view refreshes and each item includes this heading
4. [x] Scroll to the bottom and click the CSV icon to download a CSV of your filtered results
5. [x] Verify that the CSV contains the same set of filtered items
6. [x] Reset the view filters and filter the view by VAMC System Description of Service **does not contain** `<h3>`
7. [x] Verify the view refreshes and none of the items contain an h3 tag
8. [x] Scroll to the bottom and click the CSV icon to download a CSV of your filtered results
9. [x] Verify the CSV contains the same set of filtered items

As a user without the administrator or content admin roles

1. [x] Visit /admin/content/audit/vamc-system-service-audit and verify you do not have access

2021-10-21 13:27 UTC, kevwalsh approved these changes
This is great stuff. 

I tested a bit with regex, which i've never used in Drupal views filters before

`<h3>[^C]` Revealed 39 instances of h3s that don't start with C
`<h3>[^Care]` Revealed 34 results of h3s that don't start with Care.
`<h4>` revealed 
 [This search](https://pr6733-6rhvouqlarqtfooxropsbkj365ilb4kn.ci.cms.va.gov/admin/content/audit/care-we-provide?title_op=contains&title=&field_body_value_op=not_starts&field_body_value=%3Ch3%3ECare+we+provide)(not Regex) revealed 85 results that don't _start_ with `<h3>Care we provide at`. Some of them start with `<h3 id="something">Care we provide`

In short, i think this audit will help us to 
1. Identify patterns that are not standard
2. Identify places where editors have gone away fromany pattern
3. Determine the scope of migration (how many variants our migration can handle)
4. Determine the scope of manual fixes
5. Determine the scope of change management with editors.

2021-10-21 17:21 UTC, swirtSJW requested changes
Overall this looks good.  But there are bunch of places where the specific naming of the view is  misleading about what the view audits.   We can use it to audit access to care... but thankfully it is much more general and useful than that.   So the names should not mislead us about its abilities.

2021-10-21 17:21 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/views.feature
> +  @dst @views
This leads me to believe you have some behat linter that is running and adding spaces to this.

2021-10-21 17:21 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +  care_audit_export:
This seems too specific.   This report is specific to system services content not 'care'.

2021-10-21 17:21 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +    display_title: 'Care audit export'
'VAMC System service audit' would be a more honest pattern for what this is.

2021-10-21 17:21 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +      path: admin/content/audit/care-we-provide/vacms-system-health-services-care-audit.csv
update path to reflect VAMC System service audit

2021-10-21 17:21 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +        care_audit_page: care_audit_page
VAMC System service audit

2021-10-21 17:21 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +      title: 'VAMC System Health Services Care Audit'
```suggestion
      title: 'VAMC System Health Services Audit'
```

2021-10-21 17:21 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +      path: admin/content/audit/care-we-provide
reflect VAMC System service audit

2021-10-21 17:21 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +        title: 'VAMC System Health Services Care Audit'
```suggestion
        title: 'VAMC System Health Services Audit'
```

2021-10-21 17:21 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +      title: 'VAMC System Health Services Care Audit'
```suggestion
      title: 'VAMC System Health Services Audit'
```

2021-10-21 17:21 UTC, swirtSJW commented on config/sync/views.view.content.yml
> +    display_title: 'Care audit'
VAMC System service audit

2021-10-21 17:21 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/views.feature
> +| Content | Care audit | care_audit_page | Page |
reflect VAMC System service audit

2021-10-21 20:33 UTC, JayDarnell commented on config/sync/views.view.content.yml
> +      path: admin/content/audit/care-we-provide/vacms-system-health-services-care-audit.csv
Updating

2021-10-22 04:57 UTC, swirtSJW approved these changes
This all QA's fine for me.
Idid find that there are no menu links for the new view nor an existing audit tool view.   I tried an easy config change that did not resolve it, so I made a new issue.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6759

2021-10-22 04:58 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/138395666-ddc6dc59-be34-4f7b-9977-4f893d7c36e4.png)

2021-10-22 04:58 UTC, merged