VACMS-6445: Make product field required.
department-of-veterans-affairs/va.gov-cms pull request #6744
Opened 2021-10-21 13:47 UTC by msbtterswrth

## Description

closes #6445 

## Testing done
Created new CMS KB article locally and saw the products field was required.

## Screenshots
![image](https://user-images.githubusercontent.com/8375335/138288665-1402a14b-e66a-48e2-b265-ddb9993f8075.png)

## QA steps

As a cms editor, I can edit or create a new KB article and am required to choose a product.

1. Then validate Acceptance Criteria from issue
- [x] Products field is required on KB article.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change.
  - [x] Merge & carry on unburdened by announcements

2021-10-21 14:32 UTC, kevwalsh requested changes
Tests are still running, but i'm sure Behat test will fail. You'll need to update the drupal spec tool and then copy/paste the behat test it generates. [Instructions are here](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/workflow.md#drupal-spectool).

2021-10-21 16:30 UTC, swirtSJW commented
Test wise:  The behat fail makes sense.  The accessibility does not I'll look into it after the behat is updated.

2021-11-02 22:00 UTC, swirtSJW commented
composer.json needs a 
```
"3213473 - Disallow aria-required on  checkbox.": "https://www.drupal.org/files/issues/2021-06-04/3213473-27.patch",
```

and hopefully that will get tests passing.

2021-11-04 15:47 UTC, swirtSJW commented
I found part of the problem on the drupal.org issue.
https://www.drupal.org/project/drupal/issues/3213473

Somebody misnumbered the patch.   patch 27 comes before patch 24  :)    Patch 24 is the one we should be using.

2021-11-04 20:28 UTC, ethanteague commented
Just letting you all know I'm aware of the last fail and working on it.

2021-11-05 01:45 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_user_guides_content_type_fields.feature
> -@api
@msbtterswrth  his looks like that line ending issue again.  This should only be showing a change to line 17.

2021-11-05 01:46 UTC, swirtSJW requested changes
All looks good except for the line ending jumping in the behat feature.

2021-11-05 12:42 UTC, ethanteague commented on tests/behat/drupal-spec-tool/content_model_user_guides_content_type_fields.feature
> -@api
This is strange. While checked out on this branch, I pulled down the version of this file that lives on `main` and was still seeing a diff against main showing everything as being moved, @swirtSJW

2021-11-05 13:37 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/content_model_user_guides_content_type_fields.feature
> -@api
Updated!

2021-11-05 13:49 UTC, swirtSJW approved these changes

2021-11-05 13:49 UTC, merged