VACMS-6629: Move vamc code from va_gov_backend to va_gov_vamc.
department-of-veterans-affairs/va.gov-cms pull request #6799
Opened 2021-10-26 21:31 UTC by ethanteague

## Description
**Relates to #6629** 
 - moves code that is exclusive to VAMC product to `va_gov_vamc` from `va_gov_backend`
 - leverages event subscribers (instead of traditional hook system)
 - Removes code that is outdated / no longer
 - Renames function to match broader use case

## Testing done
Visual / behat

## QA steps
 - [ ] This will require a real time swarm session (~30min-ish) with @swirtSJW @netboss @ethanteague & possibly @kevwalsh

2021-11-05 02:46 UTC, swirtSJW requested changes
This was really difficult to review with both the change of location (expected) and the refactoring (not expected)  It was really hard to account for all the removals and additions and at the same time looking at the refactoring.   I noted some things that I could not find removals and additions that match.   They may be there, but i could not find them.

2021-11-05 02:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> -  _va_gov_backend_set_owner_section_default($form, $form_state);
Also I can't find where it moved to.

2021-11-05 02:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> -      unset($build[$appt_intro_field]);
This went away, but I can't find where it moved.  It did not seem to get added back in.

2021-11-05 02:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +        unset($build['field_hservice_appt_leadin']);
This appears here, but I can't find its removal

2021-11-05 02:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +        unset($build['field_hservices_lead_in_default']);
Appears, but I can not find its removal.

2021-11-05 02:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +        unset($build['field_hservices_lead_in_default']);
Appears, but can not find its removal.

2021-11-05 02:46 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
> +    $form['#attached']['library'][] = 'va_gov_vamc/set_ief_administration_select';
Added but can't find removal.

2021-11-05 12:21 UTC, ethanteague commented
I did you dirty on this one, @swirtSJW . There were a couple-few functions that were no longer being used (content model changes, etc.), that I removed. I should have broken this into several meaningful commits with meaningful messages for each item. I'll go through these and give detailed explanations.

2021-11-07 20:14 UTC, ethanteague commented
My ambition made a mess of this - closing this pr in favor of more conservative approach: just moving from .module to .module: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6928

2021-11-07 20:14 UTC, closed without merging