VACMS-6536 apply formatting suggestions to services
department-of-veterans-affairs/va.gov-cms pull request #6884
Opened 2021-11-03 14:36 UTC by ethanteague

## Description
Relates to #6536

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/140079452-666bb854-281f-4fb9-923d-55e02cbbf40b.png)

![image](https://user-images.githubusercontent.com/2404547/140079470-48a04409-d601-4076-9a39-923c4026f4ec.png)

![image](https://user-images.githubusercontent.com/2404547/140079496-4343c4e7-c229-41f0-a46e-45f562e217f5.png)

![image](https://user-images.githubusercontent.com/2404547/140079519-91b51b7c-19f2-44ab-8ee4-640815ddd768.png)

![image](https://user-images.githubusercontent.com/2404547/140079546-a84e3f1b-eddd-4ad6-ac2b-8622da365e09.png)

## QA steps
 - [ ] As an administrator, go to `/node/add/regional_health_care_service_des` and visually verify content type name and intro with link to help page appear above unset `Service name` select element.
 - [ ] Visually verify wysiwyg is not present
 - [ ] Select a service, and visually verify beige explanation box with term info is populated, and wysiwyg appears
 - [ ] Hover over question mark icon, and visually verify a help text bubble with text appears.
 - [ ] As an administrator, go to `/node/3690/edit` scroll down to `Services` fieldset, and visually verify help text at top of box has been populated to include a link to a help page.
 - [ ] Click `Add new service` button, and visually verify that workflow widget does not appear below wysiwyg
 - [ ] Select a service, and visually verify beige explanation box with term info is populated.
 - [ ] Hover over question mark icon, and visually verify a help text bubble with text appears.

2021-11-03 15:03 UTC, netboss submitted a review, later dismissed

2021-11-03 15:28 UTC, msbtterswrth approved these changes
Looks really great! 👏🏻

2021-11-03 17:23 UTC, swirtSJW requested changes
Overall looks great.  Nice work.   A few fidly bits in the comments that follow.

2021-11-03 17:23 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +    return NULL;
Major: The caller of this function treats the return as an array, always.   It does not perform any check for null.   It seems like getProductTypeTermFields   should always return an array, which is what you were leaning toward up on line 166 but then steered away from it here on 179.  If you agree with this and make the change, then the docblock for the return needs to be updated.

2021-11-03 17:23 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +  public function appendHealthServiceTermDescription(EntityViewAlterEvent $event):void {
medium: Since this function only seems to operate on Vet Centers, it would be nice to make that clear in the name.
 ```suggestion
  public function appendHealthServiceTermDescriptionToVetCenter(EntityViewAlterEvent $event):void {
```

2021-11-03 17:23 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +      foreach ($services as $key => $service) {
This has the potential to attempt a foreach on a NULL due to line 191  It would be safer to make the fallback on 191 be `[]` rather than `null`

2021-11-03 17:23 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +          ? '<br />' . trim($service_node->get('field_body')->value)
medium: This is long and hard to read and the comments make it really hard to see that the second half of this ternary is 6 lines below.

Lets assign to vars and then use those in the ternary.

I appreciate knowledge in the comments related to magic methods, but those are really for the reviewer not for reading this 6 months from now when changes might be needed.  These would be better in a comment(s) ont he PR but not in the codebase.

2021-11-03 17:52 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +    return NULL;
Dangit.......yeah. Walked away while I was working on this method and lost the narrative when I came back. Good catch, @swirtSJW

2021-11-03 17:54 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +  public function appendHealthServiceTermDescription(EntityViewAlterEvent $event):void {
Yeah, fair enough. I was kinda thinking this would be generic enough for future use for other content types, but I take your point, @swirtSJW :+1:

2021-11-03 17:55 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +      foreach ($services as $key => $service) {
Thanks for catching that, @swirtSJW :+1:

2021-11-03 18:04 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +          ? '<br />' . trim($service_node->get('field_body')->value)
Makes sense to me, @swirtSJW :+1:

2021-11-03 21:27 UTC, rachel-kauff commented
@ethanteague I look a gander, and found a few things. The screenshot is from the VAMC form, but it applies to both VAMC and Vet Center. 

<img width="1226" alt="Screen Shot 2021-11-03 at 12 54 52 PM" src="https://user-images.githubusercontent.com/41017988/140195275-38030683-4b36-405b-822d-ec83dc06e4de.png">
![Screen Shot 2021-11-03 at 2 25 23 PM](https://user-images.githubusercontent.com/41017988/140195287-bf9e6174-f6d7-4f8a-a943-b1b0e98f4995.png)

2021-11-03 21:33 UTC, rachel-kauff commented
Also this relatively minor thing: 
![Uploading Screen Shot 2021-11-03 at 2.29.37 PM.png…]()

2021-11-03 21:38 UTC, rachel-kauff requested changes
Changes requested, see issue comments.

2021-11-03 22:59 UTC, ethanteague commented
Arghhhhh....apologies, @rachel-kauff - missed some obvious stuff. Updated for you to have another look-see when your time permits :+1:

2021-11-04 04:37 UTC, suzanne-gray commented
Hi Ethan! The VAMC version looks great to me! I found a couple of things in the Vet Center version that could use attention. Thanks for taking a look!
<img width="853" alt="Vet Center changes 1" src="https://user-images.githubusercontent.com/90172187/140258653-6c6ad8a8-f0e1-4481-b031-e5fc0cc29b95.png">
<img width="888" alt="Vet Center changes 2" src="https://user-images.githubusercontent.com/90172187/140258669-e6a85619-79e5-4357-b67e-8845fe506953.png">

2021-11-04 11:59 UTC, ethanteague commented
> Hi Ethan! The VAMC version looks great to me! I found a couple of things in the Vet Center version that could use attention. Thanks for taking a look! 

Thanks for reviewing this, @suzanne-gray! Updated :+1: 

![image](https://user-images.githubusercontent.com/2404547/140309737-85fcbcfe-2171-4a25-a945-a79a159c11c7.png)

![image](https://user-images.githubusercontent.com/2404547/140309753-84f3eb0c-e746-4145-b259-cd0d23da42ac.png)

2021-11-04 13:09 UTC, kevwalsh commented
I renamed the PR to make it a bit more descriptive.

2021-11-04 14:10 UTC, swirtSJW approved these changes
Nice work Ethan.    Code passes QA

2021-11-04 14:21 UTC, swirtSJW commented
QA steps pass too.  Nice work @ethanteague

2021-11-04 14:23 UTC, merged