VACMS-6456: script to remove leading care we provide h3 tags from VAM…
department-of-veterans-affairs/va.gov-cms pull request #6889
Opened 2021-11-03 22:39 UTC by JayDarnell

…C System Health Service nodes

## Description

Closes issue #6456 

## Testing done

Visual testing

## Screenshots

![Screen Shot 2021-11-03 at 6 32 50 PM](https://user-images.githubusercontent.com/21045418/140209913-73a6ce96-6405-40da-bbe3-1081143ad43a.png)

<img width="1604" alt="Screen Shot 2021-11-03 at 6 33 16 PM" src="https://user-images.githubusercontent.com/21045418/140209923-3a866fc4-f566-4847-806a-eec596ad25ee.png">

## QA steps

As an administrator 
- [ ] Visit /admin/content/audit/vamc-system-service-audit
- [ ] Filter the results by VAMC System Description of Service: regular expression = `^<h3>Care we provide at .+ health care`
- [ ] Note the number of records and notice that they all start with this h3 tag
- [ ] From the terminal run the script: `drush scr scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php`
- [ ] When the script finishes note the number of records impacted (it should match the number found with the view)
- [ ] Go back to the view and reuse the same filter. No records should be returned.
- [ ] Remove all filters and notice how the vast majority of the results no longer have a leading h3 tag

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### This should not be merged yet

- [x] `DO NOT MERGE`

2021-11-05 03:18 UTC, swirtSJW requested changes
This looks really good @JayDarnell   Some minor stuff.   It would be great to get the query and the preg replace to use the same string var if possible.  You may have already tried that so disregard if it will not work.

2021-11-05 03:18 UTC, swirtSJW commented on scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php
> +    $new_body = preg_replace('/<[hH]3>[cC]are [wW]e [pP]rovide at .+ [hH]ealth [cC]are<\/[hH]3>/', '', $field_body, 1);
Would just doing a case inesnsitive replace made this cleaner?
```suggestion
    $new_body = preg_replace('/<H3>Care We Provide at .+ Health Care<\/H3>/i', '', $field_body, 1);
```
Then it could all be set using the same pattern as line 38.   Manily so that could be put in a var higher up and reused, to make it easier for other iterations.

2021-11-05 03:18 UTC, swirtSJW commented on scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php
> +      $node->setRevisionLogMessage('Resaved node with leading h3 removed.');
```suggestion
      $node->setRevisionLogMessage('Resaved node with leading h3  "Care we provide at ..." removed.');
```
Medium:  There are more of these coming, so we want this to be more explicit.

2021-11-05 03:18 UTC, swirtSJW commented on scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php
> +      // Set revision log message.
```suggestion
```
Minor: No clearer than the code itself.

2021-11-05 03:18 UTC, swirtSJW commented on scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php
> +      // Save the changes.
```suggestion
      // Save the changes.
```
Minor: No clearer than the code itself

2021-11-05 03:18 UTC, swirtSJW commented on scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php
> +  return "Processing VAMC System Health Service nodes... {$sandbox['current']} / {$sandbox['total']}.\n";
```suggestion
  return "Processed VAMC System Health Service nodes... {$sandbox['current']} / {$sandbox['total']}.\n";
```
Minor:

2021-11-05 14:25 UTC, JayDarnell commented on scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php
> +    $new_body = preg_replace('/<[hH]3>[cC]are [wW]e [pP]rovide at .+ [hH]ealth [cC]are<\/[hH]3>/', '', $field_body, 1);
I like this so much better. I somehow missed that the trailing `i` was for case insensitive. :)

2021-11-12 21:25 UTC, swirtSJW approved these changes

2021-11-12 21:59 UTC, swirtSJW commented
Closing this temporarily QA report  run on tugboat
![image](https://user-images.githubusercontent.com/5752113/141538579-7a974c9f-34d5-4c7a-bb6c-435aff3fef79.png)
...
![image](https://user-images.githubusercontent.com/5752113/141538822-a0622274-b5bf-431c-ab1e-065d186a2373.png)

**runtime**: ~ 3 min to finish the list of processed items... but another 3 min to return control to the terminal while post save actions complete.

- [x] Compare `[/portland-health-care/health-services/podiatry-at-va-portland-health-care](https://pr6889-j46ughfvhfpm8zop1eepr8hurvfiytje.ci.cms.va.gov/portland-health-care/health-services/podiatry-at-va-portland-health-care)` to prod and verify the heading has been removed but the page is intact.

![image](https://user-images.githubusercontent.com/5752113/141539569-1815911f-ef24-4094-a2d9-100f5673e44e.png)

2021-11-12 22:02 UTC, swirtSJW approved these changes
Nice work on this Jay.
Code review pass 
QA testing Pass

2021-11-12 22:06 UTC, swirtSJW commented
When ready to run this (after the headings are in place on FE prod)  we will need to run this script on cms prod 

`drush scr ./scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php` 
Time to list out the processing ~3 min
Don't panic.  There will be 5-10 min of dead time while post safe drupal stuff happens before the script returns control to the terminal.  
![image](https://user-images.githubusercontent.com/5752113/141540169-6c3ad877-61e5-4489-9860-6d50500ea692.png)

2021-11-12 22:06 UTC, merged