[WIP] VACMS-2041 - Update office content model with Connect with Us
department-of-veterans-affairs/va.gov-cms pull request #6903
Opened 2021-11-04 18:09 UTC by msbtterswrth

## Description

Relates to #2041 .

## Testing done
Added an office locally and verified new field existence on node create page. 

## Screenshots
![image](https://user-images.githubusercontent.com/8375335/140395084-3674a439-ef2a-4213-99f0-6cfc6cf85fd2.png)

## QA steps

As a cms editor I can 
1. View the node edit/create screen for an office (/node/add/office) and see the new fields
1. Then validate Acceptance Criteria from issue
- [ ] Add social media fields to office nodes
- [ ] Add an optional entity reference to Office from Benefits Hub Landing page (this is to support the Records Hub)
- [ ] Add an optional entity reference to Office from Campaign Landing page (this will replace the existing Connect With Us field)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-11-09 14:50 UTC, ndouglas commented on config/sync/core.entity_form_display.node.office.default.yml
> -        - revision_log
😭

2021-11-12 22:52 UTC, swirtSJW commented
Referencing this drupal.org issue which provided the patch  https://www.drupal.org/project/drupal/issues/3219165

2021-11-12 23:22 UTC, swirtSJW requested changes
Code changes look good other than some  alteration of lines in the behat features .  You may have to alter your editor to both 
* trim trailing spaces 
* add or not trim trailing end of file newline.

QA steps need some more specificity please.   QA is more than just the listing of the AC's.  It is about 
   1. Telling what you did to QA and the QAer specifically what they should be doing and looking for.  The QA er should not have to invent or research what they are looking for.
   2. Pointing out possible failure points and how to look for them.  Example:  In your code there is a fairly significant change to the admin menu offset logic.  Yet there is nothing in the QA steps that suggest to validate that the change didn't break anything or look for something the change was supposed to fix/improve.

2021-11-12 23:22 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
> +| Content type | Publication Listing Page | Related office or health care system | field_office | Entity reference | Required | 1 | Select list | Translatable |
We lost the trailing newline here.

2021-11-12 23:22 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
> +  @dst @field_type @content_type_fields @dstfields
Not sure where all these trailing spaces are coming from.

2021-11-12 23:22 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
> +  @dst @field_type @content_type_fields @dstfields
Trailing spaces coming from somewhere.

2021-11-12 23:22 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
> +| Content type | Support Service | Related office | field_office | Entity reference | Required | 1 | Select list | Translatable |
trailing newline lost.

2021-11-12 23:22 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
> +  @dst @field_type @content_type_fields @dstfields
trailing spaces

2021-11-18 15:52 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
> +  @dst @field_type @content_type_fields @dstfields
fixed.

2021-11-18 15:52 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
> +| Content type | Support Service | Related office | field_office | Entity reference | Required | 1 | Select list | Translatable |
fixed.

2021-11-18 15:52 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
> +  @dst @field_type @content_type_fields @dstfields
fixed

2021-11-18 15:52 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
> +  @dst @field_type @content_type_fields @dstfields
fixed

2021-11-18 15:52 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
> +| Content type | Publication Listing Page | Related office or health care system | field_office | Entity reference | Required | 1 | Select list | Translatable |
fixed.

2021-11-18 15:56 UTC, msbtterswrth commented
> 
> 
> Code changes look good other than some alteration of lines in the behat features . You may have to alter your editor to both
> 
>     * trim trailing spaces
> 
>     * add or not trim trailing end of file newline.
> 
> 
> QA steps need some more specificity please. QA is more than just the listing of the AC's. It is about
> 
>     1. Telling what you did to QA and the QAer specifically what they should be doing and looking for.  The QA er should not have to invent or research what they are looking for.
> 
>     2. Pointing out possible failure points and how to look for them.  Example:  In your code there is a fairly significant change to the admin menu offset logic.  Yet there is nothing in the QA steps that suggest to validate that the change didn't break anything or look for something the change was supposed to fix/improve.

I'm not actually sure what happened with those trailing spaces, but when i copy the behat test from the spec tool, they're in there. They're not added by my ide, which is strange. I have however manually resolved that issue.

As for the qa steps, I will try to add more detail, though I'm not sure i touched anything with the menus... do you mean the tabs on the office content type?

2021-11-19 03:15 UTC, swirtSJW commented
> ... though I'm not sure i touched anything with the menus... do you mean the tabs on the office content type?

Thanks @msbtterswrth I'm referring to these changes to the admin menu js.   Were they meant to be in a different PR?
![image](https://user-images.githubusercontent.com/5752113/142558854-f13713c7-f070-428f-bf6d-bf63ead7ae41.png)

2021-11-19 03:34 UTC, swirtSJW requested changes
A couple issues with inconsistent field labels.   VA style guide is sentence case.

Also these QA steps don't seem to be doable.
![image](https://user-images.githubusercontent.com/5752113/142560530-4edf19a9-3ead-4d7a-b603-11759f1e141d.png)

2021-11-19 03:34 UTC, swirtSJW commented on config/sync/field.field.node.campaign_landing_page.field_related_office.yml
> +label: 'Related Office'
Should this be sentence case?

2021-11-19 03:34 UTC, swirtSJW commented on config/sync/field.field.node.landing_page.field_related_office.yml
> +label: 'Related Office'
Sentence case

2021-11-19 03:34 UTC, swirtSJW commented on config/sync/field.field.node.office.field_email_updates_link.yml
> +label: 'Email Updates Link'
Sentence case?

2021-11-19 03:34 UTC, swirtSJW commented on config/sync/field.field.node.office.field_external_link.yml
> +label: 'External Link'
sentence case

2021-11-19 03:34 UTC, swirtSJW commented on config/sync/field.field.node.office.field_external_link.yml
> +description: 'Enter a link to the office homepage on legacy va.gov or another external site.'
Did this text go through a round of UX review?  Specifically wondering about " on legacy va.gov" as I am not sure that is a reference that has meaning for editors.

2021-11-19 03:34 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
> +| Content type | Office | External Link | field_external_link | Link |  | 1 | Link |  |
Sentence case

2021-11-19 03:34 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
> +| Content type | Office | Email Updates Link | field_email_updates_link | Link |  | 1 | Link |  |
Sentence case

2021-11-19 12:46 UTC, ndouglas commented
@swirtSJW 

>I'm referring to these changes to the scrollto js accounting for the admin menu height. Were they meant to be in a different PR?

Those changes were made because the scrolling JS assumed that `$(target).offset()` would always be defined.  [That is not always the case](https://api.jquery.com/offset/) for hidden elements, etc.  Consequently one of the tests broke when a field in there was autofilled IIRC.  It's probably breaking frequently but not visibly enough to attract attention -- just adding another red line in the JS console.

There probably should've been a test added to show the broken behavior and demonstrate that this change fixed it, but it originally was just an assumption/lack of defensiveness so I personally didn't figure it was worth bringing it up.  IIRC I actually made the commit containing that change so it's my fault for not socializing the change more openly.

2021-11-19 14:10 UTC, msbtterswrth commented on config/sync/field.field.node.campaign_landing_page.field_related_office.yml
> +label: 'Related Office'
fixed

2021-11-19 14:10 UTC, msbtterswrth commented on config/sync/field.field.node.landing_page.field_related_office.yml
> +label: 'Related Office'
fixed

2021-11-19 14:10 UTC, msbtterswrth commented on config/sync/field.field.node.office.field_email_updates_link.yml
> +label: 'Email Updates Link'
fixed

2021-11-19 14:11 UTC, msbtterswrth commented on config/sync/field.field.node.office.field_external_link.yml
> +label: 'External Link'
fixed

2021-11-19 14:11 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
> +| Content type | Office | External Link | field_external_link | Link |  | 1 | Link |  |
fixed

2021-11-19 14:11 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
> +| Content type | Office | Email Updates Link | field_email_updates_link | Link |  | 1 | Link |  |
fixed

2021-11-19 14:13 UTC, msbtterswrth commented on config/sync/field.field.node.office.field_external_link.yml
> +description: 'Enter a link to the office homepage on legacy va.gov or another external site.'
kev and I talked through it, but it will likely go through a final round of ux when the frontend is ready to be hooked up.

2021-11-21 20:08 UTC, kevwalsh commented on config/sync/field.field.node.office.field_external_link.yml
> +description: 'Enter a link to the office homepage on legacy va.gov or another external site.'
> A couple issues with inconsistent field labels. VA style guide is sentence case. 

VA style guide for veterans is sentence case, but there is a lot of use of Initial case in labels throughout the CMS, to Rachel's spec, including content types, field, and other things. 

> Specifically wondering about " on legacy va.gov" as I am not sure that is a reference that has meaning for editors.

I agree that this may not be ideal, but i don't want to burn design cycles on this. It's unlikely this field will exist once we have real editors for this content type, it will be going away when the office product is built and rolled out.

2021-11-22 16:46 UTC, msbtterswrth commented on config/sync/field.field.node.office.field_external_link.yml
> +description: 'Enter a link to the office homepage on legacy va.gov or another external site.'
I believe the latest update does fix the sentence casing, so if that's all good, we should be good to go!

2021-11-22 18:00 UTC, swirtSJW approved these changes
s a cms editor I can

- [x] View the node edit/create screen for an office (/node/38442/edit) and see the new fields for social media links
- [x] View the node edit/create screen for an office (/node/38442/edit) and see the new fields for external link

![image](https://user-images.githubusercontent.com/5752113/142911258-06ee1d53-0579-4733-8cfd-8f02eeadfce3.png)



- [?]View the node edit/create screen for an office (/node/38442/edit) and see the new fields for newsletter link
Is this the newlsetter link?
![image](https://user-images.githubusercontent.com/5752113/142911648-496ce425-cf4b-4b23-a747-5d7b4b844ce5.png)


- [x] View the node edit/create screen for an office (/node/38442/edit) and see that the fields have been organized into vertical tabs
- [x] View the form view screen for a benefits hub (/admin/structure/types/manage/landing_page/form-display) and confirm the new optional field 'Related office' is hidden
- [x] View the form view screen for a campaign landing page (/admin/structure/types/manage/campaign_landing_page/form-display) and confirm the new optional field 'Related office' is hidden
Then validate Acceptance Criteria from issue
 Add social media links field to office nodes
 Add email updates field to office nodes
 Add external link field to office nodes
 Add an optional entity reference to Office from Benefits Hub Landing page (this is to support the Records Hub)
 Add an optional entity reference to Office from Campaign Landing page (this will replace the existing Connect With Us field)
 Update drupal spec tool for new fields
 Hide new fields until frontend has been implemented

2021-11-22 18:01 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/142912027-d2fb58f7-4fd2-49f3-b58b-d9f529c87213.png)

2021-11-22 18:07 UTC, merged

2021-11-22 18:09 UTC, swirtSJW commented
> > Code changes look good other than some alteration of lines in the behat features . You may have to alter your editor to both
> > ```
> > * trim trailing spaces
> > 
> > * add or not trim trailing end of file newline.
> > ```


> I'm not actually sure what happened with those trailing spaces, but when i copy the behat test from the spec tool, they're in there. They're not added by my ide, which is strange. I have however manually resolved that issue.

@msbtterswrth  Sorry, yes they are their from the copy and paste,  that's why I am suggesting that your IDE should be configured to trim trailing spaces and add end of file newline on save.  That way it matches all the other IDE configurations on the project so we don't keep having dueling PRs.  Your IDE is likely already doing that for things like .php files.   You just need to add a couple rules for .feature files.