VACMS-5387: Add script to attach service location to health service nodes
department-of-veterans-affairs/va.gov-cms pull request #6936
Opened 2021-11-08 16:49 UTC by ethanteague

## Description
Relates to #5387

## Testing done
Visual / logs / console output

## QA steps
 - [ ] run `lando drush scr scripts/content/VACMS-5387-facility-services-add-service-location-2021-11.php`
 - [ ] after script completes (5-10 minutes), visit `admin/reports/dblog` and visually verify `Attaching service locations to health service nodes completed by drush script.` message appears

2021-11-08 17:24 UTC, netboss approved these changes
@ethanteague This looks great! Thanks!

2021-11-08 20:34 UTC, netboss commented
@ethanteague 
QA'ed this locally and all seems to be fine. One note though, I had to run the script twice (second time after rebuilding local lando env) because the first time when I tried to access the site I got this error:

> The website encountered an unexpected error. Please try again later.
PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in Drupal\Component\DependencyInjection\PhpArrayContainer->createService() (line 79 of /app/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php).

Not sure if this have any relation to the script, but just to double check and confirm, I rebuilt local lando env and then re-ran the script and this time all was fine.

2021-11-18 14:34 UTC, swirtSJW requested changes
Unnecesary repeated queries.  See comments below.

2021-11-18 14:34 UTC, swirtSJW commented on scripts/content/VACMS-5387-facility-services-add-service-location-2021-11.php
> + * Creates the service location address paragraph for the service location.
doc block missing param.

2021-11-18 14:34 UTC, swirtSJW commented on scripts/content/VACMS-5387-facility-services-add-service-location-2021-11.php
> +  $sandbox['#finished'] = 0;
It should not run these on each iteration.   It should only run this once.   All of these should be inside a  check for !isset($sandbox[total]

If the total is not set, it should run all the initial query and counts.   After that it should just update the nids_to_update,

2021-11-18 14:35 UTC, swirtSJW commented on scripts/content/VACMS-5387-facility-services-add-service-location-2021-11.php
> +  $sandbox['#finished'] = 0;
$sandbox should keep the state.   It should not be re-declared with each run.

2021-11-18 17:44 UTC, ethanteague commented on scripts/content/VACMS-5387-facility-services-add-service-location-2021-11.php
> +  $sandbox['#finished'] = 0;
Doesn't work for me when I run it that way, @swirtSJW - if I put it in an isset, I end up looping over the same set of 50 nodes in each loop. 
I tried a bunch of different ways to emulate what you did in `scripts/content/VACMS-2975-update-vamc-service-nodes-2020-10.php` when I put this together (and some other ways, today), but the way the script is written now is the only way I can seem to get through all of the updates.

2021-11-18 23:01 UTC, swirtSJW commented
Just adding some noted to track the state of the data.
This pr operates on 3,036 facility health service nodes out of a total of   12658

So approx 24% did not have defaults and they do as a result of running the script.

2021-11-18 23:04 UTC, swirtSJW approved these changes
Nice work Ethan.

I ran the script on tugboat
![image](https://user-images.githubusercontent.com/5752113/142510527-de7eb534-3390-48fe-bb9d-2a8826604d59.png)
Completes appropriately.
![image](https://user-images.githubusercontent.com/5752113/142510591-9981c6b9-c412-47bd-a84c-6039bfaba49c.png)

Running it a second time results in no items to process which is good.
![image](https://user-images.githubusercontent.com/5752113/142510663-31d31cb0-89fd-48b2-bc7f-70c341add216.png)


Logging is good
![image](https://user-images.githubusercontent.com/5752113/142510694-93ee4574-15b6-46d1-9706-01dac86ee09a.png)

CHecked out the affected nodes.   Messaging is good.  REsulting data is good.
![image](https://user-images.githubusercontent.com/5752113/142510738-7f01f951-945e-4c13-90ef-131e2aa0403a.png)

2021-11-18 23:08 UTC, swirtSJW commented on scripts/content/VACMS-5387-facility-services-add-service-location-2021-11.php
> +    Drupal::logger('drush_scr')->log(LogLevel::INFO, 'Processing all %count health service nodes completed by drush script.', [
Disregard

2021-11-19 01:13 UTC, merged