VACMS-6955: Reveal title field for admins.
department-of-veterans-affairs/va.gov-cms pull request #6961
Opened 2021-11-12 00:35 UTC by ethanteague

## Description
Relates to #6955

## Testing done
Visual / manual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/141387991-5be2b104-041b-48de-92cb-151fdb18e56e.png)

## QA steps
 - [ ] As an administrator, go to `node/3840/edit` and visually verify presence of Official name field.
 - [ ] Change the value in Official name field, and confirm it is reflected in the page title on the view page and the node form.
 - [ ] Login as any user who is not an admin and has access to node 3840, and go to `node/3840/edit` and visually verify absence of the Official name field.

2021-11-12 01:13 UTC, kevwalsh requested changes
This should remain hidden on the form until #6449 (next up!). This issue, #6955 should just be allowing admins to edit the node title (the "common name", not the "official name")

 Looks like this code will be helpful for #6449 so keep it around!

2021-11-12 01:54 UTC, ethanteague commented
> This should remain hidden on the form until #6449 (next up!). This issue, #6955 should just be allowing admins to edit the node title (the "common name", not the "official name")
> 
> Looks like this code will be helpful for #6449 so keep it around!

@kevwalsh looks like we are using the official name to populate the common name (node title) when a migration doesn't have a title for the center. I don't think we've ever used a drupal entity title for vc's.....have we? I didn't see it anywhere in our codebase.

2021-11-12 04:15 UTC, kevwalsh commented
@ethanteague looks like it's called "Name of faciliity", but wlil be renamed to "Common name" in #6449.  

<details><summary>Screenshot</summary>

From https://pr6961-clpzzkqy6xmupbqs2rshkm9dte4aw4p3.ci.cms.va.gov/admin/structure/types/manage/vet_center/form-display


<img width="708" alt="Manage_form_display___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/141408036-4cf1070c-7a32-4e49-9a6f-ed477162ceb3.png">


</details>

We may want to go ahead and rename the title field now, and enable it for admins, hide it for others. 

<details><summary>Screenshot</summary>
From https://pr6961-clpzzkqy6xmupbqs2rshkm9dte4aw4p3.ci.cms.va.gov/admin/structure/types/manage/vet_center


<img width="806" alt="Edit_Vet_Center_content_type___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/141408221-f72e4d0d-b621-417e-a618-81973504f137.png">

</details>


Others can currently see the node titile, but no one can edit it. 

<details><summary>Screenshot</summary>
<img width="1006" alt="Edit_Vet_Center_Kailua-Kona_Vet_Center___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/141408410-308f0959-3152-4710-9995-7a6293742e8e.png">



</details>

2021-11-12 14:56 UTC, netboss submitted a review, later dismissed
@ethanteague This looks good. The only one thing I might suggest is to highlight the page title text either with `<b>`/`<strong>` or maybe put it in `<h*>` tags, but I guess this depends on approved designs.

2021-11-12 15:14 UTC, swirtSJW reviewed
I had some questions about this approach.  It does not seem to match the AC's.   There will be more coming later related to conditional visibility but I don't think unsetting the title field from the form is the interim approach we want to take.

2021-11-12 15:14 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +      unset($form['field_official_name']);
Are you sure we don't want to make this disabled?   

The AC does not mention hidden or removal.
![image](https://user-images.githubusercontent.com/5752113/141488920-fc78d533-efe0-4193-b31c-f1d2dea61a87.png)

2021-11-12 15:14 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.services.yml
> +    arguments: ['@string_translation', '@va_gov_user.user_perms']
Weird.... we were passing in an arg that was not being caught... I would have expected some php warnings over that one.  Good catch.

2021-11-12 17:38 UTC, ethanteague commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +      unset($form['field_official_name']);
Yeah, I'll make it disabled.

2021-11-15 21:19 UTC, ethanteague commented
Updated

2021-11-17 21:54 UTC, swirtSJW reviewed
Seeing a couple changes I am not following the need for:

2021-11-17 21:54 UTC, swirtSJW commented on config/sync/node.type.vet_center.yml
> +    - menu_force
Confused  about this addition.   It seems completely unrelated to revealing the title field?

2021-11-17 21:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    elseif (!Drupal::service('va_gov_user.user_perms')->hasAdminRole()) {
This should apply only to vet centers.  By putting it here is seems like it is applying to all non vha facilities.

2021-11-17 23:36 UTC, ethanteague commented on config/sync/node.type.vet_center.yml
> +    - menu_force
Yeah, I noticed this, and wondered if maybe it held some necessary magic. No biggie to pull out (doesn't break anything when I test locally).

2021-11-17 23:40 UTC, ethanteague commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    elseif (!Drupal::service('va_gov_user.user_perms')->hasAdminRole()) {
Wouldn't we want to allow for admins to have the same level of control over api populated titles for temp / on the fly stuff across all types? I guess I don't understand why only vc's? I'm changing....just letting you know my thought process.

2021-11-19 03:57 UTC, swirtSJW commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    elseif (!Drupal::service('va_gov_user.user_perms')->hasAdminRole()) {
Because vet center titles are  not populated by the facility API any more.  They have the new Official name field which gets populated by the migration.   The node title is now considered the plain language name and we have to be able to edit it (via change management request when needed)

Now that being said.  All the facility api fields should be unlocked for admins and are currently across the VAMC facilities.
![image](https://user-images.githubusercontent.com/5752113/142561844-48e28d69-544b-49ae-b44b-e9dec41c567e.png)
They are also unlocked for vetcenters too
![image](https://user-images.githubusercontent.com/5752113/142562165-cefdbcee-0b46-44af-8695-a9efd7af09ab.png)


The problem is, the title is not located in that field group so is missing the logic to unlock it.  It somehow got a snowflake treatment that put it someplace without it being treated as a field 
![image](https://user-images.githubusercontent.com/5752113/142562285-72a61ddc-9699-4aad-b81e-433582b6b519.png)


It probably didn't need a special case treatment for dissabling if it was just moved back the facilityAPI box, but now it actually would be mislieading to put in faclity API box since it no longer is controlled by that.

2021-11-19 04:08 UTC, swirtSJW requested changes
I don't think this logic is working correctly.
I logged in as me and could edit... which is good
![image](https://user-images.githubusercontent.com/5752113/142563256-149b4a5d-ec13-4b71-8268-eff832537c81.png)


But then I logged in as a vetcenter editor Sharran.Chambers-Murphy@va.gov (not content admin)
![image](https://user-images.githubusercontent.com/5752113/142563321-b969e4c8-6a24-46d0-8515-314a8b6a9a18.png)
 
and I could still edit the title field (which is bad).
![image](https://user-images.githubusercontent.com/5752113/142563388-80c0a0aa-3a52-49d6-89ac-91cccc99862e.png)

2021-11-19 13:34 UTC, ethanteague commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    elseif (!Drupal::service('va_gov_user.user_perms')->hasAdminRole()) {
> I don't think this logic is working correctly. I logged in as me and could edit... which is good ![image](https://user-images.githubusercontent.com/5752113/142563256-149b4a5d-ec13-4b71-8268-eff832537c81.png)
> 
> But then I logged in as a vetcenter editor [Sharran.Chambers-Murphy@va.gov](mailto:Sharran.Chambers-Murphy@va.gov) (not content admin) ![image](https://user-images.githubusercontent.com/5752113/142563321-b969e4c8-6a24-46d0-8515-314a8b6a9a18.png)
> 
> and I could still edit the title field (which is bad). ![image](https://user-images.githubusercontent.com/5752113/142563388-80c0a0aa-3a52-49d6-89ac-91cccc99862e.png)

Dangit. Sorry about that, @swirtSJW - updated.

2021-11-22 18:41 UTC, swirtSJW requested changes

2021-11-22 18:41 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +  public function unsetNameFieldForNonAdmins(FormIdAlterEvent $event): void {
Name and comment don
t agree with what is happening here.
**doc**: remove
**function**: unset
**code**: disable

Only the code is speaking the truth.  The other two are sowing seeds of confusion.

2021-11-22 18:41 UTC, swirtSJW commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    elseif (Drupal::service('va_gov_user.user_perms')->hasAdminRole() && !in_array($form_id, [
This comment does not agree with what is happening here.  it says for all roles, but then it is only locking it down if the user as an admin role.    Also does not make sense to lock it down for only admins.

In the larger picture, something seems odd here.  You replaced a single else (generic catch-all) with two very specific else_ifs.  There is no longer a catch-all.  I think you are broadly impacting a lot with this change.
I could see an addition of a single else_if... but I would still expect it to end with an else.

2021-11-22 18:41 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +      'hook_event_dispatcher.form_node_vet_center_form.alter' => 'unsetNameFieldForNonAdmins',
This pattern prevents these form.alter from doing anything else.   They can only do `unsetNameFieldForNonAdmins`
A better pattern would be something like
```suggestion
      'hook_event_dispatcher.form_node_vet_center_form.alter' => vetcenterFormAlter',
```

Then inside that function it would call `unsetNameFieldForNonAdmins` and any other methods we need to call.

2021-11-23 20:59 UTC, ethanteague commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +  public function unsetNameFieldForNonAdmins(FormIdAlterEvent $event): void {
![image](https://user-images.githubusercontent.com/2404547/143120783-d2705b73-5587-4f2a-8327-82ed0dfaa620.png)

2021-11-23 23:53 UTC, ethanteague commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    elseif (Drupal::service('va_gov_user.user_perms')->hasAdminRole() && !in_array($form_id, [
Yeah, I got too cute on this one - cleaned it up, @swirtSJW :+1:

2021-11-23 23:54 UTC, ethanteague commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +      'hook_event_dispatcher.form_node_vet_center_form.alter' => 'unsetNameFieldForNonAdmins',
Yep, agreed. Got lazy - updated, @swirtSJW :+1:

2021-11-26 01:04 UTC, ethanteague commented
@kevwalsh - I agree with you that this work has been subsumed by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7045. Closing this one down. 
cc: @swirtSJW

2021-11-26 01:04 UTC, closed without merging