VACMS-6639: autogenerate required service nodes for all vet centers
department-of-veterans-affairs/va.gov-cms pull request #6985
Opened 2021-11-17 15:17 UTC by JayDarnell

## Description

Closes #6639 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-11-19 01:35 UTC, swirtSJW requested changes
This review is not complete but there are enough things needing changing that I want to get this out to you.

2021-11-19 01:35 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/Plugin/QueueWorker/RequiredServiceBase.php
> +    $moderation_state = ($published ? 'published' : 'draft');
Kind of an odd pattern to assume the moderation based on isPublished() rather than getting the actual moderation state with $vet_center->get('moderation_state')->value .  Is there a reason to not use the actual moderation state?

->isPublished() returns true even if the revision you are operating on is draft.

2021-11-19 01:35 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/Plugin/QueueWorker/RequiredServiceBase.php
> +    $node = Node::create([
We've got a couple of nodes we are juggling in this function.   Lets be specific about what kind of node it is to avoid confusion.
```suggestion
    $vet_center_facility_health_service_node = Node::create([
```

2021-11-19 01:35 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +  public function getRequiredServices() {
Hmmm we should consider using the state of the service to keep from having to do this query every time this is called.

2021-11-22 14:06 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +  public function getRequiredServices() {
I've added this into my most recent update.

2021-11-23 22:17 UTC, swirtSJW requested changes
Some suggestions and some questions

2021-11-23 22:17 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +    if ($service_term->getEntityTypeId() == 'taxonomy_term'
```suggestion
    if ($service_term->getEntityTypeId() === 'taxonomy_term'
```

2021-11-23 22:17 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +      && $service_term->bundle() == 'health_care_service_taxonomy'
```suggestion
      && $service_term->bundle() === 'health_care_service_taxonomy'
```

2021-11-23 22:17 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +      && !$service_term->isNew()) {
I am not clear on why this has to not be new.  Couldn't a new term be added that is required that would need this process?

2021-11-23 22:17 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +          $vet_center = $node_storage->load($missing_nid);
moderate: Loading each one separately can be kind of intensive.   Since missing_nids is an array of all the nodes you need.  Better to load multiple, then foreach through those instead of foreaching through the nids.

2021-12-01 18:32 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +    // Add all required services for this newly created facility.
I'm updating the method name to be addRequiredServicesByFacility

2021-12-01 18:33 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +    // Add any missing services for this newly required term.
I'm updating the method name to be addRequiredServicesByTerm and removing the inline comment.

2021-12-01 18:34 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +    // Add all required services for this newly created facility.
I'm removing the inline comment and updating the method name to be addRequiredServicesByFacility

2021-12-01 18:34 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +    // Add any missing services for this newly required term.
I'm removing the inline comment and updating the method name to be addRequiredServicesByTerm

2021-12-01 18:46 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Plugin/QueueWorker/RequiredServiceBase.php
> +    $vet_center = $this->nodeStorage->load($data->facility_id);
This is such a good catch. I had every intention of doing this and completely forgot to tie it together like this.

2021-12-01 18:59 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +    $item->term_id = $service_term->id();
Coming right up

2021-12-01 19:03 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +      && $service_term->bundle() == 'health_care_service_taxonomy'
Fixed

2021-12-01 19:03 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +    if ($service_term->getEntityTypeId() == 'taxonomy_term'
Fixed

2021-12-01 20:25 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Plugin/QueueWorker/RequiredServiceBase.php
> +      'uid' => $author_uid,
I've added support for this. For health service nodes created due to a taxonomy term being required the log message is: Created from required VHA health service term. For nodes created due to new facilities the message is: Created from new parent facility.

2021-12-01 20:36 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +      && is_null($facility_node->original)) {
I believe I switched to using is_null because I couldn't get it to work with isNew but perhaps that was because the type hint was missing previously. I'll give it another go.

2021-12-01 20:48 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +          $vet_center = $node_storage->load($missing_nid);
Updating this.

2021-12-01 20:54 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +      // Unset any items in the array that aren't required.
Heh, not sure what happened here. Likely started building the code one way with that comment and then reworked it without updating the comment.

2021-12-01 20:56 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +   *   Is this term is required or not.
Updated

2021-12-01 20:56 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +   *   Does the provided service exist for the provided facility.
Updated

2021-12-01 20:57 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +  protected function hasService(EntityInterface $service_term, EntityInterface $facility_node) {
No but this was in the spec for the issue so I added it.

2021-12-02 02:06 UTC, JayDarnell commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +      && is_null($facility_node->original)) {
Yes, after retesting this we cannot use isNew() here.

2021-12-02 21:22 UTC, swirtSJW reviewed
Looks good Jay.   I just have to do some testing on it.

2021-12-02 21:22 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +    /** @var \Drupal\taxonomy\TermInterface $service_term */
Minor:  Is there a reason why this declaration is not in the docblock for the method?   THe only reason for this more specific declaration is in the case where "isRequiredService" had to accept something that was not a \Drupal\taxonomy\TermInterface

2021-12-03 07:26 UTC, swirtSJW approved these changes
@JayDarnell  This works great.
I  added the following:
Logging and status  messages so we can see what happened
![image](https://user-images.githubusercontent.com/5752113/144562128-fe40c135-f866-4e3e-a82d-686653c95830.png)


![image](https://user-images.githubusercontent.com/5752113/144562162-55f45193-1589-4a9d-9665-11376c736b81.png)


I also added a deduper to the the queue adder.  Otherwise if somebody jigled the handle (un-required, then required) twice,  we'd end up with duplicates of every required service.

2021-12-03 07:52 UTC, swirtSJW commented on docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
> +
I added this.

2021-12-03 08:31 UTC, swirtSJW approved these changes
![image](https://user-images.githubusercontent.com/5752113/144570741-fc59940c-7476-4995-bc36-c1fc71d7bc1d.png)
All good.

2021-12-03 09:19 UTC, merged