VACMS-6873: show related non-clinical services on top task edit forms…
department-of-veterans-affairs/va.gov-cms pull request #7037
Opened 2021-11-23 16:25 UTC by JayDarnell

… and proofing

## Description

Closes #6873 

## Testing done

Visual Testing

## Screenshots

Pending...

## QA steps

As an administrator
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

2021-11-24 18:50 UTC, kevwalsh commented
It doesn't say there's a conflict here in github, but i think there's still a conflict, cause [on Tugboat](https://tugboat.vfs.va.gov/619d15e0690c686fc5897dc0) i'm seeing this

<img width="1288" alt="VACMS-6873__show_related_non-clinical_services_on_top_task_edit_forms…_«_CMS_Pull_Request_Environments_«_CMS_«_My_Projects_«_Tugboat" src="https://user-images.githubusercontent.com/643678/143297179-80fa00b4-c961-4bc5-b67f-0ff3cb7f51bd.png">

2021-12-01 15:09 UTC, JayDarnell commented
@kevwalsh I will try to get this rebased today. I'm thinking of writing a patch for the viewfield module to display the view in node edit. There is a setting in this module to set a default and not allow it to be changed. I'd like to add a conditional checkbox that only displays if the default and do not allow edits is selected to then show the chosen view on node edit.

2021-12-10 03:57 UTC, JayDarnell commented
This pull request accomplishes the goals outlined in the linked issue. Further iterations will be needed to properly format the contents of the view itself and where it should live within the node edit and node view displays.

2021-12-10 19:35 UTC, swirtSJW requested changes
Nice work on this issue  and patch @JayDarnell 
 https://www.drupal.org/project/viewfield/issues/3252356

Just a couple things needed to get tests passing and remove trailing spaces.

After tests are passing will run through QA steps.

2021-12-10 19:35 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
> -        - revision_log
Klinger is making a run for it.  You have to add this line back in by hand.

2021-12-10 19:35 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
> -        - revision_log
AWOL

2021-12-10 19:35 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
> -        - revision_log
AWOL

2021-12-10 19:35 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
> +  @dst @field_type @content_type_fields @dstfields @vamc
Need to set your editor to trim trailing spaces on .feature.

2021-12-10 20:01 UTC, JayDarnell commented on config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
> -        - revision_log
Adding back in

2021-12-10 20:01 UTC, JayDarnell commented on config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
> -        - revision_log
Adding back in

2021-12-10 20:01 UTC, JayDarnell commented on config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
> -        - revision_log
Adding back in

2021-12-10 20:15 UTC, JayDarnell commented on tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
> +  @dst @field_type @content_type_fields @dstfields @vamc
I believe I've sorted this at least in the short term.

2021-12-10 20:30 UTC, JayDarnell commented
Updated behat tests, readded config items accidentally removed by `lando drush cex`, rebased to remove merge conflicts.

2021-12-14 19:15 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
> +@api @jaytest
No Jay

2021-12-14 22:54 UTC, swirtSJW approved these changes
Code looks good.  
Node view 
![image](https://user-images.githubusercontent.com/5752113/146092300-fc5777a1-a146-41e0-98a5-dbc5248ed518.png)


Node edit 
![image](https://user-images.githubusercontent.com/5752113/146092312-1fe0d35f-bf7f-4bb2-b02d-f7777f8347ce.png)

No notices or anything in watchdog.

Nice work Jay.

2021-12-14 22:55 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/146092432-ad22bb55-9715-4563-a6cc-a18139f88d9a.png)

2021-12-14 22:55 UTC, merged