VACMS-7011 move help text above long text fields
department-of-veterans-affairs/va.gov-cms pull request #7038
Opened 2021-11-23 16:54 UTC by msbtterswrth

## Description

Relates to #7011 .

## Testing done
Visited a node edit page to see that the description for long text fields was not under the title and about the field.

## Screenshots
![image](https://user-images.githubusercontent.com/8375335/143068296-87ef7a2f-2305-459d-bc7c-523543bb6b9d.png)

## QA steps

As a cms editor I can:
1. Visit a node edit page (/node/add/page) and view the help text (description) is now under the field title but above the field.
2. Then validate Acceptance Criteria from issue
- [ ]  We have a POC set that moves the help text for textareas above the field for all textarea fields 
- [ ]  design review (spacing/hierarchy, unintended impacts, etc)
- [ ]  change management review
- [ ]  Textcounters remain below the field

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-11-23 17:17 UTC, ethanteague requested changes

2021-11-23 17:17 UTC, ethanteague commented on composer.json
> +        "drupal/twig_tweak": "^3.1",
Let's pull twig_tweak out, @msbtterswrth

2021-11-23 17:17 UTC, ethanteague commented on config/sync/core.extension.yml
> +  twig_tweak: 0
Let's pull twig_tweak out, @msbtterswrth

2021-11-23 17:17 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/js/script.js
> -        var targetTypes = ["health_care_local_facility", "vet_center"];
This is my bad - can you add this back, here, and in script.es6.js, @msbtterswrth ?

2021-11-23 19:39 UTC, kevwalsh commented
i'm guessing that composer.lock conflict is what's preventing Tugboat from standing up a PR environment?  
Can't... wait... to... review... this.

@msbtterswrth Because this is _such_ an awesomely sweeping change, i think we need more exhaustive QA steps. According to the audit that informed the ACs, there are 54 textarea fields that should be affected by this. I don't think we need to check every single one, but a solid sample based on a variety of criteria... rich text or not rich text, nested or not nested, etc, etc.

Also, i think we should do design review. @suzanne-gray expressed some excitement here about this change, which is kind of like volunteering for that 😆 .

2021-11-24 02:12 UTC, kevwalsh commented
I created [a followup for "Text (plain)" fields](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7048).

2021-11-24 15:16 UTC, ethanteague requested changes

2021-11-24 15:16 UTC, ethanteague commented on config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
> -        - revision_log
We need to add this back in, @msbtterswrth

2021-11-24 15:16 UTC, ethanteague commented on config/sync/core.entity_form_display.node.landing_page.default.yml
> -        - revision_log
Need to add this back, @msbtterswrth

2021-11-24 15:16 UTC, ethanteague commented on config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
>    promote: true
I don't think we want to unhide these, @msbtterswrth

2021-11-24 15:16 UTC, ethanteague commented on config/sync/core.entity_form_display.node.landing_page.default.yml
> -  field_related_office: true
Don't think we want to take this out, @msbtterswrth

2021-11-24 15:39 UTC, ethanteague requested changes
@msbtterswrth seems like the only files we should see in this diff are 

- `text-format-wrapper.html.twig`
- `script.es6.js`
- `script.js`

2021-11-24 15:40 UTC, msbtterswrth commented on config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
>    promote: true
I've already migrated the content on production to use the new fields. Kelson's PR for updating the frontend should go out today i think. We'll have a separate pr to remove the old fields, but IMO we can have both visible for now as we shift to the new experience.

2021-11-24 15:40 UTC, msbtterswrth commented on config/sync/core.entity_form_display.node.landing_page.default.yml
> -  field_related_office: true
I've already migrated the content on production to use the new fields. Kelson's PR for updating the frontend should go out today i think. We'll have a separate pr to remove the old fields, but IMO we can have both visible for now as we shift to the new experience.

2021-11-24 15:45 UTC, kevwalsh commented on config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
>    promote: true
i agree that unhiding them and having "duplicate" fields is OK, mainly because of the content types in discussion. But this definitely needs to be in a separate PR.

2021-11-24 15:45 UTC, kevwalsh commented on config/sync/core.entity_form_display.node.landing_page.default.yml
> -  field_related_office: true
Same as above.

2021-11-24 15:49 UTC, kevwalsh requested changes
<details><summary>Help text is still below the field</summary>


<img width="841" alt="Create_Benefits_Hub_Landing_Page___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/143270657-b368074c-12e8-4e3c-b301-c609e7ddaddd.png">


</details>

I randomly clicked around (again, see my comment about needing better QA instructions) and found at least one "Textarea (long)" field that didn't get the new treatment, on https://pr7038-z96inxdfdtw9vei6id1wrszjzbxuvysa.ci.cms.va.gov/node/add/landing_page

2021-11-25 23:38 UTC, ethanteague commented
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7066

2021-11-25 23:38 UTC, closed without merging