VACMS-6640 Update services table to match figma spec.
department-of-veterans-affairs/va.gov-cms pull request #7065
Opened 2021-11-25 22:03 UTC by ethanteague

## Description
Relates to #6640

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/143503153-0a909027-c32a-4a85-8095-d4f77fcf5c23.png)

## QA steps
 - [ ] As an administrator, go to `node/3840/edit` and visually verify table has new Required/Optional column.
 - [ ] Visually verify items marked as required do not have delete buttons
 - [ ] Visually verify table headers match screenshot
 - [ ] Visually verify services are alpha sorted
 - [ ] Visually verify table drag and drop column is not present
 - [ ] Edit a service, save, and confirm the save is changed and errors are not thrown.

2021-11-26 20:29 UTC, kevwalsh commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +  public function checkIfServiceRequired($service) {
i don't like the idea of hard-coding this, because the single source of truth should be the Service taxonomy term, which has a required boolean.

2021-11-26 20:34 UTC, kevwalsh commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +      $form['field_health_services']['widget']['entities']['#table_fields']['label']['label'] = $this->t('Services offered at :title', [':title' => $node_title]);
This is great, but i guess i wonder how scaleable this is. 

Say we want to drop the node title into other labels, in other places. Will we need this much field instance and widget-specific code? Is it worth this much custom code right now, if (and it's a big if) there's an opportunity to do this more generically later?

2021-11-26 20:41 UTC, EWashb commented
@ethanteague everything looks like the figma design...great work! However, I was not able to edit the service. "Edit" wasn't clickable for me, so I couldn't do the last QA step.

2021-11-26 21:55 UTC, ethanteague commented
> @ethanteague everything looks like the figma design...great work! However, I was not able to edit the service. "Edit" wasn't clickable for me, so I couldn't do the last QA step.

You probably were viewing a locked page - looks like Kev was testing right before you, so you will need to click the break lock link on the top of the form. You should be able to edit after that, @EWashb

2021-11-26 21:58 UTC, ethanteague commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +      $form['field_health_services']['widget']['entities']['#table_fields']['label']['label'] = $this->t('Services offered at :title', [':title' => $node_title]);
Meh. Not too worried about it. If we wanna reuse this, no biggie to create a reusable method that we call as needed. That said, this is a pretty common pattern that we use / have in use all over the place.

2021-11-26 21:58 UTC, ethanteague commented on docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
> +  public function checkIfServiceRequired($service) {
That's my bad. Forgot about that bool. Updated.

2021-11-28 00:11 UTC, kevwalsh requested changes
Two things i saw after comparing to the design.

- [ ] Sort by Required, then by alpha. 
- [ ] Remove the `"[Vet Center name] - "` from the first column. We want to keep these service node titles as they are, but have the node titles appear simpler in this context, with just the taxonomy term name. 

<img width="992" alt="Edit_Vet_Center_Nashville_Vet_Center___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/143724040-152cebdb-06f8-4646-97af-d10e544cf95f.png">

2021-11-28 16:57 UTC, ethanteague commented
> Two things i saw after comparing to the design.
> 
> * [ ]  Sort by Required, then by alpha.
> * [ ]  Remove the `"[Vet Center name] - "` from the first column. We want to keep these service node titles as they are, but have the node titles appear simpler in this context, with just the taxonomy term name.
> 

Thanks for catching these, @kevwalsh. Updated :+1:

2021-12-01 20:38 UTC, swirtSJW requested changes
Seems like this may have broken the winno-ing logic as I can still select a service that is already present and required.   And after adding it, the service shows as optional rather than required.
![image](https://user-images.githubusercontent.com/5752113/144310990-f4326956-8cf1-4c3f-ac2b-645077257335.png)

2021-12-01 20:59 UTC, ethanteague commented
> Seems like this may have broken the winno-ing logic as I can still select a service that is already present and required. And after adding it, the service shows as optional rather than required. 

Thank you for catching that, @swirtSJW ! Updated :+1:

2021-12-02 22:06 UTC, swirtSJW reviewed
Since this is a sprint goal.   Lets chat

2021-12-02 22:39 UTC, swirtSJW commented on docroot/themes/custom/vagovadmin/vagovadmin.theme
> +  $form = $variables['form'];
@ethanteague  I added a commit to move the long bunch of code to a function.   It should really be broken down further, but we can come back to it.

2021-12-02 22:46 UTC, swirtSJW requested changes
Adding a new service works.
Winnoing logic works.
However, the edit and remove buttons don't do anything.
![image](https://user-images.githubusercontent.com/5752113/144515243-d8bd6b59-6464-42de-8249-ac74d848802c.png)

2021-12-02 22:49 UTC, swirtSJW commented
I added testing the edit and remove buttons to the QA steps.

2021-12-03 01:33 UTC, swirtSJW commented
@ethanteague  @kevwalsh  Is it desired/expected that the the edit window jumps to the tip of the list rather than being inline?
![image](https://user-images.githubusercontent.com/5752113/144529588-d0adb89e-d276-47af-b0d6-470b55b98e0f.png)

2021-12-03 01:39 UTC, swirtSJW commented
If I edit two services simultaneously, canceling one, will cancel all.   This results in data loss.
![image](https://user-images.githubusercontent.com/5752113/144530096-7a325d5b-1f1b-4aa4-9b20-88ceb73c9389.png)

2021-12-03 01:41 UTC, swirtSJW requested changes
Edit and cancel now work.   But cancel, cancels all edits... leading to data loss.

2021-12-03 01:59 UTC, swirtSJW commented
@EWashb @kevwalsh   I have some  concerns about this design that may not have to block this PR but we might want to address soon.  

1 . I can not tell from this display which services are published and which are not.
![image](https://user-images.githubusercontent.com/5752113/144531040-1626fdbf-2286-4239-85af-1278b4473e8e.png)

2.  When I add a service, it is not published and I can only publish it through my section dashboard
![image](https://user-images.githubusercontent.com/5752113/144530676-a0a7a048-45aa-4ffe-b122-e935bc3a1d65.png)
3.  If I make an inline edit to a published service but I save the vetccenter changes as draft.... I have no idea what I just did to revisions and I have no idea what is now published within the service edit. 
Looks like it goes straight through to published 
![image](https://user-images.githubusercontent.com/5752113/144531425-7524e6c3-2686-45cf-8f69-b46649cd3e8c.png)
4.  Revision log message is really confusing because it did not go through a proper save so the log message is reused from previous.
![image](https://user-images.githubusercontent.com/5752113/144531705-54577d44-16c9-479f-87de-35fd381ec39a.png)

I suggest the edit link does not take to inline edit but takes to service node edit.

2021-12-03 02:24 UTC, ethanteague commented
> If I edit two services simultaneously, canceling one, will cancel all.   This results in data loss.
> 
> ![image](https://user-images.githubusercontent.com/5752113/144530096-7a325d5b-1f1b-4aa4-9b20-88ceb73c9389.png)
> 
> 
> 
> 

This will take a while to figure out, @swirtSJW @kevwalsh - seems like there is a lot here that needs to be addressed, so gonna leave this one alone until we discuss further.

2021-12-03 02:49 UTC, EWashb commented
I agree- this seems to be adding more complex issues and I wouldn't be comfortable introducing those for the sake of the intended design. Definitely warrants more discussion @ethanteague @swirtSJW @kevwalsh

2021-12-03 03:33 UTC, kevwalsh commented
> @ethanteague @kevwalsh Is it desired/expected that the the edit window jumps to the tip of the list rather than being inline?

Yeah this is definitely not ideal.

> If I edit two services simultaneously, canceling one, will cancel all. This results in data loss.

I just reproduced this on staging, not a regression introduced by this PR.  I'm curious is this is specific to our configuration of IEF, or an IEF problem more generally. 

> When I add a service, it is not published and I can only publish it through my section dashboard

I just reproduced this on staging, not a regression introduced by this PR.

Turns out this change happened in an earlier iteration, but hasn't been caught/realized, probably because of the nature of the launch runbooks for each Vet Center. At some point, the content moderation field got dropped from the inline form, but the ramifications of that were not caught. Either we need to:

1. bring the content moderation field to the IEF form, or
2. we need to make these IEF nodes more "paragraph-like", where their published status is somehow inherited from the parent node's published status. 

Number 1 is easier, but I like #2. Still, it probably belongs in a separate issue. 

====

My sense is that if we can address the window jumping around, we can still get this done this sprint. But we should really prioritize addressing these two other issues, particularly the content moderation one.

2021-12-03 03:42 UTC, ethanteague commented
@kevwalsh the jump is being caused by the alpha sort logic introduced in this task. Another tough one to figure out. Apologies for being a downer, just don't know how to prevent the jump when we need to sort services alphabetically.

2021-12-03 03:44 UTC, kevwalsh commented on config/sync/user.role.content_editor.yml
> +  - 'delete any vet_center_facility_health_servi content'
i think this permission, if it's needed (see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7144), should be moved to user.role.vet_center_content_creator.yml instead. Not a big deal, since it's all workbench access controlled anyway. but it's a more product-oriented role.

2021-12-03 03:45 UTC, kevwalsh commented
> @kevwalsh the jump is being caused by the alpha sort logic introduced in this task. Another tough one to figure out. Apologies for being a downer, just don't know how to prevent the jump when we need to sort services alphabetically.

what if this opened in a modal? modals create their own challenges, but that was in an earlier "blue sky" design by Kauff.

2021-12-03 03:48 UTC, ethanteague commented
> > @kevwalsh the jump is being caused by the alpha sort logic introduced in this task. Another tough one to figure out. Apologies for being a downer, just don't know how to prevent the jump when we need to sort services alphabetically.
> 
> 
> 
> what if this opened in a modal? modals create their own challenges, but that was in an earlier "blue sky" design by Kauff. 

That's an interesting idea, @kevwalsh - I'll give that a whirl in the am 👍

2021-12-03 03:52 UTC, kevwalsh commented
I created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7144 and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7145 for the two issues Steve found, that are not regressions.

2021-12-05 03:23 UTC, ethanteague commented
@kevwalsh @swirtSJW - I figured out a way to stop the form from not loading inline, and updated the pr with said logic.

2021-12-06 14:40 UTC, swirtSJW approved these changes
QA passed.

Nice work @ethanteague

2021-12-06 14:40 UTC, merged