VACMS-7011: Move help text below labels.
department-of-veterans-affairs/va.gov-cms pull request #7066
Opened 2021-11-25 23:37 UTC by ethanteague

## Description
Relates to #7011

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/143507847-138f3c86-3387-4a25-a93a-61de2cd59ce5.png)
![image](https://user-images.githubusercontent.com/2404547/143507849-687be463-d933-4c31-a97b-1904df71120c.png)

## QA steps
 - [ ] As an administrator, go to `node/add/page` & `node/add/landing_page` and visually verify help text appears below labels for all text and wysiwyg form fields.

2021-11-25 23:44 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/js/script.js
> -        var targetTypes = ["health_care_local_facility", "vet_center"];
Pulled this out without compiling in a previous pr. Removal expected.

2021-11-26 16:44 UTC, kevwalsh commented
**Overall approach and QA challenges**

I ❤️ that the scope of this is growing. But it also means we need closer QA and design review. 

Originally, this was just going to be fields marked "Text (formatted, long)" and Text "(plain, long)". Now it includes all "List (text)", "Entity reference", and a bunch of others. 

I just did some comparison of prod and this PR environment, just of the fields types present on Content types (not on paragraphs, which may have some field types that paragraphs do not) and this is what i found to be changing. 


<img width="1425" alt="CMS_DS_Component___Pattern_inventory__Field_types_-_Airtable" src="https://user-images.githubusercontent.com/643678/143605071-7f406d75-98d4-4c78-a968-5eca4cbcfe3f.png">

It just occurred to me that this may not be by Field type, but may be a bit more nuanced, by the Field widget or some other attribute of each field instance. Like for entity references, there a dozen different field formatters: 

> Select list, Entity browser, Inline entity form - Complex, Autocomplete, Entity Browser - Table, Media library, Inline entity form - Complex - Table View Mode, Check boxes/radio buttons.

I didn't check all of these. 

It's also unclear how many core field-type-things, not known to our Drupal Spec Tool, like URL alias, may be affected by this. @ethanteague you might have a sense of how far-ranging this could be. 




**Design review**

Getting a rough sample of before/after would probably be helpful for design review. 

My sense is that the help text needs a bit more `padding-bottom`, but there may be other things to watch for. 


**Change management** 

I'd like to get @xiongjaneg's  eyes on this to help determine the impact this might have on users, not to mention that this will immediatlely "date" some existing training and KB materials. Not as much as Claro will. 

**Some specific issues i've seen, not necessarily deal-breakers**


<details><summary>Phone number fields</summary>

We could solve this by dropping the extension below, but there may be other ways.

<img width="473" alt="Cursor_and_Create_VAMC_Facility_Health_Service___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/143601926-6fee4468-f52f-4fe9-aa71-e3e0b12e63a6.png">


</details>

2021-11-29 15:21 UTC, swirtSJW reviewed
Code looks fine but the QA steps seem a little light for this sweeping of a change.

2021-11-29 15:24 UTC, ethanteague commented
> Code looks fine but the QA steps seem a little light for this sweeping of a change.  

Agreed buddy. I think we need a swarm session.

2021-11-30 14:20 UTC, kevwalsh commented
A few followups from Thursday 9:15am

- [ ] Padding
- [ ] Check all the widget types from [this airtable(https://airtable.com/appKn8xeWg0SkIphM/tblyDT3IsWT9g4V3h/viwOB6i525yBSDZFF?blocks=hide), like IEF for Entity reference
- [ ] Check Integer and office hours (may need help text to test) 
- [ ] Phone number extension wrap
- [ ] Date field (see https://prod.cms.va.gov/node/add/va_form) 
- [ ] Improve comments in the code for how the patterns work and relate to field or widget types

2021-12-01 12:44 UTC, swirtSJW requested changes
Overall good.  One sustainability request.

2021-12-01 12:44 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/js/script.es6.js
> +          if (
Nested nested ifs are a bit long.  Can we compartmentalize each one to an appropriately named function that does the checking and alters if true
example: 
alterHelpTextLocationOnDateField
alterHelpTextLocationOnTextField
alterHelpTextLocationOnLongTextFullHtmlField
alterHelpTextLocationOnLongTextPlainField ...

It makies the code easier to follow... especially on ES6 which ends up with no comments.  Makes it less east to break, and more testable.

2021-12-01 12:49 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/js/script.es6.js
> +          if (
Good thinking, @swirtSJW - will do :+1:

2021-12-01 12:54 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/js/script.es6.js
> +          if (
Think I'll move this out into it's own library, as well.

2021-12-01 15:16 UTC, msbtterswrth requested changes
@ethanteague can we make one TINY change? I think the spacing is too much between the label and the description now, let's adjust it to `margin: 0 0 10px 0`.

![image](https://user-images.githubusercontent.com/8375335/144261073-cd294f31-47ce-455b-a6c9-e79f012582f5.png)

2021-12-01 18:29 UTC, ethanteague commented
Updated, @msbtterswrth @swirtSJW :+1:

2021-12-01 21:25 UTC, msbtterswrth approved these changes
Looks perf! Great job!

2021-12-02 12:33 UTC, swirtSJW reviewed
super minor fixes i am going to apply.

2021-12-02 12:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/js/help_text_treatments.es6.js
> +      alterHelpTextLocationOnParagraphsExperimentalWidget(textareaDescriptions);
```suggestion
      // Get help texts.
      const textareaDescriptions = context.querySelectorAll(".description");
      alterHelpTextLocationOnDateField(textareaDescriptions);
      alterHelpTextLocationOnTextField(textareaDescriptions);
      alterHelpTextLocationOnLongTextPlainField(textareaDescriptions);
      alterHelpTextLocationOnLongTextFullHtmlField(textareaDescriptions);
      alterHelpTextLocationOnParagraphsExperimentalWidget(textareaDescriptions);
```
With the good naming of the methods that you did, these comments are unnecessary.

2021-12-02 12:33 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/js/help_text_treatments.js
> +      alterHelpTextLocationOnParagraphsExperimentalWidget(textareaDescriptions);
```suggestion
      var textareaDescriptions = context.querySelectorAll(".description");
      alterHelpTextLocationOnDateField(textareaDescriptions);
      alterHelpTextLocationOnTextField(textareaDescriptions);
      alterHelpTextLocationOnLongTextPlainField(textareaDescriptions);
      alterHelpTextLocationOnLongTextFullHtmlField(textareaDescriptions);
      alterHelpTextLocationOnParagraphsExperimentalWidget(textareaDescriptions);
```

2021-12-02 12:34 UTC, swirtSJW approved these changes
Nice work.

2021-12-02 16:06 UTC, swirtSJW approved these changes

2021-12-02 16:06 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/144458720-6b38ed6f-6371-4e3f-91d5-446dcdf00b26.png)

2021-12-02 16:07 UTC, merged