VACMS-5492 - disable event cost field and update default value to free
department-of-veterans-affairs/va.gov-cms pull request #7122
Opened 2021-12-01 19:36 UTC by msbtterswrth

## Description

Relates to #5492 .

## Testing done
Created an event and confirmed the 'cost' field was hidden.

## Screenshots
current: 
![image](https://user-images.githubusercontent.com/8375335/144301223-779a96aa-e22a-4e1f-9414-d96afb5ba1a6.png)

updated:
![image](https://user-images.githubusercontent.com/8375335/144301074-55c448d9-e5ef-4bfe-b307-7b1cae293d73.png)

## QA steps

As cms editor I can:
1. Create a new event (/node/add/event) and verify that the cost field does not appear in the form under the registration section.
1. View the field settings for cost (/admin/structure/types/manage/event/fields/node.event.field_event_cost) and confirm the help text was updated and the default value set to 'free'
2. Then validate Acceptance Criteria from issue
- [x] Make "Free" the default value
- [x] Disable the field for non-content Admins (updating to disabled for ALL admins)
- [ ] Remove textcounter (i left this in since we're just disabling it completely)
- [x] Help text should read "All VA events are free"

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-12-01 20:59 UTC, kevwalsh requested changes
One of the ACs is 

> Help text should read "All VA events are free"

But i think this could be improved to say 

"All events on VA.gov are free."

Can you add that to the fieldgroup help text? 

<details><summary>Screenshot</summary>


![Cursor_and_144301074-55c448d9-e5ef-4bfe-b307-7b1cae293d73_png__2745×1708_](https://user-images.githubusercontent.com/643678/144312941-cf882976-62db-41b2-b281-12031e8dc341.png)

</details>

2021-12-01 21:17 UTC, msbtterswrth commented
@kevwalsh updated: 
![image](https://user-images.githubusercontent.com/8375335/144315414-5298d695-f3f6-435a-9ad0-71240b382ff1.png)

2021-12-02 03:22 UTC, swirtSJW requested changes
One fix needed.

2021-12-02 03:22 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.event.default.yml
> -        - revision_log
Klinger is trying to go AWOL again. ;)
 Please add this back.   
Note: git add -i    is your friend when encouting changes to form_display.node.*.default.yml files.

2021-12-02 15:00 UTC, msbtterswrth commented on config/sync/core.entity_form_display.node.event.default.yml
> -        - revision_log
i swore i fixed this in my last commit, but alas it didn't go up. do we know why this ALWAYS disappears whenever you touch a node?

2021-12-02 15:35 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.event.default.yml
> -        - revision_log
See thread  https://dsva.slack.com/archives/CT4GZBM8F/p1636469291454500

2021-12-03 02:41 UTC, swirtSJW approved these changes
Looks good.

One odd editorial issue: showing event is free in node view, but not having a place to set it.
![image](https://user-images.githubusercontent.com/5752113/144535738-c3bcd530-395d-4e9d-a415-ae57a735e455.png)

2021-12-03 13:54 UTC, kevwalsh commented on config/sync/core.entity_form_display.node.event.default.yml
> +        description: 'All events on VA.gov are free.'
@swirtSJW here's the diff that addressed my request.

2021-12-03 13:54 UTC, kevwalsh approved these changes

2021-12-03 14:01 UTC, kevwalsh commented
> Looks good.
> 
> One odd editorial issue: showing event is free in node view, but not having a place to set it. ![image](https://user-images.githubusercontent.com/5752113/144535738-c3bcd530-395d-4e9d-a415-ae57a735e455.png)

Maybe not ideal, but at least it mirrors the FE experience

2021-12-03 14:17 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/144617259-3a1071e3-3330-4d9b-8bd2-0c38ac5eb6e5.png)

2021-12-03 14:17 UTC, merged