VACMS-000: Fix broken standalone page toggle handling on submission.
department-of-veterans-affairs/va.gov-cms pull request #7139
Opened 2021-12-02 20:41 UTC by ethanteague

## Description
See https://dsva.slack.com/archives/CDHBKAL9W/p1638380351100500
When users submit forms that have sections turned off via booleans, submissions fail when items contained in the turned off sections are required. This code was removed in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6783. This pr restores, and adds an additional check for buttons paragraphs.

## Testing done
Visual / behat.

## QA steps
 - [ ] As an administrator, go to `node/37432/edit` and submit form, visually verifying that submission is successful without clicking on the standalone page bool.
 - [ ] As an administrator, go to `node/add/campaign_landing_page` fill in required fields, but do not toggle on any of the optional items in the fieldsets - visually verify that form submission does not fail silently, or require items in any of the turned off toggle fields.

2021-12-03 03:26 UTC, swirtSJW requested changes

2021-12-03 03:26 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
Major:  Lots of nested loops and control structures piled into a hook_form_alter that is already 100+ lines long.    At minimum this should be put in a nice descriptive function that describes what it is doing to whom.  

Functions are easy to read and debug.  Don't be afraid to use them.  Ifs piled on loops are nightmares. 

This code also does not seem to be narrowed in scope or even describing what content types we are targeting.

2021-12-03 03:26 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    if (empty($form_state->getValue('field_primary_category'))) {
```suggestion
  }
  elseif ((!empty($form_state->getValue('field_standalone_page')['value'])) &&
    (empty($form_state->getValue('field_primary_category')))) {
```
Minor: The second if does not need to be evaluated if 'value' was 0

2021-12-03 03:34 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
> Major:  Lots of nested loops and control structures piled into a hook_form_alter that is already 100+ lines long.    At minimum this should be put in a nice descriptive function that describes what it is doing to whom.  
> 
> 
> 
> Functions are easy to read and debug.  Don't be afraid to use them.  Ifs piled on loops are nightmares. 
> 
> 
> 
> This code also does not seem to be narrowed in scope or even describing what content types we are targeting.


Apologies, @swirtSJW - This is code Kaise wrote that was removed in 5439 and ended up breaking the bool hidden content checks, so I just restored (with an augmentation to account for the buttons paragraph) without giving refactoring much thought.

2021-12-03 12:31 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  }
Ahhh I see.   Sorry I should have never let that in the first time around.   Can you move it  into a function and we'll call it a day?

2021-12-06 17:11 UTC, swirtSJW approved these changes
QA pass

2021-12-06 17:12 UTC, merged