Vacms 2043 connect with us field
department-of-veterans-affairs/va.gov-cms pull request #7180
Opened 2021-12-06 22:15 UTC by msbtterswrth

## Description

Relates to #7168 .

## Testing done
Edited a CLP and saw the old field for connect with us was removed. Viewed the section taxonomy and saw the old connect with us fields were removed.

## Screenshots
![image](https://user-images.githubusercontent.com/8375335/144931034-563238ce-72c9-4736-b4b9-a00c560c52a0.png)
![image](https://user-images.githubusercontent.com/8375335/144931179-fac9c8b9-093f-43cb-a34c-805a19528004.png)

## QA steps

As a cms editor I can
1. edit a campaign landing page (node/15051/edit) and see the old fields removed
1. view the section taxonomy manage fields (/admin/structure/taxonomy/manage/administration/overview/fields) and see there are only two fields (description and product)
1. Then validate Acceptance Criteria from issue
- [ ]  Delete social media link field, connect with us link field and email updates link text and url from section taxonomy.
- [ ] Delete the 'add a connect with us panel' from CLP

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-12-07 13:22 UTC, kevwalsh commented on config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
> +        - field_related_office
i'm really confused. this change already seems to be on prod and staging.  Prod maybe made sense.

<img width="1043" alt="Cursor_and_Edit_Campaign_Landing_Page_Veterans_Experience_Action_Center___VA_gov_CMS_and_VACMS-000__Update_list_of_content_served_from_Drupal__by_kevwalsh_·_Pull_Request__6793_·_department-of-veterans-affairs_va_gov-cms" src="https://user-images.githubusercontent.com/643678/145036871-03ffda7a-e410-4315-a4b0-9e068eec4475.png">

2021-12-07 14:45 UTC, kevwalsh requested changes
Change "Related office" to "Add a "Connect with us" panel" on block
Change "Related office" to "Add a "Connect with us" block" on block
Create follow up issue for Entity reference view where user can only select from Veterans Health Administration, Veterans Benefits Administration, National Cemeteries Administration, or Veterans Affairs Central Office

2021-12-17 03:09 UTC, swirtSJW requested changes
Something seems odd.  There is a lot of stuff in here that I would not expect to see in a field removal pr.  It leads me to suspect a bad rebase or 2 along the way.   There are 24 commits and a lot of them have the exact same commit message which makes me think some rebases went wild.
![image](https://user-images.githubusercontent.com/5752113/146482683-687c5239-9a12-4e03-bc48-c6d2a6355401.png)

2021-12-17 03:17 UTC, swirtSJW commented
@msbtterswrth  My guess from looking at the wild commit history is that you are doing something along the lines of rebasing locally  merging main locally, Then getting the notice from git that you are out of sync on your remote and then you are pulling that, as a merge which is creating these repeated looping time cycles.  

Locally you should be rebasing on your local main, then force pushing to your remote.    Setting up your git defaults to always track your remote branches by rebase fast forward only is not a bad idea either.

2021-12-17 14:11 UTC, msbtterswrth commented on config/sync/core.extension.yml
> +  va_gov_backend_http_client: 0
This was something merged in from main afaik

2021-12-17 14:25 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/views.feature
> +| Content Entity Reference Source | Entity Reference: Main Offices | entity_reference_7 | Entity Reference |
Yes i included a fix in this branch to narrow the original taxonomy field by creating a view. Kev had added that as an ac for a separate ticket, but i included it in this pr to hopefully make things smoother. That was before we realized the tests were gonna fail though.

2021-12-17 14:26 UTC, msbtterswrth commented on config/sync/views.view.content_entity_reference_source.yml
> +      arguments:
related to me changing it to be a view filtered reference field.

2021-12-17 14:26 UTC, msbtterswrth commented on config/sync/views.view.content_entity_reference_source.yml
> +        title_1:
likely related to me changing it to be a view filtered reference field.

2021-12-17 14:30 UTC, msbtterswrth commented
@swirtSJW the crazy history here is due to me being ocd about clicking the 'this branch is out of date with main' button in an attempt to get tests to work at various points of this ticket's lifecycle. I have learned my lesson though and shan't push it unless i REALLY REALLY need to.

2021-12-17 14:47 UTC, ethanteague commented
> @swirtSJW the crazy history here is due to me being ocd about clicking the 'this branch is out of date with main' button in an attempt to get tests to work at various points of this ticket's lifecycle. I have learned my lesson though and shan't push it unless i REALLY REALLY need to.

@msbtterswrth It's fine to update the branch frequently in the pr by clicking the button. Just pull from main, and not your remote (pr) branch when you update your local. It's also a lot cleaner / easier on the history front to use a rebase strategy instead of a straight merge. I do business like this:
`git remote update`
`git pull --rebase origin main`

2021-12-17 14:50 UTC, msbtterswrth commented
@ethanteague i do occasionally merge main back into my local branch but you're saying that should be a rebase instead?

2021-12-17 14:50 UTC, swirtSJW requested changes

2021-12-17 14:50 UTC, swirtSJW commented on config/sync/views.view.content_entity_reference_source.yml
> +        title_1:
I don't see that change covered by your QA steps and it is not mentioned anywhere in #7168
If there are things going "off issue" please note them in the issue  or in the PR.   They should not be mysteries for a reviewer to figure out.

2021-12-17 14:50 UTC, swirtSJW commented on config/sync/core.extension.yml
> +  va_gov_backend_http_client: 0
If it was merged in from main, it should not be appearing as a change.  It would be the same as main.
This module is not enabled on prod
![image](https://user-images.githubusercontent.com/5752113/146562075-d1ffe956-a2e6-4f70-9acb-b06b4bcf3a81.png)

Unless you are intentionally enabling it, it should not be in your PR.

2021-12-17 14:50 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/views.feature
> +| Content Entity Reference Source | Entity Reference: Main Offices | entity_reference_7 | Entity Reference |
Please add QA steps that cover this and a reference to that issue.  Mysteries slow me down.

2021-12-17 14:52 UTC, ethanteague commented
> @ethanteague i do occasionally merge main back into my local branch but you're saying that should be a rebase instead?

Yeah. Team rebase represent, @msbtterswrth 

I also think it's beneficial to squash commits into a pr into as few as possible. I'm a big fan of one or two (three max) commits per pr. To do this, I do:
`git rebase -i HEAD~5` with `5` being the number of commits you wanna go back to flatten. Once in the interactive rebase screen, add and `f` in front of each commit you wanna `fixup`, which means you want to push it into the commit above it. TLDR: replace the `p` in front of the commits you want to get eaten by the commit above it with an `f`

2021-12-17 14:59 UTC, swirtSJW commented
> the crazy history here is due to me being ocd about clicking the 'this branch is out of date with main' button in an attempt to get tests to work at various points of this ticket's lifecycle. I have learned my lesson though and shan't push it unless i REALLY REALLY need to.
![image](https://user-images.githubusercontent.com/5752113/146563826-b0eeb36b-4f55-411e-a79d-78513e5b3291.png)

@msbtterswrth   Clicking the button in the UI generates the things marked with the green arrow. Those are totally fine and of no issue.  The things with red arrows are something that is happening separate from that and are creating a bit of a mess and making the commit history look like Mr. Toad's Wild Ride.   There should not be duplicate commit messages and re-appearances of commits.   That means something with your local strategy is at play.

2021-12-17 21:03 UTC, msbtterswrth commented
closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7332

2021-12-17 21:03 UTC, closed without merging