VACMS-000: updated vscode config for ddev.
department-of-veterans-affairs/va.gov-cms pull request #7249
Opened 2021-12-09 22:55 UTC by timcosgrove

## Description

I found these adjustments necessary for ddev's xdebug support to communicate with vscode. Recommendations per ddev docs: 

https://ddev.readthedocs.io/en/stable/users/step-debugging/#vscode
https://ddev.readthedocs.io/en/stable/users/snippets/launch.json

2021-12-09 23:17 UTC, cweagans approved these changes

2021-12-10 17:08 UTC, indytechcook approved these changes

2021-12-10 19:18 UTC, swirtSJW requested changes
@timcosgrove  I pulled this locally and tried it with my vscode and  it broke xdebug under lando.

I have not yet gotten past an error with getting ddev running.  So I need to work on that.   But for now merging this in breaks xdebug vscode in lando.

2021-12-10 20:45 UTC, cweagans commented
@swirtSJW if you're using Lando, there's a different debug target to use: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/d5a8c0ddd3912b97043b66b4c2e682d1e6509836/.vscode/launch.json#L5

2021-12-10 22:43 UTC, swirtSJW approved these changes
Pulled it again and restarted vcode.   Worked this time. Must have been unrelated fail. Sorry for the noise.

2021-12-10 22:44 UTC, merged