WIP: VACMS-6874
department-of-veterans-affairs/va.gov-cms pull request #7292
Opened 2021-12-15 03:38 UTC by JayDarnell

## Description

Closes #6874 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-12-15 21:46 UTC, swirtSJW requested changes
Conflict has this not able to build a pr environment.

2021-12-15 21:46 UTC, swirtSJW commented on config/sync/views.view.non_clinical_services.yml
> +    display_title: 'Billing and Insurance Offices'
Sentence case?  (sorry if this has already been cleared)  I didn't see anything referenced in the issue related to switching away from sentence case.

2021-12-15 21:46 UTC, swirtSJW commented on config/sync/views.view.non_clinical_services.yml
> +      title: 'Billing and Insurance Offices'
sentence case

2021-12-15 21:46 UTC, swirtSJW commented on config/sync/views.view.non_clinical_services.yml
> +    display_title: 'Medical Records Offices'
sentence case

2021-12-15 22:54 UTC, swirtSJW requested changes
Can't perform second step of 
`Edit the node above, scroll to the bottom of the edit page - you should see a link to Add a billing and insurance office Click this link and a new tab should open up. Switch to this new tab.` 
The link to add is not there 
![image](https://user-images.githubusercontent.com/5752113/146277369-dfee84a1-24b3-4e2f-8439-a5377049a6d8.png)

2021-12-15 22:57 UTC, swirtSJW requested changes
Also looks like you need to remove the sort link from a column in the table that has no heading.    We actually shouldn't have a column that has no heading.   Thats a 508 thing that is separate form the link with no text.  
![image](https://user-images.githubusercontent.com/5752113/146277664-ba83cb85-af50-4007-8e87-591b587208fb.png)

The sortby on the edit column needs to be removed.  
![image](https://user-images.githubusercontent.com/5752113/146278296-55dd508c-acc0-4b6f-8564-a908ddaa974d.png)


This is actually a UI accessibility failure that node link report just happened to catch.  We are venturing into new ground where UI is existing on node view.... so node link report is going to catch some stuff that is UI related and not content.

2021-12-17 03:41 UTC, swirtSJW reviewed
Two issues off the bat 
![image](https://user-images.githubusercontent.com/5752113/146485243-2518fa83-3688-4b8c-accf-032f6921d057.png)

![image](https://user-images.githubusercontent.com/5752113/146485253-4fd67842-1272-4296-ab5f-3b027e887771.png)

I can address these while I fix  the merge conflict.

2021-12-17 05:07 UTC, swirtSJW approved these changes
These test out as working fine.  Nice solution Jay. 

There are two issues I see but I don't think either of them are blockers unless we want them to be.

1) When you click the "add office link" before you save the initial top task page, the pre-filling does not work.  
![image](https://user-images.githubusercontent.com/5752113/146491474-d8c27a68-0b42-4394-83d9-5e30ec9f0953.png)
I think there is probably no clean way around this without using a bunch of hacky js.  I am not sure it is worth it.   If it is worth it, we could either
 a) make JS update the link on blur of the office and field_administration field
 b) Not display that "add office" link until the node has been saved  (on node/edit as opposed to node add.

2) The other issue that troubles me is the flip flopping of language on what we are creating.
![image](https://user-images.githubusercontent.com/5752113/146491835-730b5b50-8c97-483d-9244-56f47bc06d12.png)
Is it an office, or a service?  Trying to refer to it as both... is going to be a nightmare for training and helpdesk, not to mention understanding.
![image](https://user-images.githubusercontent.com/5752113/146491938-a526838b-3292-468d-a4ff-f3f4174ccb45.png)
Every place else it is a service.

I'll marked this as approved, but leave it up to @kevwalsh 
as to whether we want to solve this now  or later.  My guess is probably later.

2021-12-17 05:17 UTC, kevwalsh commented
The UX writing work is being taken care of elsewhere. We will be moving away from tables, too. Spec coming in #6877.

2021-12-17 05:21 UTC, swirtSJW commented
Also a little concerned about 
![image](https://user-images.githubusercontent.com/5752113/146493246-870d6895-7696-4270-adab-358cf343b94c.png)

2021-12-17 05:35 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/146494581-770e2412-e2ab-42b3-9d0d-e8b6c76740db.png)

2021-12-17 05:36 UTC, merged

2021-12-17 14:47 UTC, JayDarnell commented
Yeah a lot of the view language was already present and I left it untouched given the fact it was all going to be reworked in the next steps.