VACMS-000: Refactor events location and registration fieldset to match figma interactions
department-of-veterans-affairs/va.gov-cms pull request #7305
Opened 2021-12-16 00:55 UTC by ethanteague

## Description
@kevwalsh - this is all the stuff we talked about today in @rachel-kauff 's Figma that is **not** recurring events. Not sure of task number(s).
cc: @swirtSJW @suzanne-gray 

See https://www.figma.com/file/3ysYRmbHbJ2d0auvFDiBgF/Event?node-id=0%3A1

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/146287603-4ce38eae-8228-4d1d-8c80-2fb16e9745df.png)
![image](https://user-images.githubusercontent.com/2404547/146287642-038f3b86-0971-460a-a3fb-28131ec8f726.png)

## QA steps
 - [ ] As an administrator, go to `/node/add/event` and fill in all required fields.
 - [ ] Check `Include registration information` and visually verify you see this: 
![image](https://user-images.githubusercontent.com/2404547/146287783-93848bb8-9b6c-467f-a372-fce3984efcd4.png)
 - [ ] Hover tooltip in Cost fieldset, and visually verify it reads `All events listed on Va.gov must be free`
 - [ ] Scroll down to `Location type` radios, click on each one, visually verifying that different fields are presented with each choice.
 - [ ] Save form, and verify node data is preserved.

2021-12-16 23:36 UTC, rachel-kauff requested changes
@ethanteague Did a design review end of day (so I may have missed or confused something), but found some things to be adjusted. Let me know if it would help to chat!

<img width="1223" alt="Screen Shot 2021-12-16 at 3 18 04 PM" src="https://user-images.githubusercontent.com/41017988/146464523-d6960dd1-373e-4373-a758-43a4fddec2b5.png">
<img width="1223" alt="Screen Shot 2021-12-16 at 3 19 41 PM" src="https://user-images.githubusercontent.com/41017988/146464526-08b5d22d-a26e-4db8-a4bf-e14a84797bf1.png">
<img width="1361" alt="Screen Shot 2021-12-16 at 3 23 10 PM" src="https://user-images.githubusercontent.com/41017988/146464528-62546d05-f20e-4fc8-80fe-1170e9a47fa6.png">
<img width="1361" alt="Screen Shot 2021-12-16 at 3 27 48 PM" src="https://user-images.githubusercontent.com/41017988/146464530-fcf6f4db-8fad-48ab-9654-25435e798f15.png">
<img width="1361" alt="Screen Shot 2021-12-16 at 3 32 51 PM" src="https://user-images.githubusercontent.com/41017988/146464532-edd36db2-51a9-4113-a508-df9562cb06ec.png">
<img width="1361" alt="Screen Shot 2021-12-16 at 3 34 36 PM" src="https://user-images.githubusercontent.com/41017988/146464533-dfc357b5-8e0b-4938-93d5-a6ec6aefde7c.png">

2021-12-16 23:45 UTC, ethanteague commented
> @ethanteague Did a design review end of day (so I may have missed or confused something), but found some things to be adjusted. Let me know if it would help to chat!
> 
> 
> 
> <img width="1223" alt="Screen Shot 2021-12-16 at 3 18 04 PM" src="https://user-images.githubusercontent.com/41017988/146464523-d6960dd1-373e-4373-a758-43a4fddec2b5.png">
> 
> <img width="1223" alt="Screen Shot 2021-12-16 at 3 19 41 PM" src="https://user-images.githubusercontent.com/41017988/146464526-08b5d22d-a26e-4db8-a4bf-e14a84797bf1.png">
> 
> <img width="1361" alt="Screen Shot 2021-12-16 at 3 23 10 PM" src="https://user-images.githubusercontent.com/41017988/146464528-62546d05-f20e-4fc8-80fe-1170e9a47fa6.png">
> 
> <img width="1361" alt="Screen Shot 2021-12-16 at 3 27 48 PM" src="https://user-images.githubusercontent.com/41017988/146464530-fcf6f4db-8fad-48ab-9654-25435e798f15.png">
> 
> <img width="1361" alt="Screen Shot 2021-12-16 at 3 32 51 PM" src="https://user-images.githubusercontent.com/41017988/146464532-edd36db2-51a9-4113-a508-df9562cb06ec.png">
> 
> <img width="1361" alt="Screen Shot 2021-12-16 at 3 34 36 PM" src="https://user-images.githubusercontent.com/41017988/146464533-dfc357b5-8e0b-4938-93d5-a6ec6aefde7c.png">
> 
> 

Appreciate you looking at this  - I know you are crazy busy. Will get cracking on it in the am. Ty, @rachel-kauff - you are awesome ❤️

2021-12-17 05:54 UTC, swirtSJW reviewed
@ethanteague  This all looks fantastic.  I do want to have a look at the FE and make sure that what the editor chooses in the various states, reflects what the FE results will be.

Also I am not sure if the PO has signed off on these changes in the FIGMA.

2021-12-17 05:54 UTC, swirtSJW commented on docroot/modules/custom/va_gov_events/src/EventSubscriber/EntityEventSubscriber.php
> +  public static function getSubscribedEvents(): array {
Minor but festering ;) I'd like to break this pattern we started   from the beginning where we put this last in the file.  This one function is like the table of contents for the file and we keep burying it just because the first one someone else wrote was at the bottom.

2021-12-18 18:49 UTC, ethanteague commented on docroot/modules/custom/va_gov_events/src/EventSubscriber/EntityEventSubscriber.php
> +  public static function getSubscribedEvents(): array {
Makes sense to me, @swirtSJW :+1: updated

2021-12-18 18:49 UTC, ethanteague commented
@rachel-kauff @swirtSJW updated per latest reviews :+1:

2021-12-18 21:21 UTC, ethanteague commented on docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js
> +      enableDisable;
@ndouglas @cweagans this is an eslint sniff that I _think_ is failing incorrectly. I changed to match the expected format as reported by reviewdog, but it doesn't match our what we have in our eslint setup.
Per our config, this is correct:
```
    document.getElementById("edit-field-address-0-address-locality").required =
      enableDisable;
```
reviewdog wants this (which throws esLint notices on commit in my local):
```
    document.getElementById(
      "edit-field-address-0-address-locality"
    ).required = enableDisable;
```

2021-12-18 22:40 UTC, ndouglas commented on docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js
> +      enableDisable;
I might need to poke around in the GH actions and make sure they're referencing the correct spec, etc.  IMHO open an issue if it's causing a PITA and I'll try to get it prioritized.

2021-12-20 18:41 UTC, kevwalsh requested changes
Autocomplete facility lookup is an improvement over the dropdown, but it's busted. 

<img width="671" alt="Screenshot_2021-12-20__1_40_PM" src="https://user-images.githubusercontent.com/643678/146816676-db80b88f-6f84-4936-aac1-5645072aa420.png">

2021-12-21 23:28 UTC, rachel-kauff commented
@ethanteague Thanks for waiting! I have Registration CTA design recs for you. I added them to the Figma, but here they are in screenshot form for easy reading. 
**Screenshot 1: Design adjustments (Spacing, help text, and label changes)**
<img width="597" alt="Screen Shot 2021-12-21 at 3 22 26 PM" src="https://user-images.githubusercontent.com/41017988/147010571-0710f32c-cf42-444a-a9ce-f6c9e7772d3a.png">

**Screenshot 2: Design adjustments with padding annotations**
<img width="597" alt="Screen Shot 2021-12-21 at 3 21 46 PM" src="https://user-images.githubusercontent.com/41017988/147010557-9288231c-a529-4098-bb6f-c8def220a176.png">

**Screenshot 3: Idea for some conditional logic to help avoid errors/bad content for CTA links**
<img width="597" alt="Screen Shot 2021-12-21 at 3 24 45 PM" src="https://user-images.githubusercontent.com/41017988/147010572-36d8de93-d4e8-41bb-8223-6c6eefce96bd.png">

2021-12-21 23:33 UTC, ethanteague commented
> @ethanteague Thanks for waiting! I have Registration CTA design recs for you. I added them to the Figma, but here they are in screenshot form for easy reading. 
>

Ty, @rachel-kauff . U da best.

2022-01-14 19:50 UTC, swirtSJW commented
Conflicted.  Also I am unclear/ lost track of.. Can this go in without recurring?

2022-01-14 19:55 UTC, ethanteague commented
No, this shouldn't be merged, @swirtSJW . This is just being used for front end testing. Tagging with Do-Not-Merge label.

2022-02-11 17:26 UTC, swirtSJW commented
I believe this can be closed as it all resides in branch:  integration-recurring-events

Ethan if that is true can you close this?

2022-02-11 17:36 UTC, closed without merging

2022-03-23 19:14 UTC, ElijahLynn commented
Can we kill this Tugboat ENV? It is locked. 

![image](https://user-images.githubusercontent.com/1504756/159778198-32c34633-7fcd-4703-832e-5c3435a4478e.png)

2022-03-23 19:28 UTC, ethanteague commented
Deleted, @ElijahLynn