VACMS-2043: Rebuild clean branch and remove connect with us fields.
department-of-veterans-affairs/va.gov-cms pull request #7332
Opened 2021-12-17 20:52 UTC by msbtterswrth

## Description

Relates to #2043 . This is a clean rebuild of #7180 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-12-17 21:13 UTC, ethanteague submitted a review, later dismissed
Code make sense. Nice work grinding it out, @msbtterswrth

2021-12-20 17:38 UTC, swirtSJW requested changes
There is a view  in here that is not covered by any testing steps.  Please add testing steps to cover the view and what a reviewer should expect to see 

I am not sure if the mis-cased sentence casing or the wording is a blocker. I don't see a deviation from that pattern in the issue or any note relating to it.

2021-12-20 17:38 UTC, swirtSJW commented on config/sync/field.field.node.campaign_landing_page.field_related_office.yml
> +label: 'Add Connect with us block'
Sentence case hybrid?

In use this seems like an odd directive since it is only true once.
![image](https://user-images.githubusercontent.com/5752113/146808203-0464c11b-a866-42ea-b96a-fa012e4bc706.png)

2021-12-20 17:38 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
> +| Content type | Benefits Hub Landing Page | Add Connect with us block | field_related_office | Entity reference |  | 1 | Select list |  |
Odd casing.

2021-12-20 22:37 UTC, swirtSJW commented
Also lets fix the name of this pr.  The PR's name is what becomes the commit message when this is merged "Rebuild clean branch and remove connect with us fields. " is too specific to the previous git mess, and unrelated to the actual issue being resolved with this PR.

2021-12-21 16:37 UTC, msbtterswrth commented on config/sync/field.field.node.campaign_landing_page.field_related_office.yml
> +label: 'Add Connect with us block'
This view was added, and the name changed based on [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7180#pullrequestreview-825375705) from @kevwalsh in the original PR: 

-[ ] Change "Related office" to "Add a "Connect with us" panel" on block
-[ ] Change "Related office" to "Add a "Connect with us" block" on block
-[ ] Create follow up issue for Entity reference view where user can only select from Veterans Health Administration, Veterans Benefits Administration, National Cemeteries Administration, or Veterans Affairs Central Office

2021-12-21 22:58 UTC, swirtSJW commented on config/sync/field.field.node.campaign_landing_page.field_related_office.yml
> +label: 'Add Connect with us block'
`Add a "Connect with us" block`  is not the same as `Add Connect with us block`

2021-12-21 23:06 UTC, swirtSJW commented on config/sync/field.field.node.campaign_landing_page.field_related_office.yml
> +label: 'Add Connect with us block'
@msbtterswrth  I'm not questioning the purpose of the View, I am saying you added a View and there is not a single QA step in this PR to evaluate whether it works or the additional criteria from the original PR comment that you added onto this code.  
```
Create follow up issue for Entity reference view where user can only select from Veterans Health Administration, Veterans Benefits Administration, National Cemeteries Administration, or Veterans Affairs Central Office
```
If you leave it for me to connect the dots on these things it takes me longer to review and more back an forth to get it across the finish line.  Please update the QA steps to include evaluating the view / additional AC.

2021-12-22 14:43 UTC, msbtterswrth commented on config/sync/field.field.node.campaign_landing_page.field_related_office.yml
> +label: 'Add Connect with us block'
updated.

2021-12-22 20:27 UTC, msbtterswrth commented on tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
> +| Content type | Benefits Hub Landing Page | Add Connect with us block | field_related_office | Entity reference |  | 1 | Select list |  |
i used the casing that kev used, since that is what was there previously on the old field. I could change it but i don't think it's blocking anything.

2021-12-23 18:55 UTC, swirtSJW approved these changes
Tests all good.   Thanks @msbtterswrth

2021-12-23 18:59 UTC, swirtSJW commented
The behavioral test failing
```
  Content Release
    ✓ The content release page should normally display no in-process releases (9354ms)
    ✓ The content release page should show a pending default release initiated within the browser (6903ms)
    - The content release page should show a pending chosen release initiated within the browser
    1) The content release page should show a pending default release initiated from the command line
    ✓ The content release page should show a pending chosen release initiated from the command line (6937ms)

  3 passing (40s)
  1 pending
  1 failing


  1) Content Release
       The content release page should show a pending default release initiated from the command line:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: 'Pending' but never did.
      at Context.eval (https://pr7332-fjetzik4medwbftpl1dtnxvvmxtjaha2.ci.cms.va.gov/__cypress/tests?p=cypress/integration/content_release.feature:173553:28)
      at Context.resolveAndRunStepDefinition (https://pr7332-fjetzik4medwbftpl1dtnxvvmxtjaha2.ci.cms.va.gov/__cypress/tests?p=cypress/integration/content_release.feature:22511:9)
      at Context.eval (https://pr7332-fjetzik4medwbftpl1dtnxvvmxtjaha2.ci.cms.va.gov/__cypress/tests?p=cypress/integration/content_release.feature:21829:35)
```

This seems like a pipeline failure.   I am retriggering a test run.

2021-12-23 20:07 UTC, merged