VACMS-6935 - Create metatag audit view
department-of-veterans-affairs/va.gov-cms pull request #7352
Opened 2021-12-20 22:16 UTC by msbtterswrth

## Description
Created a view to help audit the current meta tags and how they're being used across all Veteran-facing content types.

Relates to #6935.

## Testing done
Navigated the view and saw the various fields being displayed for meta tags within the view results list.

## Screenshots
![image](https://user-images.githubusercontent.com/8375335/146839536-3c1bd1fe-691c-465e-bd76-a5248f04159e.png)

## QA steps

As cms editor I can
1. View the metatag audit tool (/admin/content-tools/metatag-audit) and
1. View a list of content and the meta data stored in the CMS
1. Then validate Acceptance Criteria from issue
- [ ] See what metadata drupal currently has (and what it has to offer that isn’t currently us

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-12-21 22:42 UTC, swirtSJW requested changes
Looks good overall.   Just some standardization things
![image](https://user-images.githubusercontent.com/5752113/147006890-651ca497-f1a3-49f6-84d1-500adab0b0f6.png)
- [ ] "Edit" should be  button.
- [ ]  Date display should match existing patttern

2021-12-21 22:42 UTC, swirtSJW commented on config/sync/views.view.metatag_audit.yml
> +      path: admin/content-tools/metatag-audit
This path deviates from our existing audit related views of `/content/audit/*`
```suggestion
      path: admin/content/audit/metatags
```
![image](https://user-images.githubusercontent.com/5752113/147006490-1f99cdb5-44b3-4e00-a5d5-ae4d3054e54c.png)

2021-12-21 22:53 UTC, swirtSJW commented
A couple other issues surfaced.
- [ ] The section filter is not working properly 
![image](https://user-images.githubusercontent.com/5752113/147007575-e56a8705-e2d5-46b0-8cbf-6f9dafede67f.png)
This should not be the field_administration filter it should be "workbench access section".  When you select a VISN, you should get all sections within that VISN.


- [ ] The filters need a "Reset" button 
- [ ] The "Apply" button should say "Filter"  
![image](https://user-images.githubusercontent.com/5752113/147007958-5e16cec2-1959-4426-9352-d3e5f25c9178.png)

2021-12-22 19:15 UTC, swirtSJW requested changes
I am still seeing this issue 
- [x] The section filter is not working properly
![image](https://user-images.githubusercontent.com/5752113/147143680-da89b055-25ee-4435-8f51-474a203bdf93.png)

This should not be the field_administration filter it should be "workbench access section". When you select a VISN, you should get all sections within that VISN.

2021-12-22 19:20 UTC, swirtSJW commented
Also something in your git process is still creating these repeating commits.
![image](https://user-images.githubusercontent.com/5752113/147144160-7a148d6e-815f-496a-a30d-fa0807cb0c17.png)

Please make sure to run the git config steps here https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/getting-started.md

2021-12-22 20:25 UTC, msbtterswrth commented
@swirtSJW i did update it to use workbench access, ass seen here: 
![image](https://user-images.githubusercontent.com/8375335/147150828-e99ede61-13c9-4011-bdee-5430244a9942.png)

I am not sure what else I need to do? 

As far as the git commits go, I did follow the git readme when i set it up originally, and again reset it it up last week. these were all different commits updating the tests, though I thought i had squashed the two yesterday into one commit, but I guess they still came through separately. 

I will remind myself not to reuse the same commit message if that's helpful.

2021-12-23 18:11 UTC, swirtSJW approved these changes
Tests out good.  Nice work.
![image](https://user-images.githubusercontent.com/5752113/147277708-2ddd6510-84cb-4e25-8a22-a4f1dd83b34b.png)

2021-12-23 18:11 UTC, merged