VACMS-5372 add favicon
department-of-veterans-affairs/va.gov-cms pull request #7368
Opened 2021-12-21 23:00 UTC by tjheffner

## Description

Relates to #5372 / #2746. Also this related PR has been floating around since May: #5373 ... I created this new branch to avoid any potential merge conflicts with config / add the icon to the claro theme, but I could do this work in that PR too if that's more appropriate. I figured it could be safely closed instead :shrug:

- Adds favicon
- Removes environment_indicator addition to favicon
- Adds a screenshot for vagovclaro (seen on the appearance page)

## Testing done
Verified favicon showed as expected logged in and logged out with both vagovadmin and vagovclaro set as the default & admin themes.

## Screenshots
<img width="234" alt="Screen Shot 2021-12-21 at 2 52 15 PM" src="https://user-images.githubusercontent.com/11279744/147008292-7e31a971-b79a-4c88-a8e8-ee6619403e08.png">

<img width="1086" alt="Screen Shot 2021-12-21 at 11 35 19 AM" src="https://user-images.githubusercontent.com/11279744/147008263-10a13c14-2555-47c9-bc48-8c68e6827a29.png">

## QA steps
open PR environment, see that favicon is present
log in and change theme to vagovclaro, see that favicon is present for both themes

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [x] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [x] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change.
  - [x] Merge & carry on unburdened by announcements

Personally I don't think an announcement is needed for a favicon update... just a nice quality of life update they may notice on their own?

2021-12-22 18:18 UTC, swirtSJW commented
@tjheffner  this looks good but I want to check on one thing.
I think we want the cms brand to differentiate from va.go so tabs are identifiable.  This PR would make them the same
![image](https://user-images.githubusercontent.com/5752113/147137318-db0975c8-0a2c-46a5-85be-b29de0e54b12.png)
I know @kevwalsh  whipped up a quick one in this PR, but he never took  it off draft.
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5373

We should check with him first.

2021-12-28 16:51 UTC, kevwalsh commented
This was [the reversed version of the VA logo](https://raw.githubusercontent.com/kevwalsh/va.gov-cms/VACMS-5373-favicon/docroot/themes/custom/vagovadmin/images/icons/favicon.png) that i [had prototyped](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5373/files#diff-d46b8ff683d80f4a82b0634e8a7365178e9dace9d8c39cca009dc1da845eca3c) to appear as the favicon. It looks like i hadn't taken the next step of creating an .ico from it, or downsizing it from 73kb. 

But yeah, the intent was to make the CMS look different than VA.gov. It seems OK per the [VA Tier 1 graphic standards](https://www.va.gov/opa/publications/graphicstandards/va_graphicstandardsguide_508_0113.pdf) 

It seems like there's an opportunity to replace the admin menu Druplicon with it too, in the short term. Not sure how many of our users know that the druplicon takes them back to the home page.

2021-12-28 17:18 UTC, rachel-kauff commented
@kevwalsh @tjheffner What about something subtle that suggests "editing?" Like so:

<img width="608" alt="Screen Shot 2021-12-28 at 9 17 52 AM" src="https://user-images.githubusercontent.com/41017988/147590881-e0144440-dbec-4523-8d66-64841d31b008.png">

2021-12-28 17:41 UTC, rachel-kauff commented
To scale:

<img width="189" alt="Screen Shot 2021-12-28 at 9 41 35 AM" src="https://user-images.githubusercontent.com/41017988/147592674-541ead48-eb40-44d3-a046-3303e3cbd163.png">

2021-12-28 19:54 UTC, tjheffner commented
Updated favicon & druplicon in the toolbar to use reverse logo.

Used imagemagick to resize the 1874x1874px png logo to a 128x128png for the toolbar and a 32x32 ico for the favicon. 5.82kb and 4.29kb respectively vs 73kb.

<img width="394" alt="Screen Shot 2021-12-28 at 11 51 06 AM" src="https://user-images.githubusercontent.com/11279744/147602277-f234d113-de7f-4d26-9cde-5279b52ac331.png">
<img width="233" alt="Screen Shot 2021-12-28 at 11 51 11 AM" src="https://user-images.githubusercontent.com/11279744/147602278-57adc49b-ad16-4171-a556-2419ec7dbb24.png">

2021-12-28 19:56 UTC, tjheffner commented
@rachel-kauff I didn't use the dashed border favicon because i was worried it felt a little cluttered in both places but can definitely use that instead if it's a make or break thing

2021-12-28 21:07 UTC, rachel-kauff commented
@tjheffner no worries, it was just an idea. And yeah, that wouldn't look good in the toolbar.

2021-12-29 02:23 UTC, kevwalsh commented on docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
> +.toolbar-tray-horizontal .menu-item:hover {
I love all this. 

Looks like you need an `:active` state too, there's a little druplicon flash when you click the VA logo.

2021-12-29 02:24 UTC, kevwalsh requested changes
I love all this.

2021-12-29 02:26 UTC, kevwalsh commented on docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
> +.toolbar-tray-horizontal .menu-item:hover {
Minor detail but i wonder if a transparent png would look better for the hover behavior. 

<img width="76" alt="Cursor_and_kevin_walsh___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/147621557-366da33c-0e7c-4344-ad3a-d602d57e134a.png">

2021-12-29 17:02 UTC, tjheffner commented on docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
> +.toolbar-tray-horizontal .menu-item:hover {
Active state accounted for now, toolbar logo also made transparent 👍

2021-12-29 18:41 UTC, kevwalsh approved these changes
Looks great!

2021-12-29 19:52 UTC, merged