[DNM] VACMS-7244: Send our prometheus metrics to Datadog
department-of-veterans-affairs/va.gov-cms pull request #7411
Opened 2021-12-28 00:29 UTC by cweagans

## Description

Relates to #7244.

This still needs some work to wire up the Datadog key. This approach means that we can continue to use the Prometheus Exporter module + its ecosystem of modules to send Datadog metrics and not worry about re-doing any of the work that was already done.

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-12-29 22:22 UTC, cweagans commented
PR to add Datadog key is here: https://github.com/department-of-veterans-affairs/devops/pull/10498

2021-12-29 22:53 UTC, cweagans commented
Not sure what's going on with PHPstan here. I _think_ the two issues found are false positives.

```
 ------ ----------------------------------------------------------------------- 
  Line   docroot/modules/custom/va_gov_backend/src/Service/Metrics.php          
 ------ ----------------------------------------------------------------------- 
  86     Method Drupal\va_gov_backend\Service\Metrics::buildMetricsObject()     
         should return object but return statement is missing.                  
  110    Binary operation "." between non-empty-string and array results in an  
         error.                                                                 
 ------ ----------------------------------------------------------------------- 
```

86 is not where that method ends (and that method definitely has a return statement).

110 is handled by the `!empty` check directly above it. The `$k` and `$v` values are strings.

2021-12-30 14:48 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/src/Service/Metrics.php
> +    switch ($this->settings->get('va_gov_frontend_build_type')) {
This would be better as Plugins with a setting to set the plugin but this is not required for this PR to be merged.

2021-12-30 14:49 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/src/Service/Metrics.php
> +  protected function buildMetricsObject(array $metricsList): object {
This should be it's own Service and injected into this class.

2021-12-30 14:51 UTC, indytechcook commented
Please make sure Unit tests are added for the metrics parsing.

2022-01-12 01:31 UTC, timcosgrove approved these changes
I think my input matters less than folks that have been here longer and have more of a devops bent, but, looks good.

2022-01-12 01:31 UTC, timcosgrove commented on docroot/sites/default/settings/settings.ddev.php
> +//$settings['va_gov_force_sending_metrics'] = true;
does this need to go into settings.prod.php as well or is that outside the scope of this work?

2022-01-12 01:31 UTC, timcosgrove commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function va_gov_backend_cron() {
I am sad that procedural hooks are not gone from Drupal.

2022-01-12 03:50 UTC, cweagans commented on docroot/sites/default/settings/settings.ddev.php
> +//$settings['va_gov_force_sending_metrics'] = true;
No, this is just for local testing. It's automatically enabled if the build type is brdgha (which is set for all names BRD environments).

2022-01-12 03:52 UTC, cweagans commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function va_gov_backend_cron() {
Saaaaame. When https://www.drupal.org/project/drupal/issues/2616814 is solved, we can override the ModuleHandler service and do our own OO hook system (or build a contrib module that does it).

2022-01-12 13:29 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function va_gov_backend_cron() {
We have https://www.drupal.org/project/hook_event_dispatcher which has `CronEvent` you can use :)

2022-01-12 15:05 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/src/Service/Metrics.php
> +    switch ($this->settings->get('va_gov_frontend_build_type')) {
After thinking about this some more, please add on to the `@Environment` plugin which already exists.  

That would change the following:

* Add `getDatadogEnvironment() : string` to `Drupal\va_gov_build_trigger\Environment\EnvironmentInterface`
* Update the Environment plugins at `Drupal\va_gov_build_trigger\Plugin\VAGov\Environment\*` with the new method.
* Inject `Drupal\va_gov_build_trigger\Environment\EnvironmentDiscovery` (service `va_gov.build_trigger.environment_discovery`) and call `EnvironmentDiscovery::getEnvironment()->getDatadogEnvironment()

2022-01-12 15:09 UTC, indytechcook requested changes
Really good structure and tests!!  Excellent work.  Just two changes and this is good to merge!

* https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7411/files#r783161109
* `CrontEvent`

2022-01-12 19:28 UTC, cweagans commented on docroot/modules/custom/va_gov_backend/src/Service/Metrics.php
> +    switch ($this->settings->get('va_gov_frontend_build_type')) {
Talked about this on slack -- this is a bit of a rabbit hole as far as tests go, so we're going to defer this and do a larger refactor of the environment discovery stuff (ticket to be created)

2022-01-13 03:25 UTC, cweagans commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +function va_gov_backend_cron() {
Done!

2022-01-13 14:34 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/src/Service/Datadog.php
> +    $this->apikey = $settings->get('cms_datadog_api_key');
I sort of hope I'm wrong about this and there is something going on that I don't see

2022-01-13 14:53 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/src/Service/Datadog.php
> +    $this->apikey = $settings->get('cms_datadog_api_key');
Looking around the Drupal issue queue I found https://www.drupal.org/project/drupal/issues/2443351 which changes the pattern from injecting the `Settings` object to using container parameters.  See this patch: https://www.drupal.org/files/issues/2251113.66.patch.

I'm not saying we should to this now as it's a pretty big refactor. But the patter of using container parameters pattern will more closely align with future Drupal and Symfony.

I logged a follow up: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7580

2022-01-13 14:54 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/src/Service/Datadog.php
> +    $this->apikey = $settings->get('cms_datadog_api_key');
I do see other examples of injecting settings in core code so that would make this acceptable.  My IDE just screams at me.  :)

2022-01-13 14:56 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
> +      - { name: event_subscriber }
This is the first time I've seen a Service used as an event subscriber instead of there being a dedicated event subscriber.  While normally I'm not sure about that pattern I do like the use case here. :)

2022-01-13 14:56 UTC, indytechcook approved these changes

2022-01-13 14:57 UTC, indytechcook commented on docroot/modules/custom/va_gov_backend/src/Service/Datadog.php
> +    $this->apikey = $settings->get('cms_datadog_api_key');
This was a fun rabbit hole but it's time to get back to my regularly scheduled documentation.

2022-01-13 18:59 UTC, cweagans commented on docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
> +      - { name: event_subscriber }
I figured it was less code this way :)

2022-01-13 22:01 UTC, indytechcook approved these changes

2022-01-14 00:48 UTC, merged