VACMS-7321: Add "Enforce unique combo office" field to fix duplicated Non-clinical Service
department-of-veterans-affairs/va.gov-cms pull request #7418
Opened 2021-12-28 22:50 UTC by netboss

- VACMS-7321:
    - Added new "Enforce unique combo office" (field_enforce_unique_combo_offic) field to the "VAMC Facility Non-clinical Service" content type and configured it.
    - Adjusted the "VAMC Facility Non-clinical Service" content type form display and rearranged the new field.
    - Updated "content_model_bundles.feature" and "content_model_vamc_content_type_fields.feature" Behat features.

## Description

closes #7321 

## Testing done

Passes all tests

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-12-29 03:06 UTC, swirtSJW requested changes

2021-12-29 03:06 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.vha_facility_nonclinical_service.default.yml
> -        - revision_log
You need to add this one back by hand.   It is the cause of the failing test.

2022-01-03 21:57 UTC, swirtSJW approved these changes
Nice work @netboss

2022-01-05 15:48 UTC, netboss commented
@swirtSJW 
What else is needed here? Or if this already approved and ready to be merged? Please let me know.

2022-01-05 21:36 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/148293011-325ece27-2d7b-4231-bcc1-233825208ad0.png)

2022-01-05 21:37 UTC, merged