VACMS-7341 Generate top task pages.
department-of-veterans-affairs/va.gov-cms pull request #7421
Opened 2021-12-29 07:10 UTC by swirtSJW

## Description

closes #7341 

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2021-12-31 05:09 UTC, swirtSJW commented
@kevwalsh This is generating all that do not already exist.  The menu experience is not great.  They get added to the right menu, just not with a specific parent.

2022-01-03 14:57 UTC, swirtSJW commented
@kevwalsh Setting the menu placement it kind of ....errr...annoying.  Right now it is setting here (red) one layer to high. 
![image](https://user-images.githubusercontent.com/5752113/147944886-282bd97d-cd73-4805-b718-feddd8f10874.png)
I am assuming it needs to be on the same layer with contact us and policies.  Should it be alpha order there?  
* Billing and insurance
* Contact us
* Medical records office
* Policies
* Register for care

2022-01-04 20:24 UTC, JayDarnell commented
@swirtSJW review looks good so far with the one question about call_user_func_array above. QA steps pass as of this moment. If you add additional QA steps let me know and I'll take another look.

2022-01-04 21:17 UTC, swirtSJW commented
This  can be approved, but can not be merged until it has been announced and Data Call made.

2022-01-07 19:23 UTC, swirtSJW commented
@JayDarnell  Thanks for the review.
You said 

> @swirtSJW review looks good so far with the one question about call_user_func_array above.

But I don't see a question about it.

2022-02-23 22:52 UTC, JayDarnell requested changes
Two regressions to remove

2022-02-23 22:52 UTC, JayDarnell commented on config/sync/user.role.content_publisher.yml
> +  - 'edit terms in health_care_service_taxonomy'
This is a regression and should be removed.
```suggestion
```

2022-02-23 22:52 UTC, JayDarnell commented on tests/phpunit/Security/RolesPermissionsTest.php
> +          'edit terms in health_care_service_taxonomy',
This is also a regression and needs to be removed
```suggestion
```

2022-02-24 14:21 UTC, JayDarnell commented
Currently failing on two frontend tests @swirtSJW @kevwalsh 

```Given I am at "/static/"                                                                                                   # Drupal\DrupalExtension\Context\MinkContext::assertAtPath()
      Current response status code is 403, but 200 expected. (Behat\Mink\Exception\ExpectationException)```

and 

``` Then the response status code should be 403                                                                                                                     # Drupal\DrupalExtension\Context\MinkContext::assertResponseStatus()
      Current response status code is 200, but 403 expected. (Behat\Mink\Exception\ExpectationException)```

```Failed scenarios:

    features/decoupled.feature:8
    features/decoupled.feature:14```

2022-02-24 17:03 UTC, swirtSJW commented
Interesting that /static failed to build.... that is usually a pipeline error.   Lookiing into the phpunit fail right now.

2022-02-24 17:05 UTC, swirtSJW commented
phpunit failures  
![image](https://user-images.githubusercontent.com/5752113/155572306-0eae101b-fc91-46f5-87dc-a116afe6a89a.png)

2022-03-03 15:59 UTC, JayDarnell commented
@swirtSJW this appears to work perfectly!

2022-04-28 18:17 UTC, swirtSJW commented on config/sync/user.role.content_publisher.yml
> +  - 'edit terms in health_care_service_taxonomy'
Bahh. regression. Fixing

2022-05-03 21:52 UTC, merged