VACMS-7309: Disallow HTML characters from character count on text fields
department-of-veterans-affairs/va.gov-cms pull request #7460
Opened 2022-01-03 19:01 UTC by msbtterswrth

## Description

Relates to #7309 .

## Testing done
Edited a vet center featured content section to add a blurb with a link and then removed the link to ensure the counter was not counting html characters. 

## Screenshots
Example with url: 
![image](https://user-images.githubusercontent.com/8375335/147968743-32164343-a347-47f0-8437-0a28ac5a9b78.png)

Same example with no url: 
![image](https://user-images.githubusercontent.com/8375335/147968761-ea7f6a08-d273-458a-979b-ebec157452df.png)

## QA steps

As a cms editor I can
1. Edit a Vet Center
2. Add "Featured Content"
4. Type more than 240 characters to within the description including a URL
5. See error message of "Description cannot be longer than 240 characters but is currently (number that's greater than 240) characters long
6. Remove characters until you're under 240 characters while keeping the URL intact
7. Remove the URL and confirm the character count does not change. 

1. Then validate Acceptance Criteria from issue
- [x] All text counters applied to rich text fields have been configured to ignore html characters

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-01-03 19:04 UTC, msbtterswrth commented
I have updated this for ALL text fields on content types and paragraphs based on a previous audit I did for text field usage, though the steps for qa are only for Vet Centers, they would be the same for all ~20 instances of this update. 

There was a stretch AC not covered in this ticket for an automated test to be created for check if any text fields are misconfigured. If that's still valid, I suggest a second follow-up ticket for that.

2022-01-03 21:24 UTC, kevwalsh approved these changes
I tested this on [/node/3613/edit](https://pr7460-eap02c269eth6p2v8yzqbyh3zudwkjth.ci.cms.va.gov/node/3613/edit) and [the revisions view](https://pr7460-eap02c269eth6p2v8yzqbyh3zudwkjth.ci.cms.va.gov/node/3613/revisions/view/598096/603113/split_fields)  shows that it works! 

@msbtterswrth The second AC on #7309 is to create an issue for the stretch item, since it wasn't included in this. Can you do that?

2022-01-03 21:24 UTC, kevwalsh commented on config/sync/core.entity_form_display.node.step_by_step.default.yml
> +      allowed_formats:
Unexpected but both set to false, so probably nto a big deal, just one of those weird config artifacts?

2022-01-05 15:36 UTC, swirtSJW requested changes
@msbtterswrth Some of these changes will break our push to lighthouse.

2022-01-05 15:36 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
> +      count_html_characters: false
major: This one has to count html chars because Lighthouse does not discriminate and will fail if we send more than 300 chars of any type.

2022-01-05 15:48 UTC, kevwalsh commented
@msbtterswrth looks like you hit all fields with counters. the AC is to only touch the ones that are _rich text fields_.
<img width="882" alt="HTML_characters_should_not_be_counted_in_Vet_Center_Featured_content_text_field_·_Issue__7309_·_department-of-veterans-affairs_va_gov-cms" src="https://user-images.githubusercontent.com/643678/148246730-20e32f9f-22b4-44cb-8ef8-5d98dc4b372a.png">

2022-01-05 15:55 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
> +      count_html_characters: false
This change is still showing.  Not resolved.

2022-01-05 15:58 UTC, swirtSJW commented on config/sync/core.entity_form_display.node.nca_facility.default.yml
> -      count_html_characters: true
![image](https://user-images.githubusercontent.com/5752113/148248400-47291394-3301-451a-9145-ba6d733d07a1.png)

2022-01-05 15:59 UTC, msbtterswrth commented
Updated those instances, also created the follow up for an automated test  in #7483

2022-01-05 16:41 UTC, msbtterswrth commented on config/sync/core.entity_form_display.node.nca_facility.default.yml
> -      count_html_characters: true
this is two different fields, but i see i changed the wrong one, and have updated it.

2022-01-05 16:42 UTC, msbtterswrth commented on config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
> +      count_html_characters: false
Ah, i updated the wrong line, should be fixed now.

2022-01-05 17:11 UTC, swirtSJW approved these changes
Nice work

2022-01-05 17:16 UTC, swirtSJW commented
I will merge as soon as tests complete.

2022-01-05 18:02 UTC, swirtSJW commented
Looks like failing tests are related to outdated code.   Bringing this up to date  and re-running tests.

2022-01-06 15:19 UTC, swirtSJW commented
Failed behat was a pipeline problem
![image](https://user-images.githubusercontent.com/5752113/148405628-f73f304d-03d8-4425-a1cc-236accc60f22.png)

I am retriggering tests.

2022-01-07 16:02 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/148571097-6fa38968-c833-4dd9-ba17-ef2bf81c8ad7.png)

2022-01-07 16:03 UTC, merged