Vacms 7420 configure claro footer menu
department-of-veterans-affairs/va.gov-cms pull request #7462
Opened 2022-01-03 21:46 UTC by msbtterswrth

## Description

Relates to #7420 .

## Testing done
Added links to the footer menu and saw them change on the login screen.

## Screenshots
Existing footer menu with new links added:
![image](https://user-images.githubusercontent.com/8375335/147983177-1906589e-20be-43f7-86d2-18e595cd87fd.png)

Frontend login screen showing new menu-based links:
![image](https://user-images.githubusercontent.com/8375335/147983119-65fd9dea-3501-4603-bd2d-6973fc2689bc.png)

## QA steps

As a cms admin I can
1. Edit the menu items at `/admin/structure/menu/manage/footer` 
2. Log out and see that they're updated on the login screen
1. Then validate Acceptance Criteria from issue
- [x] Footer Menu Has been created
- [x] Workbench menu access set to "VA.gov CMS Knowledge Base"

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-01-04 01:38 UTC, kevwalsh commented on config/sync/block.block.footer.yml
> +  label: Footer
Can you make this more specific to `Footer menu`? It will probably require redoing this, since the machine name is already `block.block.footer.yml` ,but should be `block.block.footer_menu.yml`.

2022-01-04 01:40 UTC, kevwalsh commented on docroot/themes/custom/vagovclaro/templates/layout/footer.html.twig
> +    {# these links should be tied to a menu imo
why not just delete the whole block instead of commenting it all out?

2022-01-04 01:43 UTC, kevwalsh requested changes
A couple little things, unrelated to the build error.

2022-01-04 16:05 UTC, msbtterswrth commented on docroot/themes/custom/vagovclaro/templates/layout/footer.html.twig
> +    {# these links should be tied to a menu imo
I left this is for now as a reference to what links we had in there, once this passes design/content review I imagine we can remove that.

2022-01-04 22:57 UTC, swirtSJW requested changes
Nice work @msbtterswrth  
I confirmed the menu gets placed
![image](https://user-images.githubusercontent.com/5752113/148135077-e4226e72-2108-466f-a006-463656800d84.png)

And confirmed there are no notices/warnings
![image](https://user-images.githubusercontent.com/5752113/148135134-1d289952-3da2-4689-b4f3-c90387f51710.png)

Only one requested change.  To get rid of that  theme weight test that had no effect on the issue.

2022-01-04 22:57 UTC, swirtSJW commented on config/sync/core.extension.yml
> +  vagovclaro: 1000
If the D.O patch solved the requirements issue.  Let's set the weight back to 0.
```suggestion
  vagovclaro: 0
```

2022-01-04 22:57 UTC, swirtSJW commented on docroot/themes/custom/vagovclaro/templates/layout/footer.html.twig
> +    {{page.footer}}
I confirmed output contains nav and aria role.  
![image](https://user-images.githubusercontent.com/5752113/148134693-e06096e9-7bb2-4777-b60d-3ca9191c9e86.png)

2022-01-05 16:41 UTC, tjheffner approved these changes
LGTM, noting all the config files are here because vagovclaro hasn't technically been installed & config synced prior to this point. thanks for doing this @msbtterswrth!

2022-01-05 18:18 UTC, swirtSJW approved these changes

2022-01-05 18:20 UTC, merged