VACMS-7256 Make revision log track include 'flagged' on all flaggings.
department-of-veterans-affairs/va.gov-cms pull request #7675
Opened 2022-01-19 19:33 UTC by swirtSJW

## Description

Closes #7256

## Testing done

## Screenshots

## QA steps

As user _uid_ with _user_role_
1. Do this
2. Then that
3. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-01-27 22:43 UTC, JayDarnell requested changes
Small typo but that is all I could find.

2022-01-27 22:43 UTC, JayDarnell commented on docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
> +    if (!$node->isSyncing()) {
I've not used this before and am a little unclear on what it does. Reading the documentation briefly while doing code review didn't clear things up. I'm unclear as to what the documentation means by "import process". Configuration import?

2022-01-27 22:43 UTC, JayDarnell commented on docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
> +      // Don't log test datat changes or personal flags.
Small typo.

2022-01-27 22:43 UTC, JayDarnell commented on docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
> +  protected function isLoggableFlag(Flagging $flagging) : bool {
This is a tangent but do we have a ticket to investigate the edited flag to see if it is actually used for anything?

2022-01-27 22:43 UTC, JayDarnell commented on docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
> +      $original = $this->getLatestRevision($nid, $node);
Would love to talk through this with you just to help me make sure I follow.

2022-01-27 23:36 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
> +    if (!$node->isSyncing()) {
It is basically a marker that can be set on a node to allow other code to distinguish between a "formal" save and a quick and dirty save.  It persists from presave all the way through after node save so it can be a way to keep state on the save.   I don't think there is much that actually uses it in core yet.

2022-01-27 23:38 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
> +  protected function isLoggableFlag(Flagging $flagging) : bool {
It was added by Platform CMS when they were going to be doing notifications of content changes for editors.   It was part of the initial infrastucture the rest of which has not been implemented yet.

2022-01-27 23:39 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
> +      // Don't log test datat changes or personal flags.
Its not a typo, its a Florida thing.... just kidding... its a typo.

I'll fix it before merge... I don't want to fix it now or I will lose my demo data.

2022-01-28 04:21 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
> +      // Don't log test datat changes or personal flags.
```suggestion
      // Don't log test data changes or personal flags.
```

2022-01-28 04:25 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/151487055-34211096-f4ed-49f6-b7aa-88eb1058d3dc.png)

2022-01-28 04:28 UTC, merged