VACMS-7619: Create field_va_health_connect_phone but keep it hidden
department-of-veterans-affairs/va.gov-cms pull request #7677
Opened 2022-01-19 22:05 UTC by netboss

- Created "field_va_health_connect_phone" and configured it to be disabled on both manage form display and manage display.

## Description

closes #7619 

## Testing done

Passes all tests.

## Screenshots
Fields:
![VACMS-7619_fields](https://user-images.githubusercontent.com/846871/150221541-36568064-bfcf-40ab-b872-4f9d5d1556fd.png)

Manage form display:
![VACMS-7619_manage_form_display](https://user-images.githubusercontent.com/846871/150221571-c425212b-4eda-47c6-86b8-01afbb76061b.png)

Manage display:
![VACMS-7619_manage_display](https://user-images.githubusercontent.com/846871/150221613-eb7def8d-f6d5-4744-bf44-53757e2cc3af.png)

## QA steps

As user administrator
1. [ ] Go to `/admin/structure/types/manage/health_care_region_page/fields` to verify and confirm the new `field_va_health_connect_phone` is listed there
2. [ ] Go to `/admin/structure/types/manage/health_care_region_page/form-display` to verify and confirm the new `field_va_health_connect_phone` is listed there and disabled in manage form display
3. [ ] Go to `/admin/structure/types/manage/health_care_region_page/display` to verify and confirm the new `field_va_health_connect_phone` is listed there and disabled in manage display

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-01-20 22:26 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
> -
Lost the trailing line

2022-01-20 22:28 UTC, swirtSJW commented on config/sync/core.entity_view_display.node.health_care_region_page.default.yml
> -      children:
There are a lot of changes appearing here that I would not expect.

2022-01-21 12:57 UTC, swirtSJW commented on config/sync/core.entity_view_display.node.health_care_region_page.default.yml
> -  field_administration: true
This odd.  Nobody has touched this for months, but suddenly this gets removed as hidden.
![image](https://user-images.githubusercontent.com/5752113/150530731-1c5f8375-d121-4c5f-8420-8465569b0fa3.png)

2022-01-21 12:57 UTC, swirtSJW commented on config/sync/core.entity_view_display.node.health_care_region_page.default.yml
> -  field_administration: true
It is indeed not hidden just seems odd that it has taken this long for config to catch up.

2022-01-21 13:07 UTC, swirtSJW requested changes
I added some QA steps because:
1.  There weren't any that actually involved getting eyes on what the editors see.
2. There were a bunch of config changes that I did not expect to see that were possible config playing catch-up from changes long ago, but want to confirm with side-by-side comparison.

We want to get that trailing line back in the behat test.

2022-01-21 14:23 UTC, netboss commented on config/sync/core.entity_view_display.node.health_care_region_page.default.yml
> -      children:
@swirtSJW 
I really don't know how/why these changes get there. The only thing I did in the manage display was moving the new `field_va_health_connect_phone` field to the disabled area. I didn't touch anything else.

I've looked at the CMS prod **Blurbs for subpages** group and compared it to my local and they both look the same. See screen shots.

CMS prod:
![VAMC-System-fields-manage-display-prod](https://user-images.githubusercontent.com/846871/150541220-0c7b7004-9295-4631-a809-cc13a29d5370.png)

Local:
![VAMC-System-fields-manage-display-local](https://user-images.githubusercontent.com/846871/150541252-5661301b-86de-45d9-90ab-556e25cd375c.png)

And then I went to CMS prod config sync single export to get a copy of the actual config file to check and yes it's different:

CMS prod:
```
    group_blurbs_for_subpages:
      children:
        - field_featured_content_healthser
        - field_press_release_blurb
```

Local:
```
    group_blurbs_for_subpages:
      children: { }
```

I can't see a way to resolve this via the VAMC System content type manage display page. Can I just add the (above) code to the config manually?

2022-01-21 14:27 UTC, netboss commented on tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
> -
@swirtSJW 
In my local behat feature it have the trailing line. Not sure why this one doesn't have it. Should I try adding an extra (double) trailing line?

2022-01-21 15:04 UTC, swirtSJW commented on tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
> -
It needs a single trailing line.  Your ide should be adding it on save.

2022-01-21 16:11 UTC, netboss commented on tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
> -
@swirtSJW 
Updated it and re-pushed (in my local IDE I had to make it double trailing line).

2022-01-21 18:19 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/150579688-ca8481e6-eb59-47ee-aa6a-1ba69b282e35.png)

2022-01-21 18:20 UTC, merged