VACMS-7721: display published status on non-clinical service cards
department-of-veterans-affairs/va.gov-cms pull request #7923
Opened 2022-02-08 14:36 UTC by JayDarnell

## Description

Closes #7721

## Testing done

Visual Testing

## Screenshots

## QA steps

As an admin user:
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-02-08 15:56 UTC, JayDarnell commented
@swirtSJW this PR still has the issue we discussed with caching in the va.gov admin theme but maybe that is okay as we are switching to Claro?

2022-02-11 01:47 UTC, swirtSJW requested changes
This all looks good.  Nice work.  Just would like comments in both templates leaving a bit of a clue about the why.

2022-02-11 01:47 UTC, swirtSJW commented on docroot/themes/custom/vagovadmin/templates/views/views-view-grouping--non-clinical-services.html.twig
> +{% if grouping_level == 0 %}
Still would like a comment here leaving a breadcrumb about why this was necessary.  It is not obvious to  me and definitely will not be obvious in a month from now.

2022-02-11 01:47 UTC, swirtSJW commented on docroot/themes/custom/vagovclaro/templates/views/views-view-grouping--non-clinical-services.html.twig
> +<div class="view-grouping {{ content|first['#title']|render|striptags|trim|lower }}">
comment please

2022-02-11 03:10 UTC, merged