VACMS-6696: Prevent previews and url links on no bio staff pages.
department-of-veterans-affairs/va.gov-cms pull request #7940
Opened 2022-02-08 20:55 UTC by ethanteague

## Description
closes #6696

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/153074008-c717442d-ad48-4435-bb56-7a29056e6ecb.png)

![image](https://user-images.githubusercontent.com/2404547/153074033-037da3dd-30a6-4983-a29b-00e3cfc01eca.png)

## QA steps
 - [ ] as an administrator, go to `kansas-city-health-care/staff-profiles/patty-callahan` and visually verify `CREATE PROFILE PAGE WITH BIOGRAPHY` is set to `Off` and preview button and preview url are not visible
 - [ ]  - [ ] as an administrator, go to `pittsburgh-health-care/staff-profiles/lovetta-ford` and visually verify `CREATE PROFILE PAGE WITH BIOGRAPHY` is set to `On` and preview button and preview url are not visible (preview url will show as pending b/c this is a dev environment with a link to the static build of the cms).

2022-02-08 22:50 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      (!in_array($node->bundle(), $exclusion_types)) && !$staff_no_bio) {
You trying for and Ed F. award on this double neg?   LOL

2022-02-08 23:09 UTC, swirtSJW requested changes
Some suggestions to clean up the double negatives and make the logic easier to see and less likely to bleed unintentionally to something else.

2022-02-08 23:09 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
> +    $staff_no_bio = !empty($node->field_complete_biography_create) && $node->field_complete_biography_create->value === '0' ? TRUE : FALSE;
This check should be inside of vaGovUrlShouldBeDisplayed($node).   That is literally what the method does.  Deciding whether to show the link.  It should be the very first check in that method.

2022-02-08 23:09 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      (!in_array($node->bundle(), $exclusion_types)) && !$staff_no_bio) {
Instead of adding the second condition `&& !$staff_no_bio` after the !in_array check  it would be better if your check higher up just decided whether to add 'person_profile' to the $exclusion_types array  or not.  Then there is no && and double negative intent to figure out.

2022-02-09 16:37 UTC, ethanteague commented on docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
> +    $staff_no_bio = !empty($node->field_complete_biography_create) && $node->field_complete_biography_create->value === '0' ? TRUE : FALSE;
Yeah, dunno what I was thinking here. Fixed, @swirtSJW

2022-02-09 20:47 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      (!in_array($node->bundle(), $exclusion_types)) && !$staff_no_bio) {
This shows resolved, but I am not seeing the change.

2022-02-09 20:55 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +      (!in_array($node->bundle(), $exclusion_types)) && !$staff_no_bio) {
Apologies - forgot to add the file, @swirtSJW . Updated.

2022-02-10 14:30 UTC, swirtSJW approved these changes
Looks great.    Rebuilding and waiting on tests.

2022-02-10 14:30 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +    // Exclude staff pages without bios.
Nice!  Much more readable.

2022-02-10 19:21 UTC, swirtSJW approved these changes

2022-02-10 19:25 UTC, swirtSJW requested changes
Something in the logic is not right 
https://pr7940-cngpi3x0fnk4si3bx4r871ywwcr3sz4j.ci.cms.va.gov/oklahoma-city-health-care/staff-profiles/kevin-acers
![image](https://user-images.githubusercontent.com/5752113/153481709-6aa412f9-d9d1-4aef-85a3-28a543219167.png)

2022-02-10 20:25 UTC, ethanteague commented
Yep, that was it, @swirtSJW

2022-02-11 01:39 UTC, swirtSJW approved these changes
Checks out all good.  Nice work

2022-02-11 01:40 UTC, merged