VACMS-7969: Create office connect with us view mode and display in node view
department-of-veterans-affairs/va.gov-cms pull request #7979
Opened 2022-02-11 14:47 UTC by msbtterswrth

## Description

Relates to #7969 .

## Testing done
Viewed a benefits hub landing page in drupal

## Screenshots
New embedded teaser view: 
![image](https://user-images.githubusercontent.com/8375335/153612351-dd6a79ea-e83a-41e1-9241-72e83e68fe53.png)

no broken link errors
![image](https://user-images.githubusercontent.com/8375335/153612458-7fee9900-4098-4f9c-8612-04bc0fc1e4af.png)

## QA steps

As a cms user I can
1. View a benefits hub page (`/decision-reviews`) 
2. Then validate Acceptance Criteria from issue
- [x] No "Unpublished Page found" reports at the top of /decision-reviews or /health-care
- [x] Some rendering of Office "Connect with us" content within the Benefits Hub Landing Page node view

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-02-11 21:50 UTC, swirtSJW reviewed
This approach looks good.   One concern  Showing the pink unpublished on the content being pulled in.
![image](https://user-images.githubusercontent.com/5752113/153669418-b020cf07-c439-4c7b-8864-2b6057d714f7.png)

The FE is pulling this content regardless of its published status.  So the fact that it is unpublished/pink has no impact on what gets built and in some cases the editor has no control over the published state of that content.  In most cases we want the editors to be sensitive to the presence of pink, so I think this might cause undue stress.    What do you think removing the pink.

2022-02-14 17:37 UTC, msbtterswrth commented
@swirtSJW I kind of think we should leave it. Eventually I think those nodes will actually be published when the offices product gets up and going and so I think it's a bit superfluous to remove it. Plus I agree with 'show the truth' about things, since it _is_ unpublished.

2022-02-24 20:06 UTC, swirtSJW commented
@rachel-kauff    I'd be interested in your thoughts on the last few comments.
The TLDR is
We are surfacing content on Benefits hub landing pages that are "centralized" from office nodes that are not.... and likely will not be published.  However that centralized content (connect with us) is exposed to the front end pages reguardless of the office node's published status.  So the connect with us content is technically not published, but it shows up on the FE anyway.
My concerns are:
* Stressing editors out over unpublished (pink) status they can't control  (they are not the editors of the office node)
* Teaching them its ok to ignore pink.

2022-02-24 21:04 UTC, rachel-kauff commented
@swirtSJW @msbtterswrth I agree with Swirt -- I think this is very edge casey and sticking with our principles comes at too high a cost to editors in this particular situation. To most folks, the important thing about the pink is that it tells them that something is not gonna go live on VA.gov yet. In this case, it actually is/will go live so we should confuse them further with the technicalities of how Drupal is handling it.

2022-02-25 13:22 UTC, kevwalsh commented
Removing the pink (creating a "special case") feels like we're incurring a bit of technical debt, which i'm OK with, but what's the plan for managing that debt?

2022-02-25 16:36 UTC, swirtSJW commented
> Removing the pink (creating a "special case") feels like we're incurring a bit of technical debt, which i'm OK with, but what's the plan for managing that debt?
> 
> Comments in the css? An issue in the backlog?

This is a bit of tech debt. Using unpublished data on the FE is a pattern we have been able to avoid until now.   I don't know as there is a plan to resolve it unless/until we stop serving content to the FE that is not published.    I think comments in the CSS would be good enough to start.

2022-03-03 22:18 UTC, msbtterswrth commented
@swirtSJW I went ahead and just removed the unpublished class from the 'connect with us' template so we're not creating any special rules for the class itself, only the display. There were a bunch of conflicting upstream changes but I think I've got them all sorted out now.

2022-03-10 22:55 UTC, swirtSJW commented
> @swirtSJW I went ahead and just removed the unpublished class from the 'connect with us' template so we're not creating any special rules for the class itself, only the display. There were a bunch of conflicting upstream changes but I think I've got them all sorted out now.

I think that is a good solution.  To @kevwalsh concern here https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7979#issuecomment-1050849811  It is good to add notice that we are intentionally removing it from the template so that 
A) we know why it was removed
B) so our future selves know that it was not just a mistake and put it back.

I'll add it inline so we can call this done.

2022-03-10 22:58 UTC, swirtSJW commented on docroot/themes/custom/vagovclaro/templates/node/node--office--connect-with-us.html.twig
> + *     admins.
```suggestion
 *     admins. 
 *     NOTE: This is intentionally removed from this template so that 
 *     the content that is visible on VA.gov whether it is published
 *     or not, does no confuse editors by appearing unpublished.
```

2022-03-10 23:15 UTC, swirtSJW requested changes
Sorry, this can't go out as is.  
We are exchanging one set of red warnings for another
![image](https://user-images.githubusercontent.com/5752113/157770769-71f14795-0861-4a38-b744-51443770843a.png)

The rendering of the images and links as separate links does not meet accessibility requirements and the node link report is calling it out.  
We should not have two of the same links (one for the icon and one for the text.)
![image](https://user-images.githubusercontent.com/5752113/157770929-232b6606-0d53-4f81-9ea7-320fbe953a6f.png)



We should mimic what the FE is doing in terms of structure.   That meets A11y
![image](https://user-images.githubusercontent.com/5752113/157771037-49eeb756-711d-469c-a984-f4ef54aae101.png)

2022-03-14 12:37 UTC, msbtterswrth commented
@swirtSJW This appears to be a defect in the module itself. how would you prefer me to fix this? with a template override or putting a ticket in upstream to the module?

2022-03-21 16:59 UTC, swirtSJW commented
Ideally fixing it upstream if we can.   When you applied that patch failed to apply, did it reference the failing hunk(s) or give another error that would indicate why it it won't apply?  We may need to help re-roll that patch if it is a legit failure.

2022-03-21 17:48 UTC, msbtterswrth commented
@swirtSJW no message other than 'failed to apply' so I don't have any useful info unfortunately.

2022-03-24 22:15 UTC, swirtSJW commented on .gitignore
> +*.mno
Why is this being added?  and if it is supposed to be here, it should not be breaking the comment away from the .deb entry.

2022-03-24 22:17 UTC, swirtSJW commented on composer.lock
>          {
Seems odd to me that composer.json is specifying a new version of the module and there is no entry updated in the lock  file
![image](https://user-images.githubusercontent.com/5752113/160019299-d3816cb7-6239-45ca-881f-65f6c7790fc4.png)

2022-03-25 14:57 UTC, ethanteague commented on composer.lock
>          {
Looks like .lock is already on 2.8, @swirtSJW https://github.com/department-of-veterans-affairs/va.gov-cms/blob/2ae4998c97022405289d82da77a2d1d0360f68b2/composer.lock#L9876

2022-03-30 21:31 UTC, swirtSJW approved these changes
Looks good.  Nice work.
![image](https://user-images.githubusercontent.com/5752113/160934282-7db5ad60-5c68-4713-9a98-7972fabd780c.png)
![image](https://user-images.githubusercontent.com/5752113/160934304-30c7da52-f67a-4f63-9678-18b4123183da.png)

2022-03-30 21:32 UTC, merged