VACMS-6980: Create PDF audit view and update behat tests.
department-of-veterans-affairs/va.gov-cms pull request #8013
Opened 2022-02-14 19:07 UTC by msbtterswrth

## Description

Relates to #6980 .

## Testing done
Visited view page and searched for PDFs.

## Screenshots
![image](https://user-images.githubusercontent.com/8375335/153926525-408dacd7-45e0-4879-ba3a-94814553d5f4.png)

## QA steps

As a CMS admin, 
1. navigate to the new PDF audit (`/admin/content/pdf-audit`)
2. View the list of PDFs within the CMS
3. Then validate Acceptance Criteria from issue
- [ ] VA 508 office can access a list of all PDFs that have been added, via CMS, to VA.gov.
- [ ] Ideally this list exists as a view in CMS, but can also be exported by CSV
- [ ] Stretch: shows which user uploaded them, and to what Section.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-02-14 20:16 UTC, kevwalsh requested changes
Nice!

Seeing this in action helps me think through a few ACs
- [x] I think the path for view should be /admin/content/media/audit/pdfs, and the one for urls should be /admin/content/media/audit/image-alt, ideally with /admin/content/media as a parent menu item.
- [x] Direct access to the PDF URLs in audit
  - [ ] https://www.va.gov/files/YYYY-MM//[filename].pdf is listed as column beside the name. I believe YYYY-MM is date created but that probably needs to be double checked. 
  - [x] https://prod.cms.va.gov/[path-to-pdf] is listed as column
- [x] Exposed filter label should be "Name contains" not "Name"
- [x] Section should be linked. (minor but quick)

I'm also wondering if we need to investigate some of this data to see if "number of uses" is helpful, or misleading. See screenshot below. I'm guessing only one of each of these is actually available on www.va.gov.

<details><summary>Screenshot</summary>

<img width="1467" alt="PDF_Audit___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/153937970-4987867a-f659-442d-b923-6a7d53ac64f3.png">


</details>

2022-02-16 01:24 UTC, kevwalsh requested changes
A couple things, here's a screenshot of the UI bits. 
<img width="988" alt="Cursor_and_PDF_Audit___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/154178435-7256fcd1-cdc9-4947-9c3d-b3b36063f666.png">

2022-02-16 01:24 UTC, kevwalsh commented on composer.json
> +        "drupal/entity_media_usage": "^1.0",
I'd defer to Steve on this one, but i don't think we want to add a module if we're not enabling it.

2022-02-16 01:24 UTC, kevwalsh commented on config/sync/views.view.pdf_audit.yml
> +id: pdf_audit
Should we be putting all the media audits into one view? then the machine name should be media_audit, and we would put the alt text audit here too. Not a blocker for me, just a q.

2022-02-16 01:24 UTC, kevwalsh commented on config/sync/views.view.pdf_audit.yml
> +      header: {  }
Can we put the Number of results component, which is standard on most of our views?

2022-02-16 01:24 UTC, kevwalsh commented on config/sync/views.view.pdf_audit.yml
> +            text: "{% set public= 'public://' %}\r\n{% set local= '/' %} \r\n<a href=\"{{ uri|replace({ (public): local}) }}\">{{ uri|replace({ (public): local}) }}</a>"
I like this approach, if we are going to include web PDFs.
But 
- [ ] "Local" should be "CMS". 
- [ ] "Prod" should be "Web" or "Prod Web" or "www.va.gov".  (not sure which)

2022-02-16 14:14 UTC, msbtterswrth commented on config/sync/views.view.pdf_audit.yml
> +      header: {  }
added!

2022-02-16 14:15 UTC, msbtterswrth commented on config/sync/views.view.pdf_audit.yml
> +            text: "{% set public= 'public://' %}\r\n{% set local= '/' %} \r\n<a href=\"{{ uri|replace({ (public): local}) }}\">{{ uri|replace({ (public): local}) }}</a>"
I went with 'Web', that seemed to be the most plain language version of those options.

2022-02-16 14:16 UTC, msbtterswrth commented on composer.json
> +        "drupal/entity_media_usage": "^1.0",
good catch, I thought I got them both!

2022-02-16 14:23 UTC, msbtterswrth commented on config/sync/views.view.pdf_audit.yml
> +id: pdf_audit
We have another ticket for for improving views availability (#6759) in which I suggest a lot of path changes and reorganization. I think we could think through where everything lives holistically there.

2022-02-25 06:45 UTC, swirtSJW reviewed
QA step didn't match.  The view is here.
/admin/content/media/audit/pdfs

"Last changed on" ,    "Updated" is the pattern on other views.

2022-02-25 06:46 UTC, swirtSJW approved these changes

2022-02-25 12:06 UTC, merged