VACMS-6645: Create table audit view and behat tests.
department-of-veterans-affairs/va.gov-cms pull request #8109
Opened 2022-02-22 19:44 UTC by msbtterswrth

## Description

Relates to #6645 . Other ACs will be covered in the original ticket.

## Testing done

## Screenshots

## QA steps

As cms user
1. Visit the table audit (`/admin/content-tools/audits/table-audit`)
2. Then validate Acceptance Criteria from issue
- [ ]  Database queries (Drupal view?) for what nodes have tables, how many tables, what products those nodes belong to

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-02-25 04:26 UTC, swirtSJW commented
Given the great alpha sorting debacle of D9.3 this is going to need to be config imported and config exported again, other wise the next person to export will get an unanticipated surprise.

2022-02-25 04:34 UTC, swirtSJW commented
Also the style of this View needs to be synced up with the style of our other Views.  Consistency of patterns is important for architecture.
![image](https://user-images.githubusercontent.com/5752113/155654238-2bb4a525-a853-42ed-8d16-ae867974d214.png)

2022-02-25 21:08 UTC, msbtterswrth commented
Should be all set @swirtSJW, just waiting for tests now.

2022-02-25 22:10 UTC, swirtSJW commented
> Fwiw, the only views I found with that style of revision (Updated) content were the newer facility views. I went ahead and updated this to match but there are many many other views that don't have that style. I can add it to the list of things to update in the other 'improve views' ticket.

Maybe I am missing something.  Here's at least 6 that have it
![image](https://user-images.githubusercontent.com/5752113/155809743-83ce51ba-1b35-4b18-ac31-5da86f269d93.png)

Many of the ones that don't have it were intentional deviations that needed the ability to sort updated separate from user.  Others were either old or I slipped up on catching it when they came in.

2022-02-25 22:27 UTC, swirtSJW requested changes
This is shaping up nicely.  Nice work on the table display in the table.

I am sorry, I missed a couple things on final review.  In general we want to mimic admin/content unless there is a good reason to deviate.
- [x] results counter (see admin/content)
- [x] reset button (see admin/content)
- [x] section filter is not the right section filter.  (see admin/content)

![image](https://user-images.githubusercontent.com/5752113/155811280-779bd2fa-af27-44a5-8891-b56fc667379b.png)

![image](https://user-images.githubusercontent.com/5752113/155811301-b7589de1-a9f0-4ca0-b64f-cf75de8c1752.png)

2022-02-28 14:11 UTC, msbtterswrth commented
@swirtSJW good catch! This was such an old view, I made it before you showed me some things and I forgot it hadn't been updated!

2022-02-28 19:27 UTC, swirtSJW requested changes
![image](https://user-images.githubusercontent.com/5752113/156045741-03206924-c9e6-4c7a-8cc5-10769abdf17c.png)
@msbtterswrth  can you please add QA steps that you have run through so I that these kinds of things are tested and not left to chance of the reviewer.   The QA steps here presently only detect if the page exists.

2022-02-28 19:58 UTC, msbtterswrth commented
@steve my bad, I must not have committed my last change. Just pushed that up now and also updated the ACs to be a bit more verbose.

2022-03-02 22:44 UTC, swirtSJW requested changes
QA does not match QA step validation
Filter button text 
![image](https://user-images.githubusercontent.com/5752113/156462048-d660d233-b0b1-42c3-ad2c-c692a52f0b47.png)

Edit button next to title.
![image](https://user-images.githubusercontent.com/5752113/156462150-db447e6c-d8fd-4273-bb8d-1699feea66ea.png)

This pattern does not reflect existing pattern.  
![image](https://user-images.githubusercontent.com/5752113/156462343-f1768329-6357-42fe-9c57-f951981547d3.png)

2022-03-03 20:38 UTC, msbtterswrth commented
Updated. I realized also the ID column was missing from the ACs so that was built correctly just not documented correctly.

2022-03-03 21:48 UTC, swirtSJW commented on config/sync/views.view.table_audit.yml
> +          content: "<p><a href=\"admin/content/audit/tables-usage-audit.csv\" class=\"button\">Download CSV</a></p>\r\n\r\n<p>Displaying @start - @end of @total</p>"
This button does not work.
![image](https://user-images.githubusercontent.com/5752113/156658171-e38db76c-c0cc-48ed-83a6-170e4b08df7f.png)


 I don't see the button in the ACs so maybe it is not needed.  We either need to fix it or remove it.
If we are keeping it, please add a QA step to test the functionality of this button.

2022-03-03 22:01 UTC, swirtSJW requested changes
A couple things not working.  See code comments below.

This is why QA steps, not just ac's are important.

The bit about the edit button.  The majority of our other views have the edit button follow the title.  I do see we have one audit where it follows the id.  I think that was probably an oversight.   I am glad you started that doc because I think we want to prescribe the pattern as edit sits to the right of title.   I can't think of a good reason to have an exception for if there is an id.   Maybe there is??

2022-03-07 14:55 UTC, swirtSJW commented
I like the looks of this button as opposed to the csv download link at the bottom, when there is an attached View.  However the attached View picks up the filters from the View.  This button does not. It provides the whole thing, unfiltered.
![image](https://user-images.githubusercontent.com/5752113/157058121-33c87f05-7cee-4b16-bc3c-d0bcbfe6bf13.png)

2022-03-21 19:36 UTC, msbtterswrth commented
@swirtSJW I removed the nicer button in favor of the core attachment. I'll add a new ticket to explore how we can make that default csv button better for all views.

2022-03-23 01:50 UTC, swirtSJW approved these changes

2022-03-23 01:51 UTC, merged