VACMS-7660: Enable ehr fields.
department-of-veterans-affairs/va.gov-cms pull request #8110
Opened 2022-02-22 21:52 UTC by ethanteague

## Description
closes #7660
@EWashb - couple things:

1. If I change the collapsible fieldset to match the figma spec, we are going to be outside of the ootb Claro experience for other "Details" fieldsets, i.e.: making the collapsible toggle label a different color, and moving the help text `?` trigger to be inline with the label will be a different experience than the other Detail type fieldsets.
2. The node view for the EHR stuff is the same color as the other fieldsets, but you mentioned the experience on node view being identical to form view, but this will make the EHR field have a different appearance than other fieldsets in Claro theme.

Happy to do these things, just wanna make sure this is what you are after.

## Testing done
Visual / behat

## Screenshots
Form view for a non-admin
![image](https://user-images.githubusercontent.com/2404547/155224122-6f8671a9-d2a6-46d8-a0da-2cdb06d87023.png)

Form view for an admin
![image](https://user-images.githubusercontent.com/2404547/155224206-e98241fe-3873-42d3-b866-98716a6028d0.png)

Node view
![image](https://user-images.githubusercontent.com/2404547/155224224-48905a3c-6158-4fe3-81a2-f82da7f62f12.png)

## QA steps
 - [ ] As an admin, assign an editor to Pittsburgh Health Care (sections on user page)
 - [ ] As admin, go to `node/318/edit` and enter values for VA Health Connect phone number & Electronic health records system fields, visually verifying that the fields are editable, and appear as above in screenshot.
 - [ ] Save, and login as the user you assigned to Pittsburgh, visiting `node/318/edit` 
 - [ ] Visually verify the fields are not editable and appear as above in screenshot
 - [ ] Go to `/pittsburgh-health-care` and visually verify fields are present

2022-02-23 00:41 UTC, EWashb commented
@ethanteague 

1. I've been trying to hunt down where my confusion started. I was basing our Figma off of this demo environment:  https://main-eyjs0sncpqkjhpxgnkuhzayuve040hg6.demo.cms.va.gov/node/318/edit. That looks like where the collapsible field idea started. 

I think the best path forward is not to treat this field differently than what else is on the page. I also agree the tooltip in line here isn't the way to go. It would probably make more sense to have them on each field instead of inline with the label instead of creating a new pattern (that doesn't really make sense anyway).

2022-02-23 16:14 UTC, EWashb commented
After review, let's:

Have the field open to follow this pattern:
![Screen Shot 2022-02-23 at 10 13 18 AM](https://user-images.githubusercontent.com/90111970/155359829-93e4ca0c-3905-4ee8-9691-6fd092259b68.png)

Also, include the hyphens in the phone number. After that, I think we are all good to go! Nice work Ethan and thanks for the extra sleuthing :)

2022-02-23 18:03 UTC, swirtSJW requested changes
Have not functionally tested this... but wanted to call a couple things out.

2022-02-23 18:03 UTC, swirtSJW commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +  }
This is an odd pattern warping what should be a string to be the exception and the norm treating it as a bool.  It prevents providing a meaningful place to clarify why there is this odd bool check.  An if else allows for the clarification of warping the three argument function to really be a 4 arg function.

```suggestion
  if ($display_if_empty_field === TRUE) {
    // A really clear explanation of what this single exlusion is supposed to do.  (also add to docbloc arg description.)
    $has_field_value = TRUE;
  } else
    $has_field_value = !empty($node->get($display_if_empty_field)->value);
  }
```

2022-02-23 18:51 UTC, EWashb commented
@ethanteague let me know when you'd like me to take another look!

2022-02-24 13:53 UTC, ethanteague commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    // Creating this on the fly, so make sure it appears on bottom of form.
I shouldn't be using this anyway - it's specific to vet centers. Going to add to a new fieldgroup called ehr_info. I can add it to the ui, but it will be an empty fieldgroup and behaves strangely when I try to plug in the node view stuff on the node form (it serves as a catch for the external_content node view).

2022-02-24 13:54 UTC, ethanteague commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +    _va_gov_consumers_disable_external_content_editing($form, $form_state, TRUE);
Yeah, I'm with you - struggled with a way to do this without having to write a separate function.

2022-02-24 13:55 UTC, ethanteague commented on docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
> +  }
Yep, I know it's weird / clunky. Apologies, @swirtSJW. I struggled with a way of making this more elegant / not have to write an additional function.

2022-02-24 14:08 UTC, ethanteague commented
> @ethanteague let me know when you'd like me to take another look!

Please do, @EWashb

2022-02-24 15:02 UTC, EWashb commented
We are getting there! On the admin view, in the Electronic health records system dropdown "Cerner-staged" should be changed to "Converting to Cerner"

On the editor side, the tooltip should hyperlink "CMS helpdesk" to https://va-gov.atlassian.net/servicedesk/customer/portal/3/group/8/create/26

I followed the steps to update the Pittsburgh phone number and it is showing accurately on the **edit** screen, but those changes to the phone number and health records aren't showing on the **view**. It is only showing the old data on that **view** screen. 

Let me know if you have any questions :)

2022-02-24 19:23 UTC, EWashb commented
The only thing I'm seeing now is the phone number isn't using the dashes. After that, good to go from my perspective!
<img width="532" alt="Screen Shot 2022-02-24 at 1 13 51 PM" src="https://user-images.githubusercontent.com/90111970/155592562-f608afbb-287c-4cee-99d6-58dd96d279e2.png">

2022-02-24 23:34 UTC, swirtSJW reviewed
Some things... not sure if they are issues.
![image](https://user-images.githubusercontent.com/5752113/155625132-12f40fe9-dc0a-41f6-af4d-6d04fd3b4fd3.png)

![image](https://user-images.githubusercontent.com/5752113/155625150-6cf31bb6-4347-4151-9a9e-7628a4b1e62b.png)

This health connect phone is going to be data we are sending to lighthouse.  I think we need some guardrails on its structure.

2022-02-25 03:50 UTC, swirtSJW commented
@ethanteague  I am probably missing something obvious.    Why  can't we re-use the tooltip field group we built for this exact scenario that we are using on facilities?  

![image](https://user-images.githubusercontent.com/5752113/155650038-4d1c59e2-ca45-4ebf-9f15-0cd35d27a80c.png)


![image](https://user-images.githubusercontent.com/5752113/155650052-52588302-6090-486a-8be4-007ecc57d9f6.png)

2022-02-25 03:56 UTC, swirtSJW commented
Same with node view.
![image](https://user-images.githubusercontent.com/5752113/155650786-edd23b9e-3436-4bf6-ac82-8e5234666516.png)



![image](https://user-images.githubusercontent.com/5752113/155650769-4f20d061-414f-47d7-b082-a4cef6618f21.png)

2022-02-25 04:21 UTC, swirtSJW commented
Sorry I found the tool tip in the external-content view mode.   I just may have missed several iterations on the design.  I thought we were largely making this behave like other external content treatment both on node view and edit.  I was expecting to see tool tips on the node view like this
![image](https://user-images.githubusercontent.com/5752113/155652780-298d8ad1-aac0-4c27-803e-85fa2dd8de5f.png)

But I guess we are either starting a new pattern or going to alter the existing on later iterations.

I was also expecting the  view for admins to still have a bit of warning that this is centralized and is generally a different kind of content than all the rest.    We aren't in the content that much. so it helps to see that context, even for admins.

2022-02-25 05:20 UTC, EWashb commented
> * https://pr8110-pstie3arktykejajrrgnhy8oyrg9idld.ci.cms.va.gov

@swirtSJW you're right. I dropped the ball on the editor view node. It would be best to have the edit and view nodes for editors appear similar with the same tooltip treatment.

For admins, I didn't consider that point of view about surfacing the context of that content. There are still some weeks before this goes live and I would like a chance to iterate on this if possible. 

I appreciate your perspective on this!

2022-02-25 13:13 UTC, ethanteague commented
> @swirtSJW you're right. I dropped the ball on the editor view node. It would be best to have the edit and view nodes for editors appear similar with the same tooltip treatment.
> 
> For admins, I didn't consider that point of view about surfacing the context of that content. There are still some weeks before this goes live and I would like a chance to iterate on this if possible.
> 
> I appreciate your perspective on this!

Nah, that's my bad, @EWashb . You were saying what @swirtSJW is saying when you talking about the node view being identical to the form view. Just pushed up a revision that makes the node view look like this: 
![image](https://user-images.githubusercontent.com/2404547/155721040-ad413db9-a886-46ab-b93f-3fd0e4530069.png)

2022-02-25 15:40 UTC, swirtSJW submitted a review, later dismissed
This looks quite good and is mergeable when tests complete.

Tickets are being created for 
* phone number format enforcement / validation.
* refinement of display for admin

2022-02-26 12:33 UTC, swirtSJW approved these changes

2022-02-26 12:34 UTC, merged