VACMS-7995: Remove "Entity Embed" module from code base
department-of-veterans-affairs/va.gov-cms pull request #8169
Opened 2022-02-25 20:21 UTC by netboss

- Removed the "Entity Embed" module from code base.

## Description

closes #7995 

## Testing done
Passes all tests

## Screenshots
![VACMS-7995-Entity-Embed-module-removed](https://user-images.githubusercontent.com/846871/155795612-58652c18-4565-4753-b128-0349110057ff.png)

## QA steps

As user administrator
1. Go to `/admin/modules` and:
    - [ ] Enter "entity embed" in the filter to verify and confirm that the module isn't there any more

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-02-25 21:45 UTC, swirtSJW requested changes
This looks good but there is one rollback in the composer.lock that needs fixing.

2022-02-25 21:45 UTC, swirtSJW commented on composer.lock
> +    "plugin-api-version": "2.1.0"
I don't think we want to be downgrading this.

2022-02-25 21:48 UTC, netboss commented on composer.lock
> +    "plugin-api-version": "2.1.0"
@swirtSJW 
Should I adjust that manually?

2022-02-28 16:56 UTC, netboss commented
@swirtSJW 
This one passed all tests and should be ready to merge.

2022-02-28 21:36 UTC, swirtSJW approved these changes

2022-02-28 21:36 UTC, swirtSJW commented
Module uninstall has made it to prod, so this is now clear for merge.

2022-02-28 21:37 UTC, merged