VACMS-8048: Allow authenticated users to export CSV of users
department-of-veterans-affairs/va.gov-cms pull request #8250
Opened 2022-03-03 21:33 UTC by netboss

- Created the new CSV display and configure it:
    - Removed "section" filter
    - Adjusted permission to be by role authenticated user
    - Updated the CSV display path to /admin/people/vacms-all-users-export.csv
    - Added the footer to the people main display (which later remove because the CSV icon was showing twice)
- Updated the Drupal spec tool and then updated the behat test.

## Description

closes #8048 

## Testing done
Passes all tests

## Screenshots

## QA steps

As user authenticated user
1. Go to `/admin/people/vacms-all-users-export.csv?page&amp;_format=csv` to verify and confirm that the CSV download is accessible

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-03-03 22:06 UTC, swirtSJW commented
I think we want to expand these QA steps out for a couple different user rolls to make sure it works for everyone.

We might also add some test steps for different variations on the filters that were requested to support in the issue
![image](https://user-images.githubusercontent.com/5752113/156660665-47eca5ae-39b6-460c-8725-ecf3aa6373ed.png)

2022-03-04 22:46 UTC, swirtSJW requested changes
This default treatment from the Views is pretty confusing
![image](https://user-images.githubusercontent.com/5752113/156850151-b5cdf7aa-367d-43f9-a73b-80ba6447778e.png)

I like the pattern @msbtterswrth has established with putting something like this in the top of the view header resulting in a look like this.
![image](https://user-images.githubusercontent.com/5752113/156850503-72205df0-510e-4b4c-8d47-27227ca929cc.png)

```
<div><a href="/admin/people/vacms-all-users-export.csv" class="button">Download CSV of all users</a></div>
```
And then change the "Attach to:" be none


I think a couple things got misconfigured, see below.

2022-03-07 15:50 UTC, netboss commented on config/sync/views.view.user_admin_people.yml
> +    - user.role.authenticated
@swirtSJW 
Weird, in my local this is correctly set. Both the page and data_export_1 displays have their permissions set to: `Access: Permission | Administer users`.

2022-03-07 15:53 UTC, netboss commented on config/sync/views.view.user_admin_people.yml
> -          exposed: true
@swirtSJW 
Ah, I see the problem. The "Expose this filter to visitors, to allow them to change it" checkbox was unchecked for both the page and data_export_1 displays. It must have been when I was in the process of removing it from the new data_export_2 where I first tried "hiding" it by unchecking the above checkbox (and probably did that for all displays). Fixed it. Will push soon.

2022-03-07 15:55 UTC, netboss commented on config/sync/views.view.user_admin_people.yml
> +          disable_sql_rewrite: true
@swirtSJW 
This was my mistake. I thought I did this to the data_export_2 display only. My bad. Fixed.

2022-03-07 17:58 UTC, swirtSJW commented
There are a couple related patches that allow for differentiating the duplicate download buttons.
https://www.drupal.org/project/views_data_export/issues/3200051
https://www.drupal.org/project/views_data_export/issues/2943895

2022-03-07 18:28 UTC, netboss commented
> There are a couple related patches that allow for differentiating the duplicate download buttons. https://www.drupal.org/project/views_data_export/issues/3200051 https://www.drupal.org/project/views_data_export/issues/2943895

@swirtSJW 
I already added the CSV download button to the view's header. See screen shot:
![VACMS-8048_people_new_CSV_download_button](https://user-images.githubusercontent.com/846871/157095179-e083df66-204d-4af7-ac00-c321570f8f0f.png)

Do we want to use the above or use one of the two available patches?

2022-03-08 21:28 UTC, swirtSJW commented
@netboss  If there are new things to test (like the functioning of a new button) lets add specific QA steps to make sure things are working.

2022-03-08 21:33 UTC, swirtSJW commented
I am not seeing the new button on this PR environment.
I am only seeing 
![image](https://user-images.githubusercontent.com/5752113/157328663-95698ce0-1e84-408b-a9c1-49069a2d75b6.png)


and 

![image](https://user-images.githubusercontent.com/5752113/157328713-ab1fc13f-a0ba-4084-9373-d1abdacd01cc.png)

Did you push your latest changes?

2022-03-08 22:58 UTC, swirtSJW commented
@kevwalsh I confirmed that as any authed user (like RS) I am able to access the download directly if I am provided a link 
https://pr8250-1wt1r0qcw1cajbgtbtamv3h1eazkinzz.ci.cms.va.gov/admin/people/vacms-all-users-export.csv?page&_format=csv

The button is visible to anyone who can access admin/people but that set of users is limited by role.

![image](https://user-images.githubusercontent.com/5752113/157340045-df722cb5-e252-47a0-aa0d-de504de7ba78.png)

2022-03-09 20:49 UTC, swirtSJW submitted a review, later dismissed

2022-03-10 17:20 UTC, kevwalsh submitted a review, later dismissed
We should be able to specify the drupal role as a parameter in the csv download.

2022-03-10 20:48 UTC, swirtSJW commented
@netboss  It looks like your force push confused tugboat again and it stalled out.  
I just rebuilt it to get things started up again.
![image](https://user-images.githubusercontent.com/5752113/157751860-b4462049-01cb-4d38-95c4-dbcc23d8c1e7.png)

2022-03-10 21:24 UTC, swirtSJW approved these changes
QA checks out and includes the role filter query param.

2022-03-10 22:12 UTC, merged