[WIP] VACMS-8327: Install HTML tag usage module to audit <em> tags.
department-of-veterans-affairs/va.gov-cms pull request #8332
Opened 2022-03-14 14:43 UTC by msbtterswrth

## Description

Relates to #8327 . (or closes?)

## Testing done

## Screenshots
![image](https://user-images.githubusercontent.com/8375335/158195456-bd370504-52e0-4a26-8158-a90a24ae7418.png)

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As cms admin
1. I can got to the HTML usage audit (`admin/reports/html_tag_usage`) and
   - [ ] Validate that the audit runs
2. Then click on the <em> count column and
   - [ ] Validate that the modal shows me instances of <em> usage
3. Then validate Acceptance Criteria from issue
   - [ ] a 
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-03-19 04:47 UTC, ethanteague commented
Filters and csv
![image](https://user-images.githubusercontent.com/2404547/159107276-7e20b20f-3ea3-4fc5-ae8a-7ca71f3adb90.png)

2022-03-23 17:28 UTC, swirtSJW commented
A beta module with a notice like this is a bit concerning
![image](https://user-images.githubusercontent.com/5752113/159759881-0c763111-cc87-4b8d-90c1-04536f0e0df1.png)

2022-03-23 17:30 UTC, ethanteague commented
> A beta module with a notice like this is a bit concerning ![image](https://user-images.githubusercontent.com/5752113/159759881-0c763111-cc87-4b8d-90c1-04536f0e0df1.png)

Yeah. Wonder if we should add an environment check to enable / disable, @swirtSJW ?

2022-03-23 17:43 UTC, swirtSJW requested changes
A couple niggly bits.  

@msbtterswrth  @ethanteague  @kevwalsh 
On the bigger picture of this being not recommended for production and in beta.    Do we need this enabled on prod staging and dev?

Can we just enable this on local or tugboat when needed to run the report?

2022-03-23 17:43 UTC, swirtSJW commented on config/sync/core.extension.yml
> +  ckeditor5: 0
This seems unexpected.

2022-03-23 17:43 UTC, swirtSJW commented on docroot/modules/custom/va_gov_db/va_gov_db.install
> + * Fix field_error_message on paragraph to add text format when value is NULL.
This is misleading.  It is not fixing the value when something is null.   It is forcing a value in for a specific entity id.

2022-03-23 17:45 UTC, ethanteague commented on docroot/modules/custom/va_gov_db/va_gov_db.install
> + * Fix field_error_message on paragraph to add text format when value is NULL.
Dangit - I _knew_ this was a bad message, but I got lazy and didn't clean it up, @swirtSJW

2022-03-23 17:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_db/va_gov_db.install
> +  \Drupal::logger('va_gov_db')->info('Update field_error_message revision to full_html');
Same here.  Should come after.

2022-03-23 18:33 UTC, ethanteague commented on docroot/modules/custom/va_gov_db/va_gov_db.install
> +  \Drupal::logger('va_gov_db')->info('Update field_error_message to full_html');
Yeah.....not sure why I did this. Will fix

2022-03-23 21:15 UTC, swirtSJW commented on config/sync/core.extension.yml
> +  ckeditor5: 0
This is still here.

2022-03-23 22:12 UTC, swirtSJW requested changes

2022-03-25 03:49 UTC, swirtSJW approved these changes
Nice work.

2022-03-25 03:49 UTC, swirtSJW commented on composer.json
> +                "3270450 - Add csv generator and filters": "https://www.drupal.org/files/issues/2022-03-21/add-filters-and-csv-5.patch"
Link to this issue on upstream module https://www.drupal.org/project/html_tag_usage/issues/3270450

2022-03-25 03:49 UTC, swirtSJW commented on composer.json
> +                "3270450 - Add csv generator and filters": "https://www.drupal.org/files/issues/2022-03-21/add-filters-and-csv-5.patch"
Nice work on this patch.

2022-03-25 03:49 UTC, merged