VACMS-8257: Adjust content admin role permissions
department-of-veterans-affairs/va.gov-cms pull request #8381
Opened 2022-03-17 20:24 UTC by netboss

- Updated various user roles "Media" related permissions.
- Updated various user roles permissions in PHPUnit test: /tests/phpunit/Security/RolesPermissionsTest.php.

## Description

closes #8257 

## Testing done
Passes all tests

## Screenshots
![VACMS-8257-content-admin-add-media](https://user-images.githubusercontent.com/846871/158888931-f0dbb3eb-8fa0-4f9b-8052-c7f05c04c813.png)

## QA steps

As user content admin (eg beth.potts@va.gov)

1. Go to /node/add/vet_center
    - [ ] Verify and confirm you can add a Facility photo

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-03-22 22:25 UTC, swirtSJW requested changes
@netboss  There are a lot of changes here that are not covered by the issue or the testing steps.  Were there AC's added that need to be noted somewhere?

2022-03-22 22:25 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> -    - node.type.promo_banner
These removals are not covered by the ACs and seem unexpected to me.

2022-03-22 22:25 UTC, swirtSJW commented on config/sync/user.role.content_admin.yml
> -    - va_gov_menu_access
This removal is not covered by the ACs and is unexpected.

2022-03-22 22:25 UTC, swirtSJW commented on config/sync/user.role.content_editor.yml
> +    - node.type.vha_facility_nonclinical_service
This addition is not covered by the ACs and is unexpected.

2022-03-22 22:25 UTC, swirtSJW commented on config/sync/user.role.content_publisher.yml
> +    - node.type.vamc_system_register_for_care
These additions are not covered by the ACs and is unexpected.

2022-03-22 22:25 UTC, swirtSJW commented on config/sync/user.role.content_publisher.yml
> +    - node.type.vha_facility_nonclinical_service
This addition is not covered by the ACs and is unexpected.

2022-03-22 22:25 UTC, swirtSJW commented on config/sync/user.role.content_reviewer.yml
> +    - node.type.vamc_system_register_for_care
These additions is not covered by the ACs and is unexpected.

2022-03-22 22:25 UTC, swirtSJW commented on config/sync/user.role.content_reviewer.yml
> +    - node.type.vha_facility_nonclinical_service
This addition is not covered by the ACs and is unexpected.

2022-03-22 22:25 UTC, swirtSJW commented on config/sync/user.role.vamc_content_creator.yml
> +    - node.type.vha_facility_nonclinical_service
This addition is not covered by the ACs and is unexpected.

2022-03-23 13:41 UTC, netboss commented on config/sync/user.role.content_admin.yml
> -    - node.type.promo_banner
@swirtSJW 
Restored those two configurations

2022-03-23 13:41 UTC, netboss commented on config/sync/user.role.content_admin.yml
> -    - va_gov_menu_access
@swirtSJW 
Restored the `va_gov_menu_access` configuration

2022-03-23 13:43 UTC, netboss commented on config/sync/user.role.content_publisher.yml
> +    - node.type.vamc_system_register_for_care
@swirtSJW
Removed those three configurations

2022-03-23 13:43 UTC, netboss commented on config/sync/user.role.content_publisher.yml
> +    - node.type.vha_facility_nonclinical_service
@swirtSJW
Removed the `node.type.vha_facility_nonclinical_service` configuration

2022-03-23 13:44 UTC, netboss commented on config/sync/user.role.content_reviewer.yml
> +    - node.type.vamc_system_register_for_care
@swirtSJW
Removed those three configurations

2022-03-23 13:44 UTC, netboss commented on config/sync/user.role.content_reviewer.yml
> +    - node.type.vha_facility_nonclinical_service
@swirtSJW
Removed the `node.type.vha_facility_nonclinical_service` configuration

2022-03-23 13:45 UTC, netboss commented on config/sync/user.role.vamc_content_creator.yml
> +    - node.type.vha_facility_nonclinical_service
@swirtSJW
Removed the node.type.vha_facility_nonclinical_service configuration

2022-03-25 02:52 UTC, swirtSJW approved these changes

2022-03-25 02:53 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/160045231-76893f1d-5f2a-4c16-8480-0e6de604a1a5.png)

2022-03-25 02:53 UTC, merged