VACMS-8400: Add office hours widget to service location paragraph.
department-of-veterans-affairs/va.gov-cms pull request #8435
Opened 2022-03-22 18:38 UTC by ethanteague

## Description
closes #8400

## Testing done
Visual / Behat

## Screenshots
As an editor / content admin not on a `VAMC Facility Non-clinical Service` page
![image](https://user-images.githubusercontent.com/2404547/159573466-0ca2118d-32f3-4706-86b3-7f6e198f207d.png)

As an admin not on a `VAMC Facility Non-clinical Service` page
![image](https://user-images.githubusercontent.com/2404547/159573545-a7266b00-e7af-46ca-9d14-86950e85ac91.png)

As an editor / content admin on a `VAMC Facility Non-clinical Service` page
![image](https://user-images.githubusercontent.com/2404547/159573096-4076d38f-4679-47ad-a07e-c62c870a4f85.png)

Node view
![image](https://user-images.githubusercontent.com/2404547/159573412-8bfabc9b-30ff-45db-92c4-450780deb38a.png)

## QA steps
**Admin test**
 - [x] Non clinical service: go to `https://pr8435-cunes7rsm9rifo1ypfj5fnybl6l0trl1.ci.cms.va.gov/node/44181/edit`and visually two hours fieldsets appear in the hours section (one table, the other in office hours html5 time inputs format - display will be funky until we get rid of the old table field)
 - [x] Health service: go to `https://pr8435-cunes7rsm9rifo1ypfj5fnybl6l0trl1.ci.cms.va.gov/node/1017/edit` and visually two hours fieldsets appear in the hours section (one table, the other in office hours html5 time inputs format - display will be funky until we get rid of the old table field)
 
**Content Admin / Editor tests**
 - [x] As the same administrator, go to `user/34/workbench_access` and assign Ryan to Chillicothe (this is where a `VAMC Facility Non-clinical Service` exists / can be used for testing)
 ~- [ ] As Ryan.stubblebine@va.gov, go to `node/1017/edit` and visually verify the `Use the facility hours` field does not show hours table when option is set to `Provide specific hours for this service`~ This is a `VAMC Facility Health Service` and is covered by `VAMC Facility Health Service` bundle test in next step
 - [x] as RS  go to this page https://pr8435-cunes7rsm9rifo1ypfj5fnybl6l0trl1.ci.cms.va.gov/node/1058/edit and validate he can still edit / add hours to the facility health service.
 - [x] Login back in as administrator, go to `user/34/edit` and assign Ryan the `Content admin` role
 - [x] Login again as Ryan.stubblebine@va.gov, go to `/node/44181/edit` and visually verify the `Use the facility hours` field shows a single hours table when option is set to `Provide specific hours for this service`
 - [x] on node view of https://pr8435-cunes7rsm9rifo1ypfj5fnybl6l0trl1.ci.cms.va.gov/chillicothe-health-care/locations/chillicothe-va-medical-center-0  no one can see the output from the tablefield.
 - [x] Add some time data to the new hours field, and save
 - [x] Visually verify the node view looks reasonably formatted.
 - [x] time is in 12 hr format matching Vet center cap

**QA Copied from closed pr https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8430**

1. VAMC Facility
2. VAMC System Billing and Insurance
3. Vet Center
4. Vet Center - CAP
5. Vet Center - Mobile
6. Vet Center - Outstation

As cms admin viewing office hours field for the above types, confirm the following settings for office hours field
- [ ] 12 hour time with am/pm
- [ ] Has comments field enabled with HTML disallowed
- [ ] Time increments by 1 minute increments
- [ ] Hours validation is checked

2022-03-22 19:07 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +      unset($form['subform']['field_office_hours']);
I think this logic is forgetting the part about hiding the tablefield version of the field.

2022-03-22 22:01 UTC, swirtSJW requested changes
This is not complete but I found this wich is going to require a logic change.

2022-03-22 22:23 UTC, ethanteague commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +      unset($form['subform']['field_facility_service_hours']);
:+1: updated

2022-03-23 15:45 UTC, swirtSJW submitted a review, later dismissed
QA checks out for me.   
FInal issue of time format resolved 
![image](https://user-images.githubusercontent.com/5752113/159739320-c0520254-da37-494e-b8bd-c632b31bbaa1.png)

Nice work.  (just waiting on tests to complete)

2022-03-23 18:52 UTC, swirtSJW commented
I think tests on this fell down due to todays github flakyness

2022-03-23 19:35 UTC, ethanteague commented
Updated time pickers to html5 per slack convo https://dsva.slack.com/archives/CT4GZBM8F/p1648062097027019
![image](https://user-images.githubusercontent.com/2404547/159781555-37b1a2ed-eb64-4a90-96e7-85f23ba23616.png)
![image](https://user-images.githubusercontent.com/2404547/159781576-5b010041-d676-43c8-8aae-dbee7ed41afe.png)

2022-03-23 19:49 UTC, kevwalsh submitted a review, later dismissed
There should be only Comment label per table. Not one per row. 


<details><summary>should look like this</summary>

​
![image](https://user-images.githubusercontent.com/643678/159783713-f225c4ce-50d8-4c04-847c-a4293642d7ac.png)


</details>

2022-03-23 20:12 UTC, ethanteague commented
> 

Do you know who created that table, @kevwalsh? I can't find the magic that is creating it (not in tpl / custom code)

2022-03-23 22:34 UTC, swirtSJW requested changes
Somethings not right
Yesterday when we had the html5 only the 15 min increments were showing (which was perfect)
![image](https://user-images.githubusercontent.com/5752113/159807094-c34f74a1-69c1-4549-9513-db1a92c9f3ba.png)
Today we have all numbers.... but if you don't choose one of the quarters, it fails validation.
![image](https://user-images.githubusercontent.com/5752113/159807246-85a8b788-b9c7-41d2-aabb-f130bb40654f.png)

2022-03-24 15:51 UTC, swirtSJW commented on config/sync/core.entity_view_display.paragraph.service_location.default.yml
> +      time_format: G
should this be 'h' like all the others?

2022-03-24 15:54 UTC, swirtSJW commented on config/sync/core.entity_view_display.paragraph.service_location.default.yml
> +      time_format: G
or actually shouldnt they all be 'g '  `12-hour format of an hour without leading zeros`?

2022-03-24 15:59 UTC, ethanteague commented on config/sync/core.entity_view_display.paragraph.service_location.default.yml
> +      time_format: G
Yeah, I think `g` is correct.

2022-03-24 16:18 UTC, swirtSJW commented
It looks like validation is not working right as it should have prevented this
![image](https://user-images.githubusercontent.com/5752113/159962087-8014e222-f07a-4b78-85fc-4718feccef45.png)
I validated the setting is right, 
![image](https://user-images.githubusercontent.com/5752113/159962169-e55986b1-1bf6-4717-916f-deeb32eda858.png)
So I am going to call this an upstream issue  and not block this PR on it.

2022-03-24 16:29 UTC, swirtSJW approved these changes
Checks out.
There are two issues noticed but are not regressions introduced here
1) time validation of start time that is after end time does not happen (most likely an upstream issue) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8469
2) time display on vamc facility pages is in 24 hr time. (Most likely a view mode setting) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8468
Due to urgency we are not going to block this PR on either issue.  Will follow up later.

2022-03-24 17:26 UTC, swirtSJW commented
Woot!  
![image](https://user-images.githubusercontent.com/5752113/159974950-a0803d55-a92e-4bb6-80f1-8ec778497af8.png)

2022-03-24 17:26 UTC, merged