[draft] VACMS-8346 testing
department-of-veterans-affairs/va.gov-cms pull request #8448
Opened 2022-03-23 17:34 UTC by tjheffner

## Description

Relates to #_issueid_. (or closes?)

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that 
2. Then 
   - [ ] Validate that 
3. Then validate Acceptance Criteria from issue
   - [ ] a 
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-03-23 19:22 UTC, ethanteague reviewed
Code looks fine, but storybook container isn't wanting to start, @tjheffner

2022-03-23 19:26 UTC, tjheffner commented
@ethanteague Sorry, maybe try `ddev poweroff` instead of `ddev stop`, and then try `ddev start` again? It should pick up the new service config and build the appropriate container. no lando support btw. What's the error you're seeing?

2022-03-23 19:42 UTC, ethanteague commented
> @ethanteague Sorry, maybe try `ddev poweroff` instead of `ddev stop`, and then try `ddev start` again? It should pick up the new service config and build the appropriate container. no lando support btw. What's the error you're seeing?

It's beefing that it can't find postcss module, @tjheffner

2022-03-23 20:07 UTC, ethanteague approved these changes
QA'd in real time with, @tjheffner

2022-03-23 21:56 UTC, ElijahLynn commented
We have changes pushed that have the storybook-* prefix routing to the static Storybook folder now. We had to manuallly test it though and it won't work until the base preview image is rebuilt, which we should do after merge for a final test. 

![image](https://user-images.githubusercontent.com/1504756/159802679-06d8580f-3319-42c2-8862-67871c8550be.png)
![image](https://user-images.githubusercontent.com/1504756/159802689-9cbf07b8-a7ea-402b-960f-e8982236e5fa.png)

2022-03-23 22:22 UTC, ElijahLynn commented on .tugboat/config.yml
> +        - composer va:ds:storybook
We discussed in https://dsva.slack.com/archives/C02HX4AQZ33/p1648073995874339?thread_ts=1647896815.941809&cid=C02HX4AQZ33 to move this to the 'online' stage so the build time won't add to environment creation time.

2022-03-23 22:22 UTC, ElijahLynn commented on .tugboat/config.yml
> +        - composer va:ds:storybook
We discussed in https://dsva.slack.com/archives/C02HX4AQZ33/p1648073995874339?thread_ts=1647896815.941809&cid=C02HX4AQZ33 to move this to the 'online' stage so the build time won't add to environment creation time.

2022-03-25 02:20 UTC, swirtSJW commented on .tugboat/config.yml
> +        # setup to ensure branch is up-to-date.
Nice.  Good stewardship here.

2022-03-25 02:43 UTC, swirtSJW requested changes
This all looks very good @tjheffner.   I think it should be considered as mergeable for demo tomorrow, even though I can't merge it until the composer.json and lock are worked out.  

So go ahead and plan to demo it from local or tugboat tomorrow and then we can merge it after the composer thing is resolved.    (assuming the answers to my two questions are inline with my assumptions)

2022-03-25 02:43 UTC, swirtSJW commented on composer.json
> +        "drupal/components": "^3.0@beta",
examined https://www.drupal.org/project/components
I am assuming we need the 50% improvement of the 3-beta rather than the full release 2.4.

2022-03-25 02:43 UTC, swirtSJW commented on composer.lock
> +            "version": "v0.0.2912",
This should not be here as it is regressing us.

2022-03-25 02:43 UTC, swirtSJW commented on composer.lock
> +                "source": "https://github.com/department-of-veterans-affairs/content-build/tree/v0.0.2912"
ALso a regress.   I would bring in the composer.lock  and composer.json from main and then re-run the composer require command you ran to bring in drupal/components  the first time.

2022-03-25 02:43 UTC, swirtSJW commented on config/sync/core.extension.yml
> +  components: 0
Am I right in thinking  that even though storybook is not used on BRD that drupal/components module would still be needed to be enabled on BRD for allowing things in templates to still work?

2022-03-25 03:43 UTC, tjheffner commented on composer.lock
> +            "version": "v0.0.2912",
ah good catch! this is my bad, have rebased a number of times. will fix this in the morning

2022-03-25 03:45 UTC, tjheffner commented on config/sync/core.extension.yml
> +  components: 0
yeah, for the theme drupal/components module will need enabled & `composer va:ds:drupal` command will need run (it runs as part of `va:theme:compile`, so shouldn't have to do anything else beside enable the module & clear cache).

storybook is separate from that, should be fine

2022-03-25 03:55 UTC, swirtSJW commented
Seems like you may have had a rebase conflict  issue
![image](https://user-images.githubusercontent.com/5752113/160051240-dc935aa8-6442-4805-88e8-e3ee410447da.png)

2022-03-25 17:47 UTC, tjheffner commented
Closed for https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8482 which is a cleaner rebase off of main.

2022-03-25 17:47 UTC, closed without merging