VACMS-8315: Change "Last access" and "Member since" fields date/time format
department-of-veterans-affairs/va.gov-cms pull request #8449
Opened 2022-03-23 18:50 UTC by netboss

- Changed "Last access" and "Member since" fields date/time format in "People" view "data_export_2" display.

## Description
closes #8315 

## Testing done
Behat, PHPUnit and visual

## Screenshots
![VACMS-8315-Member-since-and-Last-access-cols-datetime-updated](https://user-images.githubusercontent.com/846871/159773354-4392d2ff-11f3-4eb3-8083-e1853443c569.png)

## QA steps
As user administrator
1. Go to `/admin/people` and
   - [ ] Click the "Download CSV of all users" button to download a CSV report
   - [ ] Then verify and confirm the "Member since" and "Last access" columns date/time format is like this: `YYYY-MM-DD HH:MM`, e.g.: 2022-03-8 9:35am

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-03-23 20:01 UTC, netboss commented
@swirtSJW 
This is ready for initial review.

2022-03-23 22:43 UTC, swirtSJW commented
@kevwalsh which is more critical, readability of the data or time sort?   If proper sort is more important, then it needs to use 24hr time 
![image](https://user-images.githubusercontent.com/5752113/159808154-76403790-10bb-407a-a6ed-679f05510a50.png)

2022-03-23 22:44 UTC, swirtSJW commented
Also we may want to alter to treat 0 as empty
![image](https://user-images.githubusercontent.com/5752113/159808440-124fd084-f061-4441-9162-d41c2e0d137b.png)

2022-03-24 01:29 UTC, kevwalsh commented
> Also we may want to alter to treat 0 as empty 

Yes. Zero should be re-written as "Never" when empty.  I'm 90% sure it used to be that way, so this regression came in at some point. 

> @kevwalsh which is more critical, readability of the data or time sort? If proper sort is more important, then it needs to use 24hr time

Yeah I think 24 hour time here is appropriate, which i believe has leading zeros for 09:00:00am for sorting purposes.

2022-03-24 15:02 UTC, swirtSJW commented
@netboss  Going by your updated screen shot, this  seems to not be sorting right, but I am not sure how you sorted to get that in your spreadsheet 
![image](https://user-images.githubusercontent.com/5752113/159946145-0529ef44-36cc-4599-b82d-126ad1ea2dbc.png)

2022-03-24 15:04 UTC, swirtSJW commented
My guess is that you just didn't sort in spreadsheet after importing it?

2022-03-24 16:25 UTC, netboss commented
> My guess is that you just didn't sort in spreadsheet after importing it?

@swirtSJW 
Yeah, I didn't sort, just took a screen shot of it to show the updated date/time format.

2022-03-25 02:15 UTC, swirtSJW requested changes
Your change to format, broke your string matching for empty.
![image](https://user-images.githubusercontent.com/5752113/160041268-a4979fcf-7c54-45eb-a1d1-e411d6ed071b.png)

2022-03-25 02:15 UTC, swirtSJW commented on config/sync/views.view.user_admin_people.yml
> +            text: "{% if access == \"1970-01-1 00:00am\" %}Never\r\n{% else %} {{access}}\r\n{% endif %}"
This is really brittle.  A change to the  output like you just made, broke the rewriting.  
This should really be based on empty, treating zero as empty and having different rewriting if it is empty, not on twig logic doing string matching in the rewrite.

2022-03-25 12:38 UTC, netboss commented on config/sync/views.view.user_admin_people.yml
> +            text: "{% if access == \"1970-01-1 00:00am\" %}Never\r\n{% else %} {{access}}\r\n{% endif %}"
@swirtSJW 
Yes, I agreed, too brittle. But this conditional overwrite was already in place and I just "reused". When I did the first date/time format adjustment I also adjusted the date/time in the conditional, but then I again changed the day from 1-31 to 01-31 to fix the sorting issue and forgot to update the date/time in the conditional overwrite.

I just updated it and pushed this change.

This morning (early) I was trying (via a theme preprocess) to override the "access" field value but the issue I found (and I could be wrong with this assumption/finding) is that the "access" variable is being preset to the day 1, month 1 of the 1970 year using whatever date/time format is been set in the field. So I'm not sure how to treat this as zero or empty value when it's returning a non-empty value `1970-01-01 00:00am`.

2022-03-25 16:12 UTC, swirtSJW commented on config/sync/views.view.user_admin_people.yml
> +            text: "{% if access == \"1970-01-1 00:00am\" %}Never\r\n{% else %} {{access}}\r\n{% endif %}"
Take a look at what I did here.
https://pr8449-ja6kwurevjxgvzdzd1c7gedcnrfhe3qd.ci.cms.va.gov/admin/structure/views/view/user_admin_people/edit/data_export_2
![image](https://user-images.githubusercontent.com/5752113/160158874-3226e8d1-9f46-42be-bcd4-04544454f5c2.png)

It uses two versions of the same field, one raw and one formatted (hidden).    The raw gives the straight unix time, so you get a 0 rather than 1970.

2022-03-25 17:14 UTC, netboss commented on config/sync/views.view.user_admin_people.yml
> +            text: "{% if access == \"1970-01-1 00:00am\" %}Never\r\n{% else %} {{access}}\r\n{% endif %}"
@swirtSJW 
Done. Pushed updated config as requested.

2022-03-25 21:00 UTC, swirtSJW approved these changes
Checks out good
![image](https://user-images.githubusercontent.com/5752113/160200068-1de6157d-3622-49e1-841d-5cce484c9135.png)

2022-03-25 21:02 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/160200287-579dca2e-56c4-4a14-a43c-1d0f76e05dc4.png)

2022-03-25 21:02 UTC, merged