VACMS-8467: Update button mixin to accept arguments.
department-of-veterans-affairs/va.gov-cms pull request #8488
Opened 2022-03-28 14:14 UTC by msbtterswrth

## Description
Closes #8467 .
 
## Testing done
Edited a node and navigated to an audit view and confirmed button styles were still functional.

## Screenshots
![image](https://user-images.githubusercontent.com/8375335/160416303-1a53725b-2e90-4640-87fb-fe8b63c4f1a3.png)
![image](https://user-images.githubusercontent.com/8375335/160416324-005ff02c-85fe-4ba3-9380-e3f89ffff2d0.png)

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As CMS user
1. Edit a node (`/node/35055/edit`) and open the rich text editor
   - [ ] Validate that button styles still work as expected
2. Then view the node and
   - [ ] Validate that button styles still work as expected
3. Navigate to a view (`/admin/content/media/pdfs`) and
   - [ ] Validate that button styles still work as expected
4. Then validate Acceptance Criteria from issue
   - [ ] Mixin is updated to include arguments for background and background hover
   - [ ] Button styles are unchanged on the frontend of the CMS

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-03-28 15:36 UTC, tjheffner commented
the mixin itself looks fine to me, just two nits: 
- the csv button is a VA.gov front-end style button that editors only see in wysiwygs / proof content, versus the cms button style that is elsewhere (button--primary / secondary etc)
- we're duplicating some mixins between `_mixins.scss` and `wysiwyg.scss`. can we simplify this? maybe move the the two that are duplicated into mixins() (va-buttons, wysiwyg-action-links) and then import mixins() into wysiwyg. i assume we have them in both at the moment so that wysiwyg content still gets the right button styles on node view pages

2022-03-28 15:51 UTC, msbtterswrth commented
Good point about that cvs button, i can switch that to a cms button for sure. 

as for the duplication, that's how I found these two files, and i'm not sure why they're duplicated, I was just going with the flow 😅. Definitely agree with you, I think we could probably do a fair bit of improvement in how this older scss was organized. If you're cool with it, I can take a stab at making that a bit smoother!

2022-03-28 15:59 UTC, tjheffner commented
> @tjheffner Good point about that cvs button, i can switch that to a cms button for sure.
> 
> as for the duplication, that's how I found these two files, and i'm not sure why they're duplicated, I was just going with the flow 😅. Definitely agree with you, I think we could probably do a fair bit of improvement in how this older scss was organized. If you're cool with it, I can take a stab at making that a bit smoother!

please do :) I cleaned up some tech debt in the switch between themes, but a lot carried over for the sake of not breaking stuff. This is a perfect time to do some cleanup imo

2022-03-28 17:26 UTC, msbtterswrth commented
ok @tjheffner I think that's much better now. I didn't want to get too deep into the other files just yet, because I think once we start getting the design system implemented we're just gonna be re-writing a bunch of this in a more extensible manner.

2022-03-28 18:28 UTC, tjheffner requested changes

2022-03-28 18:28 UTC, tjheffner commented on docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
> +@import 'tokens/mixins';
don't need to import this here, the theme's gulp setup will handle it thanks to the import order in styles.scss / other top-level scss files (not starting with a `_`)

2022-03-28 18:28 UTC, tjheffner commented on docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
> +.button--primary {
Do we actually need any of these in our stylesheet? Are there any updates here with our updated mixin from what claro's stylesheet is giving us by default? e.g. by adding `button button--primary`. 
I don't think we need to bloat our stylesheet here personally

2022-03-28 18:28 UTC, tjheffner commented on docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
> -@mixin wysiwyg-va-basic-styling {
I would double check that this mixin isn't different from the other va-basic-styling one. I think I got dinged for not including it separately before as part of the airtable issues... which is why i only mentioned the other two in my original comment. I may be totally wrong here/we're fine to delete this but confirmation would be good.

2022-03-28 18:28 UTC, tjheffner commented on docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
> +  @include button(var(--button-bg-color--primary), var(--button-fg-color--primary), var(--button--hover-bg-color--primary), var(--button--active-bg-color--primary));
this is great, thank you

2022-03-28 19:45 UTC, msbtterswrth commented on docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
> +.button--primary {
I added it here so that we can easily use it when we need to restyle buttons that don't have the appropriate classes. I could see us overriding a fair amount of contrib modules someday and i'd hate to write preprocesses for them all, but I'll let you make that call!

2022-03-28 20:02 UTC, msbtterswrth commented on docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
> -@mixin wysiwyg-va-basic-styling {
I did test this one and didn't see any issues, but we should double check for sure. Do you recall what that old issue was?

2022-03-28 20:08 UTC, msbtterswrth commented on docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
> +@import 'tokens/variables';
I tried taking this out but the colors on the buttons are unset in the editor.  I feel like the wysiwyg is compiled separately from the rest of things but I'm not sure... 
![image](https://user-images.githubusercontent.com/8375335/160478488-065f1642-a8ff-4175-a51b-afa603295ab9.png)

2022-03-28 21:34 UTC, tjheffner commented on docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
> +@import 'tokens/variables';
yeah it is compiled separately, and gets included into the ckeditor iframe as its own stylesheet. thanks for checking, we can leave the other imports here so they are set :+1:

2022-03-28 21:36 UTC, tjheffner commented on docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
> -@mixin wysiwyg-va-basic-styling {
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8121 was me reverting using the same mixin before. what the exact difference was i wish i could tell you, but i forget

2022-03-29 13:05 UTC, msbtterswrth commented on docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
> -@mixin wysiwyg-va-basic-styling {
I wonder if it's the font family line; I left that with the literal fonts rather than the font-variable. It could also be that the variables weren't compiling bc we didn't import them, since this file is compiled differently than the others.
 
```
.cke_editable {
  background: #fff;
  color: #323a45;
  font-family: 'Source Sans Pro', Sans-Serif;
  font-size: 15px;
  margin: 0.5em; /* to provide padding within ckeditor */
  max-width: 700px;

  @include va-basic-styling;
}
```

2022-03-29 15:58 UTC, tjheffner commented on docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
> -@mixin wysiwyg-va-basic-styling {
works for me, let's rock with it and if it does get reported as a regression we can revert again :shrug:

2022-03-29 16:24 UTC, msbtterswrth commented on docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
> +.button--primary {
AH I totally misunderstood what you were saying here... fixed!

2022-03-29 16:28 UTC, tjheffner approved these changes

2022-03-30 21:20 UTC, swirtSJW approved these changes
Nice work.  
+ great QA steps
+ much appreciated involving @tjheffner  in the review and appreciate all the back and forth between the two of you.  Great model.

2022-03-30 21:20 UTC, merged