VACMS-6931: move service location office hours data to new field
department-of-veterans-affairs/va.gov-cms pull request #8533
Opened 2022-03-29 20:25 UTC by JayDarnell

## Description

Closes #6931 

## Testing done

Visual Testing

## Screenshots

![Screen Shot 2022-03-29 at 4 16 42 PM](https://user-images.githubusercontent.com/21045418/160699569-adddf94d-f57d-4c1b-af2f-b89f61e5c980.png)

![Screen Shot 2022-03-29 at 4 16 52 PM](https://user-images.githubusercontent.com/21045418/160699590-d3f876e5-a39d-4bb3-946f-cefb03f07571.png)

## QA steps

- [ ] From /admin/content filter by Content type = VAMC Facility Health Service
- [ ] Open a few of these nodes and note that the new office hours widget is empty while the old table field contains data 
- [ ] Leave these tabs open and run the script (using the steps below)
- [ ] Refresh each of the tabs and be sure the data was cleanly and accurately migrated to the new field (see screenshots)  

As user with shell access:

- [ ] Execute the command: `drush scr scripts/content/VACMS-6931-switch-service-locations-office-hours.php`
- [ ] An audit file containing outliers should be created in the site's docroot folder named `office_hours_outliers.csv`

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product Support`

2022-03-30 14:46 UTC, swirtSJW requested changes
Herculean effort Jay.

Some minor changes requested,  and some suggestions for future approach that do not need to be carried out on this one.

2022-03-30 14:46 UTC, swirtSJW commented on scripts/content/VACMS-6931-switch-service-locations-office-hours.php
> +            }
Would implode work here instead of foreach?
```suggestion
            $comment = implode(' ', $sub_pieces);    
```

2022-03-30 14:46 UTC, swirtSJW commented on scripts/content/VACMS-6931-switch-service-locations-office-hours.php
> +    unset($sandbox['pids_to_update']["paragraph_{$service_location->id()}"]);
```suggestion
    unset($sandbox['pids_to_update'][_va_gov_stringifypid($service_location->id())]);
```

2022-03-30 18:31 UTC, JayDarnell commented on scripts/content/VACMS-6931-switch-service-locations-office-hours.php
> +        // If the separator count is neither 1 nor 2, treat as a comment.
Some of the content supplied fit this format <start time> <separator> <end time> <separator> <comment>

2022-03-30 18:55 UTC, JayDarnell commented on scripts/content/VACMS-6931-switch-service-locations-office-hours.php
> +      $new_value = normalize_meridiem($raw_value);
Fixing this and the other helper functions

2022-04-01 17:54 UTC, merged

2022-04-05 14:23 UTC, ndouglas commented
Prod run:

```
nathan.douglas@Belmore:~$ ssm-session vagov-prod cms auto

Starting session with SessionId: Nathan.Douglas-0a3db9b41496b8d9d
sh-4.2$ sudo su - cms
[cms@redacted cms]$ drush scr ./scripts/content/VACMS-6931-switch-service-locations-office-hours.php 
Processed Service Location paragraphs... 25 / 10718.
Processed Service Location paragraphs... 50 / 10718.
<snip>
Processed Service Location paragraphs... 10650 / 10718.
Processed Service Location paragraphs... 10675 / 10718.
Processed Service Location paragraphs... 10700 / 10718.
Service Location paragraphs updates complete. 10718 / 10718
[cms@redacted cms]$ 
```