VACMS-8549: Hide delete button for content admin role
department-of-veterans-affairs/va.gov-cms pull request #8562
Opened 2022-03-30 21:35 UTC by netboss

- Implemented removeDeleteButton() method in EntityEventSubscriber.php of va_gov_backend module to remove the "Delete" button from node/*/edit for users with the "Content admin" role.

## Description

closes #8549 

## Testing done
Visual, behat and PHPUnit

## Screenshots
![VACMS-8549-node-edit-removed-delete-button](https://user-images.githubusercontent.com/846871/160933107-35e0abaa-a595-4a87-ab6a-a37e13e309e3.png)

## QA steps

As user administrator and content admin
1. Logged-in as "Content admin" user, enter the node/edit form of any node via `/node/*/edit` to
   - [ ] Verify and confirm the "Delete" button is not available for any user logged in as "Content admin" role
2. Logged-in as "Administrator", enter the node/edit form of any node via `/node/*/edit` to
   - [ ] Verify and confirm the "Delete" button is available for any user logged in as "Administrator" role

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-04-01 21:16 UTC, swirtSJW requested changes
What you put at the top of this PR is a good first step.  
```
Implemented removeDeleteButton() method in EntityEventSubscriber.php of va_gov_backend module to remove the "Delete" button from node/*/edit for users with the "Content admin" role.
```

The problem is that it ignores most of the AC's from the issue.

 - [ ] Hide delete button for all users except admin on nodes, **blocks, taxonomy terms, media**.
 - [ ] Hide delete tab for all users except admin on nodes, **blocks, taxonomy terms, media**.


Your code seems to be intentionally limiting it to nodes.

2022-04-01 21:19 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if (!in_array('administrator', $roles)) {
We don't want to use a different check here.   Then we have a place where logic can be disconnected.  This should be using the same `->hasAdminRole(TRUE)`

2022-04-01 21:59 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  if (!in_array('administrator', $roles)) {
Ideally this code should also live in an event subscriber for hook_menu_local_task_alter but unfortunately the module does not support it yet as an event.

I created an upstream issue.  https://www.drupal.org/project/hook_event_dispatcher/issues/3273042   I don't think it is worth the lift at the moment.

2022-04-04 16:24 UTC, swirtSJW requested changes

2022-04-04 16:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +    // able to do everything else with content in VA.gov CMS.
The last part of this statement has nothing to do with your code and is declaring things your code is not doing.  
```suggestion
    // Users with any role, other than administrator role,
    // shouldn't be able to delete anything.
```

2022-04-04 16:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +      $form['actions']['delete']['#access'] = FALSE;
Since this is blindly acting on ALL forms now, we want to be a bit defensive and check to see if `$form['actions']['delete']` even exists before forcing it to exist with the #access.

2022-04-04 16:24 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  // Remove the "Delete" tab for non administrator roles in */*/edit form.
Your comments should not tell a different story than your code.   There is nothing in your code that addresses the path `in */*/edit form` so its better not to have your comment say that.

2022-04-05 13:14 UTC, netboss commented on docroot/modules/custom/va_gov_backend/va_gov_backend.module
> +  // Remove the "Delete" tab for non administrator roles in */*/edit form.
@swirtSJW 
Good morning! I thinks this is ready for review (hopefully done correctly).

2022-04-05 20:45 UTC, swirtSJW requested changes
This is looking pretty good.  It needs the previously identified issue resolved as well as some code simplification.  

If you are fully on to the other project just let me know and I can finish this up.

2022-04-05 20:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +      }
This should be just one if.   

```suggestion
    if (!$this->userPermsService->hasAdminRole(TRUE) && isset($form['actions']['delete']) {
      // Remove the delete button.
      $form['actions']['delete']['#access'] = FALSE;
```

2022-04-05 20:45 UTC, swirtSJW commented on docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
> +  public function removeDeleteButton(array &$form) {
This still needs addressing.

2022-04-06 15:26 UTC, ethanteague commented
@swirtSJW I can wrap this up

2022-04-06 18:03 UTC, swirtSJW approved these changes
This tests out great.   Tested as myself (admin) and can see delete tabs and buttons.   Tested as P. Sanders and do not have access to delete tabs or buttons across all content.

Also checked dblog and there are no related notices or errors as a result of bopping around as either user.
![image](https://user-images.githubusercontent.com/5752113/162039071-e119dcae-9405-4e74-85ce-2b115394c0c3.png)


NIce work @netboss and thanks @ethanteague  for kicking it across the finish post ... errr line ;)

2022-04-06 18:03 UTC, merged