[WIP] VACMS-5844: Install and configure Admin feedback module.
department-of-veterans-affairs/va.gov-cms pull request #8887
Opened 2022-04-25 18:00 UTC by msbtterswrth

## Description

Closes to #5811

## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As a cms user
1. Navigate to a knowledgebase page (`//help/cms-basics/how-to-log-inout`)
   - [ ] Validate that the 'was this helpful' block appears at the bottom of the page
2. Then validate Acceptance Criteria from issue
   - [ ] We can collect metrics about each node, and available to knowledge base admins
   - [ ] Additional feedback comment box is a nice to have. (available, but ux decided to disable for mvp)
   - [ ] Add helpdesk link for 'no' responses 
   - [ ] Style as secondary icon buttons (stretch)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-04-26 13:44 UTC, JayDarnell requested changes
Just a couple items that stood out to me. The rest looks good as far as I can tell. I haven't QAed this in a test environment to verify it works. I've only looked at the code thus far.

2022-04-26 13:44 UTC, JayDarnell commented on composer.json
> +        "drupal/did_this_help": "^2.0",
Was this accidentally left in? It looks like you may have been exploring both modules but only ended up needing one of them.

2022-04-26 13:44 UTC, JayDarnell commented on docroot/themes/custom/vagovclaro/vagovclaro.theme
> +  // $node = $route_match->getParameter('node');
Lines 364 and 365 look like they could be deleted altogether.

2022-04-26 13:47 UTC, msbtterswrth commented on composer.json
> +        "drupal/did_this_help": "^2.0",
great catch!

2022-04-26 15:03 UTC, msbtterswrth commented on docroot/themes/custom/vagovclaro/vagovclaro.theme
> +  // (will always return a string or null, instead of mixed or null)
I had also left in the code i changed (commented out), but Jay suggested I remove the old code. This comment refers to the change from `->getParameter` to `->getRawParameter`. Wanted to leave a note for Tanner so he knew what was going on there. Happy to take this comment out too, if you suggest.

2022-04-26 16:18 UTC, swirtSJW requested changes
Overall looks good.  Just one issue that needs addressing.

2022-04-26 16:18 UTC, swirtSJW commented on composer.lock
> +            "license": [
@msbtterswrth  Looks like you removed this from composer.json  by hand from Jay's feedback but did not run `composer remove drupal/did_this_help`
For patches you can tweak the .json by hand, but for additions removals or update you have to use composer commands to make it happen.

2022-04-26 17:06 UTC, msbtterswrth commented on composer.lock
> +            "license": [
oops!

2022-04-26 17:21 UTC, msbtterswrth commented
@swirtSJW hold on on merging this until we get the final copy from @rachel-kauff, it should be today or tomorrow, but likely past cutoff for deployment today.

2022-04-26 19:56 UTC, rachel-kauff commented
@msbtterswrth I noticed the styling looks funny for the 'submit' button for the "no / add more feedback" step. 
![Uploading Screen Shot 2022-04-26 at 12.53.15 PM.png…]()

2022-04-26 19:58 UTC, msbtterswrth commented
> @msbtterswrth I noticed the styling & alignment looks funny for the 'submit' button for the "no / add more feedback" step. <img alt="Screen Shot 2022-04-26 at 12 53 15 PM" width="1095" src="https://user-images.githubusercontent.com/41017988/165381707-d88ebabe-69a9-4b03-9edd-0450d56f6160.png">

Ah good catch @rachel-kauff, I didn't even look at those, bc we weren't using that feature but I can fix that up real quick. Same blue outline button?

2022-04-26 21:19 UTC, rachel-kauff commented
> Ah good catch @rachel-kauff, I didn't even look at those, bc we weren't using that feature but I can fix that up real quick. Same blue outline button?

Yes! Secondary button pattern, same size and all.

2022-04-26 21:23 UTC, rachel-kauff commented
@msbtterswrth You mentioned that it might be possible to link to the help desk. Does that need to get hard coded in? 
![Uploading Screen Shot 2022-04-26 at 2.22.23 PM.png…]()

2022-04-26 22:07 UTC, rachel-kauff commented
@msbtterswrth Other than the link, the microcopy is ready to go! Happy to iterate based on how we need to do the link.

2022-04-27 15:59 UTC, msbtterswrth commented
Ok @swirtSJW this is good to go!

2022-04-27 19:06 UTC, swirtSJW reviewed
Code looks good.
Getting hung up on View standards.  This view does not seem to adhere to our standards
![image](https://user-images.githubusercontent.com/5752113/165600945-85ca334d-09ed-4789-b2f1-e162eb7ef3cb.png)


The export seems to not be valid csv
![image](https://user-images.githubusercontent.com/5752113/165601028-e6609097-82f0-4e1c-9eb5-85f67229924c.png)
This is a semicolon-sv

2022-04-28 20:22 UTC, swirtSJW commented
Looks like one of the fixes didn't stick
![image](https://user-images.githubusercontent.com/5752113/165839211-eabc008a-ecde-4d26-b23b-52136ffaf0cb.png)

2022-04-28 20:24 UTC, swirtSJW commented
And this csv is still a  semi-colon-SV
![image](https://user-images.githubusercontent.com/5752113/165839492-ac3fa64b-a8df-4faf-aca2-fa6520375b95.png)

2022-04-28 21:18 UTC, swirtSJW commented
Interesting, it looks like that export button is hardcoded and not done with an attached view.   Fixing that to be a proper CSV can be ignored as it is not in our immediate  control.

2022-04-28 21:40 UTC, swirtSJW commented
I created an [upstream issue for the download](https://www.drupal.org/project/admin_feedback/issues/3277800) but I do not feel like this is anything we need to fix at this time.  We can get around it if needed just by  altering the csv import settings on our spreadsheet or by doing a find `";"` and replace `"," on the file in a text editor.

2022-04-29 16:36 UTC, swirtSJW requested changes
I think we are still missing the View standards
![image](https://user-images.githubusercontent.com/5752113/165986602-6752c2c1-b67c-45a1-bddb-0a5549dcd10c.png)
The edit should come after the title and be a button like all the rest of our admin/content/* Views
![image](https://user-images.githubusercontent.com/5752113/165986711-6b315cd4-6548-43f6-83c7-eb2013f7a1dc.png)

2022-04-29 19:08 UTC, msbtterswrth commented
My apologies @swirtSJW, I very misunderstood our earlier convo. We're all good to go now:

![image](https://user-images.githubusercontent.com/8375335/166010105-3d400a7d-6a1a-405f-a2f0-c2749392aaf5.png)

2022-04-29 21:54 UTC, swirtSJW approved these changes
Tests out good.  Thanks @msbtterswrth  that is a great addition to the site.
![image](https://user-images.githubusercontent.com/5752113/166073940-a14c51bf-d13f-47f7-906d-f15d604f14b0.png)

2022-04-29 21:59 UTC, swirtSJW commented
Test failure is an unrelated deadlock issue
![image](https://user-images.githubusercontent.com/5752113/166074197-806d2d07-7936-4632-bc90-d7bffc123c48.png)


![image](https://user-images.githubusercontent.com/5752113/166074207-41caf943-cc03-4f1f-8ee1-d17806a1fa79.png)

@ndouglas ^^ Just for your awareness for tracking failures that might be due to parallelization ??

2022-04-29 22:06 UTC, swirtSJW requested changes
This is on hold.   While we investigate that this logs an alert for every interaction with the View
![image](https://user-images.githubusercontent.com/5752113/166074880-2707bfd0-108c-4b78-a88b-6bcd6beb8db1.png)

2022-04-29 22:10 UTC, swirtSJW commented on config/sync/views.view.feedback.yml
> +            format: basic_html
I think this is the problem.  We don't have a basic_html as a format.  We need to set this to one of our existing formats

2022-04-29 22:11 UTC, swirtSJW commented on config/sync/views.view.feedback.yml
> +            format: basic_html
```suggestion
            format: rich_text_limited
```

2022-04-30 03:39 UTC, swirtSJW approved these changes
Changing the text format resolved the dblog alerts.  This is ready to go

2022-04-30 03:40 UTC, merged