VACMS-9160: Add covid status preview to facility form.
department-of-veterans-affairs/va.gov-cms pull request #9244
Opened 2022-05-26 02:20 UTC by ethanteague

## Description
closes #9160

## Testing done
Visual / behat

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/170401697-2234261e-17bb-4dc9-98a1-dbbe1bd63b0e.png)

## QA steps
**Test 1**
 - [ ] As an administrator, go to `node/1524/edit` and visually verify Guidelines intro and description below covid status radio buttons
 - [ ] Verify box is filled with text on load
 - [ ] Verify tooltip displays tooltip message on hover
 - [ ] Verify changing radio buttons changes text in tooltip box
 - [ ] Verify saving node captures changes made to covid status radios
 
 **Test 2**
 - [ ] As an administrator, go to `node/add/health_care_local_facility` and visually verify Guidelines intro and description below covid status radio buttons
 - [ ] Verify box is filled with text on load
 - [ ] Verify tooltip displays tooltip message on hover
 - [ ] Verify changing radio buttons changes text in tooltip box
 - [ ] Verify saving node captures changes made to covid status radios

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-05-26 18:09 UTC, JayDarnell requested changes
Assuming the node_link yml was not intended to be a part of this PR it should be removed.

2022-05-26 18:09 UTC, JayDarnell commented on config/sync/node_link_report.settings.yml
> +  acemapp.org
I suspect this file was added to the PR accidentally.

2022-05-26 18:13 UTC, ethanteague commented on config/sync/node_link_report.settings.yml
> +  acemapp.org
I've gotten into the habit of letting these node_link_report.settings.yml changes go in as they appear to keep things in sync / not have to worry about it in a dedicated pr. If you aren't feeling it, lemme know and I'll stop doing this / pull this out, @JayDarnell

2022-05-26 18:23 UTC, JayDarnell approved these changes

2022-05-26 18:31 UTC, merged

2022-08-18 21:45 UTC, swirtSJW commented
A bit disappointed that this was so covid specific.  The machine names and logic should not have been covid at all.