VACMS-9242 Benefits Hubs meta title length
department-of-veterans-affairs/va.gov-cms pull request #9246
Opened 2022-05-26 12:57 UTC by msbtterswrth

## Description

Closes #9242

## Testing done
manual, automatic

## Screenshots
![image](https://user-images.githubusercontent.com/8375335/170490417-c5968509-174c-49e9-ab11-af24ac73f20d.png)

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As CMS editor
1. Add or edit a Benefits Hub detail page (`node/add/page`)
   - [ ] Validate that more than 70 characters can be added to the meta title
2. Add or edit a Benefits Hub landing page (`node/add/landing_page`)
   - [ ] Validate that more than 70 characters can be added to the meta title
3. Then validate Acceptance Criteria from issue
   - [ ] Character limits on Benefits Hub Detail Page and Benefits Hub Landing Pages are set to soft limits, 70 characters, instead of hard limits.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-05-26 19:00 UTC, kevwalsh approved these changes
Other than the flag fields, this LGTM. Sitewide content team signed off on this change and its immediate impact on up to 350 Benefits Hub nodes.

2022-05-26 19:09 UTC, msbtterswrth commented on config/sync/core.entity_view_display.node.landing_page.support_services_listing.yml
> +  flag_email_node:
ah i think that must've came from main which might be more updated locally than here. Should I merge main in and see what happens, or take this out?

2022-05-27 14:40 UTC, swirtSJW commented on config/sync/core.entity_view_display.node.landing_page.support_services_listing.yml
> +  flag_email_node:
I'm looking into this.  It is coming from the messages stack but I want to make sure it is benign.

2022-05-28 01:32 UTC, swirtSJW commented on config/sync/core.entity_view_display.node.landing_page.support_services_listing.yml
> +  flag_email_node:
Yah these are benign.   The flags are disabled 
![image](https://user-images.githubusercontent.com/5752113/170804537-5d397d0e-0670-4690-86f2-2a8e9689f3a9.png)

These config will start appearing on future saves of other content types.  They are one of those configs that do not get added on config export unless there is some other change causing the content type to export.

2022-05-28 01:39 UTC, swirtSJW requested changes
Overall looks good.
We are missing a hook_update_n to clear out the data from the field storage though (assuming this field is used nowhere else).  Take a look in va_gov_db.install for examples or hit @ethanteague to show you how.

2022-05-31 19:49 UTC, ethanteague approved these changes
Looks good :+1:

2022-05-31 20:47 UTC, merged