WIP VACMS-9235 Bump drupal/slack.
department-of-veterans-affairs/va.gov-cms pull request #9265
Opened 2022-05-27 21:28 UTC by swirtSJW

## Description

closes #9235
## Testing done

## Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-06-22 03:47 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/174939398-149253a8-5239-4a26-8b6f-16c26973cf3c.png)

2022-06-22 04:04 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/174940949-b14f42d6-9f46-47a9-b809-b5b343e98200.png)

2022-06-23 13:50 UTC, swirtSJW commented
Here is a run of tests that my local CMS posted to Slack #cms-notifications.
https://dsva.slack.com/archives/CJT90C0UT/p1655931171810679

They should be going to the VA forms channel but so far our Slack bot can not post to that channel yet.

Request is here: https://dsva.slack.com/archives/CJT90C0UT/p1655467200139979

2022-06-23 14:47 UTC, swirtSJW commented
Import is still failing on the new message templates.  The only thing the three failures have in common are that they were clones of the one that is importing fine.   I am guessing cloning may be incomplete and I will  recreate them by hand.

2022-06-23 20:55 UTC, swirtSJW commented
Request for opening up the access on our slack app bot is here
https://github.com/department-of-veterans-affairs/va.gov-team/issues/43239

2022-06-24 21:37 UTC, swirtSJW commented
I triggered a rebuild to run cypress.

The failure seems unrelated
```
1) Content Release
       The content release page should normally display no in-process releases:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: 'Front end has not been built yet.' but never did.
      at Context.eval (https://pr9265-8elkd3yodgnxnr3xxaqsviripvlbcfjc.ci.cms.va.gov/__cypress/tests?p=tests/cypress/integration/behavioral/content_release.feature:72999:28)
      at Context.resolveAndRunStepDefinition (https://pr9265-8elkd3yodgnxnr3xxaqsviripvlbcfjc.ci.cms.va.gov/__cypress/tests?p=tests/cypress/integration/behavioral/content_release.feature:27189:29)
      at Context.eval (https://pr9265-8elkd3yodgnxnr3xxaqsviripvlbcfjc.ci.cms.va.gov/__cypress/tests?p=tests/cypress/integration/behavioral/content_release.feature:26510:35)
```

2022-06-25 01:47 UTC, swirtSJW commented
Second failure on the content release cypress test.
![image](https://user-images.githubusercontent.com/5752113/175753680-54f66d2a-8a17-4fe1-9878-55359a506a89.png)

2022-06-27 16:33 UTC, tjheffner requested changes
Ran through the QA steps, noticed two things. These might just be an issue with lower environment and not true blockers, but want to call it out just in case.

Messages generated for all the form actions:
<img width="1877" alt="Screen Shot 2022-06-27 at 9 20 23 AM" src="https://user-images.githubusercontent.com/11279744/175988935-3d9f444d-aa8a-4b29-87e1-5df91abecd5a.png">

One thing I found is the QA steps note the message for changed form title (4th case) under "Page title" field under the forms db data, but the message is actually triggered on the "Form title" field under the forms.

<img width="1845" alt="Screen Shot 2022-06-27 at 9 21 07 AM" src="https://user-images.githubusercontent.com/11279744/175988940-ca219467-f799-4bea-8645-8e9f09879971.png">

<img width="1845" alt="Screen Shot 2022-06-27 at 9 26 34 AM" src="https://user-images.githubusercontent.com/11279744/175989535-85feeea3-a787-40a0-bd63-2158d216ddac.png">
 The double content entry is when i edited the field noted in QA steps, then the other form title field that triggered the webhooks. Also see the "form" error noting an`Illegal choice slack in type element.` This was me clicking the link to the dblog in the qa steps... slack isn't an option in that list. Maybe because lower environment? Not really a breaking issue, message_notify seems to collect the rest of the logs but wanted to raise it just in case.

2022-06-27 16:33 UTC, tjheffner commented on docroot/modules/custom/va_gov_notifications/src/Service/NotificationsManager.php
> +  public function send($template_name, $recipient, array $values = [], $notifier_name = 'email') : bool {
love this update

2022-06-27 20:25 UTC, swirtSJW commented on docroot/modules/custom/va_gov_notifications/src/Service/NotificationsManager.php
> +  public function send($template_name, $recipient, array $values = [], $notifier_name = 'email') : bool {
Glad you like this.  It felt dirty.  Any time you have a function that broadens its scope use multiple data types it is bad....  I needed shower... but at least the name is honest  :)

2022-06-27 22:53 UTC, swirtSJW commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +      if ($this->flagger->flagFieldChanged('field_va_form_title', 'changed_title', $entity, "The form title of this form changed from '@old' to '@new' in the Forms DB.")) {
Sorry, this was my fault.  Good code, bad QA step.  I fixed. the QA step.

2022-06-28 14:32 UTC, tjheffner commented on docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
> +      if ($this->flagger->flagFieldChanged('field_va_form_title', 'changed_title', $entity, "The form title of this form changed from '@old' to '@new' in the Forms DB.")) {
all good, i wanted to make sure with 3 "title" fields on these forms. resolved!

2022-06-28 14:47 UTC, tjheffner approved these changes
LGTM!
<img width="1828" alt="Screen Shot 2022-06-28 at 7 40 55 AM" src="https://user-images.githubusercontent.com/11279744/176208655-322cf761-adc4-4a48-9836-73119f81c9d7.png">
<img width="1545" alt="Screen Shot 2022-06-28 at 7 41 52 AM" src="https://user-images.githubusercontent.com/11279744/176208666-31e82200-6165-4d46-9f2a-9b19e371e5d4.png">

The only thing I notice is that the list of messages found at either `/admin/content/message` or `/admin/content/messages` changes the logs when a field the message is referencing changes. I don't change the title of the form until the third or fourth node save, but it's changed in all messages, including the previously generated ones, when I view the list after the fact. That seems a little off to me, but definitely not your code causing it

2022-06-28 17:46 UTC, swirtSJW commented
> The only thing I notice is that the list of messages found at either `/admin/content/message` or `/admin/content/messages` changes the logs when a field the message is referencing changes. I don't change the title of the form until the third or fourth node save, but it's changed in all messages, including the previously generated ones, when I view the list after the fact. That seems a little off to me, but definitely not your code causing it

That is an interesting observation, It seems the tokens are a live connection to the referenced node rather than snapshot from when the message was created.  That will be important to keep in mind if we surface changes in a dashboard in the future.

2022-06-28 17:47 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/176248943-a27fcfab-75ef-425e-9a1c-897e17b63afa.png)

2022-06-28 17:47 UTC, merged