VACMS-9410: Clear Event CTA info when toggling states.
department-of-veterans-affairs/va.gov-cms pull request #9593
Opened 2022-06-27 18:21 UTC by dsasser

## Description

Relates to #9410

## QA steps
1) Go to /node/add/event
2) Fill out all required fields
3) Click the box for "Include registration information"
4) Select an option other than "none" for Call to action.
5) Put in a URL
6) Change the Call to Action select to "- None -"
7) Confirm that the URL is now blank
8) Select an option other than "none" for Call to action.
9) Put in a URL
10) Uncheck the "Include registration information" checkbox
11) Check the "Include registration information" checkbox
12) Confirm that the Call to Action is now set to "- None -" and the URL is empty.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

2022-06-27 19:53 UTC, ryguyk commented on docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js
> +        ctaUri.value = "";
To me, this feels more how I'd naturally think about what needs to be done:

If the toggleVal is checked, then do two things:
1. Hide elements
2. Blank out some fields

```
if(toggleVal) {
	targetRegistrationElements.forEach((element) => {
	  element.style.display = "block";
	};
  ctaUri.value = "";
  ctaSelect.value = "_none";
} else {
  targetRegistrationElements.forEach((element) => {
	  element.style.display = "none";
	};
}
```

2022-06-27 19:53 UTC, ryguyk commented on docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js
> +        ctaUri.value = "";
Or, possibly even better:

```
if(toggleVal) {
  toggleRegistrationVisibility(true);
  ctaUri.value = "";
  ctaSelect.value = "_none";
} else {
  toggleRegistrationVisibility(false);
}

const toggleRegistrationVisibility = (show = true) => {
  const displayStyle = show ? 'block' : 'none';
  targetRegistrationElements.forEach((element) => {
	  element.style.display = displayStyle;
	};
}
```

2022-06-27 20:11 UTC, swirtSJW requested changes
I added some testing steps because it seemed like a few cases were missing.   A lot of the QA steps identified did not involve saving the various permutations.   I surfaced the last one (steps 13 -20)
![image](https://user-images.githubusercontent.com/5752113/176027065-81baadd7-4d6a-4a20-9be2-8ed3484fc73d.png)

Where unchecking  the box and then saving fails form validation and the node can not be saved, but no error is visible because of the field that is failing is hidden.

2022-06-27 20:27 UTC, ryguyk commented on docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js
> +      element.style.display = elementDisplayStyle;
I like this solution. Looks great!

2022-06-28 21:04 UTC, swirtSJW requested changes
@dsasser I am seeing another issue related to the "expected behavior: When you change your mind on conditionals, they remove the other field values."   The solution right now is focussed on the CTA, but there is also this other field under the conditional that is not getting cleared out

![image](https://user-images.githubusercontent.com/5752113/176287204-aa8fc3a1-2d3c-488d-8b00-214ce3ac5786.png)

So when I save the node, that registration required is still showing.

![image](https://user-images.githubusercontent.com/5752113/176286583-85c81364-ebaa-424a-b7f3-ae7a99970aee.png)

2022-06-30 05:14 UTC, swirtSJW approved these changes
This all tests out great.  Nice work @dsasser

2022-06-30 05:15 UTC, merged