VACMS-6528: archive related services/events when a facility is archived
department-of-veterans-affairs/va.gov-cms pull request #9598
Opened 2022-06-27 21:00 UTC by JayDarnell

## Description

Closes #6528

## Testing done

Manual / visual testing

## Screenshots

![Screen Shot 2022-06-27 at 4 39 27 PM](https://user-images.githubusercontent.com/21045418/176033397-1a8aaa1e-c4b4-4feb-a98f-3f980140118d.png)

![Screen Shot 2022-06-27 at 4 51 38 PM](https://user-images.githubusercontent.com/21045418/176033546-176d0c36-0e47-4fae-b630-39716d2c0859.png)

![Screen Shot 2022-06-27 at 4 51 47 PM](https://user-images.githubusercontent.com/21045418/176033635-7fcb376c-e6cc-4096-b32f-047749b0717a.png)

![Screen Shot 2022-06-27 at 4 52 05 PM](https://user-images.githubusercontent.com/21045418/176033651-c029512f-1b34-477b-aaf4-5f58f6efdd8d.png)

## QA steps

As an admin user
1. Load the Events view /admin/content/events and filter by: Facility title contains = **Rocky Mountain** (note the total number of items)
2. Load the Bulk edit view /admin/content/bulk and filter by: Title = **Rocky Mountain** and Content type = **VAMC Facility Health Service** (note the total number of items)
3. Load the Bulk edit view /admin/content/bulk and filter by: Title = **Rocky Mountain** and Content type = **VAMC Facility Non-clinical Service** (note the total number of items)
4. Load the following VAMC Facility Node page: /eastern-colorado-health-care/locations/rocky-mountain-regional-va-medical-center
5. Edit the Facility node, change the moderation state to Archived

- [ ] Verify the facility is unpublished
- [ ] Verify the status message shows a number of additional items that were archived
- [ ] Refresh the view pages listed above and verify the items are all archived
- [ ] Open one item of each type and ensure there is a revision log message stating that the item was automatically archived when the parent facility was archived.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

2022-06-28 14:56 UTC, swirtSJW requested changes
Some changes needed.   We can kick around the idea of which module it should live in if you have other ideas.

2022-06-28 14:56 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +    if ($entity instanceof NodeInterface && $entity->bundle() === 'health_care_local_facility') {
Since this is specific to health care facilities,  should this go into va_gov_vamc instead?

I can see a case to be made for needing similiar removal for vet centers but I think that will be using different fields and may involve related outstations, mobile and caps... so I think the logic would be significantly different.

2022-06-28 14:56 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +        $query = \Drupal::entityQuery('node');
Yep gotta agree with Stan here.  Pass this in as argument defined in the services yml

2022-06-28 14:56 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +              $updated[$node->bundle()] += 1;
minor: 
```suggestion
              $updated[$node->bundle()]++;
```

2022-06-28 14:58 UTC, swirtSJW commented
This PR should also update the facility removed runbook template to remove the related manual steps.

2022-06-28 15:02 UTC, ethanteague commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +    if ($entity instanceof NodeInterface && $entity->bundle() === 'health_care_local_facility') {
Not to pile on here, but all of this logic in entityUpdate (where ever this subscriber hook ultimately lives) should probably be called from a discrete function, e.g.: 
```
public function entityUpdate(EntityUpdateEvent $event): void {
  $entity = $event->getEntity();
  someDiscreetFunctionThatDescribesWhatYouAreDoing($entity);
}

2022-06-28 18:33 UTC, JayDarnell commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +    if ($entity instanceof NodeInterface && $entity->bundle() === 'health_care_local_facility') {
@ethanteague what is the main motivation behind moving the logic into a separate function call?

2022-06-30 03:50 UTC, swirtSJW reviewed
Some suggestions to make this a little clearer and re-useable when we tackle this for vetcenters.

2022-06-30 03:50 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +          ->condition('moderation_state', 'published');
I think we want this to be anything but 'archived'   If we just limit it to published, we will be creating orphans for anything that is in draft.

2022-06-30 03:50 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +              // Make this change a new revision.
minor:  If the functions being called are all well named like these are, the comments aren't adding much value. 
example: `// Make this change a new revision.`   is not much improvement over `->setNewRevision(TRUE);`

Almost all of these node operations are well named and don't benefit from the comments.

2022-06-30 03:50 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +          // Status message so editor knows the extent of the changes.
This is a good comment because it explains why. and is not repeating what the code tells.

2022-06-30 03:50 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +        }
This is a good hunk to move into its own method
something like ->isBeingArchived($entity);
Then your "if" higher up becomes
if (isset($entity->original) && ($entity->original instanceof NodeInterface) && $this->isBeingArchived($entity)) {

2022-06-30 03:50 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +    $this->archiveRelatedFacilityContent($entity);
Since this method is specific to health care facilities, it would be good to make this more transparent.
```suggestion
    $this->archiveRelatedHealthFacilityContent($entity);
```

2022-06-30 03:50 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +  protected function archiveRelatedFacilityContent(EntityInterface $entity): void {
```suggestion
  protected function archiveRelatedHealthFacilityContent(EntityInterface $entity): void {
```
If in the future we make this more broad, we can make the name more generic, but for now it is pretty specific.

2022-06-30 03:50 UTC, swirtSJW commented on docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
> +              $node->save();
This is all likely to be re-used when we do vet centers, so it could be moved to method  like
archiveNode($node);

2022-06-30 15:43 UTC, kevwalsh commented
Now that i see it in practice, I worry that auto-archiving events may be too opinionated. Events are not really "child" content in the same way that facility services are.

To me, that step is really about reducing broken links, but i think we should worry about that in a different way, which Sitewide CMS team is thinking about in the broader archiving workflow (alerting editors to possible broken links that can happen if they archive a node). And If a redirect is in place for this facility URL, is it really so bad that an event (whether future or past) stays published with a reference to a closed facility?

2022-06-30 15:50 UTC, swirtSJW commented
> is it really so bad that an event (whether future or past) stays published with a reference to a closed facility?

It would annoy me if I were looking at an event and then discovered it only to get redirected to the facility that may not be the actual location.    Creates a recipe for a disgruntled veteran.

2022-06-30 15:58 UTC, JayDarnell commented
It is important to note that prior to this update our manual steps included archiving any events for the facility in question so this automatic archiving still accomplishes that same step, just without the manual work.

2022-06-30 19:02 UTC, swirtSJW approved these changes
This tests out great
![image](https://user-images.githubusercontent.com/5752113/176757385-279108b0-5baa-41d5-af19-63ccdbc97098.png)

![image](https://user-images.githubusercontent.com/5752113/176757399-7c212610-e9b8-4deb-a43d-1ce82f13b78d.png)


Also checked recent log messages and no bad notifications or errors found.

Nice work @JayDarnell

2022-06-30 19:03 UTC, swirtSJW commented
![image](https://user-images.githubusercontent.com/5752113/176757586-1e287299-7cc4-4e03-a94a-4325b92f037c.png)

2022-06-30 19:03 UTC, merged